### ISSUE TITLE
Better log messages on cms.Page

### ISSUE THREAD

**Issue by ojii** [divio/django-cms#1198]
The log for `cms.Page` should also contain messages when fields that are on `cms.Title` change or plugins are added, removed or modified.

**Comment by mkoistinen** [comment]
I see that @digi604 says this is for 3.1, yet @yakky has been marking it for 3.0.x. Has this actually been addressed already and forgot to mark this as closed, or did we just overlook it for the 3.0.7 release? (Also tagging @ojii here).

**Comment by yakky** [comment]
It's been marked as 3.0.x sooo long ago but actually forgotten.
Let's push this post 3.1, if nobody feels compelled to work on it for 3.1

**Comment by mkoistinen** [comment]
+1

**Comment by FinalAngel** [comment]
@yakky @mkoistinen do we still want to plan it in?

**Comment by czpython** [comment]
While this is a nice to have, I think it falls into the feature category.
Will close, if anything we can continue the discussion on the developers group.
