### ISSUE TITLE
Pages in different Sites

### ISSUE THREAD

**Issue by evildmp** [divio/django-cms#1229]
It seems to me that the mechanisms for getting a Page's URL don't interact with the sites framework as it should.

Suppose you have two Sites on different domains, first-domain.com and second-domain.com.

Now in one Page belonging to the Site first-domain.com, you insert a link to a Page on SIte second-domain.com.

In such a case, the URL that is generated can't be only the /path/to/page - it needs to be: second-domain.com/path/to/page.

If I understand this correctly, what is required is something that compares the site_id of the Page we are in with the site_id of the Page we want to get to - and if they are different, prepends the Site.domain to its URL.

**Comment by czpython** [comment]
This looks like it's fixed.
