### ISSUE TITLE
Uppercase in page slugs

### ISSUE THREAD

**Issue by alesdotio** [divio/django-cms#1324]
Page slugs get lowercased upon saving, so there is no way to have a URL with uppercase letters. Consequentially, URLs with uppercase letters always result in a 404.

Possible solutions:
- accessing a URL in uppercase, displays the page with the corresponding lowercase slug,
- or, allow saving slugs in uppercase.

**Comment by mfcovington** [comment]
Redirecting to lower-case slugs would be great.

**Comment by czpython** [comment]
I'm in for redirecting to lower-case url.
/cc @divio/django-cms-core

**Comment by evildmp** [comment]
**Generated slugs** are lower-cased by default (in both Django, and django CMS). This is good behaviour.

**Manually-edited slugs** are saved as lowercase in django CMS. I'm not really decided on whether this is good behaviour or not, but I think it's probably a good choice. It's a nicer user-experience and will save people from themselves, but denies them some power and functionality.

 Our **URLconfs** are case-sensitive. This is probably good behaviour, but doesn't make much sense if you can never arrive at a URL with a slug with uppercase characters in it. If we are going to disallow uppercase characters in slugs, we may as well redirect from uppercase to lowercase when handling them.

Note that the Django Project has discussed this issue and decided that Django should have case-sensitive slug handling.

**Comment by mkoistinen** [comment]
+1 for redirecting.

**Comment by johann-abraham** [comment]
+1 for redirecting upper case to lower case urls
