### ISSUE TITLE
Page permission inconsistencies

### ISSUE THREAD

**Issue by kux** [divio/django-cms#1430]
When changing a user using 'Change User (page) ' form, you can set the user's 'Add', 'Change' , 'Delete' Page permissions.
In the meanwhile, the 'Page permissions' formset on any page has the following checkboxes: 'Can edit', 'Can add', 'Can delete' which overlap with the functionality of the three permissions above.

The problem with this is that you can make strange combinations:
* disable 'Add' on the 'Change User (page); form, but enable 'Can add' on a page's 'Page permissions' formset
   => the user will continue having the 'Add child' button active on the 'actions' column in the page hierarchy webpage, even though 'Add' is disabled for that user. I would have expected that the user has a certain permission if the permission is ticked in both 'User (page)' form and 'Page permissions' formset

* disable 'Delete' on the 'Change User (page); form, but enable 'Can delete' on a page's 'Page permissions' formset
   => the user will NO LONGER have the 'Delete' button active on the 'actions' column in the page hierarchy. This behavior is as I would have expected, but it's inconsistent with the behavior above.

I think the best solution would be:
* If the user doesn't have a page permission set in the 'Change user (page)' form, then simply disable the corresponding tickbox in a page's 'Page permissions' formset

**Comment by FinalAngel** [comment]
Closed in favour of #4598
