### ISSUE TITLE
Re-Thinking Apphooks (3.0 Feature Proposal)

### ISSUE THREAD

**Issue by ojii** [divio/django-cms#1498]
So I had this idea on how we can make apphooks suck less. A way we can kill the dreaded "restart server on apphook change".

Here it goes.

Instead of attaching an apphook, which potentially adds menu nodes, why not attach **views** to pages? And instead of creating menu nodes, an apphook creates **pages**.

We'd provide an easy way to sync models with pages.

Apphooks tell which parts of the URL we should pass to the attached views.

It could look a little like this:

```python

class AwesomeTeamApphook(Apphook):
    def setup(self):
        page = self.attach('myapp.views.index')
        self.attach_model(
            'myapp.views.detail', 
            queryset=TeamMember.objects.filter(public=True),
            parent=page,
            args=re.compile('/(?P<slug>[\w\d-]+)/$'),
        )
```

When the apphook is attachd, it attaches the view ``'myapp.views.index'`` to the page the apphook is on. It gets no extra arguments. It creates a page under that page for each published ``TeamMember``. When the page is called, it extracts the slug from the last bit of the URL. When a ``TeamMember`` is saved/deleted, it creates/removes pages accordingly and attaching the ``myapp.views.detail`` view to them.

On rendering, maybe instead of ``{% placeholder %}`` there could be a ``{% view_content %}`` or similar tag to render the bits from the view. Or alternatively it just uses the view to render the page.

I have no idea whether this is feasible, just wanted to share a crazy idea I had.

**Comment by evildmp** [comment]
This is fixed in 3.2
