### ISSUE TITLE
show_menu_below_id doesn't work for pages without softroot if it is called from subpage of a softroot

### ISSUE THREAD

**Issue by vstoykov** [divio/django-cms#1546]
I found problem with this. Lets explain with example tree structure:
- home - ( id: home )
  - page in main tree 1
  - page in main tree 2
  - page in main tree 3
- top-menu - ( id: top_menu ) ( softroot )
  - page in top menu 1
  - page in top menu 2
  - page in top menu 2

In the template I have:
{% show_menu_below_id "top_menu" 0 1 1 1 "top_menu.html" %}
and
{% show_menu_below_id "home" 0 1 1 1 "menu.html" %}

When I'm in some of the main pages the "top_menu" is rendered, but when I'm in some of the pages in top menu the main menu is not rendered. I understand that when I am on page that is inside a softroot I can't see pages that is outside this softroot. For default menu this is Ok, but when I want pages bellow id I actually want theese pages.

I'm using the latest stable release (2.3.4)

**Comment by FinalAngel** [comment]
closed in favour of #4597

**Comment by vstoykov** [comment]
If this issue is related to this https://github.com/divio/django-cms/issues/3504 (which is already fixed)?

**Comment by FinalAngel** [comment]
very much likely @vstoykov /cc @divio/django-cms-core
