### ISSUE TITLE
cms_page level field grows to 4294967295 and kills site.

### ISSUE THREAD

**Issue by jessenash** [divio/django-cms#1633]
This is a bit of a noodle scratcher. Something indirect happens to the cms_page table in the database, loading up the 'level' field to it's highest possible integer, then crashes. I can't seem to find the cause, but I'm able to clear the error by replacing that funny value with something normal like 0, 1 or 2. Here's part of the dump. Any feedback would be appreciated.

Django Version:
1.4.2

Exception Type:
OverflowError

Exception Value: 
cannot fit 'long' into an index-sized integer

Exception Location:
/home/ubuntu/.virtualenvs/h4h/lib/python2.6/site-packages/cms/forms/utils.py in update_site_and_page_choices, line 50

Python Executable:
/usr/bin/python

Python Version:
2.6.6

**Comment by evildmp** [comment]
Now that we no longer use MPTT, this no longer applies either.
