### ISSUE TITLE
concurrency issues with mptt when creating root pages

### ISSUE THREAD

**Issue by kux** [divio/django-cms#1634]
Reproduced with django-cms 2.3.3

Steps to reproduce:
1. Have multiple users add new root pages and press the 'save' button at the same time
2. Check the cms_page.tree_id

Expected:
Different tree_ids

Actual:
All pages have the same tree_id

I also reproduced this by writing a new unit test:

    class PagesTestCase(CMSTestCase):

        def test_concurrently_create_pages(self):
            """
            Test that a page can be created via the admin
            """
            class PageCreatingThread(threading.Thread):

                def run(_self):
                    page_data = self.get_new_page_data()
                    response = self.client.post(URL_CMS_PAGE_ADD, page_data)

            superuser = self.get_superuser()
            threads = []
            num_concurrent_req = 5
            with self.login_user_context(superuser):
                for _ in xrange(num_concurrent_req):
                    new_thread = PageCreatingThread()
                    new_thread.start()
                    threads.append(new_thread)
                for thread in threads:
                    thread.join()
                # all previous created pages need to have different tree_ids
                self.assertEqual(len(set(p.tree_id for p in Page.objects.all())), num_concurrent_req)

For the test to work you also need to change

    class CMSTestCase(testcases.TestCase):

to

    class CMSTestCase(testcases.TransactionTestCase):

The problem is in mptt.managers._get_next_tree_id and all it's callers:

    ./managers.py:212:            setattr(node, self.tree_id_attr, self._get_next_tree_id())
    ./managers.py:417:    def _get_next_tree_id(self):
    ./managers.py:514:            new_tree_id = self._get_next_tree_id()

**Comment by evildmp** [comment]
Fixed in 3.1 with MPTT removal.
