### ISSUE TITLE
Server error message when runserver

### ISSUE THREAD

**Issue by jimpsterbasic** [divio/django-cms#1675]
![Captura de pantalla de 2013-03-26 21:37:59](https://f.cloud.github.com/assets/3980134/306278/a1d084b8-9676-11e2-9010-125a487cf125.png)
When I run the tutorial given to configure django-cms, on 127.0.0.1:8000 on web browser shows the following message: "A server error occurred.  Please contact the administrator." 
I used sqlite.

What can be the problem?

**Comment by jhonnrock** [comment]
have the same problem how to solve ??

**Comment by yakky** [comment]
@jhonnrock please provide more information: django and django CMS versions, project settings and traceback
