### ISSUE TITLE
Placeholders case sensitive - why?

### ISSUE THREAD

**Issue by Laboratory-yorcc** [divio/django-cms#1745]
I can not understand why placeholders case sensitive? This can lead to errors in case insensitive db.

**Comment by mkoistinen** [comment]
I'm not sure we support any case-insensitive DB backends, but, it would be a good patch anyway for convenience in using the CMS_PLACEHOLDER_CONF.

**Comment by czpython** [comment]
Closing as this fits our feature request criteria.
If you're still interested in this feature, please create a topic in the [Developers Mailing List](https://groups.google.com/forum/#!forum/django-cms-developers).
