### ISSUE TITLE
Placeholder rendering broken in 2.4.0?

### ISSUE THREAD

**Issue by alsoicode** [divio/django-cms#1750]
Hello everyone,

I'm experiencing some odd behavior with Placeholder fields outside of the CMS. I simply can't get {% render_placeholder [instance].[placeholder_field] %} to work in 2.4.0.

I can take exactly the same model and render the placeholder field just fine in 2.3.6.

Has anything significantly changed regarding placeholder rendering?

Thanks,
Brandon

**Comment by czpython** [comment]
Closing as 2.4.x is no longer maintained.
Please use the latest Django CMS.
