### ISSUE TITLE
Don't invalidate menu_cache on Page changes

### ISSUE THREAD

**Issue by benliles** [divio/django-cms#1774]
The menu cache currently gets cleared when pages are changed or deleted by connecting to the pre_save and post_delete signals.

This is an expensive operation when a site is large and there are timeouts on the cache to handle flushing these changes in an appropriate amount of time.

**Comment by FinalAngel** [comment]
closed in favour of #4597

**Comment by czpython** [comment]
Closing for new ticket https://github.com/divio/django-cms/issues/6298
