### ISSUE TITLE
Document that variable extend nodes are not supported in cms templates

### ISSUE THREAD

**Issue by tobiasfuhlroth** [divio/django-cms#1847]
The limitation of the placeholder scanner to not support variable extend nodes should be documented.

Edited by ojii. Original content: (Support for {% extends variable %} in Template Inheritance (Placeholder Detection))

There is a comment in the function `_extend_blocks` in cms/utils/plugins.py:19 that states explicitly that this is not supported: # we don't support variable extensions

Before further investigation of this topic i would like to ask if there was any specific reason behind this decision.

Supporting this would be nice in situations like this:
{% extends request.is_ajax|yesno:"site_base-ajax.html,site_base.html" %}

**Comment by FinalAngel** [comment]
@yakky is this still relevant?

**Comment by yakky** [comment]
@FinalAngel yes, it's still relevant. No planned work on this, though

**Comment by diegoponciano** [comment]
I created a template using a variable extend node, with a context processor like `CMS_TEMPLATE`.  
My page rendered with just the static placeholders, so I stumbled upon this.  
I then tried commenting out the `if is_variable_extend_node` line, and got a `TemplateSyntaxError` saying the extends tag is empty.  
Any tips? Maybe I should try a different approach?
