### ISSUE TITLE
language_chooser doesn't take `SITE_ID` into account

### ISSUE THREAD

**Issue by Bouke** [divio/django-cms#1873]
in `menus/templates/menu/language_chooser.html` all languages are fetched:

```
{% get_available_languages as languages %}
```

However, using `CMS_LANGUAGES` I have defined a mixed set of languages depending on the `SITE_ID`. This setting should be taken into account for creating the language chooser, I suppose?

**Comment by FinalAngel** [comment]
Closed in favor of #4597
