### ISSUE TITLE
Warn users when they try to visit a page that's not available in their preferred language

### ISSUE THREAD

**Issue by dialelo** [divio/django-cms#1950]
It's considered a good practice to warn the user when she tries to visit a page
that's not translated to her preferred language. The `CMS_LANGUAGES` setting
allows you to fallback to another version of a page instead of redirecting you
to the home when the aforementioned page it's not available in the language you
prefer.

My suggestion is to make it possible to specify a message to be shown whenever
the we fallback to the page in another language, something along the lines of:

>The page that you requested is not available in your {preferred_language}, you
>can read it in {available_languages}.

We can leverage `django.contrib.messages` for this.

Let me know what you think and I'd be more than happy to work on this myself,
it shouldn't be too difficult and it's a little usability improvement.

**Comment by czpython** [comment]
Closing as this fits our feature request criteria.
If you're still interested in this feature, please create a topic in the [Developers Mailing List](https://groups.google.com/forum/#!forum/django-cms-developers).
