### ISSUE TITLE
Add support for touch devices

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#2169]
On touch devices most of the toolbar functions are not available.

This issue is meant to track every touch-related issue and their solution.

ATM not working:

tested on stock Android 4 browser / Safari on iOS 5.1.1
 * [ ]: Drag and drop plugins in a placeholder
 * [ ]: Drag and drop plugins between placeholders
 * [ ]: Drag and drop plugins from the clipboard
 * [ ]: Editing plugin from the **content** mode

Solving:

 * [ ]: Toobar items selection (on iOS); should be fixed by #2168 

Fixed:

**Comment by FinalAngel** [comment]
Added support in 3.2 :)
