### ISSUE TITLE
Thoughts on a dedicated admin

### ISSUE THREAD

**Issue by patrick91** [divio/django-cms#2268]
Hi all, first of all I'd say that I'm not sure if this discussion belongs here or in the dev's mailing list. 

I'm starting to use djangocms in the company where I work in, but I feel a bit unhappy with the lack of a dedicated admin. We used to use WordPress (or SPIP) for our clients and they all have a dashboard that is nice to see and easy to use (at least for WordPress).

Since I'm going to build my company's website and blog with djangocms I'm wondering if there's a way to have a nice admin.

For me the django admin looks inflexible and outdated. I saw [django-admin-tools](https://bitbucket.org/izi/django-admin-tools/wiki/Home) which is cool, but not yet sure if it is what I need.

Also I saw [django-admin2](https://github.com/pydanny/django-admin2) which looks like what I need, and it is what I, probably, will use.

That being said, I'd like to create a sort of admin for djangocms, an admin that has all the feature that I need at this time. I'd start this as a side project, not as a fork of django cms itself.

Some of the features I need at this moment (feel free to add more):

- Dashboard with the possibility to have widgets
- Possibility to show only some models (also based on user permissions)
- Configuration section

What do you think?

**Comment by evildmp** [comment]
Closing this as the admin and frontend editing have both been vastly improved in 3.2.
