### ISSUE TITLE
Unpublish Page

### ISSUE THREAD

**Issue by alanrhannah** [divio/django-cms#2275]
Using django-cms v 2.3.5 

I am having issues with my pages still being publicly visible, despite the page status being updated to unpublished. 

I have verified the page published attribute updates correctly in the database via both mysql and the python interpreter. When the page is refreshed after updating, the edit page form shows the correct value. However, the page is always visible (for non-logged in users). 

Have you got any pointers as to why this might be happening? Is there something I have missed?

**Comment by evildmp** [comment]
I hope you got to the bottom of this. We're no longer developing 2.4, so I am going to close this issue.
