### ISSUE TITLE
Weird rendering

### ISSUE THREAD

**Issue by TheDeadOne** [divio/django-cms#2282]
Almost a blank template
![base](https://f.cloud.github.com/assets/5821459/1444614/0cf24258-420d-11e3-9b94-0e8c30f99c84.jpg)
rendering to
![wut777](https://f.cloud.github.com/assets/5821459/1444617/25091ab0-420d-11e3-9673-67fce92467d2.jpg)

Why title tag in the body and what for empty string?

Sorry for my terrible english.

**Comment by czpython** [comment]
Closing as 2.4.x is no longer maintained.
