### ISSUE TITLE
Publishing pages in front end causes messages build-up

### ISSUE THREAD

**Issue by tomds** [divio/django-cms#2307]
Django CMS version: 2.4.3

When you publish a page using the front-end toolbar, it uses Django's messaging framework to create a message. However, if your page template doesn't look for and display messages, they build up over time, and then when you go to the Django admin later on, you get a huge backlog of messages.

It would be nice to have a setting to choose whether messages are generated when publishing via the toolbar (`False` by default), so the system doesn't silently pile up messages in the background.

**Comment by czpython** [comment]
I think the implementation would be more complex than what it solves because it's just target publishing
and messages come through various actions.
