### ISSUE TITLE
Page permissions don't seem to work for large user bases...

### ISSUE THREAD

**Issue by thebjorn** [divio/django-cms#2321]
Eg. in the page admin, a drop-down list of all users is created, and when you have 10000 users that takes a long time (5+ secs to display admin on our production server).

Publishing a page takes from 15sec and up (often over 30secs).  Our end-users are complaining.. loudly.  

I've tried switching from disk cache to django-redis-cache, without much effect, however I did notice (through the redis-cli monitor command) that when publishing a page, django-cms proceeded to delete (mostly non-existing) permission cache keys. Again, for 10+K users, one-by-one.

I don't know if it is relevant, but we only have 374 pages over 5 sites.

I'd love to be able to fix this myself, but I'm not even sure where to start looking.  Any advice would be greatly appreciated.

**Comment by thebjorn** [comment]
Has this been fixed (or just closed)?  
ps: the raw-id fix fixes the admin drop-down list, but not the user-by-user clearing of cache keys.

**Comment by FinalAngel** [comment]
@thebjorn we gathered in #4598
