### ISSUE TITLE
`cms_placeholder-overlay` is pushed down by `margin-top` on the body

### ISSUE THREAD

**Issue by mightyiam** [divio/django-cms#2348]
Version `2.4.3`.

![screenshot from 2013-11-23 15 07 44](https://f.cloud.github.com/assets/635591/1606472/30e83d56-5442-11e3-8e61-b59fa4112f00.png)

The `cms_placeholder-overlay` gets pushed down because there's `margin-top:43px;` on the `body`.

I work around by `#cms_placeholder-overlay{margin-top:-43px;}`.

**Comment by FinalAngel** [comment]
This has been resolved in the 3.x release
