### ISSUE TITLE
Using placeholder with name of "title" causes http 500 when attempting to "Add Plugin" from admin page

### ISSUE THREAD

**Issue by dkwestbr** [divio/django-cms#2439]
I added a placeholder to one of my html templates.  I have many other placeholders which appear to work fine.  But, when I create a placeholder with the name "title" it becomes impossible to add a plugin.  Example:

```
<!-- Inside my html template -->
<title>{% placeholder title %}</title>

```

The placeholder shows up just fine in the admin page, but when I attempt to add a plugin (any plugin), django-cms throws an http 500.  I debugged this a little bit and it appears that the post in javascript - which results from clicking "Add Plugin" - attempts to perform an ajax call in line 21 of plugin_editor.js .  For some reason, when the plugin has a name of "title", the placeholder_id argument for the http post resolves to Null.  It is initialized on line 13:

```
var placeholder_id = $(this).parent().parent().data('id');
```

Simply changing the plugin name from "title" to "meta-title" (or anything else for that matter) appears to resolve the issue.

My system info:

Python 2.7.5
Django==1.5.5
PIL==1.1.7
Pillow==2.2.1
South==0.8.2
django-classy-tags==0.4
django-cms==2.4.3
django-i18nurls==0.7
django-mptt==0.5.2
django-phonenumber-field==0.2a3
django-picklefield==0.3.1
django-sekizai==0.7
easy-thumbnails==1.4
html5lib==1.0b3
phonenumbers==5.9.1
six==1.4.1
wsgiref==0.1.2

**Comment by czpython** [comment]
Unable to reproduce on 3.2.x
Please use the latest Django CMS.
