### ISSUE TITLE
Menus with custom, specified pages

### ISSUE THREAD

**Issue by mightyiam** [divio/django-cms#2521]
Currently, the various menu tags offer some customization ability.

It would be nice to be able to use the `show_menu` tag to render a menu of a number of specifically defined pages.

I would imagine this to be using `page_lookup` arguments, like so:

```
{% show_menu 0 100 0 100 "home" "about" "contacts" %}
```

This would create a menu that has those three pages.

I've provided this outcome, by supplying a custom template to the `show_menu` tag and it's contents are:

```
{% load menu_tags %}
{% for child in children %}
{% if child.attr.reverse_id == "about" or child.attr.reverse_id == "home" %}
<li>
    <a class="{% if child.selected %}selected{% endif %}{% if child.ancestor %}ancestor{% endif %}{% if child.sibling %}sibling{% endif %}{% if child.descendant %}descendant{% endif %}" href="{{ child.attr.redirect_url|default:child.get_absolute_url }}">{{ child.get_menu_title }}</a>
</li>
{% endif %}
{% endfor %}
```

**Comment by ldgarcia** [comment]
+1

**Comment by FinalAngel** [comment]
Collected in #4597
