### ISSUE TITLE
switch to a standards compliant versioning scheme (NormalizedVersion)

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#2544]
Use version strings that are compatible with NormalizedVersion (http://www.python.org/dev/peps/pep-0386/#normalizedversion)

To test if the version string is compatible, use ``verlib`` (``pip install verlib``)

```python
from verlib import NormalizedVersion as V
```

Our current version for beta versions (``3.0.0.beta3``) does not follow it correctly. Instead the correct notation should be used: ``3.0b3``.

I also propose following the following version scheme for development snapshots: ``3.0b4.dev1``, ``3.0b4.dev2`` and include the git commit hash inside ``__init__.py`` to make it easy to verify what version of the code is in a development package.

Also ``3.0.0`` is not strictly correct. It should be ``3.0``.

Will make a pull-request.

**Comment by yakky** [comment]
Closing this: we've setup a PEP440 versioning scheme
