### ISSUE TITLE
save full plugin name instead of just class name

### ISSUE THREAD

**Issue by digi604** [divio/django-cms#2562]

**Comment by stefanfoulis** [comment]
The reason for this change is to avoid name clashes in different apps.

Currently it is not possible for multiple apps to register a plugin with the same class name. The idea is to prefix the plugin with a full class prefix of the module where the plugin resides.
Additionally it should be possible to override the value on the plugin class.

Some relevant code points:

Where the value is saved on the plugin model in https://github.com/divio/django-cms/blob/3.0.12/cms/models/pluginmodel.py#L77

It is extracted from the plugin here when it is registered to the pool: https://github.com/divio/django-cms/blob/3.0.12/cms/plugin_pool.py#L99

Here the value saved on the plugin model is used to fetch the plugin: https://github.com/divio/django-cms/blob/3.0.12/cms/plugin_pool.py#L254-260

**Comment by czpython** [comment]
Closing as duplicate of https://github.com/divio/django-cms/issues/462
