### ISSUE TITLE
Feature Request - Toolbar - Ajax response

### ISSUE THREAD

**Issue by leesolway** [divio/django-cms#2564]
It would be nice if the toolbar method 'add_ajax_item' had a way to pass feedback to the user.. This has already been implemented in case of an error (as shown below), however i can not see a way to achieve this for other use cases (such as user feedback confirmation):

There is a callback method however i do not see how this could be passed from add_ajax_item.

'error': function (jqXHR) {
    that.showError(jqXHR.response + ' | ' + jqXHR.status + ' ' + jqXHR.statusText);
}

**Comment by czpython** [comment]
@vxsx anything to add?

**Comment by JustDevZero** [comment]
Is this solved in 3.6 or 3.7? Because I don't find where from 3.4...

**Comment by Aiky30** [comment]
@leesolway @JustDevZero Is this still a valid issue?

I can see that there is the ability to add the yes / no feedback as FinalAngel mentions above. 

If this is still a valid issue, what would be a use case / scenario of how such a feature should work?
