### ISSUE TITLE
Can't set up content editor properties properly.

### ISSUE THREAD

**Issue by nagyv** [divio/django-cms#2618]
I've already tried several different setups, but neither works. 

- Can not get the menu strucutre listed with restricted users
- Can not edit text plugins (and only text plugins)

See the attached screenshots.
![kepernyofoto 2014-02-11 - 13 43 11](https://f.cloud.github.com/assets/126671/2136892/b291a95c-931a-11e3-86d4-86a062639451.png)
![kepernyofoto 2014-02-11 - 13 47 21](https://f.cloud.github.com/assets/126671/2136893/b2927f76-931a-11e3-9741-b90febcf19d8.png)

**Comment by evildmp** [comment]
Closing because no further information is available and this doesn't seem to be an issue generally.
