### ISSUE TITLE
TEMPLATE_STRING_IF_INVALID setting throws error in traversing from page-list to page item

### ISSUE THREAD

**Issue by ramandv** [divio/django-cms#2676]
Page list [http://localhost:8000/en/admin/cms/page/]  url lists the items with invalid anchor url
[http://localhost:9000/en/admin/cms/page/INVALID%20EXPRESSION:%20url7/]

It is not critical, as it will be used only in development settings. But it might confuse the newbies, when they are trying out.

**Comment by czpython** [comment]
Looks like this is fixed on the latest CMS 3.2.x
