### ISSUE TITLE
multiple PlaceholderField base on a template

### ISSUE THREAD

**Issue by avoine** [divio/django-cms#2738]
I'm trying to think about what it would take to add the "dynamic" template
scanning fonctionnality of the Page model to an outside models.

PlaceholderField is great if you have only a few placeholder that
you want to add and if you know there names in advance.

So here's what I come with so far:

A model mixin that would:
- Add a ManyToManyField field named placeholders like for the Page model.
- That would check for a template_name attribute to the class.
- And that would call rescan_placeholders() or listen to the update_placeholders signal.
- Modify PlaceholderAdmin to grab and display those changes like PageAdmin would do.

What do you think?

**Comment by FinalAngel** [comment]
@yakky @mkoistinen any way you see how to achieve it?

**Comment by czpython** [comment]
Hello,
I'm closing this as it pertains to a feature request.
If you're still interested, please submit a new ticket in our [developers google group](https://groups.google.com/forum/#!forum/django-cms-developers).
