### ISSUE TITLE
add option for opening menu item in new tab/window

### ISSUE THREAD

**Issue by daegun** [divio/django-cms#2758]
Feature request:

I'm not sure if this exists already, but it would be cool to supplement the navigation with an additional page attribute that lets the page designer choose if that menu item should be opened in a new window or tab.

i.e. this might involve adding another field to the NavigationNode, which then can be called in the menu.html template.

**Comment by FinalAngel** [comment]
Any menu item can now be opened through CTRL/CMD + click in a new tab or SHIFT + clik in a new window in 3.2
