### ISSUE TITLE
Proposal to improve the UX of 'redirect to' advanced page option.

### ISSUE THREAD

**Issue by johnraz** [divio/django-cms#2785]
( this topic was initially raised in this PR #773, this issue is here to summarize what has been discussed there and try to trigger a design decision before implementing )

## What we currently have:
A bare text input in the advanced settings of a page where we can type the url to redirect to.

## What we would like to achieve:
* A simpler way for the user to be able to pick an existing cms page to redirect to, without having to know its url.
* A straightforward way to redirect to the first children (most often for non-page root menu entries)

### To address the first point:

We could implement an input pimped with javascript (let's call it smartlink input) that would allow to pick a page from a list of existing page or to write the url manually. 

Picking a page from the list would fill the input with the relative url to the page. 

The list should only display pages in the same language as the currently edited page language. 

The ideal would be to make this field reusable by plugins.

We should also be careful to chase performance issue in case of big page trees.

To expand on the smartlink input's behavior, quoting @ojii from #773 's discussion:
> Example

> We have the following tree:

> Home: /
> Downloads: /downloads/
> Documentation: /documentation/
> When I type "h" I get "Home (/)" as an option to select from. When I continue with "http" it doesn't show anything in the dropdown, expecting me to just type a URL.

> If I type "/do" it should give me "Downloads (/downloads/)" and "Documentation (/documentation/)" as options or just let me type any relative URL, like "/doughnuts/".

### To address the second point (first child redirect):
We could simply add a checkbox next to the smartlink input. 

When checked, the smartlink input would be made readonly and filled with the relative url of the first child. 

If no child exists, trying to check the checkbox should trigger a warning.

Pinging: @FinalAngel , @digi604 , @yakky

**Comment by FinalAngel** [comment]
@johnraz we have the following in 3.x:
![image](https://cloud.githubusercontent.com/assets/270307/10822600/42db141c-7e2e-11e5-80b3-d045be522ea5.png)

**Comment by czpython** [comment]
I'm not sure the complexity behind point 2 is worth it.
I don't see many use cases for it.
Closing. Feel free to create a new ticket for point 2 with the use cases.
