### ISSUE TITLE
Make redirect link to internal page "dynamic"

### ISSUE THREAD

**Issue by johnraz** [divio/django-cms#2916]
## What we have now:
page 2 redirects to page 1, page 1's URL is changed by the user, the redirect of page 2 is now broken.

## What we would like to have:
a way to keep track of page url change and update redirections pointing to the page.

## Proposal:
Create a new foreign key field on the Title model (eg: ```internal_redirect_to```), that would hold the link with the internal page that we want to redirect to. 

We would fill this field only if the redirection is internal.

We can then add some logic when we actually check for the redirect ( eg: in the ```Page.get_redirect()``` method ) and use ```Page.get_absolute_url()``` instead of an hardcoded path to resolve the url to redirect to.

Caching should obviously be investigated to avoid having to call ```Page.get_absolute_url()``` each time a user visit an internally redirected page.

**Comment by mkoistinen** [comment]
Is this still an issue @johnraz and something you're looking into a solution for?
