### ISSUE TITLE
Child plugins who are also marked to 'allow_children' should accept them

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#2951]
I have a plugin that has 'allow_children' set to ``True``. When used directly in a placeholder, it can accept children via drag-n-drop or 'paste', no problem, but only for the first level. If I add a 'allow_children' plugin into another 'allow_children' plugin, the child plugin does not accept further children despite the 'allow_children' being True.

**Comment by yakky** [comment]
@mkoistinen could you clarifiy this?

**Comment by FinalAngel** [comment]
@vxsx we fixed the allow_children mechanism in 3.2 or?

**Comment by vxsx** [comment]
no, @FinalAngel, we fixed restrictions, this is something else

**Comment by mkoistinen** [comment]
@yakky To clarify, as requested, the structure board does not support drag-n-drop of addons into or out of TextPlugins which contain (or have room for) child-addons.

An example use-case: You have a generic Link addon which is text-enabled. You write the link addon to accept child-plugins so that you can wrap the link around any arbitrary content (photos, etc.). This is fine in the BE code of the CMS, but not in the FE code. Modifying the **contents** of a plugin which is already a child of a TextPlugin is not supported.

**Comment by czpython** [comment]
I've been briefed on the issue by @vxsx.
Seems to me that this is more a design decision rather than a bug.
Fixing this would be quite complex.
Closing as a won't fix.
