### ISSUE TITLE
Missing error handling when plugin changes are "saved"

### ISSUE THREAD

**Issue by intgr** [divio/django-cms#3028]
In CMS 3.0, when I edit the contents of a CMS plugin via frontend editing and "save" it, the AJAX request is fired off without properly checking its status:
1. If I stop the web server before clicking Save, then the spinner is displayed forever even though the request fails immediately.
2. If the request fails with an HTTP error, for example, missing permissions in the database, the frontend acts as if the save was successful, but when I open it again, it wasn't actually changed.

I haven't yet tracked down the code that is causing this.

**Comment by mkoistinen** [comment]
@intgr Is this still an issue for you in recent builds (3.0.10, in particular)? Perhaps this was satisfied already with some commit for 3.0.6 but we forget to close this issue?

**Comment by intgr** [comment]
@mkoistinen Yes, still a problem. In the 1st case I now get some cross-origin error and in the 2nd case it spins forever.

**Comment by mkoistinen** [comment]
@intgr thanks. We'll investigate.

**Comment by stefanfoulis** [comment]
I can confirm as well, that this is still a problem.

**Comment by FinalAngel** [comment]
This requires more steps within the backend to give me this feedback

**Comment by yakky** [comment]
@FinalAngel let's talk about the support you need on the backend

**Comment by czpython** [comment]
@FinalAngel Is this still an issue on 3.2/3.3?

**Comment by FinalAngel** [comment]
we have a messaging system but we are not checking for imminent failures there /cc @vxsx

**Comment by vxsx** [comment]
I believe both cases are still not covered in 3.3
The first one stops the spinner but doesn't really show correct error message (and error timeouts in e.g. reloadBrowser are not handled at all) 
second one is also not handled sadly

**Comment by vxsx** [comment]
Should be fixed by #5360
