### ISSUE TITLE
Reusable publishing workflow for custom models.

### ISSUE THREAD

**Issue by johnraz** [divio/django-cms#3032]
I'm currently facing a use case where I would like my custom models to support the publishing workflow (draft version, preview draft, publish draft).

I found some tools around (https://github.com/johnsensible/django-publish, https://github.com/platypus-creation/django-draft), but I think it requires too much hackery to have it integrated in the cms, especially with the front-end editing. 

Also a standardized way of dealing with this would improve consistency (same goal as #2639) and would avoid having to customize the live / draft switcher (#2971).

What's your input on this topic ?

**Comment by FinalAngel** [comment]
There are also multiple improvements in 3.x and 3.2 regarding naming and button states :) I hope this serves your needs.

**Comment by jscontrust** [comment]
This has been closed, but I don`t find the info on how to implement it. Is there a link to an article or tutorial, on how to implement a publication workflow for a Django model called e.g. "Project".
Is it possible, to use "Page" as base class to derive from?
