### ISSUE TITLE
Redirection to top_frame seems overzealous

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#3039]
I have a bit of JS that opens a "Tweet on Twitter" dialog into a new pop-up window. I am using event.preventDefault(); AND return false; to prevent the click from opening in the main window.

Works perfectly.

In the latest version of the CMS, however, if the operator is logged-in when they click this link, it opens in the pop-up window as expect, but also opens the Twitter URL in the top_frame too.

**Comment by yakky** [comment]
This is actually the same as #3347

**Comment by mkoistinen** [comment]
Agreed that #3347 is a duplicate of this issue.

**Comment by yakky** [comment]
Fixed in #3980
