### ISSUE TITLE
Code cleanup (module imports reorganization)

### ISSUE THREAD

**Issue by mmarzantowicz** [divio/django-cms#3064]
Development of Django CMS is getting faster and faster, lot of new functionality is incorporated and lot of changes to source code happen.

I would like to open discussion about coding standards and propose some code cleanup to allow Django CMS development without slowing down due to complicated code base.

My proposition is to more strictly adhere to PEP8 coding standards in field of organizing code in modules and using module imports. Having clean and well organized modules with all imports on top (with some minor exception as always) is very important and allows developers to familiarize with source code and what is more important to avoid circular dependencies.

Since Dajngo CMS consists of large amount of python files (modules) there would be a lot of work. I can start doing some `import` reorganization according to PEP8 (http://legacy.python.org/dev/peps/pep-0008/#imports). I'll try to avoid changing anything not related to imports to minimize introduction of errors but sometimes importing some module after/before another might have unexpected side effects. I'd also like to get rid of imports from functions and any other places which are not near the top of the module.

Is this work worth doing? Are there any particular reasons not to do this?

**Comment by FinalAngel** [comment]
@yakky I update #4580 for this
