### ISSUE TITLE
JS CMS namespace isn't checked for existence

### ISSUE THREAD

**Issue by kezabelle** [divio/django-cms#3109]
```
(function($) {
// CMS.$ will be passed for $
$(document).ready(function () {
	new CMS.Plugin('cms_plugin-101', {});
});
})(CMS.$);
```
Assuming the `CMS` exists as a global is a terrible idea, not least because it will break JS executed further on. And it did.

```
if (window.CMS !== void(0) && window.CMS.$ !== void(0)) {
    (...anonymous immediate function...)(CMS.$);
}
```
(Yes, I'm assuming `window` is valid and that this stuff is only used in a browser context)

**Comment by yakky** [comment]
@FinalAngel is this report valid? Any real fix for this?

**Comment by FinalAngel** [comment]
well cou can built in a check if CMS is available. How did you encounter that issue @kezabelle ?

**Comment by FinalAngel** [comment]
also in regards to https://github.com/divio/django-cms/issues/3110 the cms will be available as soon as ``{% cms_toolbar %}`` is available - closing
