### ISSUE TITLE
Frontend editing "Revert to live" left disabled erroneously.

### ISSUE THREAD

**Issue by kezabelle** [divio/django-cms#3112]
Steps to reproduce:
* Hit "Edit this page"
* Go to structure mode, if not already
* Drag and drop to re-order a plugin's position.
* Note that the "Revert to live" action remains inactive.
* Refresh the page
* Note that "Revert to live" is now active.

Given nothing has changed, beyond my refreshing the page, I'd expect the "Revert to live" action state to be the same at both points (whether disabled or enabled, I don't know)

**Comment by yakky** [comment]
@mkoistinen @kezabelle could you check that #3918 fixes this issue?

**Comment by mkoistinen** [comment]
Fixed by #3918.
