### ISSUE TITLE
Adding navigation buttons in the side frame.

### ISSUE THREAD

**Issue by johnraz** [divio/django-cms#3117]
I've had some feedback about the fact that navigating in the side frame is not always intuitive.
People seems to have some trouble finding how to go "back" in the sideframe and are confused if yes or no they should hit the back button of the browser to do so.
Their first thought is that it would impact the main frame instead.

I just added a toolbar on top of the sideframe - I know much more can be done on the design side of thing but there are much more talented people than me around.

PR follows

**Comment by FinalAngel** [comment]
Buttons have been added in 3.2 :)
