### ISSUE TITLE
Review the page tree UX

### ISSUE THREAD

**Issue by johnraz** [divio/django-cms#3132]
Following issues like #3113 and #3131, I think we need to review the general UX of the page tree.

So my points are:
* the edit action is triggered at the same time by the bullet button in the language column, by the page title link and by the edit icon in the action column. This is too much solutions and this is confusing the user. I think that an edit icon per language column would make much more sense.

* the contextual menu is a very good idea because it help offering more feature in a small area, but it needs to be improved. Maybe we should completely merge the action column in this contextual menu. That would make the tree lighter and clear things up.

Shout your comments ;-)

**Comment by FinalAngel** [comment]
Closed for collective issue #4597
