### ISSUE TITLE
{% cms_toolbar %} does not work inside a {% block ... %}

### ISSUE THREAD

**Issue by benjaoming** [divio/django-cms#3146]
I tried this in base.html:

    <html>
        ...
    </html>
    <body>
    {% block body_init %}{% endblock %}
    ...

...and combined it with base_cms.html

    {% extends "base.html" %}
    {% load cms_tags %}
    {% block body_init %}{% cms_toolbar %}{% endblock %}

But I got:

    TemplateSyntaxError at /
    Invalid block tag: 'endblock'

The problem is that I wanted a base.html that is not dependent on django-cms.. I can work around the problem by not caring.. but it'd still be nice to be able to host a site where the mother of all templates is not django-cms dependent.

**Comment by CDAugDev** [comment]
I'm not sure if this is still relevant, but I came up with a solution.

Create a single "cms_toolbar.html" file with only this inside:
```
{% load cms_tags %}

{% cms_toolbar %}
```

Then, when I want it in one of my many "base.html" files, I call it with an include like so:
```
{% extends "shared/base.html" %}

{% load cms_tags staticfiles sekizai_tags %}

{# Content #}
{% block base_content %}

    {# Magic #}
    {% include 'shared/cms_toolbar.html' %}

    {% block content %}{% endblock %}

{% endblock base_content %}
```

Seems to work fine in Django 1.8.3 / Django CMS 3.1.2

**Comment by FinalAngel** [comment]
thanks for a possible solution @CDAugDev
