### ISSUE TITLE
graceful exceptions for orphaned apphooks in db

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#3156]
When adding and removing apps a lot, one often runs into a whole site going down, just because there is an apphook still defined in the database that no longer exists in code. Sure there is the management command to force remove a specific apphook, but in some many circumstances this is impractical. I would not want my whole site to go down because of an issue that comes purely from the contents of the database.
There is also the inverse problem, of one adding an app, but not having added the apphook to a page yet. Apps should fail gracefully in that case and not bring the whole site down. But that is a problem for a other ticket.

I propose to no longer raise a hard exception in the case where the apphook saved in the database no longer exists in code. Instead show the apphook in the pagetree as "broken" or red and allow removing it over the advanced settings of the page. The urls should be loaded as if that apphook did not exist.

If the old behaviour should be maintained and the new behaviour could be provided through a setting could also be discussed.

The exceptions are currently raised here: 

* https://github.com/divio/django-cms/blob/6060ea14edb9066f07cfa12dc656d9f0ea7df377/cms/apphook_pool.py#L15-L29
* https://github.com/divio/django-cms/blob/6060ea14edb9066f07cfa12dc656d9f0ea7df377/cms/apphook_pool.py#L71

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/4871
