### ISSUE TITLE
Graceful failure META-issue

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#3158]
Exceptions in plugins, apphooks and menus can make a whole page or even a whole site cause a 500 error. While this is a good behaviour while developing, it is bad in production.

This issue collects various other issues that strive to change the cms to behave more gracefully in such cases.

 - [ ] Plugins: #3157
 - [x] Apphooks: #3156 
 - [x] conventions for menu extenders (don't fail hard if reverse urls fail because an apphook has not been added yet)
 - [ ] ...

**Comment by czpython** [comment]
Closing to track the only remaining issue https://github.com/divio/django-cms/issues/3157
