### ISSUE TITLE
After undo/redo cms plugin related models are lost

### ISSUE THREAD

**Issue by o-zander** [divio/django-cms#3174]
My situation: I have a Slideshow-Plugin and a related Slide-Model. Everytime I used the undo/redo function all slides of the slideshow were lost. In the docs it is mentioned that relations could only be used if the copy_relations function is implemented. It should be added to the docs that one have to register the plugin in reversion with the follow attribute set and register the related plugin too. I'm wondering that no one has ever encountered this situation.

```python
class Slideshow(CMSPlugin):
   ... fields ...

   def copy_relations(self, old_instance):
        for slide in old_instance.slides.all():
            slide.pk = slide.id = None
            slide.slideshow = self
            slide.save()

reversion.register(Slideshow, follow=['slides'])

class Slide(models.Model):
   slideshow = models.ForeignKey(Slideshow, related_name='slides')
   ... fields ...

reversion.register(Slide)
```

**Comment by yakky** [comment]
@o-zander could you check if this is still the case in latest 3.0.10?

**Comment by FinalAngel** [comment]
@yakky I think this is just documentation that you have to use `reversion` to get it working. I think @mkoistinen added docs somewhere?
