### ISSUE TITLE
Very clearly note in docs that PlaceholderAdminMixin must be first ancestor in admin class

### ISSUE THREAD

**Issue by hakanw** [divio/django-cms#3178]
I got a very strange error in my django-cms installation after upgrading to 3.0:

```
NoReverseMatch at /products/productcategory/
Reverse for 'products_productcategory_add_plugin' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

After much research, it turns out that it was because the PlaceHolderAdminMixin was after the admin.ModelAdmin class:

```
class MyProductAdmin(model.ModelAdmin, PlaceholderAdminMixin):
   pass
```

If I change the order so that PlaceholderAdminMixin is first, I get no error. I had no idea that this would be so significant.

Therefore I suggest it should be very strongly pointed out in the docs that if you put these in the wrong order, all hell will break loose. 

Thanks!

**Comment by evildmp** [comment]
@yakky this is in the develop branch - what else needs to be done, other than close the issue?

**Comment by yakky** [comment]
@evildmp Nothing, closing this

**Comment by evildmp** [comment]
@yakky sorry, apparently it was open so that @mkoistinen could cherry-pick it into support - but there ought to be a better way of signalling that than leaving issues open, I feel!

**Comment by yakky** [comment]
@evildmp it's been merged in develop 8 months ago, there should be no need to port it to support
