### ISSUE TITLE
Superuser: `You do not have permission to add a plugin` 

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#3182]
I've been developing a number of plugins and apphooks for cms and in my latest apphook I have a template which I dropped a content placeholder. However when I add a TextPlugin I get a 403 response 'You do not have permission to add a plugin'.

I've confirmed my account is a superuser and the initial database I'm using is the same for all previous apps/plugins and I've never had an issue elsewhere. Permissions are enabled, but none are defined. Regardless of permissions thought - I'm a superuser!?

**Comment by marksweb** [comment]
I'll close this as it's not been an issue for some time. If it occurs again and I can provide more info, I'll reopen.

**Comment by yakky** [comment]
@marksweb thanks!
