### ISSUE TITLE
Empty placeholderfields are impossible to edit

### ISSUE THREAD

**Issue by hakanw** [divio/django-cms#3183]
If you have a Placeholder on a custom model, and it is empty, then ```{% render_placeholder %}``` will render a plugin with 0 height. And thus, it is impossible to edit it in the new "edit on the page" admin.

My dirty CSS fix to this was:

```
.cms-ready .cms_plugin {
	display: block;
	min-height: 100px;
	min-width: 500px;
}
```

**Comment by yakky** [comment]
Closing because of no feedback
