### ISSUE TITLE
Improving support for django-suit and the likes

### ISSUE THREAD

**Issue by benjaoming** [divio/django-cms#3191]
Since django-cms has grabbed the opportunity to depend on the django admin backend for frontend editors, we'll have to deal with a lot of crappy fixes and work-arounds -- sorry, just being provocative ;)

But really, you're not getting me to leave django-suit, so I'm opening this ticket to document and refer my pull requests.

For instance, javascript quirks are looking for `<input type="button">` in the admin HTML output in order to put that in the parent fra. SInce django-suit is using a `<button>` element, it breaks like so:

![screenshot from 2014-05-23 14 52 22](https://cloud.githubusercontent.com/assets/374612/3066696/1e08537c-e279-11e3-9c89-4788b5367ec3.png)

(Danish: "Aflys" is Cancel, but there's no "Gem" / Save button)

I'm going to make a pull request in a moment for the most urgent things like getting the Save button back.

**Comment by FinalAngel** [comment]
All specific admin styles within the CMS have been removed in favour of supporting different admin themes. Themes can now control the content display of the modal or sideframe using:

- ``.cms-admin`` for global injection (wherever the cms renders an iframe)
- ``.cms-admin-modal`` only for the modal
- ``.cms-admin-sideframe`` only for the sideframe

This allows the theme developers to have more control and shifts the responsibility to their repos. Examples of the implementation can be reviewed via https://github.com/divio/djangocms-admin-style

**Comment by benjaoming** [comment]
@darklow :)
