### ISSUE TITLE
All Links on get None for 5- 10 min 

### ISSUE THREAD

**Issue by shobhit26** [divio/django-cms#3213]
We have a website sscnasscom.com and it is based on django and CMS but the problem is all its links turns to NONE various times on a day for 5-10 min and then get back again as they were earlier. Please refer to the screen shots. 
https://www.dropbox.com/sh/b5ceobspy132cax/AABnxJAeDEeNGiO90asqeAY4a
kindly help us in resolving it.

**Comment by yakky** [comment]
closing due to no feedback

**Comment by shobhit26** [comment]
Yes it is solved with the resolution you suggested. Sorry for replying so late.
