### ISSUE TITLE
Add "publish draft" and "preview draft" buttons to backend

### ISSUE THREAD

**Issue by benjaoming** [divio/django-cms#3228]
It adds unnecessary extra clicks to have to always visit the frontend preview in order to publish drafts. Can a "publish draft" button be added to the action menu on django-admin's page change view like they used to? A preview button would also be nice because it goes well with normal django-admin conventions and you don't have to go back to the pages change list to find the preview button there.

![screenshot from 2014-06-04 13 22 22](https://cloud.githubusercontent.com/assets/374612/3172769/8973ab1a-ebda-11e3-901d-ece50cb75e03.png)

**Comment by FinalAngel** [comment]
This has been implemented within the pagetree:
![image](https://cloud.githubusercontent.com/assets/270307/10820227/874c1b66-7e22-11e5-9cdd-290c9752b2c8.png)

**Comment by benjaoming** [comment]
Great work!! :)
