### ISSUE TITLE
avoiding migration hell with cms plugin magic removal in django-cms 3

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#3232]
Executive summary:

* **DO NOT use ``syncdb --all``** until each and every plugin has done a clean migration to the new cms3 style tables
* if you've not done the migration to the new table naming in your plugin yet: make sure you create new migrations in an environment with django-cms 2.4.x and not 3.0.x

---

This Issue is a braindump of what @stefanfoulis, @digi604  and @jqb discussed today. A place to work on and discuss the best approach to make upgrading to 3.0 for plugin developers as easy as possible. This should result in a documentation update and perhaps a blog post and a little helper tool that makes upgrading easier.

Way back, before South existed, some magic was added, that would rename all tables for cms plugin models to start with the ``cmsplugin_`` prefix, followed by the model name. This would create tables like ``cmsplugin_text``, ``cmsplugin_link``. That was a bad idea and caused a lot of edge case problems.
We'll call the magically renamed tables "old-style". The normal naming we'll call "new-style".

In django-cms 3.0, we introduced a bit more magic that would allow us to remove this evil thing. If an "old-style" table is found for a plugin it is used (and a deprication warning is issued). Otherwise we use the new-style table. In django-cms 3.1 all magic will be removed and all plugins will have to have migrated to "new-style" tables.

Unfortunately there are some edge cases where this strategy does not work well. Plugin authors will have to follow some guides to not run into bad situations.

### ``syncdb --all``

If a project database was initialised with ``syncdb --all`` and ``migrate --fake``, all plugin tables will use the new style table names, even if the accompaning migrations for those plugins don't know anything about it yet. The next time that plugin has a migration, it will fail because the new migration still expects old-style tables.

### creating new migrations

When creating a new migration for a plugin, south will automatically use the new-style table names if django-cms 3.0 is installed in the same project. If you want to still support django-cms 2.4.x, you'll either have to manually edit the new migrations or make sure you create the migrations in a django-cms 2.4 context.

### fully supporting django-cms 2.4.x and 3.0.x at the same time is hard

Because of the ``syncdb --all`` issue mentioned above, every migration needs to be altered based on the recipe below (without the final table rename step) to have reliable support django-cms 2.4.x and 3.x at the same time. It's recommended to switch to 3.0-only mode as soon as possible.

## How to make plugins compatible to cms 3

It's a one-way street. Once you take this step you can't support 2.4 anymore.

Add a migration that detects if the old-style table exists. If it does, rename it to new-style. Otherwise do nothing. From now on all migrations will use new-style table names.
It's still possible that someone used an older version of your plugin and used ``syncdb --all`` (or not). So there might be a mix of old-style and new-style tables, some matching and some not matching their migrations. This is why all migrations before the one that renames the table to new-style, need to make sure they can run, even if the table is already new-style (by renaming the table back to old-style if needed).

### example

https://gist.github.com/stefanfoulis/c6b393d05751314addca

Possibly related Issues:

 * #3205 
 * #3160 

Things to test:

 - [ ] can we handle the case where both tables exist somehow? (e.g ran ``migrations`` and later ``syncdb --all`` so old-style would be here from migrations and new-style form ``syncdb --all``)
 - [x] what if a package adds new plugins in a later migration? *only do magic renaming for plugins on the first migration after initial table creation*
 - [ ] what to do in data migrations? (do the table rename schema migrations anyway?)

**Comment by yakky** [comment]
I'd close this as the migration is now complete
