### ISSUE TITLE
Add support for 'active' items in a cms.toolbar.items.SubMenu

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#3251]
It would be useful if there was support for marking an item as 'active' in a cms.toolbar.items.SubMenu.

**Comment by FinalAngel** [comment]
I don't think this make sense (there was never a need for it and the mac menu doesn't offer this either) @mkoistinen what do you think, is this still relevant?

**Comment by czpython** [comment]
@mkoistinen I think this was addressed in https://github.com/divio/django-cms/pull/5268. Can you confirm?

**Comment by mkoistinen** [comment]
I think we can close this. The issue was opened when I was working on Aldryn Segmentation, some time ago.
