### ISSUE TITLE
Bring back preview mode #2

### ISSUE THREAD

**Issue by o-zander** [divio/django-cms#3252]
It is nearly a year ago since I opened the same issue #2104 

@FinalAngel I hoped your inline style changes fixes my style problems in edit mode but sadly they did not. I'm not the frontend developer who invented the horrible layout I have to bother with ;)

To explain the problem again: In Edit-Mode (Content) the layout is not exactly the same as in live mode. Cause there is a complicated grid layout with rows and columns its sometimes hard to know how they should be nested to achieve the desired layout. So to see the final layout one has to publish the page. That is cleary not the intention of a publish mechanism to check for layout errors on a live page ;)

The easy solution is to bring back a real preview mode. I stumbled through the code and found a preview flag in ``get_page_from_request`` but it is not used as intended. The easy solution is returning the draft page from this function if the preview flag is set. So the draft page is rendered without any cms-plugin-divs and looks exactly the same as the live-page after publishing will do.

**Comment by Hamms** [comment]
Any updates on this proposed feature? I'm encountering the exact same use case as @o-zander, and would love to give my designers a simple preview mode.

**Comment by FinalAngel** [comment]
We are working on solutions for 3.2 :)

**Comment by FinalAngel** [comment]
Actually this will be moved further to 3.3 @o-zander

**Comment by FinalAngel** [comment]
closed in favour of https://github.com/divio/django-cms/issues/4634
