### ISSUE TITLE
Making a get_editor_widget() function available

### ISSUE THREAD

**Issue by LeGast00n** [divio/django-cms#3254]
Hello there,
We're looking at v3 here and trying to adopt pre-v3 plugins. One common issue is the text editor widget obviously. This is not hard to fix directly into the plugin code, yet it's a pity that every plugin has to manage on their own the editor bit.
Wouldn't it be great if the CMSPluginBase class would have a get_editor_widget() method ?
Or a more general function available from the cms module itself ?
That would make it possible for a plugin to align by default to the base cms text editor.

In this case, you could secure some level of forward compatibility...

Last but not least : THANK YOU for django-cms and keep up the good work !
LA

**Comment by FinalAngel** [comment]
what's the design decision here @yakky and @mkoistinen ?

**Comment by czpython** [comment]
I don't think this is something that should be in the core.
Plugin authors are able to use any text widget that suits their needs, the standard is to use djangocms-text-ckeditor but it's not required. Django CMS itself does not require any text editor plugin.
@yakky Thoughts?
