### ISSUE TITLE
cms toolbar code breaks if current page's parent has no title

### ISSUE THREAD

**Issue by o-zander** [divio/django-cms#3270]
I don't know how my customer has done this but: There is a page without any title at all. This page has subpages and if you want to edit those you get an error 500. Why? Because the cms toolbar tries to set the on_succes attribute for the delete action. It uses the current page's parent to redirect to. But that is in this case a page without any titles and therefor has no slug. The page-with-slug is reversed with an an empty slug and raises an NoReverseMatch. It is in the code I refactored in #3259 so I could add error handling there but my actual question is how could there be a page without titles, shouldn't this be prevented and how could this even happen.

Edit: I encountered the error at another situation: I created a page type for en but the page type's parent is only available in de. So the error is raised because there couldn't be found an url for the parent in en.

**Comment by yakky** [comment]
@o-zander this has been fixed in #3259, right?
