### ISSUE TITLE
Click and hold a plugin will switch structure/content mode

### ISSUE THREAD

**Issue by benzkji** [divio/django-cms#3278]
If I click and hold a plugin in content mode, the cms switches to structure mode. And vice versa. Is this an intended (and documented) behaviour? It can drive you crazy when trying to drag'n'drop plugins in structure mode...and suddenly, you'll find yourself in content mode. This will happen if you don't drag fast enough initially (happens on a notebook, and even on desktop sometimes). Kinda strange behavior, and kinda difficult to explain to end users? I see the benefit for fast structure/content switching, though...

I'm on 3.0.2, have this behavior on FF and Safari (Mac), and probably all other browsers, as it seems intended.

**Comment by yakky** [comment]
@FinalAngel do we really need this feature? it's quite confusing, actually

**Comment by FinalAngel** [comment]
It was introduced to highlight which element you are handling. There should be better options as we are refining the structure board. But currently it also helps several editors to figure out where they are.

**Comment by frnhr** [comment]
Seems to be missing from 3.1.2? 
I found this feature useful, but agree that if would benefit from having a different trigger. Perhaps a shift+hold, or a triple-click.

**Comment by frnhr** [comment]
Yeap, here it is: https://github.com/divio/django-cms/commit/401654988b6a5bcdcd878a82f52b0740fc849895

Too bad is was just removed, without an alternative :(
I recently explained this feature to my client and he loved it. And now it's gone. 

Any thoughts about implementing it again, but with a triple-click this time? What are the changes of it being accidentally trigged that way?

**Comment by yakky** [comment]
We removed this (undocumented and poorly understood) feature as we had a lot of negative feedback on it (especially with touch devices or mousepads). Structure mode UX is going to change a lot in the next releases and it may worth exploring alternatives if there is interest for it

**Comment by FinalAngel** [comment]
This has been removed in 3.1 :)
