### ISSUE TITLE
Publish multiple pages in one click

### ISSUE THREAD

**Issue by petzlux** [divio/django-cms#3279]
As we are adding more content in 4 languages, my editors are asking me if it is possible to publish more than one page & one language at a time ?

**Comment by yakky** [comment]
@donce any update on this?

**Comment by donce** [comment]
Oops sorry, I kinda forgot about it. I'll get back to it :)

**Comment by yakky** [comment]
We have a proper command to publish all unpublished pages.
Closing this and leaving #3602 to track possible addition of a button in the UI

**Comment by mfcovington** [comment]
@yakky 

> We have a proper command to publish all unpublished pages.

What is that command? Thanks.

**Comment by yakky** [comment]
@mfcovington http://django-cms.readthedocs.org/en/support-3.0.x/reference/cli.html#additional-commands

**Comment by nishantp11** [comment]
The link is broken now. Could someone share the command to publish all unpublished pages?

**Comment by donce** [comment]
Link for latest reference: https://django-cms.readthedocs.io/en/latest/reference/cli.html#cms-publisher-publish

**Comment by peacefulseeker** [comment]
@donce , where can I see the API for that so I can try implementing the action in CMS admin to publish all 
unpublished versions for selected page. Action could live somewhere in the context menu I suppose.
![image](https://user-images.githubusercontent.com/25010454/108343807-0c22f880-71e5-11eb-9273-cbf4aad2f992.png)

**Comment by donce** [comment]
@peacefulseeker I haven't used django-cms in years now, maybe @yakky could help you with this?
