### ISSUE TITLE
Removing an app from the codebase causes 500 (ImproperlyConfigured) errors

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#3280]
I just committed a change to a staging environment whereby I removed an old app and merged it's features in to an existing plugin. This caused the server to 500 because there was a page with the old app still registered, although not used.

Surely there should be a fallback mechanism for missing apps rather than just going to an ImproperlyConfigured error? The quick fix for this was to remove the app/app urls from the page records in the db. Surely on a missing application you could simply remove those values which cause problems & maybe notify the admins or similar to highlight an issue.

I'm sure some would argue that you shouldn't remove an app that is hooked in to a page, but in this case the app wasn't even used so to cause a site-wide problem for a page issue seems drastic.

Just to add, this is also a little annoying when I'm switching between feature branches and my dev db stays in the same state as there isn't really a need to change it beyond the apphook to a page for another feature.

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/4871
