### ISSUE TITLE
model_unpickle error with Django 1.5

### ISSUE THREAD

**Issue by brente** [divio/django-cms#3282]
The signature for `django.db.models.base.model_unpickle` changed in Django 1.5 (see https://github.com/django/django/commit/146aff3bac974e56ec8cb597c2720d1cd4f77b26), and the `factory` parameter was dropped.

`CMSPlugin.__reduce__` returns a `(model, defers, factory)` tuple, so unpickling causes a "model_unpickle() takes exactly 2 arguments (3 given)" error.

This only happens with Django 1.5, since the change was reverted in Django 1.6 (see https://code.djangoproject.com/ticket/20289).

I'm using django CMS 2.4.3, but this should also affect 3.0 (only if used with Django 1.5).

**Comment by yakky** [comment]
@brente is this still the case? which django CMS version?

**Comment by FinalAngel** [comment]
we do not support django 1.5 anymore
