### ISSUE TITLE
Plugins after copy do not stay where actually dropped

### ISSUE THREAD

**Issue by o-zander** [divio/django-cms#3336]
If I copy a plugin and add it to a placeholder on another page it is coincidence where it finally gets placed. Given the example I already have three plugins in the placeholder and I try to paste the copied plugin to position 2 between plugin 1 and 2 the copied plugin after reload is maybe on position 1 or maybe at the last position and with luck on position 2 where I wanted to have it.

My thoughts on this: Is the plugin position in the last placeholder used and not correctly updated with the new position?

**Comment by FinalAngel** [comment]
We refactored copy & paste in 3.2. This has been fixed :)
