### ISSUE TITLE
Open link in a new window does not work in Edit mode

### ISSUE THREAD

**Issue by adrien-delhorme** [divio/django-cms#3347]
In Edit mode, the plugins (for example : cmsplugin_link, cmsplugin_filer_image, etc) that should open a link in a new window (target: _blank), are opened in the same window.

It works well in Published mode.

**Comment by yakky** [comment]
@FinalAngel do you think it's solvable / doable in some way?
For the record, this is due to https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.structureboard.js#L242 which hijacks the click to handle plugin editing

**Comment by FinalAngel** [comment]
@yakky I don't know yet. My head spinned around on this topic as there is no correct "doubleclick" event handler. So I have to prevent the normal link click. thought about adding an overlay to the links that hides. It's really tricky where I have no answer yet.

**Comment by yakky** [comment]
Fixed in #3980
