### ISSUE TITLE
Django CMS should ask before leaving the page when editing content

### ISSUE THREAD

**Issue by ntrrgc** [divio/django-cms#3349]
I was writing for a while in the Django CMS text editor, when I accidentaly pressed Ctrl+W in a flash. This is not so strange because I'm generally a console and vim user, so Ctrl+W means *delete word* before *close tab* for me.

The real problem is that this reflex act (that could also happen in many alternative forms, like closing a window and then remembering you were editing, closing the browser accidentally, pressing Ctrl+Q and more) has triggered half an hour of work lost.

That should not happen, not so easily.

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/5355
