### ISSUE TITLE
repeated calls to cms.api.add_plugin does not preserve order

### ISSUE THREAD

**Issue by ojii** [divio/django-cms#3353]
Using a patched version of https://pypi.python.org/pypi/aldryn-client/0.8.11 (patches make it work with CMS 3 and output a tar.gz instead of multiple files), loading the data causes plugins to be inserted in arbitrary orders (tree-order is not preserved).

Changing the loading code to always refresh all instances used in a ``add_plugin`` call did not fix the issue as expected.

What in the end did fix it, was removing three lines from ``add_plugin``: https://github.com/divio/django-cms/blob/3.0.3/cms/api.py#L297-L299

Unfortunately, I was not able to reproduce the issue in a test case yet.

**Comment by jrclaramunt** [comment]
To preserve order what i did was to modify the lines you are talking about using as parent the target:

```python
for pl in CMSPlugin.objects.filter(language=language, parent=target, tree_id=target.tree_id, position__gte=new_pos):
            pl.position += 1
            pl.save()
```

This is working for my project, but unfortunatelly i don't have any tests to support this fix.

**Comment by czpython** [comment]
Closing. Feel free to create a new ticket if this issue can be reproduced on the latest djangoCMS.
