### ISSUE TITLE
"Revert to Live" interaction with Link plugin

### ISSUE THREAD

**Issue by evildmp** [divio/django-cms#3361]
Under some circumstances, **Revert to Live** interacts with the **Link** plugin in such a way that it loses the link text in the editor, and shows a missing image:

![screenshot 2014-08-07 12 58 46](https://cloud.githubusercontent.com/assets/86222/3841316/33f9bb0c-1e2a-11e4-9971-b213924d1c7f.png)

To replicate this:

Insert a Link plugin; the standard plugin icon will be replaced with the link text:

![screenshot 2014-08-07 12 59 57](https://cloud.githubusercontent.com/assets/86222/3841323/511ac23a-1e2a-11e4-9591-5eb860c61718.png)

Save those changes and publish them.
 
Select History > Revert to Live.

Open the text plugin again for editing. The link text will be lost.

`pip list` output:
```
argparse (1.2.1)
dj-database-url (0.3.0)
Django (1.6.5)
django-classy-tags (0.5.1)
django-cms (3.0.3)
django-mptt (0.6.1)
django-reversion (1.8.2)
django-sekizai (0.7)
djangocms-admin-style (0.2.2)
djangocms-column (1.3)
djangocms-file (0.0.1)
djangocms-flash (0.0.2)
djangocms-googlemap (0.0.5)
djangocms-inherit (0.0.1)
djangocms-installer (0.5.3)
djangocms-link (1.3.5)
djangocms-picture (0.0.2)
djangocms-style (1.3)
djangocms-teaser (0.0.1)
djangocms-text-ckeditor (2.1.6)
djangocms-video (0.0.1)
html5lib (0.999)
Pillow (2.5.1)
pip (1.5.6)
pytz (2014.4)
setuptools (3.6)
six (1.7.3)
South (1.0)
wsgiref (0.1.2)
```

**Comment by yakky** [comment]
Ok, closing this
