### ISSUE TITLE
Cannot double click to edit the video plugin

### ISSUE THREAD

**Issue by tdelam** [divio/django-cms#3373]
I have a page on my site with the video plugin enabled in a placeholder, I cannot double click to edit the video plugin, nothing happens.

**Comment by davidetruffo** [comment]
Hi!
Same problem here!

Here are some screenshots to explain what i see.
Please note that i haven't done anything more than adding a video in the placeholder (all default settings).

Original view (the highlighted part should be the double-clickable one):
![screen shot 2015-02-02 at 15 21 45](https://cloud.githubusercontent.com/assets/2778867/6001989/769ee85e-aaef-11e4-89bc-0ae7dc16126d.png)

If i manually edit the above highlighted element (and make it obviously visible), the double click on it works fine (double click on the movie still play/pause it).
![screen shot 2015-02-02 at 15 18 25](https://cloud.githubusercontent.com/assets/2778867/6002009/bfe65d4e-aaef-11e4-8b75-00459383ffaa.png)

(this is the edited code)
![screen shot 2015-02-02 at 15 18 08](https://cloud.githubusercontent.com/assets/2778867/6002012/c49cc4cc-aaef-11e4-82a3-fa141d64e098.png)

Hope it helps!
thanks

**Comment by yakky** [comment]
@FinalAngel Any chance we can do something here? If the flash area has no padding around, I think it's tricky to get click events on the plugin

**Comment by FinalAngel** [comment]
the problem here is, that flash is not focusable by js events without adding an additional div layer on top. Shouldn't this be handeled by the plugin itself and not the cms? It's a very edge case there.

**Comment by yakky** [comment]
This is not really an issue, but a constraint. We cannot really *fix* this
