### ISSUE TITLE
KeyError in build_plugin_tree

### ISSUE THREAD

**Issue by o-zander** [divio/django-cms#3376]
Recently I encountered a bug I have known before but thought it was solved.

In https://github.com/divio/django-cms/blob/develop/cms/utils/plugins.py#L310 there is a KeyError if the parent_id is not yet in the cache. This could happen if the mptt tree is fucked up. I'm not into that whole mptt stuff and have no clue where or in which function the tree could be damaged but I have the fear that multiple operations on the whole page & plugin tree could easily damage it. There is another function which highly depends on a clean tree and that is page publishing. So this is broken for me quite often. I patched this function in my fork and as a workaround if I encounter a KeyError I step out of the function and continue building the cache with the parent I am missing. That was working quite good but is not the actual solution to this problem. I removed this patch as I thought it was fixed in the meantime.

Please have a look at this recurring problem. Sadly I could not connect it to a particular frontend operation.

I'm using django 1.5.8 with django cms 3.0.3 on python 2.7.

**Comment by yakky** [comment]
@o-zander would you recheck this on current develop?

**Comment by yakky** [comment]
@o-zander closing this as switch to treebeard makes the tre much more robust.
Please reopen if you encounter any similar issue with treebeard
