### ISSUE TITLE
djangocms Admin app language 'us-en' but all else in language 'en' causes many errors

### ISSUE THREAD

**Issue by aquarianpioneer** [divio/django-cms#3379]
I installed djangocms 3.0.3 on my local Windows7 computer (Django 1.6.5, Python 2.7.6, MySQL 5.5.36) and got the staffdemo app working. Its django Admin runs, but has many errors as it appears to consider its language 'us-en' which conflicts with settings.py sections LANGUAGE_CODE = 'en', LANGUAGES = (('en', gettext('en')),), and CMS_LANGUAGES = { .... 'code': 'en', ... }.

When running runserver with Debug on, I can see there are many errors behind the scenes. The django_text_ckeditor hangs when I attempt to add a text plugin.The menu StaffSubMenu never loads when editing pages. I am able to insert image plugins however, and general Admin navigation among pages seems to work okay.  

I installed djangocms without your staff demo app, and also separately installed djangocms with your staff demo app. Similar language conflicts exist in djangocms regardless.  For example: Page not found error 404, method POST, request URI http://127.0.0.1:8000/en-us/admin/cmspage/add-plugin/ The current URI did not match any of these URL patterns ^media/(?P<path>.')$ or ^static\/(?P<path>.')$ or ^en/

I have also installed djangocms with and without the staff demo app on a Ubuntu Linux cloud server (Django 1.6.5, Python 2.7.6, MySQL 5.5.36) and it appears to run without these languages errors. However I have just begun testing the server installation.

**Comment by mkoistinen** [comment]
This appears to be an issue relating to mis-configuration. It is important that the developer is consistent in their use of language codes. Even if copy-pasting code from another (my) repo, settings should be adjusted to be consistent with your project.

Based on this issue's age: greater than 4 months without activity, I am closing this issue. If you feel like there is a genuine issue with django CMS––even if only in documentation––please feel free to open a new issue.
