### ISSUE TITLE
Links wrong after publishing a page

### ISSUE THREAD

**Issue by TanjaBuecheli** [divio/django-cms#3380]
If you publish a page in the django CMS sidebar, after the refresh the links in the sidebar are not correct:

Wrong: http://www.example.com/admin/cms/page/246/None/preview/

It should be: http://www.example.com/admin/cms/page/246/de/preview/

**Comment by mkoistinen** [comment]
This was actually already reported in #3088. However, this was closed due to non-reproducibility. I'm going to close this issue too. But will keep an eye on it. I think this has been fixed in more recent builds.
