### ISSUE TITLE
Pages 404 when editing a child page whos parent has an unpublished slug change

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#3384]
I've built a site structured heavily around a few pages having many children.

It has recently been handed over to the client & they've decided to change a few of the parent page titles. They've also changed the slugs, and then gone to make edits to child pages. When they switch to edit mode the page 404s because the parent is at a different slug in edit mode.

The obvious solution here is to publish your changes immediately after changing a title/slug but I wondered if this had ever been raised before. I suspect the way CMS switches between edit/live is heavily based in javascript and to avoid this you'd actually have to redirect in order to pick up the changed url and avoid this.

**Comment by yakky** [comment]
Fixed in #3901
