### ISSUE TITLE
Page Editing Tree, Console JS/Jquery error

### ISSUE THREAD

**Issue by zakodiac** [divio/django-cms#3408]
Cannot read property 'nodeName' of undefined.

Seems to be issue with Page Edit Tree, when right clicking on page for Create and Delete, some variable seems to not be correctly named or defined. Trying to trace down but wondering if anyone else already had the issue.

**Comment by czpython** [comment]
Closing as page tree has been heavily refactored on 3.2.x.
Feel free to open new ticket if the issue pops up again.
