### ISSUE TITLE
Placeholder should be editable in Admin

### ISSUE THREAD

**Issue by n3ssi3** [divio/django-cms#3412]
For Placeholder that are not shown in Frontend there is no way to edit them.
F.E. If you are generating a PDF and there are some Informations that should be editable for the client it would be useful to have placeholders.
But right now there is no way to edit them.

Please add the "Edit Placeholder" button to a Static Placeholder in the Admin as well

http://screencast.com/t/spXfgCL1s9

**Comment by FinalAngel** [comment]
closed in favour of https://github.com/divio/django-cms/issues/4634
