### ISSUE TITLE
Function "Copy all" not usable for users without superuser rights

### ISSUE THREAD

**Issue by o-zander** [divio/django-cms#3414]
For placheolders from placeholder model fields the function is not usable. The has_copy_plugin_permission from PlaceholderAdmin and PageAdmin differs. The target placeholder for copy all is the user clipboard. The PageAdmin function takes into account that the clipboard placeholder has no page and doesn't check the permissions for it. The function from PlaceholderAdmin does not and checks them. But there couldn't be found any permissions for the clipboard and the copy permission is always denied!

Permission check for target placeholder @PlaceholderAdmin: https://github.com/divio/django-cms/blob/develop/cms/admin/placeholderadmin.py#L151 vs permission check @PageAdmin https://github.com/divio/django-cms/blob/develop/cms/admin/pageadmin.py#L549

Target Placeholder permission check leads to: https://github.com/divio/django-cms/blob/develop/cms/models/placeholdermodel.py#L103-L114 no superuser, no page, no attached objects -> return None

**Comment by mkoistinen** [comment]
Permissions are not my forte, any takers?

**Comment by czpython** [comment]
Fixed by 79d707b706b72e1cd9e653a2161c5cb7764c66a1
