### ISSUE TITLE
The VISIBILITY_STAFF  constant name  in cms/api.py is very misleading

### ISSUE THREAD

**Issue by praerien** [divio/django-cms#3426]
Hi 

The line 

    VISIBILITY_STAFF=2

in cms/api.py is misleading. 

It dosen't add up to the following code in cms/menu.py lines 179 to 184:

    if page.limit_visibility_in_menu == None:
        attr['visible_for_authenticated'] = True
        attr['visible_for_anonymous'] = True
    else:
        attr['visible_for_authenticated'] = page.limit_visibility_in_menu == 1
        attr['visible_for_anonymous'] = page.limit_visibility_in_menu == 2
    attr['is_home'] = page.is_home

I've tested the different values and using and by passing VISIBILITY_STAFF to create_page I can see the menu item when I'm anonymous (not logged in)  but not when I'm authenticated. If fits with what to be expected when reading cms/menu.py but not with the constant name in cms/api.py

Just wanted to let you know. 

Cheers
Rune

**Comment by yakky** [comment]
Fixed in #4049
