### ISSUE TITLE
feature: custom html representation of text plugins in editor

### ISSUE THREAD

**Issue by ollb** [divio/django-cms#3437]
This is a proposal for an enhancement related to cmsplugin-link but I think it is wise to open a ticket here since it would make evolve text plugins support.

Actualy, when you add a child plugin in djangocms_text_ckeditor (or whatever text editor plugin), the way to remember the plugin is to insert an img element whose src attribute is given by the `icon_src` plugin method and `id` is computed by the parent plugin. It is quite annoying to be limited to an image. For example, I would like to propose an enhancement to cmsplugin-link which would show an icon and the text of the link.

So here is my proposal :

- add a method to text plugins, let say, `in_text_editor_repr`, which would return html content intended to be put in a span element. The span element would be managed by the parent plugin like the img current one.
- in order to maintain backward compat, it would be used only if both parent plugin and text plugin support it.

Does it fit well ? (I might have missed something)

**Comment by FinalAngel** [comment]
Closing in favour of divio/djangocms-text-ckeditor#143
