### ISSUE TITLE
IntegrityError when trying to recover deleted pages

### ISSUE THREAD

**Issue by marts** [divio/django-cms#3447]
I get the following error when trying to recover a 'previously published' deleted page:

> IntegrityError at /admin/cms/page/recover/285/
> insert or update on table "cms_title" violates foreign key constraint "cms_title_publisher_public_id_fkey"
> DETAIL:  Key (publisher_public_id)=(12) is not present in table "cms_title".

I'm using a postgis database, but also get the error with a standard postgres database (9.1 and 9.3). I'm able to recover deleted pages without error when using sqllite. Also, recovering pages that have never been published seems to be fine.

django-cms: 3.0.5, Django: 1.6.7, django-reversion: 1.8.2

**Comment by yakky** [comment]
Would you recheck this for 3.0.10?

**Comment by FinalAngel** [comment]
Checked in 3.2. Works there
