### ISSUE TITLE
render_placeholder and “Publish changes”

### ISSUE THREAD

**Issue by jrief** [divio/django-cms#3449]
When I edit a plugin in a placeholder from a CMS page, and save that plugin, then a blue button appears in the toolbar, so that I can “Publish changes” I just made.

When I edit a plugin for `{% render_placeholder mymodel_instance.my_placeholder %}` from a template for that model, and I save that plugin, then _no_ blue button appears in the toolbar, and I can't save changes made to that plugin.

How can I manage, that pages with ‘Placeholders outside the CMS’, behave like normal CMS pages?

**Comment by FinalAngel** [comment]
@yakky any progress on this?

**Comment by yakky** [comment]
@jrief @FinalAngel we must come up with a generic framework for draft/live versions of generic django models to accomplish this. Not something that will happen soon AFAIK

**Comment by czpython** [comment]
This works now.
I'm not 100% sure which release fixed this, I believe 3.4.
