### ISSUE TITLE
Hidden Add-Plugin button

### ISSUE THREAD

**Issue by glomium** [divio/django-cms#3456]
My Placeholder has two allowed Plugins (Filer -> Image and Generic -> XYZ). The UI shows the info, that I can scroll for more. This info overlays almost completely the XYZ Plugin-Button (which is selected [blue] in the screenshot), but the UI does not allow me to scroll.

![cmsissue](https://cloud.githubusercontent.com/assets/5639272/4302579/8caaf5bc-3e5b-11e4-9095-dd4e39d62e76.png)

Seen with Firefox 32.0 and Chromium 37.0

**Comment by yakky** [comment]
Duplicate of #3922 

This has been plaguing us for a very long time. I think this can be solved only by rethinking the structure mode UI (which is on our todo list)

**Comment by peterfarrell** [comment]
Shouldn't #3922 be marked as a dup and closed since this one was filed many months before?

**Comment by yakky** [comment]
I think leaving both open (even if duplicated) helps in tracking issues and allows to not miss potentially useful information

**Comment by mkoistinen** [comment]
Closed by #4014
