### ISSUE TITLE
Menu not working with large number of pages.

### ISSUE THREAD

**Issue by ogrimator** [divio/django-cms#3459]
I have a website with a large number of pages (over 9000). When I publish half of them a menu in not working anymore, `children` array is returned as an empty array. I tested this and number of published pages going over 4000 is causing the issue. 
Django==1.6.6
Django CMS==3.0.5

**Comment by FinalAngel** [comment]
closed in favour of https://github.com/divio/django-cms/issues/4597, feel free to continue the conversation here :)

**Comment by czpython** [comment]
Hello @ogrimator,
Are you able to reproduce this issue with latest cms (3.4.2)?

**Comment by ogrimator** [comment]
Hi @czpython,

I am very sorry to say, but I don't have the access to that database as I no longer work with the company.

**Comment by czpython** [comment]
No worries, closing for now.
Feel free to create a new ticket if this is still an issue.
