### ISSUE TITLE
[META] History related meta-issue

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#3494]
This is a meta issue to collect any history-related problem in 3.0:

 *  [x] #3700
 *  [ ] #3599
 *  [x] #3361 
 *  [x] #3358 
 *  [x] #3447 
 *  [x] #3320 
 *  [x] #3112
 *  [x] #3543 
 *  [x] #3823
 *  [ ] #3811
 *  [x] #3174

Possible fix for some of the above #3823

**Comment by czpython** [comment]
Closing in favor of labels + individual tickets.
