### ISSUE TITLE
Document the way to user custom user models in Django 1.7

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#3521]
Due to the way migration dependencies are resolved in Django 1.7, we need to make sure that the users will:
- [x] declare custom user model application before django CMS in `INSTALLED_APPS`
- [ ] define migrations prior to setting up django CMS _or_ before setting the `AUTH_USER_MODEL` parameter

See https://code.djangoproject.com/ticket/23599#comment:6, https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#substituting-a-custom-user-model for reference

**Comment by FinalAngel** [comment]
@yakky can this be closed?

**Comment by yakky** [comment]
@FinalAngel not really. At least we should investigate if any other issues remains. Let's keep it open. Assigning myself

**Comment by czpython** [comment]
@yakky Any updates on this?
