### ISSUE TITLE
We should redirect when serving a "guessed" page

### ISSUE THREAD

**Issue by evildmp** [divio/django-cms#3547]
Suppose we have a page with English and French translations:

    /en/car
    /fr/voiture

If a user visits `/fr/car`, the French version will be served *from the given URL*.

It seems:

* **correct** that the French version is served, even though the page slug (`car`) is wrong - it's a good guess by the CMS
* **incorrect** that it doesn't redirect to `/fr/voiture` when it does this (bad for SEO, for sane-looking URLs, for common-sense)

So on detecting this behaviour, we should issue a `301 permanent redirect`.

**Comment by czpython** [comment]
Fixed by the referenced forward ports.
