### ISSUE TITLE
Toolbar menus adopt global link color

### ISSUE THREAD

**Issue by ojii** [divio/django-cms#3561]
If you define a color for ``a:link, a:active, a:visited`` (I think the culprit is ``a:link``), the toolbar menus adopt that color. Arguably, this isn't the desired result and the menu items should be "protected" from global stylesheets.

**Comment by yakky** [comment]
@FinalAngel do you think we can handle this for 3.1?

**Comment by FinalAngel** [comment]
@yakky you can add it, I'll add it to my todos so I can check it out somewhat this month.

**Comment by yakky** [comment]
@FinalAngel thanks
