### ISSUE TITLE
Add "publish all" bulk action

### ISSUE THREAD

**Issue by Lacrymology** [divio/django-cms#3602]
When I make changes to static placeholders defined in my base template, I seem to need to publish them page by page.

I think this shouldn't really be necessary at all, but at least, something like the `publihser_publish` management command that can be done from the admin site would be good

**Comment by yakky** [comment]
Now that the pulk-publishing has been moved to the API it should be easier to get this into some sort of UI

**Comment by yakky** [comment]
Moving this post 3.1

**Comment by FinalAngel** [comment]
closed in favour of https://github.com/divio/django-cms/issues/4597
