### ISSUE TITLE
`manage.py cms check` shouldn't report warning for relationship to a plugin's own "base class"

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#3604]
I don't know if the use of an abstract class is related here, but in this project, I define an (abstract) base plugin model class, which is then extended with a concrete class, which is itself extended for another concrete plugin model.

So, we ultimately have these models defined in modules X and Y:

- X.A (CMSPlugin), abstract
    - X.B (A), concrete
        - Y.C (B), concrete

`python manage.py cms check` reports:
> project.apps.moduleX.models.B has a foreign key from project.apps.moduleY.models.C, but no "copy_relations" method defined. [WARNING]

Also a bit strange is that this warning is emitted 3X.

I think I was the last person to touch this bit of code, and will probably fix it at some point, but I didn't want to lose sight of this issue.

**Comment by yakky** [comment]
this is actually fixed by #3611 right?

**Comment by mkoistinen** [comment]
I haven't explicitly tested it, but it should now be fixed. Will test shortly, then close/comment as required.

**Comment by mkoistinen** [comment]
This should have gone into 3.0.10!

**Comment by mkoistinen** [comment]
Actually, this was already fixed in 3.0.8. Closing.
