### ISSUE TITLE
Frontend glitch for get_extra_local_plugin_menu_items() 

### ISSUE THREAD

**Issue by mishbahr** [divio/django-cms#3630]
I'm trying to add an additional item to content menu for a custom plugin. So I added this to my plugin.

        def get_extra_local_plugin_menu_items(self, request, plugin):
            return [
                PluginMenuItem(
                    _('Preview Wrapper'),
                    admin_reverse('responsive_wrapper_preview_mode'),
                    data={
                        'plugin_id': plugin.pk,
                        'csrfmiddlewaretoken': get_token(request),
                    },
                )
            ]

However the `PluginMenuItem` is not displayed :-( 

![screen shot 2014-11-30 at 23 53 51](https://cloud.githubusercontent.com/assets/1264089/5239937/3e927c6c-78ec-11e4-99af-533dcf6ce249.png)

When I inspected the element, it looks like the generated HTML is incorrect. 

    <div class="cms_submenu-item">
        <a href="" data-rel="ajax" data-on-success="REFRESH_PAGE"></a>
    </div> 

This is how it should look like:
 
    <div class="cms_submenu-item">
        <a href="/manage/cms/page/plugin/responsive_wrapper_plugin/preview/"  
            data-rel="ajax" data-post="..."  data-on-success="REFRESH_PAGE">
            Preview Wrapper
        </a>
    </div>

** ``data-post`` content has been omitted.

Screenshot:
 
![screen shot 2014-12-01 at 00 04 52](https://cloud.githubusercontent.com/assets/1264089/5239971/bc08fc38-78ed-11e4-8977-d15c7ee5c2b3.png)

I was able to get the 'PluginMenuItem' to show up using:

    def get_extra_global_plugin_menu_items(self, request, plugin):
        [...]

But this means `PluginMenuItem` will be added to every plugin context menu.

Am I doing something wrong?

**Comment by mkoistinen** [comment]
Completely able to reproduce. Now looking for the issue...

**Comment by mkoistinen** [comment]
@mishbahr OK, this will be fixed in an upcoming release: 3.0.10, which should be soon.

It was probably the easiest fix ever. You can use this functionality now––if you only have one item to display––by returning the PluginMenuItem directly, and not a list.

I think you're the first person to ever use this poorly documented (I'm improving this now!) and under tested feature.

**Comment by mishbahr** [comment]
Thanks @mkoistinen.
