### ISSUE TITLE
wrong mdgid for "Are you sure you want to %s this page?"

### ISSUE THREAD

**Issue by DylannCordel** [divio/django-cms#3641]
The msgid in django.po is "Are you sure you want to %%s this page?" but the real msgid should be "Are you sure you want to %s this page?" (only one "%").

The original msgid is from here : https://github.com/divio/django-cms/blob/support/3.0.x/cms/templates/admin/cms/page/tree/base.html#L57
And the msgid in django.po is here : https://github.com/divio/django-cms/blob/support/3.0.x/cms/locale/fr/LC_MESSAGES/django.po#L1256

**Comment by DylannCordel** [comment]
Sorry for this answer 13 days after, but I really think there should not be two "s" (main reason is that the string is not translated ;-), only the "action word" is in french, but second is that in "https://github.com/divio/django-cms/blob/support/3.0.x/cms/templates/admin/cms/page/tree/base.html#L57", you use "trans", and trans does not support string replacement, it is blockstrans which can process it with his own syntax (not %s but {{something}} if something is defined)

Issue must be reopened.

**Comment by yakky** [comment]
Replacement of `%s` is  done on the javascript side (it happens to use the same syntax as python one, but it totally different implementation: https://github.com/divio/django-cms/blob/support/3.0.x/cms/static/cms/js/modules/cms.changelist.js#L179)
Anyway the syntax is confusing the ``trans`` templatetag

**Comment by yakky** [comment]
At this stage we can only solve this by manually changing the ``po`` files before compiling them
In the long run we should change the string format

**Comment by yakky** [comment]
@FinalAngel due to interaction with template parsing by gettext, could we move to some other placeholder instead of `%s` in https://github.com/divio/django-cms/blob/support/3.0.x/cms/templates/admin/cms/page/tree/base.html#L57 (and adapt https://github.com/divio/django-cms/blob/support/3.0.x/cms/static/cms/js/modules/cms.changelist.js#L179 accordingly)?

**Comment by FinalAngel** [comment]
where would you suggest to move it @yakky ?

**Comment by yakky** [comment]
I mean: use a different character combination instead of "%s" and use something different so that gettext doesn't get confused

**Comment by FinalAngel** [comment]
sure, no problem to change this, but wouldn't know what to use...

**Comment by yakky** [comment]
Basically we can use whatever character combination
Any specific convention is common in the js world?

**Comment by mkoistinen** [comment]
Fixed by #3896.
