### ISSUE TITLE
copy plugins broken?

### ISSUE THREAD

**Issue by jerch** [divio/django-cms#3642]
After updating from 3.0.3 to 3.0.7 copying plugins to clipboard doesnt work anymore if the plugin is nested within another plugin. Seems the `request.POST['source_placeholder_id']` in `PlaceholderAdminMixin.copy_plugins` contains a totally wrong id (points to some other placeholder in the template).
A quickfix for my case was to fall back to the placeholder_id of the source_plugin since the database still got the right value:
```patch
--- placeholderadmin.py	2014-12-03 16:07:10.773331000 +0100
+++ placeholderadmin_fix.py	2014-12-03 16:09:16.933332000 +0100
@@ -308,6 +308,7 @@
                 inst, cls = source_plugin.get_plugin_instance(self)
                 plugins = inst.placeholder_ref.get_plugins_list()
             else:
+                source_placeholder = get_object_or_404(Placeholder, pk=source_plugin.placeholder_id)
                 plugins = list(
                     source_placeholder.cmsplugin_set.filter(tree_id=source_plugin.tree_id, lft__gte=source_plugin.lft,
                                                             rght__lte=source_plugin.rght).order_by('tree_id', 'level',

```
I wonder why you dont do it this way in the first place instead of relying on the request value. I guess I missed there something and it has side effect? Maybe you could have a look at it.

**Comment by yakky** [comment]
Fixed by #3728
