### ISSUE TITLE
Revisiting Placeholder Inheritance in frontend editing

### ISSUE THREAD

**Issue by imagescape** [divio/django-cms#3647]
@piquadrat @yakky 
Hoping to revisit the discussion and fix from way back in #1303

In the above issue, the decision was made to not display inherited plugins in edit mode. I wonder if an alternative solution might make sense now in version 3. For instance, I have a placeholder that looks something like this:
{% placeholder "content" inherit or %}
{% static_placeholder "global content" %}
{% endplaceholder %}

This makes it a bit more confusing, I think, to see the static_placeholder when on those child pages in edit mode. Perhaps displaying the inherited placeholder but returning an error through the messaging system if the user attempts to edit it on a sub page?

**Comment by czpython** [comment]
Closing as this fits our feature request criteria.
If you're still interested in this feature, please create a topic in the [Developers Mailing List](https://groups.google.com/forum/#!forum/django-cms-developers).
