### ISSUE TITLE
Save after updating slug should redirect to new slug

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#3655]
Currently if you change the slug for a page and save, you are redirected back to the page at the old slug, which gives a 404 error. The user should instead be redirected to the page's new slug.

**Comment by jsma** [comment]
There appears to be a javascript bug [here](https://github.com/divio/django-cms/blob/379e120659095fc54a3c51af0c141cb7072d7185/cms/static/cms/js/modules/cms.base.js#L74-L78). My javascript-fu is weak but when I use Chrome developer tools to set breakpoints, this code sets the `parent.location.href` but this does not force the browser to instantly redirect, so it always hits the `parent.location.reload()` which just reloads the current url instead of the url returned by `resolve`. Haven't got far enough in testing but have a hunch that the fix for this will also solve #3654.

**Comment by yakky** [comment]
@jsma this should be solved by #3894

**Comment by yakky** [comment]
@jsma  could you please test #3894?

**Comment by jsma** [comment]
I'm on develop and this does appear to resolve the issue.

**Comment by yakky** [comment]
@jsma thanks!

**Comment by mkoistinen** [comment]
Fixed by #3894
