### ISSUE TITLE
Structureboard eats 100% CPU, overheats my laptop

### ISSUE THREAD

**Issue by qris** [divio/django-cms#3663]
Opening structure view starts an interval timer that triggers 100 times a second, trying to replace all the placeholders, I think:

    var interval = 10;
    ...
    // setup an interval
    this.interval = setInterval(function () {
        $(window).trigger('resize.sideframe');
    }, interval);

<https://github.com/divio/django-cms/blame/develop/cms/static/cms/js/modules/cms.structureboard.js#L265>

Please could you reduce this to something sensible like once per second so that my poor laptop doesn't melt or shutdown from overheating?

**Comment by qris** [comment]
I can typically have this view open for 10-20 minutes while editing content on the frontend. 60 seconds is on this page is enough to cause my laptop to overheat and emergency shutdown. That makes it difficult to use DjangoCMS as you can imagine!

**Comment by evildmp** [comment]
That doesn't seem unusual (having the view open for 20 minutes, not the emergency shutdown).

**Comment by yakky** [comment]
@evildmp @qris @FinalAngel any progress on this?

**Comment by qris** [comment]
@yakky I did propose a solution already, but for some reason we're still arguing about whether it's acceptable.

Personally I think it's rather rare that placeholders should actually move around on the page (only when you save new content/delete old content on the page) and thus updating 1-4 times per second would be plenty to cope with this, while not eating 100% CPU. Or else the position detection code could be optimised to use less CPU.

**Comment by yakky** [comment]
@FinalAngel do we need to move the placeholders only when resizing the sideframe, right? Can't we just use a signal to handle this (or triggering the internal only when the sideframe is moved)?

**Comment by yakky** [comment]
@qris @FinalAngel how about 65bef2e ?

**Comment by FinalAngel** [comment]
it needs to be set on initial loading and resizing, that is correct @yakky :)

**Comment by yakky** [comment]
@FinalAngel Does the commit looks like a sane solution?

**Comment by FinalAngel** [comment]
@yakky isn't there the window event missing when resizing?

**Comment by yakky** [comment]
@FinalAngel window resizing is handled by the same bind has ``window.resize`` has the same type as ``window.resize.sidebar`` (where sidebar is the event namespace)

**Comment by FinalAngel** [comment]
right correct! thanks for the reminder @yakky

**Comment by yakky** [comment]
Good to merge, then :)

**Comment by mkoistinen** [comment]
Assigning myself to test.
