### ISSUE TITLE
relative path for cms.toolbar.sideframe.css

### ISSUE THREAD

**Issue by frensjan** [divio/django-cms#3665]
Hi,

In [cms/static/cms/js/modules/cms.sideframe.js](https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.sideframe.js) a css file (cms/css/cms.toolbar.sideframe.css) is referenced, but this is rendered as a relative path:
`cms/css/cms.toolbar.sideframe.css` instead of
`/static/cms/css/cms.toolbar.sideframe.css`

This causes the sidebar to shift up and under the Django-CMS toolbar.

Best regards,
Frens Jan

**Comment by miraculixx** [comment]
+1 Having the same problem. Tried to debug but couldn't figure out where the actual URL is generated so I "solved" it by automatically redirecting any .css access:

```
# your app's urls.py
urlpatterns += patterns('', 
  url(r'^.*/admin/.*/cms/css/(?P<file>.*\.css)/?', 
        lambda request, *args, **kwargs : redirect('/static/cms/css/{file}'.format(**kwargs)))
)
``` 

At least it gets rid of throwing server exceptions and breaking the client code. Any hints or even better some documentation on which parts of the system are involved in generating URL/URIs would be most helpful.

**Comment by michael-mri** [comment]
Had same problem (Django 1.8.4 and Django CMS 3.1.3). 
I managed to solve it by adding: `'django.core.context_processors.static'` to `'context_processors'` in  `OPTIONS` of `TEMPLATES` setting (formerly `TEMPLATE_CONTEXT_PROCESSORS` setting).

It seems like it was not included by default by `django-admin startproject`.

**Comment by FinalAngel** [comment]
@yakky is this the case?

**Comment by yakky** [comment]
@michael-mri the supported way to setup django CMS is by using djangocms-installer or by following documetation at http://django-cms.readthedocs.org/en/latest/how_to/install.html where ``'django.core.context_processors.static`` is documented.
I'm surprised it's not activated by default in Django, but defaults may with versions so the best thing is following the django CMS which provides all the required information to configure it correctly
