### ISSUE TITLE
Stuck in draft/structure mode

### ISSUE THREAD

**Issue by darbula** [divio/django-cms#3667]
When the user who has edit permission on certain page goes to draft/structure view and then navigates to some other page, one that he has no edit permission, he is stuck in draft/structure without any intuitive way back. This issue is easy to reproduce and very unfortunate for the end user.

**Comment by darbula** [comment]
Sorry for not replying sooner.
Since currently any page editor, with or without editing permission on the current page, can switch between structure and content view by pressing spacebar it is reasonable to show content-structure button, also.
If and when restriction is introduced it must be in such way that it affects both interfaces i.e. button and keyboard shortcut.

**Comment by yakky** [comment]
@darbula could you check if #3808 fixes the issue for you?

**Comment by kurosato** [comment]
quit

**Comment by darbula** [comment]
Sorry for the delay, it works but it is not consistent. I have not been able to find some regularity. Mostly the spacebar binding does not work, regardless of editing rights. All tests were performed as user that has editing rights only to some particular pages since super user and user with no editing rights do not have this issue.

**Comment by yakky** [comment]
@darbula this should have been fixed.
Tests performed with a non-super user with all django permissions but editing rights on one page only over the tree.
If the user go to a page with no editing rights it's forced in content mode and the spacebar is disabled.
If the user open the page which she has permission on, spacebar is enabled and structure/content selector is enabled.

**Comment by mkoistinen** [comment]
@yakky, in which release/build/branch/commit should this be fixed?

**Comment by yakky** [comment]
This has been released in 3.0.10, 
@darbula could you confirm this is fixed in 3.0.10?

**Comment by darbula** [comment]
Unfortunately, I'm not able to check until next week, sorry.

**Comment by darbula** [comment]
@yakky it is working as you described, thanks.
