### ISSUE TITLE
Running tests is difficult and errorful

### ISSUE THREAD

**Issue by evildmp** [divio/django-cms#3675]
http://dpaste.com/3H95DX7 (following the docs at http://docs.django-cms.org/en/support-3.0.x/contributing/testing.html#running-tests)

For example: 39 sekizai failures ("TemplateDoesNotExist: with_data.html" etc)

This is probably a documentation issue, but even if there are other issues, the documentation needs to be improved.

**Comment by yakky** [comment]
This can be closed, right?

**Comment by yakky** [comment]
@evildmp is this still relevant?

**Comment by evildmp** [comment]
I still get a lot of test failures thanks to frontend testing problems, on Mac OS X.

**Comment by FinalAngel** [comment]
@evildmp you need to make sure that Firefox is properly installed, works so far good for me :)

**Comment by benzkji** [comment]
at least it's linked from the official docs...

http://docs.django-cms.org/en/latest/contributing/testing.html#problems-running-the-tests
