### ISSUE TITLE
Test suite is fragile and error-prone

### ISSUE THREAD

**Issue by evildmp** [divio/django-cms#3684]
This is intended to be a general point-of-collection for feedback on our test suite: http://docs.django-cms.org/en/support-3.0.x/contributing/testing.html#running-tests

**Comment by yakky** [comment]
Is this still relevant?

**Comment by stuaxo** [comment]
This ticket still mentioned in docs

http://docs.django-cms.org/en/latest/contributing/testing.html

**Comment by FinalAngel** [comment]
thank you @stuaxo for pointing this out, we'll adapt it accordingly or welcome a PR :)

**Comment by FinalAngel** [comment]
Removed in latest release
