### ISSUE TITLE
urls_need_reloading signal not firing when slugs are changed

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#3689]
On 3.0.6, 3.0.7 and master (dabf832a10a7f0687610fb33d3103bcb984d3973) the ``urls_need_reloading`` signal does not fire in the following cases. But it should.:

* the slug of an app-hooked page changes (and the change is published)
* the app-hooked page is moved
* the slug of a parent page changes (and the change is published)

This might be a regression from #2911 .

**Comment by mkoistinen** [comment]
Closed by #3853. Thanks, @ojii!
