### ISSUE TITLE
Extra slash in url pattern when app attached to home page with APPEND_SLASH=False

### ISSUE THREAD

**Issue by ogrimator** [divio/django-cms#3691]
As in title, when I have app attached to home page and `APPEND_SLASH=False` then I'm getting 404 error with following url pattern:
` ^ ^/post$ [name='Post'] `
where my `urls.py` for my app looks like:
```python
urlpatterns = patterns( '',
	url(r'^post$', views.car_results, name='Post'),
)
```
Url pattern will work if I add another slash: `http://localhost:8000//post`.

**Comment by ogrimator** [comment]
Steps needed to reproduce:
1. Create new project using tutorial: [Django CMS tutorial](https://github.com/divio/django-cms-tutorial/)
2. Create new app `python manage.py startapp sampleapp`
3. Add app in settings and follow tutorial at: [Integration with app-hooks](http://django-cms.readthedocs.org/en/latest/extending_cms/app_integration.html#integration-apphooks)
4. Create home page and attach app to home page
5. Add `APPEND_SLASH=False` in `settings.py`
After last step is done, URL pattern for `sample_view` will not work.

**Comment by yakky** [comment]
@ogrimator does #3691 fixes this?
