### ISSUE TITLE
circular import when a 3rd party app imports cms.utils.plugins from models.py

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#3692]
On the develop branch (tested with https://github.com/divio/django-cms/commit/dabf832a10a7f0687610fb33d3103bcb984d3973) there seems to be a circular import if a 3rd party app imports ``cms.utils.plugins`` from its ``models.py``.

In this case the 3rd party app was after ``cms`` in ``INSTALLED_APPS``

**Comment by yakky** [comment]
@stefanfoulis should be fixed by #3828
Could you please recheck?

**Comment by yakky** [comment]
Clsed by #3828
