### ISSUE TITLE
better error message with custom user model

### ISSUE THREAD

**Issue by jschneier** [divio/django-cms#3699]
Hi and thanks for the project.

I was trying to reorganize my installed apps settings while also using a custom user model and my app `account` (where the custom user model is defined) was placed after `cms`. With this my app failed to boot with [this exception](https://github.com/divio/django-cms/blob/develop/cms/models/permissionmodels.py#L39-L42). It might make sense to mention that the `cms` app should come before the app that defines the custom user model in the exception text or elsewhere.

**Comment by mkoistinen** [comment]
Actually, this is already in the docs since v3.0.3: https://django-cms.readthedocs.org/en/support-3.0.x/reference/configuration.html#custom-user-requirements

Closing.
