### ISSUE TITLE
History/Undo menu should be disabled for non-CMS pages

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#3700]
Consider a cms page "Blog" with a blog apphook. The Post models have PlaceholderFields so they are editable from the front end. If you navigate to a blog post detail page and double click to edit, the toolbar still shows the History menu. If you click "Undo" this **does not** undo changes on the current post instance that is being edited, but instead appears to very unhelpfully undo changes on the cms Page the apphook is attached to. This can obviously lead to very unexpected behavior for content editors and should be removed from the toolbar when not rendering a page instance to avoid potential data loss.

**Comment by mkoistinen** [comment]
@GaretJax Can you comment on this one too?

**Comment by GaretJax** [comment]
It is definitely possible to put revision placeholder under revision control, but this needs cooperation from both plugin writers and support for it from the CMS.

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/5268
The Page entry on the toolbar has been disabled on non cms pages.
