### ISSUE TITLE
Make toolbar history work with placeholderfields

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#3701]
This is the flip-side to #3700. If the History menu remains in the toolbar at all times, then we need to document how users should integrate their custom apphook models that are editable from the front-end so that clicking 'Undo' actually impacts the model instance (e.g. blog post) being edited and not whichever Page the apphook is attached to.

**Comment by yakky** [comment]
This is not going to happen in 3.1, but definitely a much-needed improvements for django CMS

**Comment by czpython** [comment]
Closing as duplicate of https://github.com/divio/django-cms/issues/4920
