### ISSUE TITLE
Usage of deprecated mimetype parameter crashes Django 1.7+

### ISSUE THREAD

**Issue by timgraham** [divio/django-cms#3722]
On the `support/3.0.x` branch, `mimetype` should be `content_type` for Django 1.6+. On `develop` where we don't need support for Django 1.4/1.5, we don't need conditional logic at all.
```
cms/utils/admin.py:        return render_to_response(template, context, mimetype="text/html; charset=utf-8")
cms/admin/settingsadmin.py:            return HttpResponse(json.dumps(""), mimetype="application/json")
cms/admin/settingsadmin.py:        return HttpResponse(json.dumps(request.session.get('cms_settings', '')), mimetype="application/json")
```
Apparently tests for these code paths also need to be added. Are the code paths that use `content_type` unconditionally also untested as it seems that should fail on Django 1.4/1.5? (e.g. a1650839)

**Comment by yakky** [comment]
@timgraham shouldn't it be ``content_type`` for Django 1.5+ (https://docs.djangoproject.com/en/1.5/topics/http/shortcuts/#django.shortcuts.render_to_response)?
I don't think we have **any** test specific for these functions
Cleanup on develop will happen after 3.0.8 relese

**Comment by timgraham** [comment]
Correct, sorry I got the version wrong on that.

**Comment by yakky** [comment]
No worries :)
Fixing the 1.4 issue (I bet we don't have much users on 1.4, though)
I'll leave this open anyway for 3.1 to help writing more tests for such functions
