### ISSUE TITLE
[proxy] Multiple model placeholders in a custom plugin

### ISSUE THREAD

**Issue by ojii** [divio/django-cms#3723]
/cc @FinalAngel 

See http://stackoverflow.com/questions/27520734/django-cms-multiple-model-placeholders-in-a-custom-plugin

Is this a bug in django CMS? Is this a CSS issue, a documentation issue?

Just wanted to get some eyeballs on this.

**Comment by FinalAngel** [comment]
The Placeholders position within the structure view get positioned where the content would be. So currently if there are multiple placeholder at the same location, they get positioned absolute on each other..

**Comment by mkoistinen** [comment]
I'd like to also point out that these are the types of issues that my recent pull: #3595 aims to solve, but at the plugin level, not the placeholder level, like this one seems to require. If this was about plugins, I'd say this is a user-project implementation issue, but given that we do not supply any tools to deal with this at the placeholder level, I'm inclined to chalk this up as a CMS bug. Comments? @FinalAngel?

**Comment by FinalAngel** [comment]
yeah you could build in some collision detection @mkoistinen but than I'd rather go for the updated mode on 3.2 later on (where this does not matter anymore)

**Comment by FinalAngel** [comment]
updated the rendering in 3.2 :)
