### ISSUE TITLE
L10N of 'Settings' for Ukrainian

### ISSUE THREAD

**Issue by oblalex** [divio/django-cms#3727]
Please, fix `Yалаштування` to `Налаштування`  typo.

https://github.com/divio/django-cms/blob/cb836a668b9e53a642a35b768bf60bda39ac03fa/cms/locale/uk/LC_MESSAGES/django.po#L1431

**Comment by yakky** [comment]
You can use transifex (https://www.transifex.com/) to update the translations

**Comment by oblalex** [comment]
Well, no, I cannot. It says `You are not a member of this project`.

**Comment by yakky** [comment]
Fixed in transifex.
Thanks for reporting

**Comment by oblalex** [comment]
Great! Thank you very much!
