### ISSUE TITLE
View restriction permission confusing and poorly documented

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#3732]
When you go to Page->Permissions from the toolbar, you'll see global permissions display like:
![screen shot 2015-01-06 at 9 20 12 pm](https://cloud.githubusercontent.com/assets/24574/5639885/e3131744-95eb-11e4-8d4d-0146deb378d8.png)
A green checkbox under 'Can view', yay, that means that users in the Content Editors group 'can view' the page!

But when you click into the details, the language seems to be the opposite:
![screen shot 2015-01-06 at 9 20 22 pm](https://cloud.githubusercontent.com/assets/24574/5639887/fb94f2c4-95eb-11e4-92ee-ffc5ba2d67e0.png)
Now the view is 'restricted'?

The [documentation](http://docs.django-cms.org/en/latest/advanced/permissions_reference.html#view-restrictions) doesn't clarify matters.

> View restrictions can be set-up from the View restrictions formset on any cms page. Once a page has at least one view restriction installed, only users with granted access will be able to see that page. Mind that this restriction is for viewing the page as an end-user (front-end view), not viewing the page in the admin interface!

> View restrictions are also controlled by the CMS_PUBLIC_FOR setting. Possible values are all and staff. This setting decides if pages without any view restrictions are:

> viewable by everyone – including anonymous users (all)
> viewable by staff users only (staff)

It's unclear if 'front-end-view' means 'front-end **editing** view' or just what normal users see when visiting the site without being logged in as a special admin user (aka published pages only). 

It's also unclear without reading the source code how a global settings.py type setting interacts with admin configurable 'global' settings. If `CMS_PUBLIC_FOR = 'all'` and I click 'view restricted' what does that mean? Obviously we can't check any view permissions for anonymous users. What if I change it to 'staff'?

**Comment by evildmp** [comment]
What actually makes it possible to obtain the link "(global)" in the permissions display?

**Comment by evildmp** [comment]
Note correct documentation URL: http://docs.django-cms.org/en/support-3.0.x/topics/permissions.html
