### ISSUE TITLE
fix-tree command does not set position

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#3735]
For some as yet unknown reason, I've found plugins that have their position set to None (will open a ticket once I trace that bug down). Calling the fix-tree command does nothing to repair this since for CMSPlugin's, it just defers to django-treebeard's `fix_tree()` method, but of course django-treebeard knows nothing about django-cms's custom 'position' field.

This breaks the page since `cms.utils.plugins.build_plugin_tree()` attempts to [sort plugins](https://github.com/divio/django-cms/blob/develop/cms/utils/plugins.py#L283-L299) by ('parent_id', 'position'), resulting in a `TypeError: unorderable types: int() < NoneType()`

**Comment by jsma** [comment]
All plugins with position == None were orphaned plugins.

**Comment by yakky** [comment]
@jsma does this happens with #3661?
Orphaned plugins will go away in 3.1

**Comment by jsma** [comment]
Actually yes, the site is running on a branch with that PR already merged. I'm still not clear on how position got set to None, haven't had a chance to find the cause. Setting that aside, do you think there is value in making sure `position` matches what treebeard has to say about `path` in the fix-tree command?

**Comment by yakky** [comment]
@jsma definitely yes

**Comment by yakky** [comment]
@jsma addressed in #4009
