### ISSUE TITLE
Responsive design for toolbar problematic

### ISSUE THREAD

**Issue by Moini** [divio/django-cms#3739]
Trying to have a browser window and a terminal window open at the same time on my 4:3 screen for debugging, I encounter the problem that the publish button is hidden when the browser window is too small (and there is a glitch, too, when the button is shown below the bar)

Could maybe the toolbar be extended in height instead? Or could a dropdown be added which allows to have the publish button available even when the window is small?

This is the respective css rule:
#cms_toolbar .cms_toolbar-right {
    display: none;
}

![Uploading gone.png . . .]()
![Uploading in_between.png . . .]()
![Uploading still_normal.png . . .]()

**Comment by Moini** [comment]
Pictures here:

![2](https://cloud.githubusercontent.com/assets/3240233/5670022/c2c654e6-977c-11e4-805c-30c5848823cb.png)
![gone](https://cloud.githubusercontent.com/assets/3240233/5670023/c2f312c4-977c-11e4-9969-ee8bc70cb468.png)
![in_between](https://cloud.githubusercontent.com/assets/3240233/5670024/c2f78656-977c-11e4-9c18-e770e2a6ddc7.png)

**Comment by yakky** [comment]
@Moini thanks for reporting.
We are aware of this and working on a long term solution

**Comment by FinalAngel** [comment]
Fixed in 3.2

**Comment by Moini** [comment]
Thank you very much! :D
