### ISSUE TITLE
Toolbar CSS: many languages make the bottom languages unaccessible

### ISSUE THREAD

**Issue by Moini** [divio/django-cms#3742]
Hi,
when the languages dropdown gets too long, the bottom languages flow over the bottom of the browser window and are only accessible if I zoom out (see screenshots).

![normal](https://cloud.githubusercontent.com/assets/3240233/5691777/665b3f80-98d7-11e4-8115-ce5db623ff94.png)
![zoomed_out](https://cloud.githubusercontent.com/assets/3240233/5691778/66608346-98d7-11e4-9ca3-15bc519b3c43.png)

**Comment by mkoistinen** [comment]
Seems like moving the "Delete..." and "Copy all..." into sub-menus would go a long way to solving this.

**Comment by mkoistinen** [comment]
Fixed by #5026

**Comment by Moini** [comment]
Thanks to everyone involved! Is there a screenshot available somewhere? I'd love to know what the description means :)

**Comment by vxsx** [comment]
@Moini there is a screencast available http://d.pr/v/1brhI 
additionally - multiple copy all and delete translations are now grouped in the nested submenus
<img width="392" alt="screen shot 2016-05-16 at 18 30 57" src="https://cloud.githubusercontent.com/assets/366813/15296194/7df46eb4-1b94-11e6-9e78-1f11bdd90ba0.png">

**Comment by Moini** [comment]
I had watched the screencast, but that didn't show what it would look like in edit mode (which is what my main problem was with), there weren't any submenus. 
So thank you very much for that screenshot @vxsx! :D

Does 'Copy all plugins', when you hover over it, tell the user if it's 'to' or 'from'? (I know it's from, of course ;) )
