### ISSUE TITLE
Disclosure triangles in the structure-mode tree should cascade with opt/alt key

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#3747]
Very common UI is that when there is a collapsible tree, opt/alt-clicking the disclosure triangle will make the action cascade. So, if you click to open with the opt/alt key held, then all sub-members of the item you clicked on would open as well. Same for close.

**Comment by astagi** [comment]
I started working on this feature, check https://github.com/astagi/django-cms/tree/feature/openclosecascade

**Comment by mkoistinen** [comment]
Awesome!

**Comment by yakky** [comment]
@mkoistinen could you check the opened PR?

**Comment by FinalAngel** [comment]
confirmed fixed
