### ISSUE TITLE
Misleading error when server not available for AJAX requests

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#3748]
With runserver off, and attempting to edit a plugin on a page, the user gets the error message:

"SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://127.0.0.1:8000" from accessing a cross-origin frame."

**Comment by pajusmar** [comment]
Related issue #3028

**Comment by vxsx** [comment]
Should be fixed by #5360

**Comment by kalombos** [comment]
I have  the same error in chromium when i use S3 as storage for media files. I created simple plugin with ImageField and tried to view the image in edit mode and got the error. Does any solution exists?

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/5360
