### ISSUE TITLE
Foreign Key Constraint 

### ISSUE THREAD

**Issue by bbcreatv** [divio/django-cms#3756]
Im getting this error while running migrations. I'm not sure if its related to #2197 

    update or delete on table "cms_cmsplugin" violates foreign key constraint cmsplugin_ptr_id_refs_id_91e23e8a" on table "cmsplugin_gridcolumn"
    DETAIL:  Key (id)=(159) is still referenced from table "cmsplugin_gridcolumn".

**Comment by SalahAdDin** [comment]
use you the MIGRATION_MODULE setting?

**Comment by bbcreatv** [comment]
I did. here are my settings:

    MIGRATION_MODULES = {
	    'cms': 'cms.migrations_django',
	    'menus': 'menus.migrations_django',

	    # Add also the following modules if you're using these plugins:
	    'djangocms_file': 'djangocms_file.migrations_django',
	    'djangocms_flash': 'djangocms_flash.migrations_django',
	    'djangocms_googlemap': 'djangocms_googlemap.migrations_django',
	    'djangocms_inherit': 'djangocms_inherit.migrations_django',
	    'djangocms_link': 'djangocms_link.migrations_django',
	    'djangocms_picture': 'djangocms_picture.migrations_django',
	    'djangocms_snippet': 'djangocms_snippet.migrations_django',
	    'djangocms_teaser': 'djangocms_teaser.migrations_django',
	    'djangocms_video': 'djangocms_video.migrations_django',
	    'djangocms_text_ckeditor': 'djangocms_text_ckeditor.migrations_django',
	    'cmsplugin_filer_file': 'cmsplugin_filer_file.migrations_django',
	    'cmsplugin_filer_folder': 'cmsplugin_filer_folder.migrations_django',
	    'cmsplugin_filer_image': 'cmsplugin_filer_image.migrations_django',
	    'cmsplugin_filer_teaser': 'cmsplugin_filer_teaser.migrations_django',
	    'cmsplugin_filer_video': 'cmsplugin_filer_video.migrations_django',
	    'filer': 'filer.migrations_django',

	}

**Comment by bbcreatv** [comment]
Okay. I ran --fake and now its sorted. I hope..
