### ISSUE TITLE
Cancel button missing

### ISSUE THREAD

**Issue by Moini** [divio/django-cms#3759]
Hi all,
we just had an issue with a less experienced member of our crew doing the following:
- clicked 'delete page' on a main menu item which has child-items
- didn't thoroughly read the warning and saw no other option than to click on 'Yes, I'm sure' anyway, because there is no 'Cancel' button shown on the warning page

(result: all pages in that submenu, including their translations gone, recover deleted pages not working - but that's something for another bug ;) )

To make it as easy as possible, please add a Cancel button for this page.

**Comment by FinalAngel** [comment]
The cancel button is now shown anywhere >= 3.1

**Comment by Moini** [comment]
Thank you!
