### ISSUE TITLE
[CRITICAL] Djangocms-installer destroys directory content

### ISSUE THREAD

**Issue by holms** [divio/django-cms#3761]
I've been doing exactly as docs stated, and my whole directory been destroyed. Before that I've tried this in home directory, and all files were destroyed there too with this crash.

```
mkdir zavifoto
cd zavifoto
virtualenv .
source bin/activate
pip install djangocms-installer
```
```
(zavifoto)django@zavifoto:~/zavifoto$ djangocms -p . zavifoto
Database configuration (in URL format) [default sqlite://localhost/project.db]:
django CMS version (choices: 2.4, 3.0, stable, develop) [default stable]:
Django version (choices: 1.4, 1.5, 1.6, 1.7, stable) [default stable]: 1.7
Activate Django I18N / L10N setting (choices: yes, no) [default yes]:
Install and configure reversion support (choices: yes, no) [default yes]:
Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: lt,en,ru
Optional default time zone [default America/Chicago]: Europe/Vilnius
Activate Django timezone support (choices: yes, no) [default yes]: yes
Activate CMS permission management (choices: yes, no) [default yes]:
Use Twitter Bootstrap Theme (choices: yes, no) [default no]: yes
Use custom template set [default no]:
Load a starting page with examples after installation. Choose "no" if you use a custom template set. (choices: yes, no) [default no]: yes
Traceback (most recent call last):
  File "/home/django/zavifoto/bin/djangocms", line 11, in <module>
  File "/home/django/zavifoto/local/lib/python2.7/site-packages/djangocms_installer/main.py", line 47, in execute
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 22] Invalid argument: '.'
```

No files left..

```
(zavifoto)django@zavifoto:~/zavifoto$ ls
(zavifoto)django@zavifoto:~/zavifoto$ ls -lah
total 8.0K
drwxrwxr-x 2 django django 4.0K Jan 14 22:33 .
drwxr-xr-x 5 django django 4.0K Jan 14 22:31 ..
```

This is the latest ubuntu instance on digital ocean.

```
(zavifoto)django@zavifoto:~/zavifoto$ uname -a
Linux zavifoto 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Just checked on OSX Yosemite, it works fine, with same version of pip. On ubuntu, I've destroyed instance 3 times already, and it destroys parent directory every time a run this installer.

**Comment by yakky** [comment]
djangocms-installer 0.7.1 has been released with the clarification (and check at runtime) that `-p` should be an empty directory (it's where the project and the ``manage.py`` are to be created) and the installer will ask before removal in case of issues.

**Comment by holms** [comment]
@yakky

1) it doesn't matter if it's actually removes something or not (he removes *PARENT* directory, which is definitely not what you want.)
2) You *REALLY* don't want this kind of option in django-cms guide, to avoid people destroying their home dir. 
3) We've got a crash in here, not just a removal ok? Please fix a crash. Because of crash it removed, parent dir, not current dir files. This is a HUGE difference, I've just lost whole home directory. Thanks god it was on my VPS and I have backups.

**Comment by yakky** [comment]
Version 0.7.1 of the installer solves both the crash *and* the cleanup-without-asking first.
Actually the ``-p `` refers to the main project directory, not the directory containing projects, that's why originally the installer didn't asked for permission to remove it.
This has been clarified in the installer docs anyway and it will be updated in the django CMS docs too

**Comment by evildmp** [comment]
@holms Thanks for your report. It's probably not your intention, but the tone of your comments comes across as less courteous than we expect in django CMS discussions. 

Please don't shout. These projects are only possible if we are careful in how we communicate, especially when we are frustrated or feel that someone else has not understood something properly. This is greatly appreciated by us all.
