### ISSUE TITLE
Only superuser can edit placeholder which is outside of CMS, when not integrated into AdminInterface

### ISSUE THREAD

**Issue by mabau** [divio/django-cms#3762]
Setup when this problem occurs:
   1) defined placeholder outside of CMS
   2) no AdminIntegration defined for the model that holds the PlaceholderField

Then only a superuser can add/modify plugins that are inside the placeholder, even if the user has all rights on the model that holds the PlaceholderField. Essentially this makes it mandatory to create AdminIntegration for models with PlaceholderField. If this is the intended behavior this should be indicated in the documentation.
I would argue it should be possible to not have an AdminIntegration, since Placeholders can be created programatically.

The Placeholder uses PlaceholderAdminMixin to detect "attached fields" in its method _get_attached_fields. If no AdminMixin exists, the attached field list is empty. When the Placeholder is defined outside the CMS also "page" is none, resulting in an implicit "return None"  in Placeholder._get_permission -> only superuser can use this Placeholder.

In my application I do not need  an AdminIntegration for my model, since the model and the placeholder are created in the code, not in the AdminInterface.

**Comment by yakky** [comment]
Admin integration is required for placeholder to work correctly
You can exclude admin from showing into the admin dashboard by using ``get_model_perms`` (see http://stackoverflow.com/questions/2431727/django-admin-hide-a-model)
