### ISSUE TITLE
Superuser unable to add to PERMISSION_ADMIN_INLINES in PageAdmin

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#3763]
I've extended the Page with some extra settings but in the PageAdmin I appear to be missing the permission in `if obj and 'permission' in request.path:`

I've written it up on SO & I'm about to go googling for PERMISSION_ADMIN_INLINES; http://stackoverflow.com/questions/27962971/extend-django-cms-pageadmin-with-an-inline-model

**Comment by yakky** [comment]
The documented API to add information and settings to page and titles is documented at http://django-cms.readthedocs.org/en/support-3.0.x/how_to/extending_page_title.html and allows adding data to both Page (language-indipendent) and Titles (language-dependent) models.
Currently there is no official way to directly extend the PageAdmin.

**Comment by marksweb** [comment]
Thanks, I've extended the page link that before so ended up switching to that. It's just that I had found a SO answer & blog post from a guy making out that you could add inlines to the PageAdmin so wanted to do that to avoid the Page menu in the toolbar becoming huge & page related settings from being disjointed.

**Comment by yakky** [comment]
@marksweb could you point me to the original SO answer?

**Comment by marksweb** [comment]
@yakky sure, it's old, but the theory in it seemed like it would work;
http://stackoverflow.com/a/10296046/1199464

**Comment by yakky** [comment]
@marksweb we can actually make it easier, please post comments on #3566 so we build a consensus on how to implement this
