### ISSUE TITLE
404 when logging out after creating a new page without publishing

### ISSUE THREAD

**Issue by samuelblattner** [divio/django-cms#3766]
I get a 404 with the following steps:
- Login to cms
- create a new page
- leave it unpublished
- logout via toolbar menu sitename > logout username

Might be related to #2770

**Comment by yakky** [comment]
@samuelblattner could you please test #3894?

**Comment by samuelblattner** [comment]
@yakky Tested #3894 (#3654, #3655, #3766) successfully. The issues no longer occurred.

**Comment by mkoistinen** [comment]
Fixed by #3894
