### ISSUE TITLE
Feature request: When deleting parent, offer to keep children and move them up one layer

### ISSUE THREAD

**Issue by Moini** [divio/django-cms#3773]
Hi,

When you delete a parent page, usually all children are deleted, too.
It would be nice if instead, django-cms asked if you want to keep the child pages and if you choose yes, just moves them into the layer where the parent page was. 
This is probably not so easy to implement, but it would be really nice.

**Comment by FinalAngel** [comment]
@Moini this feature might be a bit to specific. We rather implement a shift+click capability where you can drag items together out than another prompt to move them.

**Comment by Moini** [comment]
Okay, thanks for mulling it over!
