### ISSUE TITLE
500 errors after moving an apphook

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#3775]
Earlier I moved an apphook from one page to another. The steps were: 1) remove the apphook from the source page, save the changes and then delete the source page so there should be no existing reference to the apphook attached to any page...then 2) add the app to the destination page and save. There were several subsequent restarts of Apache afterwards and no caching is configured at the moment. Everything seemed fine but then got several alert emails when someone apparently accessed the old url where the apphook used to be attached. 

    Internal Server Error: /videos/
    Traceback (most recent call last):
      File "../env/src/django/django/core/handlers/base.py", line 111, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "../env/src/django-cms/cms/utils/decorators.py", line 11, in inner
        if page:
      File "../env/src/django/django/utils/functional.py", line 224, in inner
        self._setup()
      File "../env/src/django/django/utils/functional.py", line 357, in _setup
        self._wrapped = self._setupfunc()
      File "../env/src/django-cms/cms/middleware/page.py", line 20, in <lambda>
        request.current_page = SimpleLazyObject(lambda: get_page(request))
      File "../env/src/django-cms/cms/middleware/page.py", line 14, in get_page
        request._current_page_cache = applications_page_check(request)
      File "../env/src/django-cms/cms/appresolver.py", line 45, in applications_page_check
        page = Page.objects.public().get(id=page_id)
      File "../env/src/django/django/db/models/query.py", line 357, in get
        self.model._meta.object_name)
    cms.models.pagemodel.DoesNotExist: Page matching query does not exist.

This is not very scientific of me but since restarting Apache did not solve the problem I deleted all *.pyc files and restarted Apache again for good measure. Voila! The pages now returned 404's instead of 500's. Have not had a chance to debug further but making a note here so I can circle back and sort this out later. It may turn out to be a nothing burger and that my memories of restarting Apache earlier were false. But I did test this on a beta server before doing the same on production and am 99% confident I restarted Apache in both cases multiple times each afterwards.

**Comment by yakky** [comment]
Can't reproduce this. Looks like a caching issue

**Comment by yakky** [comment]
@jsma did you managed to reprodroduce this?

**Comment by jsma** [comment]
Haven't had a chance to look at it, will try to soon (traveling atm).

**Comment by jsma** [comment]
There seems to be a significant difference between `sudo service apache2 reload` and `sudo service apache2 restart`. The former does not sufficiently purge the old state and leads to the error above where a proper `restart` seems to fully refresh the state of the app, no errors. 

Any insights on why django-cms code would still be lingering in RAM after a `reload`? This is in a production-like environment with DEBUG = False (can't reproduce when DEBUG = True). Again, there are no CACHES configured, just the 'dummy' cache. So no actual caching beyond what Apache/Python does with byte code.

**Comment by yakky** [comment]
ok, this worth further investigation
It's an apache+mod_wsgi setup? If so, do you use mod_wsgi daemon mode?
Does touching the wsgi file trigger the same behavior?

**Comment by jsma** [comment]
Yak shaving at the moment, running into additional mod_wsgi errors which is preventing me from consistently replicating. Will update once I've made progress debugging this.

**Comment by jsma** [comment]
Can no longer reproduce this bug on 3.1.0rc1.

**Comment by shadow-identity** [comment]
Have same bug with 3.1.0rc2. I've installed newsblog. After moving apphook from one page to another one I can't get access to blog records by their slugs.
http://localhost/en/blog-record-2/
```
Page not found (404)
Request Method:	GET
Request URL:	http://localhost/en/blog-record-2/
Using the URLconf defined in mysite.urls, Django tried these URL patterns, in this order:
^media/(?P<path>.*)$
^static\/(?P<path>.*)$
^en/ ^admin/
^en/ ^sitemap\.xml$
^en/ ^ ^blog/$ [name='article-list']
^en/ ^ ^blog/feed/$ [name='article-list-feed']
^en/ ^ ^blog/search/$ [name='article-search']
^en/ ^ ^blog/(?P<year>\d{4})/$ [name='article-list-by-year']
^en/ ^ ^blog/(?P<year>\d{4})/(?P<month>\d{1,2})/$ [name='article-list-by-month']
^en/ ^ ^blog/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$ [name='article-list-by-day']
^en/ ^ ^blog/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<pk>\d+)/$ [name='article-detail']
^en/ ^ ^blog/(?P<slug>\w[-\w]*)/$ [name='article-detail']
^en/ ^ ^blog/(?P<year>\d{4})/(?P<slug>\w[-\w]*)/$ [name='article-detail']
^en/ ^ ^blog/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>\w[-\w]*)/$ [name='article-detail']
^en/ ^ ^blog/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<slug>\w[-\w]*)/$ [name='article-detail']
^en/ ^ ^blog/author/(?P<author>\w[-\w]*)/$ [name='article-list-by-author']
^en/ ^ ^blog/category/(?P<category>\w[-\w]*)/$ [name='article-list-by-category']
^en/ ^ ^blog/category/(?P<category>\w[-\w]*)/feed/$ [name='article-list-by-category-feed']
^en/ ^ ^blog/tag/(?P<tag>\w[-\w]*)/$ [name='article-list-by-tag']
^en/ ^ ^blog/tag/(?P<tag>\w[-\w]*)/feed/$ [name='article-list-by-tag-feed']
^en/ ^ ^(?P<slug>[0-9A-Za-z-_.//]+)/$ [name='pages-details-by-slug']
^en/ ^ ^$ [name='pages-root']
^en/ ^blog/
The current URL, /en/blog-record-2/, didn't match any of these.
```

**Comment by shadow-identity** [comment]
please look at my comment above @yakky

**Comment by shadow-identity** [comment]
sorry, all works fine. I've restarted app before, but only now it makes all works fine.
