### ISSUE TITLE
`list apphooks` should sort and clarify its output

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#3776]
Currently if you run `./manage.py cms list apphooks` you'll get slightly confusing output:

    VideosApp
    EventApp
    VideosApp
    EventApp
    PressReleaseApp
    NewsApp
    PressReleaseApp
    NewsApp

This could be consolidated to something like:

    EventApp (draft/published)
    NewsApp (draft/published)
    PressReleaseApp (draft/published)
    VideosApp (draft/published)

If the draft/published state is unnecessary, then it can be omitted.

**Comment by yakky** [comment]
I like the proposal!

**Comment by yakky** [comment]
Thanks @jsma for proposing this! Closed through #4585
