### ISSUE TITLE
Path '.' already exists and is not empty, please choose a different one

### ISSUE THREAD

**Issue by Hiieu** [divio/django-cms#3777]
Error occurs after `djangocms -p . mysite`

**Comment by yakky** [comment]
@Hiieu : what's the content of "." directory?

**Comment by savega** [comment]
I have the same issue. I just tried going through the demo. The "." only contains the env folder as suggested by the demo tutorial. https://github.com/divio/django-cms-tutorial/blob/master/Step%201%20-%20Initial%20Setup.md

**Comment by Hiieu** [comment]
@yakky: The only folders with '.' in my directory are /.git/ and /.idea/

**Comment by yakky** [comment]
@savega Please check the updated version at http://django-cms.readthedocs.org/en/support-3.0.x/introduction/install_from_scratch.html

**Comment by yakky** [comment]
@Hiieu would you test https://github.com/nephila/djangocms-installer/archive/feature/hidden_files.zip, please?

**Comment by 00091701** [comment]
Hi @yakky,

I have the same problem. And your "patch" does not work for me.

(env) C:\Temp\dj\ProjectSite>djangocms --db sqlite://localhost/project.db --cms-version stable --django-version stab
le --i18n yes --reversion yes --languages de --timezone Europe/Berlin --use-tz yes --permissions yes --bootstrap yes --s
tarting-page yes -p . projekt
Database configuration (in URL format) [default sqlite://localhost/project.db]:
django CMS version (choices: 2.4, 3.0, stable, develop) [default stable]:
Django version (choices: 1.4, 1.5, 1.6, 1.7, stable) [default stable]:
Activate Django I18N / L10N setting (choices: yes, no) [default yes]:
Install and configure reversion support (choices: yes, no) [default yes]:
Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported
by Django can be used here [default de]:
Optional default time zone [default Europe/Berlin]:
Activate Django timezone support (choices: yes, no) [default yes]:
Activate CMS permission management (choices: yes, no) [default yes]:
Use Twitter Bootstrap Theme (choices: yes, no) [default yes]:
Use custom template set [default no]:
Load a starting page with examples after installation. Choose "no" if you use a custom template set. (choices: yes, no)
[default yes]:
Path '.' already exists and is not empty, please choose a different one

**Comment by yakky** [comment]
@00091701 what is the content of ``ProjectSite`` directory?

**Comment by 00091701** [comment]
Hi @yakky,

this is my template for a new cms test environment.

create a dir in "c:\Temp" or "/tmp" (and change into it)

mkdir ProjectSite
cd ProjectSite

virtualenv --no-site-packages env
source env/bin/activate
pip install pillow
pip install djangocms-installer

djangocms --db sqlite://localhost/project.db --cms-version stable --django-version stable --i18n yes --reversion yes --languages de --timezone Europe/Berlin --use-tz yes --permissions yes --bootstrap yes --starting-page yes -p . projekt

after that I get the output above.

(In the "ProjectSite" directory I have only the "env" directory.)

**Comment by yakky** [comment]
@00091701 added a ``-s`` flag to skip the check in case like yours

**Comment by 00091701** [comment]
@yakky ,

after a "long" time I get this error:
Failure occurred. Do you want to cleanup by removing C:\Temp\dj\ProjectSite? [Y/N]

I called:
(env) C:\Temp\dj\ProjectSite>djangocms --db sqlite://localhost/project.db --cms-version stable --django-version stable --i18n yes --reversion yes --languages de --timezone Europe/Berlin --use-tz yes --permissions yes --bootstrap yes --starting-page yes -p . -s projekt

**Comment by yakky** [comment]
After ansering yes or not to that message you should get the error that triggered the failure (this can be due to problem with library compilation, etc)

**Comment by Hiieu** [comment]
I created completely empty folder and type in my console `djangocms -p . mysite` and I have no error with Path '.' already exist..., but a new error is showing:
`Failure occurred. Do you want to cleanup by removing C:\Dropbox\venv\portfolio\testing? [Y/N]` 

I don't if I should create a new issue

**Comment by yakky** [comment]
See answer above :)

**Comment by 00091701** [comment]
@yakky ,

I hope I can help you with this:
Failure occurred. Do you want to cleanup by removing C:\Temp\dj\ProjectSite? [Y/N] y
Removing everything under C:\Temp\dj_dh1\ProjectSite
Traceback (most recent call last):
  File "C:\Temp\dj\ProjectSite\env\Scripts\djangocms-script.py", line 9, in <module>
  File "C:\Temp\dj\ProjectSite\env\lib\site-packages\djangocms_installer\main.py", line 30, in execute
  File "C:\Temp\dj\ProjectSite\env\lib\site-packages\djangocms_installer\django\__init__.py", line 43, in create_pro
ject
  File "c:\Python27\Lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\Python27\Lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "c:\Python27\Lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "c:\Python27\Lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 ist keine zulõssige Win32-Anwendung

**Comment by yakky** [comment]
Ok, could you open an issue on nephila/djangocms-installer for this? it's a different issues

**Comment by Hiieu** [comment]
So basically I should reinstall django-cms?

**Comment by yakky** [comment]
@Hiieu ``pip install -U https://github.com/nephila/djangocms-installer/archive/feature/hidden_files.zip`` and relaunch the installer command

**Comment by Hiieu** [comment]
@yakky: 

Here what I did:

Create new project directory
Create venv
(env) pip install djangocms-installer

When I try to install your hidden_files.zip from your link I got this error:

```
pip can't proceed with requirement 'argparse from https://pypi.python.org/packages/2.7/a/argparse/argparse-1.3.0-py2.py3-none-any.whl#md5=c89395a1a43b61ca6a116aed5e3b1d59 (from djang
ocms-installer==0.7.1.post1)' due to a pre-existing build directory.
 location: c:\users\hp\appdata\local\temp\pip_build_HP\argparse
This is likely due to a previous installation that failed.
pip is being responsible and not assuming it can delete this.
Please delete it and try again.

Storing debug log for failure in C:\Users\HP\pip\pip.log

```

So I download `https://github.com/nephila/djangocms-installer/archive/feature/hidden_files.zip` and  unpack then install in my project.

But I still get this error after `djangocms -p . mysite`

```
Failure occurred. Do you want to cleanup by removing C:\Users\HP\Dropbox\venv\portfolio3\blabla? [Y/N]
Traceback (most recent call last):
  File "C:\Python27\Scripts\djangocms-script.py", line 9, in <module>
    load_entry_point('djangocms-installer==0.7.1.post1', 'console_scripts', 'djangocms')()
  File "C:\Python27\lib\site-packages\djangocms_installer-0.7.1.post1-py2.7.egg\djangocms_installer\main.py", line 57, in execute
    if strtobool(choice) or config_data.noinput:
  File "C:\Python27\lib\distutils\util.py", line 325, in strtobool
    raise ValueError, "invalid truth value %r" % (val,)
ValueError: invalid truth value ''

```

**Comment by yakky** [comment]
Ok, this is unrelated to the original issue. Could you reopen on https://github.com/nephila/djangocms-installer ?
Actually windows support in djangocms-installer it not very well tested 
Closing this and moving discussion to the installer repo
