### ISSUE TITLE
Enable plugins for an HTMLField within a FrontEndEditable model

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#3778]
I've just been asked to add the 'CMS Plugins' button to the text editor in an existing model which appears to use the `FrontendEditableAdminMixin`.

At the moment it's a standard setup using `djangocms_text_ckeditor.fields.HTMLField` but the change form renders without the 'CMS Plugins' button. Do you need to specify plugins to allow within the field in order to get this to display?

```
    class LatestNews(models.Model):    
        title = models.CharField(max_length=200)
        slug = models.SlugField(
            max_length=255, db_index=True, blank=True, null=True, help_text=_('Auto generated')
        )
        body = HTMLField(null=True, blank=True)

    class LatestNewsAdmin(admin.ModelAdmin, FrontendEditableAdminMixin):
        date_hierarchy = 'publish_date'
        frontend_editable_fields = ('title', 'body', 'publish_date')
        readonly_fields = ('publish_date',)
        list_display = ('id', 'title', 'is_active', 'order', 'publish_date')
        list_editable = ('is_active',)
        ordering = ('-publish_date',)
        search_fields = ('title', 'body')

    admin.site.register(LatestNews, LatestNewsAdmin)
```

I know you can specify a configuration but from what I've seen that's more for limiting fields to be displayed. Essentially what I've been asked for is the default from TextPlugin.

**Comment by yakky** [comment]
CMSPlugin are enabled only for text plugin, as children plugin cannot work without an underlying text plugin.
HTMLField is for "standard" models only, which does not support plugin nesting

**Comment by marksweb** [comment]
Great thanks yakky, that makes sense :)
