### ISSUE TITLE
Copying page with app hook to a different site_id fails constraint

### ISSUE THREAD

**Issue by peterfarrell** [divio/django-cms#3782]
I have a need to copy all pages from one site to a new site id.  I have a script that uses `page.copy_page(...)` however it fails with a unique constraint error when you try to copy a page that associated with an app hook: 

```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "cms_page_publisher_is_draft_382d2913a1d40b79_uniq"
DETAIL:  Key (publisher_is_draft, application_namespace)=(t, et_wpq) already exists.
```

The problem is that the `unique_together` for the application_namespace does not include the `site`.

```python
    class Meta:
        permissions = (
            ('view_page', 'Can view page'),
            ('publish_page', 'Can publish page'),
        )
        unique_together = (("publisher_is_draft", "application_namespace"), ("reverse_id", "site", "publisher_is_draft"))
```
https://github.com/divio/django-cms/blob/1b0f7a2c9d17af631630279c96f91a8f8306747a/cms/models/pagemodel.py#L122

I have looked at how hooked in apps are pulled in the urls.py with the `appresolver.py` and that uses the "site" in the QS filter.

**Comment by yakky** [comment]
Closed by #3785
