### ISSUE TITLE
Document the plugin order in INSTALLED_APPS

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#3784]
Since develop **all** plugins **must** be defined **after** ``cms``
We need to add this to the documentation (both in the upgrade section and in the normal project setup.
Especially ``djangocms_text_ckeditor`` which still is documented to be installed before ``cms``

**Comment by jsma** [comment]
I asked about `djangocms_text_ckeditor` on the [mailing list](https://groups.google.com/d/msg/django-cms-developers/On3-nFwgxeM/t3HwRhdu6kcJ) but didn't get a reply whether the recommendation to place before `cms` was valid documentation. What is happening now that requires all plugins to be listed after (sorry if I missed some announcement/changelog)? 

I'm still trying to wrap my head around the app registry in Django 1.7 (and realize y'all have semi-officially committed to supporting Django 1.6 for now) but can it be used to avoid the startup magic that requires finicky ordering of installed apps?

**Comment by yakky** [comment]
@jsma It took a while to find out the answer for the text plugin: the order is not relevant anymore.
It used to be relevant prior 3.0 for the plugin to be able to use its own templates instead of the CMS one (because it shares the template structure with the text plugin that used to be shipped with django CMS < 3).
Order **should** not be relevant anymore, but actually I find that Django 1.7 migrations are a bit tricky at resolving dependencies, so I'd say that a good advice would be cms first, then all the plugins

**Comment by jsma** [comment]
If the documented best practice then is to put all plugins *after* `cms`, and if using a custom user model to put that *before* `cms`, I think that at least resolves the issue I mentioned on the mailing list. I'll open a ticket to clarify the docs on the text plugin side of things.

**Comment by evildmp** [comment]
Fixed in #3951
