### ISSUE TITLE
urls no longer take into account setting of APPEND_SLASH

### ISSUE THREAD

**Issue by morganwahl** [divio/django-cms#3788]
This commit: https://github.com/divio/django-cms/commit/c2cd800b4ea9038b027b1079ac3d6cc8914005c7

seems to have accidentally made the `'pages-details-by-slug'` regex the same regardless of what `APPEND_SLASH` is set to. Presumably this will re-introduce whatever problem was in this issue: https://github.com/divio/django-cms/issues/284

**Comment by yakky** [comment]
Duplicate of #3691 
Fixed by #3758

**Comment by mkoistinen** [comment]
Fixed in 3.0.x. by commit: 49eb3b0cfbf62c5b87ef1501ac63204f763dbfbf. Removed 3.0.10 tag.

Tagged with 3.1 so it is not overlooked in that branch.

**Comment by yakky** [comment]
Fixed in #3872 by merging back support/3.0.x
