### ISSUE TITLE
Fully touch-capable version of the CMS

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#3796]
This issue relates to #3688, but is more general. We need the CMS to be 100% touch-friendly both for end-users (site-visitors) and content managers.

Ideally, someone with a dual-input capable machine will assist with this? A machine that supports both touch-input and mouse-input simultaneously.

Any takers?

**Comment by mkoistinen** [comment]
Is this something that can be tested with Selenium? Does it support emulation of dual-input devices?

**Comment by FinalAngel** [comment]
Done in 3.2 :)
