### ISSUE TITLE
French gettext translation does not work in 3.0.9 and 3.0.8

### ISSUE THREAD

**Issue by GabLeRoux** [divio/django-cms#3798]
Hey there, 
I generated a new site with the awesome [djangocms-installer](https://github.com/nephila/djangocms-installer) tool and realised after a while that django-cms is not being translated to the user's language. 

## Steps to reproduce:

	$ pip install --upgrade virtualenv
	$ virtualenv env
	$ source env/bin/activate
	(env) $ pip install djangocms-installer
	(env) $ djangocms -p . omg
	Database configuration (in URL format) [default sqlite://localhost/project.db]:
	django CMS version (choices: 2.4, 3.0, stable, develop) [default stable]:
	Django version (choices: 1.4, 1.5, 1.6, 1.7, stable) [default stable]:
	Activate Django I18N / L10N setting (choices: yes, no) [default yes]:
	Install and configure reversion support (choices: yes, no) [default yes]:
	Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: fr, en
	Optional default time zone [default America/Chicago]:
	Activate Django timezone support (choices: yes, no) [default yes]:
	Activate CMS permission management (choices: yes, no) [default yes]:
	Use Twitter Bootstrap Theme (choices: yes, no) [default no]:
	Use custom template set [default no]:
	Load a starting page with examples after installation. Choose "no" if you use a custom template set. (choices: yes, no) [default no]: yes

As you can see, I've used most of the defaults and djangocms is not using french, but everything else does. Note the order of the languages; ***fr, en***. Tell me if I'm wrong, but I think this sets the main language to french and gives user's the ability to translate content in english too.

## Generated `settings.py`:

**note that `SECRET_KEY` you see here is not being used anywhere** ;)

    import os
    gettext = lambda s: s
    DATA_DIR = os.path.dirname(os.path.dirname(__file__))
    """
    Django settings for omg project.

    For more information on this file, see
    https://docs.djangoproject.com/en/1.6/topics/settings/

    For the full list of settings and their values, see
    https://docs.djangoproject.com/en/1.6/ref/settings/
    """

    # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
    import os
    BASE_DIR = os.path.dirname(os.path.dirname(__file__))

    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/1.6/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = '@j#r%*#u&2v!yxih1n11e)4gg%k+)1bm&=mdhdcpzn9#ptn597'

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True

    TEMPLATE_DEBUG = True

    ALLOWED_HOSTS = []

    # Application definition

    ROOT_URLCONF = 'omg.urls'

    WSGI_APPLICATION = 'omg.wsgi.application'

    # Database
    # https://docs.djangoproject.com/en/1.6/ref/settings/#databases

    # Internationalization
    # https://docs.djangoproject.com/en/1.6/topics/i18n/

    LANGUAGE_CODE = 'fr'

    TIME_ZONE = 'America/Chicago'

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/1.6/howto/static-files/

    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(DATA_DIR, 'media')
    STATIC_ROOT = os.path.join(DATA_DIR, 'static')

    STATICFILES_DIRS = (
        os.path.join(BASE_DIR, 'omg', 'static'),
    )
    SITE_ID = 1

    TEMPLATE_LOADERS = (
        'django.template.loaders.filesystem.Loader',
        'django.template.loaders.app_directories.Loader',
        'django.template.loaders.eggs.Loader'
    )

    MIDDLEWARE_CLASSES = (
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.locale.LocaleMiddleware',
        'django.middleware.doc.XViewMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'cms.middleware.user.CurrentUserMiddleware',
        'cms.middleware.page.CurrentPageMiddleware',
        'cms.middleware.toolbar.ToolbarMiddleware',
        'cms.middleware.language.LanguageCookieMiddleware'
    )

    TEMPLATE_CONTEXT_PROCESSORS = (
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
        'django.core.context_processors.i18n',
        'django.core.context_processors.debug',
        'django.core.context_processors.request',
        'django.core.context_processors.media',
        'django.core.context_processors.csrf',
        'django.core.context_processors.tz',
        'sekizai.context_processors.sekizai',
        'django.core.context_processors.static',
        'cms.context_processors.cms_settings'
    )

    TEMPLATE_DIRS = (
        os.path.join(BASE_DIR, 'omg', 'templates'),
    )

    INSTALLED_APPS = (
        'djangocms_admin_style',
        'djangocms_text_ckeditor',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.admin',
        'django.contrib.sites',
        'django.contrib.sitemaps',
        'django.contrib.staticfiles',
        'django.contrib.messages',
        'cms',
        'menus',
        'sekizai',
        'mptt',
        'djangocms_style',
        'djangocms_column',
        'djangocms_file',
        'djangocms_flash',
        'djangocms_googlemap',
        'djangocms_inherit',
        'djangocms_link',
        'djangocms_picture',
        'djangocms_teaser',
        'djangocms_video',
        'south',
        'reversion',
        'omg'
    )

    LANGUAGES = (
        ## Customize this
        ('fr', gettext('fr')),
        ('en', gettext('en')),
    )

    CMS_LANGUAGES = {
        ## Customize this
        'default': {
            'public': True,
            'hide_untranslated': False,
            'redirect_on_fallback': True,
        },
        1: [
            {
                'public': True,
                'code': 'fr',
                'hide_untranslated': False,
                'name': gettext('fr'),
                'redirect_on_fallback': True,
            },
            {
                'public': True,
                'code': 'en',
                'hide_untranslated': False,
                'name': gettext('en'),
                'redirect_on_fallback': True,
            },
        ],
    }

    CMS_TEMPLATES = (
        ## Customize this
        ('fullwidth.html', 'Fullwidth'),
        ('sidebar_left.html', 'Sidebar Left'),
        ('sidebar_right.html', 'Sidebar Right')
    )

    CMS_PERMISSION = True

    CMS_PLACEHOLDER_CONF = {}

    DATABASES = {
        'default':
            {'ENGINE': 'django.db.backends.sqlite3', 'NAME': 'project.db', 'HOST': 'localhost', 'USER': '', 'PASSWORD': '', 'PORT': ''}
    }

Maybe this has something to do with djangocms-installer directly. I first asked a [question on stackoverflow](http://stackoverflow.com/questions/28140779/django-cms-not-using-users-language-for-its-core-translations) about this, it contains a bit more infos and screenshots.

**Comment by yakky** [comment]
Could you please open this on djangocms-installer repository?

**Comment by yakky** [comment]
Apparently there is something wrong with the french translations in django CMS
Any other language combination looks fine
Could you try downgrading to django CMS 3.0.7? (``pip install django-cms==3.0.7``)

**Comment by GabLeRoux** [comment]
You are right, this works fine with `django-cms==3.0.7`, it is broken in `django-cms==3.0.8` and `django-cms==3.0.9`.

**Comment by yakky** [comment]
Thanks for checking. Will change the title for this issue

**Comment by mkoistinen** [comment]
I would like some clarity here. I've taken the steps above to produce an django-cms installation with the primary language as 'fr'. The provided sample content appears in EN, but the CMS believes this is FR ('cause it was configured as such). Also, the CMS UI (toolbar, etc.) is appropriately all in FR.

It seems to me this is simply a matter of the djangocms-installer installing the same sample content (which happens to be in EN) regardless of the selected language.

I've also replaced the CMS with 3.0.7 and saw the same, exact behaviour. Unless I am missing something, this is *not* a blocker, but is a simple matter of the djangocms-installer not providing sample content in arbitrary languages. I would say that is reasonable and if anything, this is an issue for djangocms-installer, not the CMS itself.

Soliciting further comments here.

**Comment by mkoistinen** [comment]
OK. This appears to be some sort of caching issue. I notice that it does change the admin UI to the selected language, eventually, but it seems to take a couple of attempts. I'm trying to produce a concise and repeatable sequence as this should help pinpoint the issue.

I see exactly the same behaviour in 3.0.7 as well.

**Comment by mkoistinen** [comment]
@GabLeRoux Can you see if this patch fixes it for you? Its based off latest `Support/3.0.x` branch.

    pip uninstall django-cms && pip install https://github.com/mkoistinen/django-cms/archive/mkoistinen-feature/better_handle_user_language_change.zip

Please let me know!

**Comment by GabLeRoux** [comment]
I tried what you just mentioned, but django-cms is still being displayed in english.

I opened web inspector with setting `Disable cache (while DevTools is open)` enabled so I don't have any cache issue here and did exactly this:

1. Clicked on `User settings...` http://127.0.0.1:8000/fr/admin/cms/usersettings/ (opens in the left sidebar)
2. From `fr` to `en`, hit save.
3. Refresh the hole page.

  a. *Everything is in english (including settings left sidebar)*

4. From `en` to `fr`, hit save.
5. Refresh the hole page.

  a. *Left sidebar in french, django-cms's toolbar still in english.*

6. From `fr` to `fr`, hit save.
7. Refresh the hole page.

  a. *Nothing changed*

I tried repeating a couple of times but it did not change. Tested on `django-cms==3.0.9`

@mkoistinen Did you use djangocms-installer?

It's not a blocker for me (but maybe a liitle for the client :v:, not quite sure about that yet). I took a look at the release notes and Ill stick with `django-cms==3.0.7` for the moment as french is working fine there.

To downgrade from `django-cms==3.0.9` to `django-cms==3.0.7`, I had to run this:

    $ pip install django-cms==3.0.7 django-mptt==0.6.1

Everything is in french this way. I tried going back to `django-cms==3.0.9` again but goes back to english.

**Comment by GabLeRoux** [comment]
@mkoistinen Oh, sent this at the same time you did :P  I ran

    pip uninstall django-cms && pip install https://github.com/mkoistinen/django-cms/archive/mkoistinen-feature/better_handle_user_language_change.zip

installed fine, `pip freeze | grep django-cms`

    django-cms==3.0.10.dev1

Still in english, tried to save settings and still in english.

**Comment by mkoistinen** [comment]
OK. Hmmm, I wonder now if I've "fixed" the wrong problem. During my testing, I was looking at the menu names across the toolbar to be sure they were shown in FR or EN. They seem correct. However, now that you mention it, the menus below these are always in EN.

**Comment by GabLeRoux** [comment]
I had no difference with `3.0.10.dev1`:
![en](https://cloud.githubusercontent.com/assets/1264761/5990925/b46ea3b0-a999-11e4-8c47-1a97a862875f.png)
This is how it looks like on `3.0.7`
![fr](https://cloud.githubusercontent.com/assets/1264761/5990924/b463e218-a999-11e4-9b2f-2d68111fb2e5.png)

When you say menu names, are you talking about `Page`, `Language` and `Live`?

**Comment by BertrandBordage** [comment]
Same issue here, the toolbar stays in English while the rest of the project is correctly translated.  It was working with 3.0.7.

**Comment by yakky** [comment]
Could you check if https://github.com/yakky/django-cms/archive/feature/remove_fr_fr.zip solves the issue?

**Comment by yakky** [comment]
Ping @GabLeRoux @BertrandBordage could you check PR #3841 ?

**Comment by BertrandBordage** [comment]
@yakky I tested, it works :)
@GabLeRoux you can easily test using `pip install https://github.com/yakky/django-cms/archive/feature/remove_fr_fr.zip`

**Comment by yakky** [comment]
Great!

**Comment by GabLeRoux** [comment]
It seems like it is partially working, see screenshot

![django-translate](https://cloud.githubusercontent.com/assets/1264761/6149617/f2d37676-b1d7-11e4-9b13-093b8e8faa77.png)

**Comment by BertrandBordage** [comment]
@GabLeRoux I don’t have the same problem. Did you fully restart your dev server? New locales are not taken into account if you don’t stop then restart it. Is your locale `fr` or `fr_FR`?

**Comment by GabLeRoux** [comment]
Oh indeed, did not restart server. I'll do that tonight ;)

**Comment by GabLeRoux** [comment]
I confirm that after restarting the server, this works just fine, thanks alot, you guys are the best :)
