### ISSUE TITLE
Cleanups when dropping Django 1.6

### ISSUE THREAD

**Issue by timgraham** [divio/django-cms#3802]
When to do so hasn't been decided yet.

- [ ] `setup.py`: Python 2.6 classifier and minimum Django version (south also?)
- [ ] `from __future__ import with_statement` (for Python 2.6)
- [ ] Replace `SortedDict` with `collections.OrderedDict` (need Python 2.7 min.)
- [ ] `cms.test_utils.compat` (skipIf unittest2 stuff) (need Python 2.7 min.)
- [ ] Usage of `cms.utils.compat.DJANGO_1_6`
- [ ] Replace from `django.utils.importlib` with `importlib` (need Python 2.7 min.)

**Comment by yakky** [comment]
South can be removed when 1.6 will be dropped
Thanks for this great todo list

**Comment by FinalAngel** [comment]
aggregated in https://github.com/divio/django-cms/issues/4580
