### ISSUE TITLE
Non-existent method Page.get_title_object

### ISSUE THREAD

**Issue by BertrandBordage** [divio/django-cms#3812]
If you specify a language to `ExtensionToolbar.get_title_extension_admin`, it calls `Page.get_title_object`, which doesn’t exist.  This should probably be `Page.get_title_obj` instead.

**Comment by mkoistinen** [comment]
@yakky, it appears a fix has already been merged. Can/should we close this issue, or are we keeping it open so we can ensure the same fix is in develop?

**Comment by yakky** [comment]
Uhm, autoclosing seem not consistent ...
Closing this. Merge back from support to develop it's still possible, I'd prefer going along this way
