### ISSUE TITLE
TypeError: 'dict_keys' object does not support indexing

### ISSUE THREAD

**Issue by jedie** [divio/django-cms#3816]
I get a "TypeError: 'dict_keys' object does not support indexing" in "cms/models/pagemodel.py", line 819, in get_admin_tree_title":

![error](https://cloud.githubusercontent.com/assets/71315/6037953/27e3778c-ac59-11e4-8da1-07d9bffe7a4c.PNG)

Maybe this has been fixed, because the current version looks completely different: https://github.com/divio/django-cms/blob/develop/cms/models/pagemodel.py

His error happens with:
Django 	1.7.4
django CMS 	3.0.9

**Comment by yakky** [comment]
When does this exception pops up? Which cache backend are you using?

**Comment by jedie** [comment]
cache backend: ```django.core.cache.backends.locmem.LocMemCache```

Seems that this happens if no Title exist.

Think ```language = self.title_cache.keys()[0]``` is just not python 3 compatible.
Fix: ```language = list(self.title_cache.keys())[0]```

**Comment by yakky** [comment]
Which operation triggers the error?

**Comment by jedie** [comment]
Access the admin pages.

**Comment by yakky** [comment]
Could you check the linked PR?

**Comment by mkoistinen** [comment]
Thanks for the PR, @yakky.
