### ISSUE TITLE
A lot of pages (about 500) pages in django CMS - HELP!!!

### ISSUE THREAD

**Issue by carina21** [divio/django-cms#3817]
Hello, i have questions about the django CMS page tree:
- I have a lot of pages (about 500) in my django CMS an the overview of the page tree is very confusing and it takes me very long to scroll to bottom or find pages and move them in the tree. So my question is, is there a way to group/sort the pages by the creation-year or something else, automatically?
 - Does the django-cms developer Team plan to implement such a function to group pages by creation-year in the page tree in the next release?
 - Can I implement such a function? I need this feature very soon and need your answer!

Please contact me!
Yours,
Carina

**Comment by yakky** [comment]
Which django CMS version are you using?
you can use the search to go search for desired page.
There is no plan to implement a date-based listvies of the pages

**Comment by carina21** [comment]
I use django cms version 3.
I know the search function to get desired pages.
But i mean when I get the whole page tree with a lot of pages that haven't subpages the page tree is very long and confusing - i have to scroll - so i can't see easily the structure of pages that are on the end.
So it would be good to implement an easy structure to handle houndred of pages!
Do you get me?

**Comment by yakky** [comment]
I get what you mean
At the moment there is no plan to implement such a feature, though

**Comment by evildmp** [comment]
@carina21 Are you able to use page hierarchies to mitigate this, to categorise them?

**Comment by carina21** [comment]
Yes, it would be the one and only solution, but what do you exactly mean with page hierarchies?
Should I create subpages for hierarchies?

**Comment by FinalAngel** [comment]
will be fixed in #4597
