### ISSUE TITLE
Pages link deactivated if the user does not have permissions on the current site

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#382]
Some users may have permissions to edit multiple sites. If they login on a site they don't have permissions on, the "Pages" link to the change_list view in appindex is not linked (although there would be pages on other sites that the user could edit). Once on the change_list view with a site selected that the user has permission on (eg "/admin/cms/page/?site__exact=6") all is ok again and the dropdown appears with all sites the user can edit.
Screenshot http://imm.io/aUY

**Comment by FinalAngel** [comment]
@stefanfoulis is this still relevant?
