### ISSUE TITLE
Exception when adding sibling page

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#3820]
In a clean project if I create a Home page, then two child pages (Child 1, Child 3), then attempt to add a sibling in between (Child 2) I get the following traceback:

    Environment:

    Request Method: POST
    Request URL: http://localhost:9000/en-us/admin/cms/page/add/?language=en-us&target=3&position=right

    Django Version: 1.7.4
    Python Version: 3.4.2
    Installed Applications:
    ('djangocms_admin_style',
     'djangocms_text_ckeditor',
     'django.contrib.auth',
     'django.contrib.contenttypes',
     'django.contrib.sessions',
     'django.contrib.admin',
     'django.contrib.sites',
     'django.contrib.sitemaps',
     'django.contrib.staticfiles',
     'django.contrib.messages',
     'cms',
     'treebeard',
     'menus',
     'sekizai',
     'djangocms_link',
     'reversion',
     'my_demo')
    Installed Middleware:
    ('django.contrib.sessions.middleware.SessionMiddleware',
     'django.middleware.csrf.CsrfViewMiddleware',
     'django.contrib.auth.middleware.AuthenticationMiddleware',
     'django.contrib.messages.middleware.MessageMiddleware',
     'django.middleware.locale.LocaleMiddleware',
     'django.middleware.doc.XViewMiddleware',
     'django.middleware.common.CommonMiddleware',
     'django.middleware.clickjacking.XFrameOptionsMiddleware',
     'cms.middleware.user.CurrentUserMiddleware',
     'cms.middleware.page.CurrentPageMiddleware',
     'cms.middleware.toolbar.ToolbarMiddleware',
     'cms.middleware.language.LanguageCookieMiddleware')

    Traceback:
    File "../lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
      111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
    File "../lib/python3.4/site-packages/django/contrib/admin/options.py" in wrapper
      583.                 return self.admin_site.admin_view(view)(*args, **kwargs)
    File "../lib/python3.4/site-packages/django/utils/decorators.py" in _wrapped_view
      105.                     response = view_func(request, *args, **kwargs)
    File "../lib/python3.4/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
      52.         response = view_func(request, *args, **kwargs)
    File "../lib/python3.4/site-packages/django/contrib/admin/sites.py" in inner
      206.             return view(request, *args, **kwargs)
    File "../src/django-reversion/src/reversion/revisions.py" in do_revision_context
      296.                 return func(*args, **kwargs)
    File "../src/django-cms/cms/admin/pageadmin.py" in add_view
      410.         return super(PageAdmin, self).add_view(request, form_url, extra_context=extra_context)
    File "../lib/python3.4/site-packages/django/contrib/admin/options.py" in add_view
      1453.         return self.changeform_view(request, None, form_url, extra_context)
    File "../lib/python3.4/site-packages/django/utils/decorators.py" in _wrapper
      29.             return bound_func(*args, **kwargs)
    File "../lib/python3.4/site-packages/django/utils/decorators.py" in _wrapped_view
      105.                     response = view_func(request, *args, **kwargs)
    File "../lib/python3.4/site-packages/django/utils/decorators.py" in bound_func
      25.                 return func.__get__(self, type(self))(*args2, **kwargs2)
    File "../lib/python3.4/site-packages/django/db/transaction.py" in inner
      394.                 return func(*args, **kwargs)
    File "../lib/python3.4/site-packages/django/contrib/admin/options.py" in changeform_view
      1404.                 self.save_model(request, new_object, form, not add)
    File "../src/django-cms/cms/admin/pageadmin.py" in save_model
      246.                 language,
    File "../src/django-cms/cms/models/managers.py" in set_or_create
      151.             return self.create(**data)
    File "../lib/python3.4/site-packages/django/db/models/manager.py" in manager_method
      92.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
    File "../lib/python3.4/site-packages/django/db/models/query.py" in create
      372.         obj.save(force_insert=True, using=self.db)
    File "../lib/python3.4/site-packages/django/db/models/base.py" in save
      589.                        force_update=force_update, update_fields=update_fields)
    File "../src/django-cms/cms/models/titlemodels.py" in save_base
      89.         ret = super(Title, self).save_base(*args, **kwargs)
    File "../lib/python3.4/site-packages/django/db/models/base.py" in save_base
      613.                                   update_fields=update_fields)
    File "../lib/python3.4/site-packages/django/dispatch/dispatcher.py" in send
      198.             response = receiver(signal=self, sender=sender, **named)
    File "../src/django-cms/cms/signals/title.py" in pre_save_title
      40.         instance.page.save(no_signals=True)
    File "../src/django-cms/cms/models/pagemodel.py" in save
      444.                 self.save_base(**kwargs)
    File "../src/django-cms/cms/models/pagemodel.py" in save_base
      467.         return super(Page, self).save_base(*args, **kwargs)
    File "../lib/python3.4/site-packages/django/db/models/base.py" in save_base
      617.             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
    File "../lib/python3.4/site-packages/django/db/models/base.py" in _save_table
      679.                                       forced_update)
    File "../lib/python3.4/site-packages/django/db/models/base.py" in _do_update
      723.         return filtered._update(values) > 0
    File "../lib/python3.4/site-packages/django/db/models/query.py" in _update
      600.         return query.get_compiler(self.db).execute_sql(CURSOR)
    File "../lib/python3.4/site-packages/django/db/models/sql/compiler.py" in execute_sql
      1004.         cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
    File "../lib/python3.4/site-packages/django/db/models/sql/compiler.py" in execute_sql
      786.             cursor.execute(sql, params)
    File "../lib/python3.4/site-packages/django/db/backends/utils.py" in execute
      81.             return super(CursorDebugWrapper, self).execute(sql, params)
    File "../lib/python3.4/site-packages/django/db/backends/utils.py" in execute
      65.                 return self.cursor.execute(sql, params)
    File "../lib/python3.4/site-packages/django/db/utils.py" in __exit__
      94.                 six.reraise(dj_exc_type, dj_exc_value, traceback)
    File "../lib/python3.4/site-packages/django/utils/six.py" in reraise
      658.             raise value.with_traceback(tb)
    File "../lib/python3.4/site-packages/django/db/backends/utils.py" in execute
      65.                 return self.cursor.execute(sql, params)
    File "../lib/python3.4/site-packages/django/db/backends/sqlite3/base.py" in execute
      485.         return Database.Cursor.execute(self, query, params)

    Exception Type: IntegrityError at /en-us/admin/cms/page/add/
    Exception Value: UNIQUE constraint failed: cms_page.path

**Comment by jsma** [comment]
I've updated my bare bones [cmsdemo](https://github.com/jsma/cmsdemo/tree/django-cms-3820) app with instructions on how to reproduce.

**Comment by jsma** [comment]
This is a regression introduced in the switch from django-mptt to django-treebeard. The error does not appear in 3df86e1554208e7db4b73d529f1e6304ef3317c3 but appeared as soon as the treebeard branch was merged in c6b8b6cd96f2f5dcbfc327ed48fa971ef40c6d8f.

If you have the following tree:

    Home
    /  \
    A  C

You currently cannot add a new node 'B' to the right of 'A' since it will be given the same path as node 'C' leading to the exception above. You *can* add a node to the right of 'C' since there isn't a node currently there.

**Comment by jsma** [comment]
I'm not smart enough at the moment to know where this is a treebeard bug or a bug in how django-cms is using it. Below is the output of stepping through with ipdb and logging all the SQL queries. I've left the noise in the SQL so its exactly the output of each corresponding line of Python.

In `pageadmin.py`, it calls save on the new page:

    > ../django-cms/cms/admin/pageadmin.py(225)save_model()
        224                     obj.parent_id = target.parent_id
    --> 225                 obj.save()
        226                 obj.move(target, pos=position)

This results in the following SQL:

    SELECT "cms_page"."id", "cms_page"."path", "cms_page"."depth", "cms_page"."numchild", "cms_page"."created_by", "cms_page"."changed_by", "cms_page"."parent_id", "cms_page"."creation_date", "cms_page"."changed_date", "cms_page"."publication_date", "cms_page"."publication_end_date", "cms_page"."in_navigation", "cms_page"."soft_root", "cms_page"."reverse_id", "cms_page"."navigation_extenders", "cms_page"."template", "cms_page"."site_id", "cms_page"."login_required", "cms_page"."limit_visibility_in_menu", "cms_page"."is_home", "cms_page"."application_urls", "cms_page"."application_namespace", "cms_page"."publisher_is_draft", "cms_page"."publisher_public_id", "cms_page"."languages", "cms_page"."revision_id", "cms_page"."xframe_options" FROM "cms_page" WHERE "cms_page"."id" = 9 LIMIT 21
    SELECT "cms_page"."id", "cms_page"."path", "cms_page"."depth", "cms_page"."numchild", "cms_page"."created_by", "cms_page"."changed_by", "cms_page"."parent_id", "cms_page"."creation_date", "cms_page"."changed_date", "cms_page"."publication_date", "cms_page"."publication_end_date", "cms_page"."in_navigation", "cms_page"."soft_root", "cms_page"."reverse_id", "cms_page"."navigation_extenders", "cms_page"."template", "cms_page"."site_id", "cms_page"."login_required", "cms_page"."limit_visibility_in_menu", "cms_page"."is_home", "cms_page"."application_urls", "cms_page"."application_namespace", "cms_page"."publisher_is_draft", "cms_page"."publisher_public_id", "cms_page"."languages", "cms_page"."revision_id", "cms_page"."xframe_options" FROM "cms_page" WHERE "cms_page"."id" = 9 LIMIT 21
    SELECT DISTINCT "menus_cachekey"."key" FROM "menus_cachekey" WHERE "menus_cachekey"."site" = 1
    DELETE FROM "menus_cachekey" WHERE "menus_cachekey"."site" = 1
    UPDATE "cms_page" SET "path" = '00010003', "depth" = 2, "numchild" = 0, "created_by" = 'demo', "changed_by" = 'demo', "parent_id" = 1, "creation_date" = '2015-02-05 01:58:31.501234+00:00', "changed_date" = '2015-02-05 02:00:13.269021+00:00', "publication_date" = NULL, "publication_end_date" = NULL, "in_navigation" = true, "soft_root" = false, "reverse_id" = NULL, "navigation_extenders" = NULL, "template" = 'INHERIT', "site_id" = 1, "login_required" = false, "limit_visibility_in_menu" = NULL, "is_home" = false, "application_urls" = NULL, "application_namespace" = NULL, "publisher_is_draft" = true, "publisher_public_id" = NULL, "languages" = NULL, "revision_id" = 0, "xframe_options" = 0 WHERE "cms_page"."id" = 9
    SELECT "cms_page"."template" FROM "cms_page" WHERE ("cms_page"."path" IN ('0001') AND NOT ("cms_page"."template" = 'INHERIT')) ORDER BY "cms_page"."depth" ASC LIMIT 1
    SELECT "cms_placeholder"."id", "cms_placeholder"."slot", "cms_placeholder"."default_width" FROM "cms_placeholder" INNER JOIN "cms_page_placeholders" ON ( "cms_placeholder"."id" = "cms_page_placeholders"."placeholder_id" ) WHERE "cms_page_placeholders"."page_id" = 9

After saving the object, here's what we have in the db:

    > [(p.id, p.path) for p in Page.objects.all()]
    [(1, '0001'), (3, '00010001'), (4, '00010002'), (9, '00010003'), (2, '0002')]

Id 9 is the new page pk and its path is '00010003'.
Next, it calls the treebeard `move()` method:

    > /Users/john-scott/Projects/django-cms/cms/admin/pageadmin.py(226)save_model()
        225                 obj.save()
    --> 226                 obj.move(target, pos=position)
        227         page_type_id = form.cleaned_data.get('page_type')

This results in the following SQL:

    SELECT "cms_page"."id", "cms_page"."path", "cms_page"."depth", "cms_page"."numchild", "cms_page"."created_by", "cms_page"."changed_by", "cms_page"."parent_id", "cms_page"."creation_date", "cms_page"."changed_date", "cms_page"."publication_date", "cms_page"."publication_end_date", "cms_page"."in_navigation", "cms_page"."soft_root", "cms_page"."reverse_id", "cms_page"."navigation_extenders", "cms_page"."template", "cms_page"."site_id", "cms_page"."login_required", "cms_page"."limit_visibility_in_menu", "cms_page"."is_home", "cms_page"."application_urls", "cms_page"."application_namespace", "cms_page"."publisher_is_draft", "cms_page"."publisher_public_id", "cms_page"."languages", "cms_page"."revision_id", "cms_page"."xframe_options" FROM "cms_page" WHERE ("cms_page"."depth" = 2 AND "cms_page"."path" BETWEEN '00010000' AND '0001ZZZZ') ORDER BY "cms_page"."path" DESC LIMIT 1
    SELECT "cms_page"."id", "cms_page"."path", "cms_page"."depth", "cms_page"."numchild", "cms_page"."created_by", "cms_page"."changed_by", "cms_page"."parent_id", "cms_page"."creation_date", "cms_page"."changed_date", "cms_page"."publication_date", "cms_page"."publication_end_date", "cms_page"."in_navigation", "cms_page"."soft_root", "cms_page"."reverse_id", "cms_page"."navigation_extenders", "cms_page"."template", "cms_page"."site_id", "cms_page"."login_required", "cms_page"."limit_visibility_in_menu", "cms_page"."is_home", "cms_page"."application_urls", "cms_page"."application_namespace", "cms_page"."publisher_is_draft", "cms_page"."publisher_public_id", "cms_page"."languages", "cms_page"."revision_id", "cms_page"."xframe_options" FROM "cms_page" WHERE ("cms_page"."depth" = 2 AND "cms_page"."path" BETWEEN '00010000' AND '0001ZZZZ' AND "cms_page"."path" > '00010001') ORDER BY "cms_page"."path" ASC
    SELECT "cms_page"."id", "cms_page"."path", "cms_page"."depth", "cms_page"."numchild", "cms_page"."created_by", "cms_page"."changed_by", "cms_page"."parent_id", "cms_page"."creation_date", "cms_page"."changed_date", "cms_page"."publication_date", "cms_page"."publication_end_date", "cms_page"."in_navigation", "cms_page"."soft_root", "cms_page"."reverse_id", "cms_page"."navigation_extenders", "cms_page"."template", "cms_page"."site_id", "cms_page"."login_required", "cms_page"."limit_visibility_in_menu", "cms_page"."is_home", "cms_page"."application_urls", "cms_page"."application_namespace", "cms_page"."publisher_is_draft", "cms_page"."publisher_public_id", "cms_page"."languages", "cms_page"."revision_id", "cms_page"."xframe_options" FROM "cms_page" WHERE ("cms_page"."depth" = 2 AND "cms_page"."path" BETWEEN '00010000' AND '0001ZZZZ') ORDER BY "cms_page"."path" DESC LIMIT 1
    UPDATE "cms_page" SET path='00010005'||SUBSTR(path, 9) WHERE path LIKE '00010003%'
    UPDATE "cms_page" SET path='00010004'||SUBSTR(path, 9) WHERE path LIKE '00010003%'
    UPDATE "cms_page" SET path='00010003'||SUBSTR(path, 9) WHERE path LIKE '00010002%'
    UPDATE "cms_page" SET path='00010002'||SUBSTR(path, 9) WHERE path LIKE '00010005%'

The UPDATE calls at the end look wacky. It updates the path for the new page.id == 9 first to '00010005', but then immediately updates it to '00010004'. Then it changes page 4 to have the old path of page 9. This is where things go wrong.

The next bit of code to hit the database is the call to create the title for the page:

    > /Users/john-scott/Projects/django-cms/cms/models/managers.py(152)set_or_create()
    --> 151             return self.create(**data)
        152         for name in base_fields:

This triggers the error since the associated page 9 object still has its old path attribute in memory, it hasn't been refreshed with the latest from the db after the obj.move() call. I'm not clear why calling save on a new Title instance results in an UPDATE call on its related page instance but it does:

    SELECT "cms_page"."id", "cms_page"."path", "cms_page"."depth", "cms_page"."numchild", "cms_page"."created_by", "cms_page"."changed_by", "cms_page"."parent_id", "cms_page"."creation_date", "cms_page"."changed_date", "cms_page"."publication_date", "cms_page"."publication_end_date", "cms_page"."in_navigation", "cms_page"."soft_root", "cms_page"."reverse_id", "cms_page"."navigation_extenders", "cms_page"."template", "cms_page"."site_id", "cms_page"."login_required", "cms_page"."limit_visibility_in_menu", "cms_page"."is_home", "cms_page"."application_urls", "cms_page"."application_namespace", "cms_page"."publisher_is_draft", "cms_page"."publisher_public_id", "cms_page"."languages", "cms_page"."revision_id", "cms_page"."xframe_options" FROM "cms_page" WHERE "cms_page"."id" = 9 LIMIT 21
    SELECT DISTINCT "menus_cachekey"."key" FROM "menus_cachekey" WHERE "menus_cachekey"."site" = 1
    DELETE FROM "menus_cachekey" WHERE "menus_cachekey"."site" = 1
    UPDATE "cms_page" SET "path" = '00010003', "depth" = 2, "numchild" = 0, "created_by" = 'demo', "changed_by" = 'demo', "parent_id" = 1, "creation_date" = '2015-02-05 01:58:31.501234+00:00', "changed_date" = '2015-02-05 02:05:24.305192+00:00', "publication_date" = NULL, "publication_end_date" = NULL, "in_navigation" = true, "soft_root" = false, "reverse_id" = NULL, "navigation_extenders" = NULL, "template" = 'INHERIT', "site_id" = 1, "login_required" = false, "limit_visibility_in_menu" = NULL, "is_home" = false, "application_urls" = NULL, "application_namespace" = NULL, "publisher_is_draft" = true, "publisher_public_id" = NULL, "languages" = 'en-us', "revision_id" = 0, "xframe_options" = 0 WHERE "cms_page"."id" = 9
    ERROR:  duplicate key value violates unique constraint "cms_page_path_5a9128a907fd31b5_uniq"
    DETAIL:  Key (path)=(00010003) already exists.
    STATEMENT:  UPDATE "cms_page" SET "path" = '00010003', "depth" = 2, "numchild" = 0, "created_by" = 'demo', "changed_by" = 'demo', "parent_id" = 1, "creation_date" = '2015-02-05 01:58:31.501234+00:00', "changed_date" = '2015-02-05 02:05:24.305192+00:00', "publication_date" = NULL, "publication_end_date" = NULL, "in_navigation" = true, "soft_root" = false, "reverse_id" = NULL, "navigation_extenders" = NULL, "template" = 'INHERIT', "site_id" = 1, "login_required" = false, "limit_visibility_in_menu" = NULL, "is_home" = false, "application_urls" = NULL, "application_namespace" = NULL, "publisher_is_draft" = true, "publisher_public_id" = NULL, "languages" = 'en-us', "revision_id" = 0, "xframe_options" = 0 WHERE "cms_page"."id" = 9

This reminds me of another issue I've come across https://github.com/divio/django-cms/issues/3731#issuecomment-68964872. This is starting to concern me that we can't trust any MP_Node  model instances and will have to constantly hit the db to make sure we have the latest path set by treebeard before doing anything else with the object.

**Comment by yakky** [comment]
@jsma please check the linked PR
