### ISSUE TITLE
After publishing a translated page the browser jumps back to the base language

### ISSUE THREAD

**Issue by ursulachristen** [divio/django-cms#3821]
The page should stay in the translated language to be able to check the changes made. Publishers are confused when not seeing their changes.

**Comment by yakky** [comment]
Which Django / django-cms version?
Would you provide steps to reproduce this?
Can't reproduce on standard setup

**Comment by ursulachristen** [comment]
We could fix the problem by including admin.site.urls into i18n_patterns in urls.py. 
You can close the ticket.

**Comment by yakky** [comment]
@evildmp I think we should document to include admin urls in i18n_patterns
While djangocms-installer already does so and I guess it's pretty standard practice, I think it may worth be more explicit

**Comment by yakky** [comment]
@ursulachristen thanks for reporting!

**Comment by evildmp** [comment]
Fixed
