### ISSUE TITLE
How to redefine the width of placeholder? 

### ISSUE THREAD

**Issue by lotaku** [divio/django-cms#3824]
I know the css limit the width of placeholder.
like this img:https://www.dropbox.com/s/95dev5dhe7nt9ct/small_placeholder.png?dl=0
but sometime it's width is too small.
How can i redefine the width of placeholder

Looking forward to your reply. Thanks.

**Comment by yakky** [comment]
you may force the width of a placeholder by using your own css by matching the placheholder DOM classes in structure mode (``cms_dragarea cms_dragarea-ID`` where ID is the placeholder numeric id)

**Comment by lotaku** [comment]
Thank you very much.
