### ISSUE TITLE
show_uncached_placeholder uses caching with CMS_PLACEHOLDER_CACHE=True

### ISSUE THREAD

**Issue by ojii** [divio/django-cms#3843]
Using ``show_uncached_placholder`` with ``CMS_PLACEHOLDER_CACHE`` set to ``True`` (which is the default!) causes the plugin rendering system to cache the placeholder nevertheless, which can trigger issues in ``restore_sekizai_context``.

Specifically what happens is the template tag hits:

* Attempts to render the placeholder at https://github.com/divio/django-cms/blob/3.0.9/cms/templatetags/cms_tags.py#L558
* Correctly bypasses caching in that function at https://github.com/divio/django-cms/blob/3.0.9/cms/templatetags/cms_tags.py#L580
* Enters actual rendering via ``render_placeholder`` at https://github.com/divio/django-cms/blob/3.0.9/cms/templatetags/cms_tags.py#L597
* The step above does not pass any information with regards to caching to ``render_placeholder``
* ``render_placeholder`` checks for ``CMS_PLACEHOLDER_CACHE`` at https://github.com/divio/django-cms/blob/3.0.9/cms/templatetags/cms_tags.py#L597
* Triggers ``restore_sekizai_context`` at https://github.com/divio/django-cms/blob/3.0.9/cms/plugin_rendering.py#L135
* Because only half of the pipeline is in "caching mode", ``restore_sekizai_context`` may trigger a ``TypeError: 'NoneType' object is unsubscriptable`` at https://github.com/divio/django-cms/blob/3.0.9/cms/utils/placeholder.py#L148

Example traceback:

```
Traceback (most recent call last):
  File "/path/to/env/lib/python2.6/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/path/to/env/lib/python2.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/path/to/env/lib/python2.6/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/path/to/env/lib/python2.6/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/path/to/env/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
  
  
  ... Repeated calls to render/_render removed
  
    return self.render_tag(context, **kwargs)
  File "/path/to/env/lib/python2.6/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/path/to/env/lib/python2.6/site-packages/cms/templatetags/cms_tags.py", line 619, in get_context
    return _show_placeholder_for_page(**self.get_kwargs(*args, **kwargs))
  File "/path/to/env/lib/python2.6/site-packages/cms/templatetags/cms_tags.py", line 597, in _show_placeholder_for_page
    content = render_placeholder(placeholder, context, placeholder_name)
  File "/path/to/env/lib/python2.6/site-packages/cms/plugin_rendering.py", line 135, in render_placeholder
    restore_sekizai_context(context, cached_value['sekizai'])
  File "/path/to/env/lib/python2.6/site-packages/cms/utils/placeholder.py", line 148, in restore_sekizai_context
    sekizai_namespace = sekizai_container[key]
TypeError: 'NoneType' object is unsubscriptable
```

**Comment by ojii** [comment]
While I only had a cursory look into this issue, it feels like passing a ``no_cache`` parameter to ``render_placeholder`` could solve this.

**Comment by yakky** [comment]
@ojii The revenge of the micro-features: #3768!

**Comment by mkoistinen** [comment]
Great job sleuthing, @ojii. Thanks for the patch, @yakky. It looks like your patch is based against 3.1.x. Does this need to be rebased to 3.0.x?

**Comment by yakky** [comment]
Technically speaking #3768 is a new feature, so I'd need to rework it as a patch (which means keeping 99% of the code and just removing the templatetag declaration)
I'd vote to merge it as is (but it requires docs, that I'll write shortly) given the negligible impact of the "feature" part, but I'm open to both solutions

**Comment by mkoistinen** [comment]
@ojii, do you have an opinion on @yakky's comment above?

**Comment by mkoistinen** [comment]
@yakky @ojii: What's the way forward on this guys?

**Comment by yakky** [comment]
To me we can just merge #3768

**Comment by ojii** [comment]
If I read #3768 correctly, it doesn't actually fix this issue. It adds the ability to fix this issue. So after 3768 this still needs to be tested and fixed

**Comment by yakky** [comment]
Sorry, writing on the go and cannot clarify myself: I meant "to me we can merge #3768 as is and then write the fix on top of it instead of extracting the code needed to fix this and not merge #3768"
Anyway, I have the fix for this on top of #3768 ready

**Comment by ojii** [comment]
Okay that sounds like a reasonable way to do it.

**Comment by yakky** [comment]
If we don't want to **add** things in 3.0.10 we can leave the new templatetag undocumented and document it in 3.1

**Comment by ojii** [comment]
can we really not have a clean patch for 3.0.10?

**Comment by yakky** [comment]
Yeah, sure.
We can just leave the templatetag out

**Comment by ojii** [comment]
I'd really appreciate that. Sorry for always being the annoying guy being pedantic about these things but I do believe they're important.

**Comment by yakky** [comment]
@ojii I tend to agree with you, but actually I consider the new templatetag a bug fix, as the current API is missing a piece

**Comment by mkoistinen** [comment]
So, can I merge #3862 and close this issue? Or do I need to do some cherry-picking or what?

**Comment by yakky** [comment]
#3682 does not fix this. I'd like to have a comment on the #3862 and the I'll push a different PR with the actual fix
I'd like a review on the API change separated from the fix for this.
