### ISSUE TITLE
Question: redirect_on_fallback = False doesn't work as expected

### ISSUE THREAD

**Issue by Moini** [divio/django-cms#3847]
Hi,
I'd like to know if this is a general bug, or a problem specific to our own site.

The django-cms documentation says:
> redirect_on_fallback

> Determines behaviour when the preferred language is not available. If True, will redirect to the URL of the same page in the fallback language. If False, the content will be displayed in the fallback language, but there will be no redirect.

If I set it to False, I get no redirect, as expected, but also, the non-translated, non-English page which is displayed does not have the contents from the English page, but is empty.

Is this a django-cms bug, or might this be due to some special settings we have? (v3.09)

Thank you!

**Comment by yakky** [comment]
Are the fallback languages setup correctly for the language?

**Comment by Moini** [comment]
All languages are set to fall back to English, following the documentation.

**Comment by yakky** [comment]
See ``language_fallback`` parameter in http://django-cms.readthedocs.org/en/support-3.0.x/reference/configuration.html

**Comment by Moini** [comment]
I copied from there ;)

**Comment by yakky** [comment]
Sorry, wrong link: http://django-cms.readthedocs.org/en/support-3.0.x/reference/configuration.html#cms-placeholder-conf language fallback must be enabled per-placeholder

**Comment by Moini** [comment]
Okay, thanks for the hint, I will try that! :D

**Comment by Moini** [comment]
Works - Thank you very much again :) You have made someone very happy today!
Maybe it would be worth to add a further "Make sure that..." to the part about CMS_LANGUAGES in the docs, so people searching for one thing cannot miss the other as I did?

**Comment by yakky** [comment]
Keep this opened to track your suggestion

**Comment by evildmp** [comment]
Looking at this right now. @Moini, can you just clarify for me precisely what confused you so I can address it? Ping me on IRC if you prefer.

**Comment by Moini** [comment]
evildmp, I wasn't confused - I just didn't know I had to change two settings - and it would have helped me if the part I found would have referenced the part I also needed.

So, if this part of the page: 
http://django-cms.readthedocs.org/en/support-3.0.x/reference/configuration.html#cms-languages 
would have had a link to this one 
http://django-cms.readthedocs.org/en/support-3.0.x/reference/configuration.html#cms-placeholder-conf (and possibly the other way around, too), 

stating the fact that there are two independent settings for fallback languages, one for CMS generally, and a separate one for the placeholders - I had some really empty pages before I knew that ;)

**Comment by Moini** [comment]
Thank you!

**Comment by evildmp** [comment]
Fixed!
