### ISSUE TITLE
Make language_fallback enabled by default

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#3849]
I think we can set to enabled by default in ``CMS_PLACEHOLDER_CONF`` as the master behavior is controlled in ``CMS_LANGUAGES`` (see http://django-cms.readthedocs.org/en/support-3.0.x/reference/configuration.html#cms-placeholder-conf)

**Comment by yakky** [comment]
@evildmp @mkoistinen @ojii opinions?

**Comment by yakky** [comment]
Linked to #3847
If we want to keep this as is, make it clearer in the `CMS_LANGUAGES` documentation (http://django-cms.readthedocs.org/en/support-3.0.x/reference/configuration.html#fallbacks) that it needs a per-placeholder setting to work

**Comment by carderm** [comment]
I think this is decision was made in error. There is no configuration available in CMS_LANGUAGES that can enable/disable a placeholder language fallback default.
The options in CMS_LANGUAGES for 'fallbacks' is a list of languages for *pages* to use if there is no translation.
 This is perfectly valid, ONLY for pages - e.g. if there is no french page, provide an english page.
This does NOT equate to placeholders within each page...
e.g. if there is no french placeholder, use an english one?! 
"French Title"
"Random English Placeholder only in English?"
"More French placeholders"
This does not make sense...!

I suggest - either reversing this commit and/or adding a new setting to CMS_LANGUAGES such as:
'placeholder_language_fallback': True/False, to be used as the default value in the change above.

Cheers!
