### ISSUE TITLE
Reverse for 'sites_site_changelist' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

### ISSUE THREAD

**Issue by carina21** [divio/django-cms#3851]
I have following Bug:
NoReverseMatch at /de/

Reverse for 'sites_site_changelist' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

Request Method: 	GET
Request URL: 	http://iv.x-t.at/de/
Django Version: 	1.7.4
Exception Type: 	NoReverseMatch
Exception Value: 	

Reverse for 'sites_site_changelist' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

Exception Location: 	/opt/usr/virtualenv/iv/lib/python2.7/site-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 468
Python Executable: 	/usr/bin/python
Python Version: 	2.7.6

The reverse "sites_site_changelist" is enabled in cms/cms_toolbar.py

**Comment by mkoistinen** [comment]
@carina21, in all of the evidence you've provided above, this appears to be either an issue with your own code or an issue with Django itself. I see nothing that suggests this is a django CMS issue. If you feel differently, please provide some evidence suggesting that django CMS is involved, and open a new issue.

**Comment by slmjy** [comment]
This happend to me also, so I'll leave it here. you don't have `django.contrib.sites.admin` added to your admin site. either use `admin.autodiscover()` ,or import it in your `admin.py`
