### ISSUE TITLE
Application testing problems with CMS_PERMISSIONS

### ISSUE THREAD

**Issue by donce** [divio/django-cms#3863]
The problem is with current_user (from cms.utils.permissions), which is set in CurrentUserMiddleware.process_request. During application testing, it may cause problems.

Imagine test run scenario:
* First testcase creates user, logins with it, does some testing and logouts - this sets current_user to a new user but never clears it out - logout sets current_user to the same user, because request.user is still the same user.
* Second testcase creates user, which in turn triggers cms.signals.permissions.post_save_user to add created_by=get_current_user() on user. At this moment, get_current_user() is the same user from the first test case, because it wasn't cleared. This causes integration error, because this user is not in database anymore - it was automatically removed after finishing testcase.

Of course it's possible to add set_current_user(None) to test tearDown (as cms tests does), but I don't think that we have to make people rewrite tests just for using CMS_PERMISSIONS.
Also, I think testing with CMS_PERMISSIONS = False is also not an option, since I'd like to test my application as close as possible to my production.

**Comment by yakky** [comment]
Have you tried ``UserLoginContext``: https://github.com/divio/django-cms/blob/develop/cms/test_utils/util/context_managers.py#L81?

**Comment by donce** [comment]
@yakky - as far as I can see, it doesn't clear current_user on exit - it just calls self.testcase.client.logout(), which is what I use in my tests as well. This logout method just sets current_user to the same user which was logged in, because set_current_user is called on process_request - and request.user is still there.
After calling this function, imagine creating user model in script without making any requests (but in a different test case) - this might cause database Integration Error.

**Comment by donce** [comment]
I think it's worth adding user_logged_out signal handler, which in turn calls set_current_user(None) - what do you think? If the problem is not clear at all, I could try making a test case for the scenario described above :)

**Comment by yakky** [comment]
@donce if you use SimpleTestCase data are discarded after each test function, it shouldn't result in any permanent data to be saved

**Comment by donce** [comment]
Testcases don't discard thread data - https://github.com/divio/django-cms/blob/develop/cms/utils/permissions.py#L23 , this is kept between different test functions.

**Comment by czpython** [comment]
I've opened a public discussion on the developer's list in order to come up with a solution that addresses the underlying problem (using current thread to store user).

https://groups.google.com/forum/#!topic/django-cms-developers/T9OtsDl8qcQ

**Comment by czpython** [comment]
Closing in favor of https://github.com/divio/django-cms/issues/5411.
