### ISSUE TITLE
Templatetag: "render_model_add" should allow you to wrap any arbitrary content

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#3873]
Currently, {% render_model_add %} is sorta limited to presenting an icon, which, to be fair you can replace and re-position with CSS. I think it would be tremendously more useful if it could be used to wrap any arbitrary content. This would provide the developer a lot more options in creating frontend interfaces that are more in-keeping with the style and format of the site they are building.

**Comment by yakky** [comment]
Fixed by #3875
