### ISSUE TITLE
 Templatetag "render_model_add" requires a model instance 

### ISSUE THREAD

**Issue by helderco** [divio/django-cms#3874]
Allow to use ``render_model_add`` by passing a class as argument instead of  an instance

**Comment by mkoistinen** [comment]
I would like to see this too!

@yakky, did I hear you mention the other day that you're working on this?

**Comment by yakky** [comment]
@mkoistinen right: during the weekend I'll post a PR and will take care of this

**Comment by yakky** [comment]
@mkoistinen @helderco the linked PR should tackle the issue.
Setting ``instance.pk = 0`` looks a little hackish, but it's ok since the instance it's never really touched

**Comment by yakky** [comment]
@helderco does #3888 fixes the issue for you?

**Comment by helderco** [comment]
Hey @yakky thanks!

It fixes my original idea, but this issue is actually about something else. It's about having the form pre-populated with some values by instantiating an object with those values and using it in `render_model_add`.

**Comment by yakky** [comment]
@helderco sorry, I read the original text and missed the update.
Postponing this after 3.1, then

**Comment by helderco** [comment]
@yakky, I thought no one would want to refactor to use the class name because you can simply create a new empty object in the view, that's why I updated this issue to mean a different situation.

Since you've done it, I want to re-edit this issue to be what it was and create a new one with what this has now, but I don't have my original description.

Have you got some sort of a notification when the issue was created?

**Comment by yakky** [comment]
@helderco ok, I'll edit the description  with the oriiginal idea

**Comment by yakky** [comment]
@helderco actually it makes sense to leave this as is as a proposed enhancement, and just let the PR fix the original idea

**Comment by helderco** [comment]
Hmm... I just created a new issue. What do you want to do? Remove the one I just created or restore this one?

**Comment by yakky** [comment]
@helderco race condition! :D no worries, I'll restore this to its original content and will close with the above PR

**Comment by mkoistinen** [comment]
Can't we apply this to 3.0.x? I mean, this is how it was supposed to work anyway.

**Comment by yakky** [comment]
Fixed in #3899
