### ISSUE TITLE
set_language_changer not documented

### ISSUE THREAD

**Issue by ychouinard** [divio/django-cms#3877]
I noticed that set_language_changer is no longer in the documentation. We are still using it in most of our projects and the doc from older version still applies (http://docs.django-cms.org/en/2.3.3/advanced/i18n.html#language-chooser).

Is there something that replaced it or is it just missing from the doc?

**Comment by mkoistinen** [comment]
@yakky I see this issue is closed, but there's a reference to what appears to be a completely unrelated PR. Am I missing something?

**Comment by yakky** [comment]
Yep, sorry: the linked PR is totally unrelated, I just wrote the wrong ID there. Fixed in the PR, but still wrong link here.

**Comment by mkoistinen** [comment]
Anyway, the current docs DOES have this documented here: https://django-cms.readthedocs.org/en/support-3.0.x/reference/templatetags.html#language-chooser

So, I'm closing this Issue.
