### ISSUE TITLE
Placeholder "Empty all" remove plugins in all the languages

### ISSUE THREAD

**Issue by pevar** [divio/django-cms#3880]
The "Empty all" functionality in the "Draft | Structure" view, removes the plugins from the placeholder for all the localized versions of the page, while the "Delete Confirm Panel" message is only listing the plugins for the page in the current languages.

In depth:
Here https://github.com/divio/django-cms/blob/master/cms/admin/placeholderadmin.py#L542 you collect the plugins for the "Delete Confirm Panel", filtering by language.

Here https://github.com/divio/django-cms/blob/master/cms/admin/placeholderadmin.py#L553 you call the placeholder.clear() method without the language information.

Very dangerous for multi-languages sites, loosing a lot of contents without realizing it.

**Comment by yakky** [comment]
Fixed in #3881
