### ISSUE TITLE
Usage of deprecated mimetype parameter crashes Django 1.7+ (again)

### ISSUE THREAD

**Issue by timgraham** [divio/django-cms#3885]
The fix for #3722 was incomplete. On the `support/3.0.x` branch, `mimetype` should be `content_type` for Django 1.5+. On `develop` where we don't need support for Django 1.4/1.5, we don't need conditional logic at all. The `SettingsAdmin.session_store()` method still only uses `mimetype`.
```
cms/admin/settingsadmin.py:            return HttpResponse(json.dumps(""), mimetype="application/json")
cms/admin/settingsadmin.py:        return HttpResponse(json.dumps(request.session.get('cms_settings', '')), mimetype="application/json")
```

**Comment by yakky** [comment]
Fixed in #3887
