### ISSUE TITLE
Document redirection API

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#3889]
Redirection after editing object in the frontend requires action by the developer.
Currently documentation is kind of scattered around, and we need to fix this by providing a clear an unified documentation on how to properly implement this.

Key topics:
* implement ``toolbar.watch_models`` attribute to declare supported models
* implement ``object.get_public_url()``, ``object.get_draft_url()`` to take the publishing state into account
* implement ``request.toolbar.set_object()`` to properly set the current object on the toolbar
* implement the detail view such as the object can always be accessed by staff users when the toolbar is active even if the object is not published (according to the application-specific semantic of *published objects*)
* keep the unpublished objects out of the listviews when in edit mode

**Comment by evildmp** [comment]
Does this now have the documentation it requires? There's such a tangled web of issues and patches here that it's hard to see.

**Comment by yakky** [comment]
Current implementation (still to be merged) is https://github.com/divio/django-cms/pull/3894/files#diff-c47ae0bcfc004b5520e9654aa182096eR11

**Comment by yakky** [comment]
Fixed in #3894
