### ISSUE TITLE
Unclear/wrong breadcrumbs

### ISSUE THREAD

**Issue by pawelmarkowski** [divio/django-cms#3902]
You have 4 sites in cascaded structure
page A
+page B
++page C
+++page D

link at page D looks like example.com/a/b/c/d/
breadcrumbs a >> b >> c >> d
you do not want to show pages C and D in menu but all pages are published.

Links still looks like in an example example.com/a/b/c/d/
but breadcrumbs are wrong (do not show a structure)
breadcrumbs a >> b >> d if you are on a page d
and breadcrumbs a >> b >> c if you are on a page c

In my opinion it should be full breadcrumbs path generated by published sites.

**Comment by mkoistinen** [comment]
That indeed sounds like a bug, thanks for reporting it, @pawelmarkowski.

**Comment by pawelmarkowski** [comment]
@mkoistinen if it is feature then - why are we showing home in breadcrumbs (if it is not visible in menu)

**Comment by mkoistinen** [comment]
@pawelmarkowski I tend to agree with you, but, I don't know if there are any use-cases for breadcrumbs I hadn't considered, which is why I am soliciting community input here.

**Comment by yakky** [comment]
Currently "in menu" it's used for both menu and breadcrumbs.
I agree that situation might worth an improvement and further work

**Comment by mkoistinen** [comment]
@pawelmarkowski I went to solve this issue, then found that it had already been solved!

https://github.com/divio/django-cms/blob/develop/menus/templatetags/menu_tags.py#L265

show_breadcrumbs takes 3 optional parameters: start_level, template and only_visible

Set the last one to False, and you should be ok =)

This is getting converted into a documentation issue as I notice that the reference section in the docs is notably missing information about the menus template tags.

**Comment by pawelmarkowski** [comment]
@mkoistinen  thanks ... 

summarize: 
show_breadcrumbs takes 3 optional parameters: start_level, template and only_visible (and "show only visible" was solution of my problem. It works perfect ... waiting for docs update, ticket closed)
example:
{% show_breadcrumb 0 'menu/breadcrumb.html' False %}
