### ISSUE TITLE
Doc error about 

### ISSUE THREAD

**Issue by jedie** [divio/django-cms#3905]
The current doc page: http://django-cms.readthedocs.org/en/3.0.10/reference/plugins.html#change-form-template contains **admin/cms/page/plugin_change_form.html**

See also: https://github.com/divio/django-cms/search?utf8=%E2%9C%93&q=plugin_change_form.html

But this template seems to be renamed to: **admin/cms/plugin/change_form.html** isn't it?

**Comment by yakky** [comment]
@jedie not : https://github.com/divio/django-cms/blob/develop/cms/templates/admin/cms/page/plugin/change_form.html / https://github.com/divio/django-cms/blob/support/3.0.x/cms/templates/admin/cms/page/plugin/change_form.html

**Comment by mkoistinen** [comment]
Closing.
