### ISSUE TITLE
page_attribute does not return its content safe

### ISSUE THREAD

**Issue by Hinnack** [divio/django-cms#3906]
{% page_attribute "page_title" %} returns its content not safe. So I can not use HTML in it like adding an icon <i class="fa fa-search"></i>

this does not work, too:
{% page_attribute "page_title" as title %}{{ title|safe }}

**Comment by yakky** [comment]
Attributes handled by ``page_attribute`` are meant to be plain text-only, I don't think we shoul mark them as safe.

**Comment by Hinnack** [comment]
any other way to get menu items with icons then?

**Comment by yakky** [comment]
Use page/title extensions (http://django-cms.readthedocs.org/en/support-3.0.x/how_to/extending_page_title.html) which allows you to add any kind of attributes to page and titles and retrieve them in the templates by following the relation
