### ISSUE TITLE
Korean and Chinese can not be added to the title page

### ISSUE THREAD

**Issue by Josephpaik** [divio/django-cms#3913]
As if I put some Korean letters in title. the "slug" field does not react properly.
I can't make Korean title page. even if I have added 'kr' language support when create djangocms project.

I guess that urlify.js(django\contrib\admin\static\admin\js\urlify.js) in front page and slugify( django.template.defaultfilters) for the slug field do not support 2 byte characters

I know that the uuslug's slugify can convert "한글 title" as "hangel-title". It's awesome !
If you can change the default slugify to slugify of uuslug seems really nice.

Thanks,

**Comment by yakky** [comment]
Please have a look at http://django-cms.readthedocs.org/en/support-3.0.x/reference/configuration.html#unicode-support-for-automated-slugs

**Comment by Josephpaik** [comment]
I got it. and solved my problem.
Thank you very much, yakky!
