### ISSUE TITLE
3.0.11 Breaks cms.changelist.js 

### ISSUE THREAD

**Issue by corbinfanning** [divio/django-cms#3924]
There is a typo in cms.changelist.js that prevents Page ordering in the admin from working. 
https://github.com/divio/django-cms/blob/release/3.0.11/cms/static/cms/js/modules/cms.changelist.js#L17

![screen shot 2015-03-04 at 4 13 59 pm](https://cloud.githubusercontent.com/assets/1168680/6494719/82ab52a2-c289-11e4-8a1a-d4e6f6565fdc.png)

**Comment by yakky** [comment]
Fixed in #3925
