### ISSUE TITLE
Documentation is rather confusing when it comes to installation

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#3931]
The documentation structure has a menu-item: Tutorials, which has a sub item: "Installing django CMS from scratch". However, this tutorial then goes on to instruct someone to use the django-CMS installer to install. I don't think many of us would consider this "from scratch" anymore than making a cake from a box-mix, rather than from raw ingredients.

Also, I don't think many people would consider installation instructions to be a "Tutorial" so much, as rather "Installation instructions". I realise this may be mincing words a bit, but I think a tutorial here would be more like "how to make a plugin", or other things once you have installed the product.

Finally, in a complete different section of the menu, is another menu: "How-to Guides", which includes the item: "Integrate django CMS into an existing project", which is another set of installation instructions (more akin to installing "from scratch", really).

This is confusing (we see comments on this in IRC, G+ on this regularly).

I would like to propose that installation be separate from "Tutorials" and "How-To Guides". A sub-menu could then provide different installation paths including:

1. djangocms-installer;
2. manual installation;
3. integration with existing Django projects.

**Comment by evildmp** [comment]
Pull request https://github.com/divio/django-cms/pull/3947

**Comment by evildmp** [comment]
Thanks @mkoistinen for identifying the issue.

**Comment by mkoistinen** [comment]
Closed by #3947
