### ISSUE TITLE
Pages tree menu not building correctly

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#3940]
The project I'm working on overwrites several django and CMS templates because we're serving static files through an extra app from S3 so certain things are loaded differently.

Running Django 1.6.5, Django CMS 3.0.12

These static files haven't been maintained for many of the recent CMS releases so I've updated them whilst trying to maintain our workarounds/fixes.

Trouble is I've just found the main Pages tree view isn't rendering. With an unfiltered tree, I can see the top level pages and select them, but not the corresponding content on the right of the table, or their child pages. If I filter the list it renders correctly.

I'm seeing no console errors so don't really know where to look for the cause of this, I know it might be a nightmare debugging scenario, but if anyone could help out I'd really appreciate it!

I thought this might be caused by changes to `tree/base.html`, but reverting that file back also encounters this issue, so it must be javascript based, right?

![screen shot 2015-03-12 at 14 26 32](https://cloud.githubusercontent.com/assets/1461191/6619748/3cf672e6-c8c4-11e4-931d-1c4a921add3e.png)

**Comment by yakky** [comment]
I guess it's a rather hairy issue: having customised styles / templates / js makes very hard to understand what's going on
My best bet is something in the css, but it's a shot in the dark

**Comment by marksweb** [comment]
Right well that gives me something to look at. For all templates I updated I was happy I'd covered our previous fixes, but not knowing enough about how the page renders makes it tough to debug when there's no errors. 

I'm not sure if there's also some new content that I need to copy to our repo to override the static method to our pipeline app. Or if I can ditch that all together & rely on adminstatic. 

As I say, when you're looking at a filtered view there's no issue, so at least I can run through some breakpoints in the unfiltered JS methods.

**Comment by marksweb** [comment]
@yakky I've just noticed as well that I get a Mixed content error/warning because we're running over HTTPS but when saving page settings it seems the request from CMS is then only HTTP.

Is there a setting to move all CMS requests to HTTPS?

This was the message when trying to save page permissions;
> Mixed Content: The page at 'https://www.mydomain.com/en-gb/test-results/?edit&language=en-gb' was loaded over HTTPS, but requested an insecure form action 'http://www.mydomain.com/en-gb/admin/cms/page/'. This request has been blocked; the content must be served over HTTPS.

**Comment by yakky** [comment]
https works by default if the admin / toolbar is accessed via https
I tested major actions (opening a standard settings form both as modal and in the sideframe), arranging pages in the sideframe on an https website and everything worked as expected

**Comment by marksweb** [comment]
Just looking through the javascript when the page tree is drawn I'm seeing this error for each column by the looks of it;

```
"Error: Failed to execute 'webkitMatchesSelector' on 'Element': ':visible' is not a valid selector.
    at Error (native)
    at Function.db.matchesSelector (http://localhost:8009/static/cms/js/libs/jquery.min.js:2:12238)
    at Function.n.filter (http://localhost:8009/static/cms/js/libs/jquery.min.js:2:23198)
    at x (http://localhost:8009/static/cms/js/libs/jquery.min.js:2:23009)
    at n.fn.extend.is (http://localhost:8009/static/cms/js/libs/jquery.min.js:2:23735)
    at HTMLDivElement.<anonymous> (http://localhost:8009/static/cms/js/modules/cms.changelist.js:55:17)
    at Function.n.extend.each (http://localhost:8009/static/cms/js/libs/jquery.min.js:2:2969)
    at n.fn.n.each (http://localhost:8009/static/cms/js/libs/jquery.min.js:2:845)
    at $.ready.CMS.TreeManager.CMS.Class.setupFunctions.$.fn.syncWidth (http://localhost:8009/static/cms/js/modules/cms.changelist.js:54:13)
    at Function.$.ready.CMS.TreeManager.CMS.Class.setupFunctions.$.syncCols (http://localhost:8009/static/cms/js/modules/cms.changelist.js:44:32)"
```

I'm not entirely sure what I should be looking for still, but does anyone have any ideas?

**Comment by yakky** [comment]
@FinalAngel @astagi any hint?

**Comment by FinalAngel** [comment]
@yakky I'm not aware of any issues there

**Comment by marksweb** [comment]
@yakky @FinalAngel 

Just been stepping through the code chaps & we've isolated where the column(s) get hidden.
https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.changelist.js#L757

We've got the following variables on the first loop through;
```
this = div.col-softroot
w = 29
min_width = 0
offset = 50
```
So that equates to ```29 > -50``` which will always result in ```max_reached = True``` and this is when we're looking at any sized screen for the page tree, full screen through the admin or from the front end in a sidebar.

Are these values what you'd expect or should this be functioning differently?

**Comment by marksweb** [comment]
I'm going to close this. I believe the jtree style sheet wasn't being added on the unfiltered tree for some reason, so in the base template I simple removed the `{% if cl.is_filtered %}` block to ensure the stylesheet is always included from the template, so the JS doesn't have to add it stylesheet.

**Comment by miraculixx** [comment]
@marksweb @FinalAngel I'm getting the very same error message, except I don't have any customizations whatsoever:

```
Mixed Content: The page at 'https://cpdev.dockrzone.com/admin/cms/page/?page_id=1&language=en' was loaded over HTTPS, but requested an insecure stylesheet 'http://cpdev.dockrzone.com/admin/cms/page/cms/css/cms.toolbar.sideframe.css/'. This request has been blocked; the content must be served over HTTPS
```

This is django-cms==3.0.5

**Comment by yakky** [comment]
@miraculixx I suggest an upgrade to 3.0.13: a lot of fixes have been merged
From the error apparently the css is not available in the statics, anyway

**Comment by miraculixx** [comment]
@yakky thanks. I upgraded to 3.0.13 -- the problem persists, I still get a mixed content error as above. It all works with HTTP, but not with HTTPS. This has all sorts of bad consequences -- whenever the browser detects an ajax request to http, it basically breaks the usual JS flow. E.g. on /admin/page/, but also on pop ups, ike page settings, adding  plugin etc.

Any ideas what I could investigate next?

**Comment by yakky** [comment]
Given that the error regards ``http://www.mydomain.com/admin/cms/page/cms/css/cms.toolbar.sideframe.css/`` (notes the ``/`` at the end) apparently **https://www.mydomain.com/admin/cms/page/cms/css/cms.toolbar.sideframe.css** (note that no ``//`` is present at the end) is not available and django redirect to non-https version appending the ``/`` (due to the related Django setting)

**Comment by miraculixx** [comment]
well it is obviously not available at `http://www.mydomain.com/admin/cms/page/cms/css/cms.toolbar.sideframe.css/` (with or without trailing /), because that path is _entirely wrong_.  It should be `http://www.mydomain.com/static/css/cms.toolbar.sideframe.css/`. 

That's the source of the problem -- for some reason, the client side cms script generate the wrong URL, I just can't figure out why. The STATIC_URL is set correctly to `/static`.

**Comment by yakky** [comment]
@miraculixx could you paste the ``CMS.config = {..}`` which is added at the bottom of the page ?

**Comment by miraculixx** [comment]
```
	CMS.config = {
		'mode': 'draft',
		'auth': true,
		'debug': false,
		'csrf': 'W3lXjXX8qrDpzn7Vu1h6sp7ei13FBEfw',
		'request': {
			'language': '',
			'model': 'cms.page',
			'page_id': '17',
			'pk': '17',
			'url': '/en/admin/cms/page/resolve/',
			'tree': '/en/admin/cms/page/'
		},
		'lang': {
			'debug': 'Development version using django CMS 3.0.13',
			'cancel': 'Cancel',
			'error': '<strong>The following error occured:</strong> ',
			'success': 'Action successfull... reloading.',
			'confirm': 'Are you sure you want to delete this plugin?',
			'publish': 'Are you sure you want to publish this page?'
		},
		'urls': {
			'settings': '/en/admin/cms/usersettings/session_store/', // url to save settings
			'static': ''
		},
		'settings': {
			'version': '3.0.13',
			'toolbar': 'expanded',
			'mode': 'edit',
			'sideframe': { 'url': '' },
			'states': []
		},
		'clipboard': {
			'id': '1',
			'url': '/en/admin/cms/page/clear-placeholder/1/'
		},
		'messages': '',
		'error': '',
		'publisher': ''
	};
``` 

For what it's worth, here's the settings.py. That's taken from the same live session as the config above:

```
STATIC_URL=/static/
```

**Comment by yakky** [comment]
That empty ``'urls': { ... 'static': '' },`` is  the culprit
Any custom template processor?

**Comment by miraculixx** [comment]
Well, depends on what you call _custom_ ;-)

```
TEMPLATE_CONTEXT_PROCESSORS=(
'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages', 
'django.core.context_processors.i18n', 
'django.core.context_processors.request', 
'allauth.account.context_processors.account', 'allauth.socialaccount.context_processors.socialaccount', 
'sekizai.context_processors.sekizai', 
'cms.context_processors.cms_settings')
```

**Comment by Moini** [comment]
We've got a similar problem at times - not sure if it is the same: 
the pages overview page looks like the screenshot above, but resizing (always) or reloading (sometimes) the page helps, so it seems more of a displaying problem, with old Django 1.6, and django-cms 3.0.6 - could anyone tell me if this is a known problem? 

I have difficulties searching for this - 'page, pages, not loaded, not displayed' are too unspecific search terms to find something for django-cms... :(

**Comment by yakky** [comment]
@Moini what about 3.0.13?

**Comment by Moini** [comment]
I have only ever encountered the problem on our real website, never on my local dev server. 
And even on the real website, it doesn't happen consistently. 
Martin Owens suspected it might be a race condition kind of thing, with some part not being loaded fully before some script tries to work with it (probably something that is called again, when the window is being resized).
I'm not sure that local testing with a different version will help :-(
