### ISSUE TITLE
Placeholder's Empty all not intuitive

### ISSUE THREAD

**Issue by darbula** [divio/django-cms#3944]
Placeholders Empty all command seems not intuitive since it empties content for all languages. 

Common usecase is:

* when placeholder content is significantly modified in language A, then
    * delete all plugins for  language B and
    * copy plugins from language A and translate.

To do this users tend to click on Empty all on placeholder for language B to find that they cannot copy plugins form language A since they have been deleted.

**Comment by yakky** [comment]
This has been fixed in #3881
Which version of django CMS are you using?

**Comment by yakky** [comment]
Ops, sorry: this has been fixed in develop, this fix will be in 3.1

**Comment by darbula** [comment]
Great, thank you.

**Comment by yakky** [comment]
Fixed in #3381
