### ISSUE TITLE
conflict between frontend editing modal and bootstrap slider

### ISSUE THREAD

**Issue by avoine** [divio/django-cms#3946]
with:
Django-cms-3.0.12
Bootstrap v3.3.2
JQuery 1.11.2

I've run into a bug where the frontend editing modal was constently rerendering (flashing white every 5 sec) and I found out that it was rendering every time bootstrap3's slider was sliding to a new image.
Not really sure can/should fix this but I'm putting it here in case someone else experience it.

**Comment by yakky** [comment]
Thanks for reporting
We do our best to avoid conflicts with existing JS / CSS, but the very nature of the DOM makes quite hard to completely avoid this issue in any circumstance.

**Comment by FinalAngel** [comment]
@avoine do you still have this issue with the latest 3.2.0 (develop) ?

**Comment by avoine** [comment]
@FinalAngel indeed it's fixed, I'll close this issue. Thanks!
