### ISSUE TITLE
Incorrect admin URL can cause a Python error

### ISSUE THREAD

**Issue by evildmp** [divio/django-cms#3952]
Try to reach a non-existent admin page, say http://localhost:8000/en/admin/cms/page/23/edit-plugin/408/ - you'll get a 404, as expected.

Try (say) http://localhost:8000/en/admin/cms/page/23/edit-plugin/408/edit-plugin/407/, and you'll get:

```
ValueError at /en/admin/cms/page/23/edit-plugin/408/edit-plugin/407/
invalid literal for int() with base 10: '408/edit-plugin/407'
```

I think that this should also return a 404.

**Comment by yakky** [comment]
@evildmp please check
