### ISSUE TITLE
New database install on Dj 1.7 with 3.0.12 - Cannot resolve bases

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#3956]
I've never come across the error before but I gather it's related to model dependency.

I'm setting up a brand new project and on the initial migration with all the CMS plugins, e.g. `djangocms_text_ckeditor`, in my `INSTALLED_APPS` I'm getting an error from them all;

```bash
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'djangocms_text_ckeditor.Text'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more
```

Which is coming from the initial `contenttypes` migration.

Is there a work around for this? At the moment, if an app causes this, I have to comment out the offending apps, run migrations, then add them in again.

**Comment by yakky** [comment]
What's the order in the apps in installed apps?

**Comment by marksweb** [comment]
They're in after CMS, which is what I've always had in my 1.6 projects;

```python
INSTALLED_APPS = (
    # Must be placed before admin to allow admin styling and utils
    'administration',

    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',

    # RB/Third party priority apps
    'djangocms_admin_style',
    'django_extensions',
    'django_mobile',
    'djcelery',

    'memcache_status',

    'axes',
    'passwords',
    'cms',
    'mptt',
    'menus',
    'sekizai',
    'reversion',
    'import_export',

    'djangocms_text_ckeditor',
    'djangocms_style',
    'djangocms_column',
    'djangocms_file',
    'djangocms_link',
    'djangocms_teaser',
    'djangocms_video',
)
```

**Comment by yakky** [comment]
What's MIGRATION_MODULES? Which djangocms_text_ckeditor version?

**Comment by marksweb** [comment]
This is taken from my requirements file but I believe that's taken from a pip freeze so should be reliable;

djangocms-column==1.3
djangocms-file==0.0.1
djangocms-flash==0.0.2
djangocms-googlemap==0.0.5
djangocms-inherit==0.0.1
djangocms-installer==0.5.2
djangocms-link==1.3.4
djangocms-picture==0.0.2
djangocms-style==1.3
djangocms-teaser==0.0.1
djangocms-text-ckeditor==2.1.6
djangocms-video==0.0.1

And I think this is just taken from the 1.7 page in the docs, but I did notice some of the apps don't have django migrations but didn't get any time on this project today;

```python
MIGRATION_MODULES = {
    'cms': 'cms.migrations_django',
    'menus': 'menus.migrations_django',
}
```

I bet I'm running old versions of all the apps aren't I...

**Comment by yakky** [comment]
Update djangocms_text_ckeditor (and any other django cms plugin) to Django 1.7 compatible version and follow the instruction in the readme of each plugij

**Comment by marksweb** [comment]
I'll run through that process in the morning. I should of thought of that already! Thanks again @yakky!

**Comment by marksweb** [comment]
Just to finalise this, the original issue was fixed by upgrading the apps, but that uncovered this issue reported on djangocms_link with creating a new database resulting in a `no such table: cms_page`;
https://github.com/divio/djangocms-link/issues/34
