### ISSUE TITLE
Cache and documentation

### ISSUE THREAD

**Issue by darbula** [divio/django-cms#3961]
`CMS_CACHE_DURATIONS` dictionary does not change [cms cache durations](https://github.com/divio/django-cms/blob/develop/cms/utils/conf.py#L67), instead old `MENU_CACHE_DURATION` and `CMS_CONTENT_CACHE_DURATION` are still used.

Also, documentation is lacking info on logic behind caching Page, Placeholder and Plugins i.e if `CMS_PAGE_CACHE = True` does it mean that plugins Placeholders are cached regardless of `CMS_PLACEHOLDER_CACHE` value, the same goes for relation between Placeholder and Plugin cache.

In the Cache Setup documentation it is noted that `FetchFromCacheMiddleware` and `UpdateCacheMiddleware` should be added to `MIDDLEWARE_CLASSES` but these middlewares cache on the request-response level not on page-placeholder-plugin level, so are they mandatory?

**Comment by Chronial** [comment]
:+1: I was very confused by the text of the documentation. It implies that I need the caching middleware for _any_ kind of caching to happen.

**Comment by Chronial** [comment]
Note that this is not just a documentation issue. At the moment, only the old setting names work. The setting variables described in the documentation have no effect: https://github.com/divio/django-cms/blob/0986c6a783535ec8a15c9b6ac2f807a663b064a3/cms/utils/conf.py#L73

So to change the content cache duration, I need to set `CMS_CONTENT_CACHE_DURATION`. `CMS_CACHE_DURATIONS` has no effect. Tested against 3.2.0.

**Comment by FinalAngel** [comment]
@evildmp would you be able to check this?

**Comment by czpython** [comment]
Closing as bug is fixed.
Opened new ticket for doc changes https://github.com/divio/django-cms/issues/5307
