### ISSUE TITLE
Menu shows random entries from past

### ISSUE THREAD

**Issue by bastiW** [divio/django-cms#3965]
When I'm logged in. The menu (menu.html) shows totally random entries after each refresh of the page. . The entries which are shown were deleted or renamed before. 
This issue doesn't occur when I'm NOT logged in. 

There seems to be this issue in the past: https://groups.google.com/forum/#!topic/django-cms/_9KPqybmgWg

This happens within my production env. With the following setting: 

```
dj-database-url==0.3.0
Django==1.7.7
django-classy-tags==0.6.1
django-cms==3.0.12
django-mptt==0.6.1
django-reversion==1.8.5
django-sekizai==0.8.1
djangocms-admin-style==0.2.5
djangocms-column==1.5
djangocms-file==0.1
djangocms-flash==0.1
djangocms-googlemap==0.2
djangocms-inherit==0.1
djangocms-installer==0.7.2
djangocms-link==1.5
djangocms-picture==0.1
djangocms-style==1.5
djangocms-teaser==0.1
djangocms-text-ckeditor==2.4.3
djangocms-video==0.1
gunicorn==19.3.0
html5lib==0.999
Pillow==2.7.0
psycopg2==2.6
pytz==2014.10
requests==2.6.0
six==1.9.0
South==1.0.2

```

Python = 3.4.0

**Comment by yakky** [comment]
Any cache enabled / which backend?

**Comment by mkoistinen** [comment]
I've seen this before, but it was because I had two or more sites using the same cache-backend and I hadn't change the value of `CMS_CACHE_PREFIX` to something unique for each site. Could this be the case here?

**Comment by czpython** [comment]
Closing due to lack of info.
Please create a new ticket if this issue is still present on latest django CMS (3.4)
