### ISSUE TITLE
picture size

### ISSUE THREAD

**Issue by kkx** [divio/django-cms#3967]
Hi everybody,
when i added yesterday a picture plugin to a page(following the cms-installer instructions), i realized there is not any configs of the size of the added picture to be set. if the pic is bigger than the width of the page, it will surpass it and the result page looks ugly.
What i did to solve this problem is to rewrite "picture.html" in the cms/plugins and added width="100%" in the "img" tag, this makes it to respect its parent element's layout by default.
There is anyway to make it simple, or some elegant solution to control a rendered image size instead of put some global css in somewhere?

**Comment by jrief** [comment]
If you use Bootstrap-3.x.x as your CSS grid system, have a look at djangocms-cascade. This handles the image and picture sizes according to the current column width.
Disclaimer: I am the author of that library, hence biased.

**Comment by kkx** [comment]
@jrief Thanks for the reply. i would give a try!

**Comment by yakky** [comment]
@kkx alternatively have a look at cmsplugin_filer which has support for thumbnails and fixed image sizes (with less options than cascade but not specific for bootstrap)

**Comment by yakky** [comment]
Closing this as strictly not-related to django CMS core
