### ISSUE TITLE
Granular placeholder caching

### ISSUE THREAD

**Issue by darbula** [divio/django-cms#3969]
It would be nice if placeholders caching could be controlled with more granularity, for example through `CMS_PLACEHOLDER_CONF`. This idea could be from my lack of understanding of correlation between page-placeholder-plugin caches but this is another issue #3961

**Comment by czpython** [comment]
Closing as this fits our feature request criteria.
If you're still interested in this feature, please create a topic in the [Developers Mailing List](https://groups.google.com/forum/#!forum/django-cms-developers).
