### ISSUE TITLE
unit tests and migration problems with PageUserGroup

### ISSUE THREAD

**Issue by kakulukia** [divio/django-cms#3970]
hi all .. i have a lil problem with migrations. Im running Django 1.7.3 and have the CMS up and running fine .. all migrations applied as far as i can tell. But when i try to run my test suite i get the following error:

django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'cms.PageUserGroup'>]

how can this be resolved?
./manage.py migrate tells me there is nothing to apply for the real database .. but when setting up the test database i get this error :/
google tells me this might have to do with my custom user model .. but like i said, the cms itself works, but the test runner cant setup the database

**Comment by yakky** [comment]
Could you provide your installed apps? Have you tried with latest Django 1.7 patch release?

**Comment by kakulukia** [comment]
somehow got it fixed but dont remember how .. closing the ticket ..
