### ISSUE TITLE
Changes in Chrome breaks ability to scroll modal dialogs on Mac OS X

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#3971]
Relevant numbers:

django CMS: 3.0.12
Chrome:  41.0.2272.104
Mac OS X: 10.10.2

Continues to work as expected in Firefox and Safari.

Here's a screencast of the issue with comparison to other browsers: http://cl.ly/3W2h1V1o1g35

**Comment by mkoistinen** [comment]
Probably relevant: https://code.google.com/p/chromium/issues/detail?id=440504#c4

**Comment by FinalAngel** [comment]
@Marketionist just tried with CMS 3.1 and latest Chrome and works for me, can you confirm?

**Comment by mkoistinen** [comment]
This issue is for 3.0.12 and it still exists for me. I have noticed that if I move the modal (click-drag the title-bar of the window), the problem goes away. We'll still need a fix though, for 3.0.x.

**Comment by mkoistinen** [comment]
I'm no longer able to reproduce once #3934 is committed.
