### ISSUE TITLE
Google maps API (v3) and modals on chrome

### ISSUE THREAD

**Issue by davidetruffo** [divio/django-cms#3972]
Hi!
I have a template with a map, and I'm initialising it using gmaps API V3. So far so good.
BUT, in edit mode, when i double click on some content to edit (in the screenshot attached it's a filer-teaser plugin in a placeholder) I see the modal (to edit the teaser) but i can't see the buttons in the bottom (save, cancel, home and breadcrumbs). The weird thing is that they are in the DOM and they are working (i can hover them, click them, and they actually works). I checked the css and no, they are not moved, nor hidden, nor anything. And i did not understand where the white thing shown in the screenshot is coming from.
This happens on chrome, but it's fine in firefox and safari.

Useful numbers:
cmsplugin-filer==0.10.1
django-cms==3.0.12
django-filer==0.9.9
djangocms-admin-style==0.2.5

Chrome: 41.0.2272.104 (64-bit)
Mac OSX: 10.10.2

screenshot:
![screen shot 2015-03-27 at 17 05 17](https://cloud.githubusercontent.com/assets/2778867/6871733/e96736be-d4a4-11e4-9924-c3efa652cec4.png)

Thanks

**Comment by davidetruffo** [comment]
Nevermind, it magically works now. Don't know why, don't know how. Everybody is happy! :)

**Comment by vxsx** [comment]
I've been running into this from time to time, it's an issue with composite layer rendering in chrome. Basically if something is being transitioned under the modal it can behave like that. Setting 
```
#cms_modal {
     -webkit-backface-visibility: hidden;
}
```
solved the issue for me.

**Comment by yakky** [comment]
@vxsx is something we may consider adding to the default Django CMS styles?

**Comment by davidetruffo** [comment]
@vxsx thanks for the tip! it happened again today, but i haven't touched the code..and after a while it was gone again..
