### ISSUE TITLE
Documentation: User tutorial - publish a page: suggestion for improvement

### ISSUE THREAD

**Issue by Moini** [divio/django-cms#3978]
I just checked out your user tutorial (to see if it contains something which should be linked from our own translators' guide).
Here (http://docs.django-cms.org/en/support-3.0.x/user/tutorial/publish_page.html) I read that 
'only you can see it.' (the draft). In my experience, this is not correct, as drafts are not saved per editor.
So I think it should maybe better be something like 'only people with permission to edit the page can see it'. Else an editor may believe that he/she is *really* the only person who can see a specific draft ;)

Another little improvement suggestion: Maybe the actual number for 'Description is restricted by the number of characters the search engines actually use to show content.' could be added here: http://docs.django-cms.org/en/support-3.0.x/user/reference/page_admin.html ? (For people who copy-paste text there and then hit the limit... I already did ;) )

**Comment by yakky** [comment]
@Moini thanks for the suggestions

**Comment by evildmp** [comment]
Thanks @Moini for the suggestion.

**Comment by Moini** [comment]
Thanks for the improvement :D
