### ISSUE TITLE
#TypeError: CMS.API.changeLanguage is not a function

### ISSUE THREAD

**Issue by skrzypek** [divio/django-cms#3979]
When i'm in the `Advanced Settings` and trying to change language (by `hvad` tab),
js console response a bug: Firefox 37.0 on Ubuntu

```
: CMS.API.changeLanguage is not a function advanced-settings:1:0 
```

And sometimes :

```
ReferenceError: apphooks_configuration is not defined cms.app_hook_select.js:21:0
```

**Comment by yakky** [comment]
Which version of django-cms?

**Comment by skrzypek** [comment]
Sorry: 
Django-cms==3.0.12

**Comment by yakky** [comment]
I cannot reproduce this.
Could you provided more context?

**Comment by skrzypek** [comment]
Sure,
My position on browser : http://127.0.0.1:8000/en/admin/cms/page/1/advanced-settings/
Available languages : 
```
Python 3.4.0 (default, Apr 11 2014, 13:05:11)                          
[GCC 4.8.2] on linux                                                   
Type "help", "copyright", "credits" or "license" for more information. 
(InteractiveConsole)                                                   
>>> from django.conf import settings                                   
>>> print(settings.LANGUAGES)                                          
(('en', 'English'), ('pl', 'Polski'))                                  
>>>                                                                    
```

And: on enter this page (advanced settings) js console return a bug 
```
Uncaught ReferenceError: apphooks_configuration is not defined  (at: cms.app_hook_select.js:21)
```

Also, when i try to click on `hvad tab` to change language, js console response a bug
```
CMS.API.changeLanguage is not a function advanced-settings:1:0 
// Uncaught TypeError: undefined is not a function  (index) :110
```

**Comment by alsoicode** [comment]
Was there ever a resolution for this? I'm currently experiencing this issue unexpectedly on a production site, and it's causing my static placeholders to disappear.

**Comment by czpython** [comment]
@vxsx can you have a look?

**Comment by vxsx** [comment]
Cannot really reproduce, would appreciate more information, maybe source of the page where it's happening.

My gut feeling is that it comes from here https://github.com/divio/django-cms/blob/854a4c245d77f7cf26f167409c292cca5d78fcd3/cms/forms/widgets.py#L254-L266

the variable declaration is not rendered properly or not at all, while the script that uses it is loaded.

**Comment by czpython** [comment]
Closing as we're unable to reproduce the issue.
Please open a new ticket if this issue is present in latest cms 3.4.x
