### ISSUE TITLE
Registering a CMSAttachMenu gives unpredictable results

### ISSUE THREAD

**Issue by lunanoko** [divio/django-cms#3990]
**Django version 1.6.11
DjangoCMS version 3.0.12**

The following code doesn't work as expected:

```
from django.utils.translation import ugettext_lazy as _
from cms.menu_bases import CMSAttachMenu
from menus.base import NavigationNode
from menus.menu_pool import menu_pool
from catalogue.models import Category
 
 
class CategoryMenu(CMSAttachMenu):
    name = _('Category menu')
 
    def get_nodes(self, request):
        nodes = []
        categories = Category.objects.root_nodes()
 
        for i in range(0, len(categories)):
            cat = categories[i]
            node = NavigationNode(cat.title, cat.get_absolute_url(), i)
            nodes.append(node)
 
        return nodes
 
 
menu_pool.register_menu(CategoryMenu)
```

When using this code either of the following 3 scenarios happen:

* In the Page admin the menu does not show up under _attached menu_
* In the Page admin the menu shows up twice under _attached menu_
* In the Page admin the menu shows up once under _attached menu_

In the first scenario, the menu of course never works (how can it?).

In the second scenario, selecting the first choice in the dropdown yields the desired result (aka: the attached menu works), but only until the next server restart. After the restart either of the three scenarios may trigger.

In the third scenario, selecting the menu and publishing the Page triggers the second scenario.

@mkoistinen Suggested passing an instance of the CategoryMenu to `menu_pool.register_menu()` instead of the class, but that resulted in a `TypeError: issubclass() arg 1 must be a class` @ menu_pool.py line 155.

**Comment by yakky** [comment]
This has been fixed in #3950 and will be released in 3.0.13
