### ISSUE TITLE
Plugin's PlaceholderField - unexpected kwarg 'editable'

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#3992]
I've added a PlaceholderField to a plugin model & it's resulted in a `TypeError: render_placeholder() got an unexpected keyword argument 'editable'`

In the template where I render the plugin I just do the usual `{% render_placeholder object.my_placeholder %}`

Is it not possible to add a PlaceholderField to a CMSPlugin model?

**Comment by yakky** [comment]
It does not have much sense, since when nested plugins became possible. Any usecase which is not covered by nested plugins?

**Comment by marksweb** [comment]
I've just come across this again. This time it's a model with a PlaceholderField & the error occurs while I'm logged in & I request the page which renders the placeholder.

The error comes out from https://github.com/divio/django-cms/blob/3.1.2/cms/models/placeholdermodel.py#L137

Variables at that time are; `editable = True` and `use_cache = True`

**Comment by czpython** [comment]
Plugins are not designed for rendering placeholders.
Instead please use nested plugins.
