### ISSUE TITLE
Document apphooks behaviour regarding publication state

### ISSUE THREAD

**Issue by sephii** [divio/django-cms#4001]
If you create (or translate) a page with an apphook, as long as you don't publish it the page will appear as a standard CMS page, because only URLconfs from apphooks of published pages are loaded.

This also leads to a tricky case: if you have a parent page that's not published, and you create a child page with an apphook, if you try to publish the child page, it will go in pending state because of the unpublished parent, and then you won't be able to access it anymore and you'll just get a 404 until the parent page gets published.

It would be great to mention in the docs that you need the parent page to be published as well for your apphook page to work.

**Comment by mkoistinen** [comment]
Closed by #4020
