### ISSUE TITLE
Circular dependency problem, if auth.User has been substituted

### ISSUE THREAD

**Issue by jrief** [divio/django-cms#4005]
This is the problem:

``PageUser`` normally is derived from ``auth.User``, but if a customized User model is used, it inherits from that class.

This customized User class is loaded with other models, some of which may import models from the CMS, for instance ``PlaceholderField``. The latter imports ``PageUser`` which causes a circular dependency.

By separating the classes and moving some import statements into the calling functions, this problem can be fixed.

I will fix this.

**Comment by jrief** [comment]
I tested with django-cms vs 3.1.2 and here everything works fine when run under uwsgi.
Therefore we can close this.

**Comment by yakky** [comment]
Thanks for the update
