### ISSUE TITLE
render_model template tag doesn't show correct change list

### ISSUE THREAD

**Issue by jproffitt** [divio/django-cms#4007]
Looking at the docs here http://django-cms.readthedocs.org/en/latest/how_to/frontend_models.html#model-changelist, it says you can show the model change list by using the special "changelist" field name.

But no matter what model instance I use, and no matter what view_url I pass in, the change list that shows in the modal is always the cms pages list. I would expect the change list for the model I specified. 

Is this intended behavior? It would be really great if this were possible.

**Comment by yakky** [comment]
Fixed in #4112
