### ISSUE TITLE
Error migrate django-cms-3.0.12

### ISSUE THREAD

**Issue by anishukserg** [divio/django-cms#4016]
Hi! I install django-cms-3.0.12 
run python2.7 ./manage.py migrate
and recive:
ERRORS:
cms.AliasPluginModel: (models.E005) The field 'level' from parent model 'cms.cmsplugin' clashes with the field 'level' from parent model 'cms.cmsplugin'.
cms.AliasPluginModel: (models.E005) The field 'lft' from parent model 'cms.cmsplugin' clashes with the field 'lft' from parent model 'cms.cmsplugin'.
cms.AliasPluginModel: (models.E005) The field 'rght' from parent model 'cms.cmsplugin' clashes with the field 'rght' from parent model 'cms.cmsplugin'.
cms.AliasPluginModel: (models.E005) The field 'tree_id' from parent model 'cms.cmsplugin' clashes with the field 'tree_id' from parent model 'cms.cmsplugin'.
cms.CMSPlugin.level: (models.E006) The field 'level' clashes with the field 'level' from model 'cms.cmsplugin'.
cms.CMSPlugin.lft: (models.E006) The field 'lft' clashes with the field 'lft' from model 'cms.cmsplugin'.
cms.CMSPlugin.rght: (models.E006) The field 'rght' clashes with the field 'rght' from model 'cms.cmsplugin'.
cms.CMSPlugin.tree_id: (models.E006) The field 'tree_id' clashes with the field 'tree_id' from model 'cms.cmsplugin'.
cms.Page.level: (models.E006) The field 'level' clashes with the field 'level' from model 'cms.page'.
cms.Page.lft: (models.E006) The field 'lft' clashes with the field 'lft' from model 'cms.page'.
cms.Page.rght: (models.E006) The field 'rght' clashes with the field 'rght' from model 'cms.page'.
cms.Page.tree_id: (models.E006) The field 'tree_id' clashes with the field 'tree_id' from model 'cms.page'.
cms.PlaceholderReference: (models.E005) The field 'level' from parent model 'cms.cmsplugin' clashes with the field 'level' from parent model 'cms.cmsplugin'.
cms.PlaceholderReference: (models.E005) The field 'lft' from parent model 'cms.cmsplugin' clashes with the field 'lft' from parent model 'cms.cmsplugin'.
cms.PlaceholderReference: (models.E005) The field 'rght' from parent model 'cms.cmsplugin' clashes with the field 'rght' from parent model 'cms.cmsplugin'.
cms.PlaceholderReference: (models.E005) The field 'tree_id' from parent model 'cms.cmsplugin' clashes with the field 'tree_id' from parent model 'cms.cmsplugin'.

**Comment by yakky** [comment]
Please install ``django-mptt==0.6.1`` and migrate again.
This is fixed in 3.0.13
