### ISSUE TITLE
Toolbar menu Page->Add Page->Duplicate this Page does not duplicate page/title extensions

### ISSUE THREAD

**Issue by samuelblattner** [divio/django-cms#4038]
Django-cms 3.0.13

When I duplicate a page using "Duplicate this Page", the extensions of the source page/titles are not duplicated.

**Comment by mkoistinen** [comment]
Hmmm, this was actually fixed, I thought, in: #4019. Previously, the extensions were copied, but incorrectly. This PR supposedly fixed that.

@samuelblattner Can you advise the Django/Python versions you are using so I can setup a test project/env?

**Comment by samuelblattner** [comment]
@mkoistinen I encountered this issue with:
django-cms==3.0.13
Django==1.6.10
Python 2.7.3

The extensions are indeed copied correctly if you use the copy page function in the tree view or if you call the copy_page method of the Page class. Strangely though, using the toolbar Menu "Page->Add Page->Duplicate this Page", the extensions aren't copied at all. Maybe this is because "Duplicate a page" uses a method other than copy_page...

**Comment by mkoistinen** [comment]
@samuelblattner thanks, this helps a lot. Looking into it...

**Comment by yakky** [comment]
@samuelblattner could you test #4283?

**Comment by yakky** [comment]
Above PR does not fix the case when a page has more than one language

**Comment by yakky** [comment]
Closed by #4361
