### ISSUE TITLE
Using search field in page tree view disrupts alignment of label columns

### ISSUE THREAD

**Issue by samuelblattner** [divio/django-cms#4060]
In django-cms 3.0.13, when I enter a keyword in the search field and hit 'search', the label columns (language, Menu, Actions, Info) are somehow shifted to the right in the result view. (see screenshot).
![screen shot 2015-04-20 at 08 37 36](https://cloud.githubusercontent.com/assets/7140314/7224942/069ddb2e-e739-11e4-9f44-bd833e3abb3e.png)

**Comment by yakky** [comment]
Fixed by #4111
