### ISSUE TITLE
ImportError: cannot import name plugin_pool

### ISSUE THREAD

**Issue by HadrienMP** [divio/django-cms#4069]
I am trying to setup a django cms and django cascade website on Webfaction.

I have an apache setup (right I think). When I start with DEBUG=True everything works fine but when I set DEBUG=False I end up getting a 500 error with the following trace. You can checkout the source here : https://github.com/HadrienMP/duxomusic. Is this something I am doing wrong or bug ?

[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1] mod_wsgi (pid=22401): Exception occurred processing WSGI script '/home/hadrienmp/webapps/duxomusic_django/duxomusic/duxomusic/wsgi.py'.
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1] Traceback (most recent call last):
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     self.load_middleware()
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     mw_instance = mw_class()
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     for url_pattern in get_resolver(None).url_patterns:
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     self._urlconf_module = import_module(self.urlconf_name)
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     __import__(name)
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/webapps/duxomusic_django/duxomusic/duxomusic/urls.py", line 7, in <module>
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     admin.autodiscover()
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     import_module('%s.admin' % app)
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     __import__(name)
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/src/djangocms-cascade/cmsplugin_cascade/extra_fields/admin.py", line 9, in <module>
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     from cmsplugin_cascade.models import PluginExtraFields
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/src/djangocms-cascade/cmsplugin_cascade/models.py", line 8, in <module>
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     from cms.plugin_pool import plugin_pool
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/cms/plugin_pool.py", line 17, in <module>
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     from cms.plugin_base import CMSPluginBase
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/cms/plugin_base.py", line 19, in <module>
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     from cms.models import CMSPlugin
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/cms/models/__init__.py", line 8, in <module>
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     from .placeholderpluginmodel import *  # nopyflakes
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/cms/models/placeholderpluginmodel.py", line 3, in <module>
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     from cms.models.fields import PlaceholderField
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/cms/models/fields.py", line 2, in <module>
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     from cms.forms.fields import PageSelectFormField
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/cms/forms/fields.py", line 8, in <module>
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     from cms.forms.widgets import PageSelectWidget, PageSmartLinkWidget
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/cms/forms/widgets.py", line 14, in <module>
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     from cms.templatetags.cms_admin import CMS_ADMIN_ICON_BASE
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/cms/templatetags/cms_admin.py", line 10, in <module>
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     from cms.utils.permissions import get_any_page_view_permissions
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]   File "/home/hadrienmp/.virtualenvs/duxomusic/lib/python2.7/site-packages/cms/utils/permissions.py", line 8, in <module>
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1]     from cms.plugin_pool import plugin_pool
[Wed Apr 22 04:10:34 2015] [error] [client 127.0.0.1] ImportError: cannot import name plugin_pool

**Comment by yakky** [comment]
Which django CMS version are you using?

**Comment by FinalAngel** [comment]
@HadrienMP can you provide additional information?

**Comment by HadrienMP** [comment]
You can probably dismiss this issue. I update to all the latests versions of my dependencies and it works. I'll do another test with djangocms out of the box on webfaction when I get a chance and let you know if it happens again

**Comment by FinalAngel** [comment]
thank you @HadrienMP
