### ISSUE TITLE
nl_NL translation is empty. Should be either dropped completely or copied from 'nl'

### ISSUE THREAD

**Issue by driesdesmet** [divio/django-cms#4070]
the 'nl' language code translation is complete, but the 'nl_NL' translation is empty. On my system, without any CMS_LANGUAGES setting and LANGUAGES set to ('nl', 'Nederlands'), the nl_NL pack seems to get picked up, thus resulting in the english fallback language.

I wonder if there is a real need to maintain both 'nl' and 'nl_BE' because officially they are the same language and I've never ran into an issue where the distinction between 'nl' in Belgium and 'nl' in The Netherlands is necessary.

**Comment by yakky** [comment]
Hi @driesdesmet, there is no need to maintain both, and we're going to remove the duplicated languages  on Sunday. We will release a patch version which includes this shortly

**Comment by driesdesmet** [comment]
Excellent. I'd be happy to help for Dutch (Nederlands) but that translations seems to be complete for 3.1.

**Comment by yakky** [comment]
Yes, translations are complete, but reporting bugs it's also great part of the contribution :)

**Comment by yakky** [comment]
Bogus translation removed from travis.
This will be fixed in next patch versions
