### ISSUE TITLE
In Edit mode, structure mode opens on long-click OR modifier-click

### ISSUE THREAD

**Issue by stephband** [divio/django-cms#4078]
When hovering over an editable area (so that you get the pop-up 'Double click to edit' next to the pointer), you can long-click to open structure mode. Sometimes structure mode opens with the clicked editable area highlighted, other times not. I'm not sure what intended behaviour is exactly, but this isn't the problem.

However, a click with a modifier held also opens structure mode, and this is really annoying because it makes inspecting the page difficult for those of us who use CTRL-click > Inspect Element (Chrome, Mac).

It's easy to ignore modifier-clicks. Just stick this in the click handler:

    function isModified(e) {
        // Is a modifier key pressed?
        return (e.ctrlKey || e.altKey);
    }
    
    function clickHandler(e) {
        if (isModified(e)) { return; }
        
        // Do what has to be done...
    }

**Comment by yakky** [comment]
This behavior has been removed in 3.1
