### ISSUE TITLE
Duplicate admin menu entries

### ISSUE THREAD

**Issue by igloox** [divio/django-cms#4079]
I recently upgraded a couple of projects to 3.1 and noticed a bug with the admin menu, when viewing pages other than CMS page objects. I found I can replicate this cleanly:

0. Create a fresh virtualenv and install djangocms-installer

1. Use djangocms-installer to create a new project with all default settings (except specifying Django-CMS 3.1)  

2. Start the development server

3. Click the 'switch to edit mode' link on the 'Installation successful' page, and log in

4. The 'example.com' menu looks like this:

![image](https://cloud.githubusercontent.com/assets/757506/7392494/087a3f66-ee80-11e4-8a4f-3970721abe5b.png)

djangocms-installer pulls down these packages:

```
Django==1.7.7
Pillow==2.8.0
argparse==1.2.1
dj-database-url==0.3.0
django-classy-tags==0.6.1
django-cms==3.1.0
django-reversion==1.8.5
django-sekizai==0.8.1
django-treebeard==3.0
djangocms-admin-style==0.2.5
djangocms-column==1.5
djangocms-file==0.1
djangocms-flash==0.2.0
djangocms-googlemap==0.2
djangocms-inherit==0.1
djangocms-installer==0.7.5
djangocms-link==1.5
djangocms-picture==0.1
djangocms-style==1.5
djangocms-teaser==0.1
djangocms-text-ckeditor==2.4.3
djangocms-video==0.1
html5lib==0.999
pytz==2015.2
requests==2.6.2
six==1.9.0
tzlocal==1.1.3
wsgiref==0.1.2
```

This is on Ubuntu 14.04, Python 2.7.6.

**Comment by FinalAngel** [comment]
I can confirm this @yakky this also happens if you follow the django CMS tutorial, add the polls urls to ``urls.py`` and than navigate to ``http://localhost:8000/polls``

**Comment by yakky** [comment]
@igloox Above PR should fix the ssue, could you test it?
