### ISSUE TITLE
Pages with restrictions are hidden in menus to anonymous user

### ISSUE THREAD

**Issue by avoine** [divio/django-cms#4082]
I want a page to be restricted in editing to a certain group but visible by anonymous users.
But with CMS_PERMISSION = True and CMS_PUBLIC_FOR = 'all'
pages with restrictions are hidden in menus to anonymous user.
But if they go to the url of the page directly they can see it.

So if I understand correctly, as soon as you restrict the edition of a page
anonymous users can't view it in the menus anymore.

Maybe adding the view permission and the anonymous user in the user list
in the permission section of a page could solve the problem.

**Comment by avoine** [comment]
an other simpler idea would be to add a new value to CMS_PUBLIC_FOR for "don't show pages with restriction in the menu" and just really show all pages by default.

**Comment by yakky** [comment]
Fixed in #4076
