### ISSUE TITLE
Cached static_placeholder displaying draft on live & no structure/content buttons

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#4084]
Just had an issue raised with me as someone's been trying to prepare new content to be published over the weekend.

I've got an app which defines static placeholders in two templates, both of which are wrapped in `{% cache %}` tags as they're very rarely changed.
```
{% cache 900 static_placeholder-content1-myapp LANGUAGE_CODE %}
    {% static_placeholder "content1-myapp" site %}
{% endcache %}
```
One of my colleagues has been to change one of these placeholders just now, and upon making the change, has noticed the structure/content buttons have gone, the page is in the live state and the change is already made.

If I remove the `cache` tags from the template, the CMS displays the structure/content buttons on every page load & has the separation between draft & live pages.

**Comment by yakky** [comment]
@marksweb static placeholders are already cached by django CMS if cache is enabled, so there is not need to use custom caching. As the static placeholders are discovered only when ``static_placeholder`` templatetag is executed, wrapping in custom cache prevents it from working properly

**Comment by marksweb** [comment]
Right, thanks. Is this documented? I don't remember ever reading that.

**Comment by yakky** [comment]
http://django-cms.readthedocs.org/en/develop/how_to/caching.html#caching
