### ISSUE TITLE
I can not create the project

### ISSUE THREAD

**Issue by tormenta1026** [divio/django-cms#4089]
I can not create the project follow the steps in the quick installation and I could not install it by any means.

http://docs.django-cms.org/en/support-3.0.x/introduction/install.html

This is the message I get:

Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the projectFailure occurred. Do you want to cleanup by removing /home/user/testing? [Y/N]

I use Debian.

I need help.

**Comment by yakky** [comment]
could you please open on https://github.com/nephila/djangocms-installer repository? any message is reported with the failure?
