### ISSUE TITLE
PlaceholderField in a model related to a plugin

### ISSUE THREAD

**Issue by sergei-maertens** [divio/django-cms#4095]
I think this is the easiest to explain with this example code:

```python
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from cms.models import CMSPlugin
from cms.models.fields import PlaceholderField, PageField


@python_2_unicode_compatible
class Society(models.Model):
    name = models.CharField(_('name'), max_length=255)
    content = PlaceholderField('content')

    members = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, null=True)

    class Meta:
        verbose_name = _('society')
        verbose_name_plural = _('societies')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('societies:detail', kwargs={'pk': self.pk})


@python_2_unicode_compatible
class SocietyPlugin(CMSPlugin):
    society = models.ForeignKey(Society)
    page_link = PageField(verbose_name=_("page"), blank=True, null=True, help_text=_("Page to link to"))

    def __str__(self):
        return self.society.name

```

When you add the plugin on the frontend, you can select the Society to link (this needs to be editable in the backend - sort of). After adding the plugin, you can double click to edit.

But, since Society has a PlaceholderField, this field cannot be edited on the backend, and as long as it's emtpy, you cannot double click this field since it's nested in the double-click of the containing plugin.

As soon as some content has been entered in the PlaceholderField, double click works as expected.

I suggest rendering the PlaceholderField placeholder with a certain hight and make it stand out like a regular placeholder when it's nested inside a plugin in structure mode.

Editing the PlaceholderField in the backend would be great too, but that's a completely different story.

This is django-cms==3.1.0.

**Comment by yakky** [comment]
frontend markup for placeholderfields it's a complicated matter, subject to all kind of strange bugs because of the DOM structure.
You can sort of overcome this by using default plugins with your placeholderfield, so the field is filled with a default set of plugins upon creation. see http://django-cms.readthedocs.org/en/develop/reference/configuration.html#cms-placeholder-conf

**Comment by mkoistinen** [comment]
Another suggestion is to use [{% render_model_add ... %}](http://django-cms.readthedocs.org/en/latest/reference/templatetags.html#render-model-add) or [{% render_model_add_block ... %}](http://django-cms.readthedocs.org/en/latest/reference/templatetags.html#render-model-add-block). (links go to the respective docs)

**Comment by czpython** [comment]
This is a won't fix in my opinion.
It's a very specific edge case and solving it would require a big frontend effort.
