### ISSUE TITLE
Use Publishing Dates to control publishing of sub-tree

### ISSUE THREAD

**Issue by mikberg** [divio/django-cms#4098]
A use case could be to create an entire sub-tree of pages, but have them held back from being viewable for visitors until a specific point in time.

If I understand the current workflow correctly, this would involve setting a publishing date for *each* of the sub pages. What I propose is to have pages in a sub-tree inherit their publishing dates from ancestors.

This would line up the "publishing dates" feature with the behavior of the "publish" buttons, which affects the sub-tree for a page.

Have I misunderstood something, is there currently a way to solve this?

**Comment by yakky** [comment]
@mikberg thanks for reporting this
@mkoistinen @evildmp this looks like a bug to me. If a parent page has a publish date in the future (or an end publish in the past) all the children pages should be inaccessible too, in the same way as the publish works

**Comment by mkoistinen** [comment]
I agree. I think any other behaviour (like what is apparently the current behaviour) would be inconsistent. I think this should be fixed in 3.0.x then ported to 3.1.x, so, I am marking this for 3.0.x.

**Comment by yakky** [comment]
@mikberg Could you test #4284 ?

**Comment by mkoistinen** [comment]
Merged #4284. Would still like confirmation of fix from @mikberg, if possible.

**Comment by mikberg** [comment]
I suppose this fix is not in a 3.1 branch? I tried using #4284, but that was not straight forward coming from 3.1.

**Comment by yakky** [comment]
@mikberg #4284 is against 3.0. It will be forward ported to 3.1 soon, but it should be easily cherry-pickable

**Comment by mikberg** [comment]
I'm sorry, I don't have the time to test this in the near future with my current setup. I'd go ahead and trust the unit test.

**Comment by yakky** [comment]
This is still relevant when a page has multiple titles

**Comment by yakky** [comment]
Double checked that this is fixed by above PR
