### ISSUE TITLE
CMS > Pages display weird when resizing window

### ISSUE THREAD

**Issue by marty3d** [divio/django-cms#4100]
I'm having issues with the admin Pages, where the javascript resizes the columns way too much: `<div class="col-softroot" style="width: 0.2px; display: block;">`
![django-cms js](https://cloud.githubusercontent.com/assets/738293/7528100/fd24b452-f555-11e4-8a53-041e89d075a5.jpg)

I don't know where to start looking for the issue, so I would really appreciate if someone with knowledge about the javascript for changing the column size would chime in here.

Happens in FF 37 and Chrome 42.

Cheers!

**Comment by yakky** [comment]
Hi @marty3d when does this happens? on page load or on page resizing? the main function behind that is https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.changelist.js#L39

**Comment by mkoistinen** [comment]
Also @marty3d do you have any custom CSS that might be in effect here? Looks like, perhaps, the main column is inheriting a 100% width or something. I've not seen this in any of the projects I am working on, so I suspect this is something special about your project =)

**Comment by marty3d** [comment]
@mkoistinen, you're right. I had some custom css snuck in there. Removing that made everything purrdy again :) There is one ssue left, where the right side of the panel disappears in FF on load, but reapperas when resizing the window, but I'll put that in a new ticket. 

Thank you!
