### ISSUE TITLE
Alias plugin keeps causing typeerror

### ISSUE THREAD

**Issue by lablua** [divio/django-cms#4104]
I have no idea how you are supposed to use the alias plugin, but every time I have tried adding it to a page, it has completely broken that page and made it uneditable. The first time I ran some command line option to fix it, but this time neither fix-mptt or delete_orphaned_plugins is working to fix it. I finally just gave up and ran "uninstall plugins AliasPlugin" so that no editors can break entire pages by accident.

Django Version:	1.6.6
django-cms (3.0.12)
django-mptt (0.6.1)
Exception Type:	TypeError
Exception Value:	
unorderable types: NoneType() < int()
Exception Location:	/home/XXX/.virtualenvs/djangocms3/lib/python3.4/site-packages/cms/utils/plugins.py in build_plugin_tree, line 312
Python Executable:	/usr/local/bin/uwsgi
Python Version:	3.4.0

**Comment by yakky** [comment]
I have been able to reproduce this by creating an alias out of a plugin and then pasting it from the clipboard
Tanks @lablua for raising the issue

**Comment by mkoistinen** [comment]
Fixed by #4106
