### ISSUE TITLE
Placeholder width too small

### ISSUE THREAD

**Issue by jmr0** [divio/django-cms#4109]
Some of my placeholders are too small. I saw that a CSS override was suggested for #3824, but I see that the min width is determined this way by cms.structureboard.js:

min = (item.width()) ? 0 : 150;

Do you see any problems with changing this to something like

min = item.width() < 150 ? 150 - item.width() : 0;

So that it pads say 15px placeholders with 135px instead? Happy to submit a pull request to this effect. Thanks.

**Comment by yakky** [comment]
The structure mode rendering is going to be adapted in the next release to overcome situation like yours. It's not an quick fix, but we'll make it better over the time

**Comment by FinalAngel** [comment]
Fixed in 3.2
