### ISSUE TITLE
Page > advanced settings enhancements

### ISSUE THREAD

**Issue by lsrtdavis** [divio/django-cms#4115]
1. allow for the choice of a 301 redirect. currently it redirects with a 302.
2. Check box to add meta robots "noindex"

**Comment by FinalAngel** [comment]
Has been enhanced in 3.2

**Comment by HenryMehta** [comment]
Is part 2 (meta robots noindex) of this issue delivered?  And if so, how do I find it because I cannot see a it on the admin screens and I cannot find it in the documentation

**Comment by fsbraun** [comment]
@HenryMehta To add meta tags to sites please use [djangocms-page-meta](https://github.com/nephila/djangocms-page-meta).

**Comment by HenryMehta** [comment]
@fsbraun I am trying to implement using djangocms-page-meta but I don't understand how I would set DjangoCMS pages to be noindex

**Comment by benzkji** [comment]
How can I achieve point 1? I dont see any 301 checkbox anywhere?

**Comment by fsbraun** [comment]
@benzkji No, a 301 redirect is not available out of the box for the django CMS UI. 

I'd suggest using the `django.contrib.redirect` app (see [docs here](https://docs.djangoproject.com/en/4.2/ref/contrib/redirects/)). It issues a permanent redirect (301) by default.

The idea is that you just keep a list of URLs to redirect and need not have stub pages cluttering the page tree.

**Comment by benzkji** [comment]
Thanks for clarifying. We've removed the parent, and will add a "manual url" to the previous child page. We already use a redirects app, but if the parent page is a status code 200, that doesnt help much. I know many cases where a  page serves as parent, but doesnt have it's own content... no cluttering there, normally. 

Why not change it to a 301? It is an intended redirect, so, worth a real 301, no? It's just the SEO guys lurking around the corner...

**Comment by fsbraun** [comment]
Well, 301 is irreversible. But I see your use case. It might be a nice PR for v4... What do you think?
