### ISSUE TITLE
manage.py cms publisher_publish --unpublished does not recognize options

### ISSUE THREAD

**Issue by benzkji** [divio/django-cms#4120]
I wonder if anyone can reproduce this?!

I'm trying to run this command:
    
    » ./manage.py cms publisher_publish --unpublished

on django-cms 3.1.0 and django 1.7.8

I get:

    » ./manage.py cms publisher_publish --unpublished
    Usage: ./manage.py cms [options] <subcommand>

    django CMS command line interface.
 
    Available subcommands:
    check
    copy-lang
    delete_orphaned_plugins
    fix-tree
    list
    moderator
    publisher_publish
    uninstall

    Use `manage.py cms <subcommand> --help` for help about subcommands

    ./manage.py: error: no such option: --unpublished

`./manage.py cms --unpublished publisher_publish` (as suggested) doesnt help, running without `--unpublished` works.

I'm a bit lost, as I can see where the commands are parsed, I see argument parsing, and I see many tests...though the tests do not really test "as if called from command line". googling around, the only thing I find halfways related is this: https://github.com/jezdez/django-configurations/issues/21

**Comment by yakky** [comment]
In 3.2 we will refactor the whole subcommands to make it easier to and more consistent

**Comment by benzkji** [comment]
is there any known way to run it with --unpublished? could save a lot of click work.

**Comment by yakky** [comment]
Not ATM. I can probably prepare a quick fix, but a release is a couple of week away

**Comment by benzkji** [comment]
ok then, thx.

quick fix (and a 3.0.1 release?) would be very very nice, but not at all critical for me.

**Comment by donce** [comment]
Yeah, it seems subcommand is not getting argument after making it as a cms subcommand.. And it's actually not very nice that tests didn't catch that - maybe we should use different testing approach for commands?

**Comment by yakky** [comment]
yeah, testing commands it's tricky.
But for 3.2 a rework of the commands is in the works that will make them easier and more consistent to use

**Comment by raiderrobert** [comment]
Running 3.2 now, and this subcommand doesn't work still. I see that it's in the codebase, so I suspect whatever bug was there is still there.

**Comment by yakky** [comment]
@raiderrobert command refactoring did not make it into 3.2, but I'm working on it for 3.3
