### ISSUE TITLE
Frontend editing issue - Plugins list not scrolling

### ISSUE THREAD

**Issue by rstalbow** [divio/django-cms#4124]
Hi 

In a placeholder when hovering on the right to get the plugin dropdown, the scroll doesn't work for a certain number of plugins. On the submenu I have the following:

![screen shot 2015-05-22 at 16 14 11](https://cloud.githubusercontent.com/assets/1573276/7773638/c5fd8d8e-009d-11e5-9b21-7e0093b65602.png)

There is 1 plugin you cant see in the list and the scroll bar doesn't. If I add another plugin then the scroll bar will appear. 

This happens in all versions on CMS 3 and CMS 3.1

**Comment by yakky** [comment]
We're going to work a lot on structure mode to avoid error like this

**Comment by vxsx** [comment]
In 3.2 we changed how adding a plugin works, and removed the scroll hint.

**Comment by yakky** [comment]
Fixed in #4476
