### ISSUE TITLE
position of child.plugin set ton None when copied and dragged into parent plugin

### ISSUE THREAD

**Issue by SachaMPS** [divio/django-cms#4126]
Sorry in advance if this is an duplicate but i couldnt find anything reasonable new related to that. 

Django: 1.6.11
DjangoCMS: 3.1

### Steps to reproduce: 
* Copy a child_plugin in structure mode
* Drag and drop the copy of the child_plugin back into the same parent_plugin in structure mode
* IMPORTANT: Don't move the plugin after drag & drop... just leave it where it has been dragged to
* Publish the page

If I enter the follwing in the parents cms_plugins.py i get "Position: None" for the copied child_plugin:

    def render(self, context, instance, placeholder):

        child_plugins = instance.child_plugin_instances

        if child_plugins:
            for child in child_plugins:
                print "Position %s" % child.position

**Comment by yakky** [comment]
@SachaMPS thanks for your detailed description
Could you check the linked PR? It should fix the issue
