### ISSUE TITLE
Can't delete page

### ISSUE THREAD

**Issue by jeltoesolnce** [divio/django-cms#4128]
Can't delte page. Server displays Error 500.

**Comment by yakky** [comment]
Could you provide more information? Django and django CMS versions plus the full traceback and settings

**Comment by jeltoesolnce** [comment]
I had have forgotten that I can view the traceback if I change DEBUG on True, I'm feeling embarrassed :-). A flash plugin was dropped. Now all works fine, thank you.
 
On Sat, 30 May 2015 07:56:37 -0700
Iacopo Spalletti <notifications@github.com> wrote:

> Could you provide more information? Django and django CMS versions plus the full traceback and settings
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/divio/django-cms/issues/4128#issuecomment-107049743


-- 
Best regards,
Vladimir Vasilenko <vladimir@shumbely.com>.

**Comment by yakky** [comment]
Thanks for the update!
