### ISSUE TITLE
Welcome page toolbar duplicates languages

### ISSUE THREAD

**Issue by ygwain** [divio/django-cms#4131]
This issue appears only for welcome page (if no pages added yet).
IMHO: Indirect reason could be that cms_menu.BasicToolbar.add_language_menu called 2 times by cms_menu.BasicToolbar.populate

Environment: django 1.6.9, django-cms 3.1

![toolbar_langs](https://cloud.githubusercontent.com/assets/1922086/7859190/43ffbb1e-0547-11e5-95f9-074a3d1b146c.png)

**Comment by yakky** [comment]
@ygwain I cannot reproduce this. Could you provide the detailed steps?

**Comment by ygwain** [comment]
https://drive.google.com/open?id=0B_Q1NeUQqkF9a3lsdTZmZTRSZ3c&authuser=0
https://drive.google.com/open?id=0B_Q1NeUQqkF9TFhheXFGVGdCQ0U&authuser=0

**Comment by yakky** [comment]
@ygwain thanks for your screencasts, could you check the above PR? Issue should be fixed

**Comment by ygwain** [comment]
It's fixed. Thanks.

**Comment by yakky** [comment]
Thanks for your contribution!
