### ISSUE TITLE
i18n URLs do not redirect on wrong language slug

### ISSUE THREAD

**Issue by stefanw** [divio/django-cms#4133]
Consider the following URLs:

- `/de/kontakt/` main language contact page
- `/en/contact/` English language contact page

However, if somehow the prefix gets changed, the following happens:
- `/en/kontakt/` serves the English contact page, but with a German URL
- `/de/contact/` serves the German contact page, but with an English URL

I believe this to be a bug. I think there should be a check if the current path (after the language prefix) matches the resolved page and if not, redirect to the page using the correct language path/slug. This should happen in order to have canonical URLs for content.

I will try to provide a PR with a test, if you consider a redirect in this case to be a solution.

**Comment by yakky** [comment]
Duplicate of #3548

**Comment by FinalAngel** [comment]
Closed as duplicate
