### ISSUE TITLE
Top-level inherited X-Frame-Options are not applied

### ISSUE THREAD

**Issue by sephii** [divio/django-cms#4140]
If your page has X-Frame-Options set to INHERIT and if it's a top-level page then `get_xframe_options` for this page will return `None` (https://github.com/divio/django-cms/blob/f6277b127c463e3188b8b19c823ff4f8aac8f82b/cms/models/pagemodel.py#L1261).

The problem is, the delegation of the X-Frame-Options handler to Django is only done if the `xframe_options` is set to `INHERIT` (https://github.com/divio/django-cms/blob/f6277b127c463e3188b8b19c823ff4f8aac8f82b/cms/views.py#L205). Since it doesn't check for a `None` value, it then sets `response.xframe_options_exempt = True` and no X-Frame option will ever be set on this page.

This actually prevents DjangoCMS users from getting ponycheck stickers at the DjangoCon so I think this issue is VERY important.

I guess the right way to do it would be to let Django's middleware handle the case also if `xframe_options` is `None.`.

**Comment by yakky** [comment]
We definitely want ponycheck stickers! This will be on top of the sprints issues

**Comment by sephii** [comment]
Sorry, couldn't wait for the sprints to start.

**Comment by yakky** [comment]
Never be sorry for a PR!
Thanks for your contribution 

On 2 June 2015 19:35:18 BST, Sylvain Fankhauser <notifications@github.com> wrote:
>Sorry, couldn't wait for the sprints to start.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/divio/django-cms/issues/4140#issuecomment-108047238

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by yakky** [comment]
Fixed by #4168
