### ISSUE TITLE
cannot select menu items shown by a context mousedown (right button) on pages in the "CMS > Pages" admin 

### ISSUE THREAD

**Issue by lddubeau** [divio/django-cms#4144]
### Versions

Django CMS 3.1
Django 1.7

I am also able to reproduce this behavior at https://control.aldryn.com/demo/get-new/

### Steps to reproduce

On a Django CMS installation that already has pages:

1. Bring up "CMS > Pages" in the admin panel. This is the admin view that shows the hierarchy of pages on the site.

2. Move the mouse over a page title. Press and hold the right mouse button. A menu will appear with "Create" and "Delete" as choices.

3. Move the mouse over any of the choices.

4. Release.

### Expected Behavior

I would expect the operation corresponding to the item's name to be performed by Django CMS. And the mouse movement should not drag the page across the screen.

### Actual Behavior

The operation that corresponds to the menu item I selected is not performed. Moving the mouse with the button pressed is treated as a drag operation by Django CMS: the page is moved across the screen. If I release the button when the page is among the other pages, it does perform a move operation.

### Observation

I've also tried just doing a right click instead of holding to see if the menu would come up and stay open, but it does not stay open.

**Comment by yakky** [comment]
@FinalAngel do we need that menu in the first place?

**Comment by FinalAngel** [comment]
@yakky I'm not so sure, I'll assign and have a look

**Comment by FinalAngel** [comment]
Correct, this needs proper event cancelation. This will be solved during the pagetree refactor in 3.3

**Comment by FinalAngel** [comment]
closed in favour of https://github.com/divio/django-cms/issues/4597, please continue the discussion here
