### ISSUE TITLE
Mention Python version support in the docs

### ISSUE THREAD

**Issue by sephii** [divio/django-cms#4150]
There is no mention whether DjangoCMS supports Python 3 or not.

**Comment by isnok** [comment]
It works fine for me with python3.4 (on debian sid).
Just now i have a box (debian stable) that uses python3.2 and i don't get the djangocms command to work...

**Comment by yakky** [comment]
Only Python 3.3 and 3.4 are supported

**Comment by ahaqxjl** [comment]
I don't think django-cms v3.1..0 support python v3.4 well.

when running under python 3.4, I get error **Pillow in virtualenv missing JPEG support** while installing django-cms from command:
`djangocms -p . mysite`

But when I running under python 2.7, it works, there is no error.

**Comment by yakky** [comment]
@ahaqxjl please file an issue at https://github.com/nephila/djangocms-installer, it's unrelated to the CMS

**Comment by isnok** [comment]
Just a side note:

Got my project to run using python 3.2.
It was really only the installer that could not be used.
Once I had all the dependencies installed by hand, I was able to run the code that the installer had created. After that, it went on like regular django(-cms) development.
