### ISSUE TITLE
CMSPlugin position vs MPTT order vs Treebeard order

### ISSUE THREAD

**Issue by julienp** [divio/django-cms#4152]
I'm having trouble wrapping my head around `CMSPlugin.position` vs MPTT order vs Treebeard order.

I have a site originally developed under 3.0 and then migrated to 3.1 (I ran the mptt fix tree manage command before migrating).

When I run fix-tree under 3.1, `CMSPlugin.position` is updated by `CMSPlugin.fix_tree` to match the order as given by the treebeard path and ends up being wrong. What is the intended behavior in 3.0, should position always match the MPTT ordering? How is it kept in sync?
Searching through the code base `CMSPlugin.position` seems to be mostly used for ordering the plugins while rendering?

I have a quite a few pages that have this issue. It is possible that the discrepancy between MPTT ordering and position came from exceptions during editing of the pages (due to other plugins/apps), or maybe there's an actual bug here. The MPTT -> Treebeard migration does not seem to do anything with the position.

**Comment by yakky** [comment]
@julienp In 3.1 it's less used than it was in mptt, but it's still needed in some part of the code.
I expect it to be phased out at some point if we can efficiently use the treebeard information to substitute it
The above PR should anyway make it consistent with ``path`` and ``depth`` values set by treebeard
