### ISSUE TITLE
Recursive nesting of the same plugin removes the settings menu

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#4154]
Recursive nesting of the same plugin in itself causes the settings menu for the inner copy of the plugin for not being initialised in structure mode
This is mostly due to some plugin rendering issue in structure mode

**Comment by yakky** [comment]
Wrong report, sorry

**Comment by kelvan** [comment]
so is this fixed already (in 3.1.1)?
I'm a bit confused ;)

**Comment by yakky** [comment]
It was not an issue in the first place :)

**Comment by kelvan** [comment]
so I have to create different plugins for each level of the menu?
or is the plugin init problem caused by something else?

**Comment by yakky** [comment]
There was no plugin init issue just a bogus error

**Comment by kelvan** [comment]
Sorry, I'm still confused. :(
So what was/is the cause of the (plugin menu not shown for childs) problem and how can I fix it?
