### ISSUE TITLE
Instructions on front page of django-cms.org are wrong

### ISSUE THREAD

**Issue by jribbens** [divio/django-cms#4179]
Right on the front page of the django-cms.org are the "see how easy it is" 5 steps to install:
```
$ pip install --upgrade virtualenv
$ virtualenv env
$ source env/bin/activate
(env) $ pip install djangocms-installer
(env) $ djangocms -p . my_demo
```
Unfortunately if you actually try this, it doesn't work:
```
Path '.' already exists and is not empty, please choose a different one
If you want to use this path anyway use the -s flag to skip this check.(env) $
```
The instructions need fixing to include `-s` or to use a different directory.

**Comment by evildmp** [comment]
You're right, and in fact the docs at http://docs.django-cms.org/en/develop/introduction/install.html#use-the-django-cms-installer include an extra step:

> Create a new directory to work in, and cd into it:

>     mkdir tutorial-project
>     cd tutorial-project

**Comment by yakky** [comment]
@evildmp would you handle the changes in the django-cms.org website and then close this?

**Comment by evildmp** [comment]
Thanks Jon for the report, now fixed. Easier fixing software than dealing with a J*dith...
