### ISSUE TITLE
Cannot edit or remove plugins from placeholder outside CMS

### ISSUE THREAD

**Issue by jproffitt** [divio/django-cms#4184]
I have followed this guide to add a placeholder to a custom model: http://django-cms.readthedocs.org/en/latest/how_to/placeholders.html. I have a model like this:

    class MyObject(models.Model):
        ...
        content_placeholder = PlaceholderField('content_placeholder')
        ...

Then, I show the the placeholder in the template:

    {% render_placeholder my_object.content_placeholder %}

All of that works great. I can add plugins to the placeholder, and everything looks great. However, I can't edit or delete any plugins there. The menu on the right side of the plugin box doesn't show up:

![screen shot 2015-06-10 at 9 42 22 am](https://cloud.githubusercontent.com/assets/2227681/8085310/0b6c14c4-0f55-11e5-9d4a-c07824df8257.png)

I CAN edit the plugin by double clicking in content mode. But can't get to the edit/delete menu from structure mode. I have tested with multiple different plugin types. I can "Empty all" plugins from the PLACEHOLDER menu, but thats not very helpful if I only want to remove one.

I have staff status, and super user status. I am using django 1.7.8 and django-cms 3.1

**Comment by jproffitt** [comment]
I figured out the root of the issue is one line 12 in the template `cms/toolbar/plugin.html`:

                'type': {% if generic %}'generic'{% else %}'plugin'{% endif %},

If type is `'generic', it doesn't show the edit menu for some reason. If I simply remove the if block, and just force it to type `'plugin'`, all is good.

What is the purpose of the `'generic'` type?

**Comment by yakky** [comment]
@jproffitt ``generic`` is to support **Frontend editing for Page and Django models** (http://django-cms.readthedocs.org/en/develop/how_to/frontend_models.html) and it's not 
I cannot reproduce this, though.
Could you reenable it and paste here the rendered ``CMS.Plugin`` configuration for that plugin?
You should be able to easily find it at the bottom of the HTML source of the page, by matching the plugin primary key. It should be something like:

    (function($) {
    // CMS.$ will be passed for $
    $(document).ready(function () {
            new CMS.Plugin('cms_plugin-2', {
                    'type': 'plugin',
                    'page_language': 'en',
                    'placeholder_id': '3',
                    'plugin_name': 'Text',
                    'plugin_type': 'TextPlugin',
                    'plugin_id': '2',
                    'plugin_language': 'en',
                    'plugin_parent': 'None',
                    'plugin_order': '',
                    'plugin_breadcrumb': [{"url": "/en/admin/cms/page/edit-plugin/2/", "title": "Text"}],
                    'plugin_restriction': ["EmptyPlugin","FilePlugin","FlashPlugin","GoogleMapPlugin","LinkPlugin","PicturePlugin","StylePlugin","TextPlugin","MultiColumnPlugin"],
                    'onClose': false,
                    'urls': {
                            'add_plugin': '/en/admin/cms/page/add-plugin/',
                            'edit_plugin': '/en/admin/cms/page/edit-plugin/2/',
                            'move_plugin': '/en/admin/cms/page/move-plugin/',
                            'delete_plugin': '/en/admin/cms/page/delete-plugin/2/',
                            'copy_plugin': '/en/admin/cms/page/copy-plugins/'
                    } 
            });
    });
    })(CMS.$);

In this case ``2`` is the plugin primary key

**Comment by jproffitt** [comment]
This is what I have:

	(function($) {
	// CMS.$ will be passed for $
	$(document).ready(function () {
		new CMS.Plugin('cms_plugin-happenings-happening-1331', {
			'type': 'generic',
			'page_language': 'en',
			'placeholder_id': '371',
			'plugin_name': 'Text',
			'plugin_type': 'TextPlugin',
			'plugin_id': '1331',
			'plugin_language': 'en',
			'plugin_parent': 'None',
			'plugin_order': '',
			'plugin_breadcrumb': [{"url": "/admin/happenings/happening/edit-plugin/1331/", "title": "Text"}],
			'plugin_restriction': ["FilerFilePlugin","FilerFolderPlugin","FilerImagePlugin","FilerLinkPlugin","FilerTeaserPlugin","FilerVideoPlugin","AliasPlugin","BannerPlugin","CMSContactPlusPlugin","ExhibitionListPlugin","CustomHtmlPlugin","FeaturePlugin","GridBlockPlugin","HeadlinePlugin","HoursPlugin","ItemScrollerPlugin","PlaceholderPlugin","HappeningListPlugin","SocialMediaOverviewPlugin","StorifyPlugin","TextPlugin","WufooFormPlugin"],
			'onClose': 'REFRESH_PAGE',
			'urls': {
				'add_plugin': '/admin/happenings/happening/add-plugin/',
				'edit_plugin': '/admin/happenings/happening/edit-plugin/1331/',
				'move_plugin': '/admin/happenings/happening/move-plugin/',
				'delete_plugin': '/admin/happenings/happening/delete-plugin/1331/',
				'copy_plugin': '/admin/cms/page/copy-plugins/'
			} 
		});
	});
	})(CMS.$);

Looks like everything is the same except for that generic type. This is on a view that does have a `{% render_model_block %}` on it, so maybe thats why? I want to be able to edit the whole model, but also be able to add plugins to the placeholder I defined on the model.

I can't figure out where the generic variable is set. It doesn't seem like it should be set in this case.

**Comment by yakky** [comment]
Would you test latest develop? Apparently there's an context leak in  ``render_model_block`` which incorrectly sets the type to ``generic`` for the plugins

**Comment by yakky** [comment]
@jproffitt does your app sett anything in the context using the ``generic`` variable?

**Comment by jproffitt** [comment]
Ah. I just realized I have my `{% render_placeholder my_object.content_placeholder %}` inside the `{% render_model_block %}`. Moving it out of the block fixes it. Is that expected? If so, I can work with that. But we should probably document that somewhere.

**Comment by yakky** [comment]
@jproffitt yes probably this behavior is worth a mention in the documentation.
The behavior is totally expected. ``render_model_block`` should only contain plain markup and filters, any templatetag can trigger unexpected behavior like this

**Comment by evildmp** [comment]
@yakky However, we have an example of exactly that in our docs: https://django-cms.readthedocs.org/en/develop/how_to/frontend_models.html#page-menu-edit:

    {% render_model_block request.current_page "changelist" %}
        <h3>Menu</h3>
        <ul>
            {% show_menu 1 100 0 1 "sidebar_submenu_root.html" %}
        </ul>
    {% endrender_model_block %}

So what's the rule?
