### ISSUE TITLE
css not loading into template

### ISSUE THREAD

**Issue by kiwiheretic** [divio/django-cms#4193]
I managed to get it installed using instructions on website.

This is the contents of web page...

&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
    &lt;title&gt;Home&lt;/title&gt;
    

    &lt;style type="text/css"&gt;
        .nav {
            padding-left: 0;
        }
        .nav li {
            display: inline;
            list-style-type: none;
            padding-right: 20px;
        }
    &lt;/style&gt;
&lt;/head&gt;
&lt;body&gt;

&lt;div style="width: 940px; margin:0 auto"&gt;
    &lt;ul class="nav"&gt;
        

    &lt;/ul&gt;
    
	&lt;h1&gt;Welcome to django CMS!&lt;/h1&gt;&lt;p&gt;The easy-to-use and developer-friendly CMS&lt;/p&gt;
&lt;div class="multicolumn3 clearfix"&gt;

  	
&lt;div class="column" style="width: 33%; float: left;"&gt;

    	&lt;h2&gt;Plugin-based&lt;/h2&gt;
&lt;p&gt;Highly extendable plugin-based system that allows you to freely build sites
with various kinds of contents.&lt;/p&gt;
&lt;h2&gt;Pretty URLs&lt;/h2&gt;
&lt;p&gt;Thanks to readable URLs the page structures are perfect for search engine
optimizations (SEO).&lt;/p&gt;
&lt;h2&gt;Plugin-based&lt;/h2&gt;
&lt;p&gt;Integrate an online shop with django SHOP - a highly flexible and
extendable e-commerce solution.&lt;/p&gt;

&lt;/div&gt;

  	
&lt;div class="column" style="width: 33%; float: left;"&gt;

    	&lt;h2&gt;Permission management&lt;/h2&gt;
&lt;p&gt;Permission management to set specific rights to different users.&lt;/p&gt;
&lt;h2&gt;Apps&lt;/h2&gt;
&lt;p&gt;Add hundreds of available Python apps easily or get the ready to use
add-ons.&lt;/p&gt;
&lt;h2&gt;Frontend-Editing&lt;/h2&gt;
&lt;p&gt;Frontend-editing to directly change content on your website. Works with all
plugins.&lt;/p&gt;

&lt;/div&gt;

  	
&lt;div class="column" style="width: 33%; float: left;"&gt;

    	&lt;h2&gt;Analytics&lt;/h2&gt;
&lt;p&gt;Add your Google Analytics account to the CMS to track all relevant data
about your users.&lt;/p&gt;
&lt;h2&gt;Developers&lt;/h2&gt;
&lt;p&gt;Hundreds of developers manage the continuous development of django CMS via
GitHub.&lt;/p&gt;
&lt;h2&gt;International&lt;/h2&gt;
&lt;p&gt;Administer multiple sites and languages. The CMS itself is translated in
over 40 languages.&lt;/p&gt;

&lt;/div&gt;

&lt;/div&gt;

&lt;/div&gt;

&lt;/body&gt;
&lt;/html&gt;

I cannot even see anywhere that the css is being loaded from any external file.  Does the default install have any styling at all ?

**Comment by yakky** [comment]
The default template shipped with the installer has no style on purpose, to leave the users able to customise it.
If you want to start with a "styled" base template, select yes at ``Use Twitter Bootstrap Theme`` option of the installer
