### ISSUE TITLE
pushState and ajax support / request.is_ajax hacks

### ISSUE THREAD

**Issue by benzkji** [divio/django-cms#4194]
I think the main thing that makes ajax support for django-cms not that easy, is django-sekizai's drawback that doesn't allow a `{% render_block "whatever" %}` in a block tag. otherwise, the quick and dirty solution seems to be a collection of `{% if request.is_ajax %}` tags. Like this: https://groups.google.com/forum/#!topic/django-cms/B-b3MGn8Onw

also, I wonder if this was discussed somewhere: https://github.com/ojii/django-sekizai/issues/9 ? and, are there other best practices for ajax loading a django-cms site I don't know about? one could create an endpoint for fetching content by placeholder_id, or something similar?

currently, I use a construct like this:

```
{% if not request.is_ajax %}
<html>
<head>
....
{% endif %}{% if request.is_ajax %}<!--{% endif %}
{% render_block "css" %}
{% if request.is_ajax %}-->{% endif %}{% if not request.is_ajax %}
</head>
<body>
.....
</bod>
```

this doesnt look very good in my eyes, but it works (had to patch templates/cms/toolbar/items/live_draft.html, as this pre-ended my comment for the toolbar with a comment  itself...). also, this only works ok for one big content section that has to be replaced...

**Comment by czpython** [comment]
Closing as this fits our feature request criteria.
If you're still interested in this feature, please create a topic in the [Developers Mailing List](https://groups.google.com/forum/#!forum/django-cms-developers).
