### ISSUE TITLE
allow custom default width for sideframe

### ISSUE THREAD

**Issue by benzkji** [divio/django-cms#4195]
is this somehow already possible?

reason: opening cms page tree doesnt show further actions (not in menu, add subpage, etc.), and filer for example is very strange to use (after uploading a file, the clipboard is not visible, and the file disapeared..)

I see use cases for a small initial width, but it would be nice to have this easily customized...?

**Comment by yakky** [comment]
Basically it's this setting https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.sideframe.js#L17
It's quite doable to make it customisable in some way

**Comment by benzkji** [comment]
as I get it, it's created here:
https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.toolbar.js#L439
and here (if it was open before reload):
https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.toolbar.js#L83

one could add a data-width per sideframe button/item to
https://github.com/divio/django-cms/blob/develop/cms/templates/cms/toolbar/items/button_sideframe.html
 
and/or a default value, but I don't see how this would best get into cms.toolbar.js? Maybe with a custom Toolbar? As I don't think a django settings.CMS_TOOLBAR_DEFAULT_SIDEFRAME_WIDTH would make it... guidance welcome. and, does it need selenium tests?

**Comment by yakky** [comment]
Adding a generic "data" attribute to the ``Button`` class (https://github.com/divio/django-cms/blob/develop/cms/toolbar/items.py#L361) is an option for custom toolbars, for the default one, tou still need to override the current default, or remove the current buttons and add it in your toolbar code.

As of now frontend tests are not required as we're in the process of completely overhauling them

**Comment by vxsx** [comment]
In 3.2 by default sideframe takes 80% of the screen.

**Comment by benzkji** [comment]
nice! thx.

**Comment by yakky** [comment]
Fixed in 3.2
