### ISSUE TITLE
Editor config

### ISSUE THREAD

**Issue by vxsx** [divio/django-cms#4201]
I'd like to propose adding [editorconfig](http://editorconfig.org/) to the djangoCMS repo.

> EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

At the moment it is stated in the documentation that python files would use 4 spaces for indentation and frontend code would use tabs (even though this is going to be changed soon). 

Editorconfig would help with the case when the contributor has some specific settings in her editor of choice and has to change them in order to contribute to the project properly. With it the issue becomes non-existent because the support is very good and it removes the need to think about these things entirely. And it's not only indentation, it's also consistent end of file newline, linebreaks, trailing whitespace, etc.

**Comment by FinalAngel** [comment]
:+1:

**Comment by yakky** [comment]
Big fat :+1: @vxsx

**Comment by yakky** [comment]
Fixed by #4205
