### ISSUE TITLE
Static placeholder recursion

### ISSUE THREAD

**Issue by antofik** [divio/django-cms#4207]
You could drag'n'drop plugin into static placeholder. If this plugin contains that very static placeholder in template, you will get infinite recursion.

The similar trick could be possible with common placeholders, were it not for another bug: placeholders in plugins are not displayed correctly in edit mode.

**Comment by yakky** [comment]
Any kind of placeholders into a plugin it's not a supported feature.
The same use case can be solved with nested plugins.
