### ISSUE TITLE
Key error when reading cms settings

### ISSUE THREAD

**Issue by antofik** [divio/django-cms#4208]
I cannot reproduce this bug stable, it occurs time to time. And after refreshing the page is goes away.
Is there any thoughts, how it could be?
![django_cms_bug](https://cloud.githubusercontent.com/assets/2310260/8325708/4436fa34-1a64-11e5-8f15-743bba51510c.jpg)

**Comment by yakky** [comment]
I wonder how this could happen
``APP_NAME`` is not in ``COMPLEX`` dictionary
I've been unable to reproduce this in many different projects using develop branch
Could you provide more information and eventually debug that portion (which is https://github.com/divio/django-cms/blob/develop/cms/utils/conf.py#L261) by inspecting the value of ``name`` and ``COMPLEX`` variables?

**Comment by antofik** [comment]
I wan't able to reproduce it for some time now, but who nows when it will appear again? Unfortunately, I cannot event understand how this exception was possible in first place... By all logic, that is impossible lest someone has monkey-patched dict or COMPLEX. The funny thing it that I wasn't using any suspicious 3rd party applications, only django 1.7 +  django cms 3.1. 

I suggest you close this bug for the time being.  And I'll let you know should it appear again

**Comment by yakky** [comment]
@antofik thanks for the update. Feel free to reopen this if you can reproduce it
