### ISSUE TITLE
Wrong german translation for "meta description"

### ISSUE THREAD

**Issue by SachaMPS** [divio/django-cms#4209]
https://github.com/divio/django-cms/blob/develop/cms/locale/de/LC_MESSAGES/django.po#L88-89

This german translation desrcibes  "meta keywords" and not a "meta description". If should rather be something like: "Eine Beschreibung der Seite, welche von Suchmaschinen verwendet wird" or similar.

**Comment by yakky** [comment]
@SachaMPS you can change it on transifex https://www.transifex.com/organization/digi604/dashboard/all_resources/de/?project=django-cms

**Comment by SachaMPS** [comment]
ah nice... I fixed it and 2 more minor spelling issues i found.

**Comment by yakky** [comment]
@SachaMPS thanks! This will be included in 3.0.14/3.1.1 due to be released shortlyt
