### ISSUE TITLE
Drag and Drop not possible in Structure Mode with IE10 and an open sidebar...

### ISSUE THREAD

**Issue by SachaMPS** [divio/django-cms#4210]
I attached a screenshot which shows the UI in the state where it seems to be not possible to drag and drop plugins anymore.

##### Steps to reproduce:
* Start IE10 in a virtualbox or similar
* Open the aldryn cms demo page
* Press Structure Mode
* Open the Sidebar with Page-Tree

##### Result
It's not possible anymore to change the position via drag and drop of the plugins in the structure view

##### This screenshot represents the combination which seems to cause this
![bildschirmfoto 2015-06-24 um 14 50 14](https://cloud.githubusercontent.com/assets/305877/8330403/736aef00-1a81-11e5-8cc9-a4c3ae1343af.png)

**Comment by yakky** [comment]
@SachaMPS which django CMS version?

**Comment by SachaMPS** [comment]
@yakky CMS 3.1

**Comment by yakky** [comment]
Thanks for the feedback

**Comment by yakky** [comment]
@FinalAngel I think we can move this to 3.2 and test this on the new frontend structure

**Comment by FinalAngel** [comment]
@yakky yes will track and fix it

**Comment by FinalAngel** [comment]
This has been solved in 3.2 :)
