### ISSUE TITLE
Adding page permission removes page from menu

### ISSUE THREAD

**Issue by jproffitt** [divio/django-cms#4211]
Correct me if there is already an issue for this, or if I am just misunderstanding how this is supposed to work. 

What I want to do, is restrict who is allowed to EDIT a specific page. I still want all users, including anonymous users to VIEW the page.

So I add a page permission, which seems to make sense:

![screen shot 2015-06-24 at 10 38 19 am](https://cloud.githubusercontent.com/assets/2227681/8334361/299d65d4-1a5d-11e5-8fed-d26b79b43d57.png)

I do NOT change the menu visibility option or the login required option at the top.

What I would expect, is now only the users in the Page Permissions section can edit the page. 

But what happens, is something very strange. The page is still visible to anonymous users, but it is removed from the menu. Even stranger is that the page's sub menu is put in its place, making the menu completely messed up.

Is this a bug or am I doing something wrong?

**Comment by jproffitt** [comment]
I should clarify that the sub menu for the page gets bumped up to the top level of the menu. So when you visit the page, there is no "sub menu" anymore. It is actually as if each of the items in that sub menu are now at the top level of the menu.

**Comment by yakky** [comment]
@jproffitt which CMS version?

**Comment by jproffitt** [comment]
Django CMS 3.1.0
Django 1.7.8

**Comment by jproffitt** [comment]
This appears to be fixed in django-cms 3.1.1. I can't reproduce the issue anymore since updating to 3.1.1.

**Comment by yakky** [comment]
@jproffitt thanks for the update. Closing this. Feel free to reopen if this happens again
