### ISSUE TITLE
urlifijs and slugify behaves differently

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#4212]
Leading to some errors when slugifying non latin words

**Comment by yakky** [comment]
Approved solution: Vendorize https://github.com/dreikanter/python-urlify and use it instead of django slugify

**Comment by yakky** [comment]
A test branch is almost ready, but I'd refrain to merge this at this later stage, pushing to 3.1.2

**Comment by yakky** [comment]
Moving to 3.2 as this will change the CMS behavior

**Comment by FinalAngel** [comment]
@yakky any update on this?

**Comment by yakky** [comment]
It's a more hairy issue than it looks. Let's skip this to 3.3. Django itself it's changing a bit the way it handles this

**Comment by yakky** [comment]
Linked to #4272
Closing this as wontfix
