### ISSUE TITLE
unpublish page translation on multilingual site does not actually unpublish the language version

### ISSUE THREAD

**Issue by jozefsukovsky** [divio/django-cms#4214]
Let's say I have a multilanguage site. My page name is
"About" for en language
"O nas" for sk language

For the first time, after the sk "O nas" has been created, but it's not published yet, I see the correct "About" fallback on site and grey indicator in the administration. After publishing sk version "O nas", everything is ok, the indicator changes to green, language version can be accessed by visitors. I decide to unpublish this sk translation for some reason, I click on "UNPUBLISH", but the page remains published in navigation menu and is publicly accessible, it only changes the indicator from green to grey. 

I'm not sure if this is an actual issue (even I expected behavior similar to hide_untranslated), but it at least causes the grey indicator to behave in two different ways. 

I've tried it from cms 3.0.12/django 1.6 to 3.1/django 1.7

thanks, 
j.

**Comment by yakky** [comment]
I can reproduce this
Do you still see sk content on the unpublished page? have you checked the reachability of the page in an anonymous browser session?

**Comment by yakky** [comment]
@jozefsukovsky have you enabled the django cache? In that case the Django cache kicks in and there is little we can do. The only option is completely clear the cache on every page unpublish but it's an overkill, usually, as usually it's ok to wait for the cache timeout to delete the page cache.
If you need immediate deletion, you can hook to ``cms.signals.post_unpublish`` and clear the cache after the signal has been fired

**Comment by jozefsukovsky** [comment]
@yakky unfortunately It's still happening, with no cache in an anonymous session (a different browser). 

I'm sorry, I was probably a bit confusing. If I unpublish all translations the page will hide completely as expected. If I unpublish just sk translation I start seeing en content on the sk page (vice-versa when I unpublish en translation). I expected unpublishing just one translation will hide the item from the specific menu and sitemap. The same way as untranslated page behaves when hide_untranslated is True. 

The use case is: I have a multilingual site and pages are already translated to all languages. Then I decide to unpublish complete page in some of available languages (I don't want any fallback I don't want to have this translation page visible in menu, sitemap, anywhere). 

I can upload a demo project somewhere if needed.

**Comment by yakky** [comment]
@jozefsukovsky that would be great, thanks (this happens both with runserver and wsgi deployment, right?)

**Comment by yakky** [comment]
@jozefsukovsky Could you test #4261 (which is based on 3.0 as I think it worth to fix the bug in 3.0 too)

**Comment by jozefsukovsky** [comment]
Attached is project as I mentioned before. I've tested with 3.0 branch and #4261 unfortunately the items are still available in the menu and opening the links shows page with no content. 

https://www.dropbox.com/s/r14xfn6m923ctge/web.tgz?dl=0

**Comment by yakky** [comment]
Sorry, current of PR assumed ``'hide_untranslated': False`` and ``'redirect_on_fallback': False``
Check the updated PR (still WiP): it returns a 404 when accessing sk/kontakty and will not show it in the menu

**Comment by yakky** [comment]
@jozefsukovsky Previous version of the PR assumed ``hide_untranslated=False`` to check the general behavior. I update with a commit regarding the menu, so the ``/sk/kontakty/`` should be now not visibile in the menu
The blank page is due to ``language_fallback=False`` (or not defined) in ``CMS_PLACEHOLDER_CONF`` which does not trigger the fallback for placeholder rendering. This  is not ``True`` by default in 3.1

**Comment by yakky** [comment]
@jozefsukovsky does the refined PR works for you?

**Comment by jozefsukovsky** [comment]
@yakky I've tested it now, it works perfectly. 

Thanks!

**Comment by yakky** [comment]
Thanks for reporting and testing!
