### ISSUE TITLE
Incorrect logging syntax raises exception

### ISSUE THREAD

**Issue by tmiller02** [divio/django-cms#4220]
When failing to move a page, this line:

`Logger.warn('mptt tree may need rebuilding: run manage.py cms fix-mptt')`

in the Page model raises an exception rather than creating any log:

`TypeError: unbound method warning() must be called with Logger instance as first argument (got str instance instead)`

**Comment by yakky** [comment]
Which django CMS version are you using?

**Comment by tmiller02** [comment]
3.0.13.
Apologies, it looks like this has already been fixed on the master branch in 27be973b025c59eb6362ac0f34a0189d5adb8cc2

**Comment by yakky** [comment]
Yes, develop it's been released as 3.1.1 two days ago
