### ISSUE TITLE
Similar field names with PageUser and my custom user model

### ISSUE THREAD

**Issue by walterrenner** [divio/django-cms#4225]
I have a similar problem as @jrief describes in #3973.
We use django 1.8.2 with a custom user Model and as i tried to install django-cms 3.1.1 i got the following error:

    django.core.exceptions.FieldError: Local field 'created_by' in class 'PageUser' clashes with field of similar name from base class 'Contact'

Unfortunately my custom User model already has a `created_by` Field. And [django does not allow to override any Field attribute from the parent Model](https://docs.djangoproject.com/en/dev/topics/db/models/#field-name-hiding-is-not-permitted).

Since the PageUser model does not add any logic rather than the `created_by` Field, the best solution for me would be to swap the PageUser model like django does with `auth.User`. Are there any Plans to support that functionality? If not, i could invest some time and send a PR.

Or anyone else ran into the same problem and can give a hint?

**Comment by jrief** [comment]
@walterrenner do you have this problem only if running under uwsgi/gunicorn or also while developing with runserver.

**Comment by walterrenner** [comment]
The error occurs already during database migration.

So when i run `./manage.py migrate cms` the field `PageUser.created_by` can not be created, because my custom user model `Contact` already has a field named `created_by`.

And because of the failed migration process either the devserver nor uwsgi/gunicorn will start up.

**Comment by philippeowagner** [comment]
Thanks @yakky for triage. We will provide a patch to fix this ASAP.

**Comment by yakky** [comment]
@walterrenner ``PageUser`` is a way to add information to the User, and it's not mean to be a ``User`` model substitute
Long-term, they way to fix this is to use an explicit OneToOneField, rather than extending from the ``User`` model

**Comment by mkoistinen** [comment]
Any takers on this issue? Looks like it just keeps getting kicked down the path.

**Comment by jvamvas** [comment]
This issue still exists with 3.2.5 as the `PageUser` model has not changed.

@yakky correctly states that a `OneToOneField` would be a better way to store CMS user data than inheriting from `AUTH_USER_MODEL`.

Another, more short-term, strategy would be to rename the field to something that is less probable to clash with a custom user model, such as `page_user_created_by`:

```python
class PageUser(User):
    page_user_created_by = models.ForeignKey(settings.AUTH_USER_MODEL, 
                                             related_name="created_users", db_column='created_by')
```

**Comment by czpython** [comment]
Closing in favor of https://github.com/divio/django-cms/issues/5517
