### ISSUE TITLE
.sass-cache dirs included in sdist/wheel

### ISSUE THREAD

**Issue by blueyed** [divio/django-cms#4244]
The following directories shouldn't be included in the wheel probably?!

 - cms/static/cms/.sass-cache
 - cms/static/cms/sass/.sass-cache

I've tried adding it to `find_packages` in `setup.py`, but that does not appear to help.  It seems to affect package names only.

    packages=find_packages(exclude=["project", "project.*", ".sass-cache"]),

**Comment by yakky** [comment]
Thanks we will clean this up in the next packaging

**Comment by yakky** [comment]
Fixed by #4528

**Comment by blueyed** [comment]
Thanks!
Would be #4258 however (typo).
