### ISSUE TITLE
Home page isn't published after upgrade to 3.0

### ISSUE THREAD

**Issue by foobacca** [divio/django-cms#4247]
We're in the process of upgrading a couple of sites from 2.4 to 3.0

After the upgrade, the home page shows the "get started" page.  Going through the admin, I can find the home page as a draft, and after I publish it then it seems to be OK again.  The other pages appear to be OK, it's just the home page.

I haven't found anything similar from googling.  Anyone else come across it?  Does this seem like a bug?

If I need to workaround this I'd like to either set up the home page correctly before the upgrade so it carries on appearing after the upgrade, or I'd like to automate this step - is there a data migration I could write that would do this for me, once I've upgraded?

**Comment by yakky** [comment]
the upgrade behavior is correct: page are migrated unpublished. you can use http://django-cms.readthedocs.org/en/develop/reference/cli.html#cms-publisher-publish to published them all at once.
I think we failed to mention this in the upgrade guide ...

**Comment by yakky** [comment]
@mkoistinen @evildmp  probably it's worth to amend this page http://django-cms.readthedocs.org/en/develop/upgrade/3.0.html#upgrading-from-2-4 to clarify the behavior

**Comment by foobacca** [comment]
+1 for adding to the upgrade notes
