### ISSUE TITLE
ValueError: Lookup failed for model referenced by field.. for PlaceholderField

### ISSUE THREAD

**Issue by mishbahr** [divio/django-cms#4252]
I'm using the `PlaceholderField` on a custom app.

django==1.7.8
django-cms==3.1.0

    @python_2_unicode_compatible
    class Post(models.Model):
        [...]
        content = PlaceholderField('post content', related_name='post_content'))

When I run the `makemigrations` command.. I get something like this:

    class Migration(migrations.Migration):

        dependencies = [
            ('auth', '0001_initial'),
            ('filer', '0002_auto_20150606_2003'),
            migrations.swappable_dependency(settings.AUTH_USER_MODEL),
            ('cms', '0012_auto_20150607_2207'),
        ]

...and this works as expected when running the `migrate` command.

However, ideally I would like to like pin the migrations dependencies to the first migration so that my app works on older versions of CMS. So something like this:

    dependencies = [
        ('auth', '0001_initial'),
        ('filer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0001_initial'),
    ]

I'm following example here: https://github.com/aldryn/aldryn-newsblog/blob/master/aldryn_newsblog/migrations/0001_initial.py

But after changing migrations to use `0001_initial`, I can't migrate anymore.

I get the following error:

    ValueError: Lookup failed for model referenced by field blogitty.Post.content: cms.Placeholder

I read about the related_name requirements in the docs and how suppressing related_name using '+' will raise a ValueError. I tried model definition both with and without related_name. No success. 

Any help will be appreciated. Many Thanks.

**Comment by mishbahr** [comment]
Trying use the oldest migrations possible, using `0002_auto_20140816_1918` works!

     ('cms', '0002_auto_20140816_1918'),

Looking through the migrations files: 

    https://github.com/divio/django-cms/blob/develop/cms/migrations/0002_auto_20140816_1918.py#L48

Does this mean `Placeholder` model is created in the `0002` migration? If thats the case, how is the `aldryn-newsblog` working with migration pinned to `0001_initial`. Am I missing something really obvious?

**Comment by yakky** [comment]
A "safe" migration to depend on is ``0003_auto_20140926_2347.py`` which was part of the first version of django CMS with Django 1.7 support. 0001 and 0002 have been splitted due to some issues when porting, and ``PlaceholderField`` is created in 0002
