### ISSUE TITLE
Login form on CMS Toolbar should use `USERNAME_FIELD`

### ISSUE THREAD

**Issue by frnhr** [divio/django-cms#4254]
Django allows custom User models that user alternative fields instead of "username". Most common example of this is probably email-only User model, i.e. User model that does not have "username" field and instead relies on "email" field for identification.

To this end, Dajngo provides `USERNAME_FIELD`: https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD

Login form on the CMS Toolbar should follow this, and not hardcode "Username" for the form label. 
NB - the login form itself works fine, only the label is wrong.

`templates/cms/toolbar/items/login.html` seems like the place to start (or finish) this.

**Comment by yakky** [comment]
Nice suggestion @frnhr would you like to contribute this enhancement?

**Comment by jproffitt** [comment]
I took a shot at fixing this in this PR: https://github.com/divio/django-cms/pull/4359

Basically, since django's `AuthenticationForm` already sets the username field's label to whatever `USERNAME_FIELD` is, we can just use that.

**Comment by yakky** [comment]
@jproffitt nice change!
