### ISSUE TITLE
Plugin position not updated when copied

### ISSUE THREAD

**Issue by ychouinard** [divio/django-cms#4269]
I'm using the get_position_in_placeholder() method of plugins to find their position. I noticed that the value of the 'position' field is not updated when a plugin is copied. If I copy the plugin in 3rd position, the copy will keep the value of 3 for the position no matter where it gets pasted.

I'm using 3.0.14

**Comment by yakky** [comment]
This has been fixed in #4167 released in 3.1.1

**Comment by ychouinard** [comment]
Great, I'll try to upgrade. Thanks!
