### ISSUE TITLE
Have caching based on permissions more configurable

### ISSUE THREAD

**Issue by boydjohnson** [divio/django-cms#4271]
My understanding is that the cms.views file uses cached content for non-logged in users and uncached content for logged-in users, so there are lines about user.is_authenticated(). Since 99% of our traffic comes from logged-in users, we copy the cms.views file and change user.is_authenticated() to user.is_staff(two lines of code in 3.0, 1 line in 3.1). It would be nice if this functionality were configurable and more abstracted.

**Comment by yakky** [comment]
@boydjohnson atually the cache is not used if the user is  authenticated **and** the toolbar is visible and in edit mode, so it does not affect normal users but only staff editors when working on the website

**Comment by FinalAngel** [comment]
@boydjohnson did this answer your question?

**Comment by boydjohnson** [comment]
Yes, it did.
