### ISSUE TITLE
Performance regression in menus in 3.0.x

### ISSUE THREAD

**Issue by vstoykov** [divio/django-cms#4276]
I found that in 3.0.11 there is a performance regression in menus. One of our site (with more than thousand pages) is now 4 times slower which leads to seconds to load the HTML when there is a cache miss for the whole page or the page can't be cached because some plugin has `cache=False`.

I used `git bisect` to investigate the issue and found that the problematic commit was https://github.com/divio/django-cms/commit/cf82e7d0d7b7bb59bbeb479fad63db95e54284b4

In that change I saw that the the page instance is also attached as attr to menu node. When I remove that line the performance is back to normal.

This change is not forward ported to 3.1.x and for that reason versions >=3.1 are not affected.

I think that the reason of slowdown is because all pages (more than thousand) need to be pickled to put in cache and then restored from a cache every time when menu need to be rendered.

I can't see where this page instance is used in the menu.
@mkoistinen Is there some special need of page instance to be put in `node.attr` only for versions >=3.0.11<3.1.0?

**Comment by mkoistinen** [comment]
These changes are indeed convoluted, sadly. I can't seem to find a nicer way to support the new CMSAttachMenus. If you have any suggestions, please advise =)

**Comment by vstoykov** [comment]
I don't see a problem with having a `page` attribute in `CMSAttachMenu`, but I can't see where `node.attr['page']` is used or I'm missing something. If page instance is not used from the node then there is no need of adding it there.

One positive thing of ability to access the page instance for given node from the node itself is when you render the menu and want to get some attribute from the page in the menu template. But the cost for that is kind of hight. Probably there is a better way.

One more thing. You said that this is for the new CMSAttachMenus, but this change (setting the page instance to menu node) is not in the 3.1.x branch. This means that not all is forward ported or just it works without need of page in node attrs?

**Comment by yakky** [comment]
@vstoykov have you tested latest 3.0.x release? After 3.0.11 changes have been to improve that part of the code.
Actually the same code is in 3.1 and develop.
I haven't noticed any sigificant impact, though

**Comment by vstoykov** [comment]
I was unable to migrate the site to 3.1. There was some issues and I have not time to investigate and see if there from our end or there is something for reporting.

But if I'm right about performance is regressed because of page instances pickling and restoring (on large sites) then this is not a problem for 3.1 because this change is not present in 3.1.x branch.

This is how it looks like in 3.1.2 https://github.com/divio/django-cms/blob/3.1.2/cms/menu.py#L108

And this is how it looks like in 3.0.14 https://github.com/divio/django-cms/blob/3.0.14/cms/menu.py#L176

**Comment by vstoykov** [comment]
This is very strange behaviour. I'm testing the same code base (with another db but with similar records) and can not see same behaviour with what I saw yesterday on the other machine.

I will continue with investigation and tests and when I have more results will write back.

**Comment by yakky** [comment]
@mkoistinen 3.0.x and 3.1.x should behave the same. I totally missed that apparently we missed a merge back from 3.0 to 3.1
We need to investigate this

**Comment by vstoykov** [comment]
I need to clear my cache between tests (when I'm not using LocMemCache).

Now I can reproduce the same behaviour on other machines. By removing the page instance from menu node the site is now fast as before upgrade.

**Comment by yakky** [comment]
Fixed by #4277

**Comment by vstoykov** [comment]
![djangocmsperformance](https://cloud.githubusercontent.com/assets/902381/8814031/db5a0d22-3010-11e5-9f5c-d4074c813d8d.png)

This is success story for the bug. You can see the date where we updated to 3.0.13 from 3.0.7 and also the date where the bug was fixed.

Thanks for the quick reaction.

**Comment by yakky** [comment]
@vstoykov thanks for reporting this. Expect an official release soon
