### ISSUE TITLE
Wrong page path for draft version (v3.0.x)

### ISSUE THREAD

**Issue by DylannCordel** [divio/django-cms#4278]
Hi guys,

I'm really annoyed to report this issue because I can not reproduce it yet... Only note it...
Here is the problem :
Some pages on a live website have draft version with a wrong path : without parents and grand-parents (but the published one is okay). When saving basic infos : no change : published Title is okay but draft is still wrong (because Title instance is not updated). When saving advanced settings / or moving the page : path is fixed (because Title is updated and is path is rebuilt)

* Django-CMS version is __3.0.13__
* No custom code has been done on CMS behaviour and/or code
* No special URLs config

I asked to my client to send us more informations on what they did on the tree and/or concerned pages. At my side, I try many things without successfully reproduce it : move pages inside the tree, published or not published, play with root page, add url overwrite, add duplicate slugs etc.

Here is a video showing the problem and fixing it by saving advanced page settings without any change : https://data.webu.coop/index.php/s/7vZpX3fKe6PWw8v

In this video, there is another page with same slug but 
* problem occurs also on pages without "slug twin sister" ; it appears to not be related. 
* concerned slugs pages are not conflicting with other apps urls neither
* problem didn't appear after a special update or migration
* problem appeared after a special admin action (currently unknown. waiting answers from our Client. Found this via the apache log : first 404 on related page and last admin action coincide)
* Problem appears at different levels in the trees (same tree, but not into the same branch)

I know this is a really bad issue report... But maybe someone has already had this problem and could add some informations to turn it into a good report ? :worried:

**Comment by yakky** [comment]
Possibly some mptt concurrency issue?
Are the pages fixed when saving the "Basic form" instead of the "Advanced"?

**Comment by DylannCordel** [comment]
No fix when only saving the basic form without any modification.. This is fixed when :

* pages are drag & dropped on the tree view
* advanced form is submited (without any change)
* slug is updated to another value, saved, then set back to it's original value.

I found into ours logs "where", "who"  and "when" the problem occured. Aparently, this was an admin POST action (this confirm it's not a management command or a migration). I am waiting an answer from the concerned manager, hoping he can remember "what" he did on June 25 at 10 PM... ^^

I also tried the `fix-mptt` management command but it didn''t work.

**Comment by DylannCordel** [comment]
App's pathes are not "rebuilt" when tree is updated. 
1. Concerned page had wrong url : `/forums/` instead of `/community/forums/`. 
2. I move then move back the "community" page to correct all child pages urls. 
3. Concerned page had good url :  `/community/forums/` but its app keeped the wrong : I had `/forums/forum/1/` instead of `/community/forums/forum/1/`

I currently dunno if this is related or just another issue. I'll have a look at this problem next week and I'll split this issue in 2 if this is not related.

**Comment by DylannCordel** [comment]
Problem solved. There was a little migration which changed the locale from "en-us" to "en-gb".
For 2nd point, this is a "normal" behaviour : a signal is sent and console show a message to restart the server.

**Comment by yakky** [comment]
Good thanks for the update
