### ISSUE TITLE
Illegal attempt to modify POST request

### ISSUE THREAD

**Issue by jrief** [divio/django-cms#4282]
Today I encountered a strange error.
When posting a plugin content, this line
https://github.com/divio/django-cms/blob/develop/cms/admin/placeholderadmin.py#L349
gave me a
```
AttributeError: This QueryDict instance is immutable
```
Well, we all know that we must copy the ``QueryDict`` before modifying it. Then I looked for code using this ``request.POST['_continue']``-flag. But this flag is never used, at least I couldn't find any occurrence.

May it be that this is dead code, which was introduced long time ago and now is unused?

BTW, this line of code is already in version 3.0.x

**Comment by yakky** [comment]
According to coverage its' not dead code, but probably run with non-proper request during tests

**Comment by yakky** [comment]
fixed by #4299

**Comment by jrief** [comment]
FYI: After some more investigation, I found out that **Django** itself uses the ``request.POST['_continue']``-flag.
