### ISSUE TITLE
Subclassing models & modeladmin classes

### ISSUE THREAD

**Issue by LeGast00n** [divio/django-cms#4297]
Hello,

I'd like to leverage Django-CMS for some specific use and subclass the Page model and related Admin model. This works after wrapping a few methods (for template names) but there is an annoying design in the current code which could be avoided:
instead of calling, in your e.g. PageModelAdmin:

    page = get_object_or_404(Page, id=object_id)

could you please instead do:

    page = get_object_or_404(self.model, id=object_id)

That would make subclassing possible easily...

Thanks
LA

**Comment by yakky** [comment]
@LeGast00n yes, we can accept a PR that makes this change. Why not contributing it? :)

**Comment by LeGast00n** [comment]
cos’ I suck with git :-(

**Comment by evildmp** [comment]
cos’ I suck with git :-(

In which case, http://dont-be-afraid-to-commit.readthedocs.org/en/latest/

And if you need any help, just ask.

**Comment by LeGast00n** [comment]
Ok, let me take it. But I need a help desk :-)
So far I have followed the tuto and:
- forked the stuff in GIT
- cloned it on my dev platform
- did `git remote add upstream git@github.com:divio/django-cms.git`
- did `git fetch upstream`
- and now I'm trying `git checkout -b ticket_4297 upstream/master`and I'm getting the following error:

    fatal: Cannot update paths and switch to branch 'ticket_4297' at the same time.
    Did you intend to checkout 'upstream/master' which can not be resolved as commit?

Can you help ? Thanks

**Comment by LeGast00n** [comment]
OK, so I understand why I have this problem: `upstream/master` is not a valid branch. Which branch should I base my own branch on ? `upstream/develop` ?
Thanks

**Comment by yakky** [comment]
You have to split the above command in two:

    git checkout upstream/develop
    git checkout -b ticket_4297

Use ``develop`` branch. Master is just the latest PyPi release

**Comment by LeGast00n** [comment]
OK, so I've done my changes and submitted a PR (hopefully).
I guess I'm finished now, right ?

**Comment by LeGast00n** [comment]
OK so I've done the changes and made a PR (#4316)
I guess I'm finished now, right ?

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/4316
