### ISSUE TITLE
Placeholder are overlapping in structure board

### ISSUE THREAD

**Issue by vmonteco** [divio/django-cms#4315]
I have a problem with my structure view. I want to render this piece of code in it : 

    {% block content %}
    <div id="content">
      <section>
        {% placeholder "content" %}
      </section>
      <div class="aside">
        {% placeholder "aside" %}
      </div>
    </div>
    {% endblock content %}

But when I try to switch to the structure view, my placeholders appear like this :

![screen shot 2015-07-25 at 16 23 54](https://cloud.githubusercontent.com/assets/11329528/8889805/93771bc2-32e9-11e5-96ec-b0c5fdf6a479.png)

This behaviour disappears if I delete one line of CSS

    #content
    {
        min-width: 1000px;
        margin-right: auto;
        margin-left: auto;
        white-space: no-wrap;
        font-size: 0;
        padding-top: 144px;
        padding-bottom: 5px;
        padding-left: 5px;
        padding-right: 5px;
    }
    
    #content > section
    {
        margin: 0;
    }
    
    #content > *
    {
        min-height: 800px;
        font-size: 16px;
        display: inline-block;    // <-- this line
        white-space: normal;
        vertical-align: top;
    }
    
    .tableau, .tableau *
    {
        min-height: 15px;
        min-width: 15px;
        margin: 0px;
        padding: 0px;
    }

    #content
    {
        width: 70%;
    }

    section
    {
        width: 75%;
    }

    aside
    {
        width: 25%;
    }

How could I prevent my placeholders from overlapping in the structure board without breaking my website style?

Thank you in advance.

**Comment by yakky** [comment]
3.2 will add an option to show placeholders in structure mode in a stacked layout so they won't interfere with each other

**Comment by foobacca** [comment]
We put the below code at the end of our `base.html` to workaround this.  It basically finds all the boxes, and ensures they are positioned within the left/right edges of the window, and that they have a minimum width.

Probably not worth putting in the main django cms given 3.2 is coming, but could be a useful workaround for others:

``` javascript
<script>
/*
 * This code resizes and repositions elements in CMS edit/structure mode
 * as they can end up off the screen sometimes, and too small.
 *
 * This code can be removed when we upgrade to Django CMS 3.2
 * https://github.com/divio/django-cms/issues/4315
 */
var CMS;
(function () {
       if (!CMS) { return; }
       var $ = CMS.$;
       function reposition(i, el) {
               var $el = $(el),
                       window_width = window.innerWidth,
                       position = $el.offset(),
                       width = $el.width();

               if (width < minWidth) {
                       $el.width(minWidth);
                       width = minWidth;
               }
               if (position.left < 0) {
                       el.style.left = 0;
               }
               if (position.left + width > window_width) {
                       el.style.left = window_width - width;
               }
       }

       var minWidth = 200;

       $(window).on("resize.sideframe", function (e) {
               // Let default positioning do its work first
               window.setTimeout(function () {
                       $(".cms_dragarea").each(reposition);
               }, 50);
       });
})();
```

And you could also make the structure areas movable by using jquery.ui to do something like:

``` javascript
CMS.$(“.cms_dragarea”).draggable()
```
