### ISSUE TITLE
When moving alias in structure mode it sometimes throws errors.

### ISSUE THREAD

**Issue by vxsx** [divio/django-cms#4318]
If you try to create an alias and then move alias next to the original plugin it throws
```
Uncaught HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
```

This happens because the alias plugin contains markup for the plugin that is aliased, e.g.
```
<div class="cms-plugin cms-plugin-2"><!-- this is an alias -->
    <div class="cms-plugin cms-plugin-1">
        I'm being aliased
    </div> 
</div>
```

and when we move things in structureboard for example here https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.plugins.js#L453
what happens is it tries to insert outer div (alias plugin) after all the occurrences of `$('.cms-plugin-1')` which is impossible since it's a child of the div we are moving.

Simple solution would be to not render `cms-plugin` wrappers for alias children

**Comment by FinalAngel** [comment]
@vxsx is this something that has been fixed in 3.2?

**Comment by vxsx** [comment]
will check, but likely no. this is related to that problem when plugin tries to insert itself in itself

**Comment by vxsx** [comment]
this should be revisited when we look at alias plugin (afair we wanted to change implementation)

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/5639
