### ISSUE TITLE
holding down LMB on a clipboard item without moving the mouse switches to content mode

### ISSUE THREAD

**Issue by ojii** [divio/django-cms#4319]
When in structure mode with an item in the clipboard, clicking (and holding down) that item with the left mouse button while **not** moving the mouse for ~1 second switches frontend editing into content mode.

I'd expect that action to switch frontend editing into "drop" mode.

**Comment by ojii** [comment]
GIF showing the issue, the first two times I just hold down the left mouse button and don't move the mouse, the third time I move it. The first two times should have the same effect as the third time.

![cms-bug-4319](https://cloud.githubusercontent.com/assets/141122/8915664/a1449072-34a6-11e5-8db3-f207c28a9da9.gif)

**Comment by yakky** [comment]
@ojii actually that behavior should have been removed in 3.1 I wonder if we left some remnants

**Comment by ojii** [comment]
I see this on one of my branches which is up-to-date with develop

**Comment by yakky** [comment]
@ojii Thanks, I think this needs more investigation to get rid of it completely

**Comment by ojii** [comment]
@yakky could you (or @FinalAngel ) point me to where this was fixed?

**Comment by ojii** [comment]
is this the commit I'm looking for? https://github.com/divio/django-cms/commit/401654988b6a5bcdcd878a82f52b0740fc849895

**Comment by ojii** [comment]
issue actually fixed, bad merge on my part, closing.
