### ISSUE TITLE
Pillow is not compiled with PNG and JPEG support

### ISSUE THREAD

**Issue by sunilsrikumar** [divio/django-cms#4331]
Almost tired of this error :) 
1.
--------------
/venv/local/lib/python2.7/site-packages/djangocms_installer/install/__init__.py", line 56, in check_install
EnvironmentError: Pillow is not compiled with PNG support, see 'Libraries installation issues' documentation section: http://djangocms-installer.readthedocs.org/en/latest/libraries.html.
Pillow is not compiled with JPEG support, see 'Libraries installation issues' documentation section: http://djangocms-installer.readthedocs.org/en/latest/libraries.html
-------------

2.
---------------
/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
-------------
Can anyone help me please?
I'm using Linux Mint 17.2 

Sunil

**Comment by sunilsrikumar** [comment]
I have tried all possible solution by Googling but no luck.

**Comment by yakky** [comment]
Please reopen on djangocms-installer  repository

**Comment by sunilsrikumar** [comment]
Thank you @yakky , re-opened at https://github.com/nephila/djangocms-installer/issues/193
