### ISSUE TITLE
Redirect to another CMS Page

### ISSUE THREAD

**Issue by darioalbanesi** [divio/django-cms#4333]
Setting a redirect to another cms page is pretty simple and very good with the support of autocomplete. However there is a bug when changing the name and slug of the target page. At the moment it doesn't adapt the redirect automatically. 

django CMS 3.0.13
django 1.6.11.post1

**Comment by FinalAngel** [comment]
@darioalbanesi can you test this again with the latest 3.2.0 develop version?

**Comment by FinalAngel** [comment]
confirmed, still valid

**Comment by FinalAngel** [comment]
duplicate of https://github.com/divio/django-cms/issues/2916
