### ISSUE TITLE
StaticPlaceholder race condition when site_id is NULL

### ISSUE THREAD

**Issue by PamelaM** [divio/django-cms#4340]
There is a race condition window where two simultaneous requests to a page that needs to create a static_placeholder can both create such a placeholder. A StaticPlaceholder object is automatically created when a page with the static_placeholder template tag is first accessed.   If the race condition is hit, however, all later accesses will fail with ```get() returned more than one StaticPlaceholder -- it returned 2!``` Internal Server error.

The workaround is to delete one of the two cms_staticplaceholder records.

The root cause is that the unique constraint on StaticPlaceholder (code, site_id) is not valid when site_id is NULL (checked with both mysql and postgres).  In both databases, NULL never equals NULL when checking for unique keys.  Thus ("FOO", NULL) != ("FOO", NULL) and two records are created when the race condition is met.

I don't have a good solution for this, so I was hoping to get some suggestions.

Failing code is the second get_or_create (from templatetags/cms_tags.py):
```
 if 'site' in extra_bits:
                site = Site.objects.get_current()
                static_placeholder, __ = StaticPlaceholder.objects.get_or_create(code=code, site_id=site.pk, defaults={'name': code,
                    'creation_method': StaticPlaceholder.CREATION_BY_TEMPLATE})
            else:
                static_placeholder, __ = StaticPlaceholder.objects.get_or_create(code=code, site_id__isnull=True, defaults={'name': code,
                    'creation_method': StaticPlaceholder.CREATION_BY_TEMPLATE})
```

**Comment by evildmp** [comment]
``site_id`` should never be NULL though, should it? (``SITE_ID`` should always be configured in ``settings.py``.)

**Comment by yakky** [comment]
@PamelaM Closing this as you are required to set SITE_ID for django CMS to work properly
