### ISSUE TITLE
Add information to the documentation about release schedule/policy

### ISSUE THREAD

**Issue by evildmp** [divio/django-cms#4341]
Should also link to Roadmap documents on the wiki https://github.com/divio/django-cms/wiki/Roadmap, which themselves need a bit of tidying up.

See https://groups.google.com/forum/#!topic/django-cms-developers/tXfDNF5XMtk

**Comment by evildmp** [comment]
See also @timgraham's proposal https://docs.google.com/document/d/1L23KhInNHc_rK5LJIJB9ZPhslGeQNaw-X9btAYD8PRY/edit

**Comment by FinalAngel** [comment]
@evildmp I'd even recommend removing the Wiki and focus on the docs - but thats just my opinion :)
