### ISSUE TITLE
Switch to apache2 and got errors

### ISSUE THREAD

**Issue by shaojun** [divio/django-cms#4345]
I'm using PYTHON 3 + Django 1.8.3, and I've checked the site-packages folder under my python env, it shows a folder: django_cms-3.1.2.dist-info, so i understands the CMS version is 3.1.2, and I installed the CMS by following the tutorial at end of July.

The default clear (no other App installed) CMS system was running fine with **'python manage.py runserver'**, but when trying to switch to Apache2 host, client always see the Internal server 500 error, the Apache error logs show:

[Sat Aug 08 20:34:42.522750 2015] [:error] [pid 30234:tid 139648034608896] [remote 112.64.61.241:46173] mod_wsgi (pid=30234): Target WSGI script '/home/shawn/tutorial$
[Sat Aug 08 20:34:42.522814 2015] [:error] [pid 30234:tid 139648034608896] [remote 112.64.61.241:46173] mod_wsgi (pid=30234): Exception occurred processing WSGI scrip$
[Sat Aug 08 20:34:42.522851 2015] [:error] [pid 30234:tid 139648034608896] [remote 112.64.61.241:46173] Traceback (most recent call last):
[Sat Aug 08 20:34:42.522883 2015] [:error] [pid 30234:tid 139648034608896] [remote 112.64.61.241:46173]   File "/home/shawn/tutorial-project/mysite/wsgi.py", line 14,$
[Sat Aug 08 20:34:42.522929 2015] [:error] [pid 30234:tid 139648034608896] [remote 112.64.61.241:46173]     application = get_wsgi_application()
[Sat Aug 08 20:34:42.522950 2015] [:error] [pid 30234:tid 139648034608896] [remote 112.64.61.241:46173]   File "/home/shawn/djangoCmsEnv/lib/python3.4/site-packages/d$
[Sat Aug 08 20:34:42.523072 2015] [:error] [pid 30234:tid 139648034608896] [remote 112.64.61.241:46173]     django.setup()
[Sat Aug 08 20:34:42.523096 2015] [:error] [pid 30234:tid 139648034608896] [remote 112.64.61.241:46173]   File "/home/shawn/djangoCmsEnv/lib/python3.4/site-packages/d$
[Sat Aug 08 20:34:42.523139 2015] [:error] [pid 30234:tid 139648034608896] [remote 112.64.61.241:46173]     apps.populate(settings.INSTALLED_APPS)
[Sat Aug 08 20:34:42.523160 2015] [:error] [pid 30234:tid 139648034608896] [remote 112.64.61.241:46173]   File "/home/shawn/djangoCmsEnv/lib/python3.4/site-packages/d$
[Sat Aug 08 20:34:42.523192 2015] [:error] [pid 30234:tid 139648034608896] [remote 112.64.61.241:46173]     raise RuntimeError("populate() isn't reentrant")
[Sat Aug 08 20:34:42.523223 2015] [:error] [pid 30234:tid 139648034608896] [remote 112.64.61.241:46173] RuntimeError: populate() isn't reentrant

anyone could help?

**Comment by yakky** [comment]
Which Django / django CMS versions?

**Comment by shaojun** [comment]
I'm using PYTHON 3 + Django 1.8.3, and not sure how to check CMS versions, but I followed the tutorial to install it at end of July.

**Comment by yakky** [comment]
@shaojun which version of the installer you used? ``pip freeze | grep 'djangocms-installer'``
Version prior to 0.7.9 may create incorrect settings

**Comment by shaojun** [comment]
pip freeze
Django==1.8.3
djangorestframework==3.2.1
wheel==0.24.0

**Comment by yakky** [comment]
@shaojun but what django CMS and djangocms installer versions?

**Comment by shaojun** [comment]
@yakky I'm quite new for Django, and what I pasted is all I got from **pip freeze** under the python virtual environment, I didn't see the **djangocms-installer** listed here.

**Comment by yakky** [comment]
So, apparently some wrong happened during the tutorial. github issues is not the best place for this kind of support.
Please check http://django-cms.readthedocs.org/en/develop/contributing/index.html#development-community for the support channels (IRC and mailing list) to get help in setting up your project
