### ISSUE TITLE
Add parameter "target" for menu.add_link_item

### ISSUE THREAD

**Issue by vivazzi** [divio/django-cms#4347]
Hello, django-cms developers!
Please, add parameter "target" to menu.add_link_item for such values as "_blank". 

It may be like that:
```
@toolbar_pool.register
class CustomToolbar(CMSToolbar):
    def populate(self):
            menu = self.toolbar.get_or_create_menu('example_menu', 'example menu')
            menu.add_link_item('my link', url='https://example.com/', target='_blank')
```

**Comment by yakky** [comment]
Hi @vivazzi thanks for suggesting this.
If anyone wants to contribute this feature is very warmly welcome to do so :)

**Comment by FinalAngel** [comment]
Instead of the target you can now use "CMD/CTRL + CLICK" on any toolbar entry and than the normal browser behaviour kicks in. No need for a target blank.
