### ISSUE TITLE
HTTP 405 Publishing pages

### ISSUE THREAD

**Issue by rstalbow** [divio/django-cms#4351]
In django-cms==3.1.1 and django-cms==3.1.2 I get a 405 when publishing a page;

[12/Aug/2015 11:14:06] "GET /en-gb/admin/cms/page/1/en-gb/publish/ HTTP/1.1" 405 0
[12/Aug/2015 11:14:07] "POST /en-gb/admin/cms/page/1/en-gb/publish/ HTTP/1.1" 302 0

It results in a blank page for the user, the new content is being published. I cant see an python errors, so have no more details to give sorry. I don't experience this issue in 3.1.0. I have just upgraded from 3.0.12

I have just checked on a second site and the same thing happens.

**Comment by ojii** [comment]
Make sure you use the new javascript files after upgrading to 3.1.1 or above. (Make sure ``collectstatic`` is run on your server, clear browser cache etc). 3.1.1 fixed a security issue with the publish button, the two HTTP requests you're seeing indicate that it's still using the old JS.

**Comment by rstalbow** [comment]
Great, that worked. Thanks

**Comment by niceguydave** [comment]
I'm experiencing similar issues. My site has multilingual functionality.

As with the OP, I can get things working fine when using `3.1.0` but get a 405 error when trying to publish a page on the front end using `3.1.1` and `3.1.2`:

```
[17/Aug/2015 15:22:19] "GET /en-gb/admin/cms/page/191/en-gb/publish/ HTTP/1.1" 405 0
```

**Comment by ojii** [comment]
multilinguality has no impact on this issue. your browser is using outdated javascript files due to your server still serving the old files and/or your browser using the old file from cache. see my reply above.

**Comment by joelbitar** [comment]
Thanks!

**Comment by harshaashok93** [comment]
I'm currently using django-cms == 3.4.1. I cleared the browser cache, the django local cache and also ran the `collectstatic` command. 
The issue still seems to exist.

**Comment by czpython** [comment]
@harshaashok93 Maybe related to https://github.com/divio/django-cms/issues/5740?

**Comment by FeedTheWeb** [comment]
Same issue Django 1.11, DjangoCms 3.5.1
It doesnt happen always, as if JS/CSS files are sometimes loaded in a different order.
