### ISSUE TITLE
Documentation update re: CMSPlugins are subclasses of ModelAdmins

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#4352]
This section: http://docs.django-cms.org/en/develop/how_to/custom_plugins.html#a-note-about-cms-plugin-base-cmspluginbase

We should make it clear that CMSPlugin is a subclass of admin.ModelAdmin and that because of this, some ModelAdmin options are not only supported but recommended in some circumstances.

Notable options that do work and make sense and are used commonly:
- exclude,
- fields,
- fieldsets,
- form,
- formfield_overrides,
- inlines,
- radio_fields,
- raw_id_fields,
- readonly_fields,

Here's a rough pass at identifying options that should have no effect (but I haven't explicitly tested. Most are exclusive to the changelist view, which isn't used by the CMSPlugin):
- actions,
- actions_on_top,
- actions_on_bottom,
- actions_selection_counter,
- date_hierarchy,
- list_display,
- list_display_links,
- list_editable,
- list_filter,
- list_max_show_all,
- list_per_page,
- ordering,
- paginator,
- preserve_fields, 
- save_as,
- save_on_top,
- search_fields,
- show_full_result_count,
- view_on_site.

**Comment by evildmp** [comment]
I am pretty sure that *all* of the change view options are available and work well. A plugin admin just is a model admin, and can be treated as such, with all kinds of cunning tricks available to you.

**Comment by mkoistinen** [comment]
Well, I haven't tested, but I'm pretty sure the CMS won't know what to with "save_as" or "save_on_top"... does it? Perhaps I'll give some of these a go...

**Comment by mkoistinen** [comment]
Confirmed. "save_as", "save_on_top", or "view_on_site" do nothing.

Well, this isn't exactly true. Using "save_as" has the side effect of making the "delete" button disappear on the form.

**Comment by yakky** [comment]
Fixed by #4353
