### ISSUE TITLE
TypeError on runserver after upgrading to Django 1.8.3 and Django-CMS 3.1.2

### ISSUE THREAD

**Issue by dsimandl** [divio/django-cms#4356]
I upgraded to Django 1.8.3 and Django-CMS 3.1.2 and I'm getting the below TypeError on startup.  I've double checked my new template settings but they seem ok to me.  Am I missing something?

```python
  File "/vagrant/virtualenv/GPP-18/lib/python3.4/site-packages/cms/utils/conf.py", line 134, in get_templates
    prefix = os.path.join(*components[components.index('templates') + 1:])
TypeError: join() missing 1 required positional argument: 'a'
```

```python
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(PROJECT_ROOT.child('templates'))],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.core.context_processors.debug',
                'django.core.context_processors.request',
                'django.core.context_processors.i18n',
                'django.core.context_processors.media',
                'django.core.context_processors.static',
                'django.core.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.media',
                'django.template.context_processors.request',
                'app.context_processors.settings',
                'app.context_processors.nav',
                'account.context_processors.forms',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
            ],
            'loaders': [
                'django.template.loaders.cached.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ]
        },
    },
]
```

**Comment by yakky** [comment]
What's your CMS_TEMPLATES configuration? Have you tested the latest support/3.1.x branch?

**Comment by dsimandl** [comment]
Thanks for getting back to me @yakky.  The CMS_TEMPLATES configuration setting is below.  I'm using the 3.1.2 release off of pypi.

`CMS_TEMPLATES_DIR = str(PROJECT_ROOT.child('templates'))`

**Comment by yakky** [comment]
@dsimandl how about ``CMS_TEMPLATES`` http://django-cms.readthedocs.org/en/develop/reference/configuration.html#cms-templates?

**Comment by dsimandl** [comment]
It looks like we are just using `CMS_TEMPLATES_DIR`.  We don't have `CMS_TEMPLATES` set anywhere in our settings

**Comment by yakky** [comment]
@dsimandl ``CMS_TEMPLATES`` is a required documentation. See above link for details
I will close this. Feel free to reopen if updating the settings does not fix the issue

**Comment by dsimandl** [comment]
I just tried to upgrade Django_CMS to 3.1.4 and Django to 1.8.7.  This error came up again.  Per the documentation below it doesn't state anything about needed to set `CMS_TEMPLATES`.

http://djangocms.readthedocs.org/en/latest/reference/configuration/#std:setting-CMS_TEMPLATES_DIR
