### ISSUE TITLE
"Only allow POST for some actions" causes problems with amazonws

### ISSUE THREAD

**Issue by panosmm** [divio/django-cms#4360]
the changes introduced here:
https://github.com/divio/django-cms/commit/c210a7684287c095850feb6f521c621011fde264
(Only allow POST for some actions)

do not allow me to publish, delete, etc. when the STATIC_URL points to amazonaws.

The publish button has a GET action when STATIC_URL points to amazonaws

**Comment by yakky** [comment]
Your setup is that the static files are server by a different domain than the website, right?
Could you report the messages in the inspector console? (I assume you cleared the cache)
I guess you should setup the CORS headers so that the statics are allowed to perform a POST

**Comment by panosmm** [comment]
Problem went away after I run collectstatic. Sorry about this - rookie mistake

**Comment by yakky** [comment]
Thanks for the update
