### ISSUE TITLE
Language Chooser template incorrect variable

### ISSUE THREAD

**Issue by leesolway** [divio/django-cms#4368]
The chooser template references the incorrect variable.. The link text should reference language.1, as the verbose name, not the  language.0, the language code. 

***Original***
```
{% load i18n menu_tags %}

{% if languages|length > 1 %}
{% for language in languages %}
<li class="lang{% if current_language == language.0 %} active{% endif %}">
	<a href="{% page_language_url language.0 %}" title="{% trans "Change to language:" %} {{ language.1 }}">{{ language.0 }}</a>
</li>
{% endfor %}
{% endif %}
```

***Should read:***
```
{% load i18n menu_tags %}

{% if languages|length > 1 %}
{% for language in languages %}
<li class="lang{% if current_language == language.0 %} active{% endif %}">
	<a href="{% page_language_url language.0 %}" title="{% trans "Change to language:" %} {{ language.1 }}">{{ language.1 }}</a>
</li>
{% endfor %}
{% endif %}
```

**Comment by yakky** [comment]
Well, sometimes you just want the language abbreviation, instead of the verbose name. Either way you a good rates of cases you'll need to customise it. Probably we should just document the behavior and provide clear information on how to customise it?

**Comment by leesolway** [comment]
The current behaviour will always render 'en' regardless of the arguments passed.
The template tag itself accepts an argument (raw, short or native) which actually changes language.1, the verbose value for this very purpose.

**Comment by yakky** [comment]
ah ok

**Comment by yakky** [comment]
Fixed by above PR
