### ISSUE TITLE
CMS shouldn't try to load CMSAttachMenus if they're not attached

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#4371]
And, CMS should be very defensive in that if one menu breaks, it should still load the others.

**Comment by ojii** [comment]
I'd argue it should try to load them (and blow up on startup ideally) so a user notices immediately if a menu is broken, instead of the CMS suddenly not working anymore after the (broken) menu is attached to a page.

**Comment by mkoistinen** [comment]
Well, the issue is that if you have an apphooks-config'ed app, that isn't attached yet to the page tree, objects in that app won't resolve. As it is now, the CMS spews messages on-screen and, in some cases, prevents other menus from loading at all.

If the CMS were to load-and-blow-up, then you'd never get a chance to create the page and apphook.

**Comment by FinalAngel** [comment]
@mkoistinen what is the current status here?

**Comment by czpython** [comment]
Menus were lightly refactored on 3.3
The CMS will no longer call get_nodes() for a cms attach menu class that's not attached.
