### ISSUE TITLE
clear_permission_cache raises TypeError when using SAML in Python 3

### ISSUE THREAD

**Issue by tomtom5152** [divio/django-cms#4373]
When running in Python 3 with memcached in binary mode, clear_permission_cache throws a TypeError due to cache.incr() saving the binary value. 

This could be solved either by manually incrementing the cache value, or simply casting to int before making the comparison on line 65.

``` python
Traceback:
  File "venv/lib/python3.4/site-packages/cms/signals/page.py", line 22, in pre_save_page
    clear_permission_cache()
  File "venv/lib/python3.4/site-packages/cms/cache/permissions.py", line 65, in clear_permission_cache
    if version > 1:
TypeError: unorderable types: bytes() > int()
```

**Comment by yakky** [comment]
Above PR should fix the issue
