### ISSUE TITLE
Pillow is not compiled with JPEG support

### ISSUE THREAD

**Issue by ZeroXn** [divio/django-cms#4375]
OSError: Pillow is not compiled with JPEG support, see 'Libraries installation issues' documentation section: http://djangocms-installer.readthedocs.org/en/latest/libraries.html

http://djangocms-installer.readthedocs.org/en/latest/libraries.html
says to make sure these dependencies are installed
    sudo apt-get install -y libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev

but i already have them installed.

    (news-cms)zerovault@zerovault-VirtualBox:~/.venvs/news-cms/project$ apt --installed list | grep "jpeg"
    
    WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.
    
    libjpeg-dev/vivid,now 8c-2ubuntu8 amd64 [installed]
    libjpeg-turbo8/vivid,now 1.3.0-0ubuntu2 amd64 [installed]
    libjpeg-turbo8-dev/vivid,now 1.3.0-0ubuntu2 amd64 [installed,automatic]
    libjpeg62/vivid,now 6b1-4ubuntu1 amd64 [installed]
    libjpeg8/vivid,now 8c-2ubuntu8 amd64 [installed]
    libjpeg8-dev/vivid,now 8c-2ubuntu8 amd64 [installed]
    libmjpegutils-2.1-0/vivid,now 1:2.1.0+debian-3 amd64 [installed,automatic]
    libopenjpeg5/vivid,now 1:1.5.2-3 amd64 [installed]

**Comment by yakky** [comment]
Please reopen this on https://github.com/nephila/djangocms-installer repository
