### ISSUE TITLE
Page actions in admin interface are not available if I use search

### ISSUE THREAD

**Issue by otg-sandrey** [divio/django-cms#4377]
In /admin/cms/ for each page I see publish/unpublish actions in a small hint window which pops up when the mouse pointer is over of one of language specific rounds at the right side of the line.

If I search for a page, then (for the pages found by the search) the hint window is not shown, and the actions are not available.

Not really sure is it a bug or a feature request. But end-users comlains that it is a bug.

**Comment by yakky** [comment]
@otg-sandrey could you check if this happens on latest support/3.1 branch? Sounds like a fixed issue

**Comment by FinalAngel** [comment]
I can confirm, this is an issue in the tree:

![image](https://cloud.githubusercontent.com/assets/270307/9953571/424da30a-5de2-11e5-884b-8421fa1304e3.png)

I cannot confirm yet if we can push a fix to 3.1 or 3.2 and will update here later. Thank you @otg-sandrey

**Comment by FinalAngel** [comment]
this has been fixed in 3.2
