### ISSUE TITLE
Broken layout on Firefox 40.0

### ISSUE THREAD

**Issue by vladir** [divio/django-cms#4379]
Hi fellows,

  I have been trying to set up `django-cms==3.1.2` for an existing project, and almost everything went smoothly. I just added one `plugin` to my project: `djangocms-text-ckeditor`. I'm very happy with the way `django-cms` is going. The only one detail I found is that the rich text editor (that comes from `djangocms-text-ckeditor`) does not show up properly on the version of `Firefox` (40.0) I'm using, when trying to add content to me pages through the `placeholders` I have defined. The layout is broken. It works like a charm on `Chrome` though. I just wanted to let know to the community, so that perhaps someone has a solution already for this. If I find time I will try to fix that myself, but I wanted to share my experiences here :). I know it is not a big issue, we can live with that ;), but the goal is to be closer of the perfection, isn't it? Thanks in advance.

Best regards,
Vladir.

**Comment by yakky** [comment]
@vladir cannot reproduce this. Could you provide some details on how to reproduce it and some screenshots?

**Comment by vladir** [comment]
Thanks for your quick response @yakky , you are totally right, it seems as it was something I had wrong on my configuration. Our front-end developer confirmed that everything was ok. I'm going to mark this as invalid. Thanks a lot again for your time.

**Comment by yakky** [comment]
Thanks for the update
