### ISSUE TITLE
haystack indexing crash after upgrade to Django 1.8

### ISSUE THREAD

**Issue by kelvan** [divio/django-cms#4380]
There is a check for DJANGO_1_7 in cms.templatetags.cms_tags._show_placeholder_for_page to use request = context.get('request', False) instead of request = context.request

Using django 1.8 this function crashes as there is no context.request

Dirty quickfix:
https://github.com/kelvan/django-cms/commit/d933cc40b442fe1c0551f1f8542413109a1588ff

**Comment by yakky** [comment]
@kelvan Thanks for reporting this. Closed by #4386
