### ISSUE TITLE
RuntimeError while migrating a fresh database

### ISSUE THREAD

**Issue by o-zander** [divio/django-cms#4390]
I just updated to django 1.8 and django-cms 3.1.2 and encountered an error while running the migrations on a fresh database (running my tests). Problem is the migration "cms.0010_migrate_use_structure".

Shortened Traceback:
> File "/Users/ozan/Documents/Projekte/baywa-django/env/lib/python2.7/site-packages/cms/migrations/0010_migrate_use_structure.py", line 14, in forwards
>    ph_ctype = ContentType.objects.get_for_model(ph_model)
>  File "/Users/ozan/Documents/Projekte/baywa-django/env/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 78, in get_for_model
>    "Error creating new content types. Please make sure contenttypes "
> RuntimeError: Error creating new content types. Please make sure contenttypes is migrated before trying to migrate apps individually.

In django 1.8 the content types model is changed. In this migration the ContentType Model is imported and queried directly. The new model function does not add the name field anymore but since the content type migration isn't yet applied the field still exists in the database table raising an integrity error. I don't know how this error could be properly handled but I think it is enough to just catch the RuntimeError and skip the migration since this error should just happen on a fresh db without any users having permissions.

**Comment by yakky** [comment]
@o-zander could you tast latest 3.1 support branch? This should have been fixed

**Comment by o-zander** [comment]
Seems to work :)

**Comment by yakky** [comment]
Awesome thanks. 3.1.3 is on the launchpad, closing this
