### ISSUE TITLE
[3.1.3] AttributeError: 'User' object has no attribute 'has_perm'

### ISSUE THREAD

**Issue by DylannCordel** [divio/django-cms#4411]
Hi,

Using orm['auth.Model'] in `0075_use_structure.py` migration can not have `has_perm` attribute:

>    File "/home/dcordel/workspace/webu/projects/ffcriavs/python-env/local/lib/python2.7/site-packages/cms/south_migrations/0075_use_structure.py", line 39, in forwards
>      if user.has_perm("cms.change_page"):
>  AttributeError: 'User' object has no attribute 'has_perm'

Using "real" `User` model (like in 3.1.2) is not a good solution. What do you recognize for this ? I could write a PR but I'm not sure about which solution is the best : using real User model ? Permission queryset on user and user's groups ? other ?

**Comment by yakky** [comment]
Not using has_perm at all but using the plain ORM methods of the historical model

**Comment by DylannCordel** [comment]
But how to achieve this with south ? the "User" model could be another Model than `contrib.auth.models.User`. Do we assert that this model had a `has_perm` method with same logic than `contrib.auth.models.User` ?
Maybe we could test if this is a `contrib.auth.models.User`'s (sub)class without any overwrite of `has_perm` : if yes, we just process the new perm addition, else, we display a Warning to inform the developer he must add the new perms himself ?

**Comment by donce** [comment]
Can't upgrade to 3.1.3 because of this error. Using custom User model.

**Comment by yakky** [comment]
@donce @DylannCordel could you check above PR?

**Comment by donce** [comment]
Sorry, I've already applied this migration from 3.1.2, which seems to be working.

**Comment by DylannCordel** [comment]
@yakky : feedback on your commit [in the PR](https://github.com/divio/django-cms/pull/4419#issuecomment-137692278).
I tested your branch at 4ff7dc07301d204b78d7a7b84c41261f4f40d985 commit with django 1.6 on an existing project : it works well.

**Comment by yakky** [comment]
Fixed by #4472

**Comment by angelomendonca** [comment]
I added this to forwards and it worked "from django.apps import apps"
