### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'cms/page/30/de/descendants'

### ISSUE THREAD

**Issue by kelvan** [divio/django-cms#4420]
I'm using 3.1.3.

Just got a Http500 in my sentry stream, accessing not existing admin url:
/admin/cms/page/cms/page/30/de/descendants/

Sadly I don't know (yet) if there is a link to this invalid url.

However imo object_id should not match with any string, but int.

Error at cms/admin/pageadmin.py:419
obj = self.model.objects.get(pk=object_id)
where "object_id" is 'cms/page/30/de/descendants'

**Comment by FinalAngel** [comment]
Please see #4552:

``Fixed it by appending the / fro admin in the urls.py and added APPEND_SLASH``

does this solve your issue?

**Comment by czpython** [comment]
Closing. Please open new ticket if the suggestion above does not fix the issue.
