### ISSUE TITLE
Improvement: Use custom plugin queryset

### ISSUE THREAD

**Issue by o-zander** [divio/django-cms#4423]
Hi, I use custom plugins which uses django-filer fields. These fields are foreign keys. I noticed multiple queries to the filer table from one plugin type, which could be avoided by using ``select_related``. But I can't find a feature to set ``select_related`` on the queryset because the queryset is build by the function ``downcast_plugins``. It would be easy to use a custom queryset since in this line: https://github.com/divio/django-cms/blob/develop/cms/utils/plugins.py#L156 the plugin admin is used to obtain the model.

My proposal is to use ``cls.get_queryset()`` or use a custom ``cls.get_plugin_queryset()`` function on the admin class which can be overwritten.

**Comment by evildmp** [comment]
Hi @o-zander, thanks for this suggestion, which looks like a useful improvement. Would you like to contribute the patch?

**Comment by o-zander** [comment]
Yes, I can do that. Maybe I can get it done this week. Any advice on forking which branch to ease the process of merging the changes?

**Comment by yakky** [comment]
@o-zander use develop. As it changes the models API is targeted to 3.2

**Comment by FinalAngel** [comment]
@mkoistinen I assume that this hasn't been solved yet (as of the reverts)?

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/4556
