### ISSUE TITLE
Unable to edit from a phone/narrow window

### ISSUE THREAD

**Issue by foobacca** [divio/django-cms#4430]
When you are using a phone (or other narrow screen) and go to edit mode, the structure/content buttons disappear completely.  This means you cannot edit the structure.  

Also, while you can open content to edit, often once opened the edit iframe is too large to be used - the save etc buttons are off the edge of the screen, and I can't scroll sideways to get to them.

While primarily editing via laptops etc, occasionally it is useful to be able to make a quick edit while on the go, so having the editing interface being entirely unusable on mobile is bad.

I've also tested this on the [aldryn demo site](https://control.aldryn.com/demo/get-new/) and the same behaviour is there, so it's not just my site.  It seems the structure/content/publish buttons disappear below 800px width, and by 550px the pop up edit boxes have lost their Cancel/Save buttons.

Maybe putting "overflow: scroll" as a media query for narrow screens on these elements would make it workable?

As a workaround, is there any way to enable the old (2.x) way of editing pages through the Django Admin interface?

**Comment by yakky** [comment]
Improving the interface for mobile devices (both in terms of layout and touch support is a goal for 3.2 and beyond CMS versions)
Old placeholder admin it's no longer available as fundamentally incompatible with the revamped 3.0 frontend editor

**Comment by FinalAngel** [comment]
This has been addressed in 3.2, though we aim for a proper support on tablet rather than phone. Yet there are some modifications on phones as well (for example the toolbar menu or fullscreen modal) to make it more usable for quick edits:

http://www.django-cms.org/en/blog/2015/10/09/rc1-release-of-django-cms-32/
