### ISSUE TITLE
Unsafe script warnings when saving/publishing through the front end

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#4432]
I've got an issue whereby publishing pages, or saving plugins is sending a request to `/admin/` over `http://` while the site is running on `https://` which is resulting in our customer reporting that the site is 'hanging' or being slow to load.

I've seen videos/screen casts from them and have confirmed that the issue with with unsafe script warnings in the browser & given them the fix, but either they forget or don't notice the shield in their address bar.

We're running 3.1.3 & I'm assuming that this is related to CMS scripts from the modal dialogs or the toolbar, so is this something other people have seen, or is it something that we'll hopefully see an end to in 3.2?

**Comment by evildmp** [comment]
Possibly related to https://github.com/divio/django-cms/issues/4215.

**Comment by evildmp** [comment]
Thanks @marksweb. We *should* have removed all the protocols (explicit references to ``http`` and so on) from the code that does this, some time ago in fact. We'd like to know more; in particular, to know if this happens all the time with all content, or just sometimes. 

Can you give us more information about the set-up? Is it possible that there is a deployment configuration that's involved?

Also, some of the actual URLs that are being asked for could be useful in identifying where these requests are coming from.

**Comment by marksweb** [comment]
Thanks @evildmp - I've done searches on the entire codebase to try to track down anything that might contain a hard coded protocol but not found anything. Which is why it really annoys me that the browser won't tell you what the scripts are. That'd make debugging really easy!

It doesn't happen all the time, and I've just tried a few pages & a few plugins without reproducing it. The only thing I can reproduce is the incorrect static link from JS; `/static/adminimg/icon_clock.gif`.

When I get it again I'll post some details.

**Comment by FinalAngel** [comment]
@marksweb I'll close until this issue appears again, thank you for the investigations! Also refere to #4215

**Comment by marksweb** [comment]
Just wanted to open this again with some content from the console as I've just published two pages which created requests to `http://`

First off I published a page which lead to this;
```
Mixed Content: The page at 'https://myproj-cms.dev.myco.com/news-media/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://myproj-cms.dev.myco.com/news-media/?edit_off'. This request has been blocked; the content must be served over HTTPS.
```
This one offered to load the unsafe scripts in chrome.

Then I published another page which didn't offer to load unsafe scripts;
```
Mixed Content: The page at 'https://myproj-cms.dev.myco.com/about/overview/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://myproj-cms.dev.myco.com/about/overview/?edit_off'. This content should also be served over HTTPS.
(index):1 
XMLHttpRequest cannot load http://myproj-cms.dev.myco.com/about/overview/?edit_off. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://myproj-cms.dev.myco.com' is therefore not allowed access. jquery.min.52d16e147b53.js:4 
XHR failed loading: POST "https://myproj-cms.dev.myco.com/admin/cms/page/52/en-gb/publish/".send @ jquery.min.52d16e147b53.js:4

    n.extend.ajax @ jquery.min.52d16e147b53.js:4
    (anonymous function) @ cms.toolbar.ceb61e181601.js:224
    n.event.dispatch @ jquery.min.52d16e147b53.js:3
    r.handle @ jquery.min.52d16e147b53.js:3
    cms.toolbar.ceb61e181601.js:234

Uncaught Error: [object Object]$.ajax.error @ cms.toolbar.ceb61e181601.js:234
    j @ jquery.min.52d16e147b53.js:2
    k.fireWith @ jquery.min.52d16e147b53.js:2
    x @ jquery.min.52d16e147b53.js:4
    b @ jquery.min.52d16e147b53.js:4
```

**Comment by FinalAngel** [comment]
Did you try it with the 3.2 version?

**Comment by marksweb** [comment]
@FinalAngel Unfortunately I've not had time to start migrating to 3.2 yet. It's been on my todo list for a while, but customer requests come first at the moment :(

**Comment by bbcreatv** [comment]
I am having the same issue while publishing on the front end on an SSL enabled site. Also using Django-CMS 3.2

    Blocked loading mixed active content

**Comment by rafael-queo** [comment]
Although no one here mentioned nginx or http server configurations, I had this problem and solved it with an nginx config. 
The line "proxy_set_header X-Forwarded-Proto https;" has to be added inside the "location /" directive and not in the "server" directive as I did in the first place.
Hope it helps.

**Comment by marksweb** [comment]
So this was similar to what @rafael-queo is talking about.

We had to get our SSL proxy to pass a header & add the following to our settings;

`SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')`

This appears to have resolved things.

**Comment by macdelacruz** [comment]
Accordingly SECURE_PROXY_SSL_HEADER should be used only if your SSL proxy strips all X-Forwarded-Proto header in incoming request. So to add to @rafael-queo `proxy_set_header X-Forwarded-Proto https` should be set to `proxy_set_header X-Forwarded-Proto $scheme` when using SECURE_PROXY_SSL_HEADER.

[https://docs.djangoproject.com/en/1.9/ref/settings/#s-secure-proxy-ssl-header](https://docs.djangoproject.com/en/1.9/ref/settings/#s-secure-proxy-ssl-header)

**Comment by philippeowagner** [comment]
We had the same issue on a machine lately. We use _nginx_ in combination with _fastcgi_pass_. 
Setting `fastcgi_param  HTTPS on;` in the location explicitly did the trick for us.

**Comment by mdoyle13** [comment]
I'm having this issue even with static files hosted on S3...
