### ISSUE TITLE
Proposal: Add "authenticated" to CMS_PUBLIC_FOR

### ISSUE THREAD

**Issue by schneck** [divio/django-cms#4434]
To make access to all CMS pages password protected by default, it would be useful to add "authenticated" as an option to the CMS_PUBLIC_FOR setting.

**Comment by czpython** [comment]
@schneck 
Hi there,
Please open a new thread for this (and any other new features) in the [django-cms-developers](https://groups.google.com/forum/#!newtopic/django-cms-developers) group.
