### ISSUE TITLE
fix-tree unconditionally discards plugin position data.

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#4456]
Currently, the fix-tree management command assumes that plugin position data is irrelevant and rebuilds the plugin tree based solely on plugin id/pk.

This is very destructive (and irrecoverable) in projects where a fix-tree operation may be warranted, but suddenly, the position of all plugins is scrambled.

**Comment by yakky** [comment]
Fixed by #4457

**Comment by donce** [comment]
My production server content just got mixed up.. I'm a bit disappointed in django-cms - didn't expect this kind of bug could be in released cms version...
