### ISSUE TITLE
Overlapping icon in filer image selection

### ISSUE THREAD

**Issue by sephii** [divio/django-cms#4511]
Not sure if it's related to Django CMS or to the filer plugin but when inserting an image the magnifying glass icon is duplicated:

![2015-09-26-103645_465x172_scrot](https://cloud.githubusercontent.com/assets/754333/10116644/d8f094ee-643a-11e5-9041-b4d013027ec8.png)

**Comment by yakky** [comment]
@sephii are you using a retina display? Which Django / django CMS / djangocms-admin-style / django-filer versions? (My guess it is a djangocms-admin-style / django-filer issue)

**Comment by sephii** [comment]
No retina display. Versions:

```
django-cms==3.1.3
django-filer==0.9.12
django==1.8.4
djangocms-admin-style==0.2.8
```

This also happens with Django CMS 3.2. Looking at the HTML gives:

```html
<a href="/en/admin/filer/folder/last/?_to_field=file_ptr" class="related-lookup" id="lookup_id_image" title="Lookup" onclick="return showRelatedObjectLookupPopup(this);">
    <img src="/static/admin/img/icon_searchbox.png" alt="Lookup" height="16" width="16">
</a>
```
The `<img>` tag contains one of the magnifying glasses, and the other one is added as a background to the `<a>` element through the `related-lookup` CSS class, defined in `/admin/css/forms.css`.

**Comment by yakky** [comment]
@FinalAngel @vxsx any hint?

**Comment by FinalAngel** [comment]
@lory87 might you have a look? That's either within django-filer or djangocms-admin-style.

**Comment by lory87** [comment]
@FinalAngel yep Will have a look as well. But new Filer and admin styles are not merged to master yet.

**Comment by lory87** [comment]
This Issue is fixed on djangocms-admin-style develop branch and will be on master in the next release.
There are some changes on django-filer develop branch which are not released yet and are related to the admin styles changes on develop.

**Comment by FinalAngel** [comment]
@yakky this can be closed here IMO as its not a django-cms issue itself and will be fixed in further versions of admin-style and filer

**Comment by yakky** [comment]
@lory87 any specific PR I can point this issue to?

**Comment by lory87** [comment]
@yakky unfortunately not. Do you agree @FinalAngel

**Comment by FinalAngel** [comment]
no have no pr either, would just point to https://github.com/stefanfoulis/django-filer/commit/c436c4252a604cd1fb06c0c92d17aa3cd9602d4f or https://github.com/divio/djangocms-admin-style/tree/develop

**Comment by yakky** [comment]
Thanks. Fixed in https://github.com/stefanfoulis/django-filer/commit/c436c4252a604cd1fb06c0c92d17aa3cd9602d4f
