### ISSUE TITLE
Make access to Page admin/frontend more consistent in Django admin

### ISSUE THREAD

**Issue by evildmp** [divio/django-cms#4517]
It's odd and confusing that selecting a Page in the Pagel list ``/admin/cms/page/`` takes you to the frontend (unlike every other admin list behaviour) but to get to the actual admin you need to select the pencil icon.

I would suggest something along the lines:

```
- [view on site] Home ............................ [@ £ $ € # ]
--- [view on site] About us ...................... [@ £ $ € # ]
```

where ``view on site`` is either text, or a very clear icon of some kind. It has to be short, and at the front of the line, otherwise it will not work well in the sideframe.

**Comment by FinalAngel** [comment]
This has been fixed now for 3.2, whilst 3.3 will introduce a technical rewrite
