### ISSUE TITLE
Python 3.2 SyntaxError with u-prefixed string in pagemodel

### ISSUE THREAD

**Issue by bittner** [divio/django-cms#4519]
The pagemodel module causes a SyntaxError with Python 3.2 (a supported version of [Django 1.8](https://pypi.python.org/pypi/Django/1.8#downloads)) due to a `u""` string [on line 144](https://github.com/divio/django-cms/blob/develop/cms/models/pagemodel.py#L144). The `u`-prefix was (temporarily) not available in Python 3.2.

Should this be replaced by `title = force_text("")`, maybe? -- I can place a pull request if that's an acceptable solution.

A format string [on line 474](https://github.com/divio/django-cms/blob/develop/cms/models/pagemodel.py#L474) also has a `u`-prefix, which should probably be removed.

**Comment by bittner** [comment]
See this [example build](https://travis-ci.org/Organice/django-organice/jobs/82554136) failing with Python 3.2, passing successfully with versions 2.7, 3.3 and 3.4.

**Comment by yakky** [comment]
Python 3.2 is not supported by django CMS
