### ISSUE TITLE
Custom User no working in 3.1.3

### ISSUE THREAD

**Issue by MrMe99** [divio/django-cms#4536]
I have the full overview here: http://stackoverflow.com/questions/32878728/django-cms-3-1-3-python-3-4-and-django-1-8-customuser

However, just a quick overview.  I create a Vanilla django-cms install using the installer.  I then create a new app that contains the custom user.  I then set the AUTH_USER_MODEL and place the app above the 'cms' in the INSTALLED_APPS.

I made sure I have all the required fields required listed in the documentation.  I even tried to comment out all the CMS dependencies and run makemigrations which works.  However, as soon as you put the cms dependencies back in then an issue arises again. 

Few things:
1) Can we confirm this is an issue?
2) Is there a current workaround?
3) Can we update the documentation to give a full How to on adding a custom user? 

I would be more then happy in writing up the documentation and contributing in anyway possible but I just don't understand what is happening at the moment. 

Thanks

**Comment by MrMe99** [comment]
Just a follow up I did figure out the problem and the workaround.  I think this is a bug in the way the django cms installer sets up the INSTALLED_APPS.

Full details can be found on the stackoverflow site.

**Comment by yakky** [comment]
`djangocms_admin_style` should be fine on top of the application list. `djangocms_text_ckeditor` can be safely moved down. I'll change the installer accordingly

**Comment by yakky** [comment]
@MrMe99 This is going to be fixed in the installer. Could you test the linked PR?

**Comment by MrMe99** [comment]
Thanks @yakky
