### ISSUE TITLE
message disappears too quickly - how to override CMS.Toolbar.options.messageDelay

### ISSUE THREAD

**Issue by foobacca** [divio/django-cms#4553]
When a django messages object is shown, and the toolbar is visible, a message appears at the top of the screen, and is cleared after 2 seconds.  That isn't very long, so I'd like to make it longer.

Looking into the code, I see in static/cms/js/modules/cms.toolbar.js that the option `messageDelay` is used in the function `openMessage()`.

Is there a supported way to override the `messageDelay` value.  I see there is a `setOptions()` method on the object, but I'd obviously need to call that before `openMessage()` is called, and it's not clear to me how I'd do that.

In general I haven't found any docs about how to customise the javascript behaviour of Django CMS - is that out there?

**Comment by FinalAngel** [comment]
@foobacca the javascript is not yet publicly available / documented. We are looking to expose it in the future. What you could do is set it anew. In CMS 3.2.0:

```javascript
CMS.API.Messages.options.messageDelay = 5000;
CMS.API:messages.open({
    message: 'Hello World'
});
```

in CMS < 3.2.0

```javascript
CMS.API.Toolbar.options.messageDelay = 5000;
CMS.API.Toolbar.open('Hello World');
```
