### ISSUE TITLE
clashing dependencies between django-cms and djangocms-text-ckeditor

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#4567]
```
djangocms-text-ckeditor==2.6.0 requires html5lib!=0.9999,!=0.99999,>=0.90
django-cms==3.1.2         requires html5lib<0.9999
```
These dependencies can't be fulfilled together. ``pip`` is pretty sloppy about those and will just pick a version based on the first rule it encounters. Stricter tools like ``pip-compile`` from ``pip-tools`` discover this though and complain.

Test to reproduce:

```
pip install pip-tools
```

create a ``requirements.in`` file:

```
django-cms==3.1.2
djangocms-text-ckeditor==2.6.0
```

```
pip-compile -v requirements.in
```

**Comment by yakky** [comment]
@stefanfoulis this is fixed in 3.1.3 ``'html5lib>=0.90,!=0.9999,!=0.99999',``
