### ISSUE TITLE
Drop Django 1.6 / Python 2.6 for django CMS 3.3

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#4581]
How about adding Django 1.7 to the list?

**Comment by FinalAngel** [comment]
You mean dropping 1.7 for 3.3?

**Comment by yakky** [comment]
Yes

**Comment by FinalAngel** [comment]
@yakky I wouldn't drop django 1.7 support yet (at least for 3.3) but rather think of getting to some kind of LTS django cms release where we drop 1.7 and rely on 1.8? Wouldn't this issue fit better into the djangocms developers mailing list? (just to get the issue count down) :D

**Comment by yakky** [comment]
ok for Django 1.7. Django 1.6 / 2.6 needs to be removed anyway :)

**Comment by FinalAngel** [comment]
closed in favour of https://github.com/divio/django-cms/issues/4580
