### ISSUE TITLE
Page preview for a new page which has not been published yet

### ISSUE THREAD

**Issue by otg-sandrey** [divio/django-cms#4606]
If I create a new page, I see "draft/production" switch in the tool bar at the top of the screen.

If I click it, Django CMS tries to show the published version of the page which doesn't exist (I have not published the page yet) and returns 404 error. It seems absolutely logical but confuse users who are not software developers.

Is there a way to hide the "draft/production" switch for pages which do not have a published version?

**Comment by FinalAngel** [comment]
closed in favour of https://github.com/divio/django-cms/issues/4634
