### ISSUE TITLE
no effect CACHE_MIDDLEWARE_ANONYMOUS_ONLY=True (in /cms/test_utils/cli.py) with django 1.8

### ISSUE THREAD

**Issue by vivazzi** [divio/django-cms#4617]
The CACHE_MIDDLEWARE_ANONYMOUS_ONLY setting is removed in django 1.8

see: http://djbook.ru/rel1.8/releases/1.8.html?highlight=settings#features-removed-in-1-8

**Comment by yakky** [comment]
It will be removed when dropping support for 1.6 and 1.7
