### ISSUE TITLE
Save plugin_type with full import path

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#462]
CMSPlugin should save the full import path to identify a plugin instead of only the class name. This would prevent name clashes with more common names.

`CMSPlugin.plugin_type`:
  current: `"TopOffersPlugin"`
  proposed: `"myapp.cms_plugins.TopOffersPlugin"`   (or maybe just `"myapp.TopOffersPlugin"`)

**Comment by FinalAngel** [comment]
@stefanfoulis is this still relevant as of #3204?

**Comment by stefanfoulis** [comment]
yes. The problem still remains.

**Comment by stefanfoulis** [comment]
Changing this should be relatively simple. A database migration can update all the existing entries. It is very internal, so the vast majority of 3rd party apps should not be affected.

Anticipated problems:

* existing fixtures
* importer/exporter tools
* ...

**Comment by czpython** [comment]
@stefanfoulis apps like django-reversion would break and force users to recreate their revision history (that or update all json strings).

**Comment by stefanfoulis** [comment]
@czpython at least for django-reversion, we could update the reversion history table in the migrations as well. And we can implement it in a way that the old format still works and will be updated on next save. That would also take care of existing fixtures being loaded in.
