### ISSUE TITLE
Link copy-pasting can lead to data loss

### ISSUE THREAD

**Issue by sephii** [divio/django-cms#4620]
When copy-pasting links a reference to the plugin is pasted instead of a copy of the plugin. Which causes issues in the following cases:

* Copying a link in a Text field (With Ctrl-C) and pasting it somewhere else and then changing it (either its title or the target) will also change the original link
* Copying the contents of a Text instance (again by selecting the text in the WYSIWYG and Ctrl-C) with links to another Text instance and then deleting the first Text instance will remove all the links in the second Text instance, which is very dangerous

**Comment by FinalAngel** [comment]
@sephii that is happening within the CKEditor or?

**Comment by sephii** [comment]
Yes.

**Comment by FinalAngel** [comment]
closing > opened issue on ckeditor
