### ISSUE TITLE
Page storage location?

### ISSUE THREAD

**Issue by rajatguptarg** [divio/django-cms#4621]
After creating a page using GUI, where the HTML file of the page get stored?

**Comment by FinalAngel** [comment]
@rajatguptarg why do you mean specifically? The pages get dynamically created according to the pages you create. /cc @mkoistinen @yakky

**Comment by yakky** [comment]
@rajatguptarg there is no such thing as "HTML file of the page". pages are generated on the fly by aggregating content from database + templates + whatever, in the same way as any django application does
