### ISSUE TITLE
Touch UX issues in 3.2.0.rc4

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#4665]
Testing out the new UI/UX for 3.2.0.rc4 on tablet but encountering several significant UX issues.

 On the Pages screen in the sidebar, I can't scroll the list of pages. If I attempt do so, it immediately grabs whatever page was under my thumb and unceremoniously dumps the page at a new location in the tree, no option to confirm or undo. It will also sometimes simultaneously place the input in the search box so the keyboard will appear and cover the messaging about the moved page, so unless you look closely after the fact, you won't know that you've completely reorganized your site.

The side frame also appears to have the same persistent UX issue as the old version, which is that trying to scroll the pages list often only scrolls the underlying page, not the content within the side frame. I can only sort of scroll if I first click into the search input box (which triggers the keyboard to pop up on tablet, obscuring much of the screen) and then try to swipe in the tiny bit of screen real estate not hidden by the keyboard and not part of the draggable target area.

The entire display box of the page title is now a drag target so now the title which is linked in blue (there's even a hover text on desktop that says 'edit this page') no longer functions as an actual link to the page. Was this intentional? It's confusing UX to have a blue link that does not work as an actual link.

Occasionally when I open the Pages screen, it only displays the published state and Menu icons but the others (such as the 'view on site' button) were not accessible and is not possible to scroll horizontally. 

![img_0277](https://cloud.githubusercontent.com/assets/24574/10985098/2c339108-83d3-11e5-9d33-872ee404dc00.jpg)

This in combination with the fact that the page title is no longer clickable, means sometimes there is no way to navigate to the CMS page through the Pages menu, only by closing the CMS toolbar and using the site's own navigation (which of course won't work for pages that aren't in the nav).

Attempting to edit a page is also nearly impossible in my tests.

There is no double click to edit, so only structure mode can be used. 

Once in structure mode, click the pencil to edit a text plugin. The modal pops up, sometimes off the screen entirely so you have to scroll up to see the text editor modal. (This blank screen is because the modal is above the visible area)

![img_0058](https://cloud.githubusercontent.com/assets/24574/10985048/c9bbb0b4-83d2-11e5-8451-bf52cd3c2b94.jpg)

Click the list of CMS plugins within the text editor. Attempt to scroll the list of plugins and it will sometimes instead scroll the underlying structure mode screen. 

In the off chance you get a plugin modal to pop up (e.g. the Link plugin), you can't scroll the Link modal to edit advanced options, it will scroll the underlying text plugin modal.

Other times it is obscured under the keyboard...

![img_0055](https://cloud.githubusercontent.com/assets/24574/10985079/073437f4-83d3-11e5-88a3-1f59454b2f6d.png)

Sometimes modals get stuck inside each other...

![img_0056](https://cloud.githubusercontent.com/assets/24574/10985138/7e7b1f62-83d3-11e5-9827-499daab9639f.png)

I tested using an iPad mini 2 and all screen shots are in landscape mode for the widest display possible. Sorry for all the discouraging news but the current state is unusable on tablet :-/

I appreciate the hard work that went into laying the foundation for a touch-enabled UI!

Refs #3796

**Comment by vxsx** [comment]
Thanks a lot for the feedback! We are addressing some of the issues already for 3.2, some will be pushed likely to next releases. The pagetree will be revamped completely, for instance, as it's way too hard to fix the current state of things. And the issues in djangocms-text-ckeditor will likely be fixed there.
 
The issue with the automatically focused input is known, but we decided not to touch templates of django/contrib/admin https://github.com/django/django/blob/6ff500127a21f5f2104dc77a09dfa73d5f7c94ce/django/contrib/admin/templates/admin/search_form.html#L16. The way it works - when you focus the iframe it focuses the input. It is disruptive on mobile devices, but there's little we can do there for the moment. 

Regarding double click - it should be possible to tap once - then the tooltip would open, and then editing modal would be open if you tap on the tooltip itself.

**Comment by FinalAngel** [comment]
- [ ] Make preview visible on smaller Sideframe size and remove link color:
https://github.com/divio/django-cms/pull/4674
- [ ] Remove search auto focus and improve scrollable area:
https://github.com/divio/django-cms/pull/4675
- [ ] Remove "edit this page" note, goes along with #4674 and #4675

More updates follow...

**Comment by vxsx** [comment]
refs https://github.com/divio/django-cms/pull/4677 which fixes the tooltip not showing up every time in the content mode

**Comment by mkoistinen** [comment]
@vxsx what's the status of this issue?

**Comment by vxsx** [comment]
We addressed almost everything as far as I can see. Some things, like scrolling when keyboard pops up are almost impossible to fix, the behaviour differs from device to device, os to os, etc., so some limitations are documented [here](https://github.com/divio/django-cms/blob/develop/docs/topics/touch.rst). The issues with ckeditor should all be fixed as well.

**Comment by mkoistinen** [comment]
Closing as per all the referenced tickets. Excellent Issue, @jsma, thank you!
