### ISSUE TITLE
[3.1.3] - AttributeError: 'User' object has no attribute 'has_perm'

### ISSUE THREAD

**Issue by dsimandl** [divio/django-cms#4672]
Looking through the issues I understand that this has been fixed on 3.1.4.  I'm just wondering if 3.1.4 is targeted for a release soon or if there is a workaround on the 3.1.3 branch to get past this issue.

**Comment by mkoistinen** [comment]
@dsimandl Can you reference a ticket where it was fixed?

**Comment by dsimandl** [comment]
@mkoistinen Looks like its #4411

**Comment by yakky** [comment]
This will be fixed in 3.1.4. We need to fix #4681 before release

**Comment by yakky** [comment]
Closed by #4472

**Comment by vinitkumar** [comment]
@yakky Where is the 3.1.4 release? I don't seem to find the tags as well for this release.

**Comment by FinalAngel** [comment]
@vinitkumar I'll check with @yakky and see if we can do a release alongside 3.2.0

**Comment by vinitkumar** [comment]
@FinalAngel Thanks, I using the repo link to access the fix. It would be great if it is released soon.

**Comment by FinalAngel** [comment]
@vinitkumar I'll make a note and let you know once its out.

**Comment by yakky** [comment]
I am waiting for 3.2 to be released, to avoid stealing travis time from the 3.2 release

**Comment by FinalAngel** [comment]
@vinitkumar I'm happy to let you know that 3.1.4 has been released alongside 3.2 :) closing this now
