### ISSUE TITLE
Refactor the CLI commands

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#4679]
Currently they have inconsitent code and interface (e.g.: options/arguments confusion)
We can refactor them to use the new argparse interface of django commands (optparse will be dropped in 1.10 anyway) and provide a better help support.

At this stage does not involve any functional change

**Comment by yakky** [comment]
@evildmp @mkoistinen @FinalAngel any comments? I can do this (I already have a draft implementation for this)

**Comment by FinalAngel** [comment]
@yakky everything that makes Travis / CLI faster is welcome

**Comment by yakky** [comment]
@FinalAngel mostly change to use argparse and options instead of the mix of arguments and options we have right now.
It's mostly an internal refactoring, except it changes the interface (aka the way the arguments are passed)

**Comment by FinalAngel** [comment]
alright its probably better for @mkoistinen to give a thumbs up than me :)

**Comment by mkoistinen** [comment]
Sounds great, @yakky!
