### ISSUE TITLE
Avoid use of _latest_ in migrations?

### ISSUE THREAD

**Issue by Jc2k** [divio/django-cms#4683]
If you are migrating a site from Django 1.6 to Django 1.8 then you will want to fake the initial migrations to bridge the gap between south and django migrations. For example, for `cms` this meant faking up to `0011_auto_20150419_1006`, but not faking `0012_auto_20150607_2207`. Great so far.

In Django 1.6 the models for content types were basically at `0001_initial` and the new Django version added `0002_remove_content_type_name`. So all our own migrations only have a dependency on `0001_initial` to make sure we don't fake `0002_remove_content_type_name` (by dependency).

Unfortunately `cms.migrations.0010_migrate_use_structure` has a dependency on the `_latest_` content types migration. This means it will cause Django to fake the content types migration `0002_remove_content_type_name`. So by faking `0011_auto_20150419_1006` i implicitly fake content types `0002_remove_content_type_name`, and end up with a broken migration to Django 1.8.

I think this migration should be updated to depend on `0001_initial` rather than `0002_remove_content_type_name`, and that `_latest_` should be avoided in future.

**Comment by yakky** [comment]
@Jc2k sounds reasonable. Fixed in above PR

**Comment by yakky** [comment]
@Jc2k does #4690 fix the issue for you?

**Comment by yakky** [comment]
@Jc2k see #4725 for fix on 3.1.x branch

**Comment by Jc2k** [comment]
Its more awkward than i first realised, unfortunately.

We went from Django 1.6.x to Django 1.8.6, and cms went from 3.1.0 to 3.1.3. If you migrate like we did, you want to fake contenttypes up to `001_initial` and fake cms up to `0011_auto_20150419_1006`. In that case this change is absolutely required, otherwise `0002_remove_content_type_name` will never run. And then stuff will break. For example, as part of the `post_migrate` signal content types are synced, and this will error because `0002_remove_content_type_name` hasn't run.

If you rebuild from scratch you need to build conttenttypes `0002_remove_content_type_name` before you apply the cms migrations otherwise you get:
         
    File "/app/local/lib/python2.7/site-packages/cms/migrations/0010_migrate_use_structure.py", line 15, in forwards
      ph_ctype = ContentType.objects.get_for_model(ph_model)          
    File "/app/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 78, in get_for_model
     "Error creating new content types. Please make sure contenttypes "
    RuntimeError: Error creating new content types. Please make sure contenttypes is migrated before trying to migrate apps individually.

I don't believe there is a way to express this with django migration dependencies as they are...

**Comment by yakky** [comment]
@Jc2k In that case I usually don't trust the migrations dependency and I fake / apply django contrib migrations first and explicitly, and only after that i fake the others

**Comment by mkoistinen** [comment]
Can this be closed?

**Comment by yakky** [comment]
Yes
