### ISSUE TITLE
3.2 upgrade notes incorrectly claim "no new migrations"

### ISSUE THREAD

**Issue by timgraham** [divio/django-cms#4700]
http://docs.django-cms.org/en/develop/upgrade/3.2.html says "There are no new migrations in this release" however `0013_urlconfrevision.py` seems to be new (added in 15af0532a9ececbbb5d29b07c954367d23633fca but seems never to be backported to 3.1.3).

**Comment by FinalAngel** [comment]
thank you very much to hint this out @timgraham 

@evildmp can you or @mkoistinen add it to the documentation?

**Comment by evildmp** [comment]
@FinalAngel  will do.

@timgraham thanks.
