### ISSUE TITLE
intermittent edit break for specific users

### ISSUE THREAD

**Issue by bethlakshmi** [divio/django-cms#4713]
Django CMS = 3.1.1, 3.1.2, 3.1.3
Django = 1.6.5, 1.6.11

I could use any insights for debugging that anyone can give.

The problem is:
- a user with proper access rights, who previously successfully edited a page, returns to a page, and attempts to edit it.
- he logs in
- he selects the page - in no-edit view, it loads fine
- he goes to edit view - there is absolutely no page content - static content is there, but all content relevant to that particular page is missing.

Reverting versions does no good - any version is blank.

A user who is not stuck in this state can view and edit the page just fine.

When the problem occurs, it is stuck there for many repetitions. 

Things that don't fix the problem:
- server restarts
- dumping and reloading the database
- logging out logging in
- upgrading django cms across the 3.1.X space
- removing reversion
- flushing the mysql cache

We have the same basic installation in vagrant dev boxes, a test server emulating all settings of the live (but with older data), and the live server - all three installations have seen this problem across 3 different variants of our other code bases.

Our data dumps from a MUCH smaller database taken from 9/13 do not have this problem

We haven't been able to find a trigger or a root cause. 

The problem IS coming in intermittently, but over longish time spans.  For example:
- 2 weeks ago, all privileged users could edit the page
- 4 days ago - several users experienced the problem.  It was repeatable on more than 1/2 the pages of the site, but 2 pages worked fine for those users.  Problem was repeatable for hours.
- today - in the morning the problem persisted in the 4 day ago state.
- 6 hours later - the problem is gone on the live site, but persists elsewhere.

I feel like I'm chasing a phantom here.  Any help would be appreciated.  I'm glad to give data dumps or anything else requested to see what can be done or if there's a best way to turn on debug logging to trace this.

**Comment by mkoistinen** [comment]
Any chance you can try this is 3.1.4 and/or 3.2.0?

**Comment by czpython** [comment]
@bethlakshmi Hi, did you have a chance to try upgrade to a more recent cms version?
