### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addPluginHelpTitle' of undefined

### ISSUE THREAD

**Issue by itbabu** [divio/django-cms#4714]
[django cms 3.2.0.rc8]
* Create a new page
* Select structure
* Click the plus button to add a new plugin to first placeholder

Nothing happens

I've this error on the first placeholder only few times, so it can be difficult to reproduce.

These are the JS lines involved

```Javascript
var d = s.siblings(".cms-plugin-picker");
n._setupQuickSearch(d),
s.on(this.touchStart, function() {
    t = !0
}
).on(this.pointerUp, function(e) {
    e.preventDefault(),
    e.stopPropagation(),
    CMS.Plugin._hideSettingsMenu();
    var i = d.clone(!0, !0).data("parentId", n._getId(s.closest(".cms-draggable")));
    o.open({
        title: n.ui.container.data("settings").addPluginHelpTitle,
        html: i,
        width: 530,
        height: 400
    })
}
),
```
I placed a breakpoint on the line before the error and I 've:
```
> n.ui.container
>[]
```

**Comment by FinalAngel** [comment]
thank you @itbabu for the report. @vxsx can you have a look at it?

**Comment by evildmp** [comment]
@itbabu, @vxsx  I can't reproduce in rc12.

**Comment by vxsx** [comment]
I cannot really reproduce it. Might it be that you had cached files from some of the previous release candidates?

**Comment by itbabu** [comment]
Hi,
I'll update to rc12 this weekend and I'll try again.

**Comment by itbabu** [comment]
I can't reproduce it again with rc12 and a new enviroment.
I'm closing this ticket.
Thanks to everyone.

**Comment by FinalAngel** [comment]
thank you too @itbabu :)

**Comment by altryne** [comment]
I think I found a way to reproduce.

If you place the placeholder inside something like style= 

For example:
`<div style="background-image= url({% placeholder 'abc' %})"></div>`

Then clicking the + on placeholder abc will throw that exact error

**Comment by vxsx** [comment]
@altryne that's an interesting use case
should be fixed by https://github.com/divio/django-cms/pull/4810

**Comment by altryne** [comment]
@vxsx I tried to make a placeholder receive a file and inject it as background image in css. That however didn't work, as the output of the placeholder was like this : 
```
<div style="background-image=url(<div class="cms-plugin cms-plugin-67" style="display: inline;">https://fundbox-alex-testing-local.s3.amazonaws.com/media/filer_public/b1/18/b118e17b-fc54-42ef-8da6-c1db1612f969/photo-110397823.jpg</div>)"></div>
```
