### ISSUE TITLE
environment can only contain strings

### ISSUE THREAD

**Issue by TheDeadOne** [divio/django-cms#4755]
C:\Temp\mysite>virtualenv env
New python executable in env\Scripts\python2.7.exe
Also creating executable in env\Scripts\python.exe
Installing setuptools, pip, wheel...done.

C:\Temp\mysite>env\Scripts\activate
(env) C:\Temp\mysite>pip install djangocms-installer
Collecting djangocms-installer
...

(env) C:\Temp\mysite>djangocms -p . -s mysite
Database configuration (in URL format) [default sqlite://localhost/project.db]:
django CMS version (choices: 2.4, 3.0, 3.1, stable, develop) [default stable]:
Django version (choices: 1.4, 1.5, 1.6, 1.7, 1.8, stable) [default stable]:
Activate Django I18N / L10N setting (choices: yes, no) [default yes]:
Install and configure reversion support (choices: yes, no) [default yes]:
Languages to enable. Option can be provided multiple times, or as a comma separa
ted list. Only language codes supported by Django can be used here: ru-ru
Optional default time zone [default Asia/Irkutsk]:
Activate Django timezone support (choices: yes, no) [default yes]:
Activate CMS permission management (choices: yes, no) [default yes]:
Use Twitter Bootstrap Theme (choices: yes, no) [default no]:
Use custom template set [default no]:
Load a starting page with examples after installation (english language only). C
hoose "no" if you use a custom template set. (choices: yes, no) [default no]:
Creating the project
Please wait while I install dependencies
...
Dependencies installed
Creating the projectFailure occurred. Do you want to cleanup by removing C:\Temp
\mysite? [Y/N] N
Traceback (most recent call last):
  File "C:\Python\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Temp\mysite\env\Scripts\djangocms.exe\__main__.py", line 9, in <modul
e>
  File "c:\temp\mysite\env\lib\site-packages\djangocms_installer\main.py", line
41, in execute
    django.setup_database(config_data)
  File "c:\temp\mysite\env\lib\site-packages\djangocms_installer\django\__init__
.py", line 404, in setup_database
    env=env
  File "C:\Python\Lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python\Lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python\Lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python\Lib\subprocess.py", line 958, in _execute_child
    startupinfo)
TypeError: environment can only contain strings

(env) C:\Temp\mysite>python
ActivePython 2.7.8.10 (ActiveState Software Inc.) based on
Python 2.7.8 (default, Jul  2 2014, 19:50:44) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ
{'TMP': 'C:\\Users\\THEDEA~1\\AppData\\Local\\Temp', 'COMPUTERNAME': 'KONRAD', '
USERDOMAIN': 'Konrad', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell
\\v1.0\\Modules\\', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PR
OCESSOR_IDENTIFIER': 'x86 Family 6 Model 15 Stepping 2, GenuineIntel', 'PROGRAMF
ILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '0f02', 'SYSTEMROOT': 'C:\\Win
dows', 'PATH': 'C:\\Python\\;C:\\Python\\Scripts;C:\\ProgramData\\Oracle\\Java\\
javapath;C:\\Program Files\\Common Files\\Microsoft Shared\\Windows Live;C:\\Pro
gram Files\\NVIDIA Corporation\\PhysX\\Common;C:\\Windows\\system32;C:\\Windows;
C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\
\Program Files\\Maven\\bin;C:\\Program Files\\Java\\jdk1.8.0_51\\bin;C:\\Windows
\\Microsoft.NET\\Framework\\v4.0.30319;C:\\Program Files\\Mercurial\\;C:\\Progra
m Files\\Windows Live\\Shared;C:\\Scala\\bin;C:\\Scala\\sbt\\bin;C:\\Program Fil
es\\Skype\\Phone\\;C:\\Users\\TheDeadOne\\AppData\\Roaming\\Python\\Scripts;C:\\
Program Files\\OpenVPN\\bin;C:\\Google\\appengine\\python\\', 'WINDOWS_TRACING_F
LAGS': '3', 'TEMP': 'C:\\Users\\THEDEA~1\\AppData\\Local\\Temp', 'PROCESSOR_ARCH
ITECTURE': 'x86', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'LOCALAPPDATA': 'C:\\Use
rs\\TheDeadOne\\AppData\\Local', 'HOMEPATH': '\\Users\\TheDeadOne', 'JAVA_HOME':
 'C:\\Program Files\\Java\\jdk1.8.0_51', 'USERNAME': 'TheDeadOne', 'HGENCODING':
 '866', 'LOGONSERVER': '\\\\KONRAD', 'PROMPT': '$P$G', 'SBT_HOME': 'C:\\Scala\\s
bt\\', 'PROGRAMDATA': 'C:\\ProgramData', 'SESSIONNAME': 'Console', 'PATHEXT': '.
COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.py;.pyw', 'FP_NO_HOST_CHEC
K': 'NO', 'WINDIR': 'C:\\Windows', 'WINDOWS_TRACING_LOGFILE': 'C:\\BVTBin\\Tests
\\installpackage\\csilogfile.log', 'HOMEDRIVE': 'C:', 'SYSTEMDRIVE': 'C:', 'COMS
PEC': 'C:\\Windows\\system32\\cmd.exe', 'NUMBER_OF_PROCESSORS': '2', 'APPDATA':
'C:\\Users\\TheDeadOne\\AppData\\Roaming', 'PROCESSOR_LEVEL': '6', 'HGEDITOR': '
"C:\\Program Files\\Far Manager\\Far.exe" -e', 'OS': 'Windows_NT', 'PUBLIC': 'C:
\\Users\\Public', 'USERPROFILE': 'C:\\Users\\TheDeadOne'}

**Comment by chengaomin** [comment]
I have the same error

**Comment by FinalAngel** [comment]
Thank you for your report @TheDeadOne. @yakky is this something related to the djangocms-installer?

**Comment by yakky** [comment]
Yes, it's a  djangocms-installer.
I need to get my hands on a windows machine to understand what's going on

**Comment by mkoistinen** [comment]
Closing, please see: https://github.com/nephila/djangocms-installer/issues/217

**Comment by yakky** [comment]
@chengaomin are you using ActivePython 2.7.8.10 too? Or official python interpreter ?

**Comment by yakky** [comment]
@chengaomin @TheDeadOne could you test linked PR if it fixes the issue for you?

**Comment by chengaomin** [comment]
@yakky yes, using ActivePython 2.7.10.12  （32 bit）

**Comment by daviesattisu** [comment]
@yakky i'm having the same issue, though am using the official python interpreter (2.7)

**Comment by yakky** [comment]
@daviesattisu have you tried the linked PR?
