### ISSUE TITLE
Cannot publish a page in pagetree, but publish available on the page

### ISSUE THREAD

**Issue by Grimaldum** [divio/django-cms#4756]
Hello there !

I have a strange bug with django-cms. Here it is:
I have a page with 2 static placeholders. When I edit one of them, I can publish my page directly via the blue button, on the top right side, but the page cannot be published in the pagetree (the blue editing circle), in the django-cms edit page. Is this intended ?

**Comment by yakky** [comment]
@Grimaldum while maybe a bit misleading, yes, it's intended: when changing a static placeholder you're not publishing the "page" but the static placeholder itself, which is not available in the page tree, but only in the frontend

**Comment by Grimaldum** [comment]
Ok, thanks for the answer :)

**Comment by mkoistinen** [comment]
Closing as resolved.
