### ISSUE TITLE
Keyerror for language when trying to click on an item in view history

### ISSUE THREAD

**Issue by kopite** [divio/django-cms#4766]
In the history > view history Tab when you click on any item the following key error is displayed:

KeyError at /admin/cms/page/74/history/3051/

'language'

template causing the error : lib/python2.7/site-packages/cms/templates/admin/cms/page/change_form.html,

The code which seems to be causing the issue is 

/var/www/django/website-wepower/lib/python2.7/site-packages/cms/templatetags/cms_admin.py in get_context

     220                   language = context['language']

**Comment by quizy101** [comment]
I can confirm, I am having the same issue with KeyError viewing page history.

**Comment by yakky** [comment]
Install shang of reversion==1.8.7
We discovered an incompatibility with reversion 1.9.
It will be fixed in 3.1/3.2 branches, in the meantime use reversion 1.8

**Comment by quizy101** [comment]
Thank you, that fixed the problem for me.

**Comment by FinalAngel** [comment]
thanks @quizy101 we track the status in https://github.com/divio/django-cms/issues/4784

**Comment by kopite** [comment]
Issue has been resolved by downgrading thanks @yakky !
