### ISSUE TITLE
Docs » Tutorials » Integrating a third-party application - Improvement Part 1

### ISSUE THREAD

**Issue by bartmika** [divio/django-cms#4769]
**Description**
I am using _OSX El Captan_ operating system and when I entered:

```
  pip install aldryn-newsblog
```

I get the following error:
![screen shot 2015-11-25 at 1 56 52 pm](https://cloud.githubusercontent.com/assets/5767602/11406936/f435de4a-937d-11e5-841a-eaaf1df3b140.png)

**How-to-Fix**
In the documents webpage, may you please add a pre-requsite text or something explaining that if you are using **OSX** that you need to run the following commands before running the pip install:

```
  brew install libxml2
  xcode-select --install
```

Once the user enteres those commands and runs the pip install, everything installs smoothly. Of course you don't have to make this improvement, but it's best we provide the users a stressless experience when following the documentation.

Thanks!

**Comment by evildmp** [comment]
On reconsideration, I am not convinced it's appropriate to mention libraries such as libxml2, or give directions on installing them. There are too many such non-Python libraries, and too many ways to install them, and we can't cover them all.

If they are not installed, the user will get be informed by their system, and it will be up to them to deal with.

@yakky @FinalAngel your thoughts?

**Comment by FinalAngel** [comment]
I agree, listing specific installation steps (in this example osx) opens the question to add the remaining instructions for windows or linux as well. The prerequisite is to have a proper setup on your computer before you begin.

For the case at divio we use https://github.com/divio/osx-bootstrap for the automated setup on osx (which sets up xcode or libxml2) but that might differ from company to company.

so @evildmp :-1: except for adding a note on "please make sure your system is properly configured" if not already so.
