### ISSUE TITLE
"Add Picture" Plugin missing "class" / "width" / "height"

### ISSUE THREAD

**Issue by bartmika** [divio/django-cms#4774]
Hello,

I am a novice so forgive me if I make a mistake. But I am lookin at adding a "Picture" placeholder.

![screen shot 2015-11-26 at 10 19 03 am](https://cloud.githubusercontent.com/assets/5767602/11426075/740cef92-9427-11e5-9081-6908bd5c1412.png)

My problem is the picture image needs to look like this:
  ```
  <img src="img/ps.png" alt="#" class="img-responsive center-block" width="200" height="200">
  ```

So I am wondering how can I input the **class** / **width** / **height** html attributes? Maybe adding a **id** and **onclick** in the futue might help too. If the picture plugin doesn't support this, I think I'd like to open up a issue requesting we can add more html attributes. If it's a mistake on my part, my appoligies in advance!

**Comment by FinalAngel** [comment]
which image plugin are you using @bartmika ? You might want to add this issue to the related plugin (as core doesn't ship with plugins). We recommend using https://github.com/aldryn/aldryn-bootstrap3 or https://github.com/stefanfoulis/cmsplugin-filer

**Comment by bartmika** [comment]
Hi @FinalAngel, I am using the generic picture that came with my djang-cms. 

![screen shot 2015-11-26 at 10 50 28 am](https://cloud.githubusercontent.com/assets/5767602/11426682/b6a2d66a-942b-11e5-8202-d5a938682839.png)

**Comment by FinalAngel** [comment]
using installation instructions / djangocms-installer @bartmika is there an "advanced" section?

**Comment by bartmika** [comment]
I do not recall, no.

**Comment by bartmika** [comment]
Hi @FinalAngel, this is my screen, I don't see an advanced section.
![screen shot 2015-11-26 at 3 55 45 pm](https://cloud.githubusercontent.com/assets/5767602/11430550/5029b1da-9456-11e5-82b9-d732eef7f7df.png)

**Comment by bartmika** [comment]
Update: I deleted my old code, I installed from fresh and now I see the Picture plugin is no longer being used but the "Image" plugin. This is good as it looks like it has a lot of options I need.

![screen shot 2015-11-26 at 4 11 02 pm](https://cloud.githubusercontent.com/assets/5767602/11430704/99db0566-9458-11e5-9568-fd2bf64bc57b.png)

Question, where do I modify the image **id** and **class**? 
![screen shot 2015-11-26 at 4 13 55 pm](https://cloud.githubusercontent.com/assets/5767602/11430713/caa0c136-9458-11e5-8ff6-4727ec6ad8a1.png)

**Comment by FinalAngel** [comment]
@bartmika in your screenshot you can set "width" and "height" right there :)

**Comment by FinalAngel** [comment]
Added issue to: https://github.com/stefanfoulis/cmsplugin-filer/issues/205
