### ISSUE TITLE
"Style" Plugin needs more HTML attribute options

### ISSUE THREAD

**Issue by bartmika** [divio/django-cms#4775]
I am looking to add a "Style" plugin so I can write the following code:
  ```
  <div class="container-fluid">
  ```

But when I look in the **Advanced Settings** I don't see any ways to add the particular HTML attribute.
![screen shot 2015-11-26 at 10 32 58 am](https://cloud.githubusercontent.com/assets/5767602/11426327/33a20f80-9429-11e5-9530-08d206ef27fd.png)

I would like to open up a ticket to allowm more HTML attribute options to be available for the **Style Plugin**, more specifically:
* id
* class
* style
* onclick

**Comment by FinalAngel** [comment]
thank you for the report @bartmika can you open this issue on: https://github.com/divio/djangocms-style/issues/new ?
