### ISSUE TITLE
Install Django CMS to existing project needs update

### ISSUE THREAD

**Issue by grwhumphries** [divio/django-cms#4776]
Currently the instructions to install Django CMS to an existing project does not work for django 1.8 - imagine these instructions need updating. (requirements don't include django 1.7 or .8)

**Comment by FinalAngel** [comment]
@evildmp is this the case?

**Comment by grwhumphries** [comment]
Just as an example - in the instructions, TEMPLATE_CONTEXT_PROCESSORS = []  is used, however, in Django 1.8+, this is deprecated.  All TEMPLATE options fall into the TEMPLATE tag now.   I tried following instructions to update my project with django CMS (I'm using django 1.8.6), but instructed me to update the TEMPLATES tag

**Comment by evildmp** [comment]
@grwhumphries thanks for the report, also affects template-related steps in http://docs.django-cms.org/en/latest/introduction/install.html.
