### ISSUE TITLE
Fix compatibility with reversion 1.9

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#4784]
This is an issue in 3.1 and 3.2

Edit: reversion 1.10 has been released with modified API. I suggest to support only 1.8.5 (for Django 1.6) and 1.10 (for Django 1.7+ as stated in the documentation)

**Comment by ojii** [comment]
The docs should probably point out that 1.9/1.10 of reversion aren't supported: http://docs.django-cms.org/en/develop/how_to/install.html#revision-management

**Comment by Chronial** [comment]
Which versions of reversion are supported? Do I need to downgrade to reversion 1.8?

**Comment by yakky** [comment]
@Chronial yes. currently up to 1.8.7

**Comment by Chronial** [comment]
thx, and yes that should definitely be somewhere in the docs ^^.

**Comment by FinalAngel** [comment]
@evildmp would you be able to add this note?

**Comment by jedie** [comment]
setup.py INSTALL_REQUIREMENTS should be changed, isn't it?

**Comment by yakky** [comment]
@jedie djang CMS does not depend on reversion in setup.py because it's an optional dependency, so there is no way to fix this at installation phase, except pinning django-reversion==1.8.7 in your project requirements

**Comment by fivethreeo** [comment]
What about adding features to setup.py so reversion is pinned there, look at the setup.py of celery.

**Comment by yakky** [comment]
It's an option for 3.1 / 3.2 (like we did or south).
 It was not previously possible because of the different versions of reversion required according to the Django version
In 3.2 it will be fixed shortly by supporting reversion 1.9+ anyway

**Comment by yakky** [comment]
Merged in #4883
