### ISSUE TITLE
Add strict link checking in documentation

### ISSUE THREAD

**Issue by timgraham** [divio/django-cms#4785]
You can use the `-n` option (like Django's docs do) to show broken Sphinx links when building the docs. There are about 160 links that need to be fixed (or removed if the code won't be documented) as part of this.
```diff
diff --git a/docs/Makefile b/docs/Makefile
index 91cfb3f..07c5d6f 100644
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -9,7 +9,7 @@ PAPER         =
 # Internal variables.
 PAPEROPT_a4     = -D latex_paper_size=a4
 PAPEROPT_letter = -D latex_paper_size=letter
-ALLSPHINXOPTS   = -d build/doctrees $(PAPEROPT_$(PAPER)) $(SPHINXOPTS) .
+ALLSPHINXOPTS   = -n -d build/doctrees $(PAPEROPT_$(PAPER)) $(SPHINXOPTS) .
 
 .PHONY: help clean html dirhtml pickle json htmlhelp qthelp latex changes linkc
 
```

**Comment by yakky** [comment]
Wow, nice improvement! @evildmp do you think fixing the broken links it's doable by 3.3?

**Comment by FinalAngel** [comment]
@yakky we should fix it by 3.3 if we plan cleanups across the code

**Comment by evildmp** [comment]
@FinalAngel I think we should fix this asap.

**Comment by FinalAngel** [comment]
@evildmp I'll open a PR tomorrow morning!

**Comment by FinalAngel** [comment]
https://github.com/divio/django-cms/pull/4804#event-480243635

**Comment by timgraham** [comment]
What I envisioned was also fixing all the warnings and then failing the docs build if any warnings are introduced (this is what Django does). Should I open a separate issue?

**Comment by FinalAngel** [comment]
@timgraham I would say so @evildmp how do you want to handle this?
