### ISSUE TITLE
django-cms still raising RemovedInDjango19Warnings

### ISSUE THREAD

**Issue by jribbens** [divio/django-cms#4788]
```
$ pip install djangocms-installer
$ djangocms -sqp . my_demo
$ python manage.py startapp testapp
test/env/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  return f(*args, **kwds)

test/env/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.
  return f(*args, **kwds)
```

They are actually coming from sekizai:

```
$ python -Werror::::321 manage.py startapp testapp2
...
  File "test/env/lib/python3.4/site-packages/cms/templatetags/cms_tags.py", line 36, in <module>
    from sekizai.templatetags.sekizai_tags import SekizaiParser, RenderBlock
  File "test/env/lib/python3.4/site-packages/sekizai/templatetags/sekizai_tags.py", line 6, in <module>
    from django.utils.importlib import import_module
  File "test/env/lib/python3.4/site-packages/django/utils/importlib.py", line 9, in <module>
    RemovedInDjango19Warning, stacklevel=2)
django.utils.deprecation.RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
```

I know they're only warnings but it is very off-putting that django-cms, out of the box and completely unmodified, spams warnings all over the place constantly.

I am using Python 3.4.3, Django 1.8.7 and Django-CMS 3.2.0.

**Comment by yakky** [comment]
I think you should open an issue in the sekizai project to better track the issue

**Comment by jribbens** [comment]
sekizai already has issue ojii/django-sekizai#53 but they closed it as it was fixed in ojii/django-sekizai@bb3992e06339006bea67ebb37daf5992f11a0600. This doesn't actually help very much as that was back in July and there have been no new releases of sekizai since then.

**Comment by yakky** [comment]
Still, it's a sekizai issue, nothing the CMS can do about that

**Comment by jribbens** [comment]
It seems at least possible that a request from the django-cms developers to the sekizai developer(s) might prod them into making a new release... I made a ticket here because it is an issue being experienced by django-cms users - it's not like the problem is in an unrelated optional third-party library, it's a core dependency of django-cms. Users most likely won't even realise that sekizai exists, let alone that the problem is not coming from django-cms directly.

**Comment by FinalAngel** [comment]
@jribbens thanks for the report, it's absolutely correct that we have to work together and fix issues across multiple dependencies. @ojii might be busy but we pinged him and check if we might get release rights on it.

We keep this open and aim for a fix in the next release.

**Comment by evildmp** [comment]
@ojii is very amenable and I am sure can oblige!

**Comment by ojii** [comment]
please upgrade to sekizai 0.9.0 or higher.

**Comment by yakky** [comment]
@ojii great, thanks!
