### ISSUE TITLE
Migrating a field to PlaceholderField fails when using Postgres

### ISSUE THREAD

**Issue by jribbens** [divio/django-cms#4789]
```
$ pip install djangocms-installer psycopg2
$ djangocms -sqp . -d postgresql://test:test@localhost/test my_demo
$ python manage.py startapp testapp
```
Add `testapp` as penultimate entry in `my_demo/settings.py:INSTALLED_APPS`.
Edit `testapp/models.py`:
```python
from django.db import models
class TestModel(models.Model):
    description = models.TextField("Description")
```
```
$ python manage.py makemigrations testapp
$ python manage.py migrate
```
Edit `testapp/models.py`:
```python
from django.db import models
from cms.models.fields import PlaceholderField
class TestModel(models.Model):
    description = PlaceholderField("Description")
```
```
$ python manage.py makemigrations testapp
$ python manage.py migrate
...
Running migrations:
  Rendering model states... DONE
  Applying testapp.0002_auto_20151129_1448...Traceback (most recent call last):
  File "test/env/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column "description_id" cannot be cast automatically to type integer
HINT:  You might need to specify "USING description_id::integer".
```

This only happens with Postgres (or rather, it doesn't happen with sqlite, i.e. if you remove the `-d` from the `djangocms` invocation above). It only happens if the column is being changed in one migration, if it's split into two migrations the first of which deletes the column and the second of which creates it, there is no issue.

I was originally actually getting `ValueError: Related model 'cms.Placeholder' cannot be resolved`, but I cannot reproduce that so easily since I already fixed it in my project - see mailing list thread https://groups.google.com/forum/#!topic/django-cms/tIT3g0gCpwc.

**Comment by yakky** [comment]
Postgres refuse to convert any text field to integer without a casting function: ``PlaceholderField`` is a ``ForeignKey`` so its type it's an integer and you can either write a `'RunSql`` function or split the migrations in two steps.

**Comment by jribbens** [comment]
Shouldn't 'makemigrations' be detecting this situation rather than silently producing a broken migration?

**Comment by yakky** [comment]
I don't know the internals of migrations module to provide an answer

**Comment by jribbens** [comment]
Possibly if you hadn't've closed the ticket and labelled it a non-issue, someone who does know whether it actually is an issue might answer? ;-)

**Comment by yakky** [comment]
Not being a django CMS issue I don't see any reason to keep this open. 
The best option is to open an issue in Django and eventually link this here

**Comment by jribbens** [comment]
OK I have created a django ticket: https://code.djangoproject.com/ticket/25832
