### ISSUE TITLE
 Pages global permissions admin view does not honour the CMS_RAW_ID_USERS setting

### ISSUE THREAD

**Issue by marts** [divio/django-cms#4807]
On DjangoCMS 3.1.3:

Adding/editing a Pages global permissions, all users are shown in the dropdown even when ```CMS_RAW_ID_USERS = True```

Maybe ```GlobalPagePermissionAdmin``` method needs a ```raw_id_fields``` method much like ```PagePermissionInlineAdmin```

**Comment by marts** [comment]
I don't if this should be raised as part of this issue, but ```GlobalPagePermissionAdmin``` also has a ```list_filter``` that includes ```user```.

```list_filter = ['user', 'group', 'can_change', 'can_delete', 'can_publish', 'can_change_permissions']``` 

The list of users in this filter could also get very long.

**Comment by yakky** [comment]
Thanks for reporting

**Comment by marts** [comment]
No problem :)

**Comment by yakky** [comment]
Solved in #4951
