### ISSUE TITLE
Browser caches old cms.base.css when upgrading to 3.2

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#4808]
Recently upgraded a site to 3.2 but staff were complaining that the admin toolbar is broken. This was due to their browser using the old `cms.bas.css` from cache since the url didn't change. Don't have time at the moment to look into this myself but is it possible to have the new build tools generate this file with the version in the file name e.g. `cms.base.3.2.css` so it forces the browser to download the latest?

**Comment by FinalAngel** [comment]
@jsma thanks for the report, we are thinking of something like ``cms.base.css?randomtoken``. Just changing the filename causes reference problem inside different places.

**Comment by vxsx** [comment]
well for css we actually could use different file names but since we cannot do that for js files (because they are used in external addons) i think we'll do that consistently and use a query param (even though it's not the best solution)

**Comment by mkoistinen** [comment]
Please rename the file, adding a param is not the way to go here.

**Comment by FinalAngel** [comment]
@mkoistinen we can't rename the file as it is referenced across multiple places.

**Comment by mkoistinen** [comment]
Fixed by #4874.
