### ISSUE TITLE
page_url template tag fails silently when put in a custom inclusion tag

### ISSUE THREAD

**Issue by lukasz-virtualo** [divio/django-cms#4830]
##### Reproduction
I have defined an inclusion tag and registered it like so (example):
```python
from django.template import Library
@register.inclusion_tag('/path/to/template.html', takes_context=True)
def my_tag(context):
    return {'foo': 'bar'}
```
The file `/path/to/template.html` contains:
```html
{% load cms_tags %}
<span>{% page_url "PAGENAME" %}</span>
```
I use both the custom tag and ordinary reference to `page_url` in the main cms template:
```html
{% load my_tags cms_tags %}

<h1>{% page_url "PAGENAME" %}</h1>
{% my_tag %}
```
Expected output:
```html
<h1>/url/to/page<h1>
<span>/url/to/page</span>
```
Actual output:
```html
<h1>/url/to/page<h1>
<span></span>
```
Perhaps I am missing something in the tag registration...

### Configuration
Virtualenv:
```
cmsplugin-newsplus==0.1.10
decorator==4.0.4
dj-database-url==0.3.0
Django==1.8.4
django-bower==5.0.4
django-classy-tags==0.6.2
django-cms==3.1.3
django-filebrowser-no-grappelli==3.6.1
django-reversion==1.9.3
django-sekizai==0.8.2
Django-Select2==4.3.1
django-templatetag-handlebars==1.3.0
django-treebeard==3.0
djangocms-admin-style==0.2.8
djangocms-column==1.5
djangocms-file==0.1
djangocms-flash==0.2.0
djangocms-googlemap==0.3
djangocms-inherit==0.1
djangocms-installer==0.8.0
djangocms-link==1.7.1
djangocms-picture==0.1
djangocms-style==1.5
djangocms-teaser==0.1
djangocms-text-ckeditor==2.8.0
djangocms-video==0.1
emencia-django-slideshows==0.9.4
html5lib==0.9999999
ipython==4.0.1
ipython-genutils==0.1.0
path.py==8.1.2
pexpect==4.0.1
pickleshare==0.5
Pillow==2.9.0
ptyprocess==0.5
pytz==2015.4
simplegeneric==0.8.1
six==1.9.0
traitlets==4.0.0
tzlocal==1.2
yolk==0.4.3
```

**Comment by lukasz-virtualo** [comment]
##### Possible fix
Problem can be circumvented using:
```html
{% load my_tags cms_tags %}

{% page_url "PAGENAME" as mypagevar %}
<h1>{{ mypagevar }}</h1>
{% my_tag %}
```
in the main template, then patching the my_tag to give access to context:
```python
from django.template import Library
@register.inclusion_tag('/path/to/template.html', takes_context=True)
def my_tag(context):
    return {'context': context, 'foo': 'bar'}
```
and finally in /path/to/template.html:
```html
<span>{{ context.mypagevar }}</span>
```
Then it passes the test.

##### Still a bug?
Perhaps, if you consider the original circumstances.
What if I need to get multiple URLs inside the inclusion template? Rather not a very convenient thing to prepare them all in the main template (or view), not knowing exactly what is required at this point...

**Comment by yakky** [comment]
@lukasz-virtualo there is a error in you templatetag.
It should be :

    @register.inclusion_tag('/path/to/template.html', takes_context=True)
    def my_tag(context):
        context.update({'foo': 'bar'})
        return context

By doing ``return {'foo': 'bar'}`` you are replacing the main context (with the data from ``page_url``) with a custom context containing only ``foo`` (or ``foo`` and ``context``) in the second example

**Comment by lukasz-virtualo** [comment]
Thank you for the explanation. However, I don't see how that affects the main topic, that is being unable to use cms_tags inside an inclusion template. On this grounds, I reopen.

**Comment by lukasz-virtualo** [comment]
Actually the context handling does not affect the submitted bug. Please refer to the example In my first post.

**Comment by yakky** [comment]
The django CMS templatetag needs the full context to be able to return the page URL. If the original context is replaced, the templatetag cannot work. In the first example you are replacing the original context with a custom one, which prevents django CMS templatetag to work

**Comment by lukasz-virtualo** [comment]
Thanks. Silly me.
