### ISSUE TITLE
User lookup not working for view restrictions/page permissions when CMS_RAW_ID_USERS = True

### ISSUE THREAD

**Issue by marts** [divio/django-cms#4842]
Tested on 3.1.4 and 3.2.0

When trying to add a single user based view restriction or page permission when via the lookup button when ```CMS_RAW_ID_USERS = True```, the 'Select user to change' popup is shown. However, if a user is selected you are taken to the edit page of the user, rather than the user pk being inserted in to the user input field.

From djangoCMS tool bar select Page->Permissions...+ Add another view restriction and select a user

**Comment by mkoistinen** [comment]
@marts can you re-try this with 3.1.4, but also make sure that you've downgraded djangocms-admin-style to version 0.2.5 and let us know if that helps?

**Comment by marts** [comment]
Hi @mkoistinen, I tried downgrading djangocms-admin-style from 0.2.8 to 0.2.5 but it does not seem to help. I'm a bit confused about this...I still get the problem on my development code, although I thought the problem was also happening on fresh djangocms builds. However, I now think the browser was probably caching something from the dev build and causing the error on the fresh install. Having tried again a fresh build of 3.1.4 seems to be ok.

The only thing I can think of at the moment is that we have used a heavily customized user model rather than auth user, or that we are doing something else that is messing up the loading of the javascript somehow.

Sorry, probably not much help. This functionality is not critical for our application, but I thought I'd raise it as it may have been a more general issue. Maybe it is more specific to something we are doing.

**Comment by mbambas** [comment]
This happens because the `admin/cms/page/change_form.html` template overrides the whole `content` block of its parent, but it doesn't include the `admin_change_form_document_ready` block, which contains a javascript snippet to initialize related lookup fields.

**Comment by yakky** [comment]
Fixed in 3.1.x branch. Will be forward ported later.
Thanks @marts @mbambas for your work on this
