### ISSUE TITLE
Setup error from setuptools

### ISSUE THREAD

**Issue by onerro** [divio/django-cms#4844]
Command "/var/www/env/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-R52Bj8/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-NqAHLE-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/www/env/include/site/python2.7/Pillow" failed with error code 1 in /tmp/pip-build-R52Bj8/Pillow

How to do?

**Comment by FinalAngel** [comment]
@onerro can you tell us more about what your process was that lead to this error?

**Comment by onerro** [comment]
I did as the following steps:
    $ pip install --upgrade virtualenv
    $ virtualenv env
    $ source env/bin/activate
    (env) $ pip install djangocms-installer
    (env) $ mkdir myproject && cd myproject
    (env) $ djangocms -f -p . my_demo
    (env) $ python manage.py

"(env) $ djangocms -f -p . my_demo", it throw the error.
Others look normal.

**Comment by yakky** [comment]
@onerro could you check if installer's documentation helps? http://djangocms-installer.readthedocs.org/en/latest/libraries.html

**Comment by Chematronix** [comment]
Thanks yakky.  There were some non-Python dependencies missing in my vanilla Ubuntu server (the installer should really mention this somewhere instead of leaving us to crash with the wall).

Solved by doing the suggested `sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev`.

**Comment by yakky** [comment]
@onerro the binary dependencies are documented in both the installer and cms documentation, actually

**Comment by Chematronix** [comment]
There's nothing in the cms docs but a [passing mention of Pillow](http://docs.django-cms.org/en/3.2.3/search.html?q=Pillow&check_keywords=yes&area=default#) in the Installing django CMS by hand howto; never mind the Install Guide, which is arguably the main starting point.  There's [no mention of djangocms-installer](http://docs.django-cms.org/en/3.2.3/search.html?q=djangocms-installer&check_keywords=yes&area=default#) as such either, nor about it having its own docs, which I only found thanks to your link.

And those don't fare much better either, [not mentioning the error anywhere](http://djangocms-installer.readthedocs.org/en/latest/search.html?q=failed&check_keywords=yes&area=default#), and the dependencies [only in the page you linked](http://djangocms-installer.readthedocs.org/en/latest/search.html?q=libtiff5&check_keywords=yes&area=default#).

So, I beg to differ. ;)

**Comment by yakky** [comment]
@Chematronix for installer binary dependencies are documented in quite a few places: https://github.com/nephila/djangocms-installer#preliminary-checks-and-system-libraries, http://djangocms-installer.readthedocs.org/en/latest/faq.html, http://djangocms-installer.readthedocs.org/en/latest/libraries.html,
