### ISSUE TITLE
Confusing redirect-page behavior when logged in with CMS toolbar hidden

### ISSUE THREAD

**Issue by trawick** [divio/django-cms#4850]
Seen with Django CMS 3.1.3:

* Fill in Redirect on Advanced Settings for a page
* Save/publish
* View page with CMS toolbar enabled
* See "This page has no preview!/It is being redirected to: ``<target_URL>``"
* Disable toolbar
* See CMS page template rendered with empty content.

It should either display the "This page has no preview!" message or it should redirect.

**Comment by yakky** [comment]
@trawick what to you mean by "disable toolbar"? Switchting to live mode or selecting "Disable toolbar" item in the toolbar?

**Comment by trawick** [comment]
this: selecting "Disable toolbar" item in the toolbar

**Comment by yakky** [comment]
@trawick confirmed. Thanks for spotting this

**Comment by yakky** [comment]
@trawick please check above PR if fixes the issue for you

**Comment by trawick** [comment]
@yakky works for me; thanks so much!

**Comment by yakky** [comment]
@trawick thanks for your feedback, PR merged. Closing this, it will be included in 3.1.5 (no ETA for release, yet)
