### ISSUE TITLE
Can't install - Why do Django CMS want to include MySQL-python with Python 3.4.3?

### ISSUE THREAD

**Issue by zruu** [divio/django-cms#4860]
Trying to install Django CMS 3.2 with Django 1.9 and Python 3.4.3 and when it's time to install dependencies it gives me an error:

`Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/n9/t1wyb5y171df9032_fykvr8h0000gn/T/pip-build-3fncvfa2/MySQL-python`

Why do Django CMS even want to include the module MySQL-python with Python 3.4.3 as it is not supported? mysqlclient is the recommended one at the moment.

How can I come around this? Currently the installer won't put any files in the folder I specified.

**Comment by yakky** [comment]
Django 1.9 is currently not supported. django CMS does not depend on Mysql and allows to use any mysql driver

**Comment by zruu** [comment]
OK. Thank you for the quick reply. When do you guys think you will ship out a new release that supports 1.9?

**Comment by yakky** [comment]
No official ETA, but the end of the year is a sensible timeframe
