### ISSUE TITLE
Can't see django cms mode switcher after including cms toolbar from a different template

### ISSUE THREAD

**Issue by momomatteo** [divio/django-cms#4863]
I've upgraded my project from djangocms 3.1.3 to djangocms 3.2.0 and now I can't switch mode from content to structure.
The switcher is not visible in every page.
Is there any extra migrations I have to apply switching these versions?

Thank You

**Comment by yakky** [comment]
@momomatteo does this happen for superuser too?

**Comment by momomatteo** [comment]
Yes I'm logged with my superuser account

**Comment by vxsx** [comment]
Hi @momomatteo, thanks for the report. There's a small chance that it might be related to the #4808 Could you please try to [refresh your browser cache](http://www.refreshyourcache.com/en/home/)?

Otherwise it might be something else, but then we would need a bit more info (and maybe a screenshot).

**Comment by momomatteo** [comment]
I've tried to refresh my browser cache but nothing changed.
Here I have my header bar before editing:
![close_bar](https://cloud.githubusercontent.com/assets/6272397/12330701/bb945cf2-bae6-11e5-8599-7e9bb4b5afe1.png)
and then after I click Edit button:
![open_bar](https://cloud.githubusercontent.com/assets/6272397/12330739/e39b0250-bae6-11e5-8934-a7b7ab8b76a1.png)

Content and structure switcher is not visible anymore.
![switcher](https://cloud.githubusercontent.com/assets/6272397/12330883/8abbc5ba-bae7-11e5-9add-0f3807be295d.png)
Is there something I've missed migrating?

Thank you

**Comment by facconi** [comment]
I have the same issue.

Part of my requirements:

    Django==1.8.8
    django-cms==3.2.0
    djangocms-admin-style==1.0.7

**Comment by facconi** [comment]
The code is present in the html, but not shown on the page:

```
<div class="cms-toolbar-right">
<div class="cms-toolbar-item cms-toolbar-item-buttons ">
   <a href="/en/cms_wizard/create/?page=3&amp;edit" class="cms-btn " data-rel="modal" data-on-close="REFRESH_PAGE">Create</a>   
</div>
<div class="cms-toolbar-item cms-toolbar-item-buttons cms-toolbar-item-cms-mode-switcher">
        <a href="?build" class="cms-btn ">Structure</a>
        <a href="?edit" class="cms-btn cms-btn-active ">Content</a>  
</div>
<div class="cms-toolbar-item cms-toolbar-item-buttons cms-toolbar-item-switch-save-edit"><a class="cms-btn cms-btn-switch-save" href="/en/?edit_off"><span>View published</span></a></div>
```

In cms.base.css at row 3:

```display: none;```

**Comment by yakky** [comment]
@momomatteo / @facconi superuser or staff user?

**Comment by vxsx** [comment]
@momomatteo / @facconi are there any errors in browser console?

The switcher is hidden by default and then shown when structureboard javascript is initialized.
Requirements for the switcher to be shown are:

- There is a switcher in the dom
- There are "structureboard" placeholders on the page (rendered as `<div class="cms-dragarea">`
- There are "content" placeholders on the page (rendered as `<div class="cms-placeholder">`

Are all of these criteria valid?

**Comment by facconi** [comment]
superuser (and staff!)

**Comment by momomatteo** [comment]
@vxsx it seems that "structureboards" placeholders aren't on the page.
There are no elements with class "cms-dragarea".
The browser console reports no errors.

**Comment by vxsx** [comment]
@momomatteo then in your case it seems that there is nothing you can really do in the structure mode (as it has no placeholders) - that's why the switcher doesn't show up. 

Is it correct that the page has no placeholders (and no plugins for that matter)?

**Comment by momomatteo** [comment]
This problems happens in all the pages.
For example in homage I have 4 placeholders and the older plugins attached to them are still present.
This is my placeholders configuration in setting:
```python
CMS_PLACEHOLDER_CONF = {
    'standard-placeholder': {
        'plugins': ['FilePlugin', 'FlashPlugin', 'GoogleMapPlugin', 'LinkPlugin', 'PicturePlugin', 'TeaserPlugin',
                    'TextPlugin', 'VideoPlugin', 'CMSTestListPlugin', ],
    },
    'footer_left': {
        'inherit': 'standard-placeholder',
    },
    'footer_right': {
        'inherit': 'standard-placeholder',
    },
    'placeholder_rigth_description': {
        'inherit': 'standard-placeholder',
    },
    'placeholder_bottom_description': {
        'inherit': 'standard-placeholder',
    },
    'placeholder_description': {
        'inherit': 'standard-placeholder',
    },
    'diagnostictest_content': {
        'inherit': 'standard-placeholder',
    },
    'image-header-placeholder': {
        'limits': {
            'global': 1,
        },
        'plugins': ['PicturePlugin', ],
    },
    'home_image_header': {
        'inherit': 'image-header-placeholder',
    },
    'normal_image_header': {
        'inherit': 'image-header-placeholder',
    },
    'content-placeholder': {
        'plugins': ['LinkPlugin', 'PicturePlugin', 'TextPlugin', 'VideoPlugin', ],
    },
    'mission_text': {
        'inherit': 'content-placeholder',
    },
    'link_text': {
        'inherit': 'content-placeholder',
    },
    'home_link': {
        'plugins': ['TeaserPlugin', ],
    },
    'placeholder_left_image': {
        'limits': {
            'global': 1,
        },
        'plugins': ['PicturePlugin', 'VideoPlugin', 'GoogleMapPlugin', ],
    },
}
```

**Comment by momomatteo** [comment]
Finally I've found the problem.
When I've started this project in my base I added cms toolbar in this way:
```html
{% cms_toolbar %}
```
Later I've decided to include cms_toolbar from an external file because I wanted to display cms_toolbar only in some pages of my website and hide it in some others pages for staff users only and so without cms placeholders.
At this point my base was:
```html
{% block cmstoolbarbase %}{% include 'cms_toolbar.html' %}{% endblock %}
```
And the external file:
```html
{% load cms_tags %}

{% cms_toolbar %}
```
I know this is not standard way to add the cms toolbar but I couldn't find how to do this in the proper way (I think I've found this solution in a forum but I don't remember where). 
If I revert the changes in base everything works correct again.

Is there a way to hide cms toolbar in some pages without this sort of side effects?

Thank you

**Comment by vxsx** [comment]
@momomatteo sorry for the extremely late reply, i somehow missed the notification
`{% cms_toolbar %}` cannot really be used inside blocks, but maybe [this solution](https://github.com/divio/django-cms/issues/3146#issuecomment-135046036) would help you if this is still relevant.

**Comment by pbalazek** [comment]
In my case the problem was with the session. I was using a custom middleware to create a session if there is a visitor. But soon as the visitor logged in as the admin, there were conflicts and both buttons disappeared. Removing the custom middleware solved the problem.
