### ISSUE TITLE
djangocms 3.2 | foundation 5 | firefox --> MutationEvents warning

### ISSUE THREAD

**Issue by creimers** [divio/django-cms#4873]
django==1.8.4
django-cms==3.2
foundation=5.5.3

I'm observing a peculiar behavior after updating a project from djangocms 3.1 to 3.2.

When using ...com/?edit to login, after the POST Firefox either 

* crashes 
* alerts that jquery is not responding
* takes forever to load the side.

In the latter case, the console gives the following warning:
`Use of Mutation Events is deprecated. Use MutationObserver instead.`

If I use ...com/admin/ to login and then go to the site, everything works as expected and there are no warnings in the browser console.

This is happening in Firefox and IE 11. Chrome and Safari work just fine.

Any thoughts on how to fix this?

**Comment by vxsx** [comment]
I can reproduce the warning on http://foundation.zurb.com/sites/docs/v/5.5.3/components/tooltips.html
But I cannot reproduce loading problems/crashing on a clean CMS installation with foundation being initialised.

The problem you're experiencing probably comes from https://github.com/zurb/foundation-sites/blob/V5/js/foundation/foundation.tooltip.js#L145
(ref https://github.com/zurb/foundation-sites/pull/4973)

It might be that #4870 will solve your problem (should be released this week)
Could you please try installing cms from `pip install https://github.com/divio/django-cms/archive/release/3.2.x.zip` to see if the problem goes away?

Or maybe you have any other details?

**Comment by creimers** [comment]
@vxsx I have made the exact same reproduction experience you're describing. 

The project makes heavy use of many foundation components. I am under the impression that on large pages, i.e. lots of foundation, the browser struggles more than an pages with only a few foundation elements.

Will try #4870 tomorrow and will let you know.

**Comment by creimers** [comment]
@vxsx #4870 does the trick for me. Thanks.
