### ISSUE TITLE
Create new project via djangocms turns out an error "can not find django-admin.py"

### ISSUE THREAD

**Issue by giraffe0813** [divio/django-cms#4882]
I want to create a new django via command "djangocms -f -p . mysite" according to the tutorial (http://docs.django-cms.org/en/develop/introduction/install.html) and it occures an error.And when I create a new project via "django-admin.py startproject mysite" , it works well.Could you please help me ?
error message:
```
Dependencies installed
Creating the project
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/django-admin.py': [Errno 2] No such file or directory
Failure occurred. Do you want to cleanup by removing /Users/eleme/Documents/ymy/workspace/env/tutorial-project? [Y/N] 
```
Following is my step:
1.virtaulenv --no-site-packages env
2.source env/bin/activate
3.pip install django
4.pip install djangocms-installer
5.mkdir tutorial-project
6.cd tutorial-project
7.djangocms -f -p . mysite
8.error 

Thanks a lot

**Comment by Dquinonez** [comment]
Hi

I'm having the same problem in Ubuntu.

/usr/bin/python2.7: can't open file '/usr/bin/django-admin.py': [Errno 2] No such file or directory

I think the problem is because my django-admin.py is under /usr/local/bin and the installation is trying to locate the file under /usr/bin/

**Comment by yakky** [comment]
@Dquinonez djangocms-installer is only supported in a virtualenv environment

**Comment by Dquinonez** [comment]
I have the virtualenv installed. I got the django web framework up and running with the django-admin without problem.

**Comment by yakky** [comment]
/usr/local/bin/django-admin.py does not look like a virtualenv location for the django-admin script. djangocms-installer anyway, requires that python interpreter and django-admin.py are in the same directory https://github.com/nephila/djangocms-installer#warning

**Comment by Dquinonez** [comment]
I see. I installed the djangocms-installer without issues, the problem is when I'm creating a project

djangocms -f -p . mysite

Here is the link of the tutorial that I'm following.

http://docs.django-cms.org/en/develop/introduction/install.html

by the way, thanks for the info.

**Comment by yakky** [comment]
djangocms-installer calls django-admin.py after the "djangocms -f -p . mysite" command and given that it's not in the same directory as python interpreter it fails.
Why interpreter and django-admin are in the global path instead of the virtualenv one?

**Comment by rubengrill** [comment]
Same for me.
```
virtualenv env
source env/bin/activate
pip install djangocms-installer
djangocms -p . -s -f --verbose example
```

```
Creating the project
Project creation command: /usr/local/opt/python/bin/python2.7 /usr/local/opt/python/bin/django-admin.py startproject example .
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/opt/python/bin/django-admin.py': [Errno 2] No such file or directory
The installation failed.
```

The problem is using the `-p .` here, with the given settings, `env` folder is deleted, and thus it is using the system python, not the virtualenv one.

Changing to `-p example` (`djangocms -p example -s -f --verbose example`) solved it.
Which I don't like very much, I like to have my folder structure like this:
```
- project
  |- env
  |- manage.py
  |- project
     |- models.py
```

**Comment by ivjuris** [comment]
Try following this steps. This works for me.

```
virtualenv ~/.venvs/project_name
mkdir project_name
cd project_name
ave // activate virtualenv
pip install djangocms-installer
djangocms -f -p . project_name
```

**Comment by vlad1777d** [comment]
Why is it closed ?
It was not fixed !!

**Comment by yakky** [comment]
@vlad1777d please open an issue on https://github.com/nephila/djangocms-installer providing a complete traceback and the option you provide.
BTW since 0.9, the default command is ``djangocms project_name``

**Comment by AnrietteC** [comment]
To get around this, I added a symlink to the local executable like so:

`cd /usr/bin;
ln -s /usr/local/bin/django-admin.py django-admin.py`
