### ISSUE TITLE
For Django 1.9 support: Update RegexURLResolver

### ISSUE THREAD

**Issue by evenicoulddoit** [divio/django-cms#4890]
I know you don't have 1.9 support, but to help you on your way. Haven't had much time to look further, but I get:

`ImportError: No module named cms_appresolver` caused by `cms.appresolver:124`

I think this relates to upgrade notes:

    ResolverMatch.app_name was changed to contain the full namespace path in the case of nested namespaces. For consistency with ResolverMatch.namespace, the empty value is now an empty string instead of None.

**Comment by yakky** [comment]
See #4812 for progresses on Django 1.9

**Comment by evenicoulddoit** [comment]
Awesome, thanks for the pointer :)
