### ISSUE TITLE
Docs search doesn't seem to work, asks to enable JS, can't find jquery

### ISSUE THREAD

**Issue by altryne** [divio/django-cms#4898]
Hi, 
Frustrated enough to open a ticket. 
Search page almost never works, and searching from google sends me to the wrong version.

Search page asks to enable JS (didn't know in 2016 there's an option to disable it anymore) and opening the console shows the following errors.

![image](https://cloud.githubusercontent.com/assets/463317/12220685/d364d5ca-b783-11e5-95b8-113f209fe1db.png)

**Comment by mkoistinen** [comment]
Confirmed.

Thanks, @altryne

**Comment by evildmp** [comment]
@altryne This is now fixed. I'm not really sure what was happening...
