### ISSUE TITLE
Parent restriction not respected in clipboard

### ISSUE THREAD

**Issue by czpython** [divio/django-cms#4913]
The CMS toolbar does not respect the plugin parent restrictions when the plugin is copied (into the clipboard).

This was first reported in https://github.com/divio/django-cms/pull/4559

- [x] Merge #4914 into 3.2.x
- [x] Forward port to 3.3.x (#4916)

**Comment by vxsx** [comment]
frontend tests are a thing in a fork and they will not be merged for some time, so I'd suggest mergin/forwardporting and i'll do the tests separately
