### ISSUE TITLE
Content in static placeholders is not subject to reversion

### ISSUE THREAD

**Issue by evildmp** [divio/django-cms#4920]
Changes to (say) a text plugin in placeholder will be tracked by reversion.

This appears not to be the case for static placeholders.

Reported by @ubernostrum:
- https://botbot.me/freenode/django-cms/2016-01-15/?msg=57992263&page=1
- django-cms==3.2.0
- djangocms-text-ckeditor==2.8.1
- django-reversion==1.8.7

I can reproduce the issue on django CMS 3.2.0.26.

**Comment by yakky** [comment]
@evildmp correct. Issue is that static placeholders does not have any UI by itself; even publishing / unpublishing them is demanded to any page they are attached to.
Reversion definitely needs its own UI because the history cannot be shared with a page.
In 3.2 we can only document this, I think

**Comment by FinalAngel** [comment]
revision has been removed
