### ISSUE TITLE
Unable to restore app hooked pages on 3.2.x

### ISSUE THREAD

**Issue by czpython** [divio/django-cms#4922]
PR #4883 introduced reversion 1.10.x support on the CMS.

Due to the way reversion 1.10.x works, the page object is restored and then saved using the change form logic but the PageAdmin's save_model assumes that the page has not yet been created and so tries to create a temporary page to get the treebeard attributes but this fails because things like application_namespace are unique at the database level.

- [x] Merge #4923 into 3.2.x

Fixed. To be forward ported to CMS 3.3.x

**Comment by yakky** [comment]
:+1:

**Comment by yakky** [comment]
I expect some minor (hopefully minor) regressions. 1.10 changed a awful lot of things.
In 3.3 / 3.4 it's better to rethink reversion and have a cleaner API

**Comment by czpython** [comment]
@yakky please have a look.
