### ISSUE TITLE
Wrong Documentation On Tutorial

### ISSUE THREAD

**Issue by RocketBrain** [divio/django-cms#4924]
http://docs.django-cms.org/en/develop/introduction/plugins.html

Inside of the cms_plugins.py I had to write the following name for it to work:

class PollPluginPublisher(CMSPluginBase):
    model = PollPluginModel  # model where plugin data are saved
    module = _("Polls")
    name = _("Poll Plugin")  # name of the plugin in the interface
    render_template = "djangocms_polls/poll_plugin.html"

Whereas in the tutorial, under the model name it only said 

model = PollPlugin

**Comment by mkoistinen** [comment]
I just reviewed the linked tutorial, and it is precisely how the OP suggests it should change. So, perhaps someone has already fixed this and forgot to close this? Regardless, closing.
