### ISSUE TITLE
Impossible to override CMS_CACHE_DURATIONS

### ISSUE THREAD

**Issue by czpython** [divio/django-cms#4931]
The [docs](http://docs.django-cms.org/en/develop/reference/configuration.html#cms-cache-durations) point out that it's possible to override the ``CMS_CACHE_DURATIONS`` setting for more control over the CMS caching. This unfortunately does not work.

The CMS completely ignores the ``CMS_CACHE_DURATIONS`` setting defined at the project level and instead will use the following defaults:

```python
{
    'menus': getattr(settings, 'MENU_CACHE_DURATION', 60 * 60),
    'content': get_cms_setting('CONTENT_CACHE_DURATION'),
    'permissions': 60 * 60,
}
```

As shown, the CMS incorrectly looks at the deprecated ``MENU_CACHE_DURATION`` setting for the menu cache.
Then it correctly looks at ``CONTENT_CACHE_DURATION`` for the content cache and last it just hard codes a default for the permissions which means it's impossible to override the permissions timeout.

Credits to @vxsx for the first report.

**Comment by yakky** [comment]
Fixed in #4986
