### ISSUE TITLE
No module 'cms.middleware.utils.ApphookReloadMiddleware'

### ISSUE THREAD

**Issue by dmk12** [divio/django-cms#4938]
According to the [documentation of DjangoCMS 3.2.0](http://docs.django-cms.org/en/3.2.0/how_to/apphooks.html) I should add `cms.middleware.utils.ApphookReloadMiddleware` to `MIDDLEWARE_CLASSES` in my `settings.py` file in order to make the server auto reload whenever there's a changed to my AppHooks.  
However, when I do this 
````
MIDDLEWARE_CLASSES = (
    ...
    'cms.middleware.utils.ApphookReloadMiddleware',
    ...
````
I get an error `ImportError: No module named utils` in terminal and `A server error occurred.  Please contact the administrator.` on the web page.

When I look inside my `venv/lib/python2.7/site-packages/cms` (`venv` is the virtual environment of my project) I indeed don't see a utils.py file.

How do I install it and why is it missing? Are the docs pointing to a wrong location?

**Comment by yakky** [comment]
@dmk12 what's the output of ``pip freeze|grep cms``?
Middleware is https://github.com/divio/django-cms/blob/develop/cms/middleware/utils.py#L7 and both tar.gz and wheel file in pypi contains the relevant code

**Comment by dmk12** [comment]
Output of `pip freeze|grep cms`:
````
cmsplugin-filer==1.0.0
django-cms==3.1.4
djangocms-admin-style==1.0.7
djangocms-column==1.6.0
djangocms-file==0.2.0
djangocms-flash==0.3.0
djangocms-googlemap==0.4.0
djangocms-inherit==0.1.1
djangocms-installer==0.8.1
djangocms-link==1.7.1
djangocms-picture==0.2.0
djangocms-style==1.6.0
djangocms-teaser==0.2.0
djangocms-text-ckeditor==2.8.0
djangocms-video==0.2.0
````
And /cms/middleware/utils.py is missing in my installation.

**Comment by yakky** [comment]
@dmk12 apparently you have django-cms 3.1.4, which does not include the middleware

**Comment by dmk12** [comment]
Doh, my bad :) Thanks, @yakky
