### ISSUE TITLE
double url-escape for plugin icon inside djangocms-text-ckeditor

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#4944]
When inserting a Plugin inside the text plugin, the urls produced for a Plugin icon are escaped twice. This results in invalid urls sometimes and can cause the icon to not be loadable.

![image-2016-01-18-11-28-02-636](https://cloud.githubusercontent.com/assets/14330/12505549/36e300a0-c0e8-11e5-9688-57b1ade50db8.png)
This is for example the case when inserting an Image Plugin into djangocms-text-ckeditor using the S3 storage backend with authentication information in the url. But any url that relies on the get parameters is affected.

Expected url:
```
https://whatever.s3.amazonaws.com/my-bucket/image.jpg?many=different&get=parameters
```
What ends up being used to retrieve the file:
```
https://whatever.s3.amazonaws.com/my-bucket/image.jpg?many=different&amp;amp;get=parameters
```
notice the ``&amp;amp;`` instead of ``&``.

I've already discussed this with @FinalAngel and it comes down to this about the CKEditor: all html will be escaped, because there should never be a single, unescaped ``&`` in html, otherwise it is not strict html. Apparently it is correct to have the url in this form in the ``<img src="...`` tag in the html document:
```
https://whatever.s3.amazonaws.com/my-bucket/image.jpg?many=different&amp;get=parameters
```
Notice the ``&`` is only escaped once, as ``&amp;``. The browser will do the right thing and call the url with unescaped ``&``.

The crux seems to be that django-cms already escapes the icon url server-side: https://github.com/divio/django-cms/blob/54693e7a121190d1df9ba3cdf453ee360fd4d748/cms/admin/placeholderadmin.py#L436
And there are probably good reasons to do so.

So I am not sure where the actual bug is that needs to be fixed.
* Does CKEditor need to be smarter about escaping? e.g not escape a ``&amp;`` again.
* Should the backend return the icon url unescaped? security implications?
* Need to check whether maybe the backend already does the double escaping.

**Comment by vxsx** [comment]
http://docs.cksource.com/ckeditor_api/symbols/CKEDITOR.config.html#.basicEntities

**Comment by stefanfoulis** [comment]
@vxsx : @FinalAngel argued that we can't disable it globally, because then it won't escape stuff it should be escaping.

**Comment by FinalAngel** [comment]
@vxsx this is a very special case, we do not want to disable escaping globally on aldryn otherwise no page will be ever able to pass validation.

http://www.htmlhelp.com/tools/validator/problems.html

**Comment by czpython** [comment]
@vxsx Is this still a problem w/ the new real preview thing?

**Comment by vxsx** [comment]
@czpython not anymore i believe, as we no longer use images there

**Comment by czpython** [comment]
@vxsx hmm but we we now render the image plugin directly there.

**Comment by czpython** [comment]
Fixed by the djangocms-text-ckeditor real preview feature.
