### ISSUE TITLE
deadlock at load time from register_plugin

### ISSUE THREAD

**Issue by jbazik** [divio/django-cms#4945]
In plugin_pool.register_plugin, which runs at load time, plugins are validated in part by loading their templates.  Third party django apps can provide template loaders that can reference models.  Since django 1.7, that's not allowed.  In my case, this is causing deadlock through a nested call to django.apps.apps.populate().  Further discussion here:

https://groups.google.com/forum/#!topic/django-users/WiRzQ8EFOdo
https://groups.google.com/forum/#!topic/django-developers/YvEzdQU4qUU
https://groups.google.com/forum/#!topic/django-cms-developers/CNWHNviqS6Q

I suggest, in the latter thread, to separate plugin registration and validation and do the latter in cms.apps.CMSConfig.ready().  I'm willing to create a pull request if you agree with this in principal.

John

**Comment by yakky** [comment]
@jbazik check the linked PR, it should fix your issue

**Comment by jbazik** [comment]
@yakky awesome!  I will test tomorrow.

**Comment by jbazik** [comment]
My problem remains.  I posed a question to the django devs here:

https://groups.google.com/forum/#!topic/django-developers/YvEzdQU4qUU

It may be that loading templates at any time during setup is no good - waiting to see what they say.

**Comment by yakky** [comment]
AFAIK it's the last stage we can do initialization before the first request. Being a static sanity check I think we should **really** avoid to do this during the first request, because it's too late to do anything sensible in case of an error

**Comment by yakky** [comment]
@jbazik I'm going to merge #4946 as we're approaching the release as it looks an improvement anyway 
I'll keep this open to track your deadlock issue

**Comment by jbazik** [comment]
Agreed, looks good.  Django devs are removing nested call to apps.populate which will fix my deadlock problem.

**Comment by yakky** [comment]
Fixed in #4946
