### ISSUE TITLE
Copy from Language function doesn't work.

### ISSUE THREAD

**Issue by iddqd1** [divio/django-cms#4952]
Copy from language funtionality doesn't work.
Post data send to /admin/cms/staticplaceholder/copy-plugins/ is bad
source_language and target_language are always equal

```
source_placeholder_id:4
source_plugin_id:
source_language:en
target_plugin_id:
target_placeholder_id:4
target_language:en
```

**Comment by yakky** [comment]
@iddqd1 which django / django CMS version are you using?

**Comment by iddqd1** [comment]
@yakky Its the same  for develop and 3.2.0

vim templates/cms/toolbar/plugin.html +9
vim templates/cms/toolbar/placeholder.html +10

are problematic, page_language is  empty
I changed it to language and it works but I didnt writ the test and I dont know the logic behind

**Comment by mkoistinen** [comment]
@iddqd1 we've tried this locally and it seems OK for us. Can you try in your project with the code at release/3.2.x and report back? Thanks.

**Comment by ViktorovEugene** [comment]
Hi. This issue appears if there is no [django.template.context_processors.i18n](https://docs.djangoproject.com/en/1.9/ref/templates/api/#django-template-context-processors-i18n) in the [context_processors](https://docs.djangoproject.com/en/1.9/ref/settings/#template-context-processors). So the configuration script of the toolbar is missing the `page_language` and so on... This is totally spoils the copying process between languages, aspecially for nested plugins. Please add give us a note about this in the documentation.
