### ISSUE TITLE
PlaceholderFields in app models (feature suggestion)

### ISSUE THREAD

**Issue by jribbens** [divio/django-cms#4956]
I would like to suggest that you add something like the following to django-cms:
```python
class PlaceholderMixin:
    """Ensure the model's Placeholder fields are never empty."""
    # pylint: disable=too-few-public-methods

    def save(self, *args, **kwargs):
        """Ensure the model's Placeholder fields are never empty."""
        # Apparently this import has to be here for some reason.
        # https://gist.github.com/mkoistinen/faf0a5b9585616cfd4d8
        from cms.api import add_plugin
        super().save(*args, **kwargs)
        for field in self._meta.get_fields():
            # PlaceholderField.pre_save() ensures that the Placeholder always
            # exists; the question is: are there any plugins inside it?
            if (isinstance(field, PlaceholderField) and
                    not getattr(self, field.name).cmsplugin_set.count()):
                add_plugin(getattr(self, field.name), "TextPlugin", "en-gb",
                        body="<p>Text coming soon.</p>")
```
The idea is that this can then be used in app models which use PlaceholderFields, which otherwise are invisible and uneditable unless the user knows to go into Structure mode and add a text plug-in to the placeholder, e.g.:
```python
class BlogPost(PlaceholderMixin, models.Model):
    """A blog post."""
    title = models.CharField()
    published = models.DateField()
    content = PlaceholderField("blogpost_content")
```

**Comment by mkoistinen** [comment]
Nice code. I do this a lot. Of course, this solution doesn't work for everyone because sometimes, the user wants only a picture in the PHF, and the TextField gets in the way. Having said this, you should have a look at http://docs.django-cms.org/en/develop/reference/configuration.html#cms-placeholder-conf. Using CMS_PLACEHOLDER_CONF, you can declare the default content of a PH/PHF.

**Comment by jribbens** [comment]
Thanks, that's interesting and probably solves my personal use case. It feels like somewhat of an omission though that it looks like you can only specify this information on a site-wide basis, so individual apps would have to come with install instructions saying "install this app then cut'n'paste the following to your settings.py"... For apps most of the information seems like it belongs in the model.
