### ISSUE TITLE
No generic plugins by default

### ISSUE THREAD

**Issue by Brandl** [divio/django-cms#4973]
I just created a new site with django-cms, following the documentation, all pretty standard.
I'm new to django-cms, but is it really normal that no plugins show up by default and if so, how am I supposed to add simple text to the page:
![screen shot 2016-01-31 at 21 23 10](https://cloud.githubusercontent.com/assets/3877188/12704724/03a3c3fc-c861-11e5-861d-7a886fc6aadf.png)

**Comment by Brandl** [comment]
Tested in Chrome and Safari, also here is my settings.py:

    import os

    # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = '$...'

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True

    ALLOWED_HOSTS = []

    SITE_ID = 1

    # Application definition

    INSTALLED_APPS = (
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.sites',
        'djangocms_admin_style',
        'django.contrib.messages',
        'django.contrib.admin',
        'django.contrib.staticfiles',
        'django.contrib.sitemaps',
        'cms',
        'menus',
        'treebeard',
        'sekizai',
    )

    MIDDLEWARE_CLASSES = [
        'cms.middleware.utils.ApphookReloadMiddleware',

        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',

        'cms.middleware.user.CurrentUserMiddleware',
        'cms.middleware.page.CurrentPageMiddleware',
        'cms.middleware.toolbar.ToolbarMiddleware',
        'cms.middleware.language.LanguageCookieMiddleware',
    ]

    ROOT_URLCONF = 'Project.urls'

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [
                os.path.join(BASE_DIR,  'templates'),
                ],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',

                    'sekizai.context_processors.sekizai',
                    'cms.context_processors.cms_settings',
                ],
            },
        },
    ]

    WSGI_APPLICATION = 'Project.wsgi.application'


    # Database
    # https://docs.djangoproject.com/en/1.9/ref/settings/#databases

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


    # Internationalization
    # https://docs.djangoproject.com/en/1.9/topics/i18n/

    LANGUAGE_CODE = 'en'

    LANGUAGES = [
        ('en', 'English'),
        ]

    TIME_ZONE = 'UTC'

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/1.9/howto/static-files/
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
    STATIC_URL = '/static/'

    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    MEDIA_URL = "/media/"

    CMS_TEMPLATES = (
        ('fullwidth.html', 'Full width'),
        ('homepage.html', 'Homepage'),
    )

**Comment by yakky** [comment]
According to the settings no plugin is installed. django CMS does not ship any bundled plugin for maximum flexibility.
You can use djangocms-installer to bootstrap a fairly complete project with all the core plugins: see documentation at http://django-cms.readthedocs.org/en/develop/introduction/install.html

**Comment by Brandl** [comment]
Thanks. My fault. Problem solved :)
