### ISSUE TITLE
Error when creating custom user model

### ISSUE THREAD

**Issue by LouWii** [divio/django-cms#4974]
Hi there !

I'm having an issue with using a custom user model. I've been stuck for an entire day now.

I'm installing Django CMS using the wizard

    Database configuration (in URL format) [default sqlite://localhost/project.db]: 
    django CMS version (choices: 2.4, 3.0, 3.1, 3.2, stable, develop) [default stable]: 
    Django version (choices: 1.4, 1.5, 1.6, 1.7, 1.8, stable) [default stable]: 
    Activate Django I18N / L10N setting (choices: yes, no) [default yes]: 
    Install and configure reversion support (choices: yes, no) [default yes]: 
    Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: en,fr
    Optional default time zone [default America/Los_Angeles]: 
    Activate Django timezone support (choices: yes, no) [default yes]: 
    Activate CMS permission management (choices: yes, no) [default yes]: 
    Use Twitter Bootstrap Theme (choices: yes, no) [default no]: 
    Use custom template set [default no]: 
    Load a starting page with examples after installation (english language only). Choose "no" if you use a custom template set. (choices: yes, no) [default no]: yes

At that point, everything is working fine, I can access the admin CP.

Then, I create an app `python2.7 manage.py startapp custom_auth`
I add to the `models.py` the exact code from the test case

```
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.core import validators
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _


class CustomUserManager(UserManager):

    def _create_user(self, username, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        now = timezone.now()
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(username=username, email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.
    Username, password and email are required. Other fields are optional.
    """
    username = models.CharField(_('username'), max_length=300, unique=True,
        help_text=_('Required. 300 characters or fewer. Letters, numbers and '
                    '@/./+/-/_ characters'),
        )
    email = models.EmailField(_('email address'), blank=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    my_new_field = models.IntegerField(null=True, blank=True, default=42)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.username)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        return "A user called %s" % self.username

    def get_short_name(self):
        "Returns the short name for the user."
        return self.username

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email])
```

Then I add the app in the `INSTALLED_APPS` array, before `cms`
```
INSTALLED_APPS = (
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'custom_auth',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'djangocms_style',
    'djangocms_column',
    'filer',
    'easy_thumbnails',
    'cmsplugin_filer_image',
    'cmsplugin_filer_file',
    'cmsplugin_filer_folder',
    'cmsplugin_filer_teaser',
    'cmsplugin_filer_utils',
    'cmsplugin_filer_video',
    'djangocms_googlemap',
    'djangocms_inherit',
    'djangocms_link',
    'reversion',
    'mysite'
)
```
At that point, if I try `python2.7 manage.py makemigrations`, I got errors
```
auth.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.
	HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.
auth.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.
custom_auth.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.
	HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.
custom_auth.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.
```
And I can't add `AUTH_USER_MODEL = 'custom_auth.User'` to my settings.py file because it's showing
```
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'cms.PageUser'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.8/topics/migrations/#dependencies for more
```

So here I am, I don't really know what to do, what to change. I tried a bunch of stuff I found all around the web, but I was still stuck at some point.
Another case was, everything was setup fine, migration went OK. But I was having an error when displaying an admin page, something like `cannot query louwii, not a Group instance`. (I think it was related to not having Group/Permission management, I guess).

Anyway, a bit of help would be very very cool :)
Also, if I solve the issue, I'll be happy to write a guide or whatever to help other people.
Thank !

**Comment by yakky** [comment]
See this http://stackoverflow.com/questions/34844208/using-django-custom-user-in-existing-django-cms-project/34865060#34865060 for how to replace user model after project setup

**Comment by LouWii** [comment]
So the issue I have is related to the relationships in the database not being updated ?
Is there a guide to set things up before so it's easier and doesn't require any custom migration ?

Anyway, thanks a lot for your help, I might be able to work from here.

**Comment by yakky** [comment]
so far the best documentation is at https://code.djangoproject.com/ticket/25313. It's a django doc issue, not django CMS specific, though
i'd close this. eventually write in django-cms users groups (https://groups.google.com/forum/#!forum/django-cms) to get more help if you need
