### ISSUE TITLE
Exclude (Blacklist) Plugins from all placeholders

### ISSUE THREAD

**Issue by marcosguedes** [divio/django-cms#4979]
Hi there. I wanted to suggest the possibility of excluding a certain plugin from all placeholders. According to the docs it's only possible if I explicitly mention every other plugin in every placeholder.

It's fine if I have a small number of placeholders but it's an inglorious task on more complex templates (in my case, 12 with a great amount of different placeholders and static_placeholders each).

Thank you

(Any tips are greatly appreciated)

**Comment by yakky** [comment]
Fixed by #5412 
To implement blacklist, add the plugin to be blacklisted in ``CMS_PLACEHOLDER_CONF[None]['excluded_plugins']`` list

**Comment by marcosguedes** [comment]
Thank you
