### ISSUE TITLE
Mobile & Desktop Page

### ISSUE THREAD

**Issue by bartmika** [divio/django-cms#4982]
Hi Django-CMS team,

I have a requested feature. Clients are requesting websites to have both responsive sites and custom tailored mobile-only sites powered by jQuery-Mobile. Currently Django-CMS supports creating/editing/etc a single HTML page. The feature I would like to see is to have the ability to add a 'mobile only' page as well when adding a new page; for example, when a smartphone user enters the website, Django-CMS will load up the 'mobile only' page instead of the HTML responsive page, and when a desktop user goes to the website, the single HTML page will load.

Please tell me your thoughts on this.

Thank you kindly and Django-CMS is a phenomenal CMS btw.

**Comment by rodolfomartinez** [comment]
+1

**Comment by evildmp** [comment]
There are some Django applications such as https://github.com/gregmuellegger/django-mobile that can detect mobile users. Could you could use this to select alternative templates for mobile users?

**Comment by bartmika** [comment]
Thanks @evildmp. I will try this. You can close this issue.
