### ISSUE TITLE
Height of new touch-screen-compatible CMS toolbar problematic

### ISSUE THREAD

**Issue by Moini** [divio/django-cms#4984]
The new CMS toolbar is higher than the old one, which, in 'overlay' mode, makes it difficult to reach the breadcrumb links, as they are almost hidden by the toolbar. The toolbar cannot always be hidden using the little triangle button at the right.

![bildschirmfoto_2016-02-06_00-03-32](https://cloud.githubusercontent.com/assets/3240233/12867680/5e2cfaea-ccf4-11e5-8dd8-97f5290c9461.png)

Django 1.8.7., Django-cms 3.2.0

**Comment by FinalAngel** [comment]
@Moini we recommend using djangocms-admin-style that is also referred in the installation instructions for optimal results: https://github.com/divio/djangocms-admin-style
