### ISSUE TITLE
Allow to hide / deregister plugins from configuration

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#5000]
Sometimes, even if a plugin is available in the codebase, you don't want it to be available in any place.
Currently ``CMS_PLACEHOLDER_CONF`` only allow to whitelist plugins in specific placeholders.
**Blacklisting** plugins should be available too (either globally or per-placeholder)

See also http://stackoverflow.com/questions/35044928/django-cms-placeholder-plugin-avaliable-only-to-a-specific-placeholder

**Comment by yakky** [comment]
Linked to https://github.com/divio/django-cms/issues/4979

**Comment by yakky** [comment]
Fixed by #5412 
To implement blacklist, add the plugin to be blacklisted in ``CMS_PLACEHOLDER_CONF[None]['excluded_plugins']`` list

**Comment by marcosguedes** [comment]
Started from #5000, now we here :) Updated stackoverflow answer above

**Comment by yakky** [comment]
@marcosguedes awesome!
