### ISSUE TITLE
Issue when publishing content from custom plugin w/ parent/child

### ISSUE THREAD

**Issue by scottrogers** [divio/django-cms#5001]
I have created 2 plugins:
```
class CarouselPlugin(CMSPluginBase):
    model = Carousel
    name = ("Carousel")
    render_template = "carousel.html"
    cache = True
    allow_children = True

    def render(self, context, instance, placeholder):
        context = super(CarouselPlugin, self).render(context, instance, placeholder)
        return context

plugin_pool.register_plugin(CarouselPlugin)


class SlidePlugin(CMSPluginBase):
    model = Slide
    name = ('Slide')
    render_template = "slide.html"
    change_form_template = "change_form.html"
    cache = True
    parent_classes = ('TextPlugin', 'CarouselPlugin')

    def render(self, context, instance, placeholder):

        context = super(SlidePlugin, self).render(context, instance, placeholder)
        return context


plugin_pool.register_plugin(SlidePlugin)
```
The data comes from these models:

```
from cms.models.pluginmodel import CMSPlugin

class Carousel(CMSPlugin):
    title = models.CharField(blank=True, max_length=100)
    slug = models.SlugField()
    height = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        return self.title

class Slide(CMSPlugin):
    BACKGROUND_POSITIONS = (
        (u'top', u'top'),
        (u'center', u'center'),
        (u'bottom', u'bottom'),
    )
    image = models.ImageField(upload_to="carousel/")
    image_position = models.CharField(blank=True, max_length=100, choices=BACKGROUND_POSITIONS)
    content = models.TextField()
    order = models.PositiveIntegerField(default=0, blank=False, null=False)
    carousel = models.ForeignKey('Carousel')
    slug = models.SlugField()


    def __unicode__(self):
        return self.content

    class Meta:
        ordering = ('order',)

    def image_tag(self):
        return u'<img src="' + settings.MEDIA_URL + '%s" width="50" height="auto"/>' % self.image

    image_tag.short_description = 'Slide'
    image_tag.allow_tags = True
```

1. I can create content and view it when it's in edit mode, but when publishing the content, I get a 500 error.
2. I can publish the parent plugin, CarouselPlugin (when it doesnt have a child plugin in it).
3. When I add a Slide (child to parent plugin), and try to publish that, I get the following error:
![screenshot 2016-02-12 11 07 15](https://cloud.githubusercontent.com/assets/1859538/13017425/fe538646-d178-11e5-843b-ce4c43ca7fa0.png)

Using django-cms==3.2.0

Any help would be great!

**Comment by vivazzi** [comment]
Useless code:
```
def render(self, context, instance, placeholder):
        context = super(CarouselPlugin, self).render(context, instance, placeholder)
        return context
```
P.S. I think, there is a little information to decide your problem

**Comment by scottrogers** [comment]
What else is required?
On Sat, Feb 20, 2016 at 3:03 AM Maltsev Artyom <notifications@github.com>
wrote:

> Useless code:
>
> def render(self, context, instance, placeholder):
>         context = super(CarouselPlugin, self).render(context, instance, placeholder)
>         return context
>
> P.S. I think, there is a little information to decide your problem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/divio/django-cms/issues/5001#issuecomment-186571355>.
>
-- 
Scott Rogers
http://scottrogers.me

**Comment by vivazzi** [comment]
I find next bug: class Slide should not have foreign key to Carousel, because you created two plugins which inherit from base class CMSPlugin.

**Comment by scottrogers** [comment]
That didnt do anything. Thanks for the thought

**Comment by czpython** [comment]
@scottrogers 
The problem is that plugins already have an ordering specified.
Internally there's a field called ``position`` for all plugins, this field along with the path field determine the order of your plugin within the tree and inside a placeholder.

Please remove the ``order `` field and the ``ordering`` from the meta class.
Then run ``python manage.py cms fix-tree`` to fix the plugin positions.
Make sure to backup db just in case given that this command recalculates the plugin positions

Also please upgrade to the latest 3.2.x release as some bugs with fix-tree and the tree were fixed.

**Comment by czpython** [comment]
@evildmp We should probably update the docs on plugins to include a note about overriding the plugin ordering.
