### ISSUE TITLE
Edits can cause a page to become unrenderable

### ISSUE THREAD

**Issue by jribbens** [divio/django-cms#5007]
Somehow, a content editor managed to use the interface to add a LinkPlugin with a position of 'null'. This then causes `build_plugin_tree` to produce the following exception:
```
Exception Type:     TypeError
Exception Value:    unorderable types: NoneType() < int()
Exception Location: .../lib/python3.4/site-packages/cms/utils/plugins.py in build_plugin_tree, line 138
```
due to this:
```python
nonroots = sorted(filter(by_parent_id, cache.values()),
                  key=attrgetter('parent_id', 'position'))
```

**Comment by jribbens** [comment]
Also, the plugin appears to be invisible and hence cannot be edited or removed.

**Comment by evildmp** [comment]
It's not clear to me whether the main problem is that this can happen, or that it is not handled gracefully (the former, in my opinion).

Any idea how to replicate?

**Comment by jribbens** [comment]
My best guess would be it appeared because of the `django_migrations`->`migrations` directory changes in the django-cms plugin packages. `settings.py` files generated by the django-cms installer will contain instructions to django to look in the wrong place for the migrations, which means a simple `pip install -U` on these packages will silently break any project, due to the database tables no longer breaking the models, with inevitable hilarious consequences. That however is a whole different can of worms.

I think the main problem is that nulls are allowed by the database but are not handled gracefully by the code. Using a tiny custom function that converts `None` to `0` instead of just relying on `attrgettr` would be much better.

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/4698 on 3.3
