### ISSUE TITLE
CMS 3.2.x, structure mode : Plugins DragAndDrop does nothing

### ISSUE THREAD

**Issue by DylannCordel** [divio/django-cms#5018]
Hi,

In structure mode, when we try to draganddrop plugins inside a PH, the visual JS effect appears (Red line to see where plugin will be dropped), but when when drop it, nothing appens : no JS errors neither network calls.

Tested with 3.2.0 and 3.2.1.

**Comment by vxsx** [comment]
Red line means that the plugin cannot be pasted there. It happens if plugins involved have parent or child restrictions.

**Comment by vxsx** [comment]
In 3.1 we never enforsed [child_classes](http://docs.django-cms.org/en/develop/reference/plugins.html#child-classes) and parent_classes in the frontend, so you couldn't "add" them to it, but could still drag them. Starting from 3.2 we enforce it in the frontend

**Comment by DylannCordel** [comment]
Thx for this tip. 

It does not work for plugins I just created with the "+" button from the Placeholder (I can create many Text plugins inside this PH, but can not move into it for exemple). 

I'll continue to investigate.

**Comment by DylannCordel** [comment]
Thx a lot @vxsx, I found the problem : in the set of installed APP, there was one which overrode cms/toolbar/plugin.html with an "old" version of this file :-/

Sorry for noise...
