### ISSUE TITLE
Clipboard items are not necessarely the first

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#5023]
There is a wrong assumption here: https://github.com/divio/django-cms/blob/release/3.2.x/cms/static/cms/js/modules/cms.plugins.js#L21-L22
Clipboard items are not necessarly the first items of their kind: e.g. when multiple toolbars register for ``render_addons`` (https://github.com/divio/django-cms/blob/develop/cms/toolbar/toolbar.py#L144)

**Comment by yakky** [comment]
@FinalAngel @vxsx do we have any better way to get the clipboard items, instead of picking the first?

**Comment by vxsx** [comment]
@yakky but they are definitely the first items of their kind inside of the clipboard, no?
https://github.com/divio/django-cms/blob/develop/cms/templates/cms/toolbar/clipboard.html#L6

**Comment by yakky** [comment]
@vxsx oops, I overlooked that. 
So, the problem is not those selectors, but goes away when clipboard ``render_addons`` is called before the others. I'll provide more detailed information later

**Comment by yakky** [comment]
Fixed by #5097
