### ISSUE TITLE
`cms.middleware.toolbar.ToolbarMiddleware` prevents unauthenticated POST requests

### ISSUE THREAD

**Issue by agconti** [divio/django-cms#5024]
In addition to using django cms in my project, I also have a rest api. With `cms.middleware.toolbar.ToolbarMiddleware` included in my middleware settings `request.POST` is empty and causes requests to fail.

After debugging the [toolbar middleware](https://github.com/divio/django-cms/blob/develop/cms/middleware/toolbar.py), I found that the api requests were being identified as cms requests in [this line](https://github.com/divio/django-cms/blob/develop/cms/middleware/toolbar.py#L73). Somehow, enabling the tool bar like this is making `request.POST` empty. Adding:

```python
CMS_TOOLBAR_HIDE = True
```

to my settings solves the issue and correctly populates `request.POST`. While this works, I'd like to be able to use the tool bar. 

**Is there a way that I can prevent api routes from being identified as cms routes**?

**Comment by yakky** [comment]
@agconti this has been fixed in #5022 and will be released in 3.2.2

**Comment by agconti** [comment]
@yakky thanks for letting me know! Do you know the timeline for `3.2.2` to be released?

**Comment by yakky** [comment]
In a couple of days, if all goes well
