### ISSUE TITLE
Possible regression with placeholder permissions

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#5027]
Maybe I've been doing it wrong but previously apphooks templates that inherit from the CMS page they were attached to could optionally inherit the content of placeholders in the CMS template and were editable from the apphook pages. 

For example, say I had a products apphook, and products_list.html & products_detail.html would inherit from cms_template.html. In the products templates, I could use `{% placeholder 'content' %}` to display the parent CMS page content. This meant I could also edit them from any apphook page that inherited the placeholder (granted, it was the same, single placeholder shared by all pages).

One upside of this arrangement was that I could have CMS editable intro content on the first page of a list view (and hide the placeholder on page 2, etc.). 

Now I'm on 3.2.1 and when I try to edit the placeholder from an apphook page, I get a "You do not have permission to add a plugin" error.

This is the check where it fails:
https://github.com/divio/django-cms/blob/3.2.1/cms/admin/pageadmin.py#L556-L557

Apparently the apphook is only attached to the published version of the page, so the `publisher_is_draft` will return False.

Should the use case above be permitted and did some change in 3.2.x inadvertently break this? Or is there some other preferred method for accomplishing what I'm after?

**Comment by yakky** [comment]
In apphooked templates you can only use ``static_placeholder``
The permission message is actually misleading, as "plain" ``placeholder`` are simply not supported in apphooked templates

**Comment by jsma** [comment]
Ah. Was it an accident that this worked before? Or was this a deliberate change? 

Either way, I'm not sure that static placeholders are the right tool for the job. I haven't used them before but my understanding is that they are global across the site and not particular to children of a particular CMS page. 

If that's correct, it seems that in order to recreate the same behavior as before, I'd have to give the static placeholders unique names per apphook (e.g. 'content-products', 'content-locations', etc), then duplicate CMS_PLACEHOLDER_CONF for each of these placeholders to enforce the limits that they previously would have shared when they used the normal placeholder 'content'.

**Comment by yakky** [comment]
It was an accident that this worked before, actually
The behavior has been established since 3.0 (see docs: http://django-cms.readthedocs.org/en/develop/how_to/templates.html#static-placeholder) and I am actually surprised it worked before. In which version the plain placeholders works for you?

**Comment by jsma** [comment]
Sorry, I could be completely wrong about this 'working' in the past. It could be that we're just now noticing it because we're attempting to edit from child pages (for the first time maybe?). Sorry to waste your time on that! 

Am I correct though that I'd need to create completely separate static placeholder names and then duplicate the config for them? My real use case is essentially {% static 'sidebar' %} but I need the content to be different per apphook but they should all have the same limits on type and quantity of plugins. The only other solution I can think of is to add a Placeholder('sidebar') to the models and populate them with inherit plugins but that seems like overkill and more complex for editors to manage.

Thanks @yakky ! I owe you so many beers at this point ;)

Closing this as a wontfix.

**Comment by yakky** [comment]
PlaceholderField on the model in this case is the preferred way, otherwise "dynamic" static placeholders name is the only solution, with the additional burden of repeated configuration; this will be solved in #5006, anyway, which adds a much more flexibile ``CMS_PLACEHOLDER_CONF``
