### ISSUE TITLE
prevent reverse relation clash for plugins (back-references)

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#5030]
CMSPlugins are built with multi table inheritance. Every Custom Plugin inherits from the base ``CMSPlugin`` model.
Django automatically creates a reverse relationship from the base model to the custom plugin model, named the same as the model. It is the class name in lowercase.

So for example the ``djangocms_file.File`` Plugin will result in ``CMSPlugin`` having an attribute called ``file``, which is also available on all other plugins in the project.

If someone else now creates a Plugin with a field called ``file``, there is a naming clash. In previous django versions this was sort of ignored and continued to work. But as of Django 1.9 this results in a hard error.

The error will look something like this:
```
cmsplugin_filer_file.FilerFile.file: (models.E006) The field 'file' clashes with the field 'file' from model 'cms.cmsplugin'.
cmsplugin_filer_link.FilerLinkPlugin.file: (models.E006) The field 'file' clashes with the field 'file' from model 'cms.cmsplugin'.
```

### proposed fix

Explicitly set the reverse relation for the back-reference to be ``'+'`` (meaning no back-reference) by default. If a developer needs the back reference, it can be added back on a per plugin basis and it should be encouraged to add the app name as a prefix.

Currently you can do this on a Plugin-by-Plugin basis like this:

```python
class FoobarPlugin(CMSPlugin):
    cmsplugin_ptr = models.OneToOneField(CMSPlugin, related_name='+', parent_link=True)
    foo = models.BooleanField()
```
But it really ought to be the default.

### Related previous discussions:

* https://github.com/divio/django-cms/issues/3204 (Prefixing the Plugin model name would no longer be necessary)
* http://stackoverflow.com/questions/20334029/django-app-cannot-assign-imagetext-link-must-be-a-link-instance/20346355#20346355
* field renaming workarounds:

  * https://github.com/divio/cmsplugin-filer/pull/219
  * https://github.com/divio/djangocms-file/pull/13

* Similar, but different issue. This one is about the Plugin class, not the Plugin model class: https://github.com/divio/django-cms/issues/462

**Comment by stefanfoulis** [comment]
@yakky has tested the change that would be necessary: https://github.com/yakky/django-cms/commit/e798a9688bce7c4cc076cccefb0ff67ab2d372ae
Testsuite passes except for 2 tests that just need minor tweaks. More testing needed.

Probably it should not override it if the user specifically set something different though.

**Comment by stefanfoulis** [comment]
django-cms ``3.2.2`` and ``develop`` have been fixed to not break with custom or deactivated ``related_name`` on ``cmsplugin_ptr`` (divio/django-cms#5050). The further plan is to set a namespaced default (``appname_modelname``) by default starting in django-cms ``3.3``.
In the meantime we'll update our official plugins to set the same ``reverse_name`` manually as a workaround (see divio/meta#1).

**Comment by mkoistinen** [comment]
@stefanfoulis this can be closed right? If not, please re-open.
