### ISSUE TITLE
Can't view created pages

### ISSUE THREAD

**Issue by bxm156** [divio/django-cms#5036]
I'm running Django 1.9 and Django CMS 3.2.1. When I create a new page, I can't navigate to it, I just get a 404. I can't access it in "Admin mode" either. I was able to create the root page at /, and that works fine

My url_patterns looks like:
```
urlpatterns = [
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^filer/', include('filer.urls')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^api/', include(router.urls, namespace="api")),
    url(r'^', include('cms.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

**Comment by evildmp** [comment]
I am not sure how compatible 3.2.1 is with Django 1.9. Does this also occur if you use the ``develop`` branch?

**Comment by bxm156** [comment]
Oh, I was under the impression 3.2.1 was the first compatible release for Django 1.9, I'm not sure why I was under that impression. I'll revert to 1.8.9 and see what happens

**Comment by bxm156** [comment]
I discovered this is actually do to DjangoCMS blog, so I opened a ticket there.

https://github.com/nephila/djangocms-blog/issues/214
