### ISSUE TITLE
Reversion not created through API calls

### ISSUE THREAD

**Issue by czpython** [divio/django-cms#5054]
Creating pages through the API does **not** create revision history.
This is not really a bug as the API simply never implemented any kind of revision support.

I don't agree with adding revision logic to the ``cms.api`` but I think we can expose ``make_revision_with_plugins`` from [helpers](https://github.com/divio/django-cms/blob/develop/cms/utils/helpers.py#L39) and use it the api provided that the user explicitly wants to create a revision for a page with a new option like ``create_page(with_revision=True)``.

@divio/django-cms-core What do you guys think?

**Comment by yakky** [comment]
:+1:

**Comment by mkoistinen** [comment]
Exactly. It really shouldn't be done every time one creates a page with the API, but I do like the idea of it being an option.

**Comment by stefanfoulis** [comment]
:+1:

**Comment by FinalAngel** [comment]
:+1:
