### ISSUE TITLE
Page tree is broken if translations contains quote

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#5061]
For example in italian **Pick an action** is translated as **Seleziona un'azione** which breaks ``data-colit`` attribute in the ``PageAdmin.get_tree`` output:

    
    data-colit='
        <div class="cms-tree-col">
            <div class="cms-tree-item cms-tree-item-lang">
                
                    <a href="/admin/cms/page/514/it/preview/"
                        class="cms-tree-lang-container js-cms-tree-tooltip-trigger"
                        
                         target="_top">
                        
                        <span class="dirty" title="modifiche non pubblicate"></span>
                    </a>

                    <div class="cms-tree-tooltip-container js-cms-tree-tooltip-container">
                        <h3>Seleziona un'azione:</h3>
                        <a href="/admin/cms/page/514/it/preview/" target="_top">
                            <span class="cms-icon cms-icon-eye" title="Modifica questa pagina in IT"></span> Anteprima
                        </a>
                        
                        
                            
                                
                                    <a href="/admin/cms/page/514/it/publish/?redirect_language=en" class="js-cms-tree-lang-trigger">
                                        <span class="cms-icon cms-icon-check-o"></span> Pubblica
                                    </a>
                                
                                
                                    <a href="/admin/cms/page/514/it/unpublish/?redirect_language=en" class="js-cms-tree-lang-trigger">
                                        <span class="cms-icon cms-icon-forbidden"></span> Sospendi la pubblicazione
                                    </a>
                                
                            
                        
                    </div>
                
            </div>
        </div>

**Comment by yakky** [comment]
@FinalAngel @vxsx could you have a look at this and the proposed PR?

**Comment by yakky** [comment]
@divio/django-cms-core due to this 3.2.2 is potentially broken for a few languages. How can we handle this?

**Comment by czpython** [comment]
I would suggest waiting about a week for a 3.2.3 release which should be just a bug fixes release.

**Comment by yakky** [comment]
IMO we should plan a shorter term release, 3.2.2 may be completely unusable for some languages

**Comment by yakky** [comment]
Fixed in 3.2.3
