### ISSUE TITLE
Django-CMS 3.2.2 translation issue in Pages

### ISSUE THREAD

**Issue by maltebeckmann** [divio/django-cms#5065]
Upgraded from Django-CMS 3.2.1 to 3.2.2 yesterday and immediately ran into a bug with translation. 
Using Django 1.9.3.

Better explained with two pics:

v3.2.1: ok
http://pasteboard.co/216iNdAh.png

v3.2.2: borked
http://pasteboard.co/216kLedL.png

Note that there are no "publish-dots" in the column for Chinese page translations.

**Comment by vxsx** [comment]
Likely related to https://github.com/divio/django-cms/issues/5061

**Comment by maltebeckmann** [comment]
Want me to close this?

**Comment by yakky** [comment]
@maltebeckmann please leave this open to track the issue. It might be entirely different. Could you eventually test installing release/3.2.x branch straight from github? ( ``pip install https://github.com/divio/django-cms/archive/release/3.2.x.zip`` )

**Comment by maltebeckmann** [comment]
Sure, just ping me!

**Comment by yakky** [comment]
@maltebeckmann fix for #5061 has been merged, could you test if this fixes your problem too?

**Comment by maltebeckmann** [comment]
Hi yakky, so I ran
pip install https://github.com/divio/django-cms/archive/release/3.2.x.zip
and got "django-cms==3.2.2.post0" as pip freeze output.
Cleared by browser caches but didn't solve the issue so far.

**Comment by maltebeckmann** [comment]
Tried pip install git+git://github.com/divio/django-cms.git@56eb77ed928bf4db798107116073e50fcbe60e01

But that, for some reason, can't be executed from China...

**Comment by yakky** [comment]
@maltebeckmann thanks for you tests
@vxsx apparently this is a different issue than #5061 , thus further investigation is required

**Comment by maltebeckmann** [comment]
That seems to have fixed it! Thank you!
