### ISSUE TITLE
Seems like CMS is loading jquery from Google api

### ISSUE THREAD

**Issue by maltebeckmann** [divio/django-cms#5066]
Could it be that Django-CMS ({% render_block "js" %}) is using googleapis.com for loading jquery for the toolbar? I really can't afford to have any Googleapi calls in my app. Is there any way I can host those required files myself? Googleapis's can often not be loaded in China.

...
script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"
...

**Comment by vxsx** [comment]
Django CMS doesn't load jquery from google api, we use our own copy which is loaded as part of the `bundle.admin.base.min.js` https://github.com/divio/django-cms/blob/develop/gulpfile.js#L56

it might be that some other app / template adds jquery from googleapis to sekizai "js" block

**Comment by maltebeckmann** [comment]
My bad -- was the debug toolbar.
