### ISSUE TITLE
Permissions are overwhelming

### ISSUE THREAD

**Issue by KeithCu** [divio/django-cms#5069]
I wanted to setup an account with appropriate limited permissions for an editor, and the options are overwhelming, and I think a mess. I spent over an hour and never got it working. Please find a way to make it simpler. I don't really think any user wants all those choices and I wonder whether any were consulted in the design of the feature.

**Comment by evildmp** [comment]
Hi @KeithCu can you say more about what you wanted to achieve?

Some aspects of the page permissions are more complex than they need to be, but in general the system has worked well for many years, for many users, and has proved both reliable and adequate.

A lot of users *do* require quite granular permissions control. If you don't need this, change ``CMS_PERMISSION = True`` to ``False`` in the settings.

Still, please feel free to give some more information about the precise problem you had.

(#5701 is another issue entirely, we're looking into that.)

**Comment by KeithCu** [comment]
I couldn't understand the difference between "can add version" versus "can add revision". Why does multi-column need separate permissions than a single column? I can't envision a scenario where someone would want one, but not the other. I couldn't understand "cms | page". It would seem like many permissions, such as "can change revision" (which sounds like it is changing history as opposed to just adding new revisions which is presumably what typically happens) could just be a part of the super-user account. Same with "can change alias plugin model" 

I would want somewhat granular permissions in terms of an editor account versus a super-user account.

**Comment by czpython** [comment]
@KeithCu 
Hello, the permissions you're describing are standard Django permission labels which Django generates for all installed apps.

Django CMS extends Django's permission handling to allow per page permission control but we don't plan on overriding Django's permissions entirely.
