### ISSUE TITLE
Welcome wizard redirect to language-prefixed home, even when i18n is disabled

### ISSUE THREAD

**Issue by mrmikee** [divio/django-cms#5070]
While following [Martin's YouTube Demo](https://www.youtube.com/watch?v=NbsRVfLCE1U&list=PLbNxojMo86v42AOM47uhaEFHIJFUM4d6M&index=12) 
I answered NO to the I18N/L10N question, yet the installer still asked for a language choice.  I entered **'en'** and proceeded.  Then I:
1. `manage.py runserver 0:8000`
2. opened in browser
3. logged in 
The cms defaulted to URL `http://localhost:8000/en/?edit` which gives a **404 error**.

Changing the URL to `http://localhost:8000/?edit` actually opens home page editing view.

Please correct this behavior, for beginners it is very confusing.

**Comment by yakky** [comment]
@mrmikee at least one language is required by django, thus it must be provided in any case.
Apparently the automatic redirect of the welcome page, assumes that multilanguage is enabled anyway
Thanks for reporting

**Comment by edevil** [comment]
Is there any solution to this problem? I'm seing this as well on a fresh manual installation of 3.4.5 and I don't want to use localized URLs.

My language settings are:
```
LANGUAGE_CODE = 'pt'
LANGUAGES = [
    ('pt', _('Portuguese')),
    ('en', _('English')),
]

CMS_LANGUAGES = {
    1: [
        {
            'code': 'pt',
            'name': _('Portuguese'),
        },
        {
            'code': 'en',
            'name': _('English'),
            'fallbacks': ['pt'],
        },
    ],
    'default': {
        'fallbacks': ['en'],
        'redirect_on_fallback': False,
        'public': True,
        'hide_untranslated': False,
    }
}
```
When I try to access ```/``` I get redirected to ```/admin/login/?next=/pt/?edit``` which will 404 after the login.

Is there any configuration that I can do to mitigate this issue?
