### ISSUE TITLE
Permissions are broken with default installation

### ISSUE THREAD

**Issue by KeithCu** [divio/django-cms#5071]
1. Create default installation of Django-CMS.
2. Create basic page.
3. Create editor account.
4. Give editor account all permissions including staff status, but not superuser.
5. Try to have editor account edit a page.
6. Get error message (You do not have permission to edit this plugin)

**Comment by KeithCu** [comment]
Note, I'm doing this on Arch Linux with the stable version. Let me know if you have any other questions about my installation.

**Comment by timur-orudzhov** [comment]
@KeithCu I've encountered with the same issue. https://github.com/divio/django-cms/issues/5053 - here i described my situation.

**Comment by evildmp** [comment]
I can confirm this.

I can also confirm, that even with **all** permissions available, a non-super-user has **no** permission to edit pages at all (the Page list is not available in admin, the user does not see the *Pages...* item in the site menu in the toolbar).

This only occurs when ``CMS_PERMISSION = True`` in ``settings.py`` (the default), and happens both in 3.2.3 and develop.

**Comment by piotrjakimiak** [comment]
User Permission (django.contrib.auth.models.Permission). which allows to change Page model is missing name.
I've fixed it in #5133.

You can still find it in user form. It's unicode is something like "cms | Page | "

**Comment by czpython** [comment]
When `CMS_PERMISSIONS` is set to `True`, it's required to give each user global or individual permissions to a page, either by modifying the page specific permissions or setting a global permission for the user.
