### ISSUE TITLE
Start page changes whenever a page is saved

### ISSUE THREAD

**Issue by ribx** [divio/django-cms#5081]
I am running 3.2.3 and whenever I save a page, it is set as the start page.

I had the wrong page as start page and changed it in directly in the database. I dont know, whether this caused the problem. I was setting "is_home" to 0 and to 1 for my actual start page.

I am running django 1.9.

**Comment by czpython** [comment]
@ribx 
Yes, internally the homepage is determined through the tree position and the is_home flag.
