### ISSUE TITLE
Documentation bug in "Extending the page & title models"

### ISSUE THREAD

**Issue by jrief** [divio/django-cms#5083]
In `docs/how_to/extending_page_title.rst` I read:

> Once you’ve registered your admin class, a new model will appear in the top- level admin list.

but since the method from the base class `PageExtensionAdmin.get_model_perms()` returns an empty dict, nothing appears in the top- level admin list.

**Comment by yakky** [comment]
@jrief documentation is wrong. Nothing should appear in the admin (it used to, but has been removed because it was useless and confusing)
