### ISSUE TITLE
Reverse for 'my_test_app_view' not found

### ISSUE THREAD

**Issue by maltebeckmann** [divio/django-cms#5084]
I installed Django-CMS via installer some time ago but think I have since not used the installed. Still getting 

reverse('my_test_app_view'): Reverse for 'my_test_app_view' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

I can't find any reference in my repo. Where does this come from and how do I get rid of this?

**Comment by czpython** [comment]
@maltebeckmann 
Hi there, the code responsible for this is in https://github.com/divio/django-cms/blob/develop/cms/utils/apphook_reload.py#L96. This is called by the apphook reload middleware.

As you can see, it will only show up if ``DEBUG = True``.
That said, I think this (as most of the times prints are used) is a great case for logging..

**Comment by maltebeckmann** [comment]
Thanks!

**Comment by axil** [comment]
@czpython So what does this message tries to say a user who has just installed django-cms using the installer wizard and expecting that there will be no warnings there on this stage? I don't see any references of 'my_test_app_view' in django-cms except in this file.

And how to get rid of it? I need DEBUG=True for other things, it is not an option for me to turn it off.

**Comment by bnisevic** [comment]
Why is this closed when it is still present there?

**Comment by noranana** [comment]
user who has just installed django-cms using the installer wizard and expecting that there will be no warnings there on this stage? I don't see any references of 'my_test_app_view' in django-cms except in this file.????

**Comment by nikosgpet** [comment]
Why is this closed? I have the same issue, and it makes no sense to see a warning unless there is something to fix.

**Comment by czpython** [comment]
The original question was solved. I've created a ticket to track the issue https://github.com/divio/django-cms/issues/5448
