### ISSUE TITLE
django-cms.com serves a blank page

### ISSUE THREAD

**Issue by derek-adair** [divio/django-cms#5088]
Not sure if you guys are aware of this, but django-cms.com is currently serving an empty HTML page.  This should probably be redirected to docs.django-cms.com/ permanently if you guys are not trying to serve actual content there.

**Comment by derek-adair** [comment]
Ok, so now its back... very odd.

Is this something that you guys have a lot of problems with?

**Comment by FinalAngel** [comment]
@derek-adair thanks for the report :)

We are currently optimising some parts of the website, due to this we might have some downtimes this week.
