### ISSUE TITLE
Documentation Page and Title

### ISSUE THREAD

**Issue by petrklus** [divio/django-cms#5092]
The example provided for the "populate" method for Title extension is not correct:

```
def populate(self):
    # setup the extension toolbar with permissions and sanity checks
    current_page_menu = self._setup_extension_toolbar()
    # if it's all ok
    if current_page_menu and self.toolbar.edit_mode:
        # create a sub menu
        position = 0
        sub_menu = self._get_sub_menu(current_page_menu, 'submenu_label', 'Submenu', position)
        # retrieves the instances of the current title extension (if any) and the toolbar item URL
        urls = self.get_title_extension_admin()
        # cycle through the title list
        for title_extension, url in urls:
            # adds toolbar items
            sub_menu.add_modal_item('icon for title %s' % self._page().get_title(),
                                    url=url, disabled=not self.toolbar.edit_mode)
```

As there is no self._page(). (error 'HeroImageExtensionToolbar' object has no attribute '_page')

Also, the documentation does not include a template example when using Title instead of Page extension. I have resorted to using context processor to get it to show up in my template:

```
def add_hero(request):
    print request
    return {
        "heroimageextension" : request.current_page.get_title_obj_attribute("heroimageextension")
    }
```

Then in template

```
{% if heroimageextension %}
    {{ heroimageextension.hero_image.url }}
{% endif %}
```

But that is hardly ideal (having to have it in the settings etc.). Please provide a nicer way to do this!

**Comment by evildmp** [comment]
@petrklus You are right that the example for populate() is incorrect; a patch is coming to address that. 

I don't see what the issue is with templates is though, or why you needed a context processor.

**Comment by petrklus** [comment]
@evildmp Thank you for picking it up - if I recall correctly, I simply could not see the extension in the template without the template processor. It's a while back so probably safe to drop it, I will create another issue if I notice the behaviour again (and will be able to test it more)
