### ISSUE TITLE
Cannot publish page - Integrity error - UNIQUE constraint failed

### ISSUE THREAD

**Issue by petrklus** [divio/django-cms#5100]
See Gist for full traceback:

https://gist.github.com/petrklus/8f31dfe0e790b99a47a9

**Comment by czpython** [comment]
@petrklus 
Hey, are you able to consistently reproduce this still?

Please provide some info:

Does the page being published have a parent?
Is this the first time this page is published?
Do you know if anyone else was making changes to this or other pages around the time you published?

**Comment by czpython** [comment]
This should now be fixed on 3.3
Please check it out and run ``cms fix-tree``
