### ISSUE TITLE
Foundation 5/6 and Toolbar 

### ISSUE THREAD

**Issue by leesolway** [divio/django-cms#5101]
Both Zurb Foundation 5 and Foundation 6 seem to have issues with the Django CMS toolbar, causing misplacement of the login input fields. 

I know previous JS issues between Foundation and the CMS have been resolved before.

The following screenshot is using Foundation 6.

<img width="1065" alt="screen shot 2016-03-23 at 20 13 07" src="https://cloud.githubusercontent.com/assets/2929803/13999374/ff6d546e-f133-11e5-96fd-50bcc0aa5e0a.png">

Thanks,

**Comment by czpython** [comment]
@vxsx Can we close this?

**Comment by vxsx** [comment]
Should be fixed on latest `release/3.2.x` and `develop`, so yeah, closing, thanks a lot for the report @leesolway
