### ISSUE TITLE
Add shortcuts

### ISSUE THREAD

**Issue by vivazzi** [divio/django-cms#5105]
For example, when hovering over a page in structure of pages, pressing “e” will open quick edit mode, which lets you quickly edit the page attributes.

I have inspired of trello (task manager) shortcuts, which save a lot if time in work.
May be we can take something from trello: https://trello.com/shortcuts

Also It's need to add section "Shortcuts" to documentation.

**Comment by FinalAngel** [comment]
It would in general be a good idea to add more shortcuts, though django CMS is not an encapsulated application such as trello. Eventually you are building trello using django CMS and integrate those shortcuts yourself in the frontend. This would end up with conflicts.

We will consider the option of additional more shortcuts and the required documentation.

**Comment by vxsx** [comment]
We added some useful shortcuts for 3.4 
https://github.com/divio/django-cms/pull/5602
https://github.com/divio/django-cms/pull/5600

although not exactly same thing as with trello ones, but still.

It would make sense to open discussion on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms) or [Developers Mailing List](https://groups.google.com/forum/#!forum/django-cms-developers). Proposals and pull requests are very welcome.
