### ISSUE TITLE
Running django-cms instance in read-only mode

### ISSUE THREAD

**Issue by g10f** [divio/django-cms#5106]
Because of security reasons, it would be nice if a django-cms instance could be started in read-only mode without the django.contrib.admin app.
Currently if I remove django.contrib.admin, admin .urls and the cms_toolbar from the project, there are errors in pageadmin.py caused by the following import:

from django.contrib.admin.models import LogEntry, CHANGE

**Comment by yakky** [comment]
Maybe just removing any superuser / staff flag from any user in the database?

**Comment by czpython** [comment]
Hello @g10f , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Developers Mailing List](https://groups.google.com/forum/#!forum/django-cms-developers).

**Comment by cochiseruhulessin** [comment]
This is certainly not a non-issue and should be reopened. Any deployment that matters will not want to expose any admin URL or page to the general public, and service this in a restricted area (e.g. client auth or VPN).
