### ISSUE TITLE
All sibling pages unpublished when new sibling moves in

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#5107]
Just uncovered a very nasty bug which will unpublish all siblings when a new sibling is moved in.

Consider the following minimal tree, with a single section with two children:

<img width="855" alt="screen shot 2016-03-27 at 10 30 28 pm" src="https://cloud.githubusercontent.com/assets/24574/14071617/b0942d82-f46b-11e5-93e5-90083482530e.png">

Now click the big blue 'Add page' button to create an 'Accidental root' page (meaning it's being created at the root level instead of as 'Child 3'):

<img width="858" alt="screen shot 2016-03-27 at 10 30 53 pm" src="https://cloud.githubusercontent.com/assets/24574/14071620/b4bcd224-f46b-11e5-9b47-cc2bb308a3c6.png">

Now drag 'Accidental Root' so that it becomes a child of 'Section 1':

<img width="847" alt="screen shot 2016-03-27 at 10 31 15 pm" src="https://cloud.githubusercontent.com/assets/24574/14071621/b8a09920-f46b-11e5-8bb8-2312f8a87ce3.png">

All existing siblings are now unpublished:

<img width="843" alt="screen shot 2016-03-27 at 10 31 26 pm" src="https://cloud.githubusercontent.com/assets/24574/14071622/bcc728ca-f46b-11e5-9491-d1afd3cb15f3.png">

If you have menus and apphooks attached to Child 1 or 2, your site is now broken until you manually publish every page within Section 1.

**Comment by yakky** [comment]
Nasty indeed. Which cms version?

**Comment by jsma** [comment]
The latest, 3.2.3. I have a minimal project you can use => https://github.com/jsma/cmstest/tree/fcac9d0812104eeb2f79fe2c7f822ccd66125161

**Comment by yakky** [comment]
Awesome, thanks

**Comment by jsma** [comment]
It only seems to happen if the page being moved started its life as a 'root' page. I can move grandchildren up to be children without issue, can move children from other sections into Section 1 without issue as well.

**Comment by czpython** [comment]
Verified as a regression of 3.2.

**Comment by czpython** [comment]
Regression came from https://github.com/divio/django-cms/commit/ec1d6c3c1d666efe3cb6eec5a13f59d81f0fbc42.
I have a fix ready, will check with @mkoistinen tomorrow to make sure it's good.

**Comment by czpython** [comment]
- [ ] Merge #5137 into develop
- [ ] Merge #5139 into 3.2.x

**Comment by czpython** [comment]
Fixed in develop and 3.2.x.
@jsma thanks for reporting.
There's another bug that came from the same commit, I've started working on a fix. (#5140)

**Comment by jsma** [comment]
Thanks everyone for their work on this! Any ETA when we might see a point release for this?

**Comment by FinalAngel** [comment]
@jsma we are working for a release this week.
