### ISSUE TITLE
Documentation for 3.0 release is wrong

### ISSUE THREAD

**Issue by writepython** [divio/django-cms#5121]
http://docs.django-cms.org/en/3.2.3/upgrade/3.0.html
https://github.com/divio/django-cms/blob/3.2.3/docs/upgrade/3.0.rst

python manage.py cms publisher_publish
should read
python manage.py publisher_publish

**Comment by yakky** [comment]
Thanks for spotting this. If you would contribute a patch, we will happily merge that
