### ISSUE TITLE
CMSAttachMenus that are not configured should not be processed

### ISSUE THREAD

**Issue by mkoistinen** [divio/django-cms#5136]
Apparently, to create a CMSAttachMenu you must register it with the menu_pool in order for it even appear as an option in the AppHook configuration form (advanced page settings).

Also, apparently, if one does not select one of these menus for the apphook, the mere fact that the menu is registered, it will be processed during menu render (even if there is no actual change to the resulting menu).

There should be a way for the menu to be registered but not considered for processing unless actually chosen in the advanced page form, or, declared in `cms_apps.py`.

Processing an arbitrarily expensive CMSAttachMenu that is not used should be avoided at all costs.

**Comment by czpython** [comment]
Fixed in #5299
