### ISSUE TITLE
When changing CMS_DEFAULT_X_FRAME_OPTIONS new migration need to be created

### ISSUE THREAD

**Issue by vstoykov** [divio/django-cms#5163]
When changing `CMS_DEFAULT_X_FRAME_OPTIONS` in `settings` django wants to create new migration for the `cms` app.

The reason is that initial migration does not get this value dynamically.

One possible solution is to double the code in models and to use it in the migration.

    getattr(settings, 'CMS_DEFAULT_X_FRAME_OPTIONS', Page.X_FRAME_OPTIONS_INHERIT)

Other possible solution will be to move this configuration to `cms.utils.conf` and to get it with `get_cms_setting('DEFAULT_X_FRAME_OPTIONS')`.

Second variant can cause moving definition of: `X_FRAME_OPTIONS_INHERIT`, `X_FRAME_OPTIONS_DENY`, `X_FRAME_OPTIONS_SAMEORIGIN` and `X_FRAME_OPTIONS_ALLOW` from `cms.models.Page` to `cms.constants`

This also will allow overwriting `CMS_DEFAULT_X_FRAME_OPTIONS` in settings to look more explicit:

    CMS_DEFAULT_X_FRAME_OPTIONS = cms.constants.X_FRAME_OPTIONS_SAMEORIGIN

instead of

    CMS_DEFAULT_X_FRAME_OPTIONS = 2

Who will know what `2` means?

I can prepare a Pull Request but let me know which variant you prefer.

**Comment by czpython** [comment]
@vstoykov Thanks.

I agree that moving those definitions to ``cms.constants`` is the way to go.
So 👍  from me.
