### ISSUE TITLE
make django-cms play nice with django-multisite

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#5185]
[django-multisite](https://github.com/ecometrica/django-multisite) is an app that makes it possible to run multiple different domains mapped to different ``django.contrib.sites.Site`` with one django process.

It does this through a middleware that dynamically sets ``settings.SITE_ID``.

``cms.urls`` fetches the list of Apphooks at import time and then caches the result in the ``urls.py`` module. This is a problem when the ``SITE_ID`` changes in a later request.

Current workaround:
- create a copy of ``cms.urls`` once per site
- copy your root urls.py once per site. in it replace the url import for ``cms.urls`` with the copy.
- add a custom middleware that sets ``request.urlconf`` and applyies ``set_urlconf()`` per domain

- [ ] make a pr for django-multisite for a default implementation of the root_urlconf setting
- [ ] make django-cms not rely on ``SITE_ID`` at import time. instead it should use the threadlocal site made available by ``set_urlconf()``
- [ ] make ``cms.middleware.utils.ApphookReloadMiddleware`` work as expected with multiple root urls

**Comment by bartmika** [comment]
This is a great idea! What is the status of this?

**Comment by FinalAngel** [comment]
@bartmika I'm not sure if anyone is currently working on it. @stefanfoulis how does it look on your end?

**Comment by rodolfomartinez** [comment]
@bartmika @FinalAngel I have a great interest in this. I think this would be a godsend considering that my WordPress multisites seem to break anytime there is a major WP update, theme update, or when it just plain feels like it. Massive +1

**Comment by yakky** [comment]
Based on preliminary work from Stefan we have a live website using django muktisite, I think I can take care of this

**Comment by bartmika** [comment]
Thank you @yakky @stefanfoulis @FinalAngel, this could provide a tremendous benefit for Django-CMS users who already manage a couple Django-CMS sites looking to centralize all the separate prod servers into a single prod server.

**Comment by stefanfoulis** [comment]
@yakky that would be awesome :-) Let me know if you need any info from me about the workaround.

**Comment by rodolfomartinez** [comment]
@stefanfoulis any updates? I would love to see this come together, and I know that I'm not the only one :-)

**Comment by yakky** [comment]
@rodolfomartinez I should be able to push the middleware with a working setup and some rough docs in the next couple of days

**Comment by yakky** [comment]
@rodolfomartinez have a look at this https://github.com/nephila/djangocms-multisite (repo, packaging etc it's still totally to be defined)
@stefanfoulis @divio/django-cms-core do you think should stay as an addon?

**Comment by bartmika** [comment]
Great job yakky!! I'll take a look at this now.

**Comment by FinalAngel** [comment]
@yakky if it can be separate, then yes. The less in core the better :)

**Comment by yakky** [comment]
@FinalAngel agree

**Comment by FinalAngel** [comment]
closing this as we'll continue on djangocms-multisite
