### ISSUE TITLE
csrf token is incorrect or missing

### ISSUE THREAD

**Issue by Dharmik8478** [divio/django-cms#5200]
I am using cms toolbar login and it's properly working but sometimes i got "csrf token is incorrect or missing" error.

To solve that problem, now i am using csrf_exempt decorator with details view. Please also provide me any good solutions. 

currently working on django 1.9 and python 3.4

Thank you.

**Comment by czpython** [comment]
@Dharmik8478 Hello, this is most likely caused by using ``CMS_PAGE_CACHE``.
If this setting is ``True``, the entire rendered page will be cached, this means that any form inside that page will cache it's csrf token. Please confirm if this is the case.

**Comment by Dharmik8478** [comment]
Thank you to solved my problem.Now it's working fine.
