### ISSUE TITLE
CMS Toolbar - Sites dropdown

### ISSUE THREAD

**Issue by leesolway** [divio/django-cms#5219]
When there is a large number of sites within the sites framework, the CMS toolbar starts glitching up and down when hovering over the sites dropdown menu.

**Comment by FinalAngel** [comment]
@leesolway thanks for the report. Would you be able to provide a screencast to evaluate?

**Comment by evildmp** [comment]
@leesolway Hi, we're interested in this because good interaction with the sites framework is something we're planning to look at, but we need more information.

For example, how many is "large"? What browser are you using? And could we have a screencast or screenshot please? Thanks.

**Comment by leesolway** [comment]
I will try and mock something tonight to showcase the issue. It shouldn't be hard to replicate.

**Comment by evildmp** [comment]
@leesolway Hello, do you have any more information for us? Thanks.

**Comment by vxsx** [comment]
@leesolway it might be that the problem manifests in content mode when you open a menu that is longer than the screen height. if that's the case, could you check if https://github.com/divio/django-cms/pull/5288 fixes the problem for you?

**Comment by leesolway** [comment]
@vxsx Nice! That seems to fix the issue.
