### ISSUE TITLE
django-cms 3.2.4 wheel file seems corrupted

### ISSUE THREAD

**Issue by timgraham** [divio/django-cms#5220]
When I `pip install django-cms==3.2.4` the resulting package shows migrations 0-69 (south style) and pyc files. It looks like it wasn't packaged correctly.

**Comment by jsma** [comment]
I'm getting similar issues after upgrading to 3.2.4. `./manage.py migrate` tries to run South-style migrations and throws errors since south isn't installed.

**Comment by FinalAngel** [comment]
@divio/django-cms-core can someone confirm / check?

**Comment by intellectronica** [comment]
@FinalAngel confirmed

**Comment by FinalAngel** [comment]
@timgraham @jsma there were some issues on the uploaded PyPi releases, mainly the migrations got mixed up from switching branches. We therefore released **django CMS 3.2.5** with the correct packages.

Can you confirm that this solves the problems for you? We're very sorry for the inconvenience.

**Comment by mbi** [comment]
Confirmed fixed, thank you! :+1:

**Comment by evildmp** [comment]
Thanks @mbi for the confirmation.

**Comment by timgraham** [comment]
Thanks.

**Comment by monnikje** [comment]
I'm now getting similar issues with 3.2.5 when running manage.py migrate:

File "/home/monnikje/projects/myvac/venv/local/lib/python2.7/site-packages/easy_thumbnails/south_migrations/0013_auto__del_storage__del_field_source_storage__del_field_thumbnail_stora.py", line 4, in <module>
    from south.db import db
ImportError: No module named south.db

**Comment by FinalAngel** [comment]
@monnikje can you check "pip freeze" if you are actually using 3.2.5?

**Comment by monnikje** [comment]
cmsplugin-filer==1.0.1
Django==1.9.6
django-appconf==1.0.2
django-ckeditor==5.0.3
django-classy-tags==0.7.2
django-cms==3.2.5
django-filer==1.2.0
django-formtools==1.0
django-mptt==0.8.4
django-polymorphic==0.8.1
django-reversion==1.10.2
django-sekizai==0.9.0
django-treebeard==4.0.1
djangocms-admin-style==1.1.1
easy-thumbnails==2.3
html5lib==0.9999999
Pillow==3.2.0
six==1.10.0
Unidecode==0.4.19

**Comment by monnikje** [comment]
Ow, and this is a fresh 3.2.5 install, not an upgrade from a previous version.

**Comment by monnikje** [comment]
Ok, it was Django 1.9.6 causing this trouble. When I installed django-cms 3.2.5, Django 1.9.6 was automatically installed. When I downgraded to 1.8.7 the ./manage.py migrate worked.

**Comment by FinalAngel** [comment]
👍 @divio/django-cms-core are we aware of an issue with Django 1.9.6?

**Comment by yakky** [comment]
@monnikje @FinalAngel nope.
@monnikje how about django 1.9.5? I'm not aware of anything that can trigger importing the south migrations from easy thumbnails

**Comment by bertini36** [comment]
Sorry but I have de same issue (relation "cms_urlconfrevision" does not exist) with Django 1.8.12 and django-cms 3.2.5. In django_migrations db table I can see that the migrations have been applied (from 0001_initial to 0014_auto_20160404_1908)...

**Comment by czpython** [comment]
@bertini36 
Hello,
Is this on a fresh project? Or did you upgrade an existing project to Django 1.8?

**Comment by bertini36** [comment]
Hi!
I upgrade an existing project to Django 1.8

**Comment by czpython** [comment]
@bertini36 
How did you run the migrations on upgrade?
Did you use ``--fake``?

**Comment by bertini36** [comment]
I tried several things but the last thing I tried was migrate --fake without cms plugins in installed apps and later migrate with cms plugins in installed apps.

**Comment by czpython** [comment]
@bertini36 
Running --fake caused the cms not to run the migration that creates the cms_urlconfrevision relationship.
When migrating to Django 1.8 it's important to look at your current migration state, then fake the cms (and other apps) migrations to reach that point in django migration state and then proceed with the migration.
