### ISSUE TITLE
relation "cms_urlconfrevision" does not exist.

### ISSUE THREAD

**Issue by optimum-web** [divio/django-cms#5222]
I am trying to install django cms and get the following error. Installation was fine some days ago.

Ubuntu 14.04
Installation script: 
pip install https://github.com/nephila/djangocms-installer/archive/master.zip
Http server:  Nginx + uwsgi 
Db server: PostgreSQL 9.3.12
Python 2.7.6

ProgrammingError at /
relation "cms_urlconfrevision" does not exist
LINE 1: ...sion"."id", "cms_urlconfrevision"."revision" FROM "cms_urlco...
                                                             ^
Request Method:	GET
Request URL:	http://example.com/
Django Version:	1.8.12
Exception Type:	ProgrammingError
Exception Value:	
relation "cms_urlconfrevision" does not exist
LINE 1: ...sion"."id", "cms_urlconfrevision"."revision" FROM "cms_urlco...
                                                             ^
Exception Location:	/home/vagrant/env/local/lib/python2.7/site-packages/django/db/backends/utils.py in execute, line 64
Python Executable:	/home/vagrant/env/bin/uwsgi
Python Version:	2.7.6
Python Path:	
['/home/vagrant/projects/',
 '.',
 '',
 '/home/vagrant/env/lib/python2.7',
 '/home/vagrant/env/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/vagrant/env/lib/python2.7/lib-tk',
 '/home/vagrant/env/lib/python2.7/lib-old',
 '/home/vagrant/env/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/vagrant/env/local/lib/python2.7/site-packages']
Server time:	Wed, 27 Apr 2016 07:01:46 +0000

**Comment by FinalAngel** [comment]
@optimum-web can you try again? this might be related to https://github.com/divio/django-cms/issues/5220

**Comment by evildmp** [comment]
@optimum-web pretty sure it is.

**Comment by optimum-web** [comment]
It worked, thanks !

**Comment by FinalAngel** [comment]
thank you for confirming @optimum-web
