### ISSUE TITLE
How we dump data and load data in django cms version 3.2.3

### ISSUE THREAD

**Issue by kartikdanidhariya** [divio/django-cms#5227]
hi,
i setup django-cms in my local system with following version 
django == 1.8.10
dajngo-cms == 3.2.3

after i setup all pages in local system
now i want to deploy my site on webfactiona server 
for that i setup everything and use dumpdata in json format and load them in web faction server
i dump all data using following command
>>python manage.py dumpdata > db.json

after transfer that json file in webfaction server give following command
>>python manage.py loaddata db.json

so it give error like
"raise Value error("No Json object could be decoded") django.core.serializes.base.Depersonalization: Problem installing fixture :no Json Object could be decoded"

after i validate json file in online json validator and check but not an issue in json file
after that i create another file and try to load data but it gives same errros

and then i try dumpdata with individual app and load them in database
for that i give following command

./manage.py dumpdata cms djangocms_column djangocms_file djangocms_flash djangocms_googlemap djangocms_inherit djangocms_link djangocms_picture djangocms_style djangocms_teaser djangocms_text_ckeditor djangocms_video > db.json

but it return error like "djangocms_column is invalid app" 

so i try to dump only cms app

./manage.py cms > db.json

and load them in webfactional server but still it return same error like 
"raise Value error("No Json object could be decoded") django.core.serializes.base.Depersonalization: Problem installing fixture :no Json Object could be decoded"

please guide for dump data from local system and load them in webfactional server

**Comment by evildmp** [comment]
Hi, I don't think is really a django CMS issue, but a more general Django issue.

I made a couple of suggestions at https://groups.google.com/forum/#!msg/django-cms/CEvi5izGOBg/v_uTuC8RBgAJ.

I'm closing this here as out-of-scope, but if you find some reason to think this is specific to django CMS< please feel free to re-open.
