### ISSUE TITLE
Page recovery not working

### ISSUE THREAD

**Issue by petrklus** [divio/django-cms#5237]
I am having issues with page recovery on our test setup.

The error log is following:

http://dpaste.com/1TDNT4A

Everything else seems to be working fine, however, the page recovery does not seem to be working well. I have also encountered foreign constraint errors when running on MySQL:

    (1452, 'Cannot add or update a child row: a foreign key constraint fails (`cnk_ft1_28_cms`.`cms_cmsplugin`, CONSTRAINT `cms_cmsplugin_parent_id_3227a3752b89b923_fk_cms_cmsplugin_id` FOREIGN KEY (`parent_id`) REFERENCES `cms_cmsplugin` (`id`))')

http://dpaste.com/2MF3SFQ

I believe that both are the same problem - any ideas?

**Comment by FinalAngel** [comment]
@petrklus thanks for the report. Would you be able to re-upload the dpaste as it seemed expired?

**Comment by petrklus** [comment]
Sorry for that! This one should be corresponding to the first error:

https://gist.github.com/petrklus/6e169b9af1b2b61d35197127c9a6d287

**Comment by FinalAngel** [comment]
@czpython or @mkoistinen seems like you are the person best to help :)

**Comment by petrklus** [comment]
@FinalAngel do you still need further info on this?

**Comment by FinalAngel** [comment]
@petrklus I think we need @divio/django-cms-core to help out debugging.

**Comment by petrklus** [comment]
I think I am hitting similar/related problem with plugin recovery - at the moment, it put the CMS into a state that I could only create page duplicate + delete the old one, otherwise it was not possible to publish it. Will keep investigating but this is becoming serious.

**Comment by petrklus** [comment]
@FinalAngel can you point me to somebody I can debug it with? I have now found out that this affects many more parts of the system - it stops the UNDO functionality and results into broken pages when any history function is used.

The errors are all similar to this:

    (1452, 'Cannot add or update a child row: a foreign key constraint fails (`cnk_ft1_28_cms`.`djangocms_text_ckeditor_text`, CONSTRAINT `djangocms__cmsplugin_ptr_id_5cfb7ff7d38a35c0_fk_cms_cmsplugin_id` FOREIGN KEY (`cmsplugin_ptr_id`) REFERENCES `cms_cmsplugin` (`id`)')
    (1452, 'Cannot add or update a child row: a foreign key constraint fails (`cnk_ft1_28_cms`.`cnk_ft158_cmsplugins_headingwithcta`, CONSTRAINT `cnk_ft158__cmsplugin_ptr_id_75569871ba50d115_fk_cms_cmsplugin_id` FOREIGN KEY (`cmsplugin_ptr_id`) REFERENCES `cms_cmsplugin)')
    (1452, 'Cannot add or update a child row: a foreign key constraint fails (`cnk_ft1_28_cms`.`cms_cmsplugin`, CONSTRAINT `cms_cmsplugin_parent_id_3227a3752b89b923_fk_cms_cmsplugin_id` FOREIGN KEY (`parent_id`) REFERENCES `cms_cmsplugin` (`id`))')
    (1452, 'Cannot add or update a child row: a foreign key constraint fails (`cnk_ft1_28_cms`.`cnk_ft158_cmsplugins_contentsection`, CONSTRAINT `cnk_ft158__cmsplugin_ptr_id_1c07bdb0e1230193_fk_cms_cmsplugin_id` FOREIGN KEY (`cmsplugin_ptr_id`) REFERENCES `cms_cmsplugin)')
    (1452, 'Cannot add or update a child row: a foreign key constraint fails (`cnk_ft1_28_cms`.`djangocms_text_ckeditor_text`, CONSTRAINT `djangocms__cmsplugin_ptr_id_5cfb7ff7d38a35c0_fk_cms_cmsplugin_id` FOREIGN KEY (`cmsplugin_ptr_id`) REFERENCES `cms_cmsplugin` (`id`)')
    (1452, 'Cannot add or update a child row: a foreign key constraint fails (`cnk_ft1_28_cms`.`cnk_ft158_cmsplugins_linkbutton`, CONSTRAINT `f032531d13a8edf3329479dfc5945abc` FOREIGN KEY (`link_ptr_id`) REFERENCES `djangocms_link_link` (`cmsplugin_ptr_id`))')
    (1452, 'Cannot add or update a child row: a foreign key constraint fails (`cnk_ft1_28_cms`.`cnk_ft158_cmsplugins_linkbutton`, CONSTRAINT `f032531d13a8edf3329479dfc5945abc` FOREIGN KEY (`link_ptr_id`) REFERENCES `djangocms_link_link` (`cmsplugin_ptr_id`))')
    (1452, 'Cannot add or update a child row: a foreign key constraint fails (`cnk_ft1_28_cms`.`cnk_ft158_cmsplugins_linkbutton`, CONSTRAINT `f032531d13a8edf3329479dfc5945abc` FOREIGN KEY (`link_ptr_id`) REFERENCES `djangocms_link_link` (`cmsplugin_ptr_id`))')

I have generated the above by adding comments to the reversion's models.py.

**Comment by czpython** [comment]
@petrklus Hello, thanks for the detailed report.

I saw you posted this gist https://gist.github.com/petrklus/6e169b9af1b2b61d35197127c9a6d287 and also provided the sql errors.

Are both of these happening on a single occurrence of restoring? Or are they isolated incidents?

Also are you able to reproduce this consistently on any cms page with plugins?
Last, do any of your custom plugins subclass another plugin? (multi-table inheritance)?

**Comment by petrklus** [comment]
Thank you @czpython  - I am using Django CMS 3.2.3 on Django 1.8.9, same problem on both reversion 1.8.7 and 1.10.2.

**Comment by petrklus** [comment]
@czpython further observation - it seems to be affecting "older" pages only though, I can easily reproduce it on existing content but if I try to do the same operation on newly created page, all works fine.

**Comment by petrklus** [comment]
@czpython same behaviour on old pages even after performing deleterevisions

**Comment by petrklus** [comment]
Also, here are my full installed packages: https://gist.github.com/petrklus/f379c10a1d358ebc2c0d1e8491f2b326

**Comment by petrklus** [comment]
@czpython I would really appreciate any immediate tips how to mitigate in the meantime - in the current state, any undo/history related action can require re-creation of a page (and any links to it as well), which is quite a big problem

**Comment by petrklus** [comment]
@czpython and yes - I do have models inheriting other models (for example, I have built a few extensions to the Link class)

**Comment by czpython** [comment]
@petrklus This extension to the Link class, does it use the AbstractLink class or is it inheriting the Link plugin directly?

Is this the only case where you're inheriting a plugin model class?

I ask because this is actually not supported by Django CMS and will cause many types of issues, including a reversion corruption for any version that contains data for these plugins.

**Comment by petrklus** [comment]
One example would be here:

    class CaseStudyLink(Link):        
    
        tile_title = models.CharField(
            _('Label'), max_length=500, default="Case Study", blank=False)  
    
        description = models.TextField(
            _('Description text'), blank=True)
    
    
        casestudy_image = FilerImageField(null=True, blank=True,
                                   related_name="casestudy_block_image")


Could that be the source of all problems? If so, what would be the best way to migrate all of the content?

**Comment by petrklus** [comment]
My suggestion is following:

class LinkMixin(models.Model):
    ... link fields here ...
    class Meta:
        abstract = True

class FeatureLink(LinkMixin, CMSPlugin):            
    icon = models.CharField(
        _('Icon'), max_length=500, choices=FEATURE_ICONS, blank=False)
    .. additional methods etc...


Which works, however, it results in a warning:

/python2.7/site-packages/django/db/models/base.py:309: RuntimeWarning: Model 'cnk_ft158_cmsplugins.featurelink' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.

Which then results in a following migration: https://gist.github.com/petrklus/7f0dcfbd758739fd73a81cef4b3b2718

**Comment by petrklus** [comment]
@czpython would there be a merit in extending the cms check function to detect such situations?

**Comment by czpython** [comment]
@petrklus Sadly yes this is most likely the source of all issues.
I've encountered this exact problem before (with the link plugin 😞 ).
The link plugin already has an abstract link class for this reason, I suggest using that one.
Let me know if you need instructions on how to migrate the content.

Adding this to the CMS check is a good idea, maybe create an issue for this separately?

**Comment by petrklus** [comment]
@czpython I thought as much! what would you recommend as a course of action for migration? Also, what do you suggest as preferred "mixin" behaviour - would something like this work?

    class FeatureLink(CMSPlugin, LinkMixin): 

When I use the usual python way of having the mixins first, I get error messages (as per above). Furthermore, is it even possible to use CMSPlugin with other mixins, or is this a no-no as well?

**Comment by czpython** [comment]
@petrklus I recommend using the abstract class https://github.com/divio/djangocms-link/blob/master/djangocms_link/models.py#L14. If you need to use your own mixin though, then do so as an abstract class like so:

```python
class LinkMixin(CMSPlugin):
    ... link fields here ...
    class Meta:
        abstract = True

class FeatureLink(LinkMixin):            
    icon = models.CharField(
        _('Icon'), max_length=500, choices=FEATURE_ICONS, blank=False)
    .. additional methods etc...
```

Regarding the migration, it's quite complex. I will update you on it in a few hours as I'm AFK for now.

**Comment by petrklus** [comment]
Thank you @czpython!

What I am looking at is following:

    class LinkMixin(models.Model):
        ... link fields here ...
        class Meta:
            abstract = True

    class SEOOptionsMixin(models.Model):
        ... extra fields fields here ...
        class Meta:
            abstract = True


    class Button(CMSPlugin, LinkMixin):            
        variation = models.CharField(
            _('variation'), max_length=500, choices=BUTTON_VARIATIONS, blank=False)

        .. additional methods etc...

    class FeatureLink(CMSPlugin, LinkMixin, SEOOptionsMixin):            
        icon = models.CharField(
            _('Icon'), max_length=500, choices=FEATURE_ICONS, blank=False)
        .. additional methods etc...

Looking at your code, how would I accommodate for multiple mixins? Also, what about subclasses of CMSPlugin and their further subclassing? Found a warning in https://github.com/divio/django-cms/blob/develop/cms/models/pluginmodel.py#L72

**Comment by czpython** [comment]
@petrklus It's ok to subclass a model that subclasses CMSPlugin as long as the model is abstract.

Regarding the migration:

The moment you remove the ``Link`` subclass it will remove the ``link_ptr`` field which currently is your primary key and thus everything will break (as shown in your [gist](https://gist.github.com/petrklus/7f0dcfbd758739fd73a81cef4b3b2718#file-gistfile1-txt-L18). To avoid this, you need to do the migration in multiple steps.

**Disclaimer**: The steps below work on postgres with Django 1.6 and South migrations.

* Remove the Link subclass and then subclass your mixins.
* Add a field to the model called link_ptr which should have all attributes of the one that was created automatically by Django. This means something like:

``link_ptr = models.OneToOne(to=Link, unique=True, primary_key=True)``

You do this to keep your primary key values until you can migrate out of them.

* Add a field to the model called ``cmsplugin_ptr``. This is because this field is created automatically when you subclass CMSPlugin but we don't want Django to create it automatically because it would try to create it as a primary key and we already have one (for now).

``cmsplugin_ptr = models.OneToOne(to=CMSPlugin, unique=True, null=True, parent_link=True)``

You need to set the null=True because this is a new column (unlike link_ptr) and so you won't have a value for it yet. On postgres this works fine with unique, not sure how it would behave on mysql.

* Now create a migration, the migration should add all the fields from your mixin to your custom link table as well as the ``cmsplugin_ptr field``. No changes should be recorded for the ``link_ptr`` field.

* Create a datamigration that will pass all values for ``link_ptr`` to ``cmsplugin_ptr``.
Like so (taken from a south migration, adjust for Django):

```python
        links = orm.YourLinkModel.objects.all()

        for link in links:
            link.cmsplugin_ptr_id = link.link_ptr_id
            link.save(update_fields=['cmsplugin_ptr'])
```

* Modify your link model once more and set ``primary_key`` to ``False`` on the ``link_ptr`` field, then remove your cmsplugin_ptr field (because we can now use the automatic one).
* Create an automatic migration for the changes above.
* Modify your link model once more and set ``link_ptr`` to be ``null=True``
* Create automatic migration for the changes above.
* Create a data migration to migrate content from the link table to your custom link table.
Like so

```python
link_attributes = [
        'name',
        'url',
        'anchor',
        'mailto',
        'phone',
        'target',
]
links = orm.YourLinkModel.objects.all()

for link in links:
    cms_link = link.link_ptr
    # get link data
    attributes = {attr: getattr(cms_link, attr) for attr in link_attributes}
    # set old link_ptr relationship to null
    attributes['link_ptr'] = None
    attributes['page_link'] = cms_link.page_link_id
    # update extended link with link data
    links.filter(pk=link.pk).update(**attributes)
    # delete old Link record
    cms_link.delete()
```

* Delete the ``link_ptr`` field.
* Last create an automatic migration for the delete above.

**Comment by petrklus** [comment]
@czpython thank you very much for the exhaustive tutorial - I will test everything thoroughly on a staging setup before flipping the final switch. 

One more question - does the below make sense as the new class definition?

```python
class FeatureLink(CMSPlugin, LinkMixin, SEOOptionsMixin):            
```

The full code can be seen in my post above. Or shall I stick to usual python notation? What are the pros/cons of each? My guess would be that the CMSPlugin should be first. Also, will suggest some documentation enhancements to cover this as I imagine I am not the only one having these issues!

**Comment by czpython** [comment]
@petrklus I've not run into this issue with subclassing, my guess is that when dealing with multi-table inheritance, Django needs the first model to be the concrete one (CMSPlugin). The rest can then be abstract.
