### ISSUE TITLE
Integrity Error on page publish

### ISSUE THREAD

**Issue by petrklus** [divio/django-cms#5246]
I am seeing following messages in our Sentry log:

    IntegrityError: (1062, "Duplicate entry '01I2' for key 'cms_cmsplugin_path_7692c19a7d5df9d5_uniq'")
    (27 additional frame(s) were not displayed)
    ...
      File "cms/models/pluginmodel.py", line 246, in save
        self.add_root(instance=self)
      File "treebeard/mp_tree.py", line 593, in add_root
        return MP_AddRootHandler(cls, **kwargs).process()
      File "treebeard/mp_tree.py", line 317, in process
        newobj.save()
      File "cms/models/pluginmodel.py", line 248, in save
        super(CMSPlugin, self).save(*args, **kwargs)
      File "cnk_ft1_cms/deadlock_fix.py", line 16, in execute_wrapper
        return original(*args, **kwargs)

I think that users just click again on the "publish" button which fixes it, however, I would like to get to the bottom of this.

The request URL where the error happened is /en-gb/admin/cms/page/78/en-gb/publish/

The deadlock_fix is a simple patch to mitigate some of the MySQL locking behaviour (https://gist.github.com/petrklus/3c636e595fb5505765bfaac9bd2b6ca1). The same issue was present even before implementation of the deadlock_fix.

Any advice what the issue may be?

I am using Django 1.8 with MySQL (running on AWS Elastic Beanstalk + RDS MySQL 5.6).

**Comment by petrklus** [comment]
Another example:

    IntegrityError: (1062, "Duplicate entry '00X8' for key 'cms_cmsplugin_path_7692c19a7d5df9d5_uniq'")
    (28 additional frame(s) were not displayed)
    ...
      File "cms/models/pluginmodel.py", line 246, in save
        self.add_root(instance=self)
      File "treebeard/mp_tree.py", line 593, in add_root
        return MP_AddRootHandler(cls, **kwargs).process()
      File "treebeard/mp_tree.py", line 317, in process
        newobj.save()
      File "cms/models/pluginmodel.py", line 248, in save
        super(CMSPlugin, self).save(*args, **kwargs)
      File "cnk_ft1_cms/deadlock_fix.py", line 15, in execute_wrapper
        return original(*args, **kwargs)

**Comment by FinalAngel** [comment]
@czpython any feedback here from your end?

**Comment by czpython** [comment]
@petrklus Is this project a fresh install? or was it upgraded from earlier cms versions?
Please provide the Django CMS version and Django version used.

**Comment by petrklus** [comment]
@czpython It has always been on 3.x - not sure if all the time on 3.2 though. Django 1.8.x always, and I have tried upgrading to latest reversion in hope to fix the issue - but behaves exactly the same.

Django CMS 3.2.3 on Django 1.8.9

**Comment by petrklus** [comment]
If I may divert your attention though @czpython , please see other issue I am having - https://github.com/divio/django-cms/issues/5237

**Comment by czpython** [comment]
@petrklus please note that Django CMS 3.2.3 has some serious issues with page corruptions.
I highly advice moving to the latest 3.2.x release.

**Comment by czpython** [comment]
Hey, are you able to consistently reproduce this still?

Please provide some info:
Is this the first time this page is published?
Do you know if anyone else was making changes to this or other pages around the time you published?

This is not a page tree corruption, instead it's a plugin tree one.
