### ISSUE TITLE
Redirect functionality in Advanced Settings for Pages should allow external URLs

### ISSUE THREAD

**Issue by macolo** [divio/django-cms#5247]
The redirect field on the Advanced Settings for Pages should allow external URLs like `https://www.google.com``

![image](https://cloud.githubusercontent.com/assets/4056979/15020662/5427439c-1223-11e6-8c0b-cd1afd3a1176.png)

Alternatively, a custom page type 'external url' or 'shortcut' would also be a viable solution. 

Is there a workaround for this missing functionality?

**Comment by vxsx** [comment]
It does allow external URLs.

<img width="420" alt="screen shot 2016-05-05 at 08 30 15" src="https://cloud.githubusercontent.com/assets/366813/15037454/b0e154e2-129b-11e6-8bc9-b2a686f5b9a8.png">
<img width="512" alt="screen shot 2016-05-05 at 08 30 24" src="https://cloud.githubusercontent.com/assets/366813/15037455/b0e4096c-129b-11e6-95db-e4ba7593ce0c.png">

**Comment by macolo** [comment]
Indeed! I haven't noticed that this field is not limited to the options. Many thanks @vxsx !
