### ISSUE TITLE
CSRF verification failed

### ISSUE THREAD

**Issue by farooqaaa** [divio/django-cms#5248]
I am using django-cms 3.2.3 stable version. I have a form on my homepage that uses CSRF. It fails on the first visit to the website. It works if you visit any other page and come back to homepage. If I check cookies, the csrftoken cookie is set and the form field is also set but when I submit the form it fails.

At random times, it works even on the first visit to the page. It's really strange.

**Comment by farooqaaa** [comment]
I just noticed something else. The token in cookie is different than the one in the form.

**Comment by czpython** [comment]
@farooqaaa This looks like it's caching related.
Most likely your form on the homepage is part of a plugin that's cached, please verify.

**Comment by farooqaaa** [comment]
It doesn't use any plugin but setting **CMS_PAGE_CACHE** to false in settings fixed the problem. Thank you.
