### ISSUE TITLE
Database lock timeouts with MySQL

### ISSUE THREAD

**Issue by petrklus** [divio/django-cms#5249]
While monitoring our Sentry logs, I have noticed a few locking issues in the list:

```
OperationalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')
(20 additional frame(s) were not displayed)
...
  File "cms/models/pagemodel.py", line 506, in save
    super(Page, self).save(**kwargs)
  File "cms/models/pagemodel.py", line 521, in save_base
    return super(Page, self).save_base(*args, **kwargs)
  File "cms/signals/page.py", line 21, in pre_save_page
    menu_pool.clear(instance.site_id)
  File "menus/menu_pool.py", line 160, in clear
    cache_keys.delete()
  File "cnk_ft1_cms/deadlock_fix.py", line 19, in execute_wrapper
    raise e
```

The deadlock_fix my attempto to mitigate the issue (https://gist.github.com/petrklus/3c636e595fb5505765bfaac9bd2b6ca1).

I am running MySQL 5.6 on Amazon RDS (dedicated instance). The issues above are not happening under any heavy load - a single user editing the site is easily capable of producing such errors.

Are there any specific MySQL tweaks that need to be in place?

**Comment by czpython** [comment]
@petrklus do all tracebacks point to the cache keys? Please specify which action was the user taking?

**Comment by petrklus** [comment]
@czpython , yes they are all almost identical. This is happening during page publishing.

**Comment by czpython** [comment]
I think this is related to the amount of cache keys that might be in the db.
@petrklus are you able to reproduce the error still?

**Comment by petrklus** [comment]
@czpython We have migrated all our production Django CMS operations to Divio cloud.. and not seeing this anymore as a result.

**Comment by czpython** [comment]
Closing for new report https://github.com/divio/django-cms/issues/6298
