### ISSUE TITLE
apphook docs talk about mptt

### ISSUE THREAD

**Issue by Eraldo** [divio/django-cms#5250]
The apphook docs talk about mptt: http://docs.django-cms.org/en/develop/how_to/apphooks.html
Does that make sense? As I understood it, the project does not use mptt anymore.

**Comment by yakky** [comment]
Well that's actually an example on how to create a category model which happens to use mptt. It's not related to the cms itself. But I agree that we can better move the example to treebeard

**Comment by Eraldo** [comment]
Oh sure.. just saw that now. Thanks for the clarification. This issue is fixed. :)

**Comment by FinalAngel** [comment]
AFAIK @evildmp is working on some additional clarifications there.
