### ISSUE TITLE
Sometimes there is more than one clipboard

### ISSUE THREAD

**Issue by jrief** [divio/django-cms#5257]
When copying plugins from a placeholder to the clipboard, the database sometimes contains two ``Placeholder`` objects with ``slug='clipboard'``. The first one has a primary key of ``1``, while the second one can have any arbitrary number.
Normally the copied plugins are added to the last (second) clipboard instance, but I can not rely on this.

Why do we need two different clipboards, if we then can't distinguish them from each other? Is this a bug or an intentional feature?

Update:
By reading the CMS code, I just found out that there is a class named ``PlaceholderReference``. Via its foreign key ``placeholder_ref`` I can access the current clipboard. But how many instances of PlaceholderReference do exist in a project?

**Comment by mkoistinen** [comment]
The CMS used to support multiple clipboards. It should only support one now. Do you have a set of steps that can reproduce this issue?

**Comment by FinalAngel** [comment]
Hello, please submit only bug reports to GitHub issues. Feature requests for django CMS should be submitted to the django CMS developers [mailing list](https://groups.google.com/forum/#!forum/django-cms-developers) for discussion first. Afterwards a Pull Request should be submitted.

You can find additional information on our [support](https://django-cms.org/support) page.

**Comment by jrief** [comment]
Well, relying on having only one item in the clipboard is not a feature request, but (at least in my opinion) a bug. Unless djangoCMS intentionally want's to support such a feature.
I'll try to reproduce it, though.

**Comment by czpython** [comment]
@jrief Agree, it's a bug. Please try to reproduce on latest (3.3.1) though.
