### ISSUE TITLE
Visualise page publish action

### ISSUE THREAD

**Issue by petrklus** [divio/django-cms#5259]
In some events in the CMS, a spinning cog is visible in the top-right corner. However, this does not seem to be the case for page publication. 

The fact that page publication is under-way in the background should be visible to the user, letting them know that the action was indeed submitted.

**Comment by FinalAngel** [comment]
@vxsx did we fix that already for 3.3?

**Comment by vxsx** [comment]
not yet, but soon @FinalAngel
