### ISSUE TITLE
Adding template choices makes Django create new migrations

### ISSUE THREAD

**Issue by lunanoko** [divio/django-cms#5280]
Every time I add a new template choice to the `CMS_TEMPLATES` setting, Django sees this as a model change that requires a new migration. This migration is then created in the cms app folder which is completely out of my control.

I raised this as an issue in Django's IRC, but apparently this is expected behaviour and as such, this issue has to be fixed by third-party developers having this issue.

I expect this can be solved by having the template choices generated by a function which in turn uses the `CMS_TEMPLATES` setting to generate the choice list, but as I'm not entirely sure of what is causing this issue, this is merely a guess.

**Comment by czpython** [comment]
@lunanoko 
I believe this was fixed on 3.3
