### ISSUE TITLE
Dependency install has completely unhelpful error, no relevant pip output is shown (while it should be!)

### ISSUE THREAD

**Issue by JonasT** [divio/django-cms#5283]
The dependency install appears to have a completely unhelpful error if anything goes wrong:
the pip command is shown and then the useless information that "exit code 1" was returned:

```
root@3184124143eb:/djangocms# djangocms -f -q -p jonasch jonasch
--config-file djangocms-installer.conf
Creating the project
Please wait while I install dependencies
The installation failed.
Removing everything under /djangocms/jonasch


**********************************************************

Check documentation at http://djangocms-installer.rtfd.org

**********************************************************

Traceback (most recent call last):
  File "/usr/local/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File
"/usr/local/lib/python2.7/dist-packages/djangocms_installer/main.py",
line 33, in execute
    verbose=config_data.verbose
  File
"/usr/local/lib/python2.7/dist-packages/djangocms_installer/install/__init__.py",
line 93, in requirements
    output = subprocess.check_output(['pip'] + args)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'pip', u'install', u'-q',
u'django-cms<3.3', u'django-treebeard>=2.0', u'mysqlclient',
u'https://github.com/divio/djangocms-column/archive/master.zip?1463065854.65',
u'https://github.com/divio/djangocms-googlemap/archive/master.zip?1463065854.65',
u'https://github.com/divio/djangocms-inherit/archive/master.zip?1463065854.65',
u'https://github.com/divio/djangocms-link/archive/master.zip?1463065854.65',
u'https://github.com/divio/djangocms-style/archive/master.zip?1463065854.65',
u'easy_thumbnails', u'django-filer>=0.9.12', u'cmsplugin-filer>=0.10.2',
u'djangocms-admin-style>=1.0.6', u'djangocms-text-ckeditor>=2.8.1',
u'Django<1.9', u'pytz', u'django-reversion>=1.8.7,<1.9',
u'django-mptt<0.9', u'django-classy-tags>=0.3.4.1', u'html5lib',
u'Pillow>=2.3', u'django-sekizai>=0.7', u'six']' returned non-zero exit
status 1
```

What I would expect instead as a user is either the full pip output attached. (The output is contained in the .output member of the subprocess.CalledProcessError instance, so it shouldn't be that hard to do - simply catch the error and write proper information like the pip output to stderr, then raise the error again to propagate it up)
If you don't want to spam it to the terminal, at least a mention of some log file in the error message to read up on the full pip output would be nice.

Otherwise it is hard for me to *do something about it* and possibly fix the dependency issue which I would assume this might be. With the current error, this is only possible if I copy the whole command, painstakingly remove all the list formatting in between all parameters and run it manually just to get the actual pip output myself...

**Comment by FinalAngel** [comment]
Please submit this error to the https://github.com/nephila/djangocms-installer repository. @divio/django-cms-core any further info here?
