### ISSUE TITLE
djangocms installer fails because it has hardcoded path to /usr/bin/django-admin.py while file was installed to /usr/local/bin/django-admin.py

### ISSUE THREAD

**Issue by JonasT** [divio/django-cms#5285]
We tried to run the djangocms installer but it falls flat on its face because it appears to have a hardcoded path to /usr/bin/django-admin.py while file was actually installed to /usr/local/bin/django-admin.py.

Maybe djangocms should use the `whereis` tool or a similar approach that allows it to find it in the PATH environment variable as expected from a properly written program, instead of expecting some hardcoded path?

**Comment by yakky** [comment]
@JonasT path is not hardcoded, as djangocms-installer only supports virtualenv based installation, it requires that django-admin is in the same directory as python interpreter as documented here https://github.com/nephila/djangocms-installer#warning
