### ISSUE TITLE
Menus show last selected site instead of current site

### ISSUE THREAD

**Issue by czpython** [divio/django-cms#5310]
Create two sites:

1 - example-1.com
2 - example-2.com

Run your server with site 1 active.
Create multiple pages on site 1.
Go to the home page and verify that the pages show up in menu.

Run your server with site 2 active.
Create multiple pages on site 2.
Go to the home page and verify that the pages show up in menu.

Now while site 2 is active, switch to site one on the site selector in the admin.
Go back to the homepage and you should see the incorrect menu for site 1.

Video:

https://drive.google.com/file/d/0B9SwgyV0g1hST1ZEbl9qT2M4Mlk/view

Notice that enabling cache brings forth another problem where cache is not refreshing when switching sites.

This bug comes from a deep look at https://github.com/divio/django-cms/pull/5109

**Comment by razisayyed** [comment]
Sorry For Disturb,
But I really need to know if this bug would be fixed in the near future.
