### ISSUE TITLE
Missing slovak translations

### ISSUE THREAD

**Issue by mireq** [divio/django-cms#5334]
After commit 34a02cb36ee05c5c8fcf6e4c68ccd7f99a6beb8b slovak translations are loaded from cms/locale/sk_SK/LC_MESSAGES/django.po which contains empty translation strings instead of cms/locale/sk/LC_MESSAGES/django.po

**Comment by czpython** [comment]
@mireq 
Thanks for the report.

@mkoistinen 
Looks like when updating translations from transifex, a lot of empty sub-locale translations came in.
I believe we can just remove their respective locale folder.

**Comment by mkoistinen** [comment]
Agreed. How can we reliably and repeatably deal with this? Surely the solution is not to examine every locale to see if it is "full" or not.

**Comment by czpython** [comment]
@mkoistinen We just need to check sub-locales. There's not that many.

**Comment by czpython** [comment]
@mkoistinen 
You can remove the following locales:
https://github.com/divio/django-cms/blob/develop/cms/locale/cs_CZ
https://github.com/divio/django-cms/tree/develop/cms/locale/fi_FI/
https://github.com/divio/django-cms/blob/develop/cms/locale/is_IS/
https://github.com/divio/django-cms/tree/develop/cms/locale/ro_RO/
https://github.com/divio/django-cms/blob/develop/cms/locale/sk_SK/
https://github.com/divio/django-cms/blob/develop/cms/locale/tr_TR/

**Comment by mkoistinen** [comment]
Fixed in RC3.

**Comment by czpython** [comment]
@mireq Closing this as it's fixed on RC3.
