### ISSUE TITLE
Django admin form manytomany fields not saved. how to save

### ISSUE THREAD

**Issue by kartikdanidhariya** [divio/django-cms#5343]
I am using dango-cms ==3.2.3, django = 1.8.10

I have created models.py with many-to-many field. When I add any record in it then it is not show any warning and save record perfectly but when I open that record so it not show many-to-many selected value so I thing many-to-many field is not saved.

my models.py is

please refer this link for my models.py code

https://ghostbin.com/paste/2v7js

How can I solve this issue??

**Comment by czpython** [comment]
@kartikdanidhariya 
Hello, this looks like an issue with the multilanguage framework you're using.
Is it django-parler?

**Comment by kartikdanidhariya** [comment]
i am using django-hvad

**Comment by czpython** [comment]
@kartikdanidhariya 
Ok, mind opening a ticket in https://github.com/KristianOellegaard/django-hvad/issues?
I'll jump on there to see if I can help.

**Comment by czpython** [comment]
@kartikdanidhariya 
Seems like this is not supported on hvad (m2m fields as translatable fields).
https://github.com/KristianOellegaard/django-hvad/issues/284

**Comment by kartikdanidhariya** [comment]
i created issue in django-hvad for that
https://github.com/KristianOellegaard/django-hvad/issues/296
