### ISSUE TITLE
Missing Toolbar + Admin dropdown is missing (Administration, Pages)

### ISSUE THREAD

**Issue by khrizo** [divio/django-cms#5344]
Upgrade from 3.2.5 to 3.3.0 and toolbar is gone in the frontend, the admin is missing all the options under Django Administration , I can only see logout and change password. I have reverted back to 3.2.5 and everything works as expected. I'm not sure what could be the issue.

Thanks in advanced.

Django 1.8.3
{% load cms_tags %} and {% cms_toolbar %} are in base.html

**Comment by czpython** [comment]
@khrizo 
Hello,
Can you run `python manage.py cms check` and paste the output?

**Comment by khrizo** [comment]
********************************
Checking django CMS installation
********************************

Sekizai
=======

  - Sekizai is installed [OK]
  - Sekizai template context processor is installed [OK]
  - Sekizai namespaces 'js' and 'css' found in 'home_page.html' [OK]
  - Sekizai namespaces 'js' and 'css' found in 'page.html' [OK]
  - Sekizai namespaces 'js' and 'css' found in 'feature.html' [OK]
  - Sekizai namespaces 'js' and 'css' found in 'slider_top.html' [OK]
  - Sekizai namespaces 'js' and 'css' found in 'contact.html' [OK]
  - Sekizai namespaces 'js' and 'css' found in 'plain.html' [OK]
  - Sekizai namespaces 'js' and 'css' found in 'bmi.html' [OK]
  - Sekizai namespaces 'js' and 'css' found in 'occ_app.html' [OK]
  - Sekizai namespaces 'js' and 'css' found in 'occ_app_no_breadcrumb.html' [OK]
  - Sekizai namespaces 'js' and 'css' found in 'press.html' [OK]

Sekizai configuration okay [OK]

Internationalization
====================

  - New style CMS_LANGUAGES [OK]

Middlewares
===========


Context processors
==================


Deprecated settings
===================

  - No deprecated settings found [SKIP]

Plugin instances
================

  - Plugin instances of 24 types found in the database [OK]

The plugins in your database are in good order [OK]

Presence of "copy_relations"
============================


All plugins and page/title extensions have "copy_relations" method if needed. [OK]

Usage of deprecated placeholder_tags
====================================



OVERALL RESULTS
===============

1 checks skipped!
17 checks successful!

Installation okay

**Comment by czpython** [comment]
@khrizo 
Thanks. There's been several bugfix releases on Django 1.8, can you try using the latest 1.8 release (1.8.13)? Shouldn't have any backwards incompatibilities with 1.8.3.

**Comment by khrizo** [comment]
Thanks Paulo, I'm already in 1.8.3 :(

**Comment by czpython** [comment]
@khrizo 
Yup, but try upgrading from 1.8.3 to 1.8.13

**Comment by khrizo** [comment]
Sorry, I meant 1.8.13 - I'm already there.

**Comment by czpython** [comment]
@khrizo Can you post your settings file? (hiding any project specific stuff)

**Comment by khrizo** [comment]
`import os
gettext = lambda s: s
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

DEBUG = True

ADMINS = [('admin','email@emial.com')]
SECRET_KEY = '999999999999'
ALLOWED_HOSTS = ['']
INTERNAL_IPS = '127.0.0.1'
CMS_PLACEHOLDER_CACHE = False
ROBOTS_CACHE_TIMEOUT = 60*60*24
ZINNIA_PAGINATION = 9
ROOT_URLCONF = 'ocp.urls'
WSGI_APPLICATION = 'ocp.wsgi.application'
LANGUAGE_CODE = 'en'
TIME_ZONE = 'America/Chicago'
USE_I18N = False
USE_L10N = True
USE_TZ = True
MEDIA_URL = '/media/'
MEDIA_ROOT = '/home/lemon/public_html/ocp/public/media/'
STATIC_URL = '/static/'
STATIC_ROOT = '/home/lemon/public_html/ocp/public/static/'
CMS_SEO_FIELDS = False
SITE_ID = 1
HTML_MINIFY = True
EXCLUDE_FROM_MINIFYING = ('^admin/',)

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)


INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'djangocms_admin_style',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'djangocms_text_ckeditor',
    'djangocms_picture',
    'django_select2',
    'djangocms_file',
    'cmsplugin_cascade',
    'cmsplugin_cascade.extra_fields',
    'cmsplugin_cascade.sharable',
    'cmsplugin_forms_builder',
    'forms_builder.forms',
    'bootstrap3',
    'treebeard',
    'mptt',
    'zinnia_bootstrap',
    'zinnia',
    'djangocms-css-background',
    'adminsortable2',
    'tagging',
    'sekizai',
    'testimonial',
    'team',
    'procedure',
    'djangocms_link',
    'cms',
    'ocp',
    'robots',
    'menus',
    'easy_thumbnails',
    'filer',
    'djangocms_style',
    'positions',
    'django_comments',
    'ckeditor',
    'zinnia_ckeditor',
    'seo',
    'video',
    'press',
    'sorl.thumbnail',
    'secretballot',
    'likes',
    'meta',
    'meta_mixin',
    'djangocms_page_meta',
    'djangocms-placeholder-attr',
    'aldryn_wow',
    'djangocms_gmaps',
    'djangocms_youtube',
    'cmsplugin_gallery',
    'tinymce',
    'django_extensions',
    'newsletter',
    'subscribe',
    'djangocms_parallax',
    'compressor',
    'mathfilters',
    'photologue',
    'sortedm2m',
)


STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)
COMPRESS_ENABLED = True

CMSPLUGIN_GALLERY_TEMPLATES = (
    ('app/slider_template.html', 'Slider Gallery', ),
    ('app/grid_template.html', 'Grid Gallery', ),
)

THUMBNAIL_ALIASES = {
    '': {
        'blog_list': {'size': (1200, 600), 'crop': True},
        'blog_square': {'size': (600, 400), 'scale_and_crop': True},
        'blog_home_page': {'size': (350, 170), 'crop': True, 'quality': 60},
    },
}

MIDDLEWARE_CLASSES = (
    'django.middleware.cache.UpdateCacheMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    'djangocms_disqus.middleware.DisqusMiddleware',
    'likes.middleware.SecretBallotUserIpUseragentMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
)

TEMPLATES = [
{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [
            # insert your TEMPLATE_DIRS here
            '/home/lemon/public_html/ocp/private/ocp/templates',
            '/home/lemon/public_html/ocp/private/ocp/templates/cms_templates',
        ],
    #'APP_DIRS': True,
    'OPTIONS': {
        'debug': DEBUG,
        'context_processors':
            (
            'django.contrib.auth.context_processors.auth',
            'django.template.context_processors.debug',
            #'django.template.context_processors.i18n',
            'django.template.context_processors.media',
            'django.template.context_processors.static',
            'django.template.context_processors.tz',
            'django.template.context_processors.csrf',
            'django.template.context_processors.request',
            'django.contrib.messages.context_processors.messages',
            'sekizai.context_processors.sekizai',
            'cms.context_processors.cms_settings',
            ),
        'loaders':
            (
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
            'django.template.loaders.eggs.Loader',
            'app_namespace.Loader',
            ),
    }
},
]

CMS_LANGUAGES = {
    ## Customize this
    'default': {
        'public': True,
        'hide_untranslated': False,
        'redirect_on_fallback': True,
    },
    1: [
        {
        'public': True,
        'code': 'en',
        'hide_untranslated': False,
        'name': gettext('en'),
        'redirect_on_fallback': True,
        },
    ],
}

CMS_TEMPLATES = (
    ('home_page.html', 'Home Page'),
    ('page.html', 'Page'),
    ('feature.html', 'Page with Feature'),
    ('slider_top.html', 'Page with Top Slider'),
    ('contact.html', 'Simple Page Contact'),
    ('plain.html', 'Plain Text Pages'),
    ('bmi.html', 'BMI Calculator'),
    ('ocp_app.html', 'ocp APP'),
    ('ocp_app_no_breadcrumb.html', 'ocp APP No Breadcrumb'),
    ('press.html', 'Press Template')
)

CMS_PERMISSION = False
CMS_PLACEHOLDER_CONF = {
    'Main Content Container': {
        'plugins': ['BootstrapRowPlugin'],
    },
}

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',
    },
    'zinnia-content': {
        'toolbar_Zinnia': [
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord'],
            ['Undo', 'Redo'],
            ['Scayt'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Table', 'HorizontalRule', 'SpecialChar'],
            ['Source'],
            ['Maximize'],
            '/',
            ['Bold', 'Italic', 'Underline', 'Strike',
             'Subscript', 'Superscript', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-',
             'Outdent', 'Indent', '-', 'Blockquote'],
            ['Styles', 'Format'],
        ],
        'toolbar': 'Zinnia',
    },

    'simple_toolbar': {
        'toolbar': [
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord'],
            ['Undo', 'Redo'],
            #['Scayt'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Table', 'HorizontalRule', 'SpecialChar'],
            ['Source'],
            ['Maximize'],
            '/',
            ['Bold', 'Italic', 'Underline', 'Strike',
             'Subscript', 'Superscript', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-',
             'Outdent', 'Indent', '-', 'Blockquote'],
            ['Styles', 'Format'],
        ],
    },
}

CKEDITOR_SETTINGS = {
    'language': '{{ language }}',
    'disableNativeSpellChecker': False,
    'skin': 'moono',
    'toolbar_CMS': [
        ['Undo', 'Redo'],
        ['cmsplugins', '-', 'ShowBlocks'],
        ['Format', 'Styles'],
        ['Link', 'Unlink', 'Anchor'],
        ['Image', 'Table', 'HorizontalRule', 'SpecialChar'],
        ['Source'],
        ['Maximize'],
        ['Bold', 'Italic', 'Underline', 'Strike',
         'Subscript', 'Superscript', '-', 'RemoveFormat'],
        ['NumberedList', 'BulletedList', '-',
         'Outdent', 'Indent', '-', 'Blockquote'],
        ['Styles', 'Format'],
    ],
}

TEXT_ADDITIONAL_ATTRIBUTES = ('scrolling', 'allowfullscreen', 'frameborder')
CMS_STYLE_NAMES = (
    ('info', ("info")),
    ('new', ("new")),
    ('hint', ("hint")),
    ('top-title', ("top-title")),
    ('gray-section', ("gray-section")),
    ('dark-section', ("dark-section")),
)

CMSPLUGIN_CASCADE_LEAF_PLUGINS = ('TextLinkPlugin','SimpleWrapperPlugin',)
CMSPLUGIN_CASCADE = {
    'plugins_with_extra_fields': {
        'BootstrapButtonPlugin', 'BootstrapContainerPlugin',
        'BootstrapColumnPlugin', 'BootstrapRowPlugin', 'BootstrapPicturePlugin',
        'SimpleWrapperPlugin',
    },
    'plugins_with_sharables' : {
        'BootstrapImagePlugin': ('image-shapes', 'image-width-responsive', 'image-width-fixed', 'image-height', 'resize-options',),
        'BootstrapPicturePlugin': ('image-shapes', 'responsive-heights', 'image-size', 'resize-options',),
        'BootstrapButtonPlugin': ('link',),
        'TextLinkPlugin': ('link', 'target',),
    }
}
CMSPLUGIN_CASCADE_PLUGINS = (
    'cmsplugin_cascade.link',
    'cmsplugin_cascade.bootstrap3',
    'cmsplugin_cascade.generic',
)
CMSPLUGIN_CASCADE = {
    'plugins_with_extra_fields': ('BootstrapButtonPlugin', 'BootstrapRowPlugin', 'BootstrapColumnPlugin',
        'SimpleWrapperPlugin', 'HorizontalRulePlugin',
    ),
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '',
        'HOST': '',
        'USER': '',
        'PASSWORD': '',
        'PORT': '',
        #'CONN_MAX_AGE': 0,
    }
}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)
`

**Comment by vxsx** [comment]
@khrizo there is a difference between django admin and the site frontend
if you're in `/admin`

**Comment by mbi** [comment]
Same here: after upgrading from 3.2.5 to 3.3 the toolbar disappeared, although my admin is fine. Tried forcing the toolbar by appending `?edit` to the URL, nothing. `cms check` reports no errors, and no errors in the browser console either.

Reverting to 3.2.5 fixes the problem.

**Comment by czpython** [comment]
@khrizo 
For the sake of testing, can you set `INTERNAL_IPS = '127.0.0.1'` to an empty list? `INTERNAL_IPS = []`

@mbi 
Have you also set INTERNAL_IPS on the project? if so can you try an empty list?

**Comment by mbi** [comment]
@czpython I had `INTERNAL_IPS = ('127.0.0.1', )`, setting it as `[]` fixes the problem, good catch!

**Comment by czpython** [comment]
@mbi 
Nice. Just to make sure though, is your project running under another internal IP?
I'd like to rule out possibility of a bug that prevents us from getting the correct ip.

Change was introduced in https://github.com/divio/django-cms/pull/5173 to restrict the toolbar to certain IPs.

**Comment by mbi** [comment]
@czpython good question, I'm not sure, I haven't configured anything specific in terms of IP addresses: gunicorn binds a named socket, e.g. `bind = "unix:/path/to/gunicorn.sock"`, other than that this is a classic gunicorn + nginx reverse proxy setup.

**Comment by khrizo** [comment]
Fixed! with INTERNAL_IPS = []

**Comment by leesolway** [comment]
Same issues, fixed as above

**Comment by impala2** [comment]
I have a requirement to leave `INTERNAL_IPS` as is, but according to [the release notes](https://docs.django-cms.org/en/release-3.3.x/upgrade/3.3.html#what-s-new-in-3-3) there's a new setting `CMS_INTERNAL_IPS`. Setting it to `[]` fixed the issue. Looks like the default value for `CMS_INTERNAL_IPS` is incorrect.

**Comment by jsma** [comment]
The way this was implemented/documented in #5173 is backwards incompatible IMO. 

The CHANGELOG clearly states that this is a completely NEW setting, suggesting that if it's not set that the behavior would be the same as < 3.3.0.

It's very unexpected to do an upgrade and suddenly have no way of editing content. I think this CMS_INTERNAL_IPS should default to an empty list rather than Django's INTERNAL_IPS. At the very least, the upgrade docs should have a very loud warning about this.

**Comment by impala2** [comment]
@jsma Yea, that's what I meant by "default value is incorrect".

The documentation clearly states

> Added a new setting CMS_INTERNAL_IPS for defining a set of IP addresses for which the toolbar will appear for authorized users. **If left unset, retains the existing behavior of allowing toolbar for authorized users at any IP address.**

But the actual code uses `INTERNAL_IPS` by default.

> 'INTERNAL_IPS': settings.INTERNAL_IPS,  # Django default is []

I strongly lean towards setting it to `[]` rather than changing the documentation - principle of least surprise.

**Comment by FinalAngel** [comment]
@mkoistinen or @czpython something you can have a look at?

**Comment by czpython** [comment]
I can confirm this is indeed an oversight in our side.
The default should be `[]` as noted by @impala2 and @jsma.
Django's `INTERNAL_IPS` does not serve to block access to the admin, the assumption was that it did and so anyone that defined this would automatically benefit from the limit on the toolbar ips.

**Comment by bharling** [comment]
Confirmed - setting CMS_INTERNAL_IPS = [] fixed the problem, should definitely be documented somewhere!!

**Comment by agconti** [comment]
Confirmed as well. Should we make this more prominent in the release notes?

**Comment by czpython** [comment]
Fixed by #5409
