### ISSUE TITLE
Showing menus without pages

### ISSUE THREAD

**Issue by Eraldo** [divio/django-cms#5346]
How can I show a custom menu without creating a separate page for it.

## What I did

1. I created a menu that subclasses from `menus.base.Menu`.
2. I added a node with the id 'test' to it.
3. I added some further nodes which have 'test' as their parent.
4. In a template I added `{% show_menu_below_id 'test' 0 100 100 100 "organisms/menu.html" %}`.

=> Nothing gets shown as a result of this.

## Notes

+ The menu does exist and is attached to `root`.
  I know this because using `show_menu` instead does show the content of the menu.
  => So the menu class itself works.
+ Creating a page with an id and adding the Menu as an attached menu also works.
  => Not what I want.

## My conclusions

+ The node parent ids have nothing to do with the page ids (advanced settings).
+ I need to create a page with an advanced id to be able to reference the menu via 'id'.

## My Proposal

Add a property 'id' to the `Menu` class so the menu (living at root) can be referenced with `show_menu_below_id`.

## Alternatives / Ideas / Actions?

Any other ideas how I could achieve the same goal?
Feedback is welcome. :)
Any other information I can provide to help solve it?

**Comment by mkoistinen** [comment]
Yes, the page's "ID" in the Page's advanced settings is a little confusing. But you are correct, these have nothing to do with the Page IDs in NavigationNodes. In fact in the menu class, these are used only to link-up children to their parents, AFAICT. However, it is convenient to use the page's PK or "primary key", as they are guaranteed to be unique by the database. In the CMS, the NavigationNodes do indeed use the page's PK, so, you can look up the PK first, then use that as the parent reference, then you should be OK (haven't checked).

Are you attaching objects as part of an apphook? If so, this works for me:

````
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.core.urlresolvers import NoReverseMatch
from django.utils.translation import (
    get_language_from_request,
    ugettext_lazy as _,
)

from cms.menu_bases import CMSAttachMenu
from menus.base import NavigationNode
from menus.menu_pool import menu_pool

from .models import Organization


class PartnersMenu(CMSAttachMenu):
    # This is what will appear in the drop-list in the Advanced Settings on the
    # page. Best practice is to use the form "<app_name>: <Menu name>"
    name = _('Partners: Organizations')

    def get_nodes(self, request):
        nodes = []
        language = get_language_from_request(request, check_path=True)

        # NOTE: It is important that we only get objects that have an active
        # translation, otherwise, object.get_absolute_url() may return
        # NoReverseMatch exceptions that we will have to catch, if we want to
        # prevent errors from appearing on-screen.
        items = (Organization.objects
                             .language(language)
                             .active_translations(language))

        for item in items:
            # This try/except seems like overkill here, but if this fails for
            # any reason, this **and any further menus, even from other apps**
            # may not get loaded, so we're extra careful.
            try:
                url = item.get_absolute_url(language=language)
                node = NavigationNode(item.name, url, item.pk)
                nodes.append(node)
            except NoReverseMatch:  # pragma: no cover
                pass

        return nodes

menu_pool.register_menu(PartnersMenu)
````

**Comment by Eraldo** [comment]
Your explanation sheds light on some of my questions. :)
Thank you @mkoistinen for your clarification.
As a side remark: I like your commenting style in the snippet a lot.

## Reflection

In my template I tried to reference my menu via 'id' which was attached to the root.
Now I know that that is not yet possible since I need a `page-id` to reference that menu.
So I do need either an `apphook` configured with that menu or an attache-menu that is attached to a cms page.
In both cases I need a page to reference in order to selectively show it in a template.

## Workaround

As a workaround I created a page (located at the root) just for the sake of referencing my custom menu.
That does work now.

## Future

Does my proposal make sense to you?: Adding an id to the `menu` (not talking about the nodes).
The `show_menu_below_id`-template-tag could then be refactored to also search for menus with an `id`-attribute and attach it if a match is found.
What do you think? Or is there a reason why the tag should only be able to reference page-ids?

If that makes sense to you.. I am also willing to give it a try and create a PR if I get it to work.

**Comment by FinalAngel** [comment]
@divio/django-cms-core anyone opposing the idea?

**Comment by mkoistinen** [comment]
Have a look at this : https://gist.github.com/mkoistinen/249043bee3c53dd826dcbb7e80c4288e

I wrote this for someone else the other day, but it allows you to get the whole page object from the "id" from advanced settings. Once you have that, you can use the menu tags in the desired manner. :)

I hope this helps.

**Comment by mkoistinen** [comment]
Also, I should clarify that all menu items need to be part of the same "tree", meaning that they're all connected in a graph. So, if you wish to add some nodes that aren't pages, this is fine, but they need to be the children of some page, even if it is your root page.

**Comment by FinalAngel** [comment]
@Eraldo ist that sufficient for you?

**Comment by Eraldo** [comment]
@FinalAngel Yes it is.
I added it as an outcome to my list and will probably continue working on it next month.
In case I run into some issues I will open a new ticket and reference this one.
Thanks!

**Comment by FinalAngel** [comment]
You are very welcome, and thanks for all your feedback @Eraldo !

**Comment by jedie** [comment]
I didn't read everything (sorry), but maybe https://github.com/jedie/django-cms-named-menus can help here?!?
