### ISSUE TITLE
Link image to a document

### ISSUE THREAD

**Issue by MarcMueltin** [divio/django-cms#5348]
How can I easily link an image to an uploaded file?

I can either insert an image via the bootstrap image plugin or a file (Filer plugin). But there is no filed which lets me choose to optionally link that image to a file.
A "hack" would be to do both, copy the link from the file in the source code and then add a link tag around the image with the link to the file. There must be a better way, right?

**Comment by FinalAngel** [comment]
@MarcMueltin please place your question in Mailing List, IRC or the Divio Academy HipChat channel: https://www.django-cms.org/en/support/

To answer your question: just simply create a link plugin and nest it with an image:
http://d.pr/v/15lVH

**Comment by MarcMueltin** [comment]
Oh, I think I was not expressing myself clear enough: I want to do this within the Generic text plugin, because there I can access the other plugins as well. Or is that not possible? Thanks for the screencast by the way.

**Comment by FinalAngel** [comment]
@MarcMueltin we do not have yet the mechanic there to allow further nesting inside the text plugin. You can propose a feature request in: https://github.com/divio/djangocms-text-ckeditor. You can use the filer image plugin for this: http://d.pr/v/17Pf4

**Comment by czpython** [comment]
Closing as it's not a CMS issue. Please re-open in djangocms-text-ckeditor.
