### ISSUE TITLE
"Create Page" not translated on djangoCMS 3.3.0

### ISSUE THREAD

**Issue by retailify** [divio/django-cms#5349]
Please look at the Screenshot.

![bildschirmfoto 2016-05-30 um 11 00 13](https://cloud.githubusercontent.com/assets/5236353/15644954/232f2c40-2656-11e6-97e4-3d0a97c99042.png)

**Comment by FinalAngel** [comment]
@mkoistinen the string "Create Page" is now showing on Transifex. Am I missing something?

**Comment by FinalAngel** [comment]
Closing in favour of #5352
