### ISSUE TITLE
how we access language_code (current language) in cms_plugin.py in django_cms

### ISSUE THREAD

**Issue by kartikdanidhariya** [divio/django-cms#5350]
hi,
my django_cms == 3.2.3
django == 1.8.10

my cms_plugins.py is

from .models import *
from cms.utils import get_language_from_request
from django.contrib import admin

class FaqPlugin(CMSPluginBase):
   
    name = _("Faq Plugin")
    render_template = "faq/faq_list.html"
 

    def render(self, context, instance, placeholder):
    
	faqs = Faq.objects.language('fr').filter(status="published")
        lang = context['request']

        context.update({'instance' : instance, 'faqs' : faqs})
        return context
    
plugin_pool.register_plugin(FaqPlugin)

i want to get current language object instead of 'fr' how can i get that
plz help!!

**Comment by yakky** [comment]
Please, do not post support question, but refer to IRC channel / mailing list etc (see https://www.django-cms.org/en/support/)
