### ISSUE TITLE
multi site menu conflict

### ISSUE THREAD

**Issue by razisayyed** [divio/django-cms#5351]
Hi,

I am testing multisite installation using django-cms 3.0

I have two sites:
  - eng.example.com
  - law.example.com

everything works fine, I can login and add pages/plugins for each site. The problem is when I switch between the sites like following:

  1. I am in site law.example.com
  2. I expand the pages tree
  3. I change the page tree to eng.example.com.
  4. I collapse the admin panel. (Note: I am still on law.example.com site)
  5. I click on view published page button. **(The main menu disappears!!!)**
  6. I click on edit page button. **(main menu of eng.example.com appears instead of law.example.com!!!)**
  7. I expand the pages tree
  8. I change the page tree to law.example.com
  9. I collapse the admin panel
  10. still eng.example.com menu appears (even if I refresh the page)
  11. I click on view published page button. **(The main menu of law.example.com reappears)** and everything works as expected.

Note: the same bug appears in django-cms 3.2.5

**Comment by czpython** [comment]
Thanks for reporting.
This is known bug https://github.com/divio/django-cms/issues/5310
