### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by retailify** [divio/django-cms#5352]
Hi everybody, 

if the CMS contains no pages, there are missing german translations. 
See Screenshot 1:
a) Page Tree
b) Main Navigation
c) There is no page around yet.
d) + Add page now.
e) "New" Seite (Button on the right side)

![bildschirmfoto 2016-05-31 um 09 30 42](https://cloud.githubusercontent.com/assets/5236353/15666747/c31bb770-2712-11e6-9ea4-433398500ac6.png)
Screenshot 1

f) "Restore deleted" Seiten in the drop down menu (Screenshot 2) 
![bildschirmfoto 2016-05-31 um 09 36 33](https://cloud.githubusercontent.com/assets/5236353/15666859/4fdb162e-2713-11e6-8008-696c692a0db5.png)
Screenshot 2

There are translation issues in the static placeholder module. See screenshot.
a) erstellungs_methode
b) Bei Code 
c) Bei Vorlage
d) Nach site

![bildschirmfoto 2016-05-31 um 09 57 52](https://cloud.githubusercontent.com/assets/5236353/15667421/705d2bc8-2716-11e6-8a01-fd3f32bb5a7c.png)

There are missing translations in the page tree (Legend). see screenshot 4.

![bildschirmfoto 2016-05-31 um 10 12 03](https://cloud.githubusercontent.com/assets/5236353/15667814/7543ac64-2718-11e6-88da-0db1400dbb56.png)
Screenshot 4

Please translate "Menu" => "Menü" also (see screenshot 5)
![bildschirmfoto 2016-05-31 um 10 15 52](https://cloud.githubusercontent.com/assets/5236353/15667877/ca3d9d24-2718-11e6-8352-42e3a5cbf7d0.png)
Screenshot 5

**Comment by mkoistinen** [comment]
This is addressed. We now only need the translations (for any language, but including DE). Please go to here: https://www.transifex.com/divio/django-cms/ and provide any of the missing translations you're able to do.  I will periodically update the release/3.3.x branch with any new translations.

**Comment by FinalAngel** [comment]
@retailify translations added to the german page: https://www.transifex.com/divio/django-cms/translate/#de/core please review and add comments, as this will be merged within 3.3.1

**Comment by retailify** [comment]
Please reopen!
I had not the time to translate all!

**Comment by FinalAngel** [comment]
@retailify no worries, no release scheduled yet. But in case, I'll leave it open.

**Comment by vxsx** [comment]
3.3.1 was released yesterday with updated translations.
