### ISSUE TITLE
German translation issues in "static placeholders" djangoCMS 3.3.0

### ISSUE THREAD

**Issue by retailify** [divio/django-cms#5353]
Hi everybody, 

there are translation issues in the static placeholder modul. See screenshot.
a) erstellungs_methode
b) Bei Code 
c) Bei Vorlage
d) Nach site

![bildschirmfoto 2016-05-31 um 09 57 52](https://cloud.githubusercontent.com/assets/5236353/15667421/705d2bc8-2716-11e6-8a01-fd3f32bb5a7c.png)

**Comment by czpython** [comment]
Closed in favor of https://github.com/divio/django-cms/issues/5352
