### ISSUE TITLE
German Translation missing in page tree -> legend djangoCMS 3.3.0

### ISSUE THREAD

**Issue by retailify** [divio/django-cms#5354]
Hi everybody,

there are missing translations in the page tree (Legend). see screenshot 1.

![bildschirmfoto 2016-05-31 um 10 12 03](https://cloud.githubusercontent.com/assets/5236353/15667814/7543ac64-2718-11e6-88da-0db1400dbb56.png)
Screenshot 1

Please translate "Menu" => "Menü" also (see screenshot 2)
![bildschirmfoto 2016-05-31 um 10 15 52](https://cloud.githubusercontent.com/assets/5236353/15667877/ca3d9d24-2718-11e6-8352-42e3a5cbf7d0.png)
Screenshot 2

**Comment by czpython** [comment]
Closed in favor of https://github.com/divio/django-cms/issues/5352
