### ISSUE TITLE
apphook not respecting app_name in defined urls.py

### ISSUE THREAD

**Issue by Eraldo** [divio/django-cms#5357]
## Summary

I have an `app` that comes with it's own `namespace` baked into the app.
That works nicely on it's own.
I tried to convert that app into an apphook app.
I ended up getting an error that the namespace was not registered.

## What I did

I included the apps urls into my apphook:
```python
# maapp.cms_apps.py

class MyApphook(CMSApp):
    name = _('MyApp')
    urls = ['myapp.urls']


apphook_pool.register(MyAppApphook)
```

```python
# maapp.urls.py

app_name = 'myapp'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    ...
]
```
Reference: https://docs.djangoproject.com/en/1.9/topics/http/urls/#url-namespaces-and-included-urlconfs

Then I added the new `apphook` to a page.

## Problem

I get an error telling me that the namespace 'myapp' is not registered.
```bash
django.core.urlresolvers.NoReverseMatch: 'myapp' is not a registered namespace
```

## Workaround

Rewriting the `urls.py` file in the following manner removed the error:
```python
# maapp.urls.py

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    ...
]
urlpatterns = [
    url(r'^', include(urlpatterns, namespace='myapp')),
]
```

## Conclusion

My guess is that the apphook logic does not yet account for the app_name variable or at least does not process it in the same way stock django would. That is the only way I can currently explain myself why it does work if I include it in the main `urls.py` and stops working if I include the urls in my `apphook` definition file.
I do know that I could add a variable `app_name` to my apphook definition class (subclassing from `CMSApp`). However that means I also need to configure my apphook in the cms with an app instance name which is confusing since the app is intended to be installed only once and not multiple times. (Otherwise that would be the preferred option as far as I understand it).

## Request

I am interested in your perspective.
Is my conclusion accurate?
Are there other ideas or options that I missed?
Is there a good reason why the apphook does not account for the app_name in the `urls.py` file?
What do you think?

Thanks :)
Eraldo

**Comment by yakky** [comment]
You need to integrate the ``app_name`` attribute in the apphook class. See `class FaqApp(CMSConfigApp):`` in http://django-cms.readthedocs.io/en/release-3.3.x/how_to/namespaced_apphooks.html

**Comment by Eraldo** [comment]
Yes @yakky as I wrote in my conclusion section.. I do know that part:

> I do know that I could add a variable app_name to my apphook definition class (subclassing from CMSApp). However that means I also need to configure my apphook in the cms with an app instance name which is confusing since the app is intended to be installed only once and not multiple times. (Otherwise that would be the preferred option as far as I understand it).

Can you please comment on what I wrote, so I understand it better?

**Comment by yakky** [comment]
``app_name`` on apphook class is the only supported way to handle namespaced apps, thus you are required to define and instance name on the advanced settings

**Comment by Eraldo** [comment]
I see no advantage from using `app_name` in the `apphook class` over my `current workaround`.
The real challenge is testing my project, since the namespaces are not registered either way in the `testing database`.

Still.. Thank you for your perspective, @yakky. :)
