### ISSUE TITLE
Set .cms-toolbar-expanded on html element before the toolbar is animated

### ISSUE THREAD

**Issue by macolo** [divio/django-cms#5358]
Currently it seems not possible to animate any page content simultaneously with the show/hide animation of the DjangoCMS toolbar. Currently, first the DjangoCMS toolbar closes and then the page content is animated.

Expected behaviour: First the `cms-toolbar-expanded ` class is set or removed from `html` and then the DjangoCMS toolbar is expanded or retracted.

Example: The following overwrites are necessary to make the DjangoCMS toolbar work with the fixed menu of the website. Both menu and toolbar need to appear stacked on top of each other.

```
html
    // http://stackoverflow.com/questions/11258877/fixed-element-disappears-in-chrome
    transform: translateZ(0)
    margin-top: 0 !important
    transition: padding-top 0.1s ease-in-out

// overwrites menu bar if admin section is expanded
html.cms-toolbar-expanded
    padding-top: 49px !important

html.cms-structure-mode-structure
    padding-top: 0 !important
```

**Comment by vxsx** [comment]
http://docs.django-cms.org/en/release-3.3.x/how_to/toolbar.html#frontend

We have `cms-toolbar-expanding` and `cms-toolbar-collapsing` classes for that.

It should be possible to use them to achieve desired effect.

**Comment by macolo** [comment]
Awesome - thanks for the hint. For further references, the following works:

```
html
    // http://stackoverflow.com/questions/11258877/fixed-element-disappears-in-chrome
    transform: translateZ(0)
    margin-top: 0 !important
    transition: padding-top 0.1s linear


// overwrites menu bar if admin section is expanded
html.cms-toolbar-expanding,
html.cms-toolbar-expanded
    padding-top: 49px !important

// needs to be after ...-expanded because of CSS precedence
html.cms-toolbar-collapsing
    padding-top: 0 !important

html.cms-structure-mode-structure
    padding-top: 0 !important

```

**Comment by mateoreyes** [comment]
Could you tell me where  put this code ?
