### ISSUE TITLE
How to write unit-tests for apphooked apps.

### ISSUE THREAD

**Issue by Eraldo** [divio/django-cms#5361]
## What I did

I upgraded my `users` app to be a cms apphooked app and removed it from the main `urls.py` file.
```python
# project.users.cms_apps.py

class UsersApphook(CMSApp):
    name = _('Users')
    urls = ['project.users.urls']
    menus = [UserMenu]


apphook_pool.register(UsersApphook)
```

```python
# project.users.urls.py

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^list/$',
        view=UserListView.as_view(),
        name='list'
    ),
    ...
]
urlpatterns = 
    url(r'^', include(urlpatterns, namespace='users')),
]

```

On my staging server I created a new cms page and added the new apphook.
It works nicely on the front end side of things.
It finds the namespace and loads the write views.

## Challenge

Now when I run my tests it does not find the namespace 'users' because the apphook is not set in the  test database (having no page instances). 

Currently it fails to reverse my `get_absolute_url` on my User model. 
```python
    def test_get_absolute_url(self):
        self.assertEqual(
            self.user.get_absolute_url(),
            '/legends/testuser/'
        )
```

The error:
```
django.core.urlresolvers.NoReverseMatch: 'users' is not a registered namespace
```

So I am wondering what to do. What testing strategy to use. 

I could manually create the pages and add the apphooks to it. 
Or or I could load some fixtures. However I dislike the idea of maintaining fixtures and would prefer a different solution.

Before using django-cms I created data migrations creating all essential instances to run the tests.
That does not make much sense anymore to me when using djagno-cms. And even if I do not know how to create pages and install apphooks on the fly in my test cases.

I do not want to push the cms upgraded branch to production for the price of losing some of my basic tests.

## Request

Please give me some guidance on what to do to get back to a fully tested project.
How can I handle my cms apphooked apps in my tests?
Hints, best practises, tutorials, thoughts, .. it is all welcome since I feel quite lost when it comes to testing in combination with django-cms.

**Comment by mkoistinen** [comment]
Hi, I have a couple of things for you that may help.

1. Some time ago, I put together a "dummy" app that includes translations, reversions and apphook-ability and it has 100% (or near that) test coverage, the repo is here: https://github.com/aldryn/things and this may provide some immediate help;
2. We often use the very useful package `djangocms-helper` made by @yakky (one of the core developers of django CMS), this will also make your life easier =);
3. I would suggest in general to have a look at how we handle some of the challenges you describe above by reviewing the tests we have for [Aldryn NewsBlog](https://github.com/aldryn/aldryn-newsblog), [Aldryn People](https://github.com/aldryn/aldryn-people), [Aldryn Events](https://github.com/aldryn/aldryn-events), [Aldryn FAQ](https://github.com/aldryn/aldryn-faq) and [Aldryn Jobs](https://github.com/aldryn/aldryn-jobs).

I hope this helps!

**Comment by Eraldo** [comment]
I will take a look at these examples.
Sounds good.. and I feel better now that I have a starting point. =)
Thank you Martin.

**Comment by retailify** [comment]
Hi Martin, 
djangocms-helper is marked for django CMS: 3.0 to 3.2. 
What about 3.3.x?
