### ISSUE TITLE
[question] Specifying cache parameters

### ISSUE THREAD

**Issue by petrklus** [divio/django-cms#5363]
In one of our projects, we are serving different content based on user agent. As such, we had to disable caching of the plugin.

Is there any way to specify caching variables in a similar way as Django's template tag for cache works?

    {% cache 500 sidebar request.user.username %}

**Comment by mkoistinen** [comment]
@petrklus In version 3.3, you can now specify VARY headers on a per-plugin basis. Here's a reference to the docs on this: http://docs.django-cms.org/en/release-3.3.x/reference/api_references.html#cms.plugin_base.CMSPluginBase.get_vary_cache_on

The easiest way to try this out on a CMS 3.3 project is to use this plugin in your project to "wrap" some of your content: https://github.com/divio/cmsplugin-header-control.

I don't think we have any specific means of adding the VARY headers system-wide, but it could be very quickly and easily done with a tiny middleware that you add to your Django project too. Let me know if you need help with that.

**Comment by FinalAngel** [comment]
Hello, please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](django-cms.org/support) page.

**Comment by petrklus** [comment]
@FinalAngel noted and my apologies! Will make sure I use a proper channel next time.

**Comment by FinalAngel** [comment]
no worries, thank you @petrklus
