### ISSUE TITLE
djangocms-installer parent of subpage not navigable via menu

### ISSUE THREAD

**Issue by k-funk** [divio/django-cms#5369]
Just started out using django-cms. To reproduce my issue:

1. Go though Tutorials->Installing Django CMS (all default install options, except bootstrap=yes), and all of Using Django CMS.
2. Create a page called Books with content.
3. Create a subpage to Books called Book1 with content.
4. Publish both.
5. Click in menu to try to navigate to parent of Book1 (what I made in step2), but only get a dropdown.

I'm not exactly sure what _should_ happen here. When building drop-down menus, I've used two approaches in the past:

1. A top-level nav page that can be visited (in this case, `/books`)
2. A logical nav-grouping just for the sake of navigation, but no page that's able to be visited, only subpages can be visited

...this seems to be neither. I can't visit `/books` like in option 1, so I now have a page with content that's not reachable via the nav. I also don't see how I could achieve the second use case since the navigation seems to be tied directly to the pages and their visibility—I can't just unpublish it or take it off of the menu without doing the same to its children

Other than writing a custom navigation, what should be happening in this example site? I'm confused about the use for the parent of a subpage if the approach is option 2.

**Comment by FinalAngel** [comment]
Hello, please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](django-cms.org/support) page.

The issue you are mentioning is a bootstrap 3 behaviour: http://getbootstrap.com/components/#navbar checkout the dropdown. There are alternative dropdown behaviours available: http://getbootstrap.com/components/#btn-dropdowns you need to adapt the according menu.html: https://github.com/nephila/djangocms-installer/blob/ea6a295429eceb6dc3d5b6dfd9ae42cd6c66a143/djangocms_installer/share/templates/bootstrap/menu.html
