### ISSUE TITLE
Wrong default frontend_edit_template in doc

### ISSUE THREAD

**Issue by philippze** [divio/django-cms#5372]
The docs say the default value for the frontend_edit_template was **"cms/toolbar/placeholder_wrapper.html"**, here: https://github.com/divio/django-cms/blob/develop/docs/reference/plugins.rst#frontend_edit_template

However, the proper default value is **"cms/toolbar/plugin.html"**. It is defined here: https://github.com/divio/django-cms/blob/develop/cms/plugin_base.py#L105

**Comment by FinalAngel** [comment]
@philippze would you be able to open a PR for that fix?

**Comment by philippze** [comment]
@FinalAngel Yes. I will.

**Comment by FinalAngel** [comment]
thats awesome @philippze ! Thank you

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/5829
