### ISSUE TITLE
[Q] Does it support RTL languages?

### ISSUE THREAD

**Issue by SomeEarthling** [divio/django-cms#5380]
Hello,

Seems like a great project.
I'd love to explore building a website with this, but I've been reading the documentation and it doesn't anywhere (that I could find) say that it supports RTL languages correctly (Right-To-Left); mainly Arabic for me.

It says it's "multilingual" but I've been bitten by that before. Also, there are a couple of issues here of people saying that RTL is actually causing problems for them (unrelated to the CMS supporting it), so I'm on unclear on this yet.

I'd appreciate a quick answer :)
PS. I read the "contributing guidelines" and it doesn't talk about asking a question here. Hope it's ok.

**Comment by FinalAngel** [comment]
The toolbar / CMS UI does not yet support RTL so things might look awkward. The toolbar is specifically aligned to ``dir="ltr"``. Your frontend though can be totally independent of the CMS and can fully support RTL alignment.

You are very welcome to submit further PRs to improve RTL support. The editing experience though is not much affected.

**Comment by mbnoimi** [comment]
@FinalAngel 
> Your frontend though can be totally independent of the CMS and can fully support RTL alignment.

Just to make sure. Does the backend supports RTL in any way?

I didn't test Django CMS yet but I'm reading about it because I want to leave WordPress in favor of a flexible CMS work fine for editors and developers too (I suffer a lot of WordPress & Drupal as a developer) just like Django CMS

**Comment by Bashar** [comment]
backend supports RTL and I've launched tens if not hundreds of dual language (arabic+english) sites using django-cms in the past

as the guys said in new versions the toolbar/CMS UI isn't best, but we managed to work it out somehow and works a bit fine you can see this screenshot from one of the sites 
![sample](https://cloud.githubusercontent.com/assets/142219/24009739/f5eb5d7e-0a86-11e7-8a79-839ebd330179.png)

and this is a modified frontend look and feel (hidden some private info)

![home](https://cloud.githubusercontent.com/assets/142219/24010107/fa6fa6ce-0a87-11e7-9927-fc9c1f6d3051.png)

**Comment by mbnoimi** [comment]
@Bashar 

Thanks, I think it's vital to make to feature request about this issue. 
Any way, I'm still reading about it more and I hopeful to find my requirements because I really hate to continue writing WordPress custom plugins for some stupid stuffs.

**Comment by FinalAngel** [comment]
@Bashar it would be amazing to have your work being contributed back to the CMS in form of a Pull Request, I think that might help other developers as well.

**Comment by Bashar** [comment]
@FinalAngel sure thing, will check with my colleagues and see if anything not contributed already will submit it.

its mostly out of the box in django/django-cms and i've done most of the translation on https://www.transifex.com/divio/django-cms/language/ar/

**Comment by FinalAngel** [comment]
thats awesome @Bashar :)
