### ISSUE TITLE
cms_wizard_create error

### ISSUE THREAD

**Issue by jTiKey** [divio/django-cms#5392]
After adding django-cms to an existing project, when I go to the root url I get this:

django.core.urlresolvers.NoReverseMatch: Reverse for 'cms_wizard_create' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['$cms_wizard/create/$']

If I create a page via the django admin, the error dissapears, and I get the base.html, without any toolbars and buttons.

**Comment by czpython** [comment]
@jTiKey 
Hello,
Can you provide us with the following information?:

- Django version
- Django CMS version
- Python version

Also please post your Django settings.

**Comment by jTiKey** [comment]
django 1.8.5
django cms 3.3.0
python 3.5

`from __future__ import absolute_import, unicode_literals
from django.utils.translation import ugettext_lazy as _

from datetime import datetime

import environ
import pytz
import os

ROOT_DIR = environ.Path(__file__) - 3  # (/a/b/myfile.py - 3 = /)
APPS_DIR = ROOT_DIR.path('yovaweb')

env = environ.Env()
environ.Env.read_env(str(ROOT_DIR.path('.env')))

gettext = lambda s: s
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

# APP CONFIGURATION
# ------------------------------------------------------------------------------
DJANGO_APPS = (

    # Default Django apps:
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    # Useful template tags:
    'django.contrib.humanize',

    # Admin
    'djangocms_admin_style',  # for the admin skin. You **must** add 'djangocms_admin_style' in the list **before** 'django.contrib.admin'.
    'django.contrib.admin',
)
THIRD_PARTY_APPS = (

    'crispy_forms',  # Form layouts
    'allauth',  # registration
    'allauth.account',  # registration
    'allauth.socialaccount',  # registration
    'django_activeurl',
    'rest_framework',
)

# Apps specific for this project go here.
LOCAL_APPS = (
    'yovaweb.users',  # custom users app
    'yovaweb.ecommerce',
    'yovaweb.payments',
    'yovaweb.notifications',
    'yovaweb.texts',
    'yovaweb.extra'

)

CMS = (
    'cms',  # django CMS itself
    'treebeard',  # utilities for implementing a tree
    'menus',  # helper for model independent hierarchical website navigation
    'sekizai',  # for JavaScript and CSS management
)

SITE_ID = 1

# See: https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS + CMS

# MIDDLEWARE CONFIGURATION
# ------------------------------------------------------------------------------
MIDDLEWARE_CLASSES = (
    # Make sure djangosecure.middleware.SecurityMiddleware is listed first
    'django.contrib.sessions.middleware.SessionMiddleware',
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    # custom middleware's
    'yovaweb.register_steps_middleware.RegisterStepsMiddleware',
)

# MIGRATIONS CONFIGURATION
# ------------------------------------------------------------------------------
MIGRATION_MODULES = {
    'sites': 'yovaweb.contrib.sites.migrations'
}

# DEBUG
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#debug
DEBUG = env.bool("DJANGO_DEBUG", False)

# FIXTURE CONFIGURATION
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-FIXTURE_DIRS
FIXTURE_DIRS = (
    str(APPS_DIR.path('fixtures')),
)

# EMAIL CONFIGURATION
# ------------------------------------------------------------------------------
EMAIL_BACKEND = env('DJANGO_EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')

# MANAGER CONFIGURATION
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#admins
ADMINS = (
    ("""Michal Janowski""", 'mjanowski@milosolutions.com'),
)

# See: https://docs.djangoproject.com/en/dev/ref/settings/#managers
MANAGERS = ADMINS

# DATABASE CONFIGURATION
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#databases
DATABASES = {
    # Raises ImproperlyConfigured exception if DATABASE_URL not in os.environ
    'default': env.db("DATABASE_URL", default="postgres:///yovaweb"),
}
DATABASES['default']['ATOMIC_REQUESTS'] = True


# GENERAL CONFIGURATION
# ------------------------------------------------------------------------------
# Local time zone for this installation. Choices can be found here:
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# although not all choices may be available on all operating systems.
# In a Windows environment this must be set to your system time zone.
TIME_ZONE = 'UTC'

# See: https://docs.djangoproject.com/en/dev/ref/settings/#language-code
LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en-us', 'English'),
]

# See: https://docs.djangoproject.com/en/dev/ref/settings/#site-id
SITE_ID = 1

# See: https://docs.djangoproject.com/en/dev/ref/settings/#use-i18n
USE_I18N = True

# See: https://docs.djangoproject.com/en/dev/ref/settings/#use-l10n
USE_L10N = True

# See: https://docs.djangoproject.com/en/dev/ref/settings/#use-tz
USE_TZ = True

# TEMPLATE CONFIGURATION
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#templates
TEMPLATES = [
    {
        # See: https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-TEMPLATES-BACKEND
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # See: https://docs.djangoproject.com/en/dev/ref/settings/#template-dirs
        'DIRS': [
            str(APPS_DIR.path('templates')),
        ],
        'OPTIONS': {
            # See: https://docs.djangoproject.com/en/dev/ref/settings/#template-debug
            'debug': DEBUG,
            # See: https://docs.djangoproject.com/en/dev/ref/settings/#template-loaders
            # https://docs.djangoproject.com/en/dev/ref/templates/api/#loader-types
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
            # See: https://docs.djangoproject.com/en/dev/ref/settings/#template-context-processors
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                # Your stuff: custom template context processors go here
                'config.template_variables.template_variables',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
            ],
        },
    },
]

CMS_TEMPLATES = (
    ('template_1.html', 'Template One'),
)

# See: http://django-crispy-forms.readthedocs.org/en/latest/install.html#template-packs
CRISPY_TEMPLATE_PACK = 'bootstrap3'

# STATIC FILE CONFIGURATION
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = str(ROOT_DIR('staticfiles'))

# See: https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = '/static/'

# See: https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
STATICFILES_DIRS = (
    str(APPS_DIR.path('static')),
)

# See: https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

# MEDIA CONFIGURATION
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#media-root
MEDIA_ROOT = str(APPS_DIR('media'))

# See: https://docs.djangoproject.com/en/dev/ref/settings/#media-url
MEDIA_URL = '/media/'

# URL Configuration
# ------------------------------------------------------------------------------
ROOT_URLCONF = 'config.urls'

# See: https://docs.djangoproject.com/en/dev/ref/settings/#wsgi-application
WSGI_APPLICATION = 'config.wsgi.application'`

**Comment by jTiKey** [comment]
Full logs:
```
File "/usr/local/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
return self.application(environ, start_response)
File "/usr/local/lib/python3.5/site-packages/whitenoise/base.py", line 119, in __call__
return self.application(environ, start_response)
File "/usr/local/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
Display the sourcecode for this frameOpen an interactive python shell in this frameresponse = self.get_response(request)
File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 218, in get_response
response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
return debug.technical_500_response(request, *exc_info)
File "/usr/local/lib/python3.5/site-packages/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
six.reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.5/site-packages/six.py", line 686, in reraise
raise value
File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 164, in get_response
response = response.render()
File "/usr/local/lib/python3.5/site-packages/django/template/response.py", line 158, in render
self.content = self.rendered_content
File "/usr/local/lib/python3.5/site-packages/django/template/response.py", line 135, in rendered_content
content = template.render(context, self._request)
File "/usr/local/lib/python3.5/site-packages/django/template/backends/django.py", line 74, in render
return self.template.render(context)
File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 209, in render
return self._render(context)
File "/usr/local/lib/python3.5/site-packages/django/test/utils.py", line 96, in instrumented_test_render
return self.nodelist.render(context)
File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 903, in render
bit = self.render_node(node, context)
File "/usr/local/lib/python3.5/site-packages/django/template/debug.py", line 79, in render_node
return node.render(context)
File "/usr/local/lib/python3.5/site-packages/classytags/core.py", line 146, in render
return self.render_tag(context, **kwargs)
File "/usr/local/lib/python3.5/site-packages/sekizai/templatetags/sekizai_tags.py", line 83, in render_tag
rendered_contents = nodelist.render(context)
File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 903, in render
bit = self.render_node(node, context)
File "/usr/local/lib/python3.5/site-packages/django/template/debug.py", line 79, in render_node
return node.render(context)
File "/usr/local/lib/python3.5/site-packages/classytags/core.py", line 146, in render
return self.render_tag(context, **kwargs)
File "/usr/local/lib/python3.5/site-packages/cms/templatetags/cms_tags.py", line 631, in render_tag
rendered_contents = nodelist.render(context)
File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 903, in render
bit = self.render_node(node, context)
File "/usr/local/lib/python3.5/site-packages/django/template/debug.py", line 79, in render_node
return node.render(context)
File "/usr/local/lib/python3.5/site-packages/classytags/core.py", line 146, in render
return self.render_tag(context, **kwargs)
File "/usr/local/lib/python3.5/site-packages/sekizai/templatetags/sekizai_tags.py", line 83, in render_tag
rendered_contents = nodelist.render(context)
File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 903, in render
bit = self.render_node(node, context)
File "/usr/local/lib/python3.5/site-packages/django/template/debug.py", line 79, in render_node
return node.render(context)
File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 329, in render
return nodelist.render(context)
File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 903, in render
bit = self.render_node(node, context)
File "/usr/local/lib/python3.5/site-packages/django/template/debug.py", line 79, in render_node
return node.render(context)
File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 507, in render
six.reraise(*exc_info)
File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 659, in reraise
raise value
File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 493, in render
url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
File "/usr/local/lib/python3.5/site-packages/django/core/urlresolvers.py", line 578, in reverse
return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
File "/usr/local/lib/python3.5/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
(lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'cms_wizard_create' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['$cms_wizard/create/$']
```

**Comment by piotrjakimiak** [comment]
@jTiKey Could You paste Your urls.py file? I think you have `$` instead of `^` in urls .

**Comment by czpython** [comment]
@jTiKey 
I've reproduced the issue using @piotrjakimiak's suggestion.
Make sure to include the cms urls ``url(r'^', include('cms.urls')),`` with the ``^`` only.

**Comment by jTiKey** [comment]
Yes, you were right! Thanks for the help.
