### ISSUE TITLE
Proper usage string for djangocms

### ISSUE THREAD

**Issue by Nemecle** [divio/django-cms#5398]
Hi,
I am trying to write a dockerfile for my raspberry pi, which implies that I fully automate the command use: after struggling a bit at trying to make the link between each required information of the basic install with each argument, I am still stuck on the "--db" argument: It keeps asking for a user input for it even if I put *--db "sqlite://file///home/djangocms/website/djangocms.db'* (which might also be a bug)

the djangocms command needs more information on the expected informations (e.g. the format and possiblities of --timezone or --languages) than the available arguments.

Full command as currently used for illustration:
```

RUN /home/djangocms/website/venv/bin/djangocms -f -p /home/djangocms/website/app test \
        --db "sqlite://file///home/djangocms/website/djangocms.db" \
        --i18n yes \
        --django-version stable \
        --cms-version stable \
        --reversion yes \
        --languages "en" \
        --languages "fr" \
        --timezone "Europe/Paris" \
        --use-tz yes \
        --permissions yes \
        --bootstrap yes \
        --templates no \
        --starting-page yes
```

Result (as in docker build execution):
```
Step 15 : RUN /home/djangocms/website/venv/bin/djangocms -f -p /home/djangocms/website/app mawiink        --db "sqlite://file///home/djangocms/website/djangocms.db"      --i18n yes      --django-version stable   --cms-version stable    --reversion yes         --languages "en"        --languages "fr"  --timezone "Europe/Paris"       --use-tz yes    --permissions yes       --bootstrap yes  --templates no   --starting-page yes
 ---> Running in 4c55b800b980
*Database configuration (in URL format) [default sqlite://file///home/djangocms/website/djangocms.db]:* Traceback (most recent call last):
  File "/home/djangocms/website/venv/bin/djangocms", line 9, in <module>
    load_entry_point('djangocms-installer==0.9.b1', 'console_scripts', 'djangocms')()
  File "/home/djangocms/website/venv/local/lib/python2.7/site-packages/djangocms_installer/main.py", line 15, in execute
    config_data = config.parse(sys.argv[1:])
  File "/home/djangocms/website/venv/local/lib/python2.7/site-packages/djangocms_installer/config/__init__.py", line 166, in parse
    args = _manage_args(parser,  args)
  File "/home/djangocms/website/venv/local/lib/python2.7/site-packages/djangocms_installer/config/__init__.py", line 338, in _manage_args
    new_val = compat.input(prompt)
EOFError: EOF when reading a line
The command '/bin/sh -c /home/djangocms/website/venv/bin/djangocms -f -p /home/djangocms/website/app test      --db "sqlite://file///home/djangocms/website/djangocms.db"      --i18n yes      --django-version stable   --cms-version stable    --reversion yes         --languages "en"        --languages "fr"  --timezone "Europe/Paris"       --use-tz yes    --permissions yes       --bootstrap yes   --templates no  --starting-page yes' returned a non-zero code: 1
```

Freely,

**Comment by yakky** [comment]
@Nemecle use ``-q`` argument (see http://djangocms-installer.readthedocs.io/en/latest/usage.html#batch-mode )

**Comment by Nemecle** [comment]
Yeah I fell on it and i'm using it, but I still think that the command needs a proper help string (at least displayed with "djangocms --help"

**Comment by yakky** [comment]
@Nemecle what would you suggest?

**Comment by Nemecle** [comment]
It would be great to give some example values such as "_en_" and "_fr_" for **--languages** or "_Europe/Paris_" for **--timezone** (found those by poking around and using default values) and/or a link or an extended help (through **djangocms --help** for instance) which links every (at least major) possible values or syntaxes

**Comment by FinalAngel** [comment]
@divio/django-cms-core is thos something we should add? @yakky if yes something you can integrate?

**Comment by yakky** [comment]
@FinalAngel definitely
@Nemecle thanks for the suggestions. Closing here, tracking at nephila/djangocms-installer#258

**Comment by Nemecle** [comment]
thank you very much !
