### ISSUE TITLE
Django CMS error - "You do not have permission to edit/add/etc. a plugin"

### ISSUE THREAD

**Issue by ursomniac** [divio/django-cms#5400]
I get this intermittently.

I'm logged into the admin, the account is a super user. There's no back-end code that would in any way limit access to the plugin. It seems to just be "Django CMS has decided this is the case and there's no way around it..."

SOMETIMES if I: 1) log out of the admin, 2) clear my browser cache, 3) restart the server, and 4) reboot the entire machine, the problem MIGHT go away. Otherwise it persists.

This is REALLY affecting a production site (i.e, "the real world"). It's not the only Django-CMS-related "permissions weirdness" we've encountered but it's the one dominating getting work done at present.

Using: Django 1.8.13 with Dango-cms 3.2.5.

What's the workaround?

**Comment by yakky** [comment]
@ursomniac does this happen on pages attached to apphooks?

**Comment by ursomniac** [comment]
Yes, but only ONE of the apphooks.  All the other ones work fine, and if I put the plugin (which has no fields) on any of the other instances it works fine.

This is a site that was recently upgraded from Django CMS 2.4 to 3.2 (and Django 1.5 to 1.8 with all THAT implies), but this new app/plugin was written after the upgrade.

I've checked the auth_* tables in the database and the permissions appear to be there.  I've actually gone into the admin and deliberately set them, but the app simply refuses to let me do anything with the plugin...   It doesn't make any sense.

**Comment by czpython** [comment]
@ursomniac 
Starting with CMS 3.0, `{% placeholder %}` tags were no longer allowed in templates rendered by apphooks.

Please check if you're inheriting a template with a  `{% placeholder %} `tag in your apphook page.
It's likely that this is the placeholder that's incorrectly giving you the permission errors.

**Comment by ursomniac** [comment]
I tried creating a new user/superuser - same problem with the new user.   But the permissions ARE in auth_user_user_permissions.

**Comment by ursomniac** [comment]
@czpython --- AH that's likely the problem --- can you point me to docs that would show what the workaround would be?

**Comment by yakky** [comment]
@ursomniac the solution is to just use ``{% static_placeholder "foo bla" %}`` in apphooks instead of ``{% placeholder %}``

**Comment by ursomniac** [comment]
YOU ROCK.   Thanks.

**Comment by ursomniac** [comment]
Nope - permission error persists.

**Comment by czpython** [comment]
@ursomniac 
So you've removed the {% placeholder %} tag from your app and are now using static placeholder?

**Comment by ursomniac** [comment]
Yes but that creates ANOTHER problem.
The app is "newsletter" --- the plugins are for managing content within EACH newsletter.
It appears that static_placeholder only holds one set of content for the entire app; i.e., if I create two newsletter records and edit one to add placeholder content, it changes the content for the other record.

I need each record to have it's own unique content.

**Comment by yakky** [comment]
@ursomniac you can either user static placeholders with name generated from context variables or add a placeholderfield to your model http://django-cms.readthedocs.io/en/release-3.3.x/how_to/placeholders.html

**Comment by ursomniac** [comment]
I do have a placeholder field in my model.

**Comment by czpython** [comment]
@ursomniac Can you post your model and template code that renders it?

**Comment by ursomniac** [comment]
Got it...  (Duh)
