### ISSUE TITLE
Copy & Paste Alias Plugin from/into the same placeholder causes infinite loop

### ISSUE THREAD

**Issue by macolo** [divio/django-cms#5402]
... and this seems to make the edit page inaccessible which makes it impossible to fix the thing.

The only solution I found is removing the plugin entry directly on the database level.

On Aldryn it's even more severe because there the db needs to be copied to stage and then to local, then  manually fixing, and then the full round-trip back to production.

I'm not saying copying / pasting an alias into the same placeholder makes much sense but sooner or later somebody does it... dooh.

**Comment by FinalAngel** [comment]
thank you for reporting @macolo, this has been confirmed, will be patching the Alias plugin soon enough.

**Comment by macolo** [comment]
@mkoistinen I just found out another facet of this:

DjangoCMS allows the editor to create an alias on the placeholder level. This alias can then be placed inside the very same placeholder on another language, which also triggers the infinite loop.

So we have two scenarios:

1. the editor creates an alias of an element inside a placeholder and pastes it on the same language/page combination (same placeholder?) which triggers the infinite loop. (unconfirmed).
1. the editor creates an alias of the placeholder and pastes it on a different language/page into the same placeholder which triggers the infinite loop (confirmed).
