### ISSUE TITLE
Text editor plugin parsing issue

### ISSUE THREAD

**Issue by petrklus** [divio/django-cms#5415]
I am seeing and issue when Text editor's child plugin name/label contain > character.

I have also reproduced the issue on the Aldryn demo site:

Works fine in "Edit" mode:

![image](https://cloud.githubusercontent.com/assets/1115667/16080110/7666fa74-3307-11e6-84bf-39c0110529fd.png)

However, published page does not work properly:

![image](https://cloud.githubusercontent.com/assets/1115667/16080119/812d4e68-3307-11e6-89e9-b5faf0bacc2c.png)

The button plugin is as simple as it could be:

![image](https://cloud.githubusercontent.com/assets/1115667/16080140/9b3428fe-3307-11e6-8acb-716351c4e495.png)

I believe the issues is that on published pages, for some reason, the text is not escaped anymore, leading to the regular expressions un Text plugin's utils to not match the full placeholder.

Apart from pointing the issue, I was curious - why is this happening only on published pages?

**Comment by FinalAngel** [comment]
Actually, the edit mode behaves correctly as https://github.com/aldryn/aldryn-bootstrap3/blob/master/aldryn_bootstrap3/templates/aldryn_bootstrap3/plugins/button.html#L23 is not being escaped. You'd have to add the appropriate template tag to ``{{ instance.label }}`` like ``{{ instance.label| escape }}``.

I'm wondering what the structure board does, are strings there automatically escabed @divio/django-cms-core ? https://github.com/divio/django-cms/blob/develop/cms/templates/cms/toolbar/plugin.html#L3

**Comment by petrklus** [comment]
@FinalAngel I do not think there is an issue at all on the plugin side. The difference seems to be in the way the placeholder is generated in Text plugin's body.

For example, the placeholder looks like this when viewing in "Edit" mode:

    <img id="plugin_obj_2767" alt="Link Button" title="Link Button - asdf &amp;gt; test" src="/static/cms/img/icons/plugins/link.png">

But when looking at published page, the placeholder reads:

    <img id="plugin_obj_2791" alt="Link Button - asdf > test" title="Link Button - asdf > test" src="/static/cms/img/icons/plugins/link.png">

I am looking at the instance.body in djangocms_text_ckeditor/cms_plugins.py, render function.

Because the > symbol is kept unescaped on the live page, the regular expressions:

    OBJ_ADMIN_RE_PATTERN = r'<img [^>]*\bid="plugin_obj_(\d+)"[^>]*/?>'

in the text plugin's utils.py do not work anymore.

**Comment by czpython** [comment]
This was fixed on djangocms-text-ckeditor 3.2+
