### ISSUE TITLE
Outdated comparison grid information about django-cms.

### ISSUE THREAD

**Issue by Eraldo** [divio/django-cms#5419]
On the `django packages` `cms comparison grid` it says:
> Database limited using django-mptt
Source: https://www.djangopackages.com/grids/g/cms/

<img width="381" alt="screen shot 2016-06-15 at 20 26 26" src="https://cloud.githubusercontent.com/assets/73378/16092319/a018b2c4-3337-11e6-9e2b-1b82197a8c93.png">

According to my knowledge this is not accurate anymore since it uses `django-treebeard`, right?

(That might tip the felt scale of arguments against django-cms. I do not want that. *smile*)

I would have already edited it.. however I want to be sure what I think is true.
Please give me some feedback and I will update it.

**Comment by FinalAngel** [comment]
@evildmp how can we change this? :D

**Comment by czpython** [comment]
@Eraldo @FinalAngel It's still accurate https://tabo.pe/projects/django-treebeard/docs/2.0/mp_tree.html#treebeard.mp_tree.MP_Node.path.

Basically we're limited by 255 characters that represent the path to a page,
if we increase that number then we risk serious performance issues.

**Comment by Eraldo** [comment]
Okay. Thanks @czpython .. so I will not change it until asked otherwise. :)

**Comment by czpython** [comment]
@Eraldo If you're able to change it, then please do so as we no longer use django-mptt.
Although maybe @evildmp has some input on the text.

**Comment by Eraldo** [comment]
I changed it to "Database limited using django-treebeard" for now -- Until the difference to why wagtail (also using django-treebeard) states "unlimited" is investigated.

**Comment by evildmp** [comment]
I think that this can be safely closed for now, thanks for spotting and fixing it @Eraldo.
