### ISSUE TITLE
Compatibility with django-reversion 2.0

### ISSUE THREAD

**Issue by exploide** [divio/django-cms#5441]
It seems the new version of [django-reversion ](https://github.com/etianen/django-reversion)(since 2.0) breaks django-cms while calling migrate:
```
lib/python3.4/site-packages/cms/utils/reversion_hacks.py", line 18, in <module>
    from reversion.models import Revision, Version, post_revision_commit  # NOQA  # nopyflakes
ImportError: cannot import name 'post_revision_commit'
```
According to their release notes, this signal got removed.

My first idea was to suggest adding version pinning to setup.py until compatibility is achieved, but it seems django-reversion isn't a hard dependency at all. Though, having the user deal with this problem also isn't nice.

**Comment by bartmika** [comment]
Hello, I am having this exact same error. Can we have this fixed?

**Comment by rodolfomartinez** [comment]
+1 :-)

**Comment by czpython** [comment]
Hello,
We're aware of the issue, unfortunately it caught us at an unfortunate time as we're doing multiple refactors of the codebase in preparation for 3.4 and 3.5 and so are currently maxed out.
That said, any PR that fixes is welcome and will be given priority.

**Comment by rodolfomartinez** [comment]
Hi what do you mesn by any PR that fixes is welcome and will be given
priority?

On Tuesday, 21 June 2016, Paulo <notifications@github.com> wrote:

> Hello,
> We're aware of the issue, unfortunately it caught us at an unfortunate
> time as we're doing multiple refactors of the codebase in preparation for
> 3.4 and 3.5 and so are currently maxed out.
> That said, any PR that fixes is welcome and will be given priority.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/divio/django-cms/issues/5441#issuecomment-227554359>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMFGvMOpiaYvxg0FEiQ-cuPQOM-MaCkks5qOEMUgaJpZM4I6-rf>
> .
>


-- 
Sincerely,
Rodolfo Martinez
(519)521-3135 / (281)674-5103
Skype: rodolfo-reimar
CEO The Shooting Star Press inc.
www.LuchaComics.com

Be sure to follow @LuchaComics !

**Comment by yakky** [comment]
@czpython is this a blocker for 3.3.1?

**Comment by rodolfomartinez** [comment]
@bartmika had this issue w the latest release i believe

On Wednesday, 22 June 2016, Iacopo Spalletti <notifications@github.com>
wrote:

> @czpython <https://github.com/czpython> is this a blocker for 3.3.1?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/divio/django-cms/issues/5441#issuecomment-227881020>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMFGjZ2LhQYoV7cVetvIwr2-lyg0gewks5qOafUgaJpZM4I6-rf>
> .
>


-- 
Sincerely,
Rodolfo Martinez
(519)521-3135 / (281)674-5103
Skype: rodolfo-reimar
CEO The Shooting Star Press inc.
www.LuchaComics.com

Be sure to follow @LuchaComics !

**Comment by yakky** [comment]
@rodolfomartinez @bartmika @exploide we can't commit on any ETA for reversion 2.0, but you can just install reversion <2.0 in the meantime

**Comment by alexeykuz** [comment]
@yakky you cant install reversion < 2.0 with Django >= 1.9

**Comment by czpython** [comment]
@yakky The above would make it a blocker for 3.3.1.

@aleray Can you post the error? or a link to the docs that states reversion < 2.0 is not 1.9 compatible?

**Comment by yakky** [comment]
@alexeykuz @czpython django-reversion 1.10+ supports django 1.9 just fine ( https://django-reversion.readthedocs.io/en/stable/changelog.html#id12 + running it in production)

**Comment by czpython** [comment]
Closing as a won't fix for the core of djangoCMS.
Instead, we'll release a third party app which will re-introduce revision support
