### ISSUE TITLE
Duplicator style plugin

### ISSUE THREAD

**Issue by rodolfomartinez** [divio/django-cms#5442]
Summary:
I am migrating about 20 wordpress sites to Django CMS, and one of the WP plugins that I use the most is duplicator. It creates a .zipand .php that I upload to a server and by running the php I restore an exact copy of my site. Its very handy, and a similar function would make life a lot easier for the non technical user such as myself. You can see more on duplicator here:
https://en-ca.wordpress.org/plugins/duplicator/

**Comment by bartmika** [comment]
+1

**Comment by czpython** [comment]
Hello,
Please use the google groups list https://groups.google.com/forum/#!forum/django-cms-developers
to propose new features.
