### ISSUE TITLE
Wordpress XML Import

### ISSUE THREAD

**Issue by rodolfomartinez** [divio/django-cms#5443]
Summary:

Currently Wordpress allows me to create an xml dump which I can transfer to a new site, and it imports my posts, pages, comments etc and downloads relevant media (such as images) from the old site. Could there be a wordpress migration tool that supports these XML files down the road?

**Comment by bartmika** [comment]
+1

**Comment by czpython** [comment]
Hello, please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](django-cms.org/support) page.

In this case, I believe your question is best in the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms).

**Comment by bartmika** [comment]
thank you @czpython
