### ISSUE TITLE
Django CMS 3.3: Page tree burger icon has no effect if your page permissions are restricted

### ISSUE THREAD

**Issue by bartTC** [divio/django-cms#5449]
If your user is restricted to edit only a subset of pages, the burger icon has no effect on click. The 'Legend" icon too. 

![screen shot 2016-06-22 at 18 11 02](https://cloud.githubusercontent.com/assets/1896/16274245/105aadea-38a5-11e6-84e4-b42060301919.png)

I can see the HTML in the source code related to this, it's rendered there, it just doesn't pop up.

The icon works fine if I have permissions to edit all pages, or if I'm a superadmin. A popup pops up with meta info and copy/paste buttons. 

Django-CMS 3.3, Django 1.9.6

**Comment by czpython** [comment]
Thanks for the report.
I noticed this as well but missed to create ticket 👍

**Comment by vxsx** [comment]
@bartTC could you please check if https://github.com/divio/django-cms/pull/5461 fixes this for you?

**Comment by bartTC** [comment]
@vxsx this fixed the bug, thank you all!
