### ISSUE TITLE
Django CMS 3.3: Advanced Permissions popup is just empty if the user has no permission to edit them

### ISSUE THREAD

**Issue by bartTC** [divio/django-cms#5450]
I gave my users access to a subset of pages to edit, but I didn't gave an explicit permission to edit 'advanced settings'.

The menu item for this is disabled (ok)

![](http://d.pr/i/9Qas+)

However the user is still able to access that screen by the bottom of the regular settings

![](http://d.pr/i/7XYk+)

Or by Shift+Click on the settings icon in the page tree.

In both cases the user will just see a blank, gray popup with no information. The backend is triggering a 401 response correctly.

**Comment by czpython** [comment]
@bartTC 
Thanks for reporting.
We're currently working in a cleanup of our permissions system for 3.4
I'll keep this open in the meantime.

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/5532
The shift+click part will be fixed by https://github.com/divio/django-cms/pull/5617
