### ISSUE TITLE
Can't "Add" a subpage even though I gave users permission to.

### ISSUE THREAD

**Issue by bartTC** [divio/django-cms#5451]
*I am not sure if this is misconfiguration on my side or missing functionality.*

I gave my users 'Add/Edit/Delete' permission to a sub-page of the page tree, in this case the "New York" page. 

![screen shot on 2016-06-22 at 18_05_55](https://cloud.githubusercontent.com/assets/1896/16274550/61bf1b16-38a6-11e6-921e-4bd7cf87d788.png)

My understanding is that the user can add pages below the "New York" page but I'm missing the Plus button there.

![](http://d.pr/i/1dpsJ+)

Workaround I found:

If I'm on the New page itself and in edit mode, I can add a sub-page via the menu "Create page > New sub page". This works fine, as expected.

**Comment by bartTC** [comment]
Note that the user can also click the menu item "Create page > New page" which would create a page of at the same page level, which is not allowed. This results in a popup with a response '403 Forbidden' which is correct behavior. However I'd propose to disable that "New page" button since the user has no permission to do so in first place.

**Comment by czpython** [comment]
@bartTC 
Thanks for reporting.
We're currently working in a cleanup of our permissions system for 3.4
I'll keep this open in the meantime.

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/5532
