### ISSUE TITLE
Cannot create any plugins inside Text plugin

### ISSUE THREAD

**Issue by bharling** [divio/django-cms#5460]
For some reason, every time I attempt to add a plugin as a child of a Text plugin now I get a bad request response.

I've tracked it down to here:

https://github.com/divio/django-cms/blob/a238849952032fa8a42d0a4d4c8cfdd405927867/cms/admin/placeholderadmin.py#L247

The placeholderadmin is expecting the plugin_type parameter to be passed in the GET section of the request, but it seems ( at least on my setup ) this is a POST request. Can anyone shed any light?

**Comment by czpython** [comment]
@bharling 
Hello,
Please use the latest djangocms-text-ckeditor.
The compatibility "table" is in the [readme](https://github.com/divio/djangocms-text-ckeditor)

**Comment by bharling** [comment]
I am I think > 

```
pip freeze | grep cms
django-cms==3.3.0
djangocms-admin-style==1.2.3
djangocms-attributes-field==0.0.3
djangocms-column==1.6.0
djangocms-file==1.0
djangocms-grid==1.3.0
djangocms-inherit==0.1.1
djangocms-link==1.7.2
djangocms-picture==1.0.0
djangocms-style==1.7.0
djangocms-table==1.2
djangocms-teaser==0.2.0
djangocms-text-ckeditor==3.0.0
djangocms-video==1.0.0
```

**Comment by bharling** [comment]
This does not manifest on our staging server but does in production, I'm thinking this may be at the server setup level ( we're using apache / mod_proxy for the moment ).

**Comment by darbula** [comment]
Same thing here, using `djangocms 3.3.2` and `djangocms-text-ckeditor 3.1.0` in Django development `runserver` mode.

**Comment by czpython** [comment]
Hello @darbula,
Please use the latest djangocms-text-ckeditor version (3.2.1), there was a static file caching issue which caused the ajax calls to send old GET parameters instead of the new ones.

**Comment by darbula** [comment]
Updated to 3.2.1. and now there is `TypeError: this.editor.getSelection(...) is null` error in console when adding plugin and more or less nothing seems to work from the ckeditor toolbar with various errors in browsers console.

**Comment by darbula** [comment]
Hi @czpython it is solved, this was the static file issue in my project urls.py, sorry for the confusion.

**Comment by alexgustafson** [comment]
I am getting the `read property 'replace' of undefined` error in the console with newest version.

Django==1.10.7
django-cms==3.4.3
html5lib==0.9999999
djangocms-text-ckeditor==3.5.0

appears to be related to the djangocms-text-ckeditor plugin. As soon as I create a new line in the ckeditor and save the content I get the error in the console. When I remove the added line, no error. 
Any pages with more than one ckeditor plugin loaded are no longer editable. 
![screen shot 2017-06-13 at 12 11 04](https://user-images.githubusercontent.com/1044859/27077763-7a01e304-5031-11e7-878e-68b951a0dce1.png)

![screen shot 2017-06-13 at 12 11 31](https://user-images.githubusercontent.com/1044859/27077773-82093cc8-5031-11e7-8f6b-ad654c61eb93.png)
