### ISSUE TITLE
Git merge conflict?

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#5464]
I just tried to do the usual `git fetch upstream && git merge upstream/develop` to re-sync my fork but I get a merge conflict. I work on branches in my fork and haven't committed directly to the `develop` branch. Did someone force push a change or is my git-fu weak? If the latter (which is likely), how do I get my fork back in sync without adding a spurious commit to the develop branch?

    $ git fetch upstream
    $ git merge upstream/develop
    Auto-merging docs/reference/configuration.rst
    Auto-merging CHANGELOG.txt
    CONFLICT (content): Merge conflict in CHANGELOG.txt
    Automatic merge failed; fix conflicts and then commit the result.

    $ git diff
    diff --cc CHANGELOG.txt
    index 6ef59ab,1efe182..0000000
    --- a/CHANGELOG.txt
    +++ b/CHANGELOG.txt
    @@@ -20,6 -20,14 +20,17 @@@
      * Fixed typo in ``AdvancedSettingsForm`` error messages.
      * Fixed long standing bug that prevented apphook endspoints from being
        CSRF exempt.
    ++<<<<<<< HEAD
    ++=======
    + * Changed default value for ``CMS_INTERNAL_IPS``.
    + * Fixed an issue that prevented non superusers from copying all plugins
    +   in a placeholder.
    + * Fixed an issue where plugin permissions where not checked when clearing
    +   a placeholder.
    + * Fixed an issue where plugin permissions where not checked when deleting
    +   a page or page translation.
    + * Added support for tiered ``CMS_PLACEHOLDER_CONF``.
    ++>>>>>>> upstream/develop

**Comment by czpython** [comment]
@jsma 
Hi there,
We force pushed the develop branch to be in sync with the 3.3.x branch.
All prs should target the release/3.3.x branch unless they've been approved for 3.4.x (develop).

**Comment by jsma** [comment]
Ah, so I shouldn't even be sync-ing the develop branch anymore then? I'll have to unlearn that old habit.
