### ISSUE TITLE
The BACKEND key is missing from the TEMPLATES setting in the documentation

### ISSUE THREAD

**Issue by avoine** [divio/django-cms#5465]
In http://docs.django-cms.org/en/develop/how_to/install.html#configuring-your-project-for-django-cms
It shows how to configure the templates with django > 1.8 but it's missing the BACKEND key.
It should be:

<pre>
 TEMPLATES = [
     {
          'BACKEND': 'django.template.backends.django.DjangoTemplates',
...
    }
]
</pre>

**Comment by FinalAngel** [comment]
Thanks for the report @avoine, would you be able to submit a PR for this?

**Comment by evildmp** [comment]
Thanks for the report. This issue is addressed in #5826, which completely rewrites this section of the documentation.
