### ISSUE TITLE
Jquery error in admin when I use PageSmartLinkField in my models

### ISSUE THREAD

**Issue by V1ce** [divio/django-cms#5476]
Hi,

Before upgrade django-cms to 3.3 from 3.2.5 i was able to re-use the PageSmartiLinkField in my own models, but since the upgrade i now get jquery errors when i go to the model edition in the admin. 

This looks like a conflict with my other js files. i got this : 

- select2.js : L22, $ is undefined
- forms.pagesmartlinkwidget.js : L19, $ is not a function
- In the js part of admin "add" page : L339, CMS.$ is not a function

I got this in the popup edition with toolbar and in the admin site directly. In the admin site i don't load js plugins so this is really a conflict?

Other thing, when i go to the "advanced settings" of a page, where the PageSmartlink widget is used, i don't got these errors.

I load jquery in the "head" of my base.html with some other js files, and i load some other js file in the footer too.

Im not very familiar with these history of js conflict, i would appreciate if someone can help for understand this.

Thanks

**Comment by vxsx** [comment]
Hi, I haven't seen this kind of error before. It would be helpful if you could provide the minimal example to replicate the issue.

Also, could you try reproducing the issue on latest `release/3.3.x` branch?

**Comment by V1ce** [comment]
Django 1.9.7
python 3.4.2
django-cms 3.3.0

Here my current use of PageSmartLinkField in my "news" app for the project "bgl".

**bgl/forms.py** : global PageSmartLinkField form extended by my apps

```python
from django import forms
from django.utils.translation import ugettext_lazy as _
from cms.forms.fields import PageSmartLinkField
from cms.utils.i18n import get_language_tuple
from django.forms.widgets import HiddenInput
from django.utils.translation import get_language

class LinkForm(forms.ModelForm):

    lien  = PageSmartLinkField(label=_('Redirect'), required=False,
                                  help_text=_('Entrer une url valide ou sélectionner une page'),
                                  placeholder_text=_('Entrez adresse ou recherche'),
                                  ajax_view='admin:cms_page_get_published_pagelist',
                                  
    )
    language = forms.ChoiceField(label=_("Language"),required=False, choices=get_language_tuple(),
                                 help_text=_('The current language of the content fields.'))
    
    class Meta:
        exclude = ('language', )
        
    def __init__(self, *args, **kwargs):
       super(LinkForm, self).__init__(*args, **kwargs)
       self.fields['language'].widget = HiddenInput()
    
       if not self.fields['language'].initial:
           self.fields['language'].initial = get_language()
    
       if 'lien' in self.fields:
           self.fields['lien'].widget.language = self.fields['language'].initial
```
honnestly i don't understand these lines... i was able to re-use this with help from this page : 
http://vivazzi.ru/it/page-smart-link-widget-error/
because i got errors with language field when i try to re-use it without override init method and use a language field.

**news/models.py**
```python
class Actualite(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    lien = models.CharField(max_length=2048, null=True, blank = True)
```    
**news/admin.py**
```python

from bgl.forms import LinkForm

class NewsLinkForm(LinkForm):
    class Meta:  
        model = Actualite
        exclude = ('language', )

class ActuAdmin(PlaceholderAdminMixin,admin.ModelAdmin):
    form = NewsLinkForm
```

**Comment by vxsx** [comment]
It seems like this is a regression that started in 3.3.0 and worsened in 3.3.1 in this [commit](https://github.com/divio/django-cms/commit/a44cf25d6d5fd63cd2e9bd2ad1b5e14ae15c7d7b)

We no longer load the admin bundle in widgets, which causes the error on non-cms pages

Temporary fix would be to add this to the class that uses the widget:

```python
from cms.utils.urlutils import static_with_version

...

class Media:
    js = (
        static_with_version('cms/js/dist/bundle.admin.base.min.js'),
    )

```

**Comment by macolo** [comment]
I also see another script failing:

`dropzone.init.js:106 Uncaught ReferenceError: jQuery is not defined`

**Comment by vxsx** [comment]
@macolo is looks like a AdminFileWidget from django-filer's widget
weird, they depend on django.jQuery there, not on the CMS one

**Comment by V1ce** [comment]
Thanks for your answer.

After add the media class in my forms the js file is loaded in the model edition but i got new jquery error : 


- select2.js : L22, $ is undefined
- forms.pagesmartlinkwidget.js : L19, $ is not a function
- **In the js part of admin "add" page : L355, CMS.PageSmartLinkWidget is not a constructor**



**bgl/forms.py**

```python

class LinkForm(forms.ModelForm):

    lien  = PageSmartLinkField(label=_('Redirect'), required=False,
                                  ajax_view='admin:cms_page_get_published_pagelist' )
    language =   forms.ChoiceField(label=_("Language"),required=False,choices=get_language_tuple(),
                                 help_text=_('The current language of the content fields.'))

    class Media:
        js = (
            static_with_version('cms/js/dist/bundle.admin.base.min.js'),
        )

    class Meta:
        exclude = ('language', )

    def __init__(self, *args, **kwargs):
       super(LinkForm, self).__init__(*args, **kwargs)
       self.fields['language'].widget = HiddenInput()

       if not self.fields['language'].initial:
           self.fields['language'].initial = get_language()

       if 'lien' in self.fields:
           self.fields['lien'].widget.language = self.fields['language'].initial

```

**Comment by vxsx** [comment]
@V1ce could you please try this branch https://github.com/divio/django-cms/pull/5546 ?

**Comment by V1ce** [comment]
After install this branch, remove static files and re-collect i got same error : 

https://github.com/divio/django-cms/tree/f527425d1b7a06d782f96b55a25df75a2de54732

**Comment by vxsx** [comment]
Hmm, this is weird, could you try following steps @V1ce ?

```
pip uninstall django-cms
pip install https://github.com/divio/django-cms/archive/release/3.3.x.zip#egg=django-cms
find . -name '*.pyc' -delete
```

and then restart the server and refresh the page with clearing cache

**Comment by V1ce** [comment]
It now works !! Thanks for your time
