### ISSUE TITLE
Caching CustomPlugin depending on the Placeholder it is placed

### ISSUE THREAD

**Issue by alamasfu10** [divio/django-cms#5482]
I was wondering if is there any workaround to not cache plugins in specific placeholders.
Let's say I have a CustomPlugin, and I want this plugin to be cached everywhere except if it is inside a `{% static_placeholder 'special_placeholder' %}`
The `cache = False` flag in the definition of my CustomPlugin does not do what I want (I want this plugin to be cached or not depending on the placeholder it is included). The global settings CMS_PLUGIN_CACHE and CMS_PLACEHOLDER_CACHE don't fit my needs because of the same.

**Comment by czpython** [comment]
@alamasfu10 
Hello there,
Please post support related questions to the google groups or other support channel.
You can see all the available channels [here](https://www.django-cms.org/en/support/)
