### ISSUE TITLE
Option 'name' in CMS_PLACEHOLDER_CONF ignored

### ISSUE THREAD

**Issue by TheDeadOne** [divio/django-cms#5492]
Option 'name' is ignored If template name specified before placeholder name

```
CMS_PLACEHOLDER_CONF = {
    'some_placeholder': {
        'plugins': ['TextPlugin'],
        'name': 'Some localized name',
    },
    'some_template.html another_placeholder': {
        'plugins': ['TextPlugin'],
        'name': 'Another localized name',
    },
}
```

The first work, but the second is not.

**Comment by yakky** [comment]
@TheDeadOne why django CMS version are you using?

**Comment by TheDeadOne** [comment]
@yakky 3.3.0

**Comment by yakky** [comment]
@czpython I'll take this myself, as I want to check what the new placeholderconf changed in this respect

**Comment by czpython** [comment]
@yakky Are you able to look into this today? We'll be releasing soon, otherwise we can push it for 3.3.2

**Comment by yakky** [comment]
Confirmed. I'll send a PR later
