### ISSUE TITLE
Register Page and Title extensions into the pool with decorator.

### ISSUE THREAD

**Issue by vstoykov** [divio/django-cms#5493]
I think that will be more convenient instead of using

    class MyPageExtension(PageExtension):
        my_field = models.CharField()

    extension_pool.register(MyPageExtension)

Registering to happen with decorator

    @extension_pool.register
    class MyPageExtension(PageExtension):
        my_field = models.CharField()

The easiest way to achieve this is by adding returning the object in `register` (https://github.com/divio/django-cms/blob/release/3.3.x/cms/extensions/extension_pool.py#L12) after everything is done.

**Comment by czpython** [comment]
Personally, I like to put all registrations at the bottom of the file (plugins, admin classes, etc.)
That said, I don't see an issue with supporting both as we do with plugins.

**Comment by yakky** [comment]
I like the decorator style

**Comment by czpython** [comment]
Fixed by #5495
