### ISSUE TITLE
Make it possible to use multi-table (concrete) inheritance for Page and Title extensions

### ISSUE THREAD

**Issue by vstoykov** [divio/django-cms#5494]
I just realized that when I have multi-table inheritance for TitleExtension (I guess is the same for PageExtension) and try to publish the page django-cms fails to copy the extension instance and instead save the same instance.

The reason behind this is because `BaseExtension.copy_to_public` method (https://github.com/divio/django-cms/blob/release/3.3.x/cms/extensions/models.py#L64-L87) does not nullify pk fields of parent model(s).

I'm using Django 1.8 and DjangoCMS 3.3.

I created a workaround in my project which involves overwriting whole  `copy_to_public` method without calling `super` which is totally bad thing (If I want to upgrade the CMS in the future).

I can prepare e PR with proposed solution.

**Comment by czpython** [comment]
Fixed by 0c1ef4ffbc74bd2955afecb1a843f7574f0aa9fa
