### ISSUE TITLE
Find visible plugins with multiple templates and static placeholders

### ISSUE THREAD

**Issue by igorpejic** [divio/django-cms#5512]
Hi,

is there any way to check if a Plugin is visible (published) anywhere in a page?
I have multiple pages with different templates each. 
These templates have different static placeholders which have different plugins.

The problem is some plugins are present on templates which are not activated and therefore I don't want to get those in my query.

Is there a method to show only the plugins which are visible on the published pages?
Same question: Is there a method to show only the plugins which appear on the activated templates?

Thank you in advance.

**Comment by czpython** [comment]
Hello, please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](django-cms.org/support) page.
