### ISSUE TITLE
Swipe up or down starting from a disabled menu voice doesn't scroll the menu

### ISSUE THREAD

**Issue by itbabu** [divio/django-cms#5518]
A swipe down should scroll the menu up. This doesn't happen if the swipe starts from a disabled menu.
This is very noticeable if there are a lot of disabled menu voices.

![swipe](https://cloud.githubusercontent.com/assets/650691/16691158/be3154f4-452b-11e6-994f-c8b080ab36d3.png)

I can reproduce this on:
- my android phone with Chrome and Firefox
- my laptop with chrome-devtools and the device toolbar

**Comment by czpython** [comment]
Fixed on 3.3.2
