### ISSUE TITLE
Feature Request: Site Configs

### ISSUE THREAD

**Issue by leesolway** [divio/django-cms#5520]
It would be helpful to have some in-built CMS supported method that would allow a user to define settings for a specific site..

Settings could include items such as: Google Analytics Id, Theme, Logo and Template paths to name a few.

The CMS already provides ways to do page settings but a site settings framework that was cached and possibly dynamic would support a multi-site or even a reusable setup.

**Comment by yakky** [comment]
I think this is way better handled in a separate app

**Comment by czpython** [comment]
Hello, please make sure to submit questions or feature requests within the appropriate channels.
You can find additional information on our [support](django-cms.org/support) page.

In this case, I believe your question is best in the [Developers Mailing List](https://groups.google.com/forum/#!forum/django-cms-developers).
