### ISSUE TITLE
Allow href="tel:..."

### ISSUE THREAD

**Issue by HerHde** [divio/django-cms#5526]
Ahoi guys,
although I couldn't find any official definition, it would be helpful to allow *tel:*-values in `href` attributes like [this](http://stackoverflow.com/questions/17219688/href-tel-and-mobile-numbers).
At the moment such telephone numbers disappear when I'm saving the site, even if I've added them in the HTML-Code of a text structure.

Greetings
HerHde

**Comment by yakky** [comment]
Check djangocms-link plugin https://github.com/divio/djangocms-link that supports "tel:" prefix. Or you can configure text plugin to keep during sanitization (check https://github.com/divio/djangocms-text-ckeditor documentation)
