### ISSUE TITLE
Add a management command for enabling permissions

### ISSUE THREAD

**Issue by rasca** [divio/django-cms#5527]
When enabling permissions in an existing project that had them turned off there are no users (page) and no user groups (page).

It would be nice to have a management command that creates all the necessary PageUser and PageUserGroup models.

**Comment by czpython** [comment]
Closing as a won't fix.
The 3.4 release will allow admins to create page users from an existing auth.User, making this a command would introduce several issues because if a project has over 100k users and enables permissions, then this would convert all 100k users to page users which is not ideal.
