### ISSUE TITLE
Make note of need for migrations in plugin tutorial

### ISSUE THREAD

**Issue by pdbethke** [divio/django-cms#5555]
Just a suggestion from a user working to develop a new CMS plugin that uses a model -- it may seem intuitive to some django programmers but you might want to add a line in the http://docs.django-cms.org/en/release-3.3.x/how_to/custom_plugins.html#storing-configuration tutorial noting that you should run **manage.py makemigrations** and **manage.py migrate** following your model creation to properly set up the configuration fields -  it tripped me up a little before I realized what was the issue when I went to remove or save the newly created plugin.

**Comment by evildmp** [comment]
Thanks, fixed in https://github.com/divio/django-cms/pull/5566.
