### ISSUE TITLE
Diff of History

### ISSUE THREAD

**Issue by doctormo** [divio/django-cms#5556]
The inkscape project has worked on a diff feature of django-cms, it's currently a separate app in our repository, but I'm brining it to django-cms project's attention to see if it's useful for other users.

See screenshots for examples. It follows the wikia diff form pattern and uses reversion with diff_match_patch to produce colour diff output.

![01-history](https://cloud.githubusercontent.com/assets/589384/16989492/65f770ee-4e62-11e6-9297-e428a0d46da2.png)
![02-diff](https://cloud.githubusercontent.com/assets/589384/16989495/6791cf9e-4e62-11e6-9625-49b03e67af37.png)

**Comment by czpython** [comment]
@doctormo 
This looks amazing!
Would you mind posting on the [django-cms-developers group](https://groups.google.com/forum/#!forum/django-cms-developers).

Thanks!
