### ISSUE TITLE
render_placeholder tag raise exception

### ISSUE THREAD

**Issue by hoerin** [divio/django-cms#5557]
I created an simple app with Apphook.
However I got the following exception.

> Django Version:	1.8.9
> Exception Type:	AttributeError
> Exception Value:	'tuple' object has no attribute 'has_change_permission'
> Exception Location:	/cms/templatetags/cms_tags.py in _get_value, line 1142
> Python Version:	3.4.2

/cms/templatetags/cms_tags.py in _get_value

```
1138        if isinstance(placeholder, string_types):
1139            placeholder = PlaceholderModel.objects.get(slot=placeholder)
1140        if not hasattr(request, 'placeholders'):
1141            request.placeholders = {}
1142                    perms = (placeholder.has_change_permission(request) or not placeholder.cache_placeholder)
1143        if not perms or placeholder.slot not in request.placeholders:
1144            request.placeholders[placeholder.slot] = (placeholder, perms)
1145        else:
1146            request.placeholders[placeholder.slot] = (
1147                placeholder, perms and request.placeholders[placeholder.slot][1]
1148            )
```

The "placeholder" variable has this tuple.
`(<cms.models.fields.PlaceholderField>,)`

I think the variable should be an instance of Placeholder model.
Could someone help me?

My simple app is like this.

models.py
```
class News(models.Model):
    description = PlaceholderField('news_description'),
```

admin.py
```
class NewsAdmin(PlaceholderAdminMixin, admin.ModelAdmin):
    pass

admin.site.register(News, NewsAdmin)
```

views.py
```
class NewsDetailView(DetailView):
    model = News
```

template.html
`{% render_placeholder object.description %}`

**Comment by czpython** [comment]
@hoerin Hi there, is that a typo on your `News` model?

**Comment by hoerin** [comment]
@czpython OMG you are correct! I removed the typo and run again. it completly works!!
Thanks so much. I was suffering all day today :'-D
