### ISSUE TITLE
2.4.x branch - HTML5LIB

### ISSUE THREAD

**Issue by mikedingjan** [divio/django-cms#5559]
Html5lib has dropped the Sanitizer module in their latest version. Since django-cms doesn't have any version pinned, builds will fail.

Fixed it by manually installing version `0.9999999` maybe this can be defined in the setup.py?

**Comment by czpython** [comment]
@mikedingjan 
Hello,
The 2.4.x releases are no longer supported.
You can easily pin the htlm5lib version in your project requirements to avoid the CMS installing the latest.

Regarding the 3.x releases, we'll probably remove html5lib as a dependency.
