### ISSUE TITLE
"Missing Flash" error with djangocms-video, Django-cms 3.3.x, django 1.8.xx

### ISSUE THREAD

**Issue by chdeleuze** [divio/django-cms#5561]
Hello,

The plugin djangocms-video always raised :"missing flash" error with Django-cms 3.3.x (test on 3.3.0 and 3.3.1) and django 1.8.xx (test on 1.8.13 and 1.8.14) on fresh install.

When I try the same with django-cms 3.2.5 the videos are well displayed.

Regards,
c deleuze

**Comment by chdeleuze** [comment]
Missing folder and files into 3.3:
static\cms\swf\expressInstall.swf
static\cms\swf\player.swf
static\cms\js\libs\swfobject.min.js

**Comment by czpython** [comment]
Hello @chdeleuze,
Flash support was officially deprecated by Adobe.
There's a ticket open on djangocms-video to no longer use a flash player but it's still in early stages.

**Comment by jedie** [comment]
https://github.com/divio/djangocms-video/issues/1 ;)
