### ISSUE TITLE
Unable to create an initial page when DEBUG = False 

### ISSUE THREAD

**Issue by sephii** [divio/django-cms#5562]
With `DEBUG = False` whatever you do if you don't have any content in your database will lead you to a 404 page (even if you go to http://example.com/?edit), making you unable to do anything on your website. I'm not sure how I've never dealt with this issue before, having been a DjangoCMS user for quite some time now, so I might just be missing something. Anyway here's the code that fires up the "new page wizard" if there's no content and you're in DEBUG mode: https://github.com/divio/django-cms/blob/release/3.3.x/cms/page_rendering.py#L59. According to this code there's no way to get this wizard with debug mode disabled and without having any page in your database.

According to the docs (http://docs.django-cms.org/en/release-3.3.x/user/tutorial/index.html):

> When you visit a brand new site for the first time, you will be invited to log in.

I'd suggest to either fix these instructions to explain how to create the first page, or fix the code to make the process more user-friendly (I still haven't found a proper way to create my first page except enabling DEBUG on prod and then create the initial page).

**Comment by czpython** [comment]
@sephii 
Hi there,
which djangoCMS and Django versions are you using?

Also I assume you're accessing the page as a logged in superuser?

**Comment by sephii** [comment]
Sorry, I'm using DjangoCMS 3.3.1 and Django 1.9.7. I tried going to `/admin/` first and log in, I can access the admin without any problem but going to `/?edit` (or `/en/?edit` to be precise) still returns a 404.

You can easily reproduce the issue by creating a project with djangocms-installer and set `DEBUG=False` and `ALLOWED_HOSTS`.

**Comment by evildmp** [comment]
I can replicate this and we have agreed it's a bug - thanks for reporting, it'll be fixed.

**Comment by czpython** [comment]
Closed by https://github.com/divio/django-cms/pull/5759
