### ISSUE TITLE
Plugins not working with conditional extend tag

### ISSUE THREAD

**Issue by DharienNightroad** [divio/django-cms#5563]
I have this code at the top of a page template. With that, any placeholders and plugins don't show. I cant edit a page structure.

{% extends request.user.is_authenticated|yesno:"member_template.html,base.html" %}

If I do This

{% extends "member_template.html" %}

or this

{% extends "base.html" %}

Everything works fine. Is there a way to make the first extend work?

**Comment by FinalAngel** [comment]
Hello, please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](django-cms.org/support) page.
