### ISSUE TITLE
Migrate from 3.0 to 3.3.1

### ISSUE THREAD

**Issue by davidmaxs** [divio/django-cms#5569]
Hello, my problem : I migrate from 3.0 ( django 1.6 ) to 3.3 ( django 1.9 ) . In pip lifted up version of the 3.0 to 3.3.1 immediately and django to 1.9 - skipped steps 3.0 to 3.1 to 3.2 .... I use the documentation - changing mptt on Treebeard , south migrations will replace django . Then I do:
manage.py migrate cms 0002 --fake
manage.py migrate cms --run - syncdb
manage.py migrate --fake
manage.py migrate --run - syncdb
The application runs , admin - displays out, however methods do not work . Browsing the model everywhere have Page path = '' , depth = 0 . I'll be grateful for the answer .

**Comment by czpython** [comment]
Hello, please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Users Mailing List](https://groups.google.com/forum/#!forum/django-cms).
