### ISSUE TITLE
What about to add a page copied signal?!

### ISSUE THREAD

**Issue by philippeowagner** [divio/django-cms#5570]
We are missing a signal that will be fired after a page was copied using `page.copy_page`? 
Would this be helpful for anybody else?

**Comment by czpython** [comment]
Hello, please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](django-cms.org/support) page.

In this case, I believe your question is best in the [Developers Mailing List](https://groups.google.com/forum/#!forum/django-cms-developers).

**Comment by philippeowagner** [comment]
I just posted on the dev mailing list as suggested: https://groups.google.com/forum/#!topic/django-cms-developers/iF4CUxyEtpo
