### ISSUE TITLE
iframe Add plugin dualog in ckeditor inusable if page is very long...

### ISSUE THREAD

**Issue by jedie** [divio/django-cms#5572]
e.g.:

* Edit a ckeditor page with very long text
* try to add a link
* Everything is ok:

![djangocms_ui 1 problems](https://cloud.githubusercontent.com/assets/71315/17207943/faca8fa8-54b6-11e6-9734-28562b425c9f.PNG)

Now the problem:

* Edit a ckeditor page with very long text
* **maximize** the edit window
* Add a link (or a other plugin)

The opened "Add CMS Plugin" dialog is unuseable, because it's too heigh and can't be resized:

----

![djangocms_ui 2 problems](https://cloud.githubusercontent.com/assets/71315/17208058/805429e0-54b7-11e6-9dd2-2c76d4d0ba01.PNG)

----

![djangocms_ui problems](https://cloud.githubusercontent.com/assets/71315/17207735/2cd34ca2-54b6-11e6-9a0c-77ce1c00b5cb.PNG)

**Comment by jedie** [comment]
Django-CMS v3.3.1

**Comment by vxsx** [comment]
Thanks for the report, we'll look into it
