### ISSUE TITLE
Template not showing up when having an Umlaut (äöü...), etc. in CMS_TEMPLATES. 

### ISSUE THREAD

**Issue by philippeowagner** [divio/django-cms#5573]
_CMS 3.3.0_

This works:

![screen shot 2016-07-21 at 10 45 51](https://cloud.githubusercontent.com/assets/113043/17208475/33808f1c-54b9-11e6-8ee2-f65721b57c88.png)

    CMS_TEMPLATES = (
       ...
        ('cms/smarterzuegeln_index_template.html', 'Smarter Zuegeln Vorlage'),
       ...
    ) 

This does NOT work:

    CMS_TEMPLATES = (
       ...
        ('cms/smarterzuegeln_index_template.html', 'Smarter Zügeln Vorlage'),
       ...
    )

**Comment by czpython** [comment]
@philippeowagner 
I've looked into this a bit more, looks like you're using Python 2.7 if so then you need to use a unicode string to represent the non-ascii label.

So it should look like ``('cms/smarterzuegeln_index_template.html', u'Smarter Zügeln Vorlage'),``
