### ISSUE TITLE
Page not shown in link plugin.

### ISSUE THREAD

**Issue by philippeowagner** [divio/django-cms#5574]
_CMS 3.2.x_

Page tree shows page "Prozesse & Produktivität" correctly:

![screen shot 2016-07-28 at 11 51 34](https://cloud.githubusercontent.com/assets/113043/17208705/1166a1b8-54ba-11e6-95a1-aaee4d101fab.png)

Can't choose page "Prozesse & Produktivität",  page is not present:

![screen shot 2016-07-28 at 11 53 19](https://cloud.githubusercontent.com/assets/113043/17208712/1565760e-54ba-11e6-8360-03a38e7bd04b.png)

**Comment by philippeowagner** [comment]
Our client had an _ä_ in the `reverse_id`. No success when changing this. 

Changing title from **Having an Umlaut (äöü...), etc. in page title will not show page in link plugin.** to **Page not shown in link plugin.**.

**Comment by philippeowagner** [comment]
The page was broken in some way... Dropped it and created a new one. The re-created page showed up as expected.

**Comment by evildmp** [comment]
Hi @philippeowagner. I still suspect the title somehow. Can you recreate the problem?

**Comment by philippeowagner** [comment]
I'm sorry can't provide more info at this one. Due to deadlines we dropped the page and re-created it. The new page had no issues. I close this and reopen in case we can provide valuable information...
