### ISSUE TITLE
Error when removing plugin

### ISSUE THREAD

**Issue by minotaurdsp** [divio/django-cms#5575]
<div id="summary">
  <h1>KeyError at /lv/pakalpojumi/</h1>
  <pre class="exception_value">u'CMSSamplePlugin'</pre>
  <table class="meta">

    <tbody><tr>
      <th>Request Method:</th>
      <td>GET</td>
    </tr>
    <tr>
      <th>Request URL:</th>
      <td>http://127.0.0.1:8000/lv/pakalpojumi/?edit&amp;language=lv</td>
    </tr>

    <tr>
      <th>Django Version:</th>
      <td>1.8.13</td>
    </tr>

    <tr>
      <th>Exception Type:</th>
      <td>KeyError</td>
    </tr>

    <tr>
      <th>Exception Value:</th>
      <td><pre>u'CMSSamplePlugin'</pre></td>
    </tr>

    <tr>
      <th>Exception Location:</th>
      <td>/home/p/CMS/django_cms/env/local/lib/python2.7/site-packages/cms/plugin_pool.py in get_plugin, line 201</td>
    </tr>

    <tr>
      <th>Python Executable:</th>
      <td>/home/p/CMS/django_cms/env/bin/python</td>
    </tr>
    <tr>
      <th>Python Version:</th>
      <td>2.7.11</td>
    </tr>
    <tr>
      <th>Python Path:</th>
      <td><pre>['/home/p/CMS/django_cms',
 '/home/p/CMS/django_cms/env/lib/python2.7',
 '/home/p/CMS/django_cms/env/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/p/CMS/django_cms/env/lib/python2.7/lib-tk',
 '/home/p/CMS/django_cms/env/lib/python2.7/lib-old',
 '/home/p/CMS/django_cms/env/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/p/CMS/django_cms/env/local/lib/python2.7/site-packages']</pre></td>
    </tr>
    <tr>
      <th>Server time:</th>
      <td>pk, 29 Jūl 2016 14:50:45 +0300</td>
    </tr>
  </tbody></table>
</div>

**Comment by czpython** [comment]
@minotaurdsp Hello there,
When removing a plugin, please use `./manage.py cms uninstall plugins CMSSamplePlugin`.

**Comment by minotaurdsp** [comment]
Hello !
Yes it works 
Thank you very much
Also maybe you know how to remove a custom made page templates from db ? 
if i make custom_block.html and delete from setting.py CMS_TEMPLATES  the django_cms keep looking old template path.
I solved this manually change old template path from database table cms_page  but it is Hacking, can I solve it differently.
