### ISSUE TITLE
html5lib requires setuptools version 18.5 or above

### ISSUE THREAD

**Issue by saeed-222** [divio/django-cms#5577]
I use `django-cms==3.3.1` as a requirement in my `setup.py` and when I try to install my own package via `python setup.py install`, I get the following error:
``
html5lib requires setuptools version 18.5 or above; please upgrade before installing (you have 18.2)
``

Since `html5lib>=0.9999999` is included in django-cms `setup.py`, Can we think of a solution?

**Comment by czpython** [comment]
@saeed-222 We've removed html5lib as a dependency and will release 3.3.2 soon.
