### ISSUE TITLE
instance.child_plugin_instances is always 'None' in ModelForm.__init__

### ISSUE THREAD

**Issue by macolo** [divio/django-cms#5579]
A plugin has direct child plugins added in the DjangoCMS Structure Mode. When I try to access these child plugins in the parent model's custom form I see that it is set to 'None'.

Shouldn't it contain the child plugin instances? All other properties are set, including `numchild` which shows 2.

The following form is configured as the custom form for `GoogleMapPlugin` in `cms_plugins.py`. GoogleMapPlugin inherits from `CMSPluginBase`.
```
class GoogleMapForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(GoogleMapForm, self).__init__(*args, **kwargs)
        instance = kwargs.pop('instance', None)
        if instance:
            locations = instance.child_plugin_instances()
            # locations is now set to 'None', should contain child plugins.
            ...
```

Background: in the form of the parent plugin I would like to have a select widget that contains a reference to a child plugin.

**Comment by czpython** [comment]
Hello @macolo , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Users Mailing List](https://groups.google.com/forum/#!forum/django-cms).
