### ISSUE TITLE
How to upgrade DjangoCMS 3.2.5 -> 3.3.1

### ISSUE THREAD

**Issue by matzegebbe** [divio/django-cms#5580]
I am new to DjangoCMS. I use Version 3.2.5. Now I want to upgrade to the newest version. How should i update my version? I tried ```django-admin.py```

But there is no update. Is this not foreseen? I tried it with just simple

```pip install --upgrade django-cms```

but after that my installation was broken. What is the offical way? I only found tutorials to install djangocms but not to upgrade it

http://docs.django-cms.org/en/release-3.3.x/introduction/install.html

Or do I have to migrate with every update? Thanks!

**Comment by piotrjakimiak** [comment]
`pip install django-cms==3.3.1`
But You should also upgrade plugins to be compatible with new DjangoCms version.

**Comment by czpython** [comment]
Hello @matzegebbe, please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Users Mailing List](https://groups.google.com/forum/#!forum/django-cms).

**Comment by matzegebbe** [comment]
Sorry & thank you!
