### ISSUE TITLE
After removing template from django settings.py  django_cms keep looking old template path

### ISSUE THREAD

**Issue by minotaurdsp** [divio/django-cms#5583]
Hello ! ,i have some troubles with templating.
if i make custom_block.html and delete from setting.py CMS_TEMPLATES the django_cms keep looking old template path.
I solved this manually change old template path from database table cms_page but it is Hacking, can I solve it differently.

**Comment by evildmp** [comment]
I don't understand the problem as reported - can you clarify?

It would help if you showed your ``CMS_TEMPLATES`` before and after, and the contents of the field in the ``cms_page`` table.

**Comment by minotaurdsp** [comment]
Thanks !
First i add new template on  settings.py file in CMS_TEMPLATES
CMS_TEMPLATES = (
    ## Customize this
    ('page.html', 'Page'),
    ('feature.html', 'Page with Feature'),
   ` ('_cms/pieces/content_primary.html', 'Content Base'),`
)
But I was not careful and I had pointed an incorrect location  ` ('_cms/pieces/content_primary.html', 'Content Base'),`
And get error template does not exits , i think okey thats fine i fix the incorect location and error disappear.

i change wrong template path pointed in CMS_TEMPLATES 

from 
CMS_TEMPLATES = (
    ## Customize this
    ('page.html', 'Page'),
    ('feature.html', 'Page with Feature'),
   ` ('**_**cms/pieces/content_primary.html', 'Content Base'),`
)
to
CMS_TEMPLATES = (
    ## Customize this
    ('page.html', 'Page'),
    ('feature.html', 'Page with Feature'),
   ` ('cms/pieces/content_primary.html', 'Content Base'),`
)
then i kill django_cms ctr+C  and start server python manage.py runserver *.*.*.*:8999
   
But error is still there and not fixed.
then I thought, if django not updating information about whats hapenning in setting.py CMS_TEMPLATES dict path value then maybe it will react if I I delete the template at all.
Then after a few minutes  i remove the new added template from CMS_TEMPLATES dict 

Uh oh  error is still there. 
then I get tired and start to look for the database tables where the location information is stored.
i fix the incorect template path location in cms_page table  and then erro fixed.


--------------------------------------------------------------------------------------------------------------------------
cms_page table content
"122";"script";"root";"2016-07-26 15:59:06.482999+03";"2016-07-28 18:29:14.153505+03";"2016-07-26 16:00:38.761232+03";"";FALSE;FALSE;"";"''";"page.html";FALSE;;TRUE;"''";"";TRUE;"lv";0;0;;124;1;1;4;"0008"
"124";"root";"root";"2016-07-26 16:00:38.775039+03";"2016-07-27 12:39:21.20075+03";"2016-07-26 16:00:38.761232+03";"";TRUE;FALSE;"";"''";"INHERIT";FALSE;;TRUE;"''";"";FALSE;"lv";0;0;;122;1;1;4;"000B"
"128";"root";"root";"2016-07-26 16:03:12.612288+03";"2016-07-29 15:37:13.123423+03";"2016-07-26 16:03:18.011133+03";"";TRUE;FALSE;"";"''";"cms/pieces/service.html";FALSE;;FALSE;"''";"";TRUE;"lv";0;0;122;129;1;2;0;"00080002"
"129";"root";"root";"2016-07-26 16:03:18.022546+03";"2016-07-27 14:44:28.923268+03";"2016-07-26 16:03:18.011133+03";"";TRUE;FALSE;"";"";"INHERIT";FALSE;;FALSE;"''";"";FALSE;"lv";0;0;124;128;1;2;0;"000B0002"
"133";"root";"root";"2016-07-26 16:33:41.586677+03";"2016-07-28 18:27:31.051211+03";"2016-07-26 17:14:37.733701+03";"";TRUE;FALSE;"";"''";"cms/pieces/content_primary.html";FALSE;;FALSE;"''";"";TRUE;"lv";0;0;122;134;1;2;0;"00080003"
"134";"root";"root";"2016-07-26 17:14:37.749855+03";"2016-07-26 17:15:11.297482+03";"2016-07-26 17:14:37.733701+03";"";FALSE;FALSE;"";"";"feature.html";FALSE;;FALSE;"''";"";FALSE;"lv";0;0;124;133;1;2;0;"000B0003"
"136";"root";"root";"2016-07-27 12:39:41.480755+03";"2016-07-28 18:09:25.447247+03";"2016-07-27 12:43:56.320121+03";"";TRUE;FALSE;"";"''";"cms/pieces/content_primary.html";FALSE;;FALSE;"''";"";TRUE;"lv";0;0;122;137;1;2;0;"00080001"
"137";"root";"root";"2016-07-27 12:43:56.32986+03";"2016-07-27 12:44:07.639143+03";"2016-07-27 12:43:56.320121+03";"";TRUE;FALSE;"";"''";"page.html";FALSE;;FALSE;"''";"";FALSE;"lv";0;0;124;136;1;2;0;"000B0001"
"139";"root";"root";"2016-07-27 14:46:16.175364+03";"2016-07-28 18:28:19.989519+03";"2016-07-27 14:47:04.839499+03";"";TRUE;FALSE;"";"''";"cms/pieces/content_primary.html";FALSE;;FALSE;"''";"";TRUE;"lv";0;0;122;140;1;2;0;"00080004"
"140";"root";"root";"2016-07-27 14:47:04.857872+03";"2016-07-27 14:47:15.54873+03";"2016-07-27 14:47:04.839499+03";"";TRUE;FALSE;"";"";"INHERIT";FALSE;;FALSE;"''";"";FALSE;"lv";0;0;124;139;1;2;0;"000B0004"
"";"";"";"";"";"";"";;;"";"";"";;;;"";"";;"";;;;;;;;""


befor
CMS_TEMPLATES = (
    ## Customize this
    ('page.html', 'Page'),
    ('feature.html', 'Page with Feature'),
    ('cms/pieces/content.html', 'Content with galery'),
    ('cms/galery.html', 'galery'),
    ('cms/pieces/service.html', 'service'),
)


after
CMS_TEMPLATES = (
    ## Customize this
    ('page.html', 'Page'),
    ('feature.html', 'Page with Feature'),
   ` ('cms/pieces/content_primary.html', 'Content Base'),`
    ('cms/pieces/content.html', 'Content with galery'),
    ('cms/galery.html', 'galery'),
    ('cms/pieces/service.html', 'service'),
)

Question is Why django not sync small Incremental changes in CMS_TEMPLATES and reacts only when new template appears.
or can I do something wrong.

**Comment by czpython** [comment]
Hello @minotaurdsp ,
This is a known caveat of the template choices.
There's no way for the CMS to know that the template it has in the database say "x.html" is now "y.html". It's a limitation of Django's field choices.

To fix this, as you pointed out, can only be done through the shell.

**Comment by czpython** [comment]
@minotaurdsp 
If your template settings were

```python
CMS_TEMPLATES = (
    ('old_path/content_primary.html', 'Content'),
)
```

And you changed it to

```python
CMS_TEMPLATES = (
    ('new_path/content_primary.html', 'Content'),
)
```

You can update all pages that used the old template to use the new one, using the following:

```python
from cms.models import Page

update_count = Page.objects.filter(
    template='old_path/content_primary.html'
).update(template='new_path/content_primary.html')

print "Updated %d" % update_count
```

**Comment by minotaurdsp** [comment]
Many many thanks !
You saves the day
