### ISSUE TITLE
Google Search Console Is Hating On Us

### ISSUE THREAD

**Issue by seogod** [divio/django-cms#5593]
Okay this is really weird.

We are using DJANGO and for the past 8 months, our traffic has just been steady. 

We get tons of links from authority sites / news networks but it's just been 'steady'.

After getting this legendary SEO on board, he started getting links, did some on-page stuff
and things started picking up. However, the growth was just too slow.

So after running some tests, he discovered that for some weird reason, Our site gets indexed
(600 pages or so) and the very next day, it drops off to 127. This happens literally every 24 hours.

I've actually managed to track this for a whole week (Please see attached PDF).

Is this related to DJANGO somehow? Never seen it before using any other CMS before?

Does DJANGO indexes pages properly and generates proper sitemaps as well?

[IndexingTest.pdf](https://github.com/divio/django-cms/files/405432/IndexingTest.pdf)

**Comment by czpython** [comment]
Hello @seogod , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Users Mailing List](https://groups.google.com/forum/#!forum/django-cms).
