### ISSUE TITLE
Assign result of rendering placeholder to variable in template

### ISSUE THREAD

**Issue by vivazzi** [divio/django-cms#5607]
I suggest to add opportunity to assign result of rendering placeholder to variable, for example like this:
```
{% placeholder 'content' as rendered_content %}
{% if rendered_content %}
    <div class="wrapper">{{ rendered_content }}</div>
{% endif %}
```

Code above looks like to I need in tag page_url. With page_url I can do something like this:

```
{% page_url 'shop-cart' as shop_cart_url %}
{% if shop_cart_url %}
    <a href="{{ shop_cart_url }}" class="cart_icon"></a>
{% endif %}
```

If I could do same with placeholder it will be cool!

**Comment by czpython** [comment]
Hello @vivazzi , please make sure to submit questions/feature requests within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Developers Mailing List](https://groups.google.com/forum/#!forum/django-cms-developers).
