### ISSUE TITLE
Cache - Page is not being cached at refresh or when changing pages more than once

### ISSUE THREAD

**Issue by dimapou** [divio/django-cms#5608]
Hello,

After reading this: http://docs.django-cms.org/en/release-3.3.x/how_to/caching.html

I thought that I could cache my pages (including placeholders) but as is written in the docs cache is enabled by default and I'm not on edit mode or have another plugins that contain "cache = false"

Everytime I refresh the page or change pages  mutiple database connections are being made. So my question is: Is it possible to cache my website so it wouldn't make mutiple db connections to every single user? 

The problem is that it would be very expensive especially for big webistes, I saw the section "use cases" and I thought "They must being caching their pages, otherwise they wouldn't their traffic effectively"

Sorry if it's a dumb question but I can't figure out a way to serve my pages as static files after editing them.

**Comment by czpython** [comment]
Hello @dimapou,
Are you doing your tests as a logged in user?
If so then page level cache is disabled for authenticated users.

**Comment by dimapou** [comment]
Hello @czpython thanks for your help,

I'm not logged in and I also passed "?edit_off=true"  in the url just in case.

I pushed my app to the cloud and everytime I turn my MySQL db off  I get an error as soon as I change pages or refresh a page:

(2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 38")


So it is definitely accesing my database in each page request.

Am I doing something wrong or that's how django cms works?

Again, thanks for helping me.

**Comment by czpython** [comment]
It's currently not possible for caching to completely avoid the database.
There will be queries from Django which djangoCMS has no control over, as well as query to fetch a page from the requested url path.

That said, caching should avoid most queries from the cms because it caches the entire page content for a url.

Is the mysql connection working? Try running ./manage.py dbshell and see if it connects correctly.

**Comment by dimapou** [comment]
Yes @czpython the mysql is working, I was just trying to understand if I could make a single connection to mysql per user.

I understood what you said, I'm just gonna try to figure out some numbers on how much traffic a website could handle using django cms, I'm just kind worried to know what will happen if my website gets a lot of traffic.

Thanks a lot for your help I'll try to do some research to see what people do to make their django websites faster.

I'm closing this issue now.
