### ISSUE TITLE
Set session cookie on every request when `CMS_TOOLBAR_ANONYMOUS_ON` is `False`

### ISSUE THREAD

**Issue by vstoykov** [divio/django-cms#5627]
I found very strange problem. When I set `CMS_TOOLBAR_ANONYMOUS_ON = False` I see that for anonymous users django creates a session and not only session is created but session cookie is sent from the server on every request.

This behavior is breaking caching trough http proxy because every anonymous visitor has different session created on first load and on every request it will sent different cookies than other visitors and can't share the cache.

I found that the problem is in `ToolbarMiddleware` (https://github.com/divio/django-cms/blob/3.3.1/cms/middleware/toolbar.py#L102-L103). If check is added to see if there is a need of modification of session variables then the session will not be modified and django will not send it to the client.

I will prepare PR with a fix.

**Comment by czpython** [comment]
Merged in https://github.com/divio/django-cms/pull/5628
