### ISSUE TITLE
Unable to select page with PageField

### ISSUE THREAD

**Issue by czpython** [divio/django-cms#5631]
I'm using Aldryn Forms which has a plugin with `PageField`.
If I create a form and select a page as a redirect target, the next time I edit the form I get a JS error:

`Uncaught TypeError: Cannot read property '_pageSelectWidgets' of undefined`

Only after I publish the page, the error **sometimes** goes away.

http://xplorer-1002-stage.us.aldryn.io/en/forms/?edit&language=en

![cms_bug_with_pagefield](https://cloud.githubusercontent.com/assets/994951/17838047/6069e704-6791-11e6-8073-b7f27f88e30f.png)

Reproduced on both 3.3 and 3.4

**Comment by macolo** [comment]
Seems to be related to this here: https://github.com/divio/django-cms/issues/5476

**Comment by vxsx** [comment]
3.2 issue is a little different (and indeed is #5476), 3.3 and 3.4 though break in this particular case because of djangocms-text-ckeditor

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/5637
