### ISSUE TITLE
KeyError for context['request'] in Admin with placeholder

### ISSUE THREAD

**Issue by bittner** [divio/django-cms#5646]
I'm using django CMS 3.3.2 and Zinnia blog 0.16 with [cmsplugin-zinnia](https://github.com/django-blog-zinnia/cmsplugin-zinnia#cmsplugin-zinnia) 0.8.1 and `EntryPlaceholder`. The blog entries use the CMS placeholders to display content.

When I'm adding content everything is fine. However, when I try to modify an existing blog entry in the Admin (say, I remove a tag) then a `KeyError` occurs in [render_placeholder, line 125](https://github.com/divio/django-cms/blob/3.3.2/cms/plugin_rendering.py#L125), because there is no `request` key in `context`. The related piece of code in the Zinnia CMS plugin is [admin.py, line 28](https://github.com/django-blog-zinnia/cmsplugin-zinnia/blob/develop/cmsplugin_zinnia/admin.py#L28) where the call to `render_placeholder()` is issued.

## Catching and Ignoring KeyError works -- WT*?! 

Interestingly, wrapping the call in a try-except block in `cmsplugin-zinnia`'s [admin](https://github.com/django-blog-zinnia/cmsplugin-zinnia/blob/develop/cmsplugin_zinnia/admin.py#L28) makes the whole thing work, apparently without negative side-effects:
``` python
# -- cmsplugin_zinnia/admin.py -- (lines 22+)

    def save_model(self, request, entry, form, change):
        context = RequestContext(request)
        try:
            content = render_placeholder(entry.content_placeholder, context)
            entry.content = content or ''
        except KeyError:
            entry.content = ''
        super(EntryPlaceholderAdmin, self).save_model(request, entry, form, change)
```
Something similar has been reported and "fixed" this way in https://github.com/django-blog-zinnia/cmsplugin-zinnia/pull/45 before.

I'm not sure what's happening, TBH. Why is the `KeyError` occurring, and why can it be caught and ignored without side-effects? This seems to be rather an issue of django CMS than the Zinnia CMS plugin.

**Comment by czpython** [comment]
Hello @bittner,

The `KeyError` happens of of Django 1.8 (if I remember correctly), the reason of it is that in the past calling `RequestContext()` would apply the context processors when initializing which would set the `request` key on the context. This all changed to apply context processors when a context is bound to a template, in other words only when the template is rendered.

Example:

```python
context = RequestContext(request)
context['request'] # Raises KeyError
```

vs

```python
def my_template_tag(context):
    request = context['request'] # Does not raise KeyError

context = RequestContext(request)
template = Template("{% my_template_tag %}")
# Binds context to template and applies all context processors
template.render(context)
```

Regarding try/except, it doesn't actually work.

When you have something like:

```python
context = RequestContext(request)

try:
    content = render_placeholder(entry.content_placeholder, context)
    entry.content = content or ''
except KeyError:
    entry.content = ''
```

The `KeyError` will be raise every time and as a result the placeholder is never rendered.
So even though the object is saved() without problem, it's content field never gets a value.

**Comment by bittner** [comment]
Alright, thanks for the explanation.

For Zinnia's CMS plugin this appears not to be a blocker, because the placeholder is never rendered in the Admin interface at all. - Though it would be interesting to make rendering the CMS placeholder work in the Admin. This is missing in Zinnia since the switch from django CMS 2.4 to 3.0.
