### ISSUE TITLE
Putting language= in querystring breaks CMS pages

### ISSUE THREAD

**Issue by stefanw** [divio/django-cms#5651]
Adding a `?edit&language=` on any CMS page leads to a `NoReverseMatch` error. [See here for an example](https://www.django-cms.org/en/blog/?edit&language=).

My best guess why this happens without looking deeper: the toolbar admin language is set to the empty string which breaks language-based reversing of URLs. Solution: better sanitation of the toolbar language input.

**Comment by czpython** [comment]
Thanks for reporting @stefanw.
I know I've seen this one before.. think it got lost in time.
