### ISSUE TITLE
Massive 404s

### ISSUE THREAD

**Issue by JacobBose** [divio/django-cms#5653]
Hi there, we run a site with about 7000 pages indexed (On the DJANGO CMS ofcourse) - Our recent crawl showed there are about 17,000 404s that are getting picked up. Funny thing is we have less than 2400 (600 in English, rest translated in Japanese, Italian and Korean) pages on the CMS itself. Has any other DJANGO CMS owner went through such massive discrepancy in their 404s. Is Django proned to create just URLS on it's own? What could be causing this?

**Comment by czpython** [comment]
Hello @JacobBose , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Users Mailing List](https://groups.google.com/forum/#!forum/django-cms).

**Comment by JacobBose** [comment]
Sorry about that guys. Thx for the info! :)
