### ISSUE TITLE
show which app has deprecated files

### ISSUE THREAD

**Issue by ojii** [divio/django-cms#5655]
both the menu and apphook pool warn about old file names (`menu.py`/`cms_app.py`), but they don't tell you the offending app name (or full path to file). They probably should.

**Comment by czpython** [comment]
@ojii 
djangoCMS 3.4 removes these warnings.
Not sure if it's worth it to change them this far down the road.

**Comment by ojii** [comment]
Fair enough. We just ran into this issue today and thought it could be useful.
