### ISSUE TITLE
Creating page types programatically

### ISSUE THREAD

**Issue by discopatrick** [divio/django-cms#5661]
In other CMS's I've used, it's been possible to define Page Types (or "post types") programatically. This is desirable, as it allows me to commit these to code, and have them ready for use when the site has been installed - rather than going through the manual process of creating it via the admin area post-installation.

Is this possible in Django CMS? It doesn't seem to be documented. If not, please consider this a feature request :)

**Comment by czpython** [comment]
Hello @discopatrick , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Developers Mailing List](https://groups.google.com/forum/#!forum/django-cms-developers).

**Comment by discopatrick** [comment]
Hi @czpython - no problem, I'll ask on the mailing list. I had come here after asking on the IRC channel, where it was said there was no API for Page Types yet, so I thought this thread could double as a feature request in that case.
