### ISSUE TITLE
Image resizing fundamentally not working in most basic page setup

### ISSUE THREAD

**Issue by JonasT** [divio/django-cms#5668]
To reproduce, do the following:
1. Make a fresh virtualenv
2. Install django and django-cms from pip (latest versions)
3. Install django-cms using the djangocms installer tool
4. Add a superuser using manage.py
5. Launch django-cms and login as admin
6. Add a new page
7. Click "Edit"
8. Click "Structure"
9. Add a new "Text" content
10. In the WYSIWYG editor, insert some text and then insert an image plugin
11. Add a really big image (e.g. photo 4k x 4k or something)
12. Click the image for the detailed properties and make sure Crop and Upscale are checked, and Automatic resize is unchecked. Click "Ok" to close again
12. Resize the image in the WYSIWYG editor to a small size (like really small, try something around roughly 150 pixel) using the resize handlers and click "Save" on the text content
13. Publish changes on the overview edit page

Expected result:
The image is as small as in the WYSIWYG editor

Actual result:
The image will be huge again on the resulting site (expected behavior is obviously: it remains small).
If you click "edit" again and click the edit button on the text content, in the WYSIWYG editor the image is small again. If you right-click > "Inspect" in your browser, you will see width/height tags with exact pixel dimensions is set on the <img> instance displayed as part of the WYSIWYG content area. If you now return to the published page, no width/height tags are present on the <img> rendered as part of the resulting page which seems to be really weird.

**Comment by czpython** [comment]
Hello @JonasT , I believe this is an issue with the image plugin you're using.
If it's cmsplugin-filer or djangocms-picture, please create a ticket there in those apps.

Thanks!

**Comment by JonasT** [comment]
I used _your_ default install with _your_ default choice of Image insertion. (I literally just clicked the button for content to insert and chose "Image".) I did _zero work_ beyond just running the default installer with no extensions, other packages or _anything_

Do you expect me to know **your** internal project structure?? If this needs to be forwarded to some party, please do it yourself since I am just a user. You should really deal with bug reports of such basic functionality differently...

**Comment by JonasT** [comment]
Checking again in the editor, it seems to be in a "Filer" section, so I am going to assume it's "cmsplugin-filer"?

However, just to stress this: there is literally no other option available, and this is the most default install I could have done with pretty much zero changes, and inserting images is a super basic behavior in a CMS - I can file it somewhere else if you tell me where exactly, but I certainly can't guess the correct responsible component myself..

**Comment by czpython** [comment]
Hello @JonasT,
Thanks for looking into it.
I apologize for the confusion. There's the cms core and then all the other third party integrations, as such we are constantly making sure to only file cms core issues here and distribute the other issues to their respective party. That said, I can see that we need a better strategy for this as it can sometimes be tricky to know which party the issue originates from.

Regarding this specific issue, seems like the problem comes from the WYSIWYG editor, the resize handles are added by the editor js but I don't think these are hooked up to the backend, an oversight on our part.

I've filed a ticket for this https://github.com/divio/djangocms-text-ckeditor/issues/362.
