### ISSUE TITLE
Page admin tree-view does not display sub-pages with CMS 3.4 / Django 1.9

### ISSUE THREAD

**Issue by sivictorallen** [divio/django-cms#5694]
Noticed this issue while testing upgrade of current project to version 3.4. Tested with clean install using djangocms-installer (pip freeze and install conf below). This issue has not been present in CMS version 3.3.

The Page tree view stops displaying sub-pages (cannot expand root page to show sub-pages). This issue intermittent, and accessing the site from a different browser has restored functionality before, but only until the tree-view is used to publish/unpublish a page or to toggle menu visibility of a sub-page.

Environment is Python 3.5.2, CMS 3.4.0, Django 1.9.9 (Mac 10.11.6).

I have also tested with identical installation configuration, except using django-version = stable, (which installs Django 1.8.4) and was not able to reproduce the issue. Upgrading that install to Django 1.9 via pip, re-introduced the issue.

---

Installer config:

[djangocms_installer]
db = sqlite://localhost/project.db
i18n = no
use-tz = yes
timezone = America/Los_Angeles
reversion = no
permissions = yes
pip-options = 
languages = 
django-version = 1.9
cms-version = 3.4
parent-dir = cmstest
bootstrap = no
templates = no
starting-page = no
list-plugins = false
dump-requirements = false
no-input = false
wizard = false
verbose = false
filer = true
requirements = 
no-deps = false
no-plugins = false
no-db-driver = false
no-sync = false
no-user = false
template = 
extra-settings = 
skip-empty-check = false
delete-project-dir = false
utc = false

---

pip freeze:

cmsplugin-filer==1.1.3
dj-database-url==0.4.1
Django==1.9.9
django-appconf==1.0.2
django-classy-tags==0.8.0
django-cms==3.4.0
django-filer==1.2.5
django-formtools==1.0
django-mptt==0.8.6
django-polymorphic==0.8.1
django-sekizai==0.10.0
Django-Select2==4.3.2
django-treebeard==4.0.1
djangocms-admin-style==1.2.4
djangocms-attributes-field==0.1.1
djangocms-column==1.7.0
djangocms-googlemap==0.5.2
djangocms-installer==0.9
djangocms-link==2.0.0
djangocms-snippet==1.9.1
djangocms-style==1.7.0
djangocms-text-ckeditor==3.2.1
djangocms-video==2.0.1
easy-thumbnails==2.3
html5lib==0.9999999
Pillow==3.3.1
pytz==2016.6.1
six==1.10.0
tzlocal==1.2.2
Unidecode==0.4.19

**Comment by czpython** [comment]
Thanks for reporting this @sivictorallen.
Would you mind providing us with a screencast that shows the issue?

**Comment by jsma** [comment]
I think I'm experiencing this same issue. I used to see the following page structure:

<img width="67" alt="screen shot 2016-09-17 at 4 40 35 pm" src="https://cloud.githubusercontent.com/assets/24574/18611792/b2783644-7cfa-11e6-9246-862d96ccb77a.png">

Now the first node can't be expanded:

<img width="64" alt="screen shot 2016-09-17 at 4 40 53 pm" src="https://cloud.githubusercontent.com/assets/24574/18611793/bfa21eac-7cfa-11e6-97ca-98f9bab82fcf.png">

I have no insight into what is going on. I haven't been able to figure out how to reliably trigger the buggy behavior. It seems random. I can preview the same page multiple times but when I click 'Pages' from the toolbar it's a coin flip whether all nodes are expandable or not.

This also extends to grandchildren pages. On the rare occasion that I can expand the first node, sometimes all of its children are expandable, other times only some of the nodes are. The only difference between these two screenshots are a random number of page refreshes. Nothing else was changed.

![screen shot 2016-09-18 at 12 00 45 am](https://cloud.githubusercontent.com/assets/24574/18613682/5e998a66-7d34-11e6-92de-f55944a3ed1a.png)

![screen shot 2016-09-18 at 12 02 31 am](https://cloud.githubusercontent.com/assets/24574/18613685/62a82572-7d34-11e6-95a3-b01434a39ea8.png)

To be clear, all of this was while running 3.4. I haven't attempted to downgrade.

**Comment by czpython** [comment]
Thanks for the info @jsma.

Got a few questions:

1. Is the user you're using to access the site a superuser?
2. Do you have `CMS_PERMISSIONS` set to `True` in your `settings.py
3. When you're able to reproduce this, does anything show up in the console?

**Comment by sivictorallen** [comment]
In my case the user is a super user and CMS_PERMISSIONS = True
There's no special output in the console (either the shell or the browser JS console)

**Comment by jsma** [comment]
1. Yes, this was a superuser account
2. CMS_PERMISSIONS is not specifically set in this project
3. I do not see any errors the the browser console or the command line

**Comment by wullerot** [comment]
Same issue
Example project: [django-cms-vanishing-subpages](https://github.com/wullerot/django-cms-vanishing-subpages)

**Comment by FilippoIOVINE** [comment]
I was having same issue and I guess I figured out what was wrong:
**show_admin_menu_for_pages** tag (under cms/templatetags/cms_admin.py) is not returning a safe context instead it was returning escaped html text.
It is just necessary to add mark_safe wrapper to the rendering result to fix this issue:

https://github.com/FilippoIOVINE/django-cms/commit/6d762b47979f99173b49f4033240f785209a78c7

**Comment by czpython** [comment]
Thanks for info.
I think this is caused by a change in django 1.9 as we can't seem to reproduce the issue on 1.8.
I'll push a fix with tests later today.

**Comment by vxsx** [comment]
https://docs.djangoproject.com/en/1.10/releases/1.9/#simple-tag-now-wraps-tag-output-in-conditional-escape

**Comment by zypro** [comment]
Still having this issue with django-cms 3.5.2 and django 1.11? thought this was finally fixed in 3.4.x? Can anyone confirm this problem?

**Comment by jonathanrickard** [comment]
I am still seeing this issue with Django-CMS 3.7.1 and Django 2.2. The `fix-tree` command did not make a difference for me. Until this is resolved, is there a workaround for reordering pages in nodes that cannot be expanded?

**Comment by openHBP** [comment]
Same for me with 
> Django==3.1.5
> django-cms==3.8.0
> djangocms-admin-style==2.0.2

**Comment by jiangpuxuan** [comment]
> Same for me with
> 
> > Django==3.1.5
> > django-cms==3.8.0
> > djangocms-admin-style==2.0.2

My project is also:

Django==3.1.6/3.2.0
django-cms==3.8.0
djangocms-admin-style==2.0.2

and  I faced the similar error. The page tree appeared abnormal and I cannot add any thing.

**Comment by openHBP** [comment]
The strange thing is that it is working in dev on my PC but not in prod on line with the same DB even after backup and restore.
But by chance I've tried **with Opera Navigator and it works!** I've removed all cashed and saved data on Chrome by using 'Chrome Cleaner 1.3.2' but the TreeView is still not showing!?

**Comment by jiangpuxuan** [comment]
Thank you very much for your reply！ I will
try it tomorrow.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 21, 2021 23:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [django-cms/django-cms] Page admin tree-view does not display sub-pages with CMS 3.4 / Django 1.9 (#5694)




 
The strange thing is that it is working in dev on my PC but not in prod on line with the same DB even after backup and restore.
 But by chance I've tried with Opera Navigator and it works! I've removed all cashed and saved data on Chrome by using 'Chrome Cleaner 1.3.2' but the TreeView is still not showing!?

**Comment by jiangpuxuan** [comment]
> The strange thing is that it is working in dev on my PC but not in prod on line with the same DB even after backup and restore.
> But by chance I've tried **with Opera Navigator and it works!** I've removed all cashed and saved data on Chrome by using 'Chrome Cleaner 1.3.2' but the TreeView is still not showing!?
I tried it on opera navigator, but it doesn't works. I have raised this issue on Stackoverflow, as well.
![image](https://user-images.githubusercontent.com/81287604/115644737-a58b9980-a351-11eb-91d5-0bf82a04bff3.png)

**Comment by openHBP** [comment]
Ok thanks, keep me informed. In my case on Firefox or Chrome a click on **Pages** at least expand the beginning of the Tree-view (level 0 and 1 but not 2, 3 & 4). Just to be sure, is the CMS_PERMISSIONS set to True in your `settings.py`? Note also that with django 3.2 I'm encountering an other issue not yet released: https://github.com/django-cms/django-cms/issues/7015. I suggest to stay with django 3.1.6

**Comment by jiangpuxuan** [comment]
> Ok thanks, keep me informed. In my case on Firefox or Chrome a click on **Pages** at least expand the beginning of the Tree-view (level 0 and 1 but not 2, 3 & 4). Just to be sure, is the CMS_PERMISSIONS set to True in your `settings.py`? Note also that with django 3.2 I'm encountering an other issue not yet released: #7015. I suggest to stay with django 3.1.6

Thank you for your advice, but I surely keep CMS_PERMISSIONS set to True, and have been facing this problem from 3.1.6 to 3.1.7 and 3.2.0.
