### ISSUE TITLE
Toolbar causes CSRF validation to fail

### ISSUE THREAD

**Issue by rfleschenberg** [divio/django-cms#5696]
This seems to be similar to #5024.

I have a DRF `APIView` that acceps data via POST. The CSRF check for that view fails. If I set `CMS_TOOLBAR_HIDE = True` in my settings, everything works fine.

At first glance, I think that the bug is here: https://github.com/divio/django-cms/blob/60d7202b73609735015504503ff1215ae1e69d77/cms/middleware/toolbar.py#L32-L33

Maybe the logic of this check should rather be `if toolbar_hide: return False`? On the other hand, this would then not show the toolbar on pages with AppHooks, I think.

Maybe the better course of action is to ensure that the toolbar does not interfere with the request in the first place?

**Comment by rfleschenberg** [comment]
https://github.com/tomchristie/django-rest-framework/issues/3951

**Comment by rfleschenberg** [comment]
I'm closing this issue, since the real problem seems to be in DRF, and it looks like Tom is already on it :)

**Comment by czpython** [comment]
Cool, thanks for looking into it @rfleschenberg
