### ISSUE TITLE
ImportError: No module named formtools.wizard.views

### ISSUE THREAD

**Issue by vinayjulme** [divio/django-cms#5697]
I have installed django-cms==3.4.0

Form tools are also upto date.

But still getting "ImportError: No module named formtools.wizard.views"

in 

File "/Users/~/lib/python2.7/site-packages/cms/wizards/views.py", line 13, in <module>
    from formtools.wizard.views import SessionWizardView

**Comment by czpython** [comment]
Hey @vinayjulme,
Did you install `django-formtools`?

**Comment by vinayjulme** [comment]
Kindly see the attached screenshot. The marked section is causing the problem.

Please suggest a solution, as this has become a blocker for me.

![screen shot 2016-09-19 at 9 49 26 pm](https://cloud.githubusercontent.com/assets/22296803/18639945/880a1228-7eb3-11e6-8d57-54bde523554d.png)

**Comment by czpython** [comment]
@vinayjulme Can you provide us with the output of `pip freeze`?

**Comment by vinayjulme** [comment]
Kindly find the pip freeze output

I also tried pip install django-formtools -I
Which installed Django 1.10

So I downgraded Django back to 1.8.12.

Now it showing 
django.db.utils.ProgrammingError: relation "auth_user" does not exist

Are both thing related?



[FreezeLog.txt](https://github.com/divio/django-cms/files/480871/FreezeLog.txt)

**Comment by vinayjulme** [comment]
@czpython , let me know if you have any input on this?

**Comment by czpython** [comment]
@vinayjulme So you downgraded to django 1.8 and still get the import error? Or now get the db error?

**Comment by czpython** [comment]
Unable to reproduce this. Please create a new ticket if this issue still persists.
