### ISSUE TITLE
How I can add shortcuts help module as button to menu?

### ISSUE THREAD

**Issue by vivazzi** [divio/django-cms#5709]
I want to add shortcuts help button like this:
![help module](https://cloud.githubusercontent.com/assets/11954799/18897283/72877a2c-855b-11e6-9b84-a546f601f479.png)

which opens shortcuts help dialog:
![h_2](https://cloud.githubusercontent.com/assets/11954799/18897287/76914f30-855b-11e6-90cc-13052dc0fb19.png)

**Comment by czpython** [comment]
Hello @vivazzi,
This is currently not possible as the shortcuts functionality does not expose any public API.

**Comment by vivazzi** [comment]
Yes, I see. I suggest to do it. I think it will be useful for administrators
