### ISSUE TITLE
Django 1.10 support

### ISSUE THREAD

**Issue by koslibpro** [divio/django-cms#5712]
The pull request from django-treebeard is ready and merged (https://github.com/tabo/django-treebeard/pull/29). Can you roll out the full 3.4 version which includes the django 1.10 support? 

Tried today with `pip install django-cms` but still required django 1.9.

**Comment by czpython** [comment]
Hello @koslibpro,
djangoCMS is fully compatible with Django 1.10 but we can't support it "officially" because even though that PR has been merged, there's another one needed https://github.com/tabo/django-treebeard/pull/33 and we need treebeard to be released to PyPI as well.

We're discussing this internally and will do a release with "official" Django 1.10 support in the coming weeks.

**Comment by Fxlr8** [comment]
Hi, seems like https://github.com/tabo/django-treebeard/pull/33 was successfully merged! Can't wait to see django-cms 1.10 support!)

**Comment by aubricus** [comment]
Ran `pip install django-cms` today and it still requires 1.9.x. Any eta on 1.10 "official" support?

**Comment by czpython** [comment]
Hello @aubricus,
We're waiting on the official treebeard PyPI release.
A lot of progress has been made, I don't think it will be long.
You can follow along in https://bitbucket.org/tabo/django-treebeard/issues/97/package-maintenance

**Comment by yakky** [comment]
@aubricus @czpython treebeard is now community maintained. No ETA for a release, but I should really have a release within a couple of weeks

**Comment by JordanReiter** [comment]
Looks like newest version of treebeard released Nov. 27: https://pypi.python.org/pypi/django-treebeard

Updated version now available in PyPI, would love to see django-cms moving ahead with update for Django  1.10

**Comment by yakky** [comment]
Next patch release will have 1.10 compatibility (already merged in #5786 )

**Comment by snimavat** [comment]
Is it out, or still few days to go ?

**Comment by czpython** [comment]
The next patch release is coming.
We're planning to start code-freeze by the end of next week.
