### ISSUE TITLE
Djangocms failed in install because timezone incorrect

### ISSUE THREAD

**Issue by lukasgarcya** [divio/django-cms#5713]
I try install the Django CMS and I receive the error: ValueError: Incorrect timezone setting: local
The installation has failed.

![error djangocms](https://cloud.githubusercontent.com/assets/1985696/18993765/2c4ac1bc-86fb-11e6-8b48-d6c8e6337848.png)

**Comment by czpython** [comment]
Thanks for reporting @lukasgarcya.
Closing this as duplicate of https://github.com/nephila/djangocms-installer/issues/291

**Comment by lukasgarcya** [comment]
Thank You.
@czpython Do you have any solution?
