### ISSUE TITLE
Static placeholders on different sites

### ISSUE THREAD

**Issue by adonisnafeh** [divio/django-cms#5715]
I'm running into the same issue from #2797 using 3.4 and the develop branch. The static placeholder is the same across multiple sites regardless of the SITE_ID. I need every site to have a different footer and sidebar. Is this on purpose or is it another bug?

**Comment by czpython** [comment]
Hello @adonisnafeh,

By default, static placeholders have their `site` field set to `None` which causes them to show up in all sites. To change this behavior, you have to add the **site** flag to the `{% staticplaceholder %}` tag, this will cause a new static placeholder record to be created for each site the static placeholder is rendered in.

Example:

`{% static_placeholder "staticplaceholder_1" site %}`

Please checkout the [docs](http://docs.django-cms.org/en/latest/reference/templatetags.html#static-placeholder) for more information.

**Comment by adonisnafeh** [comment]
Yep, that works. Thanks
