### ISSUE TITLE
Failure during project creation using 'djangocms' command

### ISSUE THREAD

**Issue by thisispaulcyr** [divio/django-cms#5721]
- Django CMS 3.4.1
- Django 1.10.2
- pip modules: http://pastebin.com/vJWvZVfA
- pip 8.1.2
- Python 2.7.12
- OS: Amazon Linux AMI release 2016.03

I'm new to Django CMS, Django, and Python. My previous CMS experience has been with WordPress and I'm try to try out Django CMS as an alternative to WordPress, but am getting an error that I can not seem to figure out. I have updated the pip modules and installed others as suggested in threads on StackOverflow, but to no avail. 

I followed the [tutorial the instructions](http://docs.django-cms.org/en/release-3.3.x/introduction/install.htm), with the exception of the `djangocms` command, which is incorrect in the tutorial. (It's missing the -w flag.)

    (env)[ec2-user@${HOST} tutorial-project]$ djangocms -w -f -p . mysite
    Database configuration (in URL format). Example: sqlite://localhost/project.db [default sqlite://localhost/project.db]: postgres://${USERNAME}:${PASSWORD}@${HOST}:${PORT}
    django CMS version (choices: 3.2, 3.3, 3.4, stable, develop) [default stable]:
    Django version (choices: 1.8, 1.9, stable) [default stable]:
    Activate Django I18N / L10N setting; this is automatically activated if more than language is provided (choices: yes, no) [default yes]:
    Install and configure reversion support (only for django CMS 3.2 and 3.3) (choices: yes, no) [default yes]: no
    Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here. Example: en, fr-FR, it-IT: en-CA, en-US, en, fr-CA, fr-FR
    Optional default time zone. Example: Europe/Rome [default UTC]:
    Activate Django timezone support (choices: yes, no) [default yes]:
    Activate CMS permission management (choices: yes, no) [default no]: yes
    Use Twitter Bootstrap Theme (choices: yes, no) [default no]:
    Use custom template set [default no]:
    Load a starting page with examples after installation (english language only). Choose "no" if you use a custom template set. (choices: yes, no) [default no]: yes
        

 This is the error I'm getting:

    Creating the project
    Please wait while I install dependencies
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6x0RJS/psycopg2/
    The installation failed.
    Do you want to clean up by removing /home/ec2-user/tutorial-project?
            Warning: this will delete all files in:
                    /home/ec2-user/tutorial-project
    Do you want to cleanup? [y/N] n
    
    
    *****************************************************************
    
    Check documentation at https://djangocms-installer.readthedocs.io
    
    *****************************************************************
    
    Traceback (most recent call last):
      File "/home/ec2-user/env/bin/djangocms", line 11, in <module>
        sys.exit(execute())
      File "/home/ec2-user/env/local/lib/python2.7/site-packages/djangocms_installer/main.py", line 33, in execute
        verbose=config_data.verbose
      File "/home/ec2-user/env/local/lib/python2.7/site-packages/djangocms_installer/install/__init__.py", line 91, in requirements
        output = subprocess.check_output(['pip'] + args)
      File "/usr/lib64/python2.7/subprocess.py", line 574, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '[u'pip', u'install', u'-q', u'django-cms<3.5', u'djangocms-admin-style>=1.2,<1.3', u'django-treebeard>=4.0,<5.0', u'psycopg2', u'djangocms-text-ckeditor>=3.2.1', u'djangocms-link>=1.8', u'djangocms-style>=1.7', u'djangocms-googlemap>=0.5', u'djangocms-snippet>=1.9', u'djangocms-video>=2.0', u'djangocms-column>=1.6', u'easy_thumbnails', u'django-filer>=1.2', u'cmsplugin-filer>=1.1', u'Django<1.9', u'pytz', u'django-classy-tags>=0.7', u'html5lib>=0.999999,<0.99999999', u'Pillow>=3.0', u'django-sekizai>=0.9', u'django-select2<5.0six']' returned non-zero exit status 1`

**Comment by czpython** [comment]
Hello @thisispaulcyr, thanks for trying out djangoCMS.

Please reopen this in our [User Mailing List](https://groups.google.com/forum/#!forum/django-cms) or  [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

**Comment by thisispaulcyr** [comment]
Done: https://stackoverflow.com/questions/39862388/failure-during-project-creation-using-djangocms-command
