### ISSUE TITLE
Reversion register plugin doesn't set follow property

### ISSUE THREAD

**Issue by doctormo** [divio/django-cms#5722]
Currently the code in `cms/plugin_pool.py` does not pass along any value for `follow` this means that our cms plugin which uses a reverse foreignkey breaks every time a reversion is used.

This is my suggested change:

```
            from reversion.revisions import RegistrationError
            try:
                reversion_register(plugin.model,
                    follow=getattr(plugin, 'reversion_follow', []) 
                )
            except RegistrationError:
                pass
```

**Comment by czpython** [comment]
Revision support was removed on 3.4
We left the registration code to prevent third party apps from breaking if they had revisions created with plugins and content managers tried to revert. This shim will be removed entirely on 3.5.

As a result we're not planning to make further revision related changes to the core.

That said, we're currently working on bringing undo/redo to the cms as a third party app.

Sorry for the inconvenience.

**Comment by doctormo** [comment]
That's not actually a surprise at all. Thanks for letting me know.
