### ISSUE TITLE
Add plugin from Text Editor response CSRF Token error, page cache is false

### ISSUE THREAD

**Issue by CoffiDev** [divio/django-cms#5733]
Using django-cms 3.4.0, Text CKEditor	3.2.1 and Django 1.9.10

When I want to add a plugin from the Text editor, after submit the form it response "CSRF verification failed." 
I'm not using cache and also in my settings I have 
`CMS_PAGE_CACHE = False`

I inspected the elements and the token saved in the cookies and the one in the html iframe are the same, so I assume that It have the correct csrf token.

Also I have already tried [this solution ](https://github.com/divio/django-cms/issues/1906) but it didn't worked for me.

In my localhost it works with no problem, but in my staging server it isn't working, and the only differences in my settings are the database they are refering to, also the both have DEBUG = True.

I have read some issues where the solution is the cache, but I think it's not my case.

**Comment by czpython** [comment]
Hello @CoffiDev,

Please have a look at the [compatibility table](https://github.com/divio/djangocms-text-ckeditor#djangocms-text-ckeditor).
In this case you need to install djangocms-text-ckeditor version 3.3.0

**Comment by CoffiDev** [comment]
Hello @czpython 
I have just upgrade my version of django cms to 3.4.1 and Text CKEditor to 3.3.0, but the error still appearing, you have any other idea of what is causing the error? Thanks for your quick response

**Comment by czpython** [comment]
Is everything else working fine in your stage server? or are other actions throwing the same error?

**Comment by CoffiDev** [comment]
No, that is the only issue I have encounter in my stage server, the other forms work as expected.
It can be something related to my nginx configuration or uwsgi?

**Comment by czpython** [comment]
Hard to say but based on description definitely not cms/ckeditor issue.
Likely something in the server setup (as you mentioned nginx/uwsgi)

I'm closing the ticket here but feel free to open one in our [users group](https://groups.google.com/forum/#!forum/django-cms).

You can reach me via email and I can help have a look at the site itself to see if I notice anything.

Also make sure to install 3.4.1 as it fixed some bugs with 1.9 compatibility.

**Comment by CoffiDev** [comment]
Hi, I have find the cause of the error.
In my local host the content of request.POST is something expected: 
`{"override_height": "", "title": "", "img_responsive": "on", "_popup": "1", "shape": "", "override_width": "", "file": "15", "aspect_ratio": "", "csrfmiddlewaretoken": "fqWWEsrtXwLJtXGvlOqB9.....", "classes": "", "alt": ""}
`

But **in my staging server I'm receving this in the request.POST:**
`{"hash": "3b4aa3e05c668b06b62112248ca76257...", "raw_sql": "SELECT \"django_admin_log\".\"id\" FROM \"django_admin_log\" WHERE (\"django_admin_log\".\"action_flag\" IN (%s, %s) AND \"django_admin_log\".\"user_id\" = %s) ORDER BY \"django_admin_log\".\"id\" DESC LIMIT 1", "alias": "default", "params": "[1, 2, 1]", "sql": "SELECT \"django_admin_log\".\"id\" FROM \"django_admin_log\" WHERE (\"django_admin_log\".\"action_flag\" IN (1, 2) AND \"django_admin_log\".\"user_id\" = 1) ORDER BY \"django_admin_log\".\"id\" DESC LIMIT 1", "duration": "0.226020812988"}`

you have any idea of why are sql instructions in my request.POST ? Thanks

**Comment by czpython** [comment]
@CoffiDev I'm not sure but it might be that you have django-debug-toolbar in your environment and its doing something strange.
