### ISSUE TITLE
Update docs to reflect changes in django CMS installer

### ISSUE THREAD

**Issue by joncage** [divio/django-cms#5737]
The installation instructions: http://docs.django-cms.org/en/release-3.3.x/introduction/install.html suggest that after issuing this command:

`djangocms -f -p . mysite`

..there should be some prompts to fill in various options including the admin user but I get none.

After installation, when I run dev server up I just get a login page not the welcome screen indicated here:

http://docs.django-cms.org/en/release-3.3.x/_images/welcome.png

 I'm on a Macbook Pro running OSX 10.11.4, Python 3.4.3, Django v1.8.15, Django-CMS v3.4.1 if that makes a difference?

**Comment by czpython** [comment]
Hello @joncage,
Thanks for reporting this.

We changed the installer to setup the project using all defaults without input by default.
This was a design decision based on user feedback as some of these options can be confusing to newcomers.

To get the wizard, you can pass the `-w` option to `djangocms -f -p . mysite`

I'm keeping the ticket open as we need to update the docs to reflect these changes.

**Comment by czpython** [comment]
Fixed in https://github.com/divio/django-cms/pull/5815
