### ISSUE TITLE
The file 'cms/css/cms.base.css' could not be found with CompressedManifestStaticFilesStorage

### ISSUE THREAD

**Issue by oesah** [divio/django-cms#5740]
I am stuck with this issues since yesterday, and cannot find a solution. 

I use django-cookiecutter and integrated my django-cms app. Everything works fine, except when I open pages that have django-cms CSS. I get the following error:

```
ValueError: The file 'cms/css/cms.base.css' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7f238b1fa610>.
  File "django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "opbeat/instrumentation/packages/base.py", line 63, in __call__
    args, kwargs)
  File "opbeat/instrumentation/packages/base.py", line 222, in call_if_sampling
    return self.call(module, method, wrapped, instance, args, kwargs)
  File "opbeat/instrumentation/packages/django/template.py", line 18, in call
    return wrapped(*args, **kwargs)
  File "django/template/base.py", line 208, in render
    return self._render(context)
  File "django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/templatetags/static.py", line 104, in render
    url = self.url(context)
  File "cms/templatetags/cms_static.py", line 31, in url
    url = super(StaticWithVersionNode, self).url(context)
  File "django/templatetags/static.py", line 101, in url
    return self.handle_simple(path)
  File "django/templatetags/static.py", line 114, in handle_simple
    return staticfiles_storage.url(path)
  File "django/contrib/staticfiles/storage.py", line 132, in url
    hashed_name = self.stored_name(clean_name)
  File "django/contrib/staticfiles/storage.py", line 292, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "django/contrib/staticfiles/storage.py", line 95, in hashed_name
    (clean_name, self))
```

Colelctstatic correctly copied the file and whitenoise even `Post-processed` the file:

```
django_1    | Copying '/usr/local/lib/python2.7/site-packages/cms/static/cms/css/3.4.1/cms.base.css'
django_1    | Post-processed 'cms/css/3.4.1/cms.base.css' as 'cms/css/3.4.1/cms.base.1784b3b6c6ab.css'
```

Here are some settings, where I believe they might have an impact:

```
MIDDLEWARE = (
    'django.middleware.security.SecurityMiddleware',
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    # Your stuff goes here (save in config.middlewares)
    'config.middlewares.RequireLoginMiddleware',
)
# STATIC FILE CONFIGURATION
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = str(ROOT_DIR('staticfiles'))

# See: https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = '/static/'

# See: https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
STATICFILES_DIRS = (
    str(APPS_DIR.path('static')),

)

WHITENOISE_MIDDLEWARE = ('whitenoise.middleware.WhiteNoiseMiddleware', )
MIDDLEWARE = WHITENOISE_MIDDLEWARE + MIDDLEWARE
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
```

Anyone any idea? Any other info you need?

**Comment by oesah** [comment]
So I found out, that for some reason, the class `StaticWithVersionNode` does not return the correct value. Instead of `cms/css/3.4.1/cms.base.css` it return `cms/css/cms.base.css`. 

And of course, during `collectstatic` those files are stored in `cms/css/3.4.1`, which WhiteNoise does not find, because it does not exist. 

Any idea how to fix it?

**Comment by evildmp** [comment]
@vxsx do you have any insights?

**Comment by oesah** [comment]
Looks like the `cms/templatetags/cms_static.py` line 32 isn't returning the correct path.

**Comment by oesah** [comment]
And I narrowed down the problem to `STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'`. If disabled, no problemes anymore! So it must be something in the combination of `STATICFILE_STORAGE` and Django CMS.

**Comment by oesah** [comment]
Any progress on the issue? I cannot seem to fix it on my own.

**Comment by czpython** [comment]
Hello @oesah,
Thanks for following-up
I've been unable to look at this yet, will try later in the week/weekend.

**Comment by czpython** [comment]
Hello @oesah,
Small update, I've tried to reproduce this using the `ManifestStaticFilesStorage` storage and so far no luck, after running `collectstatic` everything works for me.

I can only reproduce this when using the whitenoise `CompressedManifestStaticFilesStorage` storage.

**Comment by oesah** [comment]
Is there a way to fix the ``CompressedManifestStaticFilesStorage``? I would need that for production soon.

**Comment by czpython** [comment]
Hello @oesah,
I'm unable to look at this again within the next two weeks because I will be on vacation.

**Comment by oesah** [comment]
Any Update on this? Would need it for my production release in Mid January.

**Comment by impala2** [comment]
Looks like the django class that the `StaticWithVersionNode` class extends checks for the validity of the path before the version can be added to the path.

    ------------------------ cms/templatetags/cms_static.py ------------------------
    index 05c7957..ed6cb8d 100644
    @@ -1,6 +1,8 @@
     # -*- coding: utf-8 -*-
     from django import template
    -from django.templatetags.static import StaticNode
    +from django.apps import apps
    +from django.templatetags.static import StaticNode, PrefixNode
    +from django.utils.six.moves.urllib.parse import urljoin
     
     from cms.utils.urlutils import static_with_version
     
    @@ -26,7 +28,12 @@ def do_static_with_version(parser, token):
     
     
     class StaticWithVersionNode(StaticNode):
    -
    -    def url(self, context):
    -        url = super(StaticWithVersionNode, self).url(context)
    -        return static_with_version(url)
    +    @classmethod
    +    def handle_simple(cls, path):
    +        path_with_version = static_with_version(path)
    +
    +        if apps.is_installed('django.contrib.staticfiles'):
    +            from django.contrib.staticfiles.storage import staticfiles_storage
    +            return staticfiles_storage.url(path_with_version)
    +        else:
    +            return urljoin(PrefixNode.handle_simple("STATIC_URL"), path_with_version)

I'd make a pull request but not sure if this is a satisfactory fix or not.

**Comment by punto1** [comment]
@oesah & @czpython: here a gist with the steps to reproduce and the fix:
https://gist.github.com/punto1/9c056bb9c3e8c9bdf0d9b0b3e51eeafc

relevant pull request:
#5860

replace code for StaticWithVersionNode in django-cms/cms/templatetags/cms_static.py
with:

```
class StaticWithVersionNode(StaticNode):

    def url(self, context):
        self.path.var = static_with_version(self.path.resolve(context))
        return super(StaticWithVersionNode, self).url(context)
```

**Comment by oesah** [comment]
Thanks! I'll try it out this week on the dev server and let you know how it goes. @czpython When can we expect a merge?

**Comment by czpython** [comment]
Thanks @punto1.
I've reviewed the PR, left some feedback.

@oesah We're not planning to release 3.4.3 soon, as a result once its merged I recommend installing directly from the commit hash. There's no other unreleased changes at the moment so it should be fine.

**Comment by trexchard** [comment]
@oesah @czpython Hey guys! I'm also using cookiecutter with a deploy to heroku with a virtualenv, but I can't seem to find where this file is located in order to edit it. Would you mind pointing me in the right direction?

**Comment by czpython** [comment]
Hello @trexchard,
which file are you referring to?

**Comment by trexchard** [comment]
django-cms/cms/templatetags/cms_static.py

I can't seem to locate this in my project. I looked in the virtualenv and the generated project from the django cms installer.

**Comment by oesah** [comment]
@trexchard It should be in your `site-packages` folder in your virtual env.

@czpython Awesome! Once you merge, ill pull it. Thanks for you help.

**Comment by trexchard** [comment]
Thanks so much @oesah!

**Comment by platzhersh** [comment]
@czpython what's the best way to install it by commit hash if I am installing django cms from requirements.txt in my prod environment during build?

**Comment by czpython** [comment]
Re-opening as the fix introduced a regression.
Reverted in https://github.com/divio/django-cms/pull/5909

**Comment by platzhersh** [comment]
Any idea when this will be fixed? This is causing me real problems on a customer project

**Comment by impala2** [comment]
I'm just using the commit with the fix for now. Add this to your requirements file: `git+ssh://git@github.com/divio/django-cms.git@8fabb5c3ef8b9283b535ea1b76f029c51d3e9c29`. Unfortunately it clones the entire repo when installing which slows down travis tests.

Hoping this gets fixed again soon.

**Comment by stefanw** [comment]
Until this is fixed I'm using a custom `ManifestStaticFilesStorage`:

```python
from django.contrib.staticfiles.storage import ManifestStaticFilesStorage
from django.core.files.storage import FileSystemStorage


class CustomManifestStaticFilesStorage(ManifestStaticFilesStorage):
    def url(self, name, force=False):
        """
        Return the non-hashed URL when detecting cms paths in order to work
        with their webpack setup
        """

        if name.startswith('cms/'):
            return FileSystemStorage.url(self, name)
        return super(CustomManifestStaticFilesStorage, self).url(name, force)
```

Use in `settings.py` like this:

```
STATICFILES_STORAGE = 'path.to.module.CustomManifestStaticFilesStorage'
```

This will exclude all static files paths starting with "cms/". Because django-cms static file paths contain a version number, cache busting across versions should still work. Depends on `Django==1.10`.

**Comment by EliotBerriot** [comment]
@stefanw thank you for sharing that. I've deployed your workaround in production and while I do not get 500 errors anymore (which is way better), the static files corresponding to the CMS toolbar are simply raising 404 errors. We have a bit of a unusual setup, though, since we use Nginx / Pagespeed to optimize static assets delivery, so it could be the cause of the problem.

Maybe I'm simply missing something obvious,

**Comment by racitup** [comment]
Any update on this? Just ran into it with whitenoise configuration almost 10 months after being reported!

**Comment by Jafnee** [comment]
Is there an estimate for when 3.4.5 will come out of rc?

**Comment by FinalAngel** [comment]
@Jafnee we are planning in about a week or two, depending on the results from testing and the help from the community.
