### ISSUE TITLE
Time selection box is displayed out of the modal page window (on v3.4)

### ISSUE THREAD

**Issue by FabriceSalvaire** [divio/django-cms#5741]
Before to click
![django-bug-time-box-1](https://cloud.githubusercontent.com/assets/2358471/19707149/439d72e0-9b16-11e6-982e-8317369cbcd9.png)

Result
![django-bug-time-box-2](https://cloud.githubusercontent.com/assets/2358471/19707152/455b854a-9b16-11e6-9b12-0823d1b4d8ad.png)

**Comment by czpython** [comment]
Closing this as a won't fix.
Because the modal is an iframe, the only solution would be to move the field to appear at the left.
