### ISSUE TITLE
Cannot publish a changed overwrite url (it doesn't see the page as as edited)

### ISSUE THREAD

**Issue by Arany** [divio/django-cms#5745]
Steps to reproduce:
- Create a page with an overwritten url (e.g "foo/bar/baz")
- Publish the page
- Edit the overwritten url (eg. to "foo/bar/bam")

-> The icon is still green, indicating there was no change, when you click it, you can only preview and unpublish the page
You cannot publish the new url, unless you change something else, like the title of the page.

Expected outcome:
The icon is blue and you can publish the new url

This is in version 3.3.3

**Comment by czpython** [comment]
Hello @Arany,
I've tried reproducing this on both 3.3.x and 3.4.x but so far no luck.

Here's a screencast of the steps I followed:

https://drive.google.com/file/d/0B9SwgyV0g1hSbFdxbERRX3V4YVU/view

**Comment by Arany** [comment]
Hi @czpython,
Can you one step to what you did:
have a page, that already has an overwritten url, and then change that overwritten url?
For me, I can not publish it then.
https://www.dropbox.com/s/f17vu50pxjazo2w/djang-cms-5745.mov?dl=0

**Comment by czpython** [comment]
Confirmed. Thank you :)
