### ISSUE TITLE
Documentation for caching is incorrect

### ISSUE THREAD

**Issue by vstoykov** [divio/django-cms#5746]
In the documentation there is no info about possible keys in `CMS_CACHE_DURATIONS` (`content`, `menus`, `permissions`).

**Comment by czpython** [comment]
There is, under the available settings http://docs.django-cms.org/en/latest/reference/configuration.html#cms-cache-durations

**Comment by vstoykov** [comment]
My fault. I was tinging that it should be at http://docs.django-cms.org/en/latest/how_to/caching.html?highlight=caching but I do not clicked on the link there to see that it is in configuration section.
