### ISSUE TITLE
Rendering plugin variable issue - not rendering the same when in editing mode

### ISSUE THREAD

**Issue by sulazix** [divio/django-cms#5747]
I wrote a simple plugin which display contact people, but I need to exclude some contact on certain pages. So I added a related model to my plugin which use an "structure_to_exclude" ManyToMany relationship. My issue, when I get this variable it's allways empty.

The cms_plugins.py

    class VMContactContactPlugin(CMSPluginBase):
        module = 'VM Contact Plugin'
        render_template = 'vm_contact/calendars/contacts_list.html'
        model = VMContactCalendarPluginModel
        name = _('VM Contact plugin')

        def render(self, context, instance, placeholder):
            print 'Instance : {0}'.format(instance)
            inst = instance.structure_to_exclude.all()
            print 'Instance.all() result : {0}'.format(inst)
            structures = Structure.objects.exclude(contact=None).exclude(pk__in=instance.structure_to_exclude.all().values_list('id',flat=True))
            context.update({
                'structures': structures,
            })
            return context

    plugin_pool.register_plugin(VMContactContactPlugin)

The related model

     class VMContactCalendarPluginModel(CMSPlugin):
         structure_to_exclude = models.ManyToManyField(
             Structure,
             verbose_name=_(u'Structures à exclure'),
         )

The Structure Models (Polymorphic !!)

    class Structure(PolymorphicModel):
        contact = models.ForeignKey(Contact, blank=True, null=True)
        members = models.ManyToManyField(Contact, blank=True, null=True, related_name='%(class)s_members')
        title = models.CharField(max_length=50, default='Castor')
        description = models.CharField(max_length=254, blank=True)
        categories = CategoryManyToManyField('aldryn_categories.Category',
                                             verbose_name=_('categories'),
                                             blank=True)
        calendars = models.ManyToManyField(Calendar, blank=True)
        has_pages = models.BooleanField(default=True)
        avatar = FilerFileField(null=True, blank=True,
                                     on_delete=models.SET_NULL)
        classcss =  models.CharField(max_length=1, choices=CSS_CLASS, default='5')
        order = models.PositiveSmallIntegerField(default=0)
        class Meta:
            ordering = ['order']

Print results : 

Instance : 93
Instance.all() result : []
    
And When in "editing" mode of django-cms, my code is working...

Instance : 92 
Instance.all() result : [ Grammont>, Mayen>, Aï>, ]

Any idea why it's bugy in normal mode and not when in editing ?

**Comment by sulazix** [comment]
I just notice that Instance id changes... is that normal ? 
Regards,
Robin

**Comment by czpython** [comment]
Hello @sulazix,

For every plugin you create, there's two versions once you publish.
The public and the draft versions. So its perfectly fine for the ids to change.

Because relationships vary from project to project, anytime your plugin has relationships, you need to explicitly tell the cms how to "copy over" these relationships when publishing the page.

Please adapt your plugin model to have the following method:

```python
def copy_relations(self, oldinstance):
    self.structure_to_exclude = oldinstance.structure_to_exclude.all()
```

You can read more about plugin relations in our [docs](http://docs.django-cms.org/en/release-3.4.x/how_to/custom_plugins.html#for-many-to-many-or-foreign-key-relations-to-other-objects).

**Comment by czpython** [comment]
Closing in favor of stackoverflow post.

**Comment by sulazix** [comment]
THANKS ! Sorry I missed this part of the documentation... my mistake...
