### ISSUE TITLE
Can we get a get_form() method on the Wizard class?

### ISSUE THREAD

**Issue by lunanoko** [divio/django-cms#5748]
I think it would come in handy to let developers choose the form class for a Wizard dynamically, based on the current request/user.

As a secondary request: can we get the current request in the other `Wizard.get_<attr>()` methods as well? That would allow us to actually base the return values of these methods on the current user and such.

**Comment by czpython** [comment]
Hello @lunanoko, please make sure to submit questions/requests within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Developers Mailing List](https://groups.google.com/forum/#!forum/django-cms-developers).
