### ISSUE TITLE
Move child page within parent has no effect in public menu (published)

### ISSUE THREAD

**Issue by wullerot** [divio/django-cms#5752]
If I move a child page within its parent, the public menu won't get updated.

Steps to reproduce:
- create page
- publish page
- create 2nd page
- publish 2nd page
- create child page in 2nd page
- publish child page
- create 2nd child page in 2nd page
- publish 2nd child page
- move child pages within same parent page

Example Project: https://github.com/wullerot/django-cms-page-move-bug

**Comment by wullerot** [comment]
cms.models.pagemodel.py
there seems to be something wrong with Page._publisher_save_public

**Comment by czpython** [comment]
Yes, its a tree issue where the live page is not moved so there's an inconsistency with the draft and live trees.

We're planning a fix for 3.3.4 and 3.4.2

**Comment by wullerot** [comment]
Thanks for the info

**Comment by thomas-d** [comment]
Looks like I encountered the same issue on version 3.4.1.

 I only had a few pages to move around in the public menu, so I messed around with the interface to see if I could get anything to change. 

I got the order in the public menu right by 

1. Moving the subpage I wanted to move to the top of the tree, as a sibling of my homepage. 
2. Dropping the page back in it's section. It's now shown as the first item of that subsection in the public menu.

Repeat for all necessary pages in the correct sequence, and you can match the menu and the pages' tree. 

Not at all a solution, but I hope it will help you fix the problem ;)

**Comment by czpython** [comment]
Hello @wullerot & @thomas-d,
Would you mind trying out the branch in https://github.com/divio/django-cms/pull/5770?
Specifically with a broken tree?
You'll need to run `./manage.py cms fix-tree` to repair the live tree.

**Comment by thomas-d** [comment]
Hi @czpython, 

I tried to use your branch, and I still have problems. 

I had some glitches in the admin interface when I first moved a page amongst its siblings. Some pages would disappear (see https://dl.dropboxusercontent.com/u/478185/django_cms_5752.mov). They come back when I refresh. Once a page has been dragged & dropped, it stops disappearing. I have to move a page, then refresh to reload the list, move the next page, etc. until they all stop disappearing. 

At that point it gets better : I can reorder the pages in the admin interface, and _the public menu is correctly updated_. \o/

Then if I run `manage.py cms fix-tree` it starts over again.

**Comment by wullerot** [comment]
Hi @czpython,

Tried your patch. Seems to work, once the tree is rebuild by hand. Before that the subpages get reorganized into the first parent.

before first fix-tree:
- Parent 1
    - Sub 1 1
    - Sub 1 2
- Parent 2
    - Sub 2 1
    - Sub 2 2

after first fix-tree:
- Parent 1
    - Sub 1 1
    - Sub 1 2
    - Sub 2 1
    - Sub 2 2
- Parent 2

If i then reorganize it by hand everything seams to work ok, thought i haven't had the time to test it thoroughly

**Comment by czpython** [comment]
Thank you both for the feedback.
Looks like there's more work to be done on the fix-tree command.

**Comment by czpython** [comment]
Hello @wullerot & @thomas-d,
I've updated the branch in https://github.com/divio/django-cms/pull/5770
Please check it out.
Make sure to run `./manage.py cms fix-tree` before moving any pages.

**Comment by wullerot** [comment]
Hello @czpython

Thanks a lot. Tested it with several projects, works like a charme.

**Comment by thomas-d** [comment]
Works perfectly for me too. Thanks :)

**Comment by czpython** [comment]
Thank you both for checking.
This will be landing soon, in time for the 3.4.2 release :)

**Comment by wullerot** [comment]
Thanks for your work
