### ISSUE TITLE
CMS_PLACEHOLDER_CONF 'limits' appears to have gotten broken between 3.3.3 and 3.4.1

### ISSUE THREAD

**Issue by mikemcgowan** [divio/django-cms#5754]
I have a minimal template like this:

```
{% load cms_tags sekizai_tags %}
<html>
  <head>
      <title>{% page_attribute 'page_title' %}</title>
      {% render_block 'css' %}
  </head>
  <body>
      {% cms_toolbar %}
      {% placeholder mike-mcgowan-test-placeholder %}
      {% render_block 'js' %}
  </body>
</html>
```

And a corresponding CMS placeholder configuration like this:

```
    'mike-mcgowan-test-placeholder': {
        'plugins': ['TextPlugin',],
        'limits': {
            'TextPlugin': 1,
        },
    },
```

If I try to add just one `TextPlugin` to a new CMS page, I get _"This placeholder already has the maximum number (1) of allowed Text plugins."_

When I look at my network panel, I see two requests, the first returns a redirect to the second, and the second returns a 400:

```
http://10.0.0.10:8000/en/admin/cms/page/add-plugin/?placeholder_id=2941&plugin_type=TextPlugin&plugin_language=en
http://10.0.0.10:8000/en/admin/cms/page/add-plugin/?delete-on-cancel&placeholder_id=2941&plugin_language=en&plugin=14495&plugin_type=TextPlugin
```

I am using Python 2.7.6, Django==1.8.15, Django-CMS==3.4.1, djangocms-text-ckeditor==3.3.0.

**Comment by czpython** [comment]
Hello @mikemcgowan,

Does this only happen with the text plugin?
Would you mind checking with a different plugin type?

**Comment by mikemcgowan** [comment]
Infact it seems to be okay with `LinkPlugin` and `FilePlugin`. Apologies. I should have raised this in the plugin-specific repo. Closing.
