### ISSUE TITLE
Only show DjangoCMS version in toolbar for logged in users

### ISSUE THREAD

**Issue by sephii** [divio/django-cms#5755]
Currently the toolbar shows the DjangoCMS version when you hover on the DjangoCMS logo. This allows you to go to any site running DjangoCMS, add "?edit" to the end of the URL (if it's enabled), and see the DjangoCMS version without even logging in.

I think it would be better security-wise that this information would only be visible to logged in users and/or add a setting to disable this feature.

**Comment by czpython** [comment]
Hello @sephii,

Thanks for reporting this.
As this is not a bug please create a new topic in our [developers mailing list](https://groups.google.com/forum/#!forum/django-cms-developers).

**Comment by Aiky30** [comment]
I would say that this is definitely not the intended behaviour which makes this a bug. That toolbar is for logged in users only and I agree that this is definitely a bug!!

**Comment by FinalAngel** [comment]
@Aiky30 it's something thats more of a security concern rather than a bug. Disabling the version when not logged in would be okay. Hiding the logo is most likely not something we would do.

If thats a concern to you or your client, simply adapt the templates (as they can be overridden)
