### ISSUE TITLE
Typo in CMS_PLACEHOLDER_CONF documentation example

### ISSUE THREAD

**Issue by thomas-d** [divio/django-cms#5765]
http://docs.django-cms.org/en/release-3.4.x/reference/configuration.html#cms-placeholder-conf

The current example starts with
```python
CMS_PLACEHOLDER_CONF = {
    None: {
        "plugins": ['TextPlugin'],
        'exclude_plugins': ['InheritPlugin'],
    }
```

The fourth line is wrong, it should read `'excluded_plugins': ['InheritPlugin'],`.

**Comment by czpython** [comment]
@thomas-d  Thanks for reporting this.

**Comment by SteinRobert** [comment]
The typo is still present in the "stable" version of the documentation.
http://docs.django-cms.org/en/stable/reference/configuration.html

**Comment by czpython** [comment]
Hello, we've not released yet.
As a result, the "stable" docs still point to 3.4.1
The "latest" docs are the ones with the changes pending release.

**Comment by evildmp** [comment]
Actually we have another issue here.

Our ``stable`` build is https://github.com/divio/django-cms/tree/3.4.1, commit https://github.com/divio/django-cms/commit/845c5fdd3deed0ead7cc0b7bd19062ceaa8a9589 (4th October 2016).

Unfortunately, ReadTheDocs is basing http://docs.django-cms.org/en/stable/ on commit https://github.com/divio/django-cms/commit - which doesn't actually exist.

So our stable docs are out of date already, and it's going to get worse unless we can find a solution.

See https://github.com/rtfd/readthedocs.org/issues/2563.

**Comment by czpython** [comment]
@evildmp If this is the case, please open another ticket as this specific issue has been fixed.

**Comment by evildmp** [comment]
I'm going to try some things on the RTD admin, expect some weirdness for a bit.
