### ISSUE TITLE
No content in field node.soft_root 

### ISSUE THREAD

**Issue by MacLake** [divio/django-cms#5767]
When I create a menu list with the default menu template, I can display all attributes of a node but soft_root: When I put `soft_root: {{ child.soft_root }}` in the default template menu.html, it is  empty, other attributes do show up, like `{{ child.title }}`.

I use Django CMS 3.4.1with Django 1.9.11 on Python 3.4.2.

**Comment by czpython** [comment]
Hello @MacLake,
This is correct behavior as the menu nodes don't expose this information.
If you need this, you'll have to create a menu modifier to set this information on page nodes.

For the future, please submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Users Mailing List](https://groups.google.com/forum/#!forum/django-cms), if you'd like we can discuss there the details on menu modifiers.
