### ISSUE TITLE
Inherited placeholders don't show overridden content

### ISSUE THREAD

**Issue by czpython** [divio/django-cms#5781]
When using an inherited placeholder:

`{% placeholder something inherit %}`

This CMS will not display any plugins added to the placeholder in child pages, instead it will always show the inherited content.

**Comment by gkmngrgn** [comment]
Hi @czpython what do you think about changing usage of inherit placeholders like this:

```
{% inherit_placeholder something %}
```

I guess it's more compatible with the other placeholder tags. static_placeholder, etc.

**Comment by czpython** [comment]
I like it @gkmngrgn but such a change would have to go through a big deprecation cycle.
Not sure if worth all the hassle for users.

**Comment by jrief** [comment]
I'm not sure if this is the same bug in Django-CMS 3.4.1, but I have a template with

```
{% placeholder "Main Content" inherit or %}
    ... some default content ...
{% endplaceholder %}
```

This template is used by the home page and by it's children pages. If I edit one of the child pages, I can add plugins to the placeholder, edit them and everything is fine.

However, when I publish the page, I can only see the contents of the home (aka parent page). Up to version 3.3.3 this worked as expected.

**Comment by czpython** [comment]
Hello Jacob,

The issue you mentioned is foxed by the attached pull request.

On Nov 28, 2016 11:11 AM, "Jacob Rief" <notifications@github.com> wrote:
>
> I'm not sure if this is the same bug in Django-CMS 3.4.1, but I have a
template with
>
> {% placeholder "Main Content" inherit or %} ... some default content ...
{% endplaceholder %}
>
> This template is used by the home page and by it's children pages. If I
edit one of the child pages, I can add plugins to the placeholder, edit
them and everything is fine.
>
> However, when I publish the page, I can only see the contents of the home
(aka parent page). Up to version 3.3.3 this worked as expected.

**Comment by jrief** [comment]
Thanks @czpython , I've seen that.

It would be great, if you could publish CMS-3.4.2, since currently I can't deploy my projects because of this.
