### ISSUE TITLE
"text_enabled" plugins in Text plugin become uneditable after saving

### ISSUE THREAD

**Issue by bcdickinson** [divio/django-cms#5787]
Using a simplified version of the `HelloPlugin` class from the tutorial, but with `text_enabled` set to `True`:
```python
from cms.plugin_base import CMSPluginBase
from cms.plugin_pool import plugin_pool
from cms.models.pluginmodel import CMSPlugin

from django.utils.translation import ugettext_lazy as _
from django.templatetags.static import static

class HelloPlugin(CMSPluginBase):
    model = CMSPlugin
    render_template = "hello_plugin.html"
    cache = False
    text_enabled = True

    def icon_src(self, instance):
        return static('user.svg')

plugin_pool.register_plugin(HelloPlugin)
```
hello_plugin.html:
```html
<h1>Hello</h1>
```
When it's first added to a text plugin everything works as expected:
![first](https://cloud.githubusercontent.com/assets/17799825/20763487/20b48bf6-b722-11e6-8fdb-c48c025ca54d.png)

... however, once the containg Text plugin is saved and reopened then the content of the plugin ("Hello") is no longer a plugin block, but editable text. Additionally, the `<cms-plugin>` element is now empty in the source view:
```html
<p>Real text content</p>

<p><cms-plugin alt="Hello Plugin - 21 " id="21" render-plugin="true" title="Hello Plugin - 21"></cms-plugin></p>

<h1>Hello</h1>

<p>&nbsp;</p>
```

Saving and reopening the parent text plugin adds a new occurrence of the text every time after this, too:
```html
<p>Real text content</p>

<p><cms-plugin alt="Hello Plugin - 21 " id="21" render-plugin="true" title="Hello Plugin - 21"></cms-plugin></p>

<h1>Hello</h1>

<p>&nbsp;</p>

<h1>Hello</h1>

<p>&nbsp;</p>
```

**Comment by evildmp** [comment]
Thanks for this excellent report, we'll look into it!

**Comment by vxsx** [comment]
Which version of djangocms-text-ckeditor is used?

I believe the issue belongs there, not in django-cms itself

**Comment by bcdickinson** [comment]
`djangocms-text-ckeditor==3.3.1`

**Comment by czpython** [comment]
Hello @bcdickinson,
Thanks for reporting this.
I've moved the ticket to https://github.com/divio/djangocms-text-ckeditor/issues/405 as this is an issue with the text editor.
