### ISSUE TITLE
Toolbar UserSettings language never gets updated

### ISSUE THREAD

**Issue by dibell** [divio/django-cms#5788]
As far as I can see the UserSettings for the toolbar get saved the first time the user logs in. After that they are never updated anywhere so the user can not change their preferred language after that. Am I missing something or is there an error in toolbar.py.

**Comment by evildmp** [comment]
@dibell What version are you using? Does this happen on all project?

I am not aware of any such problem (with any version). The user's language is always updated correctly on the sites I use.

In order to accept this as a bug we need to be able to replicate it.

**Comment by czpython** [comment]
I'm unable to reproduce this issue on 3.4.x
Please open a new ticket if this issue still persists and provide us with steps to reproduce this.
A screencast would also be helpful.

**Comment by kaushal235** [comment]
I'm able to reproduce this issue in django-cms 3.5.2 with the  Django 1.11.14
