### ISSUE TITLE
URL pattern changes caused by apphook changes do no propagate to ongoing helper processes (e.g. Celery workers)

### ISSUE THREAD

**Issue by lddubeau** [divio/django-cms#5789]
Consider the following scenario:

1. A Celery worker is started to offload some computations from the Django processes that respond to resquests.
2. The processes that respond to HTTP requests are started.
3. A staff user logs in, creates a page that uses an apphook and publishes it.
4. A visitor to the site uses the new page, the view code of the new page triggers a computation in a Celery worker, and this computation tries to perform a `reverse()` call on a named URL pattern that is to be resolved by the apphook used in step 3.

The `reverse()` may fail because the Celery worker does not know about the changes done in 3. URL patterns are loaded lazily. So if something causes the worker to load the patterns *before* the page is created, then the `reverse()` call will fail. Otherwise, it will work. Django CMS has code (`ApphookReloadMiddleware`) that causes the URL configuration to be reloaded when pages that have apphooks are edited, but the signal to reload (as far as I've been able to tell) does not cross process boundaries.

What I describe above is a simplification of a real case I ran into. I detected the issue in the Celery worker by doing this:

```
    from cms.apphook_pool import apphook_pool
    print "HOOKS", apphook_pool.get_apphooks()
    from cms.appresolver import get_app_patterns
    print "PATTERNS", get_app_patterns()
    # from lib import cmsutil
    # cmsutil.refresh_cms_apps()
    from cms.urls import urlpatterns
    print "URLS", urlpatterns
```

The HOOKS and PATTERNS line were fine but URLS was wrong unless I uncommented the two lines before it, which use a function I've been using in testing code to force the recomputation of URL patterns.

I've been able to work around the problem by redesigning my app so that it has "regular" URLs (for lack of a better term) and "REST" URLs. The REST URLs live independently from the apphook. (This is a better design, irrespective of the issue being discussed here: the REST API should not be subject to being moved around due to page edits.) The "regular" URLs are provided by the apphook. The Celery workers only depend on the REST URLs so they are no longer affected by edits to the CMS pages. This worked for me but I'm not convinced this is a workable solution in *all* cases.

It could well be that there's nothing reasonable that can be done in Django CMS' code base to help with this, and the best that can be done is document the issue and ways to handle it but I figured it won't be documented until someone raises the issue.

**Comment by czpython** [comment]
Hello @lddubeau,
Thanks for reporting this.

As you pointed out, there's not much we can do on the cms for this.
Its really a limitation on the way django urls are loaded and how the cms apphooks were designed to work with this mechanism. Resolving apphooks should not happen outside of the request/response cycle.

Because this is not really a cms bug as its very specific to this use case (celery or other non request based process), please file this report in our [developers](https://groups.google.com/forum/#!forum/django-cms-developers) mailing list.
