### ISSUE TITLE
test_requirements.txt on develop broken

### ISSUE THREAD

**Issue by benzkji** [divio/django-cms#5790]
I get a

    HTTP error 404 while getting https://github.com/fladi/django-treebeard/archive/django-1.10.zip
    Could not install requirement https://github.com/fladi/django-treebeard/archive/django-1.10.zip (from -r test_requirements/requirements_base.txt (line 5)) because of error 404 Client Error: Not Found for url: https://codeload.github.com/fladi/django-treebeard/zip/django-1.10

when trying `pip install -r test_requirements/django-1.8/9/10.txt` on branch develop. On 3.4.x this is ok?

**Comment by yakky** [comment]
@benzkji this has been fixed by #5626

**Comment by benzkji** [comment]
shall I develop and PR agains 3.4.x, then? @yakky

**Comment by czpython** [comment]
@yakky until we start with 3.5 I'd rather leave develop as is, otherwise we'll be doing rebasing multiple times.
