### ISSUE TITLE
Not editable plugin with static placeholder

### ISSUE THREAD

**Issue by dede322** [divio/django-cms#5792]
I created plugin:
```
class StaticLogo(CMSPluginBase):
    render_template = 'path/to/static_logo.html'
    module = 'Footer'
    name = 'Static logo'
    allow_children = False
plugin_pool.register_plugin(StaticLogo)
```

I write static placeholder in template static_logo.html:
```
{% load cms_tags %}

{% static_placeholder 'static_logo' %}
```

Then i add plugin and static_placeholder is visible and i can fill it. But i can't edit plugin 'Static logo' which define static_placeholder. Click by buttons is unresponsive:
http://image.prntscr.com/image/e596ceb0b50240bdaf18d1e34026be5e.png

I can edit plugin 'Static logo' if wrap static_placeholder in other tag. for example:
```
{% load cms_tags %}

<div>
    {% static_placeholder 'static_logo' %}
</div>
```

**Comment by czpython** [comment]
Hello @dede322,
This is expected behavior.

By design, plugins can't render an editable container (placeholder, static placeholder, etc.) as they themselves are inside a container.

**Comment by dede322** [comment]
This case is not described in the documentation, but in the example of wrapping in div works exactly as I need.
