### ISSUE TITLE
Internal Server Error when deleting all plugins from a placeholder

### ISSUE THREAD

**Issue by jrief** [divio/django-cms#5794]
When deleting all plugins from a placeholder, the method ``clear_placeholder()`` in ``cms.admin.placeholderadmin.PlaceholderAdminMixin`` raises an exception at the last statement ``return TemplateResponse(...)``.

This is because the API for the constructor of ``TemplateResponse`` changed from Django-1.9 to Django-1.10

I can reproduce this with commit 1670ea9ef2f84945e700f0117c3ceae058d9555b from branch release/3.4.x and Django-1.10.4.

**Comment by jrief** [comment]
There is a fix for this: #5795

**Comment by czpython** [comment]
Fixed by #5795
