### ISSUE TITLE
Duplicate lemma: "CMSToolbar"

### ISSUE THREAD

**Issue by jrief** [divio/django-cms#5796]
In version 3.4 the lemma ``CMSToolbar`` is used twice.
Once in ``cms.toolbar_base.CMSToolbar`` and once in ``cms.toolbar.toolbar.CMSToolbar``.
For external programmers it is very confusing, if the same lemma is used for different classes. Please choose a different name.

**Comment by czpython** [comment]
I agree that this can be confusing but its not really a bug.
As such, please file this in the [django CMS developers group](https://groups.google.com/forum/#!forum/django-cms-developers).
We can get the other core devs involved in the discussion there.
