### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by jrief** [divio/django-cms#5798]
It seems that in CMS version 3.4, the method ``render_plugin()`` from class ``cms.models.pluginmodel.CMSPlugin`` is not invoked anymore.
 
If this is correct, then it should be removed to reduce further confusion.

**Comment by czpython** [comment]
Hello @jrief,
We're aware of this but have not removed it because it has to go through a deprecation cycle.
I'm planning to tackle this and other dead code in 3.5

**Comment by jrief** [comment]
@czpython 
Python has a built-in exception class named ``PendingDeprecationWarning``. In these kind of circumstances, it should be used to avoid confusion by other developers.
