### ISSUE TITLE
Question: Default options in page permissions

### ISSUE THREAD

**Issue by jerickbixly** [divio/django-cms#5800]
Hi

In the page permissions form, is it possible to set the "Login required" option checked and the menu visibility option set as "for logged in users only", both as default for new cms pages?

thanks

**Comment by czpython** [comment]
Hello @jerickbixly  , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Users Mailing List](https://groups.google.com/forum/#!forum/django-cms).
