### ISSUE TITLE
jquery is missing on production site

### ISSUE THREAD

**Issue by DatCGI2net** [divio/django-cms#5803]
Hello,

it is fine on dev mode(manage.py runserver - port 8000), but I got below js error when I run with apache2 and uwsgi.py(port 80) file:
http://mydomain/static/admin/js/vendor/jquery/jquery.js: is missing

RelatedObjectLookups.js:132 Uncaught TypeError: django.jQuery is not a function(…)

I use the latest version 3.4.1

Thanks,

Dat

**Comment by vxsx** [comment]
RelatedObjectLookups and the jquery path you're seeing are coming from django admin,
cms doesn't expose our jquery anymore, so it seems unlikely that the error comes from us.

Can you provide more details, e.g. what page do you see the error on, what other packages are installed?

**Comment by DatCGI2net** [comment]
Thanks!

Here is my full packages:

INSTALLED_APPS = (
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'cms',
    'aldryn_apphooks_config', # added
    #'aldryn_categories',
    #'aldryn_common',
    #'aldryn_newsblog',
    'aldryn_people',
    'aldryn_reversion',
    'aldryn_translation_tools',
    'parler',
    'sortedm2m',
    'taggit',
    'taggit_autosuggest',
    'meta',
    'djangocms_blog',
    'reversion', # added
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'absolute', ##added for form
    'aldryn_forms',
    'aldryn_forms.contrib.email_notifications',
    'captcha',
    'emailit', ##added for form
    'filer',
    'easy_thumbnails',
    'djangocms_column',
    'djangocms_link',
    'cmsplugin_filer_file',
    'cmsplugin_filer_folder',
    'cmsplugin_filer_image',
    'cmsplugin_filer_utils',
    'djangocms_style',
    'djangocms_snippet',
    'djangocms_googlemap',
    'djangocms_video',
    'mycms',
    'django_select2',
    'djangocms_page_meta',
)

**Comment by vxsx** [comment]
And on which page do you see the error?

**Comment by DatCGI2net** [comment]
It started with any pages of cms like Page list, etc. But it seem fixed now after  I removed django 1.x on system.

Thanks!
