### ISSUE TITLE
How to login initially

### ISSUE THREAD

**Issue by pinksharpii** [divio/django-cms#5806]
I've had a ton of problems getting this setup, mostly permissions errors, with my machine apparently. However in settings.py I did have to change the DATABASE NAME to os.path.join(BASE_DIR, 'project.db'), instead of just 'project.db'. Not sure if this is a known issue.

Anyway I finally got it up and running and I have no idea to login. There is nothing helpful in the documentation. During the installation process, the only line I saw was "Creating admin user". No prompt. I can see in the db that the username is admin. 
The documentation just says: "The developers of your site are responsible for creating and providing the login credentials so consult them if you are unsure." I am the developer and at no point was this declared so I'm not sure how I should know this.

**Comment by czpython** [comment]
Hello @pinksharpii , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Users Mailing List](https://groups.google.com/forum/#!forum/django-cms).
