### ISSUE TITLE
NoReverseMatch: u'<my_app>' is not a registered namespace in managment commands

### ISSUE THREAD

**Issue by seroy** [divio/django-cms#5811]
Django==1.9.12
DjangoCMS==3.4.1

I've written apphook for application, the app hooks are correct and hooked to page, all work done. But in managment command (which call get_absolute_url method for model) raise NoReverseMatch exception.

**Comment by czpython** [comment]
Hello @seroy , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Users Mailing List](https://groups.google.com/forum/#!forum/django-cms).
