### ISSUE TITLE
Empty placeholders render "None" on non-cms pages

### ISSUE THREAD

**Issue by furiousdave** [divio/django-cms#5819]
I've come across an issue, specifically while using 3.4.1. If a non-cms controlled page, e.g. a login screen, extends a template containing a placeholder tag, the string "None" is rendered in its place.

In a very trivial test, it appears updating the line below with the following resolves the issue:
https://github.com/divio/django-cms/blob/release/3.4.x/cms/templatetags/cms_tags.py#L222

222.    return content or ''

**Comment by czpython** [comment]
Thanks @furiousdave.
This has been addressed by https://github.com/divio/django-cms/pull/5734
