### ISSUE TITLE
Multi-Step Wizard [feature-request]

### ISSUE THREAD

**Issue by bxm156** [divio/django-cms#5821]
It would be nice if there was support for a multi-step wizard, where I could define 5-6 steps, each with their own form. Then user would fill out the form, (the system would ensure it validates), and then render then next form.

The data could be either uploaded to the backend after each step, or all at once.

**Comment by czpython** [comment]
Hello @bxm156 , please make sure to submit questions/requests within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your request is best in the [Developers Mailing List](https://groups.google.com/forum/#!forum/django-cms-developers).
