### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by crazy-canux** [divio/django-cms#5834]
I follow the document here:

http://docs.django-cms.org/en/stable/how_to/install.html#configuration-and-setup

and got the exception:

![capture](https://cloud.githubusercontent.com/assets/14313415/21636249/da3cd1f6-d29c-11e6-9c0c-0cf95d70ea31.PNG)

this is my virtualenv:

![capture1](https://cloud.githubusercontent.com/assets/14313415/21636255/dc4f5d6a-d29c-11e6-94cd-5acda6725f90.PNG)

Anyboday knows how to fix this issue?

**Comment by czpython** [comment]
Hello @crazy-canux , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Users Mailing List](https://groups.google.com/forum/#!forum/django-cms).
