### ISSUE TITLE
Unable to edit placeholders

### ISSUE THREAD

**Issue by vaibhav-jain** [divio/django-cms#5848]
### Summary

Unable to edit placeholder text.
    
### Expected behaviour

I should get the text editor to edit the placeholder text.

#### Actual behaviour

![image](https://cloud.githubusercontent.com/assets/4224414/21977477/51327276-dbfc-11e6-9743-ce4c3e8f9444.png)

After double clicking I get this instead of text editor where I can edit the text.

![image](https://cloud.githubusercontent.com/assets/4224414/21977515/79a53676-dbfc-11e6-8002-3bdafca5bdc4.png)

#### Environment

* Python version: 2.7
* Django version: 1.9.12
* django CMS version: 3.4.1

**Comment by czpython** [comment]
Hello @vaibhav-jain,
Does this only happen with the text editor?
Can you post the djangocms-text-ckeditor version you're using?

**Comment by vaibhav-jain** [comment]
Hi @czpython No it is also happening with image plugin.

![image](https://cloud.githubusercontent.com/assets/4224414/22008193/f7d333de-dc9e-11e6-80d9-101eef921f46.png)


I'm using djangocms-text-ckeditor==3.3.1

**Comment by vxsx** [comment]
Are there any errors in a browser console? Which chrome version is it?

**Comment by vaibhav-jain** [comment]
No errors on console. Chrome Version 55.0.2883.87 (64-bit). Also not working on FireFox (v 50.1.0)

![image](https://cloud.githubusercontent.com/assets/4224414/22012627/11f8f0ac-dcbb-11e6-97be-bcdc37932c55.png)

**Comment by vaibhav-jain** [comment]
Any update. Its not even working on the older version

**Comment by vxsx** [comment]
So far I wasn't able to reproduce, sadly

Are there any other addons installed that change django admin?

**Comment by vaibhav-jain** [comment]
@vxsx It's weird sometimes it works sometimes doesn't. No visible errors so far on the console. Tried different versions too.

**Comment by czpython** [comment]
Hello @vaibhav-jain,
Can you try with django CMS 3.4.2?

**Comment by vaibhav-jain** [comment]
@czpython Sure I will give it a try . . .

**Comment by czpython** [comment]
Hello @vaibhav-jain, any updates?

**Comment by vaibhav-jain** [comment]
@czpython Sorry for the late response Yeah its working fine for 3.4.2.
