### ISSUE TITLE
Add Page or Sub page need reload server

### ISSUE THREAD

**Issue by tvudochi** [divio/django-cms#5850]
Hello,
From France, sorry for my englaish which is not fluent. I use Django CMS 3.4.1, Django 1.9.
When i add a page or a sub-page in the menu, sometimes, I don't see the added page.
I need to reload the server (Apache 2.4, WSGI).

I don't have any troubles when it run in runserver mode.
I try to find a work around about this trouble, 

I find this 
http://docs.django-cms.org/en/stable/how_to/apphooks.html
which talk about reloading server when using apphook.
I don't know if it is in this case.

**Comment by czpython** [comment]
Hello @tvudochi , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In this case, I believe your question is best in the [Users Mailing List](https://groups.google.com/forum/#!forum/django-cms).
