### ISSUE TITLE
Undocumented PageQuerySet.published and PageManager.published filters give duplicate results

### ISSUE THREAD

**Issue by fp4code** [divio/django-cms#5851]
### Summary

When used on bilingual sites, the filters PageQuerySet.published and PageManager.published gives duplicate results. This is because title_set__published=True filters on the titles and not on the pages,
and on a bilingual site there is 2 titles for each page.

### Expected behaviour

root_pages = Page.objects.filter(parent__isnull=True, site=Site.objects.get_current())
root_pages[0].publisher_is_draft, root_pages[1].publisher_is_draft # OK, True and False

len(root_pages.published()) # 1

#### Actual behaviour

len(root_pages.published()) # 4
len(root_pages.published().published()) # 8
len(root_pages.published().published().published()) # 16
...

#### Environment

* Python version: 2.7.12
* Django version: 1.9.12
* django CMS version: release/3.4.x

**Comment by czpython** [comment]
Hello @fp4code,
This is a won't fix as the `published()` method is internal and the behavior described is not an actual bug but rather an expected result of the multi-table query.

If you'd like to use this on your apps/projects, you need to ensure that you call `.distinct()` on the resulting queryset.

```
In [4]: len(root_pages.published().distinct())
Out[4]: 20

In [5]: len(root_pages.published().published().distinct())
Out[5]: 20

In [6]: len(root_pages.published().published().distinct())
Out[6]: 20

In [7]: len(root_pages.published().published().published().distinct())
Out[7]: 20
```
