### ISSUE TITLE
Subplugins are not editable when render_plugin is set to false

### ISSUE THREAD

**Issue by FabriceSalvaire** [divio/django-cms#5853]
I am experimenting a markup language plugin (RST, Markdown) where the idea is to use subplugins as "resources" for a parent plugin (images, source code, etc.). The property _render_plugin_ is set to false for these subplugins since they are fakes.

Unfortunately the buttons like edit in the structure page don't work for this kind of subplugins. After investigation I discovered we have to call the **content_renderer.render_plugin** method so as to register the plugin in the _CMS._plugins_ javascript variable.

**Is this behaviour expected or am I doing funny things ?**

**Comment by czpython** [comment]
Hello @FabriceSalvaire,
Unfortunately this behavior is expected.
The reason being that currently the content rendering logic is coupled with the toolbar rendering logic.

I suggest to let the cms render your plugin but simply have the `render_template` attribute point to an instance of a `Template() `object

**Comment by FabriceSalvaire** [comment]
Do you plan to separate them?
