### ISSUE TITLE
<object> element in CMS plugin template breaks CMS toolbar

### ISSUE THREAD

**Issue by trawick** [divio/django-cms#5854]
### Summary

If a plugin's template contains the object element, adding the plugin to a page breaks the toolbar.  The plugin can no longer be edited, other operations on the placeholder are also broken.  (No action triggered by clicking on the edit or other icons.)

### Expected behaviour

Toolbar not impacted by any HTML tag in a template

#### Actual behaviour

A JavaScript exception occurs here in the toolbar:

![image](https://cloud.githubusercontent.com/assets/1207350/22250810/54a400e4-e216-11e6-92b1-4f60e2104178.png)

I've added <object> to other plugin templates and reproduced the same error, so it isn't specific to this one plugin.  I can do that with an out of the box third-party plugin and the same thing happens.

No issue was seen on Django 1.5, Django CMS 2.4.3 :)  (yeah, I'm [hopefully] nearing the end of a big upgrade project)

I don't see this issue in a fresh setup of the Django CMS tutorial (djangocms-installer instructions followed verbatim, <object> inserted in a link plugin template, 3.4.2 currently installed).

Any hints on what could be triggering this, so that I can dig further?

#### Environment

* Python version: 2.7.12
* Django version: 1.8.17
* django CMS version: 3.4.2rc1  (or 3.4.1 or 3.4.2)

**Comment by vxsx** [comment]
> Due to the way browsers interact with plugins and external code, the .data() method cannot be used on <object> (unless it's a Flash plugin), <applet> or <embed> elements.

https://api.jquery.com/data/

apparently this is not supported in jquery, and therefore it's unlikely to be supported by CMS (at least not soon).

for a workaround you could wrap the top level object element with a span

**Comment by trawick** [comment]
Wow, thank you so much!!!!!  The workaround is effective, and hopefully anybody else with such an issue will find this ticket.  (I apparently wasn't putting <object> in a trigger position in my test with the tutorial project.)
