### ISSUE TITLE
CMS menu broken when resizing

### ISSUE THREAD

**Issue by maartinez** [divio/django-cms#5856]
### Summary
CMS menu breaks during browser window resizing or switching from portrait to landscape mode on tablet.

### Expected behaviour
Menu should look like this:
![screenshot3](https://cloud.githubusercontent.com/assets/23735559/22370661/d433223a-e492-11e6-90d6-fbc909e193d2.png)

#### Actual behaviour
When browser window is resized under 600px width and than resied back over 600px menu starts to look like this:
![screenshot](https://cloud.githubusercontent.com/assets/23735559/22370588/6b7122e2-e492-11e6-94ae-8e2d4f8d69df.png)

After refresh it looks normal again. It happens every time.

Console in browser shows also this error when entering editing mode:
![screenshot2](https://cloud.githubusercontent.com/assets/23735559/22370760/556defe2-e493-11e6-9f40-4fce3e2cc30a.png)

#### Environment

* Python version: 2.7.6
* Django version: 1.9.12
* django CMS version: 3.4.1

Other:
cmsplugin-filer==1.1.3
dj-database-url==0.4.2
Django==1.9.12
django-appconf==1.0.2
django-ckeditor-filebrowser-filer==0.2.1
django-classy-tags==0.8.0
django-cms==3.4.1
django-filer==1.2.6
django-formtools==2.0
django-mptt==0.8.7
django-polymorphic==1.0.2
django-sekizai==0.10.0
Django-Select2==4.3.2
django-treebeard==4.1.0
djangocms-admin-style==1.2.6.2
djangocms-attributes-field==0.1.2
djangocms-column==1.7.0
djangocms-googlemap==1.0.2
djangocms-installer==0.9.3
djangocms-link==2.0.3
djangocms-snippet==1.9.2
djangocms-style==2.0.1
djangocms-text-ckeditor==3.3.1
djangocms-video==2.0.3
easy-thumbnails==2.3
html5lib==0.9999999
olefile==0.44
Pillow==4.0.0
pytz==2016.10
six==1.10.0
tzlocal==1.3
Unidecode==0.4.20

**Comment by vxsx** [comment]
Cannot reproduce with a clean install, do you have a minimal case to reproduce it? 
The js error doesn't look familiar, it would be great if you could find where is it actually is (i can provide the same js bundle but with sourcemaps)

**Comment by evildmp** [comment]
I am also unable to reproduce.

**Comment by maartinez** [comment]
I am very very sorry for this. I had two times {% render_block "js" %}. One at the top and one at the bottom of the template file. I don't know how I couldn't find it for so long. Sorry again that I wasted your time to check this issue.
