### ISSUE TITLE
CMS_PLACEHOLDER_CONF[‘template placeholder’]['name'] seems to be ignored in 3.4.x (worked in 3.3.x)

### ISSUE THREAD

**Issue by SachaMPS** [divio/django-cms#5859]
Hey there...
after updating to 3.4.2 from 3.3.x the follwing pattern doesnt result in displaying the given name in dragbar.html.

CMS_PLACEHOLDER_CONF[‘template placeholder’]: {
        'name': u 'some name',
 },

I couldn't find any recent changes causing this but follwing the request for the placeholder label it appears to me that the template name is not being passed as needed:

1. Render the dragbar
https://github.com/divio/django-cms/blob/release/3.4.x/cms/templates/cms/toolbar/dragbar.html#L27

2. Call for the placeholder label (no mention of the template!!!)
https://github.com/divio/django-cms/blob/release/3.4.x/cms/models/placeholdermodel.py#L71

3. Here the template name would be required but isn't passed in step 2.
https://github.com/divio/django-cms/blob/release/3.4.x/cms/utils/placeholder.py#L37

**After reverting back to 3.3.2 the get_label method passes the template name!!!!!**

```    
def get_label(self):
        from cms.utils.placeholder import get_placeholder_conf
        if self.page:
            template = self.page.get_template()
        else:
            template = None
        name = get_placeholder_conf("name", self.slot, template=template, default=title(self.slot))
        name = _(name)
        return name
```

**Somehow this fix got lost**
ISSUE: https://github.com/divio/django-cms/issues/5492

**Comment by czpython** [comment]
Ouch.. looks like it never got forward ported to 3.4.x https://github.com/divio/django-cms/pull/5534#issuecomment-232064769 /cc @yakky.

Thanks for reporting, I'm pushing the fix now.

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/5877
