### ISSUE TITLE
Add change password link to frontend menu

### ISSUE THREAD

**Issue by timgraham** [divio/django-cms#5867]
I had a CMS user contact me wondering how to reset his password. As far as I see, the change password link is only available in the menu when viewing the Django admin. Would it be an improvement to also make it accessible in the frontend editing menu (perhaps under "User settings")?

**Comment by czpython** [comment]
Thanks @timgraham.
I'm closing this and opened a topic for it in our [developers group](https://groups.google.com/forum/#!topic/django-cms-developers/doc5qtqiQk0).
This is so we keep github tickets for bugs only.
