### ISSUE TITLE
[Not running on Elementary OS]

### ISSUE THREAD

**Issue by vikaskyadav** [divio/django-cms#5868]
Elementary OS freya is based upon Ubuntu 14.04. The new beta release for Linux is not working on this linux distro.

**Comment by czpython** [comment]
Hello @vikaskyadav,
Are you referring to django CMS? or the [Divio](https://www.divio.com/en/products/divio-app/) app?

**Comment by vikaskyadav** [comment]
@czpython . I am referring in context of new divio app released for linux.

**Comment by czpython** [comment]
Hello @vikaskyadav,
Please contact us through https://www.divio.com/en/#intercom (the intercom popup on the right) for Divio app issues.

I'm closing the ticket as this issue tracker is only for bugs in the django CMS app.

**Comment by vikaskyadav** [comment]
Okay. Thanks.
