### ISSUE TITLE
Documentation for`render_plugin()`-Deprecation

### ISSUE THREAD

**Issue by melbic** [divio/django-cms#5876]
### Summary

In 3.4 the `render_plugin()`-method is deprecated and will be removed in 3.5 due to the docstring. I couldn't find any documentation what to use instead.

### Expected behaviour

Add or publish documentation how to migrate the existing code/behaviour.

#### Actual behaviour

There is none.

#### Environment

* Python version:
* Django version:
* django CMS version:

**Comment by czpython** [comment]
Hello @melbic,
We included this information in the [3.4.0 release notes](https://djangocms.readthedocs.io/en/stable/upgrade/3.4/#manual-plugin-rendering) as this was deprecated on 3.4
