### ISSUE TITLE
Installation failure on Linux AMI

### ISSUE THREAD

**Issue by paulcyr** [divio/django-cms#5879]
### Summary

When running the `djangocms -f -p . mysite` command in the [installation tutorial](http://docs.django-cms.org/en/release-3.4.x/introduction/install.html) instructions, installation fails and fails without a clearly stated reason other than the failure happening while dependencies are being installed.

### Expected behaviour

The installation should either succeed or provide a specific reason for the failure in natural language.

#### Actual behaviour

The installation fails but does not provide a specific reason for the failure. The program outputs the internal command being run and the stacktrace.

	Creating the project
	Please wait while I install dependencies
	ERROR: cmd : ['pip', 'install', '-q', 'django-cms<3.5', 'djangocms-admin-style>=1.2,<1.3', 'django-treebeard>=4.0,<5.0', 'djangocms-text-ckeditor>=3.2.1', 'djangocms-link>=1.8', 'djangocms-style>=1.7', 'djangocms-googlemap>=0.5', 'djangocms-snippet>=1.9', 'djangocms-video>=2.0', 'djangocms-column>=1.6', 'easy_thumbnails', 'django-filer>=1.2', 'cmsplugin-filer>=1.1', 'Django<1.9', 'pytz', 'django-classy-tags>=0.7', 'html5lib>=0.999999,<0.99999999', 'Pillow>=3.0', 'django-sekizai>=0.9', 'django-select2<5.0six'] :b'You are using pip version 6.0.8, however version 9.0.1 is available.\nYou should consider upgrading via the \'pip install --upgrade pip\' command.\n    Command "/home/ec2-user/testenv/bin/python34 -c "import setuptools, tokenize;__file__=\'/tmp/pip-build-qn3xpl4j/Pillow/setup.py\';exec(compile(getattr(tokenize, \'open\', open)(__file__).read().replace(\'\\r\\n\', \'\\n\'), __file__, \'exec\'))" install --record /tmp/pip-p1mgk27p-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2-user/testenv/include/site/python3.4" failed with error code 1 in /tmp/pip-build-qn3xpl4j/Pillow\n'
	The installation has failed.

	*****************************************************************

	Check documentation at https://djangocms-installer.readthedocs.io

	*****************************************************************

	Traceback (most recent call last):
	  File "/home/ec2-user/testenv/bin/djangocms", line 11, in <module>
		sys.exit(execute())
	  File "/home/ec2-user/testenv/local/lib/python3.4/site-packages/djangocms_installer/main.py", line 33, in execute
		verbose=config_data.verbose
	  File "/home/ec2-user/testenv/local/lib/python3.4/site-packages/djangocms_installer/install/__init__.py", line 95, in requirements
		output = subprocess.check_output(['pip'] + args, stderr=subprocess.STDOUT)
	  File "/usr/lib64/python3.4/subprocess.py", line 620, in check_output
		raise CalledProcessError(retcode, process.args, output=output)
	subprocess.CalledProcessError: Command '['pip', 'install', '-q', 'django-cms<3.5', 'djangocms-admin-style>=1.2,<1.3', 'django-treebeard>=4.0,<5.0', 'djangocms-text-ckeditor>=3.2.1', 'djangocms-link>=1.8', 'djangocms-style>=1.7', 'djangocms-googlemap>=0.5', 'djangocms-snippet>=1.9', 'djangocms-video>=2.0', 'djangocms-column>=1.6', 'easy_thumbnails', 'django-filer>=1.2', 'cmsplugin-filer>=1.1', 'Django<1.9', 'pytz', 'django-classy-tags>=0.7', 'html5lib>=0.999999,<0.99999999', 'Pillow>=3.0', 'django-sekizai>=0.9', 'django-select2<5.0six']' returned non-zero exit status 1

#### Environment

* Python version: 3.4.3
* Django version: 1.8
* django CMS version: Unknown. Installed using pip. The command `pip show djangocms` returns the following notice:

	You are using pip version 6.0.8, however version 9.0.1 is available.
	You should consider upgrading via the 'pip install --upgrade pip' command.

When pip is upgraded to 9.0.1, the command `pip show djangocms` returns nothing.

**Comment by thisispaulcyr** [comment]
Upgrading pip does allow the installation to succeed, so it appears the problem lies with how djangocms is interacting with pip 6.0.8.

**Comment by czpython** [comment]
Hello,
Thanks for reporting this.
I'll mark it as a documentation issue to make sure we inform users to install latest pip.

**Comment by thisispaulcyr** [comment]
That would address the immediate error, but would it also be a good idea to modify the error handling so that the installer gives a clear reason for the failure?

**Comment by czpython** [comment]
Yes but this would be outside the scope of the core.
Please file a ticket on https://github.com/nephila/djangocms-installer
