### ISSUE TITLE
ShowMenu template tag - namespace parameter seems to be ignored.

### ISSUE THREAD

**Issue by SteinRobert** [divio/django-cms#5880]
### Summary
The template tag `show_menu` does not seem to take the parameter `namespace` into consideration.

### Expected behaviour
The template tag should cut off all menu nodes, which do not have the namespace of the parameter `namespace`.

#### Actual behaviour
The template tag `show_menu` simply shows all menu nodes and does not cut off the nodes with namespace which differ from the parameter `namespace` passed to the template tag. 

#### Environment

* Python version: 2.7
* Django version: 1.8.16
* django CMS version: 3.4.2

**Comment by czpython** [comment]
Hello,
Thanks for reporting this.
Unfortunately this feature never implemented.
As a result we'll likely just take it out of the documentation.

**Comment by rfleschenberg** [comment]
FWIW, I believe the feature would be useful, and it doesn't seem super-hard to implement.

**Comment by rfleschenberg** [comment]
What works for me is to use a `Modifier` to check the namespace, for example:

```python
from menus.base import Modifier
from menus.menu_pool import menu_pool


class MyModifier(Modifier):

    def modify(self, request, nodes, namespace, root_id, post_cut, breadcrumb):
        if namespace != 'mynamespace' or not post_cut:
            return nodes
        return [n for n in nodes if n.title in [
            'foo',
            'bar',
        ]]
```

**Comment by evildmp** [comment]
@rfleschenberg Can you confirm that you are using the ``namespace`` parameter in code?

If people are using it, then we should keep it, and drop only false promised from the docs, not any of its functionality.

Agreed @czpython?

**Comment by czpython** [comment]
@evildmp 
The functionality does not exist. The only way to "use it in code" is by creating a custom modifier like shown above or custom menu class that adds the functionality.

We will leave the attribute there until 3.5 or 3.6 but deprecate its usage because it doesn't do anything.

**Comment by rfleschenberg** [comment]
@evildmp I use it as shown, so @czpython is right. I believe there is a valid use-case here that djangoCMS should support. I don't know if the `namespace` parameter is the right way to do it.

The whole menu API seems to promise more than it does. I am not sure what the point of the whole pool / registration thing is, currently. If I understand correctly, you can effectively only have one menu, so what exactly is the purpose of registering menus with a menu pool?

I *might* come up with a PR to make some progress in this area, but due to time constraints, I cannot promise this. Should this discussion be taken to the ML, since it is beyond the scope of this specific issue?

**Comment by czpython** [comment]
Hello @rfleschenberg,
We are planning to do some major refactors of the menu system.
The goal will be to cleanup the codebase and also add new features like multiple menu support per request.

In regards to your question about the menu pool, the reason for this is that the cms allows developers to integrate their own menu class which lets the cms know about non-page nodes.

So even though all nodes are stored in one "menu" instance, the cms correctly filters them out when needed.

An example of this is breadcrumb navigation on a blog application, if you access a blog article's detail page, the cms breadcrumb navigation will not know anything about the blog article you're on, so the breadcrumb will be incomplete.

To solve this, you can create your own blog menu, register it with the cms and then attach it to the blog page, then the cms will have the nodes it needs to identify your blog detail pages. For more information, have a look at [cms intro custom menus](https://www.youtube.com/watch?v=6jn_-WyRcaY&feature=youtu.be&t=22m57s).

**Comment by rfleschenberg** [comment]
@czpython thanks for clearing this up! I guess I will wait for the results of the refactoring then, before I dig deeper into this.
