### ISSUE TITLE
Fix-tree while upgrading django-cms from 3.3.2 to 3.4.2 takes more than 2 hours

### ISSUE THREAD

**Issue by bvermeule** [divio/django-cms#5883]
### Summary

I'm upgrading django-cms from 3.3.2 to 3.4.2 and running `python manage.py cms fix-tree` as documented. Running the command however took a long while and I noticed that it has been stuck for around 2 hours on the following query:

```
SELECT tbn1.path, tbn1.numchild, (SELECT COUNT(1) FROM `cms_cmsplugin` AS tbn2 WHERE tbn2.path LIKE CONCAT(tbn1.path, '____')) AS real_numchild FROM `cms_cmsplugin` AS tbn1 HAVING tbn1.numchild != real_numchild
```

Seems like this query comes from treebeard.

I got ~151k rows in `cms_cmsplugin` and I suspect that there are too many plugins for treebeard to process in a timely manner.

### Expected behaviour

I expected the cms fix-tree command to take a while but finish within a couple of minutes.

#### Actual behaviour

I decided to quit the running query after 2 hours because I felt the duration was unacceptable.

#### Environment

* Python version: 2.7.10
* Django version: 1.8.17
* django CMS version: 3.4.2

**Comment by czpython** [comment]
Thanks for reporting this.
We're aware of the issue, its part of a limitation imposed by our usage of treebeard.

Can you comment out the lines above and including https://github.com/divio/django-cms/blob/release/3.4.x/cms/models/pluginmodel.py#L443 then re-run the command?

This is **not** a fix but can help us determine if there's something to be done in the core.

**Comment by bvermeule** [comment]
I commented out the lines you specified and the fix-tree command completed successfully (in a few minutes)

```
fixing page tree
fixing plugin tree
all done
```

The upgrade seems to be done successfully and the site looks like to be working as expected (including the page tree in the admin).

Any side effects I can expect by skipping the treebeard tree fix? What is the tree fix generally used for?

**Comment by czpython** [comment]
Hello @bvermeule,
Just realized I said "above"... I meant "below".
This line https://github.com/divio/django-cms/blob/release/3.4.x/cms/models/pluginmodel.py#L442 should still run, all others should be commented out.

If it takes a long time then we need to address the issue in treebeard, otherwise its on our side.

The tree fix does a lot to make sure the tree is consistent, prior to 3.4 there were a lot of "tree corruption bugs" which would put the page or plugin tree in an inconsistent state and that would cause problems when pages or plugins are added, moved or deleted.

**Comment by bvermeule** [comment]
Hi @czpython ,

I can easily confirm that the treebeard method takes a really, really long time. I isolated the query (see the original issue post above) and tried to run it directly on the database.

You can easily reproduce this by adding at least as many rows in cms_cmsplugin as me (150.000) en running the query.

**Comment by bvermeule** [comment]
@czpython 

Any idea what my next step could be? 
Skipping the tree fix didn't seem to have any issues. I tested this by just clicking through the site. Any way to verify whether I need the tree fix?

**Comment by czpython** [comment]
Hello @bvermeule,
You can run https://gist.github.com/czpython/bacfd888e45b6713abb7395acd44ec1d.
This checks the plugin tree for a "numchild" corruption which is the most common.

As this is confirmed to be an issue with treebeard, I'm closing the ticket.
Feel free to reach out via google groups if you need more assistance with this.
