### ISSUE TITLE
CMS_Plugin ManyToManyField Doesn't work. -Fixed

### ISSUE THREAD

**Issue by itzik16** [divio/django-cms#5886]
### Summary
Hello. I've made a simple CMS App which have videos, categories. and List view and a detail view for each.
 I wanted to extend the App to a plugin too, So I've added to my models.py the following:

```
class VideoPlugin(CMSPlugin):
    videos = models.ManyToManyField(Video)
    howmany = models.IntegerField(default='5',)
    

    def copy_relations(self, oldinstance):
        self.videos = oldinstance.videos.all()
    def __unicode__(self):
        return smart_unicode(self.howmany)

```

and I've made a new cms_plugins.py:
```
from cms.plugin_base import CMSPluginBase
from cms.plugin_pool import plugin_pool
from django.utils.translation import ugettext as _
from v_uploader import *
from .models import *

class VideoPluginPublisher(CMSPluginBase):
    model = VideoPlugin  # model where plugin data are saved
    module = _("Video")
    name = _("v-uploader plugin")  # name of the plugin in the interface
    render_template = "video_plugin.html"
    
    def render(self, context, instance, placeholder):
    	
    	context = super(VideoPluginPublisher, self).render(context, instance, placeholder)
        context.update({'instance': instance})
        print instance.howmany  #Debug
        print instance.videos.all() #Debug
        
        return context


plugin_pool.register_plugin(VideoPluginPublisher)  # register the plugin
```

### Expected behaviour
I should be able to use instance.videos.all in my plugin template with a for loop.

#### Actual behaviour
I Am only able to use instance.howmany in my plugin template
and the videos array always come empty.
![print](https://cloud.githubusercontent.com/assets/3527186/23402347/d775aaf0-fdb3-11e6-8595-f74e2da146ec.PNG)
In the red/blue box the first value is instance.videos.all and the second one is instance.howmany
same happens in the view.
```
    {%if instance.video.all %}
        <h1>It worked..</h1> <!-- it never works --!>
    {%endif%}
    {{instance.howmany}}  <!-- it always works. --!>
  
```

#### Environment

* Python version:2.7.12
* Django version:1.8.17
* django CMS version:3.4.2

--Thanks in advance, Itzik.

**Comment by czpython** [comment]
Hello @itzik16,
Does this happen both on draft and live mode?
or only on live mode?

**Comment by itzik16** [comment]
Hey @czpython , Thanks for replying mate,
It happens in both draft and live modes.

**Comment by itzik16** [comment]
FIXED:
Solution: Delete the old page and republish it. thank czpython! 👍
