### ISSUE TITLE
Tweak treebeard MP_Path options

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#5888]
If Plugins or Pages are deleted and created very often there might be a 
```
Path Overflow from: 'ZZZZ'
```
exception after a while.

I've run into this with a script that auto imports tens of thousands of pages and hundreds of thousands of plugins. Part of the process is to delete all plugins of a page and re-import them. At some point the max root id of ``ZZZZ`` is reached.

http://django-treebeard.readthedocs.io/en/stable/mp_tree.html?highlight=alphabet#treebeard.mp_tree.MP_Node.path

The defaults for the path field are like this:
* alphabet: ``0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ ``
* ``max_length=255``
* ``steplen=4``
This results in max ``1'679'616`` root nodes and a max depth of ``63``

I recommend we change ``steplen=7`` which gives us ``2'821'109'907'456`` root nodes and a max depth of ``36``.

Or more conservative: ``steplen=6`` for ``2'176'782'336`` root nodes and a max depth of ``42``.

This will make the time until the path field becomes a problem much longer.

Changing these values will require a migration that re-writes the ``path`` field.

If anyone else has run into this problem: I have a snippet of code I could provide that rewrites the path field on plugins to free up the gaps again.

**Comment by czpython** [comment]
Given the impact this would have, let's discuss this on a core devs meeting.
/cc @divio/django-cms-core

**Comment by czpython** [comment]
Closing as this will be done in https://github.com/divio/django-cms/issues/6049 for plugins.
