### ISSUE TITLE
404 errors for all links in docs.django-cms.org search results

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#5893]
I just did a search and it appears all search results links are broken at the moment.

For example, I searched for ['PlaceholderField'](http://docs.django-cms.org/en/release-3.4.x/search.html?q=placeholderfield&check_keywords=yes&area=default).

The links for the results all have *.rst.html as the file extension, but this should just be *.html. For example:

    http://docs.django-cms.org/en/release-3.4.x/how_to/placeholders.rst.html

**Comment by evildmp** [comment]
This is an issue upstream at Read the Docs: https://github.com/rtfd/readthedocs.org/issues/2708.

Short-term solution: wait for RTD to fix it.

Long-term solution: Everyone who benefits from Read the Docs should help by giving some financial support to this wonderful free service! https://readthedocs.org/sustainability/.

**Comment by evildmp** [comment]
Has been fixed. Many thanks to our friends at Read the Docs.
