### ISSUE TITLE
Plugin copy does not show on secondary published  page

### ISSUE THREAD

**Issue by barsch** [divio/django-cms#5895]
### Summary

Upgrade to Django 1.10.6 & DjangoCMS 3.4.2 worked fine. ```python manage.py migrate```, ```python manage.py cms check``` and ```python manage.py cms fix-tree``` all worked as expected.  

On an existing page cmsfiler-image's and a djangocms-link's did not show anymore - both were copies of plugins of another page where the links worked as expected. Is this the expected behaviour?

I tried with a new blank page - copying it via [source code] in editor as well as with right mouse context menu in the ckeditor editor - same result. It is showing correctly in the preview page - but not in the published page.

Any idea?

#### Environment
```
(test) D:\Workspace\test\src>python -c "import sys; print(sys.version)"
2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
```

```(test) D:\Workspace\test\src>pip list
appdirs (1.4.3)
backports.shutil-get-terminal-size (1.0.0)
cmsplugin-filer (1.1.3)
colorama (0.3.7)
decorator (4.0.11)
Django (1.10.6)
django-appconf (1.0.2)
django-classy-tags (0.8.0)
django-cms (3.4.2)
django-debug-toolbar (1.7)
django-debug-toolbar-template-timings (0.7)
django-file-resubmit (0.5.0)
django-filer (1.2.7)
django-formtools (2.0)
django-markup-deprecated (0.0.3)
django-mptt (0.8.7)
django-polymorphic (1.1)
django-reversion (2.0.8)
django-reversion-compare (0.7.3)
django-sekizai (0.10.0)
Django-Select2 (5.8.10)
django-smart-selects (1.3.4)
django-treebeard (4.1.0)
djangocms-admin-style (1.2.6.2)
djangocms-attributes-field (0.2.0)
djangocms-link (2.1.1)
djangocms-text-ckeditor (3.4.0)
easy-thumbnails (2.3)
enum34 (1.1.6)
html5lib (0.9999999)
ipython (5.3.0)
ipython-genutils (0.2.0)
olefile (0.44)
packaging (16.8)
pathlib (1.0.1)
pathlib2 (2.2.1)
pickleshare (0.7.4)
Pillow (4.0.0)
pip (9.0.1)
pip-review (0.5.2)
prompt-toolkit (1.0.13)
psycopg2 (2.7.1)
Pygments (2.2.0)
pyparsing (2.2.0)
pyScss (1.3.5)
regex (2017.2.8)
scandir (1.5)
setuptools (34.3.2)
simplegeneric (0.8.1)
six (1.10.0)
sqlparse (0.2.3)
textile (2.3.6)
traitlets (4.3.2)
Unidecode (0.4.20)
wcwidth (0.1.7)
webencodings (0.5)
wheel (0.29.0)
win-unicode-console (0.5)
xlwt (1.2.0)
```

**Comment by czpython** [comment]
Hello @barsch,
Is this issue present only when copying plugins via the source code on the text plugin?
Or does it also happen when copying plugins using the "Copy" action on plugins?

**Comment by barsch** [comment]
I created a test page with text plugin (djangocms-text-ckeditor) and added a single link (djangocms-link) to an external URL - after that I tried the following:

(1) copy & paste test page via /admin/cms/page/ context menu into new page & published -> works!
(2) copy & paste using the "Copy" action on plugins & publish -> works!
(3) copy & paste via source code from one text plugin to the other & publish -> does not work

again (3) shows correctly in the HTML preview of ckeditor but not in the published page

**Comment by czpython** [comment]
Thanks for the clarification.
Closing as this is an issue with the djangocms-text-ckeditor app.

This feature is currently not supported on the text plugin.
There's a ticket for it and other improvements [here](https://github.com/divio/djangocms-text-ckeditor/issues/285)

**Comment by barsch** [comment]
what puzzles me is why it stopped working for existing pages after the upgrade - I'm not sure there was an update of djangocms-text-ckeditor at the time of the the upgrade - on the other side the offending page hasn't been touched for a while ... - anyway thanks for clarification
