### ISSUE TITLE
nicer __repr__ for Page, Title, CMSPlugin and Placeholder

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#5897]
### Summary

When debugging on the shell or looking at tracebacks it would be very helpful if the default __repr__ for ``Page``, ``Title``, ``CMSPlugin`` and ``Placeholder`` would contain the ``id``

### Expected behaviour

```python
repr(page)
>>> '<cms.models.pagemodel.Page id=12849 object at 0x7fb43e27d590>'
```
or if ``page`` is not saved to the db yet:

```python
repr(page)
>>> '<cms.models.pagemodel.Page id=None object at 0x7fb43e27d590>'
```

#### Actual behaviour

```python
repr(page)
>>> '<cms.models.pagemodel.Page object at 0x7f89c99e9050>'
```

**Comment by koslibpro** [comment]
@czpython interested in working on this, if nobody else has already been assigned on.

**Comment by FinalAngel** [comment]
@koslibpro your contribution would be much welcome :)

**Comment by czpython** [comment]
Hello @koslibpro,
Sure, thanks for reaching out.

For both Page & Title, please also expose the publisher_is_draft value, like so:

```python
repr(page)
>>> '<cms.models.pagemodel.Page id=12849 is_draft=True object at 0x7fb43e27d590>'

repr(title)
>>> '<cms.models.titlemodel.Title id=12850 is_draft=True object at 0x7fb43e27d580>'
```

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/5972
