### ISSUE TITLE
Error: (1364, "Field 'file' doesn't have a default value")

### ISSUE THREAD

**Issue by FabrizioA** [divio/django-cms#5901]
### Summary

Every time I try to add a new File (as Plugin file from Django CMS) I get the error:

(1364, "Field 'file' doesn't have a default value")

Any suggestion?
Thank you.

#### Environment

* Python version: 2.7.10
* Django version: 1.9.12
* django CMS version: 3.4.2

**Comment by czpython** [comment]
Hello @FabrizioA , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

If this is an issue with a third party package like https://github.com/divio/djangocms-file, please create a new ticket there.

You can find additional information on our [support](https://www.django-cms.org/support) page.
