### ISSUE TITLE
Add Ukrainian language.

### ISSUE THREAD

**Issue by nibytes** [divio/django-cms#5903]
I am try use Ukrainian in `LANGUAGES = [
    ('ru', 'Russian'), #work
    ('uk', 'Ukrainian'), #it not work
    ('en', 'English') #work
]`
but when I try switch to Ukrainian in menu recive error 404
`Page not found (404)
Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/ru/ua/
Raised by: 	cms.views.details`
There https://www.transifex.com/divio/django-cms/ have translate but how add it in project. I was not find.
#### Environment

* Python version: 3.5
* Django version: 1.8
* django CMS version: 3.4.2

**Comment by czpython** [comment]
Hello, can you post your settings?

**Comment by nibytes** [comment]
http://pastebin.com/5pcJE2Zh
Settings

**Comment by nibytes** [comment]
Ohhh I edit CMS_LANGUAGES to `CMS_LANGUAGES = {
    ## Customize this
    'default': {
        'public': True,
        'hide_untranslated': False,
        'redirect_on_fallback': True,
    },
    1: [
        {
            'name': gettext('ru'),
            'public': True,
            'hide_untranslated': False,
            'redirect_on_fallback': True,
            'code': 'ru',
        },
        {
            'name': gettext('uk'),
            'public': True,
            'hide_untranslated': False,
            'redirect_on_fallback': True,
            'code': 'uk',
        },
        {
            'name': gettext('en'),
            'public': True,
            'hide_untranslated': False,
            'redirect_on_fallback': True,
            'code': 'en',
        },
    ],
}`
And all work.
