### ISSUE TITLE
Issue with injected JS file (page select widget)

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#5928]
I noticed the page select widget wasn't showing any pages, and a look at the console showed two static paths merged into one.
I originally raised this as a djangocms-link [issue](https://github.com/divio/djangocms-link/issues/122) but was asked to raise here as it's a cms core issue.

Here's a screenshot to highlight the issue (top line, yellow highlight);

![screen shot 2017-04-11 at 10 09 43](https://cloud.githubusercontent.com/assets/1461191/24930072/25b81276-1f00-11e7-9e1b-b7d4b20360d8.png)

This only occurs when `DEBUG = False`

#### Environment

* Python version: 2.7
* Django version: 1.10.6
* django CMS version: 3.4.2

**Comment by vxsx** [comment]
Does your S3 bucket contain only hashed files or also the original ones? I'm asking because while CMS would be able to detect the correct path, but won't be able to guess hashed filename.

Could you try this branch to see if it fixes the problem for you https://github.com/divio/django-cms/pull/5929

**Comment by marksweb** [comment]
@vxsx yeah the bucket contains the originals alongside the hashed files.

I'll try to take a look at that branch as soon as possible but I'm being kept busy fixing a few other bits.

If it helps, my storage classes look like this;

```python
from django.conf import settings
from django.contrib.staticfiles.storage import ManifestFilesMixin
from django.utils.deconstruct import deconstructible

from storages.backends.s3boto import S3BotoStorage


@deconstructible
class DeconstructableS3BotoStorage(S3BotoStorage):
    pass


@deconstructible
class MediaStorage(S3BotoStorage):
    location = '{sub_bucket}/{folder}'.format(
        sub_bucket=settings.AWS_S3_SUB_BUCKET,
        folder=settings.MEDIAFILES_LOCATION
    )

    def path(self, name):
        return self._normalize_name(name)


@deconstructible
class StaticStorage(ManifestFilesMixin, S3BotoStorage):

    # https://s3-{region}.amazonaws.com/{bucket}/{sub_bucket}/static
    location = '{sub_bucket}/{folder}'.format(
        sub_bucket=settings.AWS_S3_SUB_BUCKET,
        folder=settings.STATICFILES_LOCATION
    )
```
