### ISSUE TITLE
page_attribute "field-name" page_lookup as varname fails silently

### ISSUE THREAD

**Issue by jrief** [divio/django-cms#5930]
### Summary

when using the templatetag 

```
{% page_attribute "field-name" page_lookup as varname %}
```

using a ``page_lookup`` of a CMS page which does not exist, this templatetag fails silently, without rendering any part of the template. This makes is very hard to track down the reason.

### Expected behaviour

just as
```
{% page_url page_lookup as varname %}
```
can be used on a CMS page which does not exist, hence setting ``varname`` to ``None``, one would expect the same behaviour for the templatetag ``page_attribute``.

#### Environment

* Python version: any
* Django version: 1.10
* django CMS version: 3.4.2, HEAD of releases/3.4.x

**Comment by czpython** [comment]
Hello @jrief,
I'm unable to reproduce this.
Can you provide me with a test project where I can do so?

**Comment by czpython** [comment]
Closing as we're unable to reproduce this.

**Comment by jrief** [comment]
This error occurred again, this time in version 3.5.3.
How to reproduce:

* Create two CMS pages A and B.
* On page A, in Advanced settings, set Page-ID to `id-a`.
* To the template used by page B add:
  ```
  {% page_url 'id-a' as a_url %}
  {% page_attribute 'menu_title' 'id-a' as a_title %}
  ```
* Publish both pages.
* Remove Page-ID from page A.
* Load Page B. If that doesn't raise a page-not-found exception, unpublish page B, then republish.

btw. there is an asymmetry in the code, while the class `PageUrl` implementing templatetag `page_url`, catches a page-not-found exception, the class `PageAttribute` does not catch this exception.
