### ISSUE TITLE
django cms ignore addtoblock and block in case of python 3.

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [divio/django-cms#5934]
### Summary
django cms ignore addtoblock and block in case of usage python 3.
### Expected behaviour
Expected that it will work same way as for python 2 . Or at least to work at all.
#### Actual behaviour
Page which use extending template not have content defined between {% addtoblock %} statements using Python3.
#### Environment

* Python version:  Python 3.5.2 
* Django version:  Django 1.8.18 also 1.10.7
* django CMS version: 3.4.2

Recreation way easy : 
virtualenv -p python3 env
source env/bin/activate
pip install djangocms-installer 
djangocms --i18n no --django-version 1.10 --cms-version 3.4 site1

in fullwidth.html 

```
{% extends "base.html" %}
{% load cms_tags sekizai_tags %}
.....
{% block css %}
    {% addtoblock "css" %}
      !-- Latest compiled and minified CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
       <!-- Optional theme -->
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    {% endaddtoblock %}
{% endblock css %}
```

**Comment by czpython** [comment]
Hello @jpVm5jYYRE1VIKL,

There's no `{% block css %}` on the `base.html` file coming from djangocms-installer, this is why your `addtoblock` call is ignored.

Replace `{% block css %}` for `{% block content %}`.
