### ISSUE TITLE
Mobility issues with admin page tree

### ISSUE THREAD

**Issue by exploide** [divio/django-cms#5952]
### Summary

We discovered an usability issue regarding the admin panel on a mobile touch device. When the page tree is opened, it is easy to mess up the ordering of the pages, since each scroll or zoom gesture is interpreted as a "move this page" action. At least as long as the gesture is done over the page title column, which is usually the largest one. I think scroll or zoom gestures are much more frequent on a mobile device than moving a page on purpose.

I can think of two ways to improve the behavior:
- page move is triggered after selecting a page with longpress
- move the page only when the grey-colored grab icon (the left-most thing in a row) is touched and not on every move on the title column

#### Expected behaviour
I can scroll through the page tree without moving pages all the way around.

#### Actual behaviour
The page tree got messed up after scrolling through the page tree.

#### Environment

* Python version: 3.5.3
* Django version: 1.10.7
* django CMS version: 3.4.3

\cc @ObviouslyNot

**Comment by ObviouslyNot** [comment]
This is especially true when one has successfully scrolled in, for example at the top of the page, and then scrolled down until only the page tree is visible on the screen. I haven't found a way to get back out of that situation.

**Comment by jsma** [comment]
@vxsx any consensus on how this should be solved? We can provide a pull request but would like some direction. Should we simply add a confirmation modal for page moves? Or does the touch handling itself need to be changed? We ran into an issue with this today where an entire section of a site was accidentally moved into another section and was rendered temporarily inaccessible.

**Comment by FinalAngel** [comment]
@jsma @exploide thank you for your concerns and feedback.

The "move page directly" via the knob on the left would still generate the same issue if the user is unaware, leading to accidental moving of pages.

I'm more leaning towards the long-pressing of an item before moving start (mobile only though!) @vxsx do you also agree?

**Comment by vxsx** [comment]
i think a dialog is a no go, but otherwise i have no strong preference, maybe it should only be possible to drag a previously tapped page, e.g. tap and then move, or longtap and then move, either way would be very happy if anyone could provide a PR
