### ISSUE TITLE
Was reversion support removed?

### ISSUE THREAD

**Issue by Chronial** [divio/django-cms#5957]
I can't find any interface to access old versions even though I have installed reversion. In  #5830 it was mentioned that reversion was supposed to be removed? I couldn't find any reference in the documentation nor a changelog entry regarding removal of reversion support.

**Comment by czpython** [comment]
Hello @Chronial  , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

To answer your question, revision was removed on django CMS 3.4.0
You can see it in the [changelog](http://docs.django-cms.org/en/release-3.4.x/upgrade/3.4.html#what-s-new-in-3-4).

We introduced undo/redo in its place, you can find more info [here](https://www.django-cms.org/en/blog/2017/02/03/back-in-time-with-django-cms/)

**Comment by Chronial** [comment]
Sorry, I missed that note in the changelog. Thx for you detailed answer :).
