### ISSUE TITLE
Static placeholders inside <head>

### ISSUE THREAD

**Issue by paramono** [divio/django-cms#5967]
I thought it's a good idea to create a static placeholder in `<head>` so that users could easily add snippets to it (for example, Google Analytics code). The docs say it's possible:

>The `static_placeholder` template tag can be used **anywhere** in any template and is not bound to any page or model.

However, if I add `static_placeholder` in `<head>`, it becomes unusable ("add plugin" and "menu" buttons for this placeholder do nothing at all). Further investigation has shown that `cms_toolbar` is the culprit here:

>The `cms_toolbar` template tag has to be placed after the `<body>` tag and before any {% cms_placeholder %} occurrences within your HTML

What is the recommended way to add user-editable Snippets to `<head>`?

### Summary

`static_placeholder` (as well as `placeholder`) is only usable inside `<body>`. If `static_placeholder` is added to head, "add plugin" and "menu" buttons for this placeholder won't work, since placeholder is located before `cms_toolbar`. Is it possible to make `static_placeholder` editable in `<head>`, or is there any other way to add Snippets inside `<head>`?

Docs for static_placeholder template tag should probably be updated, since it's clear it cannot be used "anywhere" and needs to be placed some place after `cms_toolbar`. 

#### Environment

* Python version: 3.5.2
* Django version: 1.10.6
* django CMS version: 3.4.3

**Comment by czpython** [comment]
Hello @paramono,
Your findings are correct, any placeholder tag whether its `{% placeholder %}` or `{% static_placeholder %}` needs to be placed after the `{% cms_toolbar %}` tag.

So I think we can reword the statement about static placeholders as such:

The static_placeholder template tag can be used anywhere in any template as long as it occurs **after** the `{% cms_toolbar %}` tag. It is not bound to any page or model.

@evildmp can you confirm the text?

**Comment by evildmp** [comment]
@czpython That doesn't address the question of using static placeholders in <head> though - perhaps we should make that clear too.

**Comment by czpython** [comment]
@evildmp 
True, in regards to that, its not possible to add editable content to the `<head>` tag.

@paramono 
I suggest to use page or title extensions (depending on your needs) to add custom attributes and render them in the `<head>` tag.

**Comment by paramono** [comment]
Thanks for clarification, @czpython and @evildmp!

>I suggest to use page or title extensions (depending on your needs) to add custom attributes and render them in the <head> tag.

@czpython 
Are page/title extensions inheritable? That is, if I add an extension to some page, will its children get access to this extension's values?

I want to replicate `static_placeholder` behavior to make a common value that is used for every website page. In order to do so, I should probably add page extension to Home Page. If there is no extension inheritance, I should somehow (via a template tag?) extract Home Page Object inside of a common page template (base.html), and then get extension values from this object. In other words, every page will be looking up home page, and then accessing extension values from it.

Is that correct, or is there a better way to do so?

**Comment by czpython** [comment]
Hello @paramono,
There is no inheritance in extensions.
So your suggestion with the template tag is the way to go.

**Comment by paramono** [comment]
I see. Template tag it is, then. 
Thanks, @czpython!

**Comment by alexchanwk** [comment]
IMHO Using `static_placeholder` to insert snippets into `<head>` is actually very useful.

In my case, I could achieve something similar using **sekizai** by placing a `render_block` inside `<head>`, and then use `addtoblock` to add contents inside a `static_placeholder` into the `render_block`.

For example,

```
{% load ...... sekizai_tags %}
<!doctype html>
<html>
    <head>
        ....
        {% render_block "css" %}
    </head>
    <body>
        {% cms_toolbar %}
        {% addtoblock "css" %}
            {% static_placeholder "html_head_css" %}
        {% endaddtoblock %}
        ...
    <body>
</html>
```
