### ISSUE TITLE
toolbar_javascript.html: ValueError: invalid literal for int() with base 10 with USE_L10N=True

### ISSUE THREAD

**Issue by mbi** [divio/django-cms#5970]
### Summary

When `USE_L10N` is set to True, [toolbar_javascript.html#L20](https://github.com/divio/django-cms/blob/release/3.4.x/cms/templates/cms/toolbar/toolbar_javascript.html#L20) renders the pk of the current toolbar object as e.g. `'45&#39;596'`, resulting in an `ValueError: invalid literal for int() with base 10` error in e.g. [pageadmin.py#L1334](https://github.com/divio/django-cms/blob/release/3.4.x/cms/admin/pageadmin.py#L1334) (this gets called when e.g. closing a sidebar after editing an object)

### Expected behaviour

Shouldn't throw an error 500.

#### Actual behaviour

Throws an error. 

Would it be acceptable to filter the pk through `unlocalize`? 

```
'pk': '{{ request.toolbar.get_object_pk|unlocalize }}',
```

#### Environment

* Python version: 2.7.13
* Django version: 1.9.13
* django CMS version: 3.4.3

**Comment by czpython** [comment]
Thanks for reporting!

**Comment by mbi** [comment]
This seems to have been fixed in the `3.5.x` branch, in #6296.
