### ISSUE TITLE
Unable to remove/configure broken plugin using front-end/admin UI

### ISSUE THREAD

**Issue by plamen-nikolov** [divio/django-cms#5974]
I didn't manage to find easy way to remove broken plugin from a page. The only way I'm aware is to use the front-end editor, but if the plugin fails there is basically no way to load the page in order to remove the plugin. Didn't also manage to find how to do it in the admin UI.
Any thoughts ?

**Comment by czpython** [comment]
Hello @plamen-nikolov  , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.
