### ISSUE TITLE
Impossible to redirect to home when not using i18n_patterns

### ISSUE THREAD

**Issue by AlexElvers** [divio/django-cms#5975]
### Summary

I have a site where I don't need international URLs, so I disabled them by not using `i18n_patterns` in `urls.py`.

Let's say I have two cms pages:

* Home (path / without language prefix)
* Foo (path /foo and also without language prefix)

In the advanced settings of Foo, I can select the entry "Home (/)" in the redirect field. After submitting the form, I get the following error: "Enter a valid URL."

The redirect field (`PageSmartLinkField`) uses `validate_url`. `validate_url` gets `value='/'` and calls `RegexValidator(regex=relative_url_regex)(value)`. I think the issue is that `relative_url_regex` does not match the path `/`. It only matches paths like e.g. `/foo`.

I suggest to modify `relative_url_regex` so that it also matches `/` and `./` since these are valid paths.

### Expected behaviour

Redirect field accepts `/`.

#### Actual behaviour

Redirect field does not accept `/`. The error "Enter a valid URL." is shown.

#### Environment

* Python version: 3.6.1
* Django version: 1.10.7
* django CMS version: 3.4.3

**Comment by czpython** [comment]
Hello @AlexElvers,
Thanks for reporting.
This is a regression introduced by security patch (https://github.com/divio/django-cms/commit/186eb70caad0c3fde15ad9d354d6f84ff648dd7c)
