### ISSUE TITLE
cms api's add_plugin cannot add at first position

### ISSUE THREAD

**Issue by benzkji** [divio/django-cms#5986]
### Summary

adding a new plugin with the cms api, like this:

    add_plugin(
        placeholder,
        'DownloadEntryPlugin',
        'de',
        'first-child',
        parent_plugin,
        **download_data
    )
                
#### Expected behaviour

Plugin is created, at first position in parent_plugin

#### Actual behaviour

Plugin is created, at last position in parent_plugin

#### Ideas

Related to #5153 (still) ? I havnt looked at the internals (yet).

    created_plugin.move(parent_plugin, 'first-child')

does not work/move as expected as well. 

#### Environment

* Python version: 2.7.13
* Django version: 1.8.15
* django CMS version: 3.4.3

**Comment by benzkji** [comment]
is there a workaround, for moving plugins via api? maybe updating some fields manualy?

**Comment by benzkji** [comment]
see workaround.

**Comment by benzkji** [comment]
see #6049

**Comment by benzkji** [comment]
@czpython up to you if you want to reopen this and tackle it in 3.4...for now it's closed, got my workaround.

**Comment by philippze** [comment]
I have the same problem with pages. There, 

```
page.node.move(parent.node, 'first-child')
```

after inserting the page helps.
