### ISSUE TITLE
render_extra_menu_items tag uses Context instance in stead of a dict

### ISSUE THREAD

**Issue by hussum** [divio/django-cms#5994]
in `cms/templatetags/cms_tags.py`, the render_extra_menu_items rag uses  a Context as parameter for `template.render`. This throws an exception `context must be a dict rather than Context.`

versions used:
django 1.11.2
django-cms 3.4.4

**Comment by czpython** [comment]
Hello,
Thanks for reporting this.
It will be fixed in https://github.com/divio/django-cms/pull/5932
