### ISSUE TITLE
Django 1.11 support

### ISSUE THREAD

**Issue by horejsek** [divio/django-cms#6001]
Add support of Django 1.11. Should be without any issue. :-)

**Comment by czpython** [comment]
Hello @horejsek, please make sure to submit questions/requests within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

There's an on-going [effort](https://github.com/divio/django-cms/pull/5932) to add django 1.11 support.

**Comment by horejsek** [comment]
I see. I wasn't able to find any info about that. Could you consider to add to documentation table where anyone could easily see which versions are supported with each release and what future releases are planned?

**Comment by mammuth** [comment]
> Could you consider to add to documentation table where anyone could easily see which versions are supported with each release 

No real table, but for the latest version the Python and Django requirements are stated in the [installation-section](http://docs.django-cms.org/en/release-3.4.x/introduction/install.html) of the documentation.


> and what future releases are planned?

Major changes are stated at the [roadmap](https://www.django-cms.org/en/roadmap/). There are also GitHub-Milestones for releases like [3.5.x](https://github.com/divio/django-cms/milestone/45).

Hope those resources come in handy for you.
