### ISSUE TITLE
Same plugin rendered twice throws a js error that prevents edits.

### ISSUE THREAD

**Issue by vxsx** [divio/django-cms#6012]
### Summary

If a plugin is rendered twice - the page stops working. It's addressed in the https://github.com/divio/django-cms/pull/5980/files#diff-f96d3a435150f4243bb19f36483ba630R118 but needs to be backported

### Expected behaviour

The page continues working

#### Actual behaviour
The js doesn't expect this and fails

#### Environment

* Python version: 3.5.2
* Django version: 1.8.18
* django CMS version: 3.4.4

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/pull/6092
