### ISSUE TITLE
click on edit(pensil) or add(plus) button in Structure mode on some plugins\placeholders nothing reaction

### ISSUE THREAD

**Issue by nibytes** [divio/django-cms#6024]
### Summary
When I try click on edit(pensil) or add(plus) button in Structure mode on some plugins\placeholders nothing reaction but they active. It only on home page and in js console I recive this error
`TypeError: this.ui.container.data(...).push is not a function[Подробнее]  bundle.toolbar.min.js:5:18129
	initialize http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:5:18129
	o http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:4:6267
	f._initializeTree/< http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:6:8942
	each http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:1:14646
	f._initializeTree http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:6:8908
	<анонимная> http://127.0.0.1:8000/:2104:5
	c http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:2:6423
	fireWith http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:2:7245
	ready http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:2:9104
	h http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:1:1607`

* Python version: 3.5.2
* Django version: 1.8.18
* django CMS version: 3.4.4
**requirements.txt**
`aldryn-apphooks-config==0.3.3
aldryn-boilerplates==0.7.5
aldryn-categories==1.0.4
aldryn-common==1.0.4
aldryn-newsblog==1.3.3
aldryn-people==1.2.2
aldryn-reversion==1.1.0
aldryn-translation-tools==0.2.1
Babel==2.4.0
backport-collections==0.1
cmsplugin-filer==1.1.3
cmsplugin-image-gallery==0.7.2
dj-database-url==0.4.2
Django==1.8.18
django-annoying==0.10.3
django-appconf==1.0.2
django-appdata==0.1.6
django-classy-tags==0.8.0
django-cms==3.4.4
django-contrib-comments==1.8.0
django-filer==1.2.7
django-formtools==2.0
django-mptt==0.8.7
django-parler==1.8
django-password-reset==1.0
django-phonenumber-field==1.3.0
django-polymorphic==1.0.2
django-registration==2.2
django-reversion==1.10.2
django-sekizai==0.10.0
django-sortedm2m==1.4.0
django-taggit==0.22.1
django-treebeard==4.1.2
djangocms-admin-style==1.2.7
djangocms-attributes-field==0.2.0
djangocms-audio==1.0.2
djangocms-column==1.7.0
djangocms-googlemap==1.1.1
djangocms-installer==0.9.6
djangocms-link==2.1.2
djangocms-snippet==1.9.2
djangocms-style==2.0.2
djangocms-text-ckeditor==3.5.0
djangocms-video==2.0.3
easy-thumbnails==2.4.1
html5lib==0.9999999
lxml==3.8.0
Markdown==2.6.8
olefile==0.44
phonenumbers==8.6.0
phonenumberslite==8.6.0
Pillow==4.1.1
psycopg2==2.7.1
pybbm==0.18.4
python-dateutil==2.6.0
python-slugify==1.2.0
pytz==2017.2
six==1.10.0
sorl-thumbnail==12.4a1
tzlocal==1.4
Unidecode==0.4.20
YURL==0.13
`
**UPD:**
found problem in djangocms-audio
in player template if comment 2 line then all work fine.
https://pastebin.com/XYGmm4bZ

**Comment by czpython** [comment]
Hello @nibytes , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.
