### ISSUE TITLE
Frontend Editing Delete Plugin does not work [branch develop]

### ISSUE THREAD

**Issue by SteinRobert** [divio/django-cms#6026]
### Summary

I was testing the new frontend editing behavior implmented in https://github.com/divio/django-cms/pull/5980 
It seems like deleting plugin does not work properly. They are deleted after reload.

### Expected behaviour

Plugins should disappear in structure and content mode after deleting.

#### Actual behaviour

Plugins are removed from the frontend after a reload. When the modal for deleting a plugin is opened an JavaScript error occurs: 

``Uncaught ReferenceError: django is not defined
    at cancel.js:9``

I am using a simple Django CMS setup with the TextPlugin.

#### Environment

* Python version: 2.7.10
* Django version: 1.10.7
* django CMS version: 3.4.3 (develop branch)

**Comment by czpython** [comment]
Hello @SteinRobert,
Thanks for trying out the trunk version!

Currently develop is unstable as we're finalizing minor fixes on https://github.com/divio/django-cms/issues/6026. It would be great if you try out that branch instead.

Also, in order for the text plugin to work, you'll need the latest rc release, available in https://github.com/divio/djangocms-text-ckeditor.
