### ISSUE TITLE
Slug change doesn't propagate to all child pages

### ISSUE THREAD

**Issue by vxsx** [divio/django-cms#6027]
### Summary

When changing the slug of the page - not all of it's children update their path.
I create pages like this:
```
- Homepage (completely unrelated)
- page-a
     - page-b
        - page-c
```
So the slugs are:
```
/en/page-a
/en/page-a/page-b
/en/page-a/page-b/page-c
```

After that I publish _every_ page.
After that I change slug of "Page A" to "expected" and publish it.

### Expected behaviour
The resulting pages slugs are:
```
/en/expected
/en/expected/page-b
/en/expected/page-b/page-c
```

#### Actual behaviour
```
/en/expected
/en/expected/page-b
/en/page-a/page-b/page-c
```
If there are children to page-c - their paths aren't updated either.
Also this might be relevant:
```
>>> from cms.models import Page
>>> page = Page.objects.get(pk=18)
>>> page.title_set.values("path")
<QuerySet [{'path': 'page-a/page-b/page-c'}]>
>>> page.publisher_public.title_set.values("path")
<QuerySet [{'path': 'expected/page-b/page-c'}]>
```

#### Environment

* Python version: 3.5
* Django version: 1.10
* django CMS version: 3.4.4 (actually 3.5)

**Comment by PeterW-LWL** [comment]
We noticed this too.

- Python 2.7
- Django 1.8
- django CMS 3.4.5.dev1

**Comment by SydorenkoSergiy** [comment]
It's also present on CMS 3.4.4.2 and 3.4.3.1 with different versions of Django and Python

What could be added to the mentioned above, that when changing the slug of "page-a" AND "page-b", "page-c" sees all the slug changes

[video proff](https://www.screencast.com/t/Ekr7mSjxOl)
