### ISSUE TITLE
djangocms-link not setup properly in default divio project

### ISSUE THREAD

**Issue by digiology** [divio/django-cms#6032]
### Summary

The default divio project has djangocms-link's LinkPlugin installed. However the settings file is missing `DJANGOCMS_LINK_USE_SELECT2 = True` which results in the Internal Link dropdown being empty without any errors or explanation.

#### Environment

* Python version: 2.7.13
* Django version: 1.8.18.1
* django CMS version: 3.4.4.2

**Comment by czpython** [comment]
Hello @digiology,
Please contact us through https://www.divio.com/en/#intercom (the intercom popup on the right) for Divio cloud issues.

I'm closing the ticket as this issue tracker is only for bugs in the django CMS core app.
