### ISSUE TITLE
Editing advanced settings through change view raises AttributeError

### ISSUE THREAD

**Issue by sbywater** [divio/django-cms#6035]
### Summary

Editing advanced settings for a page through the change view of page admin raises an error if djangocms_blog is an installed app.

AttributeError: This QueryDict instance is immutable error is raised

### Expected behaviour

Advanced settings for a page should be successfully modified through page admin change view.

#### Actual behaviour

AttributeError: This QueryDict instance is immutable is raised at cms/admin/forms.py at line 305:

  del self.data['application_configs']

self is django.http.request.QueryDict({'application_namespace': '', 'reverse_id': '', 'xframe_options': '0', 'site': '1', 'application_urls': '', 'template': 'base.html', 'csrfmiddlewaretoken': 'foo', 'redirect': '', 'language': 'en', 'overwrite_url': '', 'navigation_extenders': '', '_save': 'Save'  })

app is a djangocms_blog.cms_apps.BlogApp

app_configs is like {'BlogApp': <djangocms_blog.cms_apps.BlogApp object at foo>}

app_namespaces is {'BlogApp': 'djangocms_blog'}

#### Environment

* Python version: 3.5
* Django version: 1.11.4 (But this error is non-specific to latest Django)
* django CMS version: 3.4.3

**Comment by plamen-nikolov** [comment]
The same behaviour here:

It doesn't work with:
Django: 1.11.X
Django-Cms: 3.4.5

It works with:
Django: 1.10.X

**Comment by olibook** [comment]
Hi there,
feel free to comment on the related PR.

**Comment by czpython** [comment]
A fix for this will be released on django CMS 3.5.1 and 3.4.6

**Comment by jedie** [comment]
Django CMS is not really useable because of this Bug :( When will the new release comes out?!?
