### ISSUE TITLE
Plugins can be hidden when changing Page Template

### ISSUE THREAD

**Issue by doctormo** [divio/django-cms#6036]
django-cms 3.4.4

Plugins will often be lost or left behind when a page's template is changed, where the placeholder names are different or there are different placeholders. There's no way to see plugins that are 'in the trash can' as it where.

The work around currently is to change a page back to it's original template, cut the plugin, change the page to the new template and paste it in. Of course this isn't create user interface design.

A way to solve this (and maybe even #4512) is to have a Trash can placeholder, a bit like the clipboard placeholder, but it holds ANY plugin which doesn't have a valid placeholder for the currently page template. This means migrating sites to new templates would be possible and hiding plugins would be simply a matter of parking them in the trash can.

If the divio devs like the idea, but don't have time, I can code a patch. But a positive opinion would be useful before I do any work.

**Comment by czpython** [comment]
Hello @doctormo,
I've opened a [topic](https://groups.google.com/forum/#!topic/django-cms-developers/eufv-Z7iJM8) in our developers mailing list to discuss this.
