### ISSUE TITLE
Odd case with fix to #6000

### ISSUE THREAD

**Issue by trawick** [divio/django-cms#6037]
### Summary

I tested the fix to #6000 and it is working largely as desired.  I noticed one odd case though:

* in the CMS editing environment
* active page has ``{% placeholder "FOO" inherit or  %} ``
* parent page does not have that placeholder, so nothing to inherit

The placeholder is not rendered (collapses to ''), whereas I expected the "or" contents to be used.

If I view the page anonymously or with the toolbar off, the placeholder is rendered, using the "or" contents as desired.

As of the fix for #6000, the modified call to ``render_placeholder()`` in ``render_page_placeholder()`` no longer passes through nodelist but instead passes ``None``.  If I change that as shown below, this particular scenario works as I anticipated.

```
diff --git cms/plugin_rendering.py cms/plugin_rendering.py
index 79258a6..dc1d310 100644
--- cms/plugin_rendering.py
+++ cms/plugin_rendering.py
@@ -296,7 +296,7 @@ class ContentRenderer(object):
                 page=current_page,
                 editable=editable,
                 use_cache=True,
-                nodelist=None,
+                nodelist=nodelist,
             )
 
         should_inherit = (
```

I don't know how this relates to why it works when outside of edit mode.  Any thoughts?

#### Expected behaviour

I expected the "or" contents to be used when

* in the CMS editing environment
* active page has ``{% placeholder "FOO" inherit or  %} ``
* parent page does not have that placeholder, so nothing to inherit

#### Actual behaviour

The placeholder is not rendered.

#### Environment

* Python version:  2.7.12
* Django version: 1.8.18
* django CMS version: 3.4.x release branch

**Comment by czpython** [comment]
Thanks for filing an issue for this.
Saw your comment on the previous one but forgot to create a new one.
The problem happens because code doesn't know the difference between placeholder with content and placeholder without content but with edit tags.

I'll have to refactor this a bit.

**Comment by trawick** [comment]
Thank you!
