### ISSUE TITLE
Child menu item sticking to top of list below parent

### ISSUE THREAD

**Issue by hillsboroughncgov** [divio/django-cms#6038]
I'm seeing a child menu item stick to the top of the list below a parent menu item when another item is moved into that position in the admin site. I have seen three instances of this since updating to django-cms 3.3.3. Our admin site uses djangocms-admin-style 0.2.5 because a widget we use is not compatible with later versions. Thank you for your assistance.

![menu_admin](https://user-images.githubusercontent.com/13467735/29041804-449b4c1a-7b82-11e7-8650-77d6ec6bf802.png)
![menu_display](https://user-images.githubusercontent.com/13467735/29041805-44a002f0-7b82-11e7-9084-0481a0566427.png)

**Comment by czpython** [comment]
Hello @hillsboroughncgov, please make sure to submit questions/support within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In regards to your issue, I "think" it is related if not the same as https://github.com/divio/django-cms/issues/5752. This and other corruptions of the page-tree were fixed on django CMS 3.4.
