### ISSUE TITLE
Remove administration dropdown from toolbar?

### ISSUE THREAD

**Issue by mistalaba** [divio/django-cms#6039]
Is it possible to customize the default frontend toolbar? I would like to remove the administration dropdown since my client gets confused by the options there and the flyout admin.

Thank you,
/Martin

**Comment by czpython** [comment]
Hello @mistalaba, please make sure to submit questions/support within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.
