### ISSUE TITLE
Attribute placeholder.is_static is confusing and boguous 

### ISSUE THREAD

**Issue by jrief** [divio/django-cms#6053]
### Summary

Instances of type ``Placeholder`` contain an attribute ``is_static``. One would expect that this flag marks a static_placeholder. However, this attribute is ``False`` if the placeholder is accessed through ``PlaceholderAdmin.edit_plugin``, even though the placeholder actually *is* static.

### Expected behaviour

``placeholder.is_static`` shall be ``True`` for all static placeholders, since this is the value we expect.

Otherwise we could just check if ``placeholder.page`` is ``None``, because static placeholders have no page assigned to them.

#### Environment

* Python version: Any
* Django version: 1.10.7, but presumably any
* django CMS version: 3.4.4

**Comment by czpython** [comment]
The `is_static` attribute is an internal legacy flag used only for rendering.
We plan to get rid of it but in the meantime its only set to `True` when the placeholder is rendered.

To check if a placeholder is static, I recommend something like:
```python
StaticPlaceholder.objects.filter(Q(draft=placeholder)|Q(public=placeholder)).exists()
```

I don't recommend relying on the `page` attribute.
