### ISSUE TITLE
no such table: cms_urlconfrevision

### ISSUE THREAD

**Issue by Liuheng268** [divio/django-cms#6063]
### Expected behaviour
When I depoly my site using apache24 ,I got this issue:no such table: cms_urlconfrevision
But when I use python manage.py runserver ,this error will not happen.

#### Actual behaviour

Request Method: | GET
OperationalError : no such table: cms_urlconfrevision
Exception Location : C:\Python27\lib\site-packages\django\db\backends\sqlite3\base.py in execute, line 318
Python Executable : C:\Apache24\bin\httpd.exe

['C:\\Windows\\system32\\python27.zip',  'C:\\Python27\\Lib',  'C:\\Python27\\DLLs',  'C:\\Python27\\Lib\\lib-tk',  'C:\\Apache24\\bin',  'C:\\Python27',  'C:\\Python27\\lib\\site-packages',  'C:\\Python27\\lib\\site-packages\\FontTools',  'C:\\Python27\\lib\\site-packages\\itk',  'C:\\Python27\\lib\\site-packages\\win32',  'C:\\Python27\\lib\\site-packages\\win32\\lib',  'C:\\Python27\\lib\\site-packages\\Pythonwin',  'C:\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode',  'C:/www/mysite2']

#### Environment

* Python version:2.7.10
* Django version:1.8.18
* django CMS version:3.4.4

**Comment by czpython** [comment]
Hello @Liuheng268, please make sure to submit questions/support within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.
