### ISSUE TITLE
JS issue in 3.4.4 - cmsWebpackJsonp is not defined

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#6065]
### Summary

I previously raised an issue whereby the page select widget wasn't working for us due to hashed static files breaking the static paths.

I've just upgraded to 3.4.4 which has fixed the page select, but now the page tree is broken.

```bash
Uncaught ReferenceError: cmsWebpackJsonp is not defined
    at bundle.admin.pagetree.min.b409a9a7d4a8.js:1
(anonymous) @ bundle.admin.pagetree.min.b409a9a7d4a8.js:1
```

Where abouts is this supposed to be defined, I can see it in the gulp setup, but not in the installed app.

#### Environment

* Python version: 2.7
* Django version: 1.10.7
* django CMS version: 3.4.4

**Comment by vxsx** [comment]
Hi, could you provide the source of that admin page? There should also be a `bundle.admin.base.min.js` that defines that, and both of them are normally included https://github.com/divio/django-cms/blob/release/3.4.x/cms/templates/admin/cms/page/tree/base.html#L16-L17

**Comment by marksweb** [comment]
Hello, @vxsx - it seems to have resolved itself. All I've done since is run `fix-tree` but I can't imagine that could have anything to do with static issues.

**Comment by vxsx** [comment]
No, that doesn't affect these. Probably caching, but hard to tell
