### ISSUE TITLE
Destroy CMS.Plugin instances

### ISSUE THREAD

**Issue by GianlucaGuarini** [divio/django-cms#6074]
### Summary

At moment we can create new `CMS.Plugin` instances in runtime but it's not clear how to destroy them removing all DOM nodes and all the events creaded with the Plugin.

### Expected behaviour

I expect that a plugin can be created and destroyed for example:
```js
const plugin = new CMS.Plugin(name, options)

// remove DOM and events without side effects
plugin.destroy()
```

### Actual behaviour

A plugin can only be created

### Environment

* Python version: 3.5.4
* Django version: 1.10.7
* django CMS version: 3.4.4

p.s.
[This method](https://github.com/divio/django-cms/blob/release/3.4.x/cms/static/cms/js/modules/cms.plugins.js#L1935-L1939) could also return an array of the plugins created using `$.map` instead of `$.each`

**Comment by vxsx** [comment]
In 3.5 we kinda will have the plugin registry available https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.plugins.js#L2156 

We will likely add the destroy method as well in 3.5, as we now handle the page changes without reloads and will need destroying in the core, but likely not for 3.4.x, you'll have to roll your own there

**Comment by GianlucaGuarini** [comment]
@vxsx thanks I am looking forward to it. At moment for our SPA we are forced to do a complete page reload because I don't want to hack the django-cms javascript to handle my own destroy method. Please let me know if I could help you on anything on this task and I will be glad to make a PR

**Comment by vxsx** [comment]
The PR would be most welcome!

**Comment by GianlucaGuarini** [comment]
@vxsx it seems you don't use any js unit test... am I right? Any hint about knowing if I will break anything 😄 ? 

![](https://i.imgur.com/A0kTa8i.gif)

**Comment by GianlucaGuarini** [comment]
Ok I will use and add a new test here in the [integration tests](https://github.com/divio/django-cms/tree/release/3.4.x/cms/tests/frontend/integration) never mind

**Comment by vxsx** [comment]
There are also unit tests available https://github.com/divio/django-cms/tree/release/3.4.x/cms/tests/frontend/unit

Integration tests are currently broken on develop so might be a bit tricky
