### ISSUE TITLE
AttributeError: 'str' object has no attribute 'regex' in cms/appresolver.py

### ISSUE THREAD

**Issue by artforlife** [divio/django-cms#6075]
### Summary
I was manually updating the site to Django 1.10 and Django-CMS 3.4.4 (from 3.4.3) but began receiving the following error:

>   File "/django-cms-env/lib/python3.6/site-packages/cms/urls.py", line 19, in <module>
>     urlpatterns = get_app_patterns()
>   File "/django-cms-env/lib/python3.6/site-packages/cms/appresolver.py", line 189, in get_app_patterns
>     return _get_app_patterns()
>   File "/django-cms-env/lib/python3.6/site-packages/cms/appresolver.py", line 253, in _get_app_patterns
>     app_ns, get_patterns_for_title(path, title), app)
>   File "/django-cms-env/lib/python3.6/site-packages/cms/appresolver.py", line 183, in get_patterns_for_title
>     url_patterns += recurse_patterns(path, pattern_list, page_id)
>   File "/django-cms-env/lib/python3.6/site-packages/cms/appresolver.py", line 110, in recurse_patterns
>     app_pat = pattern.regex.pattern
> AttributeError: 'str' object has no attribute 'regex'

### Environment
Below is the output of `pip freeze > requirements.txt`

> alabaster==0.7.10
> aldryn-apphooks-config==0.3.3
> aldryn-background-image==0.1.1
> aldryn-boilerplates==0.7.5
> aldryn-bootstrap3==1.2.2
> aldryn-categories==1.0.4
> aldryn-common==1.0.4
> aldryn-events==1.1.7
> aldryn-forms==2.2.2
> aldryn-newsblog==1.3.3
> aldryn-people==1.2.2
> aldryn-reversion==1.0.9
> aldryn-translation-tools==0.2.1
> Babel==2.4.0
> backport-collections==0.1
> cssselect==1.0.1
> cssutils==1.0.2
> dj-database-url==0.4.2
> Django==1.10
> django-absolute==0.3
> django-appconf==1.0.2
> django-appdata==0.1.6
> django-bootstrap3==8.2.3
> django-classy-tags==0.8.0
> django-cms==3.4.4
> django-emailit==0.2.2
> django-extended-choices==1.1.1
> django-filer==1.2.7
> django-formtools==2.0
> django-mptt==0.8.7
> django-parler==1.7
> django-phonenumber-field==1.3.0
> django-polymorphic==1.0.2
> django-reversion==1.10.2
> django-sekizai==0.10.0
> django-simple-captcha==0.5.5
> django-sizefield==0.9.1
> django-sortedm2m==1.3.3
> django-standard-form==1.1.1
> django-tablib==3.2
> django-taggit==0.22.1
> django-treebeard==4.1.0
> djangocms-admin-style==1.2.7
> djangocms-attributes-field==0.2.0
> djangocms-column==1.7.0
> djangocms-file==2.0.2
> djangocms-googlemap==1.1.0
> djangocms-installer==0.9.6
> djangocms-link==2.1.2
> djangocms-picture==2.0.5
> djangocms-snippet==1.9.2
> djangocms-style==2.0.2
> djangocms-text-ckeditor==3.5.0
> djangocms-video==2.0.3
> docutils==0.13.1
> easy-thumbnails==2.3
> future==0.16.0
> html5lib==0.9999999
> imagesize==0.7.1
> Jinja2==2.9.6
> lxml==3.7.3
> MarkupSafe==1.0
> olefile==0.44
> phonenumbers==8.4.3
> phonenumberslite==8.4.3
> Pillow==4.1.1
> premailer==3.0.1
> Pygments==2.2.0
> python-dateutil==2.6.0
> python-slugify==1.2.0
> pytz==2017.2
> requests==2.14.2
> six==1.10.0
> snowballstemmer==1.2.1
> Sphinx==1.6.2
> sphinxcontrib-websupport==1.0.1
> tablib==0.11.4
> tzlocal==1.4
> Unidecode==0.4.20
> YURL==0.13

* Python version: 3.5
* Django version: Django 1.10
* django CMS version: 3.4.4

**Comment by czpython** [comment]
Hello @artforlife , please make sure to submit questions/support within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In your case, I think the issue might be related to using urlpatterns which is deprecated.
