### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by jproffitt** [divio/django-cms#6083]
### Summary

There are a lot of deprecation warnings when running on django 1.10, which django CMS supports. It would probably be a good idea to clean those up. 

### Expected behaviour

no deprecation warnings

### Actual behaviour

Lots of warnings. Note: since django 1.10, you have to run python with `-Wd` to see the warnings. Might be a good idea to do that when running the tests suite.

Here's a list of all the warnings:

1. "Importing from `django.core.urlresolvers` is deprecated in favor of `django.urls`".
    - This is done in several places.
2. "on_delete will be a required arg for `OneToOneField` in Django 2.0. Set it to `models.CASCADE` on models and in existing migrations if you want to maintain the current default behavior." 
    - This warning happens all over the place. 
    - To fix, every `ForeignKey` in all existing migrations need to set `on_delete=models.CASCADE` if they do not already specify `on_delete`. Then, set `on_delete=models.CASCADE` on all `ForeignKey`'s in all models, unless cascade is not the intended behavior. If the behavior should be different, new migrations will need to be created after changing  the models. 
3. "Managers from concrete parents will soon qualify as default managers. As a result, the 'objects' manager won't be created (or recreated) automatically anymore on 'cms.PageUserGroup' and 'objects' declared on 'auth.Group' will be promoted to default manager. You can declare explicitly `objects = models.Manager()` on 'PageUserGroup' to keep things the way they are or you can switch to the new behavior right away by setting `Meta.manager_inheritance_from_future` to `True`."
    - This only happens once from what I can tell, but the warning is pretty self-explanatory.

There could probably be more warnings. These are only the ones I see when I run my own test suite on my own project which uses django CMS.

**Comment by czpython** [comment]
@Julz089 I think it makes sense to leave it configurable. Can you push a pr?
