### ISSUE TITLE
Django CMS Apphook only redirects to the root path

### ISSUE THREAD

**Issue by mosesmc52** [divio/django-cms#6091]
### Summary

With additional URLs included, the custom apphook redirects only to the root path view. For example, if the redirect path was set to '/location'. The apphook would redirect to '/' path.

### Expected behavior

The apphook should redirect to the path specified.

### Actual behavior

Instead, it redirects only to the root path

My suspicion is that in the apphook_pool.py file, since the order of all of the paths are lost. After sorted, the root path is first and it is always called and never the other paths.

### Environment

* Python version: 2.7
* Django version: 1.8.4
* django CMS version: 3.4.4

**Comment by czpython** [comment]
Hello @mosesmc52,
I'm not sure I fully understand the issue.
Can you post the urls / views for your custom apphook?

**Comment by mosesmc52** [comment]
It seems like I'm misunderstanding how to configure the apphooks feature. In my example, I created a page with the path /studios/. Within the app hook, I created a route like this. (Patika represents the name of the application)

url(r'^studios/$','patika.views.studios'),

When I try to load the page using [hostname]/studios/, the page is blank. However, when I load the page [hostname]/studios/studios/. It loads the correct route. The route I want to use is [hostname]/studios/. I believe I'm misconfiguring something the template in the settings.

**Comment by czpython** [comment]
Hello @mosesmc52,
You need to set the application urls as `url(r'^$','patika.views.studios')`.
The url paths defined in your app will always be relative to the url defined on the page, so if on the page you define `/page-url/` then **all** urls on your app will start with `/page-url/`.

**Comment by mozilla-rowvigor** [comment]
I understand. To complicate things I have another URL route called 'events', in this return request.

return [
            url(r'^$','patika.views.studios'),
            url(r'^events/','patika.views.events'),
]

 Everytime when I run the ap and insert '/events/', Django CMS redirects me to the studio page instead of events. In order to redirect to the events page, I need to type '/events/events/' in the browser. How do I set the route within apphooks to direct to the events page?
