### ISSUE TITLE
Move "redirect to" and "manual url" from advanced to standard settings

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#6102]
There is a permission to allow or disallow staff users the access to **advanced settings**.
We don't want regular staff to be able to add/edit app hooks. We do however want them to be able to edit the **redirect to** and **manual URL** attributes.
I propose moving those two fields to the **standard settings** since they are more commonly used and not necessarily "advanced".

Or as an alternative provide more granular permissions for the various fields.

**Comment by czpython** [comment]
Moved to https://groups.google.com/forum/#!topic/django-cms-developers/-FI7jb5DQr4
