### ISSUE TITLE
Nested plugin inside parent plugin

### ISSUE THREAD

**Issue by krzysztofp** [divio/django-cms#6103]
I have rather a general question or a feature request, not sure. Looks like a very common use case, but I couldn't find any useful information though.

I'm trying to prepare around 10-15 custom "high-order" plugins that will consist of simple:
- text
- image
- link
- h1-h7
elements

I'd like these "high-order" to be available for the user in the plugin dropdown and when he selects one - it will add that plugin with nested plugins automatically.

So say I have a list of the following "high-order" plugins:
![image](https://user-images.githubusercontent.com/1634660/31615674-9618eaa4-b28a-11e7-9b16-1abf97f52c26.png)

Similar to "slides" in PowerPoint, so I can add a single "slide" containing of smaller elements:
![image](https://user-images.githubusercontent.com/1634660/31615725-ceb7b3fe-b28a-11e7-8ee2-21864a8f547e.png)

Another example - let's assume I'm creating a plugin that looks like this bar:
![image](https://user-images.githubusercontent.com/1634660/31615853-427dee34-b28b-11e7-8789-5c85b7ed8858.png)

I imagine it will automatically add multiple buttons, text and header fields as nested/child plugins into my parent plugin.

Is that easily possible within Django CMS? I was googling for nested plugins, but couldn't find any useful information about it.

**Comment by czpython** [comment]
Hello @krzysztofp , please make sure to submit questions/support within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

**Comment by krzysztofp** [comment]
@czpython how about making this issue a feature request? How do I submit feature requests for missing features?
