### ISSUE TITLE
Default Plugins limit

### ISSUE THREAD

**Issue by EpokeWeb** [divio/django-cms#6119]
### Summary
Can't have more than 105 different plugins in one page. If I add a new one after that, I c'ant have access to the edit mode on this page (I get a 500 error). I have to delete the plugin first. Any plugin, in any placeholders do the same.

### Expected behaviour
When adding more than 105 plugins, the page should be loading normaly and I should be able to add more plugins.

### Actual behaviour
When adding 106th plugin on a single page, i get a error 500 and i have to delete the plugin in the database to see the webpage again.

### Environment

* Python version: 3.5.4
* Django version: 1.8.18
* django CMS version: 3.4.5

**Comment by czpython** [comment]
Hello @EpokeWeb,
Please provide us a traceback of the 500 error you get.

**Comment by czpython** [comment]
Closing.
Please reopen if this is still an issue.
