### ISSUE TITLE
No configuration questions asked when creating a project

### ISSUE THREAD

**Issue by joshfcollins** [divio/django-cms#6120]
The command `djangocms -p . [project name]` is supposed to ask configuration questions according to the tutorials. For example: using the Bootstrap template or setting the admin.

This hasn't happened for me. Why is this? Please look into it

**Comment by vxsx** [comment]
Hi,
`djangocms` cli is https://github.com/nephila/djangocms-installer
and since version 0.9  it's not asking questions by default http://djangocms-installer.readthedocs.io/en/latest/usage.html#batch-mode-default

For the command to use wizard mode you need to use `-w` option.

Which tutorials are you referring to?

**Comment by joshfcollins** [comment]
Thanks Vadim, I managed to figure that out in the end. I've been working
through the book: Beginning Django CMS, by Nigel George. It contains a
forward by Daniele Procida, from Divio. Do you know of anything else from
the book that has changed?

**Comment by vxsx** [comment]
Well, to be honest, I haven't read the book myself, but quite a lot have changed in 2 years since it's been published. 
These guides and documentation should always be up to date though: http://docs.django-cms.org/en/release-3.4.x/how_to/index.html

**Comment by joshfcollins** [comment]
Hi Vadim,

I'd like to dynamically create thumbnails based on my blog posts which
would be published through the frontend. Is accessing the database the best
approach?

**Comment by vxsx** [comment]
Hi @joshfcollins, I think it would be better if you ask the question on Stackoverflow. Otherwise, maybe this tutorial can help http://support.divio.com/academy/basic-how-to-build-a-website-and-blog-with-django-cms-60-minutes/introduction (blog starts from part 9)
