### ISSUE TITLE
Inline formset on CMS_wizard?

### ISSUE THREAD

**Issue by elebumm** [divio/django-cms#6127]
I have a model that has a foreign key

```
class Show(models.Model):

    title = models.CharField(blank=True, max_length=300)
    header_image = FilerImageField(blank=True, related_name='show_header_image')
    genre = models.CharField(blank=True, null=True, max_length=100, choices=GENRES)
    
    def __str__(self):
        return str(self.title)


class ShowDates(models.Model):
    show = models.ForeignKey(Show, on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateField(default=datetime.datetime.today, blank=True)

    def __str__(self):
        return str(self.date)


```

I am unable to find a way to use `inline_formsets` to be implemented inside of the cms_wizards. Is there any way?

**Comment by czpython** [comment]
Hello @elebumm , please make sure to submit questions/support within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.
