### ISSUE TITLE
Placeholder inside menu template is invisible

### ISSUE THREAD

**Issue by jedie** [divio/django-cms#6157]
I have something like this:
```
{% show_menu 0 100 100 100 "foo/bar.html" %}
```
And in `"foo/bar.html"` is a placeholder. This placeholder isn't rendered and i can't filled it in frontend editing.

I look around and found that the placeholder doesn't exist in the result of `cms.models.pagemodel.Page.rescan_placeholders()`

It it inpossible to insert a placeholder in a menu template ?!?

**Comment by czpython** [comment]
Hello @jedie,
The cms will not find any {% placeholder %} or {% static_placeholder %} tags rendered by another template tag. This is by design.

**Comment by jedie** [comment]
Thanks for the info... This information is missing from the documentation, isn't it?
