### ISSUE TITLE
Erroneous scanning of placeholders in inherited nested blocks

### ISSUE THREAD

**Issue by dimkyr** [divio/django-cms#6170]
### Summary

In a child template, we place a `{{block.super}}` reference to a  doubly nested block in the parent.
If the doubly nested block contains a placeholder, it is counted twice by the `get_placeholders()` function.

### Steps to reproduce

base.html:

```html
{% load cms_tags %}

<html>
<body>
{% block content %}
    {% block content_top_links %}
        {% placeholder 'content_top_left' inherit %}
    {% endblock content_top_links %}
{% endblock content %}
</body>
</html>
```
index.html:
```html
{% extends "base.html" %}

{% load cms_tags %}

{% block content %}
    {{ block.super }}
    This is new text.
{% endblock content %}
```

### Expected behaviour

No warning should appear because placeholder 'content_top_left' appears only once in the actual page.

### Actual behaviour
When index.html is parsed by the `cms.utils.placeholder.get_placeholders()` function, a warning is raised:

```bash
home/vagrant/env_migration_new/local/lib/python2.7/site-packages/cms/utils/placeholder.py:251: 
DuplicatePlaceholderWarning: Duplicate {% placeholder "content_top_left" %} in template index.html.
  DuplicatePlaceholderWarning)
```

### Environment

python: 2.7.6
django: 1.8.18
django-cms: 3.4.5

OS: Ubuntu 14.04.5 LTS
Kernel: 3.13.0-135-generic #184-Ubuntu SMP Wed Oct 18 11:55:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by czpython** [comment]
I believe this is now fixed on the develop branch (3.5)
Considering its a warning, we won't be back-porting the fix to 3.4.x
