### ISSUE TITLE
Raise the meta description's length to 320

### ISSUE THREAD

**Issue by adrien-delhorme** [divio/django-cms#6185]
Google has increased the meta description length: https://searchengineland.com/google-officially-increases-length-snippets-search-results-287596

It was previously 160 characters, it can be now up to 320 characters. Django-cms only allows 155 characters for now.

Maybe the meta description's length should be configurable in the settings?

**Comment by czpython** [comment]
@adrien-delhorme 
Thanks for the report.
Making this configurable would get messy because of migrations.
I think its ok to just raise the length to max 320 characters.

**Comment by kenzic** [comment]
@czpython - Can you make the underlying field something more flexible like a TextField or a CharField with a high max_length value and handle validation in python? I know, not amazing, but it gives more control to the site developer to meeting changing SEO requirements. Not allowing this to be configurable puts the CMS at a disadvantage. Site owners want to implement the change as soon as Google makes it and we have to tell them they need to wait until the next version of the CMS is released.
