### ISSUE TITLE
Any way to disable permission caching or a manual way to update/clear permission cache?

### ISSUE THREAD

**Issue by barsch** [divio/django-cms#6210]
### Actual behaviour

In our environment we syncronise like 400k users once a month between two independend databases using a REST API.  A few (~50) of those users have rights to edit the CMS pages.

However during the monthly sync every user object gets saved on our side as we are considered "the slave database". This triggers (due to ```CMS_PERMISSION = True``` and 
https://github.com/divio/django-cms/blob/release/3.4.x/cms/signals/__init__.py#L115-L138) for each user 8 misses on our cache server (memcached) and monitoring goes crazy as miss to hit ratio is out of the roof.

Excerpt from ```memcached.log``` for a single user
```
<29 get :1:cms-:permission:version
>29 END
<29 delete :1:cms-:permission:40068:view_page
>29 NOT_FOUND
<29 get :1:cms-:permission:version
>29 END
<29 delete :1:cms-:permission:40068:add_page
>29 NOT_FOUND
<29 get :1:cms-:permission:version
>29 END
<29 delete :1:cms-:permission:40068:change_page
>29 NOT_FOUND
<29 get :1:cms-:permission:version
>29 END
<29 delete :1:cms-:permission:40068:change_page_advanced_settings
>29 NOT_FOUND
<29 get :1:cms-:permission:version
>29 END
<29 delete :1:cms-:permission:40068:change_page_permissions
>29 NOT_FOUND
<29 get :1:cms-:permission:version
>29 END
<29 delete :1:cms-:permission:40068:delete_page
>29 NOT_FOUND
<29 get :1:cms-:permission:version
>29 END
<29 delete :1:cms-:permission:40068:move_page
>29 NOT_FOUND
<29 get :1:cms-:permission:version
>29 END
<29 delete :1:cms-:permission:40068:publish_page
>29 NOT_FOUND
```

Using ```CMS_CACHE_DURATIONS['permissions'] = 0``` didn't disable this behaviour. Setting  ```CMS_PERMISSION = True``` to ```False``` is no option as page permissions are used.

Is there any way to disable permission caching or a manual way to update/clear permission cache?

### Expected behaviour

Don't spam cache server with unneeded requests ...

### Environment

* Python version: 2.7.x
* Django version: 1.11.9
* django CMS version: 3.4.5

**Comment by czpython** [comment]
Hello @barsch , please make sure to submit questions/support within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

**Comment by czpython** [comment]
@barsch I think the only workaround would be to disconnect those signals on start-up and make sure to set permissions cache duration to 0. The only signals truly needed are `post_save_user` and `post_save_user_group`.

**Comment by barsch** [comment]
@czpython - many thanks for your comment - your solution seems to work - another idea would be just temporarly disconnect before writing the user object and reconnect afterwards, but there are just to many signals ...
