### ISSUE TITLE
url not found when set DEBUG to False

### ISSUE THREAD

**Issue by helvrud** [divio/django-cms#6229]
### Summary

I have almost default instalation of Django cms
when I set the settings.DEBUG parameter to False I receive the error 

_Not Found
The requested URL / was not found on this server._

I am running nginx web server with uwsgi through unix socket
### Environment

* Python version:  3.5.3
* Django version: 1.8.18
* django CMS version: 3.4.5

**Comment by czpython** [comment]
Hello @helvrud , please make sure to submit questions/support within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.
