### ISSUE TITLE
bs4

### ISSUE THREAD

**Issue by yangchnet** [divio/django-cms#6238]
I can't use bs4 in python3.6 ,and my bs4's version is 4.6.0. Is bs4 does not support python3.6?

**Comment by czpython** [comment]
Hello @yangchnet , please make sure to submit questions/support within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.
