### ISSUE TITLE
PlaceHolderField not removing plugin data on model instance deletion.

### ISSUE THREAD

**Issue by crivet** [divio/django-cms#6240]
### Summary

I've encountered an issue with using PlaceHolderFields in app models, that i'm not sure how to resolve. 

I'm not sure if it's due to a configuration error on my part, or if it's from the underlying code base, but if a model contains a PlaceHolderField, the plugins added to that field are never removed from the database if the model instance is deleted. As you can imagine, this has the potential to retain a lot of unused content in the database with no native option to remove it.

Additionally, the models are utilizing django-polymorphic in some cases, though I've tested with a generic 'model.Model' containing only a PlaceHolderField as well, and it's still producing the issue.

Currently in the application I'm developing I have several models utilizing the PlaceHolderFields for generating display content. (this is my first time posting an issue so please excuse any formatting issues)

models.py:

```
# Polymorphic parent model
class Section(PolymorphicModel):
    class Meta:
        app_label = 'core'
        verbose_name_plural = 'Sections'

    #... fields/methods ...

# child model
 class ReadingSection(Section):
    class Meta:
        verbose_name_plural = 'Sections (Reading)'
     
     #... fields/methods ...
    content = PlaceholderField('reading_content')
```
    
admin.py:

```
class SectionChildAdmin(PolymorphicChildModelAdmin):
    base_model  = Section
    show_in_index = True

class ReadingSectionAdmin(PlaceholderAdminMixin, SectionChildAdmin):
    model = ReadingSection
    base_model  = ReadingSection
 
class SectionParentAdmin(PlaceholderAdminMixin, PolymorphicParentModelAdmin):
    """ The parent model admin """
    base_model = Section

    child_models = (
            (ReadingSection, ReadingSectionAdmin),
            # ...other section types...
        )

```

settings.py:
```
CMS_PLACEHOLDER_CONF = {
    'reading_content':{
        'plugins': ['TextPlugin', ],
        'limits': {
            'TextPlugin': 1,
        },
        'default_plugins': [
            {
                'plugin_type': 'TextPlugin',
                'values':{
                    'body': 'This Reading Section doesn\'t appear to have any content.',
                }
            }
        ]
    },
```
using the above configuration, i have the ability to add content to the 'ReadingSections', as well as additional child plugins that all work as expected to add a TextPlugin to the section with custom child plugins, but the issue arises when Deleting one of the 'Sections'. 

If one of the ReadingSections is deleted from the database through the admin interface, and i check the database afterwards, the content that was populating the placeholderfield persists. 

entries for the placeholder can remain present in the following db tables:
- cms_placeholder
- cms_plugin
- djangocms_ckeditor_Text
- potentially others that i haven't mentioned

### Expected behaviour

Upon deletion of a model instance utilizing a Placeholder field, ReadingSection in this case, the content that was placed in the TextPlugins as well as it's child plugins are also removed.

### Actual behaviour
Ghost content...
references to placeholder fields linked to cmsplugins, linked to previously input text that was only referenced by a model instance that is deleted. 

There are no errors warning of this, no exceptions get fired, just leftover content left behind in the database with no page to call home...

As I've said, I've also attempted to set up a test case using a very simple model, only containing an id and a PlaceHolderField, but that test also left the ghost content in the database.

I've been looking for a solution to this under the assumption that I've configured something incorrectly, but i have yet to locate any information of value, only a couple other threads of people describing a similar issue

Any Assistance/Guidance/Corrections would be greatly appreciated

### Environment

* Python version: 3.6.3
* Django version: 1.11.7
* django CMS version: 3.4.5
* django-polymorphic: 1.3

**Comment by czpython** [comment]
Hello @crivet,
By design, the django CMS `PlaceholderField` does not handle deletion of the plugins for you.
If you would like to clear the placeholder content and remove the placeholder itself when the object that references it is deleted, you can do so by calling the `clear()` method on the placeholder instance and then the delete() method, you can do this either on your model's delete method or the admin's.

**Comment by crivet** [comment]
Paulo,



Thanks for the information. Could you provide a snippet of the overriding 
the model’s delete method and getting the reference to the placeholder to 
call clear?



I’m having trouble locating the calls required to get the placeholder 
itself.



Regards,

-crivet
