### ISSUE TITLE
Missing Toggle toolbar arrow for CMS Toolbar

### ISSUE THREAD

**Issue by plamen-nikolov** [divio/django-cms#6242]
### Summary

Missing Toggle toolbar arrow for CMS Toolbar

### Expected behaviour

In case of front-end edit and edit mode enabled, Toggle toolbar arrow should be available in order to toggle the CMS toolbar. That's very useful if there is a header menu as the CMS Toolbar overlaps it.

### Actual behaviour

CMS Toolbar overlaps the header menu and there is no easy way to toggle it.

### Environment

* Python version: 2.7.10
* Django version: 1.11.9
* django CMS version: 3.5.0RC1

**Comment by czpython** [comment]
Hello @plamen-nikolov,
Thanks for reporting this.
Could you provide us with a screenshot of the issue?

**Comment by vxsx** [comment]
The toggle is no longer there in 3.5. That's by design. You can use `cms-toolbar-expanded` to move the header down.

**Comment by Mezgrman** [comment]
what a stupid fucking design decision.

**Comment by victor-yunenko** [comment]
Hence the users are obligated to adapt any third-party libraries that don't except a global overlapping global header? Could somebody share the the reasoning behind this decision?

**Comment by jrief** [comment]
@victor-yunenko a workaround I use is to adopt the CSS as:
```css
html.cms-toolbar-expanded {
	.navbar-fixed-top, .fixed-top {
		top: 46px;
	}
	.modal-dialog {
		margin-top: 3.5rem;
	}
}
```

Then, if Django-CMS toolbar is expanded, move everything, even with `position: fixed`, such as a navbar, by 46px downwards.

**Comment by victor-yunenko** [comment]
Thank you for the snippet, it works!

Naturally I still wish we didn't need to remember to add plugins class names to this snippet 😅
