### ISSUE TITLE
Nodes from CMSAttachMenu are ignored by cms.admin.pageadmin.get_published_pagelist

### ISSUE THREAD

**Issue by jrief** [divio/django-cms#6251]
### Summary

Nodes added by a class inheriting from from `CMSAttachMenu` are ignored by `cms.admin.pageadmin.get_published_pagelist` which builds a results list, when querying  *Redirect* in the *Advanced Settings* of **Pages**.

### Expected behaviour

Since Nodes returned by `CMSAttachMenu.get_nodes()` are part of the CMS menu tree, I would expect them to be offered by the *Redirect* input field of *Advances Settings*.

### Actual behaviour

Only CMS pages are returned, but not nodes added by a menu extension.

By reading the code, it seems as if this feature was forgotten, since not attempt has been made to add these nodes to the result set.

### Environment

* Python version: all
* Django version: 1.11
* django CMS version: 3.4.5

**Comment by czpython** [comment]
Hello @jrief,
This is expected behavior.
The redirect option only allows for cms pages by design.
We don't plan to integrate menu nodes into the redirect field.

**Comment by jrief** [comment]
@czpython hmm, there is no workaround, it's not explicitly documented and can't be overridden. 

However, this feature might be useful and sooner or later someone else will hit the same issue. An API should be *complete*, meaning that you can do anything you like with it. So please reopen and lets discuss about alternatives.
