### ISSUE TITLE
"Unable to render cms menu. There is a language misconfiguration." in edit mode after upgrading to 3.5.0

### ISSUE THREAD

**Issue by timgraham** [divio/django-cms#6265]
After upgrading from django-cms 3.4.5 to 3.5.0, a `{% show_menu 1 2 0 1 %}` call (on all pages where that's present) gives this traceback:
```
File "/home/tim/code/django-cms/menus/menu_pool.py" in get_nodes
  216.         nodes = self._build_nodes()
File "/home/tim/code/django-cms/menus/menu_pool.py" in _build_nodes
  167.                 nodes = menu.get_nodes(self.request)
File "/home/tim/code/django-cms/cms/cms_menus.py" in get_nodes
  300.             menu_node = _page_to_node(page)
File "/home/tim/code/django-cms/cms/cms_menus.py" in _page_to_node
  285.                 fallbacks=fallbacks,
File "/home/tim/code/django-cms/cms/cms_menus.py" in get_menu_node_for_page
  157.         raise RuntimeError('Unable to render cms menu. There is a language misconfiguration.')
Exception Type: RuntimeError at /ministries/
Exception Value: Unable to render cms menu. There is a language misconfiguration.
```
(only if logged in)

I'm still debugging to find the root cause, but I found that commenting out:
https://github.com/divio/django-cms/blob/fd5956bef4b74b0a8c144c2ecde74fdae67756a7/cms/cms_menus.py#L244
fixes the issue. It might be a mismatch between page id in the `cms_title` table.

### Environment

* Python version: 3.5
* Django version: 1.11.10
* django CMS version: 3.5.0

**Comment by czpython** [comment]
Thanks for reporting this.
Can you check if there's any page in db with no title objects?
Or a page with less title objects on draft mode than on live mode?

**Comment by timgraham** [comment]
Yes, the page that raises the exception has `publisher_is_draft=True` but its only title has `publisher_is_draft=False`.

**Comment by czpython** [comment]
Interesting!
I decided to let the exception propagate to catch these sorts of corruptions from older versions.
Although I have not seen this one before.
Can you check if the `publisher_is_draft` was `False` prior to migrating to 3.5?

**Comment by timgraham** [comment]
I used this script and identified 4 bad pages in the pre-3.5 database (and the results are the same after migrating):
```python
from cms.models import Page
for page in Page.objects.all():
    for title in page.title_set.all():
        if title.publisher_is_draft == page.publisher_is_draft:
            break
    else:
        print('bad page %s' % page.pk)
```

**Comment by czpython** [comment]
So I think in this case the fix would be to set those title objects to draft.
Make sure to check if they have a publisher_public relationship and if so do they link to another broken title?

I'll leave this ticket open for a few days in case anyone else runs into this.
Sadly there's not much we can do as there's quite a lot of different types of data corruptions from older versions.

One idea would be to put these checks into the checks module but we anyways can't / shouldn't fix these automatically as they're quite specific and should be treated with care.

**Comment by timgraham** [comment]
Okay, I ran `Title.objects.filter(page_id__in=(4, 306, 380, 412)).update(publisher_is_draft=True)` to resolve the problem. I don't see any problems with the publisher_public relationships. My only concern is if the corruption occurs again, it renders the entire site uneditable. Thanks for your help, I guess it's okay to close this unless some sort of mention in the 3.5 release notes might be warranted.
