### ISSUE TITLE
Broken links to GitHub in Django-cms website

### ISSUE THREAD

**Issue by omiras** [divio/django-cms#6272]
### Summary

Broken links to GitHub in django-cms documentation website. 

### Expected behaviour

To be able to edit/contribute in the documentation edition in GitHub.

### Actual behaviour

User is redirected to a broken Github page.

![screenshot from 2018-02-06 10-35-22](https://user-images.githubusercontent.com/3286458/35852296-cddf7b94-0b2a-11e8-846c-2d9986cfc03e.png)

**Comment by czpython** [comment]
Fixed. Thanks for reporting this.
