### ISSUE TITLE
IntegrityError at /admin/cms/page/1/bg/publish/

### ISSUE THREAD

**Issue by plamen-nikolov** [divio/django-cms#6277]
### Summary

I'm setting up a brand new instance of Django-CMS 3.5.0 and trying to configure the HOME page.
Here is the page structure:

Top Menu
Slider-Placeholder-1
   - Slider plugin

Content-Placeholder-1
   - Ajax search plugin

Home-Tab-Placeholder-1
   - Another plugin

Home-Tab-Placeholder-2
   - Another plugin

Home-Tab-Placeholder-3
   - Another plugin

Home-Tab-Placeholder-4
   - Another plugin

Home-Tab-Placeholder-5
   - Another plugin

Footer-Title-Static-Placeholder-1
Footer-Static-Placeholder-1

Successfully saved.
Than I try to edit the page and add link & text plugins to the footer. The following error occurs:

> IntegrityError at /admin/cms/page/1/bg/publish/ update or delete on table "cms_cmsplugin" violates foreign key constraint "catalog_ajaxsearc_cmsplugin_ptr_id_3095ec55_fk_cms_cmsplugin_id" on table "catalog_ajaxsearchpluginmodel" DETAIL: Key (id)=(12) is still referenced from table "catalog_ajaxsearchpluginmodel". Request Method: POST Request URL:

The Ajax Search Plugin contains has a model configured with one text field - template type. If I try to delete the Ajax search plugin, it fails with:

> IntegrityError at /admin/cms/page/delete-plugin/4/
update or delete on table "cms_cmsplugin" violates foreign key constraint "catalog_ajaxsearc_cmsplugin_ptr_id_3095ec55_fk_cms_cmsplugin_id" on table "catalog_ajaxsearchpluginmodel"
DETAIL:  Key (id)=(4) is still referenced from table "catalog_ajaxsearchpluginmodel".

I tried to disable FK Constraints and remove the plugin and it worked. The catalog_ajaxsearchpluginmodel should usually contain 1 records - horizontal template, but for some reason there are 8 items in it that I haven't configured myself. It seems catalog_ajaxsearchpluginmodel it not getting cleaned up every time when I remove the corresponding plugin

I did the following test cases:

Dropped the database and started on. Added one Ajax Search Plugin with horizontal value for plugin model. Then checked the DB: There were two records in cms_cmsplugin and two in catalog_ajaxsearchpluginmodel. Than I deleted the plugin and checked the DB - There were no records in cms_cmsplugin and two records in catalog_ajaxsearchpluginmodel.

The same test case with Django-CMS 3.4.5. Before deleting the plugin - two records in cms_cmsplugin and two in catalog_ajaxsearchpluginmodel. When I deleted the plugin, there were 0 records in cms_cmsplugin and 0 records in catalog_ajaxsearchpluginmodel. It turns out the problem is with Django CMS 3.5.0 only.

* Python version: 2.7.6
* Django version: 1.10.8
* django CMS version: 3.5.0
* PostgreSQL: 9.4.11

**Comment by czpython** [comment]
Hello @plamen-nikolov,
Thanks for reporting this.
I see in your test case that you mentioned **two** records for the ajax plugin, did you publish the page? If so then is ok to have to records, otherwise that's an issue.

Aside from that I see that both records are deleted for both tables on 3.4 but not on 3.5.
Can you provide me with the code for this ajax search plugin?

**Comment by plamen-nikolov** [comment]
> I see in your test case that you mentioned two records for the ajax plugin, did you publish the page? If so then is ok to have to records, otherwise that's an issue.

Yes, all the page content is published, and there are still two records in both tables. That also happens for 3.4.5 though.

`PLUGIN_TEMPLATES = (
    ("catalog/plugins/ajax_search/ajax_search_vertical.part.html", "Vertical"),
    ("catalog/plugins/ajax_search/ajax_search_horizontal.part.html", "Horizontal"),
)

class AjaxSearchPluginModel(CMSPlugin):
    template = models.CharField("Template", max_length=255, choices=PLUGIN_TEMPLATES)


class AjaxSearchPlugin(CMSPluginBase):
    name = _(u"Catalog - Ajax Search module")
    model = AjaxSearchPluginModel
    render_template = PLUGIN_TEMPLATES[0][0]
    cache = False`

**Comment by czpython** [comment]
Its ok for there to be two records, when a page is published all its plugins are duplicated and added to the public version of the draft page.
After removing the plugins, did you publish the page?
Also did this plugin change db schema recently? like renaming the model, or other changes?

**Comment by plamen-nikolov** [comment]
> After removing the plugins, did you publish the page?
Yes, I did.

> Also did this plugin change db schema recently? like renaming the model, or other changes?
No

**Comment by czpython** [comment]
Strange.. I'm unable to reproduce this.

**Comment by czpython** [comment]
@plamen-nikolov 
Can you try reproducing this on sqlite3?
Also, can you provide me with an environment where this is reproducible?

**Comment by czpython** [comment]
Ping @plamen-nikolov

**Comment by zypro** [comment]
@czpython same problem here, not reproducible... 
Using python3.6, django 1.11.10, djangocms 3.5.2, apache2.4 and postgres 10.5
This error appears suddenly and we don't know why and how to produce it. Once we thought that we can fix it by removing all .pyc files and touch the wsgi.py... but this was not the right solution...
Often the problem appears if we update the project (with git) and adapt the server in multiple steps.

Means: If I am doing all steps (compilemessages, collectstatic, migrate) in once (in a row), then it is usually working beyond the update. But if I am doing the update and doing a little second fix after it, then the error occurs for sure.

I know, this is a quite bad "description" of an error, but maybe it helps to get new ideas of understanding the problem...

Thanks in advance.
