### ISSUE TITLE
Error when migrating from 3.4.5 to 3.5

### ISSUE THREAD

**Issue by db654** [divio/django-cms#6280]
### Summary

When trying to upgrade cms from 3.4.5 to 3.5, I get the following migration error at cms.0018_pagenode:
>django.db.utils.OperationalError: cannot ALTER TABLE "cms_page" because it has pending trigger events

Haven't seen anyone else report this so I've considered that it may be a third party conflict but it's not a particularly large project.

### Environment

* Python version: 3.5
* Django version: 1.11.10
* django CMS version: 3.5
* Database: postgresql_psycopg2

**Comment by czpython** [comment]
Hello @db654,
What postgres version are you running?

**Comment by db654** [comment]
Apologies @czpython 
9.3.20

**Comment by czpython** [comment]
Thanks for the info.
Is this a project you've migrated from earlier versions?
Meaning did this project start with 3.4.x or was it earlier than that?

**Comment by db654** [comment]
This project started with cms version 3.2.3, django 1.7.

**Comment by db654** [comment]
Interestingly, I just tried going from 3.4.5 to 3.5 on another project, completely different server and hit the same migration error.

This project is running django 1.11, psql 9.4.10 but is older. It started on cms version 2.3.5, django 1.4.

**Comment by czpython** [comment]
The fact that both projects come from earlier versions of cms (older than 3.4) means we might be dealing with a data corruption. I will think about this more to come up with a query you can execute to check this. Thanks for the info, very helpful 👍

**Comment by db654** [comment]
Thanks. I'll share if I come across any more context or some kind of fix for this.

**Comment by czpython** [comment]
Can you run the following query on the shell in your 3.4.x installation:

```python
from cms.models import Page
Page.objects.filter(publisher_is_draft=False, publisher_public__isnull=True).exists()
```
Does it return `True`?

**Comment by db654** [comment]
It returns False.

**Comment by db654** [comment]
@czpython If this helps in pinning this down, the migration completed when run with the lines below commented out.

**0018_pagenode.py**
```
47  #        draft_pages.filter(pk=page.pk).update(
48  #            publication_date=None,
49  #            publication_end_date=None,
50  #        )
```

**Comment by czpython** [comment]
I believe the source of the issue is the PostgreSQL version, there's been quite a few reports of this in vanilla django apps (no cms) where migrations which alter a table can't update the same table in the same transaction (django runs one single transaction for each migration on pg).

This same migration runs well on PostgreSQL versions >=9.5 (not sure on 9.4), but for sure it doesn't run on 9.3. Likely something changed in the way they handle transactions.

More info can be found in https://docs.djangoproject.com/en/1.11/ref/migration-operations/#runpython

In the meantime, I will workout how to fix this because it could mess-up the migration order 😞

**Comment by czpython** [comment]
Hello @db654,
Please try the branch in https://github.com/divio/django-cms/pull/6322
Let me know if the migration goes through.

**Comment by chschuermann** [comment]
Hi @czpython,
I ran into the same problem using Postgres 9.2.4 yesterday. Using your fix with the three migrations just worked like a charm. Thanks!
