### ISSUE TITLE
Http404 from app hook does not trigger defined 404 page

### ISSUE THREAD

**Issue by Natureshadow** [divio/django-cms#6288]
### Summary

Raising an Http404 exception from a cmsapp attached to a page does not result i nthe 404 page being displayed, if the 404 page is defined in the normal CMS pages (i.e. a page with id 404 i nthe normal page tree). The 404 status is correctly set, but Django CMS simply renders the empty app hook page instead of the 404 page.

### Expected behaviour

The page with id 404 is rendered, just like for other non-existent pages.

### Actual behaviour

An empty page is shown.

### Environment

* Python version: 3.5.3
* Django version: 1.10
* django CMS version: 3.4.5

**Comment by czpython** [comment]
Hello, is your page published?

**Comment by Natureshadow** [comment]
>Hello, is your page published?

Yes.

**Comment by czpython** [comment]
Can you post the code of your cms_apps.py and the apphook view?

**Comment by Natureshadow** [comment]
Sure:

https://edugit.org/Teckids/ticdesk/blob/master/ticdesk_cmsstuff/cms_apps.py

https://edugit.org/Teckids/ticdesk/blob/master/ticdesk_cmsstuff/views.py

**Comment by czpython** [comment]
Based on the [view](https://edugit.org/Teckids/ticdesk/blob/master/ticdesk_cmsstuff/views.py#L21) which raises the 404, the cms is not the one handling that exception.

This looks like an issue on the project setup, very likely the `handler_404` renders an empty template.

**Comment by Natureshadow** [comment]
>Based on the
>[view](https://edugit.org/Teckids/ticdesk/blob/master/ticdesk_cmsstuff/views.py#L21)
>which raises the 404, the cms is not the one handling that exception.
>
>This looks like an issue on the project setup, very likely the
>`handler_404` renders an empty template.

I do not understand that.

How do I trigger the normal 404 behaviour of the CMS from within an app view?

**Comment by ellavs** [comment]
Hello! I have the same question, but about plugin. I want to show 404 error from plugin, but Django CMS (v 4.1) doesn't show error and still render page.

Code sample:
```python
from django.http import Http404
from cms.plugin_base import CMSPluginBase
from cms.plugin_pool import plugin_pool

@plugin_pool.register_plugin
class CustomPlugin(CMSPluginBase):
    model = PluginModel
    name = "Custom Plugin"

    def render(self, context, instance, placeholder):
        if some_condition:
            raise Http404("Page not found")

        context['instance'] = instance
        return context
```

In console I got and see error:
`django.http.response.Http404: Page not found`
But web-page still render and show to users...

How to trigger a 404 page from a plugin when users will see a 404 error instead of rendered the page?

**Comment by fsbraun** [comment]
That's currently not possible, I'm afraid. If you believe it should, please raise a new issue describing the feature you need, including a use case that allows to evaluate how beneficial the feature would be to the community.

**Comment by ellavs** [comment]
Thanks for the answer, I found a solution for myself: trigger the 404 error from the middleware, for example:

```python
#middleware.py
from django.http import Http404    
  
class Custom404Middleware:  
    def __init__(self, get_response):  
        self.get_response = get_response  
  
    def __call__(self, request):  
        # conditions that should trigger a 404 error  
        if some_condition:  
            raise Http404("Page not found")  
  
        response = self.get_response(request)  
        return response
```

**Comment by fsbraun** [comment]
Yeah, that works by design. To me it also looks like a cleaner solution.
