### ISSUE TITLE
Unregistering Customized Menus

### ISSUE THREAD

**Issue by swdelaney2** [divio/django-cms#6305]
### Summary

It appears there is no method to unregister customized menus. i.e. `menu_pool.unregister_menu(ExampleMenu)`

After removing code for custom menus, they remain discoverable with `menu_pool.get_registered_menus()` and in logging.

### Environment

* Python version: 2.7
* Django version: 1.11.9
* django CMS version: 3.4.5

**Comment by czpython** [comment]
Hello @swdelaney2 , please make sure to submit questions/support within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

In regards to your question, to unregister a menu, you can do:

`del menu_pool.menus['YourMenuClass']`.

Please note that this is an internal API, as such it is subject to change.
