### ISSUE TITLE
Should throw an error when the child plugins are not rendered in the parent template

### ISSUE THREAD

**Issue by batisteo** [divio/django-cms#6306]
I had the exact same issue as #5085 and it took me a while to find it.

As far as I understood, every plugins should be rendered, even if there the child template is empty.

So I wish there were a Python or JavaScript error thrown when I forgot this block:
```jinja
{% for plugin in instance.child_plugin_instances %}
    {% render_plugin plugin %}
{% endfor %}
```

### Environment

* Python version: 3.5.4
* Django version: 1.10.8
* django CMS version: 3.4.5

**Comment by czpython** [comment]
Hello @batisteo , please make sure to submit questions/support/feature-requests within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.
