### ISSUE TITLE
Publishing updates to home/root page prefixes child public page paths with "%2F" 

### ISSUE THREAD

**Issue by mtully-blitz** [divio/django-cms#6307]
### Summary
The extra slash is only added when both the parent and child page have already been published. The 
draft version of the child page still has the correct path 
Steps to recreate:

1. Create a new page at the root and set as the home page. Use default settings.
2. Publish home page
3. Create a sub-page off the root with a simple title and slug (ex. Archer, archer)
4. Publish sub-page and note its public url. In this case "localhost/archer"
5. Make a change to the home page such updating title or adding a plugin
6. Publish the homepage

### Expected behavior
The public path of child pages should not change

### Actual behavior
As a logged out public user go to localhost/archer and you will get a 404. If you have a menu on your home page it will show the url for the subpage as "/%2Farcher"

### Environment

* Python version: 3.6.6
* Django version: 1.11.10
* django CMS version: 3.5.1 and 3.5.0

### What to Fix
The culprit appears to be this line of code: https://github.com/divio/django-cms/blob/3.5.1/cms/models/pagemodel.py#L1121

I believe fixing is as easy as comparing if base == '/' and excluding the '/'. Will try to confirm.

**Comment by mtully-blitz** [comment]
I haven't reproduced it yet, but looks like the same fix will need to be applied for moving pages as well: https://github.com/divio/django-cms/blob/3.5.1/cms/models/pagemodel.py#L304

**Comment by mtully-blitz** [comment]
This snippet fixes the issue, but sure about other possible side effects.

``` 
        # Prevent extra slash being added to empty base
        if not base == '':
            base += '/'
        # Update public title paths
        unpublished_public.exclude(has_url_overwrite=True).update(
            path=Concat(models.Value(base), models.F('slug'))
        )

**Comment by czpython** [comment]
Thanks for the thorough report.
I've now reproduced the issue, we'll ship a fix with 3.5.2

**Comment by mtully-blitz** [comment]
No problem! Thanks for addressing it. Do you have a rough idea when 3.5.2 might ship?

**Comment by horejsek** [comment]
We had this issue for awhile and wasn't able to reproduce it until today. Anything our customer change on homepage broke many links in the app. Would be great to release it as soon as possible. Any change by users on homepage without notifying developers now means users has problem to access some pages...

Probably because of that we had also problems with pages under app-hook (https://github.com/divio/django-cms/issues/6282).

**Comment by czpython** [comment]
@horejsek 
When you say "for a while", are you reproducing this on 3.4 as well? 
The apphooks limitations/issues are unrelated to this change.

**Comment by horejsek** [comment]
Not sure. We upgraded to 3.5 soon after it's release because it was solving some bugs we had. I have feeling like I saw this problem also in 3.4 but definitely last two weeks we see this bug almost every day, before only very little bit (which could be different bug which is solved now).

**Comment by czpython** [comment]
@mtully-blitz @horejsek 
Can you have a look at the branch in https://github.com/divio/django-cms/pull/6311?
Let me know if the issue persists.

**Comment by mtully-blitz** [comment]
@czpython Looks good to me! I tested these use cases and wasn't able to reproduce the issue:
publishing parent page
publishing parent with an updated slug
moving pages to new parent page
copying a parent page.

**Comment by czpython** [comment]
Great, thanks!

**Comment by horejsek** [comment]
Thanks for the fix! I can check on Monday if it works. But base on the diff and debug I did it should work for us as well.

**Comment by horejsek** [comment]
Tested now, works for us as well.

**Comment by SachaMPS** [comment]
Here also! Yipiiee

**Comment by horejsek** [comment]
When we can expect release of 3.5.2 with this fix? :-)
