### ISSUE TITLE
All custom Javascript breaks after plugin save... (because the DOM gets mutated since 3.5.1)

### ISSUE THREAD

**Issue by SachaMPS** [divio/django-cms#6316]
Hi there,

we used to load our javascript after the CMS (Javascript) modified the DOM. 
This way we could preserve frontend editing and custom javascript stuff like sliders or accordions.

In the latest version of djangoCMS there seems to be something new how the DOM gets refreshed after a plugin save. It appears to me that there is no full page reload anymore - instead it appears the DOM gets (nearly completly) mutated.

This is nice regarding speed but any javascript on the page which has been injected for sliders, offcanvas menus, accordions, etc breaks because all the references are lost.

Its also reproducable on the ALDRY-DEMO-SITE: After a plugin save a click on the blue circle in the right bottom corner doesnt open the window pane anymore.
![image](https://user-images.githubusercontent.com/305877/37720772-486cf674-2d28-11e8-9a12-18f93c254a21.png)

I checked if there are any events i could listen to but didnt find any usable. Right now the only solution we are imagining is to look into the amount of DOM Mutations and will bootstrap our whole javascript again.

Nevertheless i think a event someone could attach on window.CMS.Helpers or similar which would indicate that a plugin is saved would be cleaner. Since the whole DOM seems to be mutated there is no need for element ids or anything else. You have to initialize all javascript again... Well i am not sure if this is so great... but hmm..

I hope you agree that this can be regarded as an issue and not as a feature request. Otherwise I would have posted to the Google Deveoper Group.

*(There is always the possiblity that i am blind regarding a simple solution or talking complete rubbish - if thats the case - Sorry in advance :) )*

**Comment by vxsx** [comment]
Hi! There is an event available to fix those issues: http://docs.django-cms.org/en/latest/topics/frontend-integration.html

(made a not to fix cloud demos as well)

**Comment by vxsx** [comment]
This may be also helpful as an example (although it's a bit of a specific webpack implementation): https://github.com/divio/djangocms-boilerplate-webpack/commit/4ef019b9dd4d74511f4725d9e60692f01371e698

**Comment by vxsx** [comment]
To elaborate - this is a tradeoff we decided to make to improve speed of editing, even if it places a bit of a burden on the website developers. It's not really possible to reload things in smaller chunks because plugins can affect other plugins and certain operations can affect multiple placeholders and so on.

**Comment by SachaMPS** [comment]
Damn, and i really really tried to look very closely but didnt find that event call on window. Thank you!!!!!
