### ISSUE TITLE
{{ csrf_token }} inside of sekizai tag invalidates cache on every page load

### ISSUE THREAD

**Issue by sniku** [divio/django-cms#6323]
There is `{{ csrf_token }}` template variable inside of the `{% addtoblock "js" %}` block in `cms/toolbar/toolbar_javascript.html`.

For logged in admin users, this variable changes on every page load. Since this variable is inside of the sekizai tag, it generates new .js file in `static/CACHE/js/`on every page load. 

This causes 2 major problems for me:
* disk space quickly runs out on the server, as the CACHE folder fills up with gigabytes of cached js files.
* page loads are slower since sekizai compresses and caches js files on every page load

Here's the snippet of code from `cms/toolbar/toolbar_javascript.html`.

```html

{% load i18n l10n sekizai_tags admin_static cms_tags cms_static %}

{% addtoblock "css" %}<link rel="stylesheet" href="{% static_with_version "cms/css/cms.base.css" %}" />{% endaddtoblock %}

{% addtoblock "js" %}
<script src="{% static_with_version "cms/js/dist/bundle.toolbar.min.js" %}" type="text/javascript"></script>
{% language request.toolbar.toolbar_language %}
<script>
CMS._plugins = [];
// this is a global shared configuration
CMS.config = {
    'mode': {% if request.toolbar.edit_mode %}'draft'{% else %}'live'{% endif %},
    'auth': {% if user.is_authenticated %}true{% else %}false{% endif %},
    'debug': {% if debug %}true{% else %}false{% endif %},
    'csrf': '{{ csrf_token }}',
    'request': {
        'language': '{{ request.GET.language|escape|escapejs }}',
        'model': '{{ request.toolbar.get_object_model }}',
        'page_id': '{% if request.current_page.publisher_is_draft %}{{ request.current_page.pk }}{% else %}{{ request.current_page.publisher_public_id }}{% endif %}',
        'pk': '{{ request.toolbar.get_object_pk }}',
        'url': '{% language request.toolbar.language %}{% cms_admin_url "cms_page_resolve" %}{% endlanguage %}',
        'tree': '{% language request.toolbar.language %}{% cms_admin_url "cms_page_changelist" %}{% endlanguage %}'
    },
...
```

I suggest moving the `CMS.config = {...}` outside of the sekizai tag.

**Comment by jproffitt** [comment]
I have this problem as well. I assume you are using django-compressor along with sekizai?
It's sort of a hack, but I fixed it by overriding the `toolbar_javascript.html` file, and moving the js outside of the `addtoblock`.

I think a better fix would be to change CMS to use the CSRF token cookie rather than spitting it out in a template somewhere.

**Comment by czpython** [comment]
Hello,

The cms does not support putting its internal js in compressor.
We already minify the internal js files.
If you want to use compressor with sekizai, please use a different block to add your custom styles, so instead of js block, you can use custom-js block and compress that one.

**Comment by jproffitt** [comment]
I really don't think that's the correct solution. For compressor to work with sekizai, you actually HAVE to name the block either js or css. Or you have to hack the compressor processor for sekizai. For a normal sekizai/compressor setup, django-cms will break it.

I'm really not sure, but is there a reason djangoCMS can't use the csrf token cookie that django provides? For my projects, I always grab the token out of the cookie when I need it for ajax requests. Django actually talks about how to do there here: https://docs.djangoproject.com/en/2.0/ref/csrf/#ajax

**Comment by czpython** [comment]
It is not only about the csrf token but rather all the other dynamic js variables in that file which can't / shouldn't be compressed into a static file.

This is a limitation of sekizai / compressor integration

**Comment by sniku** [comment]
@czpython django-cms is using sekizai_tags, not the client code. See the first line of `cms/toolbar/toolbar_javascript.html.` it clearly loads sekizai  `{% load i18n l10n sekizai_tags admin_static cms_tags cms_static %}`

And the `{% addtoblock "js" %}` block used in `toolbar_javascript.html` is a sekizai tag. 

There's nothing we can do on the client side to fix this. I agree with @jproffitt and vote for the ticket to be reopened.

**Comment by jproffitt** [comment]
@czpython you are right, there is more than just the csrftoken. But you’re basically saying that if you use Django-compressor with sekizai, then there’s nothing you can do. That’s not a very good solution. Right now, the only way to fix this is for me to override the toolbar_javascript.html template in every project, and rename the sekizai block to something else. That is especially painful if I have to upgrade CMS, and that template changes.

I’m not exactly sure what the solution is, but I think we need to think about some way to fix it. We could introduce a second sekizai block not named “JS”, or we could put the JavaScript in this file outside of a sekizai block altogether.

**Comment by jproffitt** [comment]
Another idea: perhaps make the name for the sekizai block a setting that users could change in order to put it in a different block?

**Comment by czpython** [comment]
We are thinking to bundle a compressor processor with sekizai which allows for custom namespaces instead of using css / js only.
