### ISSUE TITLE
Permission issue - "cms | placeholder | Can use Structure mode" not set, users can still access structure board

### ISSUE THREAD

**Issue by harryjacko** [divio/django-cms#6326]
### Summary
I appear to have run into an issue regarding User/Group permissions, specifically the 
`cms | placeholder | Can use Structure mode` permission. 
As I understand it, this limits a user from being able to access the structure board, and can only edit in content mode.

When this is not assigned to a user/group the structure board is still accessible to that user. It appears as though the permission is checked as the structure button (top right) that expands the structure board is removed. However, when double clicking to edit a plugin the structure board then expands.

![screen shot 2018-04-03 at 1 28 56 pm](https://user-images.githubusercontent.com/14305213/38224460-3abb51a8-3744-11e8-8acb-5ecb82825021.png)

The expanded structure board, with the `cms | placeholder | Can use Structure mode` not set, note the structure button is not visible.

### Expected behaviour
The structure board should not be accessible when a user/group does not have the “cms | placeholder | Can use Structure mode” permission set. 

### Actual behaviour
The structure board can be accessed regardless of the `cms | placeholder | Can use Structure mode` permission. It can be accessed by editing a plugin (double click), which will then expand the structure board.

### Environment

* Python version: 3.6.4
* Django version: 1.9.13
* django CMS version: 3.5.0

**Comment by vxsx** [comment]
Could you please check if the issue is reproducible on 3.5.1?

**Comment by vxsx** [comment]
Actually, latest `develop` would be better, it might be this: https://github.com/divio/django-cms/commit/917d768e4ad277bc84e042a5fe9198a565597371

**Comment by vxsx** [comment]
Great. Thanks for checking!
