### ISSUE TITLE
Cached page permissions override global permissions

### ISSUE THREAD

**Issue by czpython** [divio/django-cms#6335]
The cms has page permissions and global permissions.
When a user creates a page permission, the cms will cache the page permissions for any staff user rendering a page and this cache will take precedence over any configured global permissions.

Example:

User has global permission to edit all pages.
A page permission is created to restrict editing to other users on a specific page.

Once cached, that one page permission will override the user's global permission to edit all pages.

Make sure to turn on cms permissions by adding `CMS_PERMISSIONS = True` to settings and make sure permissions are cached (`CMS_CACHE_DURATIONS`).

**Comment by macolo** [comment]
In the meantime you can work around this by setting CMS_CACHE_DURATIONS['permissions'] to 0

```
    CMS_CACHE_DURATIONS = {
        'menus': 60,
        'content': 60,
        'permissions': 0,
    }
```
