### ISSUE TITLE
dumpdata/loaddata cycle not working anymore

### ISSUE THREAD

**Issue by heppstux** [divio/django-cms#6340]
### Summary

dumping database (esp. PageModels) using dumpdata and reinstalling them using loaddata leads to:

Exeption: TreeNode matching query does not exist.

### Expected behaviour

should work.

### Actual behaviour

Exception.

### Environment

* Python version: 2.7
* Django version: 1.11
* django CMS version: 3.5.0 and up

**Comment by heppstux** [comment]
solution should be as simple as declaring the model `TreeNode` **before** `Page` in [pagemodel.py](https://github.com/divio/django-cms/blob/develop/cms/models/pagemodel.py)

**Comment by czpython** [comment]
Hello @heppstux,
Do you have a link to a mention about this in django docs?
Seems a bit odd that model order affects this.

**Comment by heppstux** [comment]
yea, seems strange but, it makes a difference. From what i can see in the django code, models are exported in the order of their initialisation. First comes, first served ;) Try it!

**Comment by mtully-blitz** [comment]
@czpython @heppstux  I've experienced this same error. We can't generate any fixtures that worked. When I get a moment I'll try to test this PR to see if it resolves the issue.

**Comment by jrief** [comment]
@czpython shall I reopen this issue?
