### ISSUE TITLE
Document the text_enabled param for plugins

### ISSUE THREAD

**Issue by jeroenpeters1986** [divio/django-cms#6342]
I think the Django CMS docs could use a little more information about the `text_enabled` attribute, which is available on CMSPlugins.

It's a very cool attribute/setting, but it took me quite some time to find out that I was looking for this when I was developing a plugin for my work.

**Comment by czpython** [comment]
Hello @jeroenpeters1986,
I've moved your ticket to https://github.com/divio/djangocms-text-ckeditor/issues/478.
The text_enabled attribute is not used by the cms but rather by the text plugin.

**Comment by jeroenpeters1986** [comment]
@czpython that is allright, but the docs live in this repo, right?

**Comment by czpython** [comment]
@jeroenpeters1986 the main cms docs yes but this is a feature unique to the text plugin.

**Comment by jeroenpeters1986** [comment]
@czpython okay :-) My contribution would be to the docs, that's why I opened it here
