### ISSUE TITLE
Toolbar randomly renders as mobile version on desktop

### ISSUE THREAD

**Issue by benzkji** [divio/django-cms#6344]
### Summary

On big screens, after a plugin save (mostly), the toolbar is rendered with the mobile layout, i.e. it only shows the "More ..." button. This doesnt happen every time, but quite often...

### Expected behaviour

Normal toolbar shown.

### Actual behaviour

Mobile toolbar shown.

### Environment

* Python version: any
* Django version: any
* django CMS version: 3.5.x

**Comment by czpython** [comment]
I think this is a duplicate of https://github.com/divio/django-cms/issues/6332

**Comment by benzkji** [comment]
thx. dont remember any imgs in head, but will investigate...

**Comment by benzkji** [comment]
happens on firefox as well. have moved sekizais css just before `</head>`, as suggested here (was just after `<body>`): http://docs.django-cms.org/en/latest/how_to/install.html#templates and this helps :) thank you!

**Comment by benzkji** [comment]
consider changing "recommended" to "needed" in the docs ;-)
