### ISSUE TITLE
Version 3.2.6 is not available via pip

### ISSUE THREAD

**Issue by mogoh** [divio/django-cms#6352]
I have django-cms Version 3.2.5 installed, but it says that there is a new Version 3.2.6. 

3.2.6 is not listet here:

http://docs.django-cms.org/en/release-3.4.x/upgrade/3.2.5.html
http://docs.django-cms.org/en/latest/upgrade/3.2.5.html
https://pypi.org/project/django-cms/#history

But it is listed here:
http://docs.django-cms.org/en/release-3.2.x/upgrade/3.2.6.html

**Comment by czpython** [comment]
Hello,
There's no release because 3.2 is no longer supported.
The docs will continue to show the changelog and upgrade notes because it fetches the files from `release/3.2.x branch`.
