### ISSUE TITLE
page_moved signal is not fired

### ISSUE THREAD

**Issue by moellering** [divio/django-cms#6356]
### Summary
Moving a page does not fire the page_moved signal as stated in the documentation

### Expected behaviour
Moving a page does fire the page_moved signal as stated in the documentation

### Actual behaviour
Since commit f7af69f3e15d80f39c2b659b92a47f6cdc3216e1 (treebeard refactoring) there is no page_moved.send in the Page.move_page wrapper function. Thus no page_moved gets sent.

**Comment by czpython** [comment]
The move signal was explicitly removed.
Can you post a link of where in the documentation it mentions this signal?

**Comment by moellering** [comment]
Thanks for clearing that up for me. I didn't find any mention of the signal in the pull request discussion so I assumed an unintentional removal.

The inline documentation of the function (comment) states that move_page ["should be used on all the places which are changing page position. Used like an interface to django-treebeard, but after move is done page_moved signal is fired."](https://github.com/divio/django-cms/blob/fe29ed60d130adc7f6df026da6893c9b4ca9a8b5/cms/models/pagemodel.py#L482)

Is there a discussion I could read on the reasoning for removing that signal or do you know an alternative on how to react on page moves from the top of you head?

**Comment by czpython** [comment]
We are moving away from all custom signals per event, as well as all django builtin signal handlers, for maintenance and performance reasons.

There's no public api for this yet, the move signal was an internal, if you really need this, I suggest to use the "pre object" / "post object" operation signals.

Here's an example handler https://github.com/divio/djangocms-history/blob/master/djangocms_history/models.py#L151, please note that this is still an internal api and as a result can change without an official deprecation.

**Comment by moellering** [comment]
Thanks @czpython for the link!

For everybody else running into a similar problem:
I solved my problem it the following way:

```
@receiver(post_obj_operation)
def recreate_moved_page(sender, **kwargs):
    operation_type = kwargs['operation']
    if operation_type == operations.MOVE_PAGE:
        page : Page = kwargs['obj']
        # DO STUFF HERE
```

Watch out: The post_obj_operation gets called by the `BasePageAdmin` and not by the `Page` object itself. Thus it is not thrown if using the `move_page`method of the Page.

Also I wrote proper tests for this such that I notice if an upgrade of django-cms breaks anything.

**Comment by jrief** [comment]
Then this should not be mentioned in the docstrings as
https://github.com/divio/django-cms/blob/develop/cms/models/pagemodel.py#L487
