### ISSUE TITLE
Documentation: tutorial docs and sample code is out of date

### ISSUE THREAD

**Issue by geoidesic** [divio/django-cms#6358]
### Summary
Documentation and the code-base for `polls` here may be out of date: http://docs.django-cms.org/en/latest/introduction/integrating_applications.html

`urlpatterns` implementation has changed

### Expected behaviour

When installing the `polls` application egg, it should work with the latest version of Django – or the documentation should specify that it won't and explain where to find the information required in order to use the tutorial with Django 1.10+

The out of date code sample is addressed by the a pull request made in April 2017 which hasn’t been accepted yet: https://github.com/divio/django-polls/pull/4

If the pull request is accepted, the docs should still probably be updated to indicate how to make it work with older versions of DjangoCMS. 

My suggestion would be the latter: update the code by accepting the pull request then adjust the docs to explain backward compatibility.

### Actual behaviour

Following the tutorial as it stands with Django 1.10+ leads to error:

`from django.conf.urls import patterns, url
ImportError: cannot import name 'patterns'`

### Environment

* Python version: 3.6.4
* Django version: 1.10
* django CMS version: 3.5.2

**Comment by evildmp** [comment]
[Polls application  is now updated](https://github.com/divio/django-polls/commit/104e777d4ff6a6fb6145e1bd80d650c9286cdef3).
