### ISSUE TITLE
Documentation: integration tutorial – redundant sections with errors in folder resulting structure and build

### ISSUE THREAD

**Issue by geoidesic** [divio/django-cms#6359]
### Summary

This deals with two tutorial links because the two seem to represent a misleading redundancy in the documentation. The tutorials docs on these two links seem to be describing the same thing – or two things which are sufficiently similar that the difference isn't obvious and nor is it explained by the docs. Both seem to be creating polls_cms_integration and integrating it with DjangoCMS, one page has a few extra steps but it's not made clear what the essential difference between these approaches is in the introduction of the page.

http://docs.django-cms.org/en/latest/introduction/integrating_applications.html
http://docs.django-cms.org/en/latest/introduction/plugins.html

In addition each page suffers from errors of a similar nature, so these are described jointly here. 
(Please, both tutorials suffer from the problem described in issue #6358)

### Expected behaviour

1. The documentation indicates that the following folder structure should be the result:

├── env
└── polls_cms_integration
        └── migrations
├── mysite
├── static
   
2. Following the tutorial should not lead to any build errors

### Actual behaviour

1. If you follow either of these tutorials using the installation instructions (http://docs.django-cms.org/en/latest/introduction/install.html) as your starting point then you do not end up with the workflow folder structure as depicted in the tutorial diagrams. This makes it difficult to debug path issues.
├── env
└── tutorial-project
└      ├── media
└      ├── mysite
└     │   ├── __pycache__
└      │   ├── static
└      │   └── templates
└      ├── polls_cms_integration
└      │   └── migrations
└      └── static

2. Following the tutorial after fixing the issue described in #6358 (in the fashion suggested in that issue) leads to a further error:

`
    from polls.models import Poll
ImportError: cannot import name 'Poll'
`
Because the folder structure isn't as suggested in point 1, this becomes difficult to debug.

### Environment

* Python version: 3.6.4
* Django version: 1.10
* django CMS version: 3.5.2

**Comment by geoidesic** [comment]
Any progress on this?

**Comment by evildmp** [comment]
Work in progress to address this.
