### ISSUE TITLE
language_chooser displaying where a menu should be.

### ISSUE THREAD

**Issue by tPegler** [divio/django-cms#6363]
### Summary

I have a Django site using CMS and I have a language_chooser template set which displays fine when called however I have a secondary menu in the footer which seems to be pulling in the main header for the navigation but the child pages are just displaying the language.

Here is my footer navigation template:

```
{% load menu_tags %}

    {% for child in children %}
        {% if child.level == 0 %}
            {% if child.children %}
            <div class="footer-nav-column col-md-2">
                <h6><a href="{{ child.attr.redirect_url|default:child.get_absolute_url }}">{{ child.get_menu_title }}</a></h6>
                    <ul>
                            {% show_menu from_level to_level extra_inactive extra_active template "" "" child %}
                    </ul>
            </div>
            {% else %}
            <div class="footer-nav-column col-md-2">
                <h6><a href="{{ child.attr.redirect_url|default:child.get_absolute_url }}">{{ child.get_menu_title }}</a></h6>
            </div>
            {% endif %}
        {% endif %}

        {% if child.level == 1 %}
        <li><a href="{{ child.attr.redirect_url|default:child.get_absolute_url }}">{{ child.get_menu_title }}</a>
            {% if child.children %}
            <div>
                <ul data-background="assets/images/menu-1.jpg">
                    {% show_menu 1 100 100 100 template "" "" child %}        
                </ul>
            </div>
            {% endif %}
        </li>
        {% endif %}

    {% endfor %}
```

Custom language_chooser template:
```

{% load i18n menu_tags %}

{% for language in languages %}
<li class="menu-item location lang {% if current_language == language.0 %} active{% endif %}">
	<a href="{% page_language_url language.0 %}" title="{% trans "Change to language:" %} {{ language.1 }}">{{ language.1 }}</a>
</li>
{% endfor %}
```
Link to site where the issue is located. In the footer. [https://www.eoexecutives.es/es/](https://www.eoexecutives.es/es/)

I feel I should also mention that the footer navigation as it is was working fine before introducing the language_chooser to the template.

### Expected behaviour

Displaying child page titles and links.

### Actual behaviour

Displaying language chooser links.

### Environment

* Python version: 3.5.2
* Django version: 1.11.11
* django CMS version: 3.5.1

**Comment by vxsx** [comment]
I don't see the issue on the link provided. I assume you fixed it? If yes, what was the problem?
