### ISSUE TITLE
Documentation: toolbar introduction 'watch_models' isn't well defined

### ISSUE THREAD

**Issue by geoidesic** [divio/django-cms#6381]
### Summary
http://docs.django-cms.org/en/latest/introduction/toolbar.html#create-the-toolbar

### Expected behaviour
The documentation should explain explicitly what this attribute is used for along with an example of how that might be useful and why it's important

### Actual behaviour
The document defines:
```'watch_models' allows the frontend editor to redirect the user to the model instance```

Reading this, I'm left none the wiser about what this attribute is for or how it works. It's a very generic high-level description which is in no way useful and makes a lot of assumptions about the reader's knowledge.

### Environment

* Python version: 3.6.4
* Django version: 1.11
* django CMS version: 3.5.2

**Comment by evildmp** [comment]
That has been removed from the introduction. It's actually unnecessary. The toolbar introduction is cleaned up and improved in https://github.com/divio/django-cms/pull/6400> `watch_models` and other more advanced aspects will be explained better in the how-to/reference documentation.
