### ISSUE TITLE
Documentation: apphooks error after adding poll

### ISSUE THREAD

**Issue by geoidesic** [divio/django-cms#6395]
### Summary

http://docs.django-cms.org/en/latest/introduction/apphooks.html?highlight=PollListView#apply-the-apphook-to-a-page

After integrating the apphook and selecting poll as the Application for the page and then creating a poll I get this error.

Note that I was able to fix this error by ignoring (undoing) the bit of the tutorial that says:

```
You can now remove the mention of the Polls application (url(r'^polls/', include('polls.urls', namespace='polls'))) from your project’s urls.py 
```

So if I add that url definition back in, then this error vanishes.

I would suggest that the docs should also explain _why_ it is expected that at this point one can remove this URL definition. That would at least help one debug the problem.

### Expected behaviour
The tutorial should be complete enough that you can run it without errors.

### Actual behaviour

After addressing #6394 and adding a new poll I get the following error:

```
Request Method: | GET
-- | --
http://localhost:8000/en/test-polls-and-publisher/
1.11.11
NoReverseMatch
'polls' is not a registered namespace
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/base.py in reverse, line 87
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
3.6.4
['/Users/noeldacosta/Documents/NOEL/projects/arc/fidelity/daft/cms',  '/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip',  '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6',  '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload',  '/Users/noeldacosta/Library/Python/3.6/lib/python/site-packages',  '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages',  '/Users/noeldacosta/Documents/NOEL/projects/arc/fidelity/daft/djangocms-article-drafts',  '/Users/noeldacosta/Documents/NOEL/projects/arc/fidelity/daft/django-polls']
```

### Environment

* Python version: 3.6.4
* Django version: 1.11.11
* django CMS version: 3.5.1

**Comment by evildmp** [comment]
Looks like a mismatch between the versions of the tutorial and the polls application - can't replicate with the latest versions.
