### ISSUE TITLE
Documentation: cmstoolbars concepts are unclear.

### ISSUE THREAD

**Issue by geoidesic** [divio/django-cms#6396]
### Summary

http://docs.django-cms.org/en/latest/how_to/toolbar.html#how-to-extend-the-toolbar

It's not clear how the CMSToolbar system works conceptually from a code-perspective.

### Expected behaviour
 I think a general description of the principles involved would serve as an introduction – such as:

* register and unregister
* when to apply each
* buttons vs. menu items
* what determines which toolbars will display on which URLs

### Actual behaviour
It says: "You can add and remove toolbar items." but never explains how to remove items.
We created a toolbar and register it and it shows up on the polls URL, however others (like Pages cmstoolbar) does not show up for polls – it's not clear how it's determined which one's will be active or not for a given url.

### Environment

* Python version: 3.6.4
* Django version: 1.11.11
* django CMS version: 3.5.1

**Comment by evildmp** [comment]
All these issues should be addressed in Pull Request #6427

**Comment by evildmp** [comment]
Addressed in #6427
