### ISSUE TITLE
Documentation: toolbar watch_models and other properties are not clearly explained

### ISSUE THREAD

**Issue by geoidesic** [divio/django-cms#6398]
http://docs.django-cms.org/en/latest/introduction/toolbar.html?highlight=watch_models#what-this-all-means

These descriptions really aren't sufficient to get any understanding of what these properties do. They need a lot more details.

**Comment by evildmp** [comment]
All these questions should be addressed in Pull Request #6427.

**Comment by evildmp** [comment]
Addressed in #6427
