### ISSUE TITLE
Documentation: apphooks - attaching an application multiple times; has untruths

### ISSUE THREAD

**Issue by geoidesic** [divio/django-cms#6399]
### Summary

The documentation here is inaccurate: http://docs.django-cms.org/en/latest/how_to/namespaced_apphooks.html?highlight=apphook%20instance#define-a-namespace-at-class-level

### Expected behaviour
Perhaps the tutorial section for the Polls should cover this ground also. I.e. http://docs.django-cms.org/en/latest/introduction/apphooks.html

Docs should mirror the real behaviour and should be true. 

Also they should explain the instance mechanism from a UI perspective more closely – i.e. how to create / manage instances, valid / invalid usage.

### Actual behaviour
It states that the `app_name` property must be set to expose the `application instance` field in the `Advanced Settings` for the page. However if you follow the polls example tutorial, this property is not set and yet that field is exposed.

It also states that the `app_name` property will be the default value for that field. This may be true (not sure) but if you don't provide `app_name` there's still a default value in the field, which seems to default to the value of the `name` property.

The documentation also shows an image where there is a field called "Application Configurations". I don't see this field (and it's not described in the documentation), instead I see "Application Instance". 

It's also not clear how this field works. Sometimes when I try to save a page with an instance it says "this instance is already in use" other times not (even though it is already in use). One can create a new instance just by typing in a different string into the "Application Instance" field. However, it's not clear what this means or what effect it has other than passing validation – for example the instance doesn't appear when one edit's the poll.

The docs also state that adding the `app_name` will fix reverse lookup error but this doesn't seem to work. I added in the `app_name` property and I still get the error below. This only occurs on the second instance of the poll, the first (which has the default Application Instance name of `polls`) works fine. The admin UI allows one to add as many instances as one likes – but it's not clear what these mean or what they map to – they don't map to `app_name`, that much seems clear – which is contrary to the docs.

```
NoReverseMatch at /en/test-polls-and-publisher-2/
Reverse for 'detail' not found. 'detail' is not a valid view function or pattern name.
Request Method:	GET
Request URL:	http://localhost:8000/en/test-polls-and-publisher-2/
Django Version:	1.11.11
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'detail' not found. 'detail' is not a valid view function or pattern name.
Exception Location:	/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 497
Python Executable:	/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
Python Version:	3.6.4
Python Path:	
['/Users/geoidesic/stuff/daft/cms',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload',
 '/Users/noeldacosta/Library/Python/3.6/lib/python/site-packages',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages',
 '/Users/geoidesic/stuff/daft/djangocms-article-drafts',
 '/Users/geoidesic/stuff/daft/django-polls']
Server time:	Fri, 1 Jun 2018 15:32:01 +0100

```

### Environment

* Python version: 3.6.4
* Django version: 1.11.11
* django CMS version: 3.5.1

**Comment by evildmp** [comment]
All these questions should be addressed in Pull Request #6427.
