### ISSUE TITLE
Creating a category using News&Blog encountered TypeError

### ISSUE THREAD

**Issue by pancodia** [divio/django-cms#6430]
### Summary

![screen shot 2018-07-02 at 9 32 29 pm](https://user-images.githubusercontent.com/5241979/42193947-7bc3f79e-7e3f-11e8-8709-ba348db46eb5.jpg)

### Expected behaviour

A category named "blockchain" should be created.

### Actual behaviour

Got TypeError

### Environment

![screen shot 2018-07-02 at 9 34 50 pm](https://user-images.githubusercontent.com/5241979/42194005-d02384f8-7e3f-11e8-9223-6f5e5a453eb5.jpg)

The following is the output of `pip freeze`

[pip-freeze.txt](https://github.com/divio/django-cms/files/2157315/pip-freeze.txt)

**Comment by pancodia** [comment]
The above error happened when no value is provided for "slug". When I provided the text value for "slug" in the creation form, there is not error.

![screen shot 2018-07-02 at 9 45 42 pm](https://user-images.githubusercontent.com/5241979/42194341-7071ed40-7e41-11e8-85dd-8de7c6e9142b.jpg)

**Comment by czpython** [comment]
Closing here as this is a bug in aldryn-categories.
Moved to https://github.com/aldryn/aldryn-categories/issues/45
