### ISSUE TITLE
app_manage

### ISSUE THREAD

**Issue by ayershub** [divio/django-cms#6449]
Excuse me, Why app_manage in manage.py can't be found ？

**Comment by czpython** [comment]
manage.py is only used for testing purposes, you'll find the package dependency in the base test requirements.

**Comment by onny** [comment]
@czpython Is this dependency still required? According to https://github.com/django-cms/django-cms/blob/adbcb71be4085b3c69c6d4db6045e58292d7c165/test_requirements/requirements_base.txt#L22
it should be not required anymore?

**Comment by fsbraun** [comment]
@onny Thanks for bringing this up again. Status:
* django-app-manage is still required
* django-better-tests is not

A good opportunity to also let go of django-app-manage...
