### ISSUE TITLE
Structure mode does not expand as the elements grow

### ISSUE THREAD

**Issue by hygull** [divio/django-cms#6474]
I've a Django CMS website with the following requirements (It is in development).

	django-cms>=3.5,<3.6
	djangocms-admin-style>=1.2,<1.3
	django-treebeard>=4.0,<5.0
	djangocms-text-ckeditor>=3.6.0
	djangocms-link>=2.1
	djangocms-style>=2.0
	djangocms-googlemap>=1.1
	djangocms-snippet>=2.0
	djangocms-video>=2.0
	djangocms-column>=1.7
	djangocms-file>=2.0,<3.0
	djangocms-picture>=2.0,<3.0
	easy_thumbnails
	django-filer>=1.3
	Django<2.0
	pytz
	django-classy-tags>=0.7
	html5lib>=0.999999,<0.99999999
	Pillow>=3.0
	django-sekizai>=0.9
	six

It is working, the problem is when I go to Structure mode (by clicking on button available on right), I can see the element until the page fills after that I can't see the way to reach to the elements available at very bottom. There is no scrollbar.
 
Please help me in fixing this problem, I searched a lot but could not find the solution or suggest me any best Django CMS version which does not have this issue (like in previous versions, Structure and content mode was not like in the current version).

@czpython can you please suggest me?

**Comment by czpython** [comment]
Hello @hygull , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.
In this case I also think it would be good to include screenshots.
