### ISSUE TITLE
Django CMS - Admin page permissions per language page

### ISSUE THREAD

**Issue by Konstantin-Bozhkov** [divio/django-cms#6475]
This issue was raised and closed few years ago where you have different users editing different languages without having the permission to edit other languages that they are not aurhorised for.

This issue was closed but doens`t seem it has been resolved. 
The original question was asked here http://stackoverflow.com/questions/19198135/django-cms-permissions-per-language and the issued #2259 and refereneced #4598

Is this still on going issue or it has been resolved or there is a workaround that.
Thanks

**Comment by czpython** [comment]
Hello @Konstantin-Bozhkov , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.
To answer your question, currently there is no per language permissions.
