### ISSUE TITLE
Page.has_view_restrictions

### ISSUE THREAD

**Issue by DylannCordel** [divio/django-cms#6512]
Hi,

I really don't understand [this line](https://github.com/divio/django-cms/blob/2923f0d919913e2cfc3b7aba09dd7e97b31ef21a/cms/models/pagemodel.py#L1501):

```python
restrictions = (
                PagePermission
                .objects
                .for_page(page)
                .filter(can_view=True)
)
```

Why `can_view=True` ? Should not it be `can_view=False` ? Method is has_view_**restrictions**, not has_view_**permissions**. 

Usage exemple:

(with django CMS 3.4 LTS which is also concerned)

**Page tree:**

* Home
* Some page
* Projects
  * A public project => can_view by every one, can_change by members of group "a-public-project"
  * A Private project => can_view (and can_change) by members of group "a-private-project"
  * ...
* Some other page

**Settings:**
```
CMS_PERMISSION = True
CMS_PUBLIC_FOR = 'all'
```

**PagePermissions for concerned project pages :**

(we have a real User instance called "anonymous" which replace the default fake anonymous user to be able to assign specific perms for not authenticated user)  
members of projects groups are also members of a common group "members"

| page | group |  user | can_view | can_change |
| -------- | --------- |  ------- | --------------- | ------------------- |
| a public project | a-public-project | None | :heavy_check_mark:  | :heavy_check_mark: |
| a private project | a-private-project | None | :heavy_check_mark: | :heavy_check_mark: |
| a private project | members | None | :no_entry: | :no_entry: |
| a private project | None | anonymous | :no_entry: | :no_entry: |

With current code:
* when a user which does not belongs to group "a-public-project" try to go on page "a public project", he can't because cms considers that this page has_view_restrictions (but it doesn't: every one can_view this page).
* if this user is anonymous (not autehticated), permissions are not even checked because as cms considers this page has restrictions and user is not authenticated, it `user_can_view_page` just returns False
* when a user which does not belongs to group "a-private-project", he can, because cms considers that this page has not any view restrictions.
* In "permissions" view of this page, when we add a "restriction" (so can_view=True), in "all permissions" fieldset, can_view is marked as "yes" (but it means no : it's considered as a restriction and is also display in "restrictions" fieldset)

On my project, I patched Page Model (I use cms 3.4.x LTS) 

`myapp/apps.py`:
```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.apps import AppConfig
from django.apps import apps


class MyAppConfig(AppConfig):
    name = 'myapp'
    verbose_name = _('My App')

    def ready(self):
        from cms.models import Page
        from cms.models import PagePermission

        def get_view_restrictions(self):
            page = self.get_draft_object()
            return PagePermission.objects.for_page(page=page).filter(can_view=False)
        Page.get_view_restrictions = get_view_restrictions
```

With this patch, permissions work well. But before to create a pull request, I would like to be sure there is not any strong reasons to revert the `can_view` value.

I dig a little. This behaviour (page is considered restricted if there is a can_view Permission set to True...) is old. It seems to be appeared in this commit fd25f6546dc53a8e11e65d99b9b4cdeeca63d4de (8 years ago  )   
@jezdez, do you remember if it was really wanted or just a typo ?

**Comment by czpython** [comment]
Hello @DylannCordel,

The moment you add a can_view page permission, it effectively causes the page to have "view restrictions". Meaning that this page is no longer accessible to anyone except those who have view permissions.

This was designed as a "who can access" this page vs "who can't".

**Comment by DylannCordel** [comment]
Hi @czpython 

To stay short : with this design, could you explain how do you:
* keep "public access" (logged and unlogged users) on a page with only one PagePermission set for a specific group (maintainers) allowing it to change this page.
* restrict access to a group (members) and allow access to an other (maintainers) on the same page ?
