### ISSUE TITLE
Menu with Font Awesome icons

### ISSUE THREAD

**Issue by kristiandrucker** [divio/django-cms#6552]
Hi, is there a way to extend menu child so I can have per page font-awesome icons on the menu?

**Comment by czpython** [comment]
Hello @kristiandrucker , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.
