### ISSUE TITLE
Image in Contributing Translations 404s

### ISSUE THREAD

**Issue by afs2015** [divio/django-cms#6573]
### Summary
When you go to http://docs.django-cms.org/en/latest/contributing/translations.html the image under `Top translations django-cms core:` returns a 404.

### Expected behaviour
An image should be loaded.

### Actual behaviour
Broken image icon appears in Google Chrome and attempting to go to the image link results in a 404.

### Environment
Google Chrome on a Mac.

* Python version:
N/A
* Django version:
N/A
* django CMS version:
Latest

**Comment by vThaian** [comment]
Thanks, @afs2015 for your contribution, we will fix this.
