### ISSUE TITLE
Features : version control??

### ISSUE THREAD

**Issue by logicnextPramod** [divio/django-cms#6588]
I am not able to figure out where is version control.

**Comment by czpython** [comment]
Hello @logicnextPramod , please make sure to submit questions/support within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).
You can find additional information on our [support](https://www.django-cms.org/support) page.

django CMS does not come with built-in versioning.

**Comment by logicnextPramod** [comment]
Thank you for your quick reply.
Actually in feature list it shows version control thats why i came up with
this issue.
It is misleading. Please remove this line.
Thanks
