### ISSUE TITLE
django-cms 3.6.0rc1 disappeared from pip

### ISSUE THREAD

**Issue by paffare** [divio/django-cms#6594]
### Summary

After running django-cms 3.6.0rc1 from pip successfully for a month our builds suddenly started failing due to this version unavailable.

Does anyone know why rc1 is no longer available on pip, and also why rc2 is not available either?

### Environment

* Python version: 3.6
* Django version: 2.1.5
* django CMS version: 3.6.0rc1

**Comment by vThaian** [comment]
Hey @paffare 

RC1 and RC2 for django-cms 3.6.0 are available via devpi.

We are planning to release the final version of 3.6.0 in next days.

Future release candidates will be available via PyPi.
