### ISSUE TITLE
Page permissions form (table) not rendering.

### ISSUE THREAD

**Issue by skyforest** [divio/django-cms#6689]
### Summary
Not being able to see or edit the `page permissions` at menu location:  Page > Permissions > Page Permissions (table). I can see the form/table in the DOM with class='form-row row1 empty-form' class="pagepermission_set-2-empty''. This is being done using a superuser account.

### Expected behaviour
I expected to be able to add specific page permissions to a user in this section but nothing appears below the table headers.

### Actual behaviour
No rendering of table/form to edit page permissions.

### Environment

* Python version: 3.6.7
* Django version: 1.11.20
* django CMS version: 3.6.0

**Comment by skyforest** [comment]
Update - I moved down to django-cms==3.5.3 and the table renders correctly...

**Comment by rolandf** [comment]
> Update - I moved down to django-cms==3.5.3 and the table renders correctly...

I did a diff between 3.6.0 and 3.5.3 and was not able to see much changes in the code related to permissions.
Did you had a chance look for a solution ?
I'm too long in my project to change of CMS so I have a big requirement and it is to have permission working and easy to set/change.
If you want we can collaborate to find a fix.

**Comment by rolandf** [comment]
Ok, I'm making progress slowly but I'm in the right direction I think.

I created the following management command to debug my installation:

`from django.core.management.base import BaseCommand, CommandError
from django.core.management import call_command
from cms.api import create_page, add_plugin
from filer.models.filemodels import File
import locale

from django.contrib.auth.models import User, Group
from cms.api import Page, PageUser
from cms.models.permissionmodels import PagePermission
from cms.models import ACCESS_PAGE, ACCESS_DESCENDANTS, ACCESS_CHILDREN, ACCESS_PAGE_AND_CHILDREN, ACCESS_PAGE_AND_DESCENDANTS



class Command(BaseCommand):
    args = '<no args needed>'
    help = 'Create test permissions'

    def handle(self, *args, **options):
        # These are the full set of available permissions. We exclusively want to test can_view.
        view_perms = {
            'can_change': False,
            'can_add': False,
            'can_delete': False,
            'can_change_advanced_settings': False,
            'can_publish': False,
            'can_change_permissions': False,
            'can_move_page': False,
            'can_view': True,
        }

        p = Page.objects.filter(title_set__title='Page 2')
        u = User.objects.get(pk=4)

        groups = u.groups.all()

        for pageToPermit in p:
            perm_a, _ = PagePermission.objects.get_or_create(grant_on=ACCESS_PAGE_AND_DESCENDANTS, group=groups[0], page=pageToPermit, **view_perms)
            perm_a.save()`

and I got this while before everything related to the page was empty

![permissions_screenshot](https://user-images.githubusercontent.com/189596/62427268-d7c61500-b6f0-11e9-9275-32b2108ed7f1.png)

I think that there must be an Add button missing

**Comment by plutosrings** [comment]
@rolandf You're awesome man, I'm dealing with this issue with my site too
setup:
    -  django 1.11.12
     - django-cms==3.6.0
     - python 3.7.4
    
And cannot add restrictions/permissions directly to pages. Love this framework and want to see this working. I'll give your code above a shot tomorrow at some point.  Thank you for providing it!

**Comment by rolandf** [comment]
According to this thread in Django Cms google group, the issue doesn't seem to be linked to a particular version of Django-Cms but to a version of Django:

https://groups.google.com/d/msg/django-cms-developers/ApZ4seVaFc8/zTttVmBMBAAJ

**Comment by skyforest** [comment]
Interesting... I am going to read through the Django CMS and Django release notes to see if anything stands out. Will update if I find anything to help us.

**Comment by rolandf** [comment]
Unfortunately I don't do javascript but maybe related to jquery versions if you have multiple versions of the library ? (One for django, an other one for DjangoCms if you use Bootstrap ?)

django/contrib/admin/static/admin/js/change_form.js that is not triggered ?

**Comment by skyforest** [comment]
> Unfortunately I don't do javascript but maybe related to jquery versions if you have multiple versions of the library ? (One for django, an other one for DjangoCms if you use Bootstrap ?)
> 
> django/contrib/admin/static/admin/js/change_form.js that is not triggered ?

That could make sense because I could still manually display the table by removing display:false; in the html divs when I originally discovered this issue. Let me look into that as well. Good thought.

**Comment by rolandf** [comment]
> > Unfortunately I don't do javascript but maybe related to jquery versions if you have multiple versions of the library ? (One for django, an other one for DjangoCms if you use Bootstrap ?)
> > django/contrib/admin/static/admin/js/change_form.js that is not triggered ?
> 
> That could make sense because I was able to still manually display the table by removing display:false; in the html divs when I originally discovered this issue. Let me look into that as well. Good thought.

I found this:

.empty-form {
	display: none; 
}

once I find where it's defined and where it's generated I will better understand this too.

**Comment by rolandf** [comment]
It's not change form, I was able to enable it and there was a popup that appeared, it's not this.
I believe it's more in

django/contrib/admin/static/admin/js/inlines.js

**Comment by plutosrings** [comment]
.empty-form {
    display: none;
}
is defined in django/contrib/admin/static/css/forms.css

**Comment by rolandf** [comment]
Today I used djangocms-installer to install Django-cms with a lot of distinct config with variation of django version and django-cms version. Django 1.11 has a problem. Django-cms 3.5 with Django 1.9 is OK, Django-cms 3.6 with django 2.1 is ok too. I will not spend time trying to support Django 1.11, I prefer to use 2.1 and continue from there.

**Comment by skyforest** [comment]
> Today I used djangocms-installer to install Django-cms with a lot of distinct config with variation of django version and django-cms version. Django 1.11 has a problem. Django-cms 3.5 with Django 1.9 is OK, Django-cms 3.6 with django 2.1 is ok too. I will not spend time trying to support Django 1.11, I prefer to use 2.1 and continue from there.

Yep, you are correct. Just upgraded my dependencies to latest versions of Django / Django CMS and the permissions system seems to work as intended. I am going to close this issue and conclude our issue was a versioning problem. Thanks for all the help and happy coding!

**Comment by plutosrings** [comment]
Will django 2.1 be added to the list of officially supported versions for django-cms, right now the docs only say Django 1.8, 1.9 or 1.10 on the installation requirements here: http://docs.django-cms.org/en/release-3.5.x/introduction/install.html (the latest & 3.6 pages don't work currently)
