### ISSUE TITLE
Structure and content modes are outdated in the docs

### ISSUE THREAD

**Issue by DmytroLitvinov** [divio/django-cms#6694]
### Summary

Seems like [docs](https://github.com/divio/django-cms/blob/release/3.6.x/docs/user/tutorial/structure-content-modes.rst) is outdated for djangoCMS 3.6 because in the cms_toolbar we don't have explicit switcher from Structure mode to Content mode and vice versa. 

### Expected behaviour

See at the top of the site(in djangocms toolbar) switcher from Structure mode to Content mode and vice versa. 
![image](http://docs.django-cms.org/en/latest/_images/structure-content1.png)

### Actual behaviour

See only one button which related to Structure mode.
![image](https://user-images.githubusercontent.com/16066485/60255899-438ab600-98d9-11e9-9199-6913c88590dd.png)
![image](https://user-images.githubusercontent.com/16066485/60256110-9f553f00-98d9-11e9-8c8d-1ec43f4d538f.png)

### Environment

* Python version: 3.6
* Django version: 2.1
* django CMS version: 3.6

#### Additional information
Related to issue https://github.com/divio/django-cms/issues/3423

@FinalAngel @czpython I am ready to prepare PR for outdated doc if you need help.

**Comment by FinalAngel** [comment]
That be great @DmytroLitvinov :)

**Comment by tarasyyyk** [comment]
Hi, I'm newbie to Django CMS. There aro issues I found in documentation:
![1  Installing django CMS — django cms 3 6 0 documentation 2019-07-06 15-23-30](https://user-images.githubusercontent.com/20100011/60756137-9dd6f580-a002-11e9-95c8-b9e6120af007.jpg)
![1  Installing django CMS — django cms 3 6 0 documentation 2019-07-06 15-20-22](https://user-images.githubusercontent.com/20100011/60756138-9dd6f580-a002-11e9-9806-88be026efb8b.jpg)

**Comment by DmytroLitvinov** [comment]
Hello @tarasyyyk ,

You should create a separate issue ticket for that case.
Also, it would be great, if you could provide PR for fixing this issue.
