### ISSUE TITLE
djangocms 3.7.1, django 2.2, python 3.7.2 mark_safe no longer in django.utils.text

### ISSUE THREAD

**Issue by woodz-** [divio/django-cms#6777]
Hi there,

I've just upgraded to those versions mentioned  in headline. And I required to do a small fix in 
_djangocms_attributes_field/widgets.py_:

`#from django.utils.text import mark_safe`
`from django.utils.safestring import mark_safe`

If I wouldn't have done this, I sill would receive:
`ImportError: cannot import name 'mark_safe' from 'django.utils.text'`

Greetings

**Comment by Zmeylol** [comment]
@woodz- This seems to be fixed in https://github.com/divio/djangocms-attributes-field/pull/32, try to update `djangocms-attributes-field` package.

**Comment by woodz-** [comment]
@Zmeylol: confirmed! Shouldn't such update be an automatism of the djangocms update process?
