### ISSUE TITLE
[BUG]: django-formtools==2.2 breaking python 2.7 installations

### ISSUE THREAD

**Issue by s-weigand** [divio/django-cms#6779]
## Description
Yesterday `django-formtools` made a new release (2.2) with is python3 only, which is why `django-cms` breaks on python 2.7 installations.

## Solution 
Pin the max version of `django-formtools<2.2` for installations on python 2.7 .

**Comment by FinalAngel** [comment]
@s-weigand we recommend pinning the requirement in your project as we can't add the restriction to the CMS itself.

**Comment by s-weigand** [comment]
> 
> 
> @s-weigand we recommend pinning the requirement in your project as we can't add the restriction to the CMS itself.

Well you could i.e. by adding the following to `setup.py`.
```python
import sys
if sys.version_info < (3,):
    formtools_index = INSTALL_REQUIREMENTS.index('django-formtools>=2.1')
    INSTALL_REQUIREMENTS[formtools_index] = 'django-formtools>=2.1, <2.2'
```

Anyway, since by now python 2.7 is officially dead, I hope no one is using it anyway.
