### ISSUE TITLE
cannot install. CommandError: 'xxx' conflicts with the name of an existing Python module and cannot be used as a project name. Please try another name. 

### ISSUE THREAD

**Issue by simonm3** [divio/django-cms#6786]
Followed exactly the instructions in the docs but when I get to "djangocms mysite" there is an error every time. Does not matter what I call the project. I am using python 3.7 on windows10

CommandError: 'xxx' conflicts with the name of an existing Python module and cannot be used as a project name. Please try another name.

**Comment by simonm3** [comment]
This is probably a documentation error. Previous version uses "djangocms -p . mysite" which works. The current documentation just says "djangocms mysite" which fails.

**Comment by yakky** [comment]
@simonm3 could you open the issue on the installer repo https://github.com/nephila/djangocms-installer ?
I can't reproduce it in the latest version

**Comment by simonm3** [comment]
moved issue to installer

**Comment by yakky** [comment]
For future reference issue is https://github.com/nephila/djangocms-installer/issues/359
