### ISSUE TITLE
Unable to make first new page

### ISSUE THREAD

**Issue by Sweetbarrow** [divio/django-cms#6787]
I'm trying to make a site running with DjangoCMS on Windows Server Azure VM B1ms(1 vcore 2GB RAM).
But when I try to make the first page from 'Add New Page' wizard, the error message below has shown.
I'm using Python 3.8.1 x64 with venv and my DjangoCMS version is 3.7.1

```
Request Method: POST https://pdmnu.com/ko/cms_wizard/create/
2.2.9 TemplateSyntaxError
'menu_tags' is not a registered tag library. Must be one of:

(tag list...skip)

C:\inetpub\python\lib\site-packages\django\template\defaulttags.py in find_library, line 1023
C:\inetpub\python\Scripts\python.exe
3.8.1
['.',  'C:\\inetpub\\wwwroot',  'C:\\Program Files\\Python38\\python38.zip',  'C:\\Program Files\\Python38\\DLLs',  'C:\\Program Files\\Python38\\lib',  'C:\\Program Files\\Python38',  'C:\\inetpub\\python',  'C:\\inetpub\\python\\lib\\site-packages']
```

But it's okay on my desktop(running Windows 10 x64 1809).
What should I do to fix this?

**Comment by yakky** [comment]
have you added `menus` to `INSTALLED_APPS`?

**Comment by Sweetbarrow** [comment]
As I mentioned, I didn't edit any of original source of DjangoCMS.
I used pip djangocms-installer.
But it was solved after I completely uninstall Python and reinstall it.

2020년 1월 3일 (금) 오후 6:51, Iacopo Spalletti <notifications@github.com>님이 작성:

**Comment by yakky** [comment]
Sorry I missed that part of the comment.
Closing the issue, then

**Comment by Sweetbarrow** [comment]
Okay, thanks.

2020년 1월 3일 (금) 오후 7:01, Iacopo Spalletti <notifications@github.com>님이 작성:
