### ISSUE TITLE
Help on page plugins and ajax on plugins param

### ISSUE THREAD

**Issue by ciskshitij** [divio/django-cms#6805]
Hi, 
I have 2 questions.
1. I am creating a plugin and I want a dependent field in the config with Ajax how I can do that. for ex. If I have a country and state dropdown in the config on plugin I want to populate the state drop-down bases on the country selected.

2. Can I get all the plugins and their content in a page? basically I want to add a condition based on plugin A's content which is loaded on the page.

Thanks in Advance!

**Comment by pupattan** [comment]
> 1. I am creating a plugin and I want a dependent field in the config with Ajax how I can do that. for ex. If I have a country and state dropdown in the config on plugin I want to populate the state drop-down bases on the country selected.

i have the same question

**Comment by FinalAngel** [comment]
please ask your plugin-specific question in https://groups.google.com/g/django-cms

thank you 👏
