### ISSUE TITLE
Push is not a function (BUG)

### ISSUE THREAD

**Issue by agajankush** [divio/django-cms#6816]
## Description

When I try to add same placeholder twice in different positions on same page i get this error 
![image](https://user-images.githubusercontent.com/16169801/76243381-9d849f00-620e-11ea-8ffc-6877822ffffb.png)
after i click on edit hamburger for the first time.

The weird part is its only happens for the first time and then it starts working again.

## Steps to reproduce

Click on the edit hamburger after adding the placeholder.

## Expected behaviour

Should open the edit sidebar structure the first time.

**Comment by FinalAngel** [comment]
please provide additional information on what versions you are using :)
