### ISSUE TITLE
How to avoid SITE_ID to be set in settings?

### ISSUE THREAD

**Issue by 1st** [divio/django-cms#6836]
We are using Django CMS for a while, and need to migrate our website to a multi-site implementation with Django Sites framework. We wanna use [CurrentSiteMiddleware](https://docs.djangoproject.com/en/2.1/ref/contrib/sites/#site-middleware) to detect which site is used (based on subdomain). In result we will have a `request.site.id` set by middleware that is based on the current user request to our website.

I've tried to find the best way how to use Django CMS without forking it, and didn't find a good way how to do this.

What do we actually need:
 * each **Page** can be used on the current Site, or **on few sites** at the same time. To do so, Django documentation recommends to add **M2M** FK to the **Site** model from each Article object (in our case, it's the Page object). But the `TreeNode` has the FK to the `Site` model, that means that only one Page can be mapped to a single site. But we need to map one Page to one or few sites at the same time.
 * we need to use Sites framework, because Django has it and creators of Django use it on their projects (and it's for what is was designed - to map some object to one or few sites at the same time). In my opinion it's very clear approach to have a multi-site solution running on the same instance of the web app.
 * we need to have a single instance of the app, because we have shared plugins that we need to use across multiple organisations (each organisations has it's own Site on subdomain).
 * we plan to have hundreds of organisations using our shared codebase, and it's unable to run a new instance for each new subdomain. Also it's harder in maintenance, upgrading, etc. But looks that Django CMS in current implementation is able to work only per one instance with set `SITE_ID` in the `settings.py` file.
 * when we remove `SITE_ID` definition from `settings.py`, Django can't start web server because Django CMS uses `get_current_site()` and `get_site_id()` -- trying load `SITE_ID` value from the settings file. I'm trying to mock such usages, but wanna to find a better approach for this.

Please, help us to find the way how to continue use of Django CMS, without writing our own CMS-like bicycle solution. We generally like Django CMS and wanna continue use it in our 5-years old social project.

Will wait for your reply.

**Comment by 1st** [comment]
Also asked this question here: https://stackoverflow.com/questions/61018518/django-cms-how-to-avoid-site-id-to-be-set-in-settings

**Comment by FinalAngel** [comment]
thank you 👍

**Comment by amanpreet-98888** [comment]
Hi @FinalAngel - did you find any solution? I tried using custom middleware to update settings.SITE_ID on every request. It works for subdomains, but in production, when the load increases, I encounter cross-site content leak issues across multiple sites.  

so do you have any solution for that I can use multi sites without dynamically change settings.SITE_ID at runtime (which is global)?
CC @1st
