### ISSUE TITLE
ImportError when running djangocms. python_2_unicode_compatible

### ISSUE THREAD

**Issue by uilhao** [divio/django-cms#6839]
## Description
Running djangocms will fail with a fatal error

File "../env/lib/python3.7/site-packages/djangocms_snippet/models.py", line 9, in <module>
    from cms.utils.compat.dj import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'cms.utils.compat.dj'

## Steps to reproduce
Just run djangocms sitename

## Expected behaviour
Installation should complete

## Actual behaviour
Fails to install

## Additional information
Python 3.7.7
Django 3.0.5
django-cms 3.7.2
djangocms-installer 1.2.1

**Comment by yakky** [comment]
Please check with djangocms-installer 1.2.2 which has just being release and which provides Django 3.0 support (along with django CMS 3.7.2)

**Comment by patagoniapy** [comment]
I am having the same issue. @yakky , what do you mean by check with `djangocms-installer`? Will installing this package solve this issue?

**Comment by uilhao** [comment]
djangocms-installer 1.2.2 fixes the issue. thank you!

**Comment by pupattan** [comment]
Facing the same issue

**Comment by yakky** [comment]
@pupattan @patagoniapy 
If using djangocms-installer using djangocms-installer will fix the issue
If not using djangocms-installer you need updated addons for django CMS 3.7.2
