### ISSUE TITLE
Please fix a conflict in your bundle JS file

### ISSUE THREAD

**Issue by 1st** [divio/django-cms#6842]
In 3.5.x branch you have next file that has conflict.
https://github.com/divio/django-cms/blob/release/3.5.x/cms/static/cms/js/dist/3.5.3/bundle.admin.base.min.js

I use this version for my local development, and found this problem that in Django admin Django CMS Page show no content at all.

Please fix this conflict, even if this version old and not supportable anymore.
Thank you.

**Comment by 1st** [comment]
OK, I've found a workaround for Django 1.11.x version yo clone the latest release version using `git checkout tags/3.5.2`. But anyway, it's not god that in your repo you have files with merge conflicts, and they are committed.

**Comment by FinalAngel** [comment]
@1st this has been fixed in the latest releases of django CMS 3.4-3.7. Thank you for pointing this out!
