### ISSUE TITLE
3.7.2 release breaks a bunch of third party plugins

### ISSUE THREAD

**Issue by paiuolo** [divio/django-cms#6843]
Release notes follows:

Bug Fixes
migrated from django.utils.six to the six package
migrated from django.utils.lru_cache to functools.lru_cache
migrated from render_to_response to render in cms.views
added cms.utils.compat.dj.available_attrs
added --force-color and --skip-checks in base commands when using Django 3
replaced staticfiles and admin_static with static
replaced djangocms-helper with django-app-helper

Are those bug fixes? What kind of "bug" do they fix?

**Comment by FinalAngel** [comment]
django compatibility issues :)
