### ISSUE TITLE
TemplateSyntaxError at /en/admin/login/ when starting server

### ISSUE THREAD

**Issue by edraobdu** [divio/django-cms#6844]
## Description

Following the installation tutorial (http://docs.django-cms.org/en/latest/introduction/01-install.html#installing-django-cms) and found a TemplateSyntaxError at /en/admin/login/ when running the server for the first time. This guy also have the same error:
https://stackoverflow.com/questions/61417238/templatesyntaxerror-at-en-admin-login-staticfiles-is-not-a-registered-tag-li

## Steps to reproduce

After downloading the installer ```pip install djangocms-installer``` (new virtual environment python 3.7.3) creating a folder, and run the new project command ```djangocms mysite```, it starts creating all the required files, creates the django project, make migrations, etc etc, after that, I run ```python manage.py runserver``` as the tutorial suggests. Go to http://127.0.0.1:8000 and get the error

## Expected behaviour

Should expect to be redirected to the admin login page as the tutorial suggests:

> Open http://localhost:8000/ in your browser, where you should be invited to login, and then 
> create a new page.

## Actual behaviour

Instead I get the following error:

```
TemplateSyntaxError at /en/admin/login/

'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_style_tags
admin_tree
admin_tree_list
admin_urls
cache
cms_admin
cms_alias_tags
cms_js_tags
cms_static
cms_tags
djangocms_text_ckeditor_tags
easy_thumbnails_tags
filer_admin_tags
filer_image_tags
filer_tags
i18n
l10n
log
menu_tags
sekizai_tags
snippet_tags
static
thumbnail
tz
```

## Additional information

![Screenshot from 2020-04-24 18-08-01](https://user-images.githubusercontent.com/31775663/80263571-a44c6180-8656-11ea-8366-5c5b42cb05fe.png)

![Screenshot from 2020-04-24 18-07-56](https://user-images.githubusercontent.com/31775663/80263579-ab736f80-8656-11ea-9bc8-7693546cfa7e.png)

**Comment by PanosTrak** [comment]
The same also happens on me!
From what i searched this looks like the `{% load staticfiles %}` has be changed to `{% load static %}` in django 3, i went to the source and replaced them where it needed and then i could login but many things was broken and got the following error:
`The form could not be loaded. Please check that the server is running correctly.`

**Comment by pupattan** [comment]
I am also facing this issue.
Its with the latest version 3.7.2  due to change to django 3.0

**Comment by yakky** [comment]
@edraobdu @pupattan @PanosTrak we are working on a fix on djangocms-installer
A release should be available really soon

**Comment by yakky** [comment]
I am closing the bug here as it's a djangocms-installer one
Please followup at https://github.com/nephila/djangocms-installer/issues/366

**Comment by yakky** [comment]
Expect djangocms-installer 1.2.3 release in the next hours
Thanks all for reporting this issue

**Comment by yakky** [comment]
@edraobdu @pupattan @PanosTrak djangocms-installer 1.2.3 released with fix

**Comment by edraobdu** [comment]
Thank you so much
