### ISSUE TITLE
3.7.2 shows error  from_db_value() missing 1 required positional argument: 'context'

### ISSUE THREAD

**Issue by pupattan** [divio/django-cms#6845]
I am getting the following error while page renders
![image](https://user-images.githubusercontent.com/19246595/80356483-26c36400-8897-11ea-9394-e289630554c9.png)

![image](https://user-images.githubusercontent.com/19246595/80356701-730ea400-8897-11ea-9a11-31925f897973.png)

The same code works find in 3.7.1

**Comment by pupattan** [comment]
Looks like some issues with the following in the latest version
from djangocms_text_ckeditor.fields import HTMLField
The pages - plugins  using the above field showing error

**Comment by pupattan** [comment]
https://github.com/divio/djangocms-text-ckeditor/issues/522

**Comment by remoover** [comment]
I HAVE SAME ISSUE !!! PLEASE HELP !!!

**Comment by FinalAngel** [comment]
have you tried upgrading to the latest cms version?

**Comment by pupattan** [comment]
This is working fine in latest version
