### ISSUE TITLE
Potential dependency conflicts between django-cms and django

### ISSUE THREAD

**Issue by NeolithEra** [divio/django-cms#6852]
Hi, as shown in the following full dependency graph of **_django-cms_**, **_django-cms_** requires **_django <3.0,>=1.11_** ， while the installed version of **_django (2.2.12)_** ，**_django-classy-tags 1.0.0_** requires **_django >=1.11_**.
According to Pip's _“first found wins”_ installation strategy, **_django 2.2.12_** is the actually installed version.
Although the first found package version **_django 2.2.12_** just satisfies the later dependency constraint （**_django >=1.11_**), it will easily cause a build failure once the updated **_django-classy-tags_** introduces a higher version of **_Django_**.
According to the release history of **_django-classy-tags_**, it habitually upgrates **_Django_** in its recent releases. For instance, **_django-classy-tags 0.6_** upgrated **_Django_**’s constraint from **_>=1.2 to >=1.3_**,and **_django-classy-tags 0.9_** upgrated **_Django_**’s constraint from **_>=1.3 to >=1.11_**. 

### Dependency tree
```
django-cms - 3.7.1
| +- django(install version:2.2.12 version range:<3.0,>=1.11)
| | +- pytz(install version:2019.3 version range:*)
| | +- sqlparse(install version:0.3.1 version range:*)
| +- django-classy-tags(install version:1.0.0 version range:>=0.7.2)
| | +- django(install version:2.2.12 version range:>=1.11)
| | | +- pytz(install version:2019.3 version range:*)
| | | +- sqlparse(install version:0.3.1 version range:*)
| | +- six(install version:1.14.0 version range:*)
| +- django-formtools(install version:2.2 version range:>=2.1)
| | +- django(install version:2.2.12 version range:>=1.11)
| | | +- pytz(install version:2019.3 version range:*)
| | | +- sqlparse(install version:0.3.1 version range:*)
| +- django-sekizai(install version:1.1.0 version range:>=0.7)
| | +- django(install version:2.2.12 version range:>=1.11)
| | | +- pytz(install version:2019.3 version range:*)
| | | +- sqlparse(install version:0.3.1 version range:*)
| | +- django-classy-tags(install version:1.0.0 version range:>=0.9.0)
| | | +- django(install version:2.2.12 version range:>=1.11)
| | | | +- pytz(install version:2019.3 version range:*)
| | | | +- sqlparse(install version:0.3.1 version range:*)
| | | +- six(install version:1.14.0 version range:*)
| | +- six(install version:1.14.0 version range:*)
| +- django-treebeard(install version:4.3.1 version range:>=4.3)
| +- djangocms-admin-style(install version:1.5.0 version range:>=1.2) 
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Lose the version range of **_django_** to be **_>=1.11_**.
2.	Remove your direct dependency **_django_**, and use the **_django_** transitively introduced by **_django-classy-tags_**.
@vxsx Which solution do you prefer, 1 or 2 ?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by yakky** [comment]
releases of django CMS and django-classy-tags are usually made in coordination, so I don't think there is any confilict between them

**Comment by NeolithEra** [comment]
@yakky Thanks for your feedback. If **_django-cms_** always upgrades **_django-classy-tags_** in its new releases, please ignore my issue. Just a warm prompt for the potential dependency conflicts between django-cms and django.
