### ISSUE TITLE
Creating pages programmatically takes some time to appear in the menu

### ISSUE THREAD

**Issue by pupattan** [divio/django-cms#6863]
Hi,

I am creating Pages programmatically using create_page api function after migrate (fresh DB)
After creating pages when i run the app, the menus are not showing the menu immediately.

I have cache disabled 

CMS_PAGE_CACHE = False
CMS_PLACEHOLDER_CACHE = False
CMS_PLUGIN_CACHE = False

Some menus are showing in published pages. But when i login with admin (not edit mode) they are not showing

**Comment by jrief** [comment]
Did you publish the pages? Just creating pages, leaves them in unpublished state.

**Comment by pupattan** [comment]
Its visible on published pages without admin login. But when i login through admin. Menus are not showing on published pages

**Comment by FinalAngel** [comment]
@pupattan are the parent pages published? Can you check inside the page tree that everything is green? Please provide additional information on steps to reproduce and which versions (django/python/django CMS) as the ticket template suggests. Afterwards, we can re-open the issue.
