### ISSUE TITLE
Unexpected caching 

### ISSUE THREAD

**Issue by pupattan** [divio/django-cms#6872]
I have model SiteInfo which has a one to one relation with django.contrib.sites.models.Site
```
class SiteInfo(models.Model):
    site = models.OneToOneField(Site, on_delete=models.CASCADE, related_name="site_info")
    data = models.CharField(max_length=10, null=True, blank=True)

```
In templates i am using {{request.site.name}} {{request.site.site_info.data}}
If i change Site.name from admin panel its immediately updating the name in the template.
But when i change SiteInfo.data it takes 2 3 minutes time to update.
I have all caching disabled

**Comment by pupattan** [comment]
Another caching issue: 
When I create a new page (with navigation menu enabled) it does not appear on navigation the menu immediately even though i publish the pages. It takes some random time to appear. By mean time it shows in the edit mode

**Comment by FinalAngel** [comment]
Hello @pupattan 👋 , please ask your question inside the [django CMS users](https://groups.google.com/g/django-cms) group. Once confirmed by the community please propose an issue in the necessary format to tackle the problem,

Thank you!
