### ISSUE TITLE
+ / a shortcut not working

### ISSUE THREAD

**Issue by pupattan** [divio/django-cms#6890]
+ / a shortcut not working.
It should open "Add Plugin" modal i suppose. But nothing is working as such

**Comment by FinalAngel** [comment]
@pupattan it should work. You just need to make sure that the structure-mode is selected.

* Press "f > p" to activate placeholder selection mode
* Press "Enter" to navigate through the plugins

Then you can use "a" to add plugins, edit etc. If you want to add a plugin to the placeholder simply skip step 2 and just type "a".

Here a screencast:
![2020-08-26 15 32 30](https://user-images.githubusercontent.com/270307/91309914-7ff1c480-e7b1-11ea-9979-f154905aa65e.gif)
