### ISSUE TITLE
How can use Django-CMS as an app in existed Django project?

### ISSUE THREAD

**Issue by AhmedSalam22** [divio/django-cms#6891]
sorry for bother I have searched How we can use Django-CMS as an app in existed Django project? but I couldn't find any resources

**Comment by FinalAngel** [comment]
@AhmedSalam22 you simply plugin django-cms as any other app, add the necessary configuration ([see documentation](http://docs.django-cms.org/en/latest/how_to/install.html)) and configure your URLs to include the cms at a specific point. e.g. /cms/
