### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by AhmedSalam22** [divio/django-cms#6893]
I am trying to install Django-CMS Manually I just follow this documentation as it is
http://docs.django-cms.org/en/latest/how_to/install.html#using-cms-check-for-configuration

I use Django 3.0.9
and django-cms==3.7.4
![Screenshot (297)](https://user-images.githubusercontent.com/35177448/91580691-bfedae80-e94d-11ea-806b-0111232e66fa.png)

**Comment by FinalAngel** [comment]
@yakky will this also be fixed in #6886 ?

**Comment by yakky** [comment]
@FinalAngel yes
@AhmedSalam22 the issue description says Django 3.0.9, but I see Django 3.1 in the requirements file in the screenshot.

Django 3.1 support is available in 3.8.0rc1

Or you can downgrade to django 3.0.9

**Comment by AhmedSalam22** [comment]
thank you so much
